# Experiment 5: Color-Textured Image Enhancement Pipeline (balanced dataset)

Eksperimen ini berfokus pada mencapai akurasi 80%+ pada dataset awan yang diratakan dengan mengombinasikan:
1. **Image Enhancement (CLAHE pada HSV + Gaussian Blur)** untuk memperjelas perbedaan kontras antara langit dan awan serta mengurangi noise.
2. **RGB/Color-based Extraction (HSV Stats & Histograms, serta NRBR Stats & Histograms)** untuk menangkap komponen warna biru langit dan putih/abu-abu awan.
3. **Texture-based Extraction (GLCM & LBP)** untuk menangkap pola tekstur mikro seperti riak altocumulus, wisps cirrus, dan kegelapan cumulonimbus.
4. Penggunaan **dataset seimbang** (`max_per_class=1250` yang di-split 80/20 menjadi 1000 train dan 250 test) untuk menghindari akurasi semu.

In [1]:
import sys
sys.path.append('..')  # supaya src/ bisa diimport dari notebooks/

import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from scipy.stats import skew, kurtosis, entropy
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from skimage.feature import graycomatrix, graycoprops
from src.loader import get_dataset_root, load_dataset
from src.image_processing import *

EXPERIMENT_NAME = "experiment5"

c:\Users\Mahesa\miniconda3\envs\imgproc\Lib\site-packages\cupy\_environment.py:284: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(

CuPy tidak aktif atau tidak berfungsi (fallback ke CPU/NumPy): Failed to find CUDA headers. Please install CUDA toolkit headers (e.g., pip install cupy-cuda12x[ctk]) or specify CUDA_PATH environment variable.

## Data Loading (Balanced to Max 1250 per Class)

In [2]:
DATASET_ROOT = get_dataset_root()
# Muat gambar warna (color=True) agar ekstraksi HSV dan NRBR bisa dilakukan
# Default max_per_class=1250 dan target_size=(256, 256) otomatis digunakan
images, labels, filenames = load_dataset(DATASET_ROOT, target_size=(256, 256), color=True)
print(f"Dataset loaded: {len(images)} gambar warna, {len(set(labels))} kelas")

Environment: Lokal
DATASET_ROOT dari .env: D:\INFORMATICS\SEMESTER 4\IMAGE PROCESSING\Praktikum\Project\GCD

Loading altocumulus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading altocumulus:   5%|▌         | 63/1250 [00:00<00:01, 615.47it/s]

Loading altocumulus:  10%|█         | 126/1250 [00:00<00:01, 623.72it/s]

Loading altocumulus:  15%|█▌        | 189/1250 [00:00<00:01, 609.79it/s]

Loading altocumulus:  20%|██        | 251/1250 [00:00<00:01, 605.31it/s]

Loading altocumulus:  25%|██▍       | 312/1250 [00:00<00:01, 606.10it/s]

Loading altocumulus:  30%|██▉       | 373/1250 [00:00<00:01, 592.72it/s]

Loading altocumulus:  35%|███▍      | 436/1250 [00:00<00:01, 600.09it/s]

Loading altocumulus:  40%|████      | 501/1250 [00:00<00:01, 611.75it/s]

Loading altocumulus:  45%|████▌     | 568/1250 [00:00<00:01, 628.22it/s]

Loading altocumulus:  51%|█████     | 636/1250 [00:01<00:00, 641.78it/s]

Loading altocumulus:  56%|█████▌    | 701/1250 [00:01<00:00, 640.29it/s]

Loading altocumulus:  61%|██████▏   | 766/1250 [00:01<00:00, 621.49it/s]

Loading altocumulus:  66%|██████▋   | 830/1250 [00:01<00:00, 622.04it/s]

Loading altocumulus:  71%|███████▏  | 893/1250 [00:01<00:00, 612.66it/s]

Loading altocumulus:  76%|███████▋  | 955/1250 [00:01<00:00, 574.49it/s]

Loading altocumulus:  81%|████████  | 1013/1250 [00:01<00:00, 566.49it/s]

Loading altocumulus:  86%|████████▌ | 1074/1250 [00:01<00:00, 573.95it/s]

Loading altocumulus:  91%|█████████ | 1134/1250 [00:01<00:00, 581.37it/s]

Loading altocumulus:  96%|█████████▌| 1200/1250 [00:01<00:00, 603.77it/s]

Loading cirrus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading cirrus:   5%|▍         | 62/1250 [00:00<00:01, 618.23it/s]

Loading cirrus:  10%|█         | 131/1250 [00:00<00:01, 645.39it/s]

Loading cirrus:  16%|█▋        | 204/1250 [00:00<00:01, 673.93it/s]

Loading cirrus:  22%|██▏       | 272/1250 [00:00<00:01, 675.97it/s]

Loading cirrus:  27%|██▋       | 340/1250 [00:00<00:01, 672.27it/s]

Loading cirrus:  33%|███▎      | 409/1250 [00:00<00:01, 668.15it/s]

Loading cirrus:  38%|███▊      | 476/1250 [00:00<00:01, 659.50it/s]

Loading cirrus:  43%|████▎     | 542/1250 [00:00<00:01, 650.02it/s]

Loading cirrus:  49%|████▊     | 609/1250 [00:00<00:00, 647.43it/s]

Loading cirrus:  54%|█████▍    | 674/1250 [00:01<00:00, 645.46it/s]

Loading cirrus:  59%|█████▉    | 742/1250 [00:01<00:00, 654.73it/s]

Loading cirrus:  65%|██████▍   | 808/1250 [00:01<00:00, 642.77it/s]

Loading cirrus:  70%|███████   | 877/1250 [00:01<00:00, 655.21it/s]

Loading cirrus:  75%|███████▌  | 943/1250 [00:01<00:00, 545.78it/s]

Loading cirrus:  81%|████████  | 1007/1250 [00:01<00:00, 567.70it/s]

Loading cirrus:  86%|████████▌ | 1075/1250 [00:01<00:00, 592.33it/s]

Loading cirrus:  92%|█████████▏| 1145/1250 [00:01<00:00, 614.43it/s]

Loading cirrus:  97%|█████████▋| 1214/1250 [00:01<00:00, 632.57it/s]

Loading clearsky:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading clearsky:   6%|▌         | 72/1250 [00:00<00:01, 705.61it/s]

Loading clearsky:  11%|█▏        | 143/1250 [00:00<00:01, 691.99it/s]

Loading clearsky:  17%|█▋        | 213/1250 [00:00<00:01, 671.95it/s]

Loading clearsky:  22%|██▏       | 281/1250 [00:00<00:01, 645.62it/s]

Loading clearsky:  28%|██▊       | 350/1250 [00:00<00:01, 651.24it/s]

Loading clearsky:  33%|███▎      | 418/1250 [00:00<00:01, 654.30it/s]

Loading clearsky:  39%|███▉      | 489/1250 [00:00<00:01, 666.18it/s]

Loading clearsky:  45%|████▍     | 558/1250 [00:00<00:01, 671.91it/s]

Loading clearsky:  50%|█████     | 626/1250 [00:00<00:00, 674.03it/s]

Loading clearsky:  56%|█████▌    | 695/1250 [00:01<00:00, 671.53it/s]

Loading clearsky:  61%|██████    | 763/1250 [00:01<00:00, 625.07it/s]

Loading clearsky:  66%|██████▌   | 827/1250 [00:01<00:00, 626.58it/s]

Loading clearsky:  71%|███████▏  | 893/1250 [00:01<00:00, 632.67it/s]

Loading clearsky:  77%|███████▋  | 957/1250 [00:01<00:00, 622.68it/s]

Loading clearsky:  82%|████████▏ | 1027/1250 [00:01<00:00, 641.41it/s]

Loading clearsky:  87%|████████▋ | 1092/1250 [00:01<00:00, 643.65it/s]

Loading clearsky:  93%|█████████▎| 1157/1250 [00:01<00:00, 613.54it/s]

Loading clearsky:  98%|█████████▊| 1219/1250 [00:01<00:00, 608.96it/s]

Loading cumulonimbus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading cumulonimbus:   5%|▌         | 63/1250 [00:00<00:01, 627.87it/s]

Loading cumulonimbus:  10%|█         | 126/1250 [00:00<00:01, 572.32it/s]

Loading cumulonimbus:  15%|█▍        | 184/1250 [00:00<00:01, 567.51it/s]

Loading cumulonimbus:  20%|█▉        | 244/1250 [00:00<00:01, 572.87it/s]

Loading cumulonimbus:  24%|██▍       | 302/1250 [00:00<00:01, 549.70it/s]

Loading cumulonimbus:  29%|██▉       | 362/1250 [00:00<00:01, 558.42it/s]

Loading cumulonimbus:  34%|███▍      | 431/1250 [00:00<00:01, 591.47it/s]

Loading cumulonimbus:  40%|███▉      | 498/1250 [00:00<00:01, 611.32it/s]

Loading cumulonimbus:  45%|████▌     | 565/1250 [00:00<00:01, 627.27it/s]

Loading cumulonimbus:  51%|█████     | 632/1250 [00:01<00:00, 638.60it/s]

Loading cumulonimbus:  56%|█████▌    | 696/1250 [00:01<00:00, 597.14it/s]

Loading cumulonimbus:  61%|██████    | 757/1250 [00:01<00:00, 518.32it/s]

Loading cumulonimbus:  65%|██████▍   | 811/1250 [00:01<00:00, 493.07it/s]

Loading cumulonimbus:  69%|██████▉   | 868/1250 [00:01<00:00, 512.25it/s]

Loading cumulonimbus:  75%|███████▍  | 937/1250 [00:01<00:00, 559.33it/s]

Loading cumulonimbus:  81%|████████  | 1007/1250 [00:01<00:00, 594.17it/s]

Loading cumulonimbus:  86%|████████▌ | 1075/1250 [00:01<00:00, 617.59it/s]

Loading cumulonimbus:  91%|█████████ | 1138/1250 [00:01<00:00, 601.53it/s]

Loading cumulonimbus:  96%|█████████▌| 1199/1250 [00:02<00:00, 564.36it/s]

Loading cumulus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading cumulus:   4%|▍         | 56/1250 [00:00<00:02, 554.04it/s]

Loading cumulus:   9%|▉         | 112/1250 [00:00<00:02, 536.25it/s]

Loading cumulus:  14%|█▎        | 169/1250 [00:00<00:01, 549.25it/s]

Loading cumulus:  18%|█▊        | 226/1250 [00:00<00:01, 554.58it/s]

Loading cumulus:  23%|██▎       | 284/1250 [00:00<00:01, 561.78it/s]

Loading cumulus:  27%|██▋       | 341/1250 [00:00<00:01, 563.46it/s]

Loading cumulus:  32%|███▏      | 400/1250 [00:00<00:01, 571.13it/s]

Loading cumulus:  37%|███▋      | 458/1250 [00:00<00:01, 571.63it/s]

Loading cumulus:  42%|████▏     | 519/1250 [00:00<00:01, 582.61it/s]

Loading cumulus:  46%|████▌     | 578/1250 [00:01<00:01, 582.79it/s]

Loading cumulus:  51%|█████     | 637/1250 [00:01<00:01, 578.20it/s]

Loading cumulus:  56%|█████▌    | 696/1250 [00:01<00:00, 579.63it/s]

Loading cumulus:  60%|██████    | 754/1250 [00:01<00:00, 575.16it/s]

Loading cumulus:  65%|██████▍   | 812/1250 [00:01<00:00, 553.12it/s]

Loading cumulus:  69%|██████▉   | 868/1250 [00:01<00:00, 540.02it/s]

Loading cumulus:  74%|███████▍  | 923/1250 [00:01<00:00, 540.28it/s]

Loading cumulus:  79%|███████▊  | 982/1250 [00:01<00:00, 552.17it/s]

Loading cumulus:  83%|████████▎ | 1040/1250 [00:01<00:00, 559.12it/s]

Loading cumulus:  88%|████████▊ | 1098/1250 [00:01<00:00, 560.67it/s]

Loading cumulus:  92%|█████████▏| 1155/1250 [00:02<00:00, 501.90it/s]

Loading cumulus:  97%|█████████▋| 1213/1250 [00:02<00:00, 520.85it/s]

Loading mixed:   0%|          | 0/955 [00:00<?, ?it/s]

Loading mixed:   6%|▋         | 61/955 [00:00<00:01, 605.11it/s]

Loading mixed:  13%|█▎        | 128/955 [00:00<00:01, 633.02it/s]

Loading mixed:  20%|██        | 193/955 [00:00<00:01, 638.52it/s]

Loading mixed:  27%|██▋       | 259/955 [00:00<00:01, 644.91it/s]

Loading mixed:  34%|███▍      | 324/955 [00:00<00:01, 617.84it/s]

Loading mixed:  40%|████      | 386/955 [00:00<00:00, 609.51it/s]

Loading mixed:  47%|████▋     | 448/955 [00:00<00:00, 595.26it/s]

Loading mixed:  53%|█████▎    | 508/955 [00:00<00:00, 587.10it/s]

Loading mixed:  59%|█████▉    | 567/955 [00:00<00:00, 542.97it/s]

Loading mixed:  65%|██████▌   | 623/955 [00:01<00:00, 545.40it/s]

Loading mixed:  71%|███████▏  | 682/955 [00:01<00:00, 554.91it/s]

Loading mixed:  77%|███████▋  | 740/955 [00:01<00:00, 561.80it/s]

Loading mixed:  84%|████████▎ | 799/955 [00:01<00:00, 566.82it/s]

Loading mixed:  90%|████████▉ | 859/955 [00:01<00:00, 570.05it/s]

Loading mixed:  96%|█████████▌| 917/955 [00:01<00:00, 545.74it/s]

Loading stratocumulus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading stratocumulus:   4%|▍         | 49/1250 [00:00<00:02, 480.05it/s]

Loading stratocumulus:   9%|▉         | 115/1250 [00:00<00:01, 581.87it/s]

Loading stratocumulus:  14%|█▍        | 174/1250 [00:00<00:01, 562.21it/s]

Loading stratocumulus:  19%|█▊        | 232/1250 [00:00<00:01, 565.61it/s]

Loading stratocumulus:  24%|██▎       | 296/1250 [00:00<00:01, 590.45it/s]

Loading stratocumulus:  29%|██▊       | 359/1250 [00:00<00:01, 602.13it/s]

Loading stratocumulus:  34%|███▎      | 420/1250 [00:00<00:01, 581.86it/s]

Loading stratocumulus:  38%|███▊      | 479/1250 [00:00<00:01, 581.17it/s]

Loading stratocumulus:  43%|████▎     | 542/1250 [00:00<00:01, 595.31it/s]

Loading stratocumulus:  48%|████▊     | 602/1250 [00:01<00:01, 569.45it/s]

Loading stratocumulus:  53%|█████▎    | 668/1250 [00:01<00:00, 594.91it/s]

Loading stratocumulus:  58%|█████▊    | 728/1250 [00:01<00:00, 574.93it/s]

Loading stratocumulus:  63%|██████▎   | 786/1250 [00:01<00:00, 571.89it/s]

Loading stratocumulus:  68%|██████▊   | 854/1250 [00:01<00:00, 602.15it/s]

Loading stratocumulus:  73%|███████▎  | 915/1250 [00:01<00:00, 572.08it/s]

Loading stratocumulus:  78%|███████▊  | 976/1250 [00:01<00:00, 581.36it/s]

Loading stratocumulus:  83%|████████▎ | 1038/1250 [00:01<00:00, 592.43it/s]

Loading stratocumulus:  88%|████████▊ | 1098/1250 [00:01<00:00, 571.65it/s]

Loading stratocumulus:  92%|█████████▏| 1156/1250 [00:02<00:00, 542.53it/s]

Loading stratocumulus:  97%|█████████▋| 1211/1250 [00:02<00:00, 536.07it/s]

Dataset loaded: 8455 gambar, 7 kelas, ukuran=(256, 256)
Dataset loaded: 8455 gambar warna, 7 kelas

## Preprocessing Pipeline (CLAHE HSV + Gaussian Blur)

In [3]:
# ================================================================
# EDIT BAGIAN INI untuk mengubah pipeline preprocessing
# Tambah, hapus, atau ganti fungsi sesuai experiment
# ================================================================

PIPELINE = [
    lambda img: clahe_hsv(img, tile_size=8, clip_limit=2.0),
    lambda img: gaussian_filter(img, kernel_size=5, sigma=1.0),
]

# ================================================================
# Jangan edit di bawah ini
# ================================================================

def apply_pipeline(image: np.ndarray, pipeline: list) -> np.ndarray:
    for fn in pipeline:
        image = fn(image)
    return image

In [4]:
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor

def process_one(img):
    return apply_pipeline(img, PIPELINE)

print("Menjalankan Preprocessing Pipeline...")
if USING_GPU:
    print("Menggunakan ThreadPoolExecutor (GPU aktif)...")
    with ThreadPoolExecutor(max_workers=4) as executor:
        images_preprocessed_color = list(tqdm(
            executor.map(process_one, images),
            total=len(images),
            desc="Preprocessing"
        ))
else:
    print("Menggunakan Pemrosesan Sekuensial CPU...")
    images_preprocessed_color = [process_one(img) for img in tqdm(images, desc="Preprocessing")]
    
images_preprocessed_color = np.array(images_preprocessed_color)

Menjalankan Preprocessing Pipeline...

Menggunakan Pemrosesan Sekuensial CPU...

Preprocessing:   0%|          | 0/8455 [00:00<?, ?it/s]

Preprocessing:   0%|          | 2/8455 [00:00<08:59, 15.67it/s]

Preprocessing:   0%|          | 5/8455 [00:00<06:45, 20.83it/s]

Preprocessing:   0%|          | 8/8455 [00:00<06:59, 20.16it/s]

Preprocessing:   0%|          | 11/8455 [00:00<06:23, 22.03it/s]

Preprocessing:   0%|          | 14/8455 [00:00<05:59, 23.47it/s]

Preprocessing:   0%|          | 17/8455 [00:00<05:46, 24.38it/s]

Preprocessing:   0%|          | 20/8455 [00:00<05:54, 23.80it/s]

Preprocessing:   0%|          | 23/8455 [00:01<06:15, 22.46it/s]

Preprocessing:   0%|          | 26/8455 [00:01<06:18, 22.24it/s]

Preprocessing:   0%|          | 29/8455 [00:01<06:24, 21.94it/s]

Preprocessing:   0%|          | 32/8455 [00:01<06:31, 21.50it/s]

Preprocessing:   0%|          | 35/8455 [00:01<06:40, 21.02it/s]

Preprocessing:   0%|          | 38/8455 [00:01<06:37, 21.15it/s]

Preprocessing:   0%|          | 41/8455 [00:01<06:48, 20.59it/s]

Preprocessing:   1%|          | 44/8455 [00:02<06:48, 20.59it/s]

Preprocessing:   1%|          | 47/8455 [00:02<07:12, 19.44it/s]

Preprocessing:   1%|          | 49/8455 [00:02<07:29, 18.72it/s]

Preprocessing:   1%|          | 52/8455 [00:02<06:59, 20.05it/s]

Preprocessing:   1%|          | 55/8455 [00:02<06:36, 21.21it/s]

Preprocessing:   1%|          | 58/8455 [00:02<06:29, 21.58it/s]

Preprocessing:   1%|          | 61/8455 [00:02<06:04, 23.04it/s]

Preprocessing:   1%|          | 64/8455 [00:02<06:17, 22.23it/s]

Preprocessing:   1%|          | 67/8455 [00:03<05:59, 23.32it/s]

Preprocessing:   1%|          | 70/8455 [00:03<06:04, 22.97it/s]

Preprocessing:   1%|          | 73/8455 [00:03<06:08, 22.75it/s]

Preprocessing:   1%|          | 76/8455 [00:03<05:49, 23.95it/s]

Preprocessing:   1%|          | 79/8455 [00:03<05:40, 24.62it/s]

Preprocessing:   1%|          | 82/8455 [00:03<05:35, 24.97it/s]

Preprocessing:   1%|          | 85/8455 [00:03<05:35, 24.96it/s]

Preprocessing:   1%|          | 88/8455 [00:03<05:33, 25.10it/s]

Preprocessing:   1%|          | 91/8455 [00:04<05:22, 25.95it/s]

Preprocessing:   1%|          | 94/8455 [00:04<05:19, 26.19it/s]

Preprocessing:   1%|          | 97/8455 [00:04<05:20, 26.11it/s]

Preprocessing:   1%|          | 100/8455 [00:04<05:23, 25.85it/s]

Preprocessing:   1%|          | 103/8455 [00:04<05:36, 24.84it/s]

Preprocessing:   1%|▏         | 106/8455 [00:04<05:24, 25.74it/s]

Preprocessing:   1%|▏         | 109/8455 [00:04<05:13, 26.58it/s]

Preprocessing:   1%|▏         | 112/8455 [00:04<05:04, 27.37it/s]

Preprocessing:   1%|▏         | 115/8455 [00:04<05:00, 27.78it/s]

Preprocessing:   1%|▏         | 118/8455 [00:05<05:02, 27.53it/s]

Preprocessing:   1%|▏         | 121/8455 [00:05<05:20, 26.01it/s]

Preprocessing:   1%|▏         | 124/8455 [00:05<05:27, 25.42it/s]

Preprocessing:   2%|▏         | 127/8455 [00:05<05:17, 26.24it/s]

Preprocessing:   2%|▏         | 131/8455 [00:05<05:00, 27.66it/s]

Preprocessing:   2%|▏         | 134/8455 [00:05<04:57, 27.99it/s]

Preprocessing:   2%|▏         | 138/8455 [00:05<04:51, 28.57it/s]

Preprocessing:   2%|▏         | 141/8455 [00:05<04:48, 28.79it/s]

Preprocessing:   2%|▏         | 144/8455 [00:06<05:07, 26.99it/s]

Preprocessing:   2%|▏         | 147/8455 [00:06<05:07, 27.01it/s]

Preprocessing:   2%|▏         | 150/8455 [00:06<05:16, 26.27it/s]

Preprocessing:   2%|▏         | 154/8455 [00:06<05:00, 27.60it/s]

Preprocessing:   2%|▏         | 158/8455 [00:06<04:49, 28.63it/s]

Preprocessing:   2%|▏         | 161/8455 [00:06<04:51, 28.44it/s]

Preprocessing:   2%|▏         | 164/8455 [00:06<04:52, 28.37it/s]

Preprocessing:   2%|▏         | 167/8455 [00:06<04:49, 28.65it/s]

Preprocessing:   2%|▏         | 171/8455 [00:06<04:41, 29.45it/s]

Preprocessing:   2%|▏         | 174/8455 [00:07<04:40, 29.52it/s]

Preprocessing:   2%|▏         | 178/8455 [00:07<04:39, 29.61it/s]

Preprocessing:   2%|▏         | 181/8455 [00:07<04:41, 29.42it/s]

Preprocessing:   2%|▏         | 184/8455 [00:07<04:42, 29.25it/s]

Preprocessing:   2%|▏         | 187/8455 [00:07<04:53, 28.18it/s]

Preprocessing:   2%|▏         | 190/8455 [00:07<04:51, 28.34it/s]

Preprocessing:   2%|▏         | 193/8455 [00:07<05:02, 27.32it/s]

Preprocessing:   2%|▏         | 196/8455 [00:07<05:45, 23.93it/s]

Preprocessing:   2%|▏         | 199/8455 [00:08<05:37, 24.48it/s]

Preprocessing:   2%|▏         | 202/8455 [00:08<05:29, 25.05it/s]

Preprocessing:   2%|▏         | 205/8455 [00:08<05:50, 23.54it/s]

Preprocessing:   2%|▏         | 208/8455 [00:08<05:42, 24.05it/s]

Preprocessing:   2%|▏         | 211/8455 [00:08<05:26, 25.28it/s]

Preprocessing:   3%|▎         | 214/8455 [00:08<05:18, 25.88it/s]

Preprocessing:   3%|▎         | 217/8455 [00:08<05:10, 26.50it/s]

Preprocessing:   3%|▎         | 220/8455 [00:08<05:29, 24.98it/s]

Preprocessing:   3%|▎         | 223/8455 [00:08<05:35, 24.51it/s]

Preprocessing:   3%|▎         | 226/8455 [00:09<05:30, 24.93it/s]

Preprocessing:   3%|▎         | 229/8455 [00:09<05:26, 25.19it/s]

Preprocessing:   3%|▎         | 232/8455 [00:09<05:17, 25.88it/s]

Preprocessing:   3%|▎         | 236/8455 [00:09<05:00, 27.32it/s]

Preprocessing:   3%|▎         | 239/8455 [00:09<05:02, 27.20it/s]

Preprocessing:   3%|▎         | 242/8455 [00:09<04:59, 27.38it/s]

Preprocessing:   3%|▎         | 245/8455 [00:09<05:24, 25.32it/s]

Preprocessing:   3%|▎         | 249/8455 [00:09<05:02, 27.12it/s]

Preprocessing:   3%|▎         | 252/8455 [00:10<04:56, 27.69it/s]

Preprocessing:   3%|▎         | 256/8455 [00:10<04:47, 28.49it/s]

Preprocessing:   3%|▎         | 259/8455 [00:10<04:46, 28.65it/s]

Preprocessing:   3%|▎         | 262/8455 [00:10<05:01, 27.16it/s]

Preprocessing:   3%|▎         | 265/8455 [00:10<05:27, 25.02it/s]

Preprocessing:   3%|▎         | 268/8455 [00:10<05:39, 24.15it/s]

Preprocessing:   3%|▎         | 271/8455 [00:10<05:42, 23.87it/s]

Preprocessing:   3%|▎         | 274/8455 [00:10<05:25, 25.12it/s]

Preprocessing:   3%|▎         | 277/8455 [00:11<05:41, 23.95it/s]

Preprocessing:   3%|▎         | 280/8455 [00:11<05:33, 24.52it/s]

Preprocessing:   3%|▎         | 283/8455 [00:11<05:35, 24.38it/s]

Preprocessing:   3%|▎         | 286/8455 [00:11<05:36, 24.27it/s]

Preprocessing:   3%|▎         | 289/8455 [00:11<05:32, 24.59it/s]

Preprocessing:   3%|▎         | 293/8455 [00:11<05:07, 26.52it/s]

Preprocessing:   4%|▎         | 297/8455 [00:11<05:03, 26.92it/s]

Preprocessing:   4%|▎         | 300/8455 [00:11<05:20, 25.46it/s]

Preprocessing:   4%|▎         | 303/8455 [00:12<05:14, 25.90it/s]

Preprocessing:   4%|▎         | 307/8455 [00:12<04:59, 27.21it/s]

Preprocessing:   4%|▎         | 310/8455 [00:12<05:12, 26.06it/s]

Preprocessing:   4%|▎         | 314/8455 [00:12<04:55, 27.52it/s]

Preprocessing:   4%|▍         | 318/8455 [00:12<04:47, 28.32it/s]

Preprocessing:   4%|▍         | 321/8455 [00:12<04:46, 28.41it/s]

Preprocessing:   4%|▍         | 324/8455 [00:12<04:52, 27.81it/s]

Preprocessing:   4%|▍         | 327/8455 [00:12<05:01, 26.95it/s]

Preprocessing:   4%|▍         | 331/8455 [00:13<04:44, 28.56it/s]

Preprocessing:   4%|▍         | 334/8455 [00:13<04:40, 28.93it/s]

Preprocessing:   4%|▍         | 337/8455 [00:13<04:54, 27.53it/s]

Preprocessing:   4%|▍         | 340/8455 [00:13<04:57, 27.27it/s]

Preprocessing:   4%|▍         | 343/8455 [00:13<04:53, 27.61it/s]

Preprocessing:   4%|▍         | 347/8455 [00:13<04:41, 28.80it/s]

Preprocessing:   4%|▍         | 350/8455 [00:13<04:41, 28.84it/s]

Preprocessing:   4%|▍         | 354/8455 [00:13<04:35, 29.36it/s]

Preprocessing:   4%|▍         | 358/8455 [00:13<04:35, 29.37it/s]

Preprocessing:   4%|▍         | 361/8455 [00:14<04:39, 28.92it/s]

Preprocessing:   4%|▍         | 364/8455 [00:14<04:45, 28.33it/s]

Preprocessing:   4%|▍         | 367/8455 [00:14<04:50, 27.89it/s]

Preprocessing:   4%|▍         | 371/8455 [00:14<04:40, 28.82it/s]

Preprocessing:   4%|▍         | 374/8455 [00:14<04:41, 28.68it/s]

Preprocessing:   4%|▍         | 377/8455 [00:14<04:42, 28.63it/s]

Preprocessing:   5%|▍         | 381/8455 [00:14<04:33, 29.57it/s]

Preprocessing:   5%|▍         | 384/8455 [00:14<04:34, 29.40it/s]

Preprocessing:   5%|▍         | 387/8455 [00:14<04:33, 29.46it/s]

Preprocessing:   5%|▍         | 390/8455 [00:15<04:51, 27.65it/s]

Preprocessing:   5%|▍         | 393/8455 [00:15<05:06, 26.28it/s]

Preprocessing:   5%|▍         | 396/8455 [00:15<05:06, 26.30it/s]

Preprocessing:   5%|▍         | 399/8455 [00:15<05:03, 26.57it/s]

Preprocessing:   5%|▍         | 402/8455 [00:15<05:21, 25.06it/s]

Preprocessing:   5%|▍         | 405/8455 [00:15<05:41, 23.56it/s]

Preprocessing:   5%|▍         | 408/8455 [00:15<05:49, 23.05it/s]

Preprocessing:   5%|▍         | 411/8455 [00:15<05:34, 24.05it/s]

Preprocessing:   5%|▍         | 414/8455 [00:16<05:16, 25.39it/s]

Preprocessing:   5%|▍         | 417/8455 [00:16<05:08, 26.02it/s]

Preprocessing:   5%|▍         | 420/8455 [00:16<04:58, 26.90it/s]

Preprocessing:   5%|▌         | 423/8455 [00:16<04:50, 27.67it/s]

Preprocessing:   5%|▌         | 427/8455 [00:16<04:36, 29.02it/s]

Preprocessing:   5%|▌         | 430/8455 [00:16<04:38, 28.85it/s]

Preprocessing:   5%|▌         | 433/8455 [00:16<04:42, 28.41it/s]

Preprocessing:   5%|▌         | 436/8455 [00:16<04:49, 27.71it/s]

Preprocessing:   5%|▌         | 439/8455 [00:16<04:46, 27.97it/s]

Preprocessing:   5%|▌         | 442/8455 [00:17<04:46, 28.01it/s]

Preprocessing:   5%|▌         | 445/8455 [00:17<04:41, 28.47it/s]

Preprocessing:   5%|▌         | 448/8455 [00:17<05:05, 26.18it/s]

Preprocessing:   5%|▌         | 451/8455 [00:17<04:58, 26.80it/s]

Preprocessing:   5%|▌         | 454/8455 [00:17<04:53, 27.22it/s]

Preprocessing:   5%|▌         | 457/8455 [00:17<04:52, 27.34it/s]

Preprocessing:   5%|▌         | 460/8455 [00:17<05:01, 26.53it/s]

Preprocessing:   5%|▌         | 463/8455 [00:17<05:12, 25.56it/s]

Preprocessing:   6%|▌         | 466/8455 [00:18<05:13, 25.49it/s]

Preprocessing:   6%|▌         | 469/8455 [00:18<05:05, 26.18it/s]

Preprocessing:   6%|▌         | 472/8455 [00:18<05:42, 23.29it/s]

Preprocessing:   6%|▌         | 475/8455 [00:18<05:56, 22.36it/s]

Preprocessing:   6%|▌         | 478/8455 [00:18<05:34, 23.85it/s]

Preprocessing:   6%|▌         | 481/8455 [00:18<05:26, 24.41it/s]

Preprocessing:   6%|▌         | 484/8455 [00:18<05:17, 25.09it/s]

Preprocessing:   6%|▌         | 487/8455 [00:18<05:08, 25.84it/s]

Preprocessing:   6%|▌         | 490/8455 [00:18<04:58, 26.68it/s]

Preprocessing:   6%|▌         | 493/8455 [00:19<04:49, 27.55it/s]

Preprocessing:   6%|▌         | 496/8455 [00:19<04:56, 26.88it/s]

Preprocessing:   6%|▌         | 499/8455 [00:19<04:53, 27.12it/s]

Preprocessing:   6%|▌         | 503/8455 [00:19<04:38, 28.52it/s]

Preprocessing:   6%|▌         | 506/8455 [00:19<04:52, 27.18it/s]

Preprocessing:   6%|▌         | 509/8455 [00:19<04:52, 27.20it/s]

Preprocessing:   6%|▌         | 512/8455 [00:19<05:17, 25.06it/s]

Preprocessing:   6%|▌         | 515/8455 [00:19<05:16, 25.11it/s]

Preprocessing:   6%|▌         | 518/8455 [00:20<05:11, 25.45it/s]

Preprocessing:   6%|▌         | 521/8455 [00:20<05:14, 25.26it/s]

Preprocessing:   6%|▌         | 524/8455 [00:20<05:23, 24.53it/s]

Preprocessing:   6%|▌         | 527/8455 [00:20<05:20, 24.74it/s]

Preprocessing:   6%|▋         | 531/8455 [00:20<04:59, 26.47it/s]

Preprocessing:   6%|▋         | 534/8455 [00:20<05:05, 25.95it/s]

Preprocessing:   6%|▋         | 537/8455 [00:20<04:53, 26.98it/s]

Preprocessing:   6%|▋         | 541/8455 [00:20<04:40, 28.17it/s]

Preprocessing:   6%|▋         | 544/8455 [00:21<05:02, 26.20it/s]

Preprocessing:   6%|▋         | 547/8455 [00:21<05:08, 25.62it/s]

Preprocessing:   7%|▋         | 550/8455 [00:21<05:07, 25.72it/s]

Preprocessing:   7%|▋         | 553/8455 [00:21<05:06, 25.78it/s]

Preprocessing:   7%|▋         | 556/8455 [00:21<05:01, 26.19it/s]

Preprocessing:   7%|▋         | 559/8455 [00:21<05:00, 26.24it/s]

Preprocessing:   7%|▋         | 562/8455 [00:21<04:56, 26.59it/s]

Preprocessing:   7%|▋         | 565/8455 [00:21<04:53, 26.91it/s]

Preprocessing:   7%|▋         | 568/8455 [00:21<04:51, 27.05it/s]

Preprocessing:   7%|▋         | 571/8455 [00:22<05:12, 25.21it/s]

Preprocessing:   7%|▋         | 574/8455 [00:22<05:28, 23.98it/s]

Preprocessing:   7%|▋         | 577/8455 [00:22<06:01, 21.79it/s]

Preprocessing:   7%|▋         | 580/8455 [00:22<06:24, 20.48it/s]

Preprocessing:   7%|▋         | 583/8455 [00:22<06:15, 20.94it/s]

Preprocessing:   7%|▋         | 586/8455 [00:22<05:56, 22.07it/s]

Preprocessing:   7%|▋         | 589/8455 [00:22<05:38, 23.22it/s]

Preprocessing:   7%|▋         | 592/8455 [00:23<05:24, 24.24it/s]

Preprocessing:   7%|▋         | 595/8455 [00:23<05:18, 24.69it/s]

Preprocessing:   7%|▋         | 598/8455 [00:23<05:43, 22.90it/s]

Preprocessing:   7%|▋         | 601/8455 [00:23<05:36, 23.32it/s]

Preprocessing:   7%|▋         | 604/8455 [00:23<05:22, 24.36it/s]

Preprocessing:   7%|▋         | 607/8455 [00:23<05:29, 23.81it/s]

Preprocessing:   7%|▋         | 610/8455 [00:23<05:22, 24.31it/s]

Preprocessing:   7%|▋         | 613/8455 [00:23<05:50, 22.40it/s]

Preprocessing:   7%|▋         | 616/8455 [00:24<05:49, 22.43it/s]

Preprocessing:   7%|▋         | 619/8455 [00:24<06:13, 20.96it/s]

Preprocessing:   7%|▋         | 622/8455 [00:24<06:21, 20.54it/s]

Preprocessing:   7%|▋         | 625/8455 [00:24<06:04, 21.51it/s]

Preprocessing:   7%|▋         | 628/8455 [00:24<05:44, 22.71it/s]

Preprocessing:   7%|▋         | 631/8455 [00:24<05:35, 23.33it/s]

Preprocessing:   7%|▋         | 634/8455 [00:24<05:35, 23.33it/s]

Preprocessing:   8%|▊         | 637/8455 [00:24<05:31, 23.58it/s]

Preprocessing:   8%|▊         | 640/8455 [00:25<05:40, 22.93it/s]

Preprocessing:   8%|▊         | 643/8455 [00:25<05:42, 22.82it/s]

Preprocessing:   8%|▊         | 646/8455 [00:25<05:56, 21.88it/s]

Preprocessing:   8%|▊         | 649/8455 [00:25<06:05, 21.36it/s]

Preprocessing:   8%|▊         | 652/8455 [00:25<06:45, 19.26it/s]

Preprocessing:   8%|▊         | 655/8455 [00:25<06:28, 20.06it/s]

Preprocessing:   8%|▊         | 658/8455 [00:25<05:54, 22.02it/s]

Preprocessing:   8%|▊         | 661/8455 [00:26<05:37, 23.11it/s]

Preprocessing:   8%|▊         | 664/8455 [00:26<05:20, 24.32it/s]

Preprocessing:   8%|▊         | 667/8455 [00:26<05:02, 25.79it/s]

Preprocessing:   8%|▊         | 670/8455 [00:26<05:10, 25.10it/s]

Preprocessing:   8%|▊         | 673/8455 [00:26<05:49, 22.27it/s]

Preprocessing:   8%|▊         | 676/8455 [00:26<06:40, 19.41it/s]

Preprocessing:   8%|▊         | 679/8455 [00:26<06:59, 18.53it/s]

Preprocessing:   8%|▊         | 681/8455 [00:27<07:06, 18.23it/s]

Preprocessing:   8%|▊         | 683/8455 [00:27<07:12, 17.96it/s]

Preprocessing:   8%|▊         | 685/8455 [00:27<07:20, 17.64it/s]

Preprocessing:   8%|▊         | 687/8455 [00:27<07:23, 17.50it/s]

Preprocessing:   8%|▊         | 689/8455 [00:27<07:34, 17.08it/s]

Preprocessing:   8%|▊         | 691/8455 [00:27<07:44, 16.70it/s]

Preprocessing:   8%|▊         | 693/8455 [00:27<07:38, 16.92it/s]

Preprocessing:   8%|▊         | 695/8455 [00:27<07:36, 17.02it/s]

Preprocessing:   8%|▊         | 697/8455 [00:28<07:48, 16.55it/s]

Preprocessing:   8%|▊         | 699/8455 [00:28<07:51, 16.46it/s]

Preprocessing:   8%|▊         | 701/8455 [00:28<08:02, 16.08it/s]

Preprocessing:   8%|▊         | 703/8455 [00:28<09:49, 13.15it/s]

Preprocessing:   8%|▊         | 705/8455 [00:28<10:30, 12.30it/s]

Preprocessing:   8%|▊         | 707/8455 [00:28<10:54, 11.84it/s]

Preprocessing:   8%|▊         | 709/8455 [00:29<11:45, 10.97it/s]

Preprocessing:   8%|▊         | 711/8455 [00:29<12:05, 10.67it/s]

Preprocessing:   8%|▊         | 713/8455 [00:29<11:22, 11.35it/s]

Preprocessing:   8%|▊         | 715/8455 [00:29<10:38, 12.13it/s]

Preprocessing:   8%|▊         | 717/8455 [00:29<10:18, 12.51it/s]

Preprocessing:   9%|▊         | 719/8455 [00:29<10:22, 12.42it/s]

Preprocessing:   9%|▊         | 721/8455 [00:30<10:09, 12.69it/s]

Preprocessing:   9%|▊         | 723/8455 [00:30<09:56, 12.97it/s]

Preprocessing:   9%|▊         | 725/8455 [00:30<10:00, 12.88it/s]

Preprocessing:   9%|▊         | 727/8455 [00:30<09:49, 13.12it/s]

Preprocessing:   9%|▊         | 729/8455 [00:30<09:29, 13.57it/s]

Preprocessing:   9%|▊         | 731/8455 [00:30<09:11, 14.01it/s]

Preprocessing:   9%|▊         | 733/8455 [00:30<09:38, 13.34it/s]

Preprocessing:   9%|▊         | 735/8455 [00:31<09:26, 13.63it/s]

Preprocessing:   9%|▊         | 737/8455 [00:31<09:11, 14.01it/s]

Preprocessing:   9%|▉         | 740/8455 [00:31<08:16, 15.54it/s]

Preprocessing:   9%|▉         | 742/8455 [00:31<08:11, 15.68it/s]

Preprocessing:   9%|▉         | 744/8455 [00:31<08:20, 15.42it/s]

Preprocessing:   9%|▉         | 746/8455 [00:31<08:07, 15.81it/s]

Preprocessing:   9%|▉         | 748/8455 [00:31<08:09, 15.73it/s]

Preprocessing:   9%|▉         | 750/8455 [00:32<08:07, 15.80it/s]

Preprocessing:   9%|▉         | 752/8455 [00:32<08:14, 15.59it/s]

Preprocessing:   9%|▉         | 754/8455 [00:32<08:27, 15.19it/s]

Preprocessing:   9%|▉         | 756/8455 [00:32<08:29, 15.11it/s]

Preprocessing:   9%|▉         | 758/8455 [00:32<08:26, 15.19it/s]

Preprocessing:   9%|▉         | 760/8455 [00:32<08:26, 15.18it/s]

Preprocessing:   9%|▉         | 762/8455 [00:32<08:39, 14.80it/s]

Preprocessing:   9%|▉         | 764/8455 [00:32<08:35, 14.92it/s]

Preprocessing:   9%|▉         | 766/8455 [00:33<08:25, 15.22it/s]

Preprocessing:   9%|▉         | 768/8455 [00:33<08:15, 15.52it/s]

Preprocessing:   9%|▉         | 770/8455 [00:33<08:18, 15.40it/s]

Preprocessing:   9%|▉         | 772/8455 [00:33<08:21, 15.32it/s]

Preprocessing:   9%|▉         | 774/8455 [00:33<08:15, 15.51it/s]

Preprocessing:   9%|▉         | 776/8455 [00:33<08:14, 15.52it/s]

Preprocessing:   9%|▉         | 778/8455 [00:33<08:12, 15.59it/s]

Preprocessing:   9%|▉         | 780/8455 [00:33<08:14, 15.52it/s]

Preprocessing:   9%|▉         | 782/8455 [00:34<08:17, 15.43it/s]

Preprocessing:   9%|▉         | 784/8455 [00:34<08:15, 15.48it/s]

Preprocessing:   9%|▉         | 786/8455 [00:34<08:11, 15.60it/s]

Preprocessing:   9%|▉         | 788/8455 [00:34<08:19, 15.36it/s]

Preprocessing:   9%|▉         | 790/8455 [00:34<08:00, 15.94it/s]

Preprocessing:   9%|▉         | 792/8455 [00:34<08:11, 15.58it/s]

Preprocessing:   9%|▉         | 794/8455 [00:34<09:12, 13.86it/s]

Preprocessing:   9%|▉         | 796/8455 [00:35<08:39, 14.75it/s]

Preprocessing:   9%|▉         | 798/8455 [00:35<08:06, 15.75it/s]

Preprocessing:   9%|▉         | 800/8455 [00:35<07:38, 16.69it/s]

Preprocessing:   9%|▉         | 802/8455 [00:35<07:24, 17.22it/s]

Preprocessing:  10%|▉         | 804/8455 [00:35<07:12, 17.68it/s]

Preprocessing:  10%|▉         | 806/8455 [00:35<07:00, 18.18it/s]

Preprocessing:  10%|▉         | 808/8455 [00:35<06:53, 18.50it/s]

Preprocessing:  10%|▉         | 810/8455 [00:35<07:01, 18.12it/s]

Preprocessing:  10%|▉         | 812/8455 [00:35<07:44, 16.45it/s]

Preprocessing:  10%|▉         | 814/8455 [00:36<08:33, 14.88it/s]

Preprocessing:  10%|▉         | 816/8455 [00:36<08:36, 14.79it/s]

Preprocessing:  10%|▉         | 818/8455 [00:36<08:05, 15.72it/s]

Preprocessing:  10%|▉         | 820/8455 [00:36<08:02, 15.83it/s]

Preprocessing:  10%|▉         | 822/8455 [00:36<07:37, 16.68it/s]

Preprocessing:  10%|▉         | 824/8455 [00:36<07:37, 16.67it/s]

Preprocessing:  10%|▉         | 826/8455 [00:36<08:13, 15.47it/s]

Preprocessing:  10%|▉         | 828/8455 [00:36<07:50, 16.20it/s]

Preprocessing:  10%|▉         | 830/8455 [00:37<07:46, 16.33it/s]

Preprocessing:  10%|▉         | 832/8455 [00:37<07:32, 16.85it/s]

Preprocessing:  10%|▉         | 834/8455 [00:37<07:31, 16.87it/s]

Preprocessing:  10%|▉         | 836/8455 [00:37<08:43, 14.54it/s]

Preprocessing:  10%|▉         | 838/8455 [00:37<08:37, 14.71it/s]

Preprocessing:  10%|▉         | 840/8455 [00:37<08:23, 15.13it/s]

Preprocessing:  10%|▉         | 842/8455 [00:37<07:54, 16.05it/s]

Preprocessing:  10%|▉         | 844/8455 [00:38<09:01, 14.07it/s]

Preprocessing:  10%|█         | 846/8455 [00:38<09:21, 13.56it/s]

Preprocessing:  10%|█         | 848/8455 [00:38<09:05, 13.94it/s]

Preprocessing:  10%|█         | 850/8455 [00:38<08:54, 14.23it/s]

Preprocessing:  10%|█         | 852/8455 [00:38<08:53, 14.25it/s]

Preprocessing:  10%|█         | 854/8455 [00:38<09:57, 12.73it/s]

Preprocessing:  10%|█         | 856/8455 [00:38<09:26, 13.42it/s]

Preprocessing:  10%|█         | 858/8455 [00:39<09:13, 13.73it/s]

Preprocessing:  10%|█         | 860/8455 [00:39<08:58, 14.11it/s]

Preprocessing:  10%|█         | 862/8455 [00:39<08:44, 14.48it/s]

Preprocessing:  10%|█         | 864/8455 [00:39<08:28, 14.93it/s]

Preprocessing:  10%|█         | 866/8455 [00:39<08:54, 14.19it/s]

Preprocessing:  10%|█         | 868/8455 [00:39<09:14, 13.68it/s]

Preprocessing:  10%|█         | 870/8455 [00:39<09:04, 13.94it/s]

Preprocessing:  10%|█         | 872/8455 [00:40<09:03, 13.95it/s]

Preprocessing:  10%|█         | 874/8455 [00:40<09:01, 14.01it/s]

Preprocessing:  10%|█         | 876/8455 [00:40<09:28, 13.34it/s]

Preprocessing:  10%|█         | 878/8455 [00:40<10:30, 12.02it/s]

Preprocessing:  10%|█         | 880/8455 [00:40<10:39, 11.85it/s]

Preprocessing:  10%|█         | 882/8455 [00:40<09:52, 12.78it/s]

Preprocessing:  10%|█         | 884/8455 [00:41<09:25, 13.39it/s]

Preprocessing:  10%|█         | 886/8455 [00:41<10:27, 12.06it/s]

Preprocessing:  11%|█         | 888/8455 [00:41<09:55, 12.71it/s]

Preprocessing:  11%|█         | 890/8455 [00:41<10:50, 11.63it/s]

Preprocessing:  11%|█         | 892/8455 [00:41<10:10, 12.40it/s]

Preprocessing:  11%|█         | 894/8455 [00:41<09:42, 12.97it/s]

Preprocessing:  11%|█         | 896/8455 [00:41<09:32, 13.21it/s]

Preprocessing:  11%|█         | 898/8455 [00:42<09:36, 13.10it/s]

Preprocessing:  11%|█         | 900/8455 [00:42<10:00, 12.59it/s]

Preprocessing:  11%|█         | 902/8455 [00:42<10:14, 12.28it/s]

Preprocessing:  11%|█         | 904/8455 [00:42<09:54, 12.70it/s]

Preprocessing:  11%|█         | 906/8455 [00:42<09:31, 13.22it/s]

Preprocessing:  11%|█         | 908/8455 [00:42<09:43, 12.93it/s]

Preprocessing:  11%|█         | 910/8455 [00:43<09:45, 12.88it/s]

Preprocessing:  11%|█         | 912/8455 [00:43<10:12, 12.32it/s]

Preprocessing:  11%|█         | 914/8455 [00:43<09:44, 12.90it/s]

Preprocessing:  11%|█         | 916/8455 [00:43<09:11, 13.66it/s]

Preprocessing:  11%|█         | 918/8455 [00:43<09:27, 13.28it/s]

Preprocessing:  11%|█         | 920/8455 [00:43<10:15, 12.25it/s]

Preprocessing:  11%|█         | 922/8455 [00:44<10:11, 12.32it/s]

Preprocessing:  11%|█         | 924/8455 [00:44<10:11, 12.32it/s]

Preprocessing:  11%|█         | 926/8455 [00:44<09:50, 12.75it/s]

Preprocessing:  11%|█         | 928/8455 [00:44<09:08, 13.71it/s]

Preprocessing:  11%|█         | 930/8455 [00:44<08:28, 14.80it/s]

Preprocessing:  11%|█         | 932/8455 [00:44<08:24, 14.91it/s]

Preprocessing:  11%|█         | 934/8455 [00:44<08:13, 15.23it/s]

Preprocessing:  11%|█         | 936/8455 [00:44<07:50, 15.97it/s]

Preprocessing:  11%|█         | 938/8455 [00:45<07:40, 16.33it/s]

Preprocessing:  11%|█         | 940/8455 [00:45<08:07, 15.42it/s]

Preprocessing:  11%|█         | 942/8455 [00:45<09:28, 13.21it/s]

Preprocessing:  11%|█         | 944/8455 [00:45<08:56, 14.00it/s]

Preprocessing:  11%|█         | 946/8455 [00:45<09:13, 13.56it/s]

Preprocessing:  11%|█         | 948/8455 [00:45<08:39, 14.45it/s]

Preprocessing:  11%|█         | 950/8455 [00:45<08:29, 14.73it/s]

Preprocessing:  11%|█▏        | 952/8455 [00:46<09:37, 12.99it/s]

Preprocessing:  11%|█▏        | 954/8455 [00:46<08:51, 14.11it/s]

Preprocessing:  11%|█▏        | 956/8455 [00:46<08:50, 14.12it/s]

Preprocessing:  11%|█▏        | 958/8455 [00:46<08:27, 14.76it/s]

Preprocessing:  11%|█▏        | 960/8455 [00:46<08:01, 15.57it/s]

Preprocessing:  11%|█▏        | 962/8455 [00:46<07:48, 16.01it/s]

Preprocessing:  11%|█▏        | 964/8455 [00:46<09:10, 13.60it/s]

Preprocessing:  11%|█▏        | 966/8455 [00:47<09:25, 13.25it/s]

Preprocessing:  11%|█▏        | 968/8455 [00:47<08:46, 14.23it/s]

Preprocessing:  11%|█▏        | 970/8455 [00:47<08:24, 14.84it/s]

Preprocessing:  11%|█▏        | 972/8455 [00:47<08:44, 14.27it/s]

Preprocessing:  12%|█▏        | 974/8455 [00:47<08:28, 14.72it/s]

Preprocessing:  12%|█▏        | 976/8455 [00:47<08:56, 13.94it/s]

Preprocessing:  12%|█▏        | 978/8455 [00:47<08:24, 14.83it/s]

Preprocessing:  12%|█▏        | 980/8455 [00:48<07:59, 15.58it/s]

Preprocessing:  12%|█▏        | 982/8455 [00:48<07:42, 16.16it/s]

Preprocessing:  12%|█▏        | 984/8455 [00:48<07:24, 16.82it/s]

Preprocessing:  12%|█▏        | 986/8455 [00:48<07:14, 17.17it/s]

Preprocessing:  12%|█▏        | 988/8455 [00:48<07:14, 17.20it/s]

Preprocessing:  12%|█▏        | 990/8455 [00:48<07:11, 17.32it/s]

Preprocessing:  12%|█▏        | 992/8455 [00:48<07:13, 17.21it/s]

Preprocessing:  12%|█▏        | 994/8455 [00:48<07:24, 16.79it/s]

Preprocessing:  12%|█▏        | 996/8455 [00:48<08:19, 14.93it/s]

Preprocessing:  12%|█▏        | 998/8455 [00:49<08:46, 14.17it/s]

Preprocessing:  12%|█▏        | 1000/8455 [00:49<08:48, 14.10it/s]

Preprocessing:  12%|█▏        | 1002/8455 [00:49<08:17, 14.98it/s]

Preprocessing:  12%|█▏        | 1004/8455 [00:49<07:59, 15.54it/s]

Preprocessing:  12%|█▏        | 1006/8455 [00:49<08:11, 15.15it/s]

Preprocessing:  12%|█▏        | 1008/8455 [00:49<07:56, 15.62it/s]

Preprocessing:  12%|█▏        | 1010/8455 [00:49<07:38, 16.23it/s]

Preprocessing:  12%|█▏        | 1012/8455 [00:49<07:26, 16.67it/s]

Preprocessing:  12%|█▏        | 1014/8455 [00:50<08:08, 15.24it/s]

Preprocessing:  12%|█▏        | 1016/8455 [00:50<09:08, 13.55it/s]

Preprocessing:  12%|█▏        | 1018/8455 [00:50<10:04, 12.30it/s]

Preprocessing:  12%|█▏        | 1020/8455 [00:50<09:28, 13.07it/s]

Preprocessing:  12%|█▏        | 1022/8455 [00:50<08:49, 14.03it/s]

Preprocessing:  12%|█▏        | 1024/8455 [00:50<08:20, 14.86it/s]

Preprocessing:  12%|█▏        | 1026/8455 [00:51<09:22, 13.20it/s]

Preprocessing:  12%|█▏        | 1028/8455 [00:51<08:31, 14.53it/s]

Preprocessing:  12%|█▏        | 1030/8455 [00:51<08:05, 15.31it/s]

Preprocessing:  12%|█▏        | 1032/8455 [00:51<08:01, 15.43it/s]

Preprocessing:  12%|█▏        | 1034/8455 [00:51<07:41, 16.09it/s]

Preprocessing:  12%|█▏        | 1036/8455 [00:51<08:18, 14.87it/s]

Preprocessing:  12%|█▏        | 1038/8455 [00:51<09:16, 13.32it/s]

Preprocessing:  12%|█▏        | 1040/8455 [00:52<09:22, 13.18it/s]

Preprocessing:  12%|█▏        | 1042/8455 [00:52<08:38, 14.30it/s]

Preprocessing:  12%|█▏        | 1044/8455 [00:52<08:00, 15.42it/s]

Preprocessing:  12%|█▏        | 1046/8455 [00:52<08:13, 15.00it/s]

Preprocessing:  12%|█▏        | 1048/8455 [00:52<08:00, 15.40it/s]

Preprocessing:  12%|█▏        | 1050/8455 [00:52<07:54, 15.59it/s]

Preprocessing:  12%|█▏        | 1052/8455 [00:52<07:44, 15.94it/s]

Preprocessing:  12%|█▏        | 1054/8455 [00:52<07:34, 16.28it/s]

Preprocessing:  12%|█▏        | 1056/8455 [00:53<07:35, 16.25it/s]

Preprocessing:  13%|█▎        | 1058/8455 [00:53<08:07, 15.17it/s]

Preprocessing:  13%|█▎        | 1060/8455 [00:53<09:20, 13.19it/s]

Preprocessing:  13%|█▎        | 1062/8455 [00:53<09:21, 13.17it/s]

Preprocessing:  13%|█▎        | 1064/8455 [00:53<08:35, 14.33it/s]

Preprocessing:  13%|█▎        | 1066/8455 [00:53<08:07, 15.17it/s]

Preprocessing:  13%|█▎        | 1068/8455 [00:53<08:34, 14.35it/s]

Preprocessing:  13%|█▎        | 1070/8455 [00:54<09:22, 13.13it/s]

Preprocessing:  13%|█▎        | 1072/8455 [00:54<09:35, 12.83it/s]

Preprocessing:  13%|█▎        | 1074/8455 [00:54<08:48, 13.97it/s]

Preprocessing:  13%|█▎        | 1076/8455 [00:54<08:09, 15.07it/s]

Preprocessing:  13%|█▎        | 1078/8455 [00:54<09:03, 13.57it/s]

Preprocessing:  13%|█▎        | 1080/8455 [00:54<09:47, 12.55it/s]

Preprocessing:  13%|█▎        | 1082/8455 [00:54<08:55, 13.76it/s]

Preprocessing:  13%|█▎        | 1084/8455 [00:55<08:11, 15.01it/s]

Preprocessing:  13%|█▎        | 1086/8455 [00:55<08:01, 15.30it/s]

Preprocessing:  13%|█▎        | 1088/8455 [00:55<07:47, 15.77it/s]

Preprocessing:  13%|█▎        | 1090/8455 [00:55<08:12, 14.96it/s]

Preprocessing:  13%|█▎        | 1092/8455 [00:55<08:35, 14.28it/s]

Preprocessing:  13%|█▎        | 1094/8455 [00:55<09:01, 13.59it/s]

Preprocessing:  13%|█▎        | 1096/8455 [00:55<08:30, 14.43it/s]

Preprocessing:  13%|█▎        | 1098/8455 [00:55<08:06, 15.13it/s]

Preprocessing:  13%|█▎        | 1100/8455 [00:56<08:43, 14.05it/s]

Preprocessing:  13%|█▎        | 1102/8455 [00:56<08:56, 13.72it/s]

Preprocessing:  13%|█▎        | 1104/8455 [00:56<08:39, 14.15it/s]

Preprocessing:  13%|█▎        | 1106/8455 [00:56<08:12, 14.91it/s]

Preprocessing:  13%|█▎        | 1108/8455 [00:56<07:56, 15.41it/s]

Preprocessing:  13%|█▎        | 1110/8455 [00:56<07:37, 16.05it/s]

Preprocessing:  13%|█▎        | 1112/8455 [00:56<08:45, 13.97it/s]

Preprocessing:  13%|█▎        | 1114/8455 [00:57<09:42, 12.60it/s]

Preprocessing:  13%|█▎        | 1116/8455 [00:57<09:40, 12.65it/s]

Preprocessing:  13%|█▎        | 1118/8455 [00:57<08:55, 13.69it/s]

Preprocessing:  13%|█▎        | 1120/8455 [00:57<08:20, 14.66it/s]

Preprocessing:  13%|█▎        | 1122/8455 [00:57<07:57, 15.36it/s]

Preprocessing:  13%|█▎        | 1124/8455 [00:57<07:37, 16.04it/s]

Preprocessing:  13%|█▎        | 1126/8455 [00:57<08:13, 14.85it/s]

Preprocessing:  13%|█▎        | 1128/8455 [00:58<07:54, 15.44it/s]

Preprocessing:  13%|█▎        | 1130/8455 [00:58<07:36, 16.05it/s]

Preprocessing:  13%|█▎        | 1132/8455 [00:58<08:16, 14.75it/s]

Preprocessing:  13%|█▎        | 1134/8455 [00:58<08:37, 14.15it/s]

Preprocessing:  13%|█▎        | 1136/8455 [00:58<08:44, 13.96it/s]

Preprocessing:  13%|█▎        | 1138/8455 [00:58<08:14, 14.79it/s]

Preprocessing:  13%|█▎        | 1140/8455 [00:58<07:47, 15.64it/s]

Preprocessing:  14%|█▎        | 1142/8455 [00:59<08:52, 13.73it/s]

Preprocessing:  14%|█▎        | 1144/8455 [00:59<09:06, 13.37it/s]

Preprocessing:  14%|█▎        | 1146/8455 [00:59<08:33, 14.24it/s]

Preprocessing:  14%|█▎        | 1148/8455 [00:59<08:46, 13.89it/s]

Preprocessing:  14%|█▎        | 1150/8455 [00:59<08:25, 14.45it/s]

Preprocessing:  14%|█▎        | 1152/8455 [00:59<07:51, 15.47it/s]

Preprocessing:  14%|█▎        | 1154/8455 [00:59<08:28, 14.35it/s]

Preprocessing:  14%|█▎        | 1156/8455 [01:00<08:43, 13.94it/s]

Preprocessing:  14%|█▎        | 1158/8455 [01:00<08:11, 14.85it/s]

Preprocessing:  14%|█▎        | 1160/8455 [01:00<07:50, 15.51it/s]

Preprocessing:  14%|█▎        | 1162/8455 [01:00<07:27, 16.32it/s]

Preprocessing:  14%|█▍        | 1164/8455 [01:00<07:56, 15.30it/s]

Preprocessing:  14%|█▍        | 1166/8455 [01:00<08:15, 14.70it/s]

Preprocessing:  14%|█▍        | 1168/8455 [01:00<08:08, 14.92it/s]

Preprocessing:  14%|█▍        | 1170/8455 [01:00<08:05, 15.00it/s]

Preprocessing:  14%|█▍        | 1172/8455 [01:01<07:59, 15.20it/s]

Preprocessing:  14%|█▍        | 1174/8455 [01:01<07:53, 15.36it/s]

Preprocessing:  14%|█▍        | 1176/8455 [01:01<08:10, 14.83it/s]

Preprocessing:  14%|█▍        | 1178/8455 [01:01<08:01, 15.12it/s]

Preprocessing:  14%|█▍        | 1180/8455 [01:01<07:48, 15.51it/s]

Preprocessing:  14%|█▍        | 1182/8455 [01:01<07:39, 15.83it/s]

Preprocessing:  14%|█▍        | 1184/8455 [01:01<07:53, 15.35it/s]

Preprocessing:  14%|█▍        | 1186/8455 [01:01<08:11, 14.80it/s]

Preprocessing:  14%|█▍        | 1188/8455 [01:02<08:09, 14.85it/s]

Preprocessing:  14%|█▍        | 1190/8455 [01:02<09:22, 12.92it/s]

Preprocessing:  14%|█▍        | 1192/8455 [01:02<08:42, 13.90it/s]

Preprocessing:  14%|█▍        | 1194/8455 [01:02<08:25, 14.35it/s]

Preprocessing:  14%|█▍        | 1196/8455 [01:02<08:42, 13.89it/s]

Preprocessing:  14%|█▍        | 1198/8455 [01:02<08:51, 13.64it/s]

Preprocessing:  14%|█▍        | 1200/8455 [01:03<09:02, 13.39it/s]

Preprocessing:  14%|█▍        | 1202/8455 [01:03<08:18, 14.54it/s]

Preprocessing:  14%|█▍        | 1204/8455 [01:03<07:57, 15.20it/s]

Preprocessing:  14%|█▍        | 1206/8455 [01:03<07:54, 15.29it/s]

Preprocessing:  14%|█▍        | 1208/8455 [01:03<08:49, 13.69it/s]

Preprocessing:  14%|█▍        | 1210/8455 [01:03<09:43, 12.42it/s]

Preprocessing:  14%|█▍        | 1212/8455 [01:03<09:56, 12.14it/s]

Preprocessing:  14%|█▍        | 1214/8455 [01:04<09:29, 12.71it/s]

Preprocessing:  14%|█▍        | 1216/8455 [01:04<08:46, 13.74it/s]

Preprocessing:  14%|█▍        | 1218/8455 [01:04<09:07, 13.22it/s]

Preprocessing:  14%|█▍        | 1220/8455 [01:04<09:39, 12.48it/s]

Preprocessing:  14%|█▍        | 1222/8455 [01:04<09:26, 12.76it/s]

Preprocessing:  14%|█▍        | 1224/8455 [01:04<08:49, 13.65it/s]

Preprocessing:  15%|█▍        | 1226/8455 [01:04<08:19, 14.47it/s]

Preprocessing:  15%|█▍        | 1228/8455 [01:05<08:36, 13.99it/s]

Preprocessing:  15%|█▍        | 1230/8455 [01:05<09:26, 12.75it/s]

Preprocessing:  15%|█▍        | 1232/8455 [01:05<10:00, 12.03it/s]

Preprocessing:  15%|█▍        | 1234/8455 [01:05<09:16, 12.98it/s]

Preprocessing:  15%|█▍        | 1236/8455 [01:05<08:33, 14.06it/s]

Preprocessing:  15%|█▍        | 1238/8455 [01:05<08:13, 14.63it/s]

Preprocessing:  15%|█▍        | 1240/8455 [01:05<08:38, 13.91it/s]

Preprocessing:  15%|█▍        | 1242/8455 [01:06<08:45, 13.73it/s]

Preprocessing:  15%|█▍        | 1244/8455 [01:06<08:30, 14.11it/s]

Preprocessing:  15%|█▍        | 1246/8455 [01:06<08:04, 14.88it/s]

Preprocessing:  15%|█▍        | 1248/8455 [01:06<07:44, 15.51it/s]

Preprocessing:  15%|█▍        | 1250/8455 [01:06<07:28, 16.08it/s]

Preprocessing:  15%|█▍        | 1252/8455 [01:06<07:34, 15.86it/s]

Preprocessing:  15%|█▍        | 1254/8455 [01:06<07:31, 15.94it/s]

Preprocessing:  15%|█▍        | 1256/8455 [01:07<07:34, 15.84it/s]

Preprocessing:  15%|█▍        | 1258/8455 [01:07<07:32, 15.90it/s]

Preprocessing:  15%|█▍        | 1260/8455 [01:07<08:02, 14.90it/s]

Preprocessing:  15%|█▍        | 1262/8455 [01:07<08:37, 13.90it/s]

Preprocessing:  15%|█▍        | 1264/8455 [01:07<09:24, 12.73it/s]

Preprocessing:  15%|█▍        | 1266/8455 [01:07<08:49, 13.57it/s]

Preprocessing:  15%|█▍        | 1268/8455 [01:07<08:22, 14.31it/s]

Preprocessing:  15%|█▌        | 1270/8455 [01:08<08:07, 14.75it/s]

Preprocessing:  15%|█▌        | 1272/8455 [01:08<09:16, 12.90it/s]

Preprocessing:  15%|█▌        | 1274/8455 [01:08<09:45, 12.26it/s]

Preprocessing:  15%|█▌        | 1276/8455 [01:08<09:34, 12.49it/s]

Preprocessing:  15%|█▌        | 1278/8455 [01:08<08:46, 13.64it/s]

Preprocessing:  15%|█▌        | 1280/8455 [01:08<08:23, 14.25it/s]

Preprocessing:  15%|█▌        | 1282/8455 [01:08<08:00, 14.92it/s]

Preprocessing:  15%|█▌        | 1284/8455 [01:09<07:52, 15.18it/s]

Preprocessing:  15%|█▌        | 1286/8455 [01:09<09:00, 13.27it/s]

Preprocessing:  15%|█▌        | 1288/8455 [01:09<08:18, 14.37it/s]

Preprocessing:  15%|█▌        | 1290/8455 [01:09<07:56, 15.05it/s]

Preprocessing:  15%|█▌        | 1292/8455 [01:09<08:11, 14.58it/s]

Preprocessing:  15%|█▌        | 1294/8455 [01:09<07:55, 15.07it/s]

Preprocessing:  15%|█▌        | 1296/8455 [01:09<08:25, 14.15it/s]

Preprocessing:  15%|█▌        | 1298/8455 [01:10<08:09, 14.61it/s]

Preprocessing:  15%|█▌        | 1300/8455 [01:10<08:12, 14.51it/s]

Preprocessing:  15%|█▌        | 1302/8455 [01:10<07:57, 14.99it/s]

Preprocessing:  15%|█▌        | 1304/8455 [01:10<07:53, 15.09it/s]

Preprocessing:  15%|█▌        | 1306/8455 [01:10<09:06, 13.09it/s]

Preprocessing:  15%|█▌        | 1308/8455 [01:10<09:15, 12.87it/s]

Preprocessing:  15%|█▌        | 1310/8455 [01:10<08:45, 13.58it/s]

Preprocessing:  16%|█▌        | 1312/8455 [01:11<08:21, 14.24it/s]

Preprocessing:  16%|█▌        | 1314/8455 [01:11<07:57, 14.95it/s]

Preprocessing:  16%|█▌        | 1316/8455 [01:11<07:46, 15.29it/s]

Preprocessing:  16%|█▌        | 1318/8455 [01:11<08:04, 14.73it/s]

Preprocessing:  16%|█▌        | 1320/8455 [01:11<07:52, 15.09it/s]

Preprocessing:  16%|█▌        | 1322/8455 [01:11<07:45, 15.34it/s]

Preprocessing:  16%|█▌        | 1324/8455 [01:11<07:35, 15.65it/s]

Preprocessing:  16%|█▌        | 1326/8455 [01:11<08:14, 14.42it/s]

Preprocessing:  16%|█▌        | 1328/8455 [01:12<09:13, 12.88it/s]

Preprocessing:  16%|█▌        | 1330/8455 [01:12<08:30, 13.95it/s]

Preprocessing:  16%|█▌        | 1332/8455 [01:12<08:08, 14.58it/s]

Preprocessing:  16%|█▌        | 1334/8455 [01:12<07:51, 15.10it/s]

Preprocessing:  16%|█▌        | 1336/8455 [01:12<09:02, 13.13it/s]

Preprocessing:  16%|█▌        | 1338/8455 [01:12<09:07, 12.99it/s]

Preprocessing:  16%|█▌        | 1340/8455 [01:13<09:07, 13.00it/s]

Preprocessing:  16%|█▌        | 1342/8455 [01:13<08:36, 13.77it/s]

Preprocessing:  16%|█▌        | 1344/8455 [01:13<08:15, 14.37it/s]

Preprocessing:  16%|█▌        | 1346/8455 [01:13<08:03, 14.70it/s]

Preprocessing:  16%|█▌        | 1348/8455 [01:13<07:47, 15.19it/s]

Preprocessing:  16%|█▌        | 1350/8455 [01:13<07:43, 15.31it/s]

Preprocessing:  16%|█▌        | 1352/8455 [01:13<07:40, 15.42it/s]

Preprocessing:  16%|█▌        | 1354/8455 [01:13<07:29, 15.80it/s]

Preprocessing:  16%|█▌        | 1356/8455 [01:14<07:34, 15.62it/s]

Preprocessing:  16%|█▌        | 1358/8455 [01:14<08:08, 14.53it/s]

Preprocessing:  16%|█▌        | 1360/8455 [01:14<08:25, 14.05it/s]

Preprocessing:  16%|█▌        | 1362/8455 [01:14<08:04, 14.64it/s]

Preprocessing:  16%|█▌        | 1364/8455 [01:14<07:45, 15.22it/s]

Preprocessing:  16%|█▌        | 1366/8455 [01:14<07:30, 15.73it/s]

Preprocessing:  16%|█▌        | 1368/8455 [01:14<07:29, 15.76it/s]

Preprocessing:  16%|█▌        | 1370/8455 [01:14<07:20, 16.09it/s]

Preprocessing:  16%|█▌        | 1372/8455 [01:15<07:14, 16.31it/s]

Preprocessing:  16%|█▋        | 1374/8455 [01:15<07:08, 16.54it/s]

Preprocessing:  16%|█▋        | 1376/8455 [01:15<07:10, 16.44it/s]

Preprocessing:  16%|█▋        | 1378/8455 [01:15<08:29, 13.88it/s]

Preprocessing:  16%|█▋        | 1380/8455 [01:15<09:29, 12.42it/s]

Preprocessing:  16%|█▋        | 1382/8455 [01:15<10:06, 11.67it/s]

Preprocessing:  16%|█▋        | 1384/8455 [01:16<09:00, 13.08it/s]

Preprocessing:  16%|█▋        | 1386/8455 [01:16<08:25, 13.98it/s]

Preprocessing:  16%|█▋        | 1388/8455 [01:16<08:07, 14.49it/s]

Preprocessing:  16%|█▋        | 1390/8455 [01:16<09:07, 12.90it/s]

Preprocessing:  16%|█▋        | 1392/8455 [01:16<09:05, 12.94it/s]

Preprocessing:  16%|█▋        | 1394/8455 [01:16<08:24, 14.00it/s]

Preprocessing:  17%|█▋        | 1396/8455 [01:16<08:15, 14.25it/s]

Preprocessing:  17%|█▋        | 1398/8455 [01:16<08:00, 14.70it/s]

Preprocessing:  17%|█▋        | 1400/8455 [01:17<08:31, 13.79it/s]

Preprocessing:  17%|█▋        | 1402/8455 [01:17<09:32, 12.32it/s]

Preprocessing:  17%|█▋        | 1404/8455 [01:17<09:28, 12.39it/s]

Preprocessing:  17%|█▋        | 1406/8455 [01:17<10:40, 11.01it/s]

Preprocessing:  17%|█▋        | 1408/8455 [01:17<10:02, 11.70it/s]

Preprocessing:  17%|█▋        | 1410/8455 [01:18<09:37, 12.21it/s]

Preprocessing:  17%|█▋        | 1412/8455 [01:18<08:50, 13.29it/s]

Preprocessing:  17%|█▋        | 1414/8455 [01:18<09:17, 12.63it/s]

Preprocessing:  17%|█▋        | 1416/8455 [01:18<09:30, 12.33it/s]

Preprocessing:  17%|█▋        | 1418/8455 [01:18<09:16, 12.64it/s]

Preprocessing:  17%|█▋        | 1420/8455 [01:18<08:50, 13.25it/s]

Preprocessing:  17%|█▋        | 1422/8455 [01:18<08:30, 13.78it/s]

Preprocessing:  17%|█▋        | 1424/8455 [01:19<08:16, 14.16it/s]

Preprocessing:  17%|█▋        | 1426/8455 [01:19<08:01, 14.61it/s]

Preprocessing:  17%|█▋        | 1428/8455 [01:19<07:41, 15.24it/s]

Preprocessing:  17%|█▋        | 1430/8455 [01:19<07:46, 15.06it/s]

Preprocessing:  17%|█▋        | 1432/8455 [01:19<08:25, 13.90it/s]

Preprocessing:  17%|█▋        | 1434/8455 [01:19<09:38, 12.14it/s]

Preprocessing:  17%|█▋        | 1436/8455 [01:19<09:27, 12.38it/s]

Preprocessing:  17%|█▋        | 1438/8455 [01:20<08:48, 13.27it/s]

Preprocessing:  17%|█▋        | 1440/8455 [01:20<08:20, 14.01it/s]

Preprocessing:  17%|█▋        | 1442/8455 [01:20<09:12, 12.70it/s]

Preprocessing:  17%|█▋        | 1444/8455 [01:20<09:47, 11.94it/s]

Preprocessing:  17%|█▋        | 1446/8455 [01:20<09:40, 12.06it/s]

Preprocessing:  17%|█▋        | 1448/8455 [01:20<08:55, 13.08it/s]

Preprocessing:  17%|█▋        | 1450/8455 [01:21<08:42, 13.41it/s]

Preprocessing:  17%|█▋        | 1452/8455 [01:21<08:57, 13.02it/s]

Preprocessing:  17%|█▋        | 1454/8455 [01:21<09:07, 12.79it/s]

Preprocessing:  17%|█▋        | 1456/8455 [01:21<09:14, 12.63it/s]

Preprocessing:  17%|█▋        | 1458/8455 [01:21<08:33, 13.62it/s]

Preprocessing:  17%|█▋        | 1460/8455 [01:21<08:06, 14.37it/s]

Preprocessing:  17%|█▋        | 1462/8455 [01:21<08:27, 13.78it/s]

Preprocessing:  17%|█▋        | 1464/8455 [01:22<09:19, 12.50it/s]

Preprocessing:  17%|█▋        | 1466/8455 [01:22<09:18, 12.52it/s]

Preprocessing:  17%|█▋        | 1468/8455 [01:22<09:39, 12.06it/s]

Preprocessing:  17%|█▋        | 1470/8455 [01:22<09:10, 12.68it/s]

Preprocessing:  17%|█▋        | 1472/8455 [01:22<08:53, 13.08it/s]

Preprocessing:  17%|█▋        | 1474/8455 [01:22<09:23, 12.39it/s]

Preprocessing:  17%|█▋        | 1476/8455 [01:23<09:55, 11.73it/s]

Preprocessing:  17%|█▋        | 1478/8455 [01:23<10:17, 11.31it/s]

Preprocessing:  18%|█▊        | 1480/8455 [01:23<09:12, 12.63it/s]

Preprocessing:  18%|█▊        | 1482/8455 [01:23<08:31, 13.63it/s]

Preprocessing:  18%|█▊        | 1484/8455 [01:23<09:24, 12.35it/s]

Preprocessing:  18%|█▊        | 1486/8455 [01:23<09:17, 12.49it/s]

Preprocessing:  18%|█▊        | 1488/8455 [01:24<09:58, 11.65it/s]

Preprocessing:  18%|█▊        | 1490/8455 [01:24<08:54, 13.02it/s]

Preprocessing:  18%|█▊        | 1492/8455 [01:24<08:07, 14.27it/s]

Preprocessing:  18%|█▊        | 1494/8455 [01:24<07:44, 14.99it/s]

Preprocessing:  18%|█▊        | 1496/8455 [01:24<08:02, 14.44it/s]

Preprocessing:  18%|█▊        | 1498/8455 [01:24<09:00, 12.87it/s]

Preprocessing:  18%|█▊        | 1500/8455 [01:24<08:17, 13.99it/s]

Preprocessing:  18%|█▊        | 1502/8455 [01:24<07:43, 14.99it/s]

Preprocessing:  18%|█▊        | 1504/8455 [01:25<07:27, 15.53it/s]

Preprocessing:  18%|█▊        | 1506/8455 [01:25<07:45, 14.94it/s]

Preprocessing:  18%|█▊        | 1508/8455 [01:25<08:41, 13.32it/s]

Preprocessing:  18%|█▊        | 1510/8455 [01:25<08:42, 13.28it/s]

Preprocessing:  18%|█▊        | 1512/8455 [01:25<08:44, 13.23it/s]

Preprocessing:  18%|█▊        | 1514/8455 [01:25<08:32, 13.54it/s]

Preprocessing:  18%|█▊        | 1516/8455 [01:26<08:47, 13.14it/s]

Preprocessing:  18%|█▊        | 1518/8455 [01:26<09:35, 12.06it/s]

Preprocessing:  18%|█▊        | 1520/8455 [01:26<09:07, 12.67it/s]

Preprocessing:  18%|█▊        | 1522/8455 [01:26<09:06, 12.69it/s]

Preprocessing:  18%|█▊        | 1524/8455 [01:26<08:37, 13.40it/s]

Preprocessing:  18%|█▊        | 1526/8455 [01:26<08:28, 13.62it/s]

Preprocessing:  18%|█▊        | 1528/8455 [01:26<08:07, 14.20it/s]

Preprocessing:  18%|█▊        | 1530/8455 [01:27<07:41, 15.00it/s]

Preprocessing:  18%|█▊        | 1532/8455 [01:27<07:21, 15.70it/s]

Preprocessing:  18%|█▊        | 1534/8455 [01:27<07:30, 15.38it/s]

Preprocessing:  18%|█▊        | 1536/8455 [01:27<07:48, 14.77it/s]

Preprocessing:  18%|█▊        | 1538/8455 [01:27<08:04, 14.27it/s]

Preprocessing:  18%|█▊        | 1540/8455 [01:27<07:55, 14.53it/s]

Preprocessing:  18%|█▊        | 1542/8455 [01:27<07:40, 15.00it/s]

Preprocessing:  18%|█▊        | 1544/8455 [01:27<07:12, 15.97it/s]

Preprocessing:  18%|█▊        | 1546/8455 [01:28<06:52, 16.74it/s]

Preprocessing:  18%|█▊        | 1548/8455 [01:28<06:43, 17.10it/s]

Preprocessing:  18%|█▊        | 1550/8455 [01:28<06:34, 17.48it/s]

Preprocessing:  18%|█▊        | 1552/8455 [01:28<06:42, 17.17it/s]

Preprocessing:  18%|█▊        | 1554/8455 [01:28<06:47, 16.94it/s]

Preprocessing:  18%|█▊        | 1556/8455 [01:28<06:37, 17.37it/s]

Preprocessing:  18%|█▊        | 1558/8455 [01:28<06:49, 16.83it/s]

Preprocessing:  18%|█▊        | 1560/8455 [01:28<06:36, 17.39it/s]

Preprocessing:  18%|█▊        | 1562/8455 [01:28<06:37, 17.34it/s]

Preprocessing:  18%|█▊        | 1564/8455 [01:29<06:46, 16.97it/s]

Preprocessing:  19%|█▊        | 1566/8455 [01:29<06:48, 16.87it/s]

Preprocessing:  19%|█▊        | 1568/8455 [01:29<06:37, 17.33it/s]

Preprocessing:  19%|█▊        | 1570/8455 [01:29<06:35, 17.42it/s]

Preprocessing:  19%|█▊        | 1572/8455 [01:29<06:49, 16.79it/s]

Preprocessing:  19%|█▊        | 1574/8455 [01:29<07:31, 15.25it/s]

Preprocessing:  19%|█▊        | 1576/8455 [01:29<07:29, 15.30it/s]

Preprocessing:  19%|█▊        | 1578/8455 [01:29<07:16, 15.77it/s]

Preprocessing:  19%|█▊        | 1580/8455 [01:30<07:33, 15.16it/s]

Preprocessing:  19%|█▊        | 1582/8455 [01:30<08:04, 14.18it/s]

Preprocessing:  19%|█▊        | 1584/8455 [01:30<08:57, 12.79it/s]

Preprocessing:  19%|█▉        | 1586/8455 [01:30<08:13, 13.92it/s]

Preprocessing:  19%|█▉        | 1588/8455 [01:30<07:38, 14.97it/s]

Preprocessing:  19%|█▉        | 1590/8455 [01:30<07:23, 15.48it/s]

Preprocessing:  19%|█▉        | 1592/8455 [01:30<07:04, 16.16it/s]

Preprocessing:  19%|█▉        | 1594/8455 [01:31<06:50, 16.71it/s]

Preprocessing:  19%|█▉        | 1596/8455 [01:31<07:01, 16.27it/s]

Preprocessing:  19%|█▉        | 1598/8455 [01:31<06:41, 17.07it/s]

Preprocessing:  19%|█▉        | 1601/8455 [01:31<05:47, 19.71it/s]

Preprocessing:  19%|█▉        | 1604/8455 [01:31<05:18, 21.52it/s]

Preprocessing:  19%|█▉        | 1607/8455 [01:31<04:52, 23.38it/s]

Preprocessing:  19%|█▉        | 1610/8455 [01:31<04:39, 24.47it/s]

Preprocessing:  19%|█▉        | 1613/8455 [01:31<05:32, 20.58it/s]

Preprocessing:  19%|█▉        | 1616/8455 [01:32<05:10, 22.05it/s]

Preprocessing:  19%|█▉        | 1619/8455 [01:32<04:53, 23.30it/s]

Preprocessing:  19%|█▉        | 1622/8455 [01:32<05:11, 21.94it/s]

Preprocessing:  19%|█▉        | 1625/8455 [01:32<05:28, 20.80it/s]

Preprocessing:  19%|█▉        | 1628/8455 [01:32<05:23, 21.09it/s]

Preprocessing:  19%|█▉        | 1631/8455 [01:32<05:09, 22.07it/s]

Preprocessing:  19%|█▉        | 1634/8455 [01:32<04:54, 23.20it/s]

Preprocessing:  19%|█▉        | 1637/8455 [01:32<04:36, 24.62it/s]

Preprocessing:  19%|█▉        | 1640/8455 [01:33<04:31, 25.14it/s]

Preprocessing:  19%|█▉        | 1643/8455 [01:33<04:19, 26.23it/s]

Preprocessing:  19%|█▉        | 1646/8455 [01:33<04:16, 26.50it/s]

Preprocessing:  20%|█▉        | 1649/8455 [01:33<04:12, 26.99it/s]

Preprocessing:  20%|█▉        | 1652/8455 [01:33<04:04, 27.77it/s]

Preprocessing:  20%|█▉        | 1655/8455 [01:33<04:08, 27.34it/s]

Preprocessing:  20%|█▉        | 1658/8455 [01:33<05:11, 21.81it/s]

Preprocessing:  20%|█▉        | 1661/8455 [01:33<04:59, 22.69it/s]

Preprocessing:  20%|█▉        | 1664/8455 [01:34<05:10, 21.88it/s]

Preprocessing:  20%|█▉        | 1667/8455 [01:34<05:19, 21.22it/s]

Preprocessing:  20%|█▉        | 1670/8455 [01:34<05:25, 20.82it/s]

Preprocessing:  20%|█▉        | 1673/8455 [01:34<05:31, 20.46it/s]

Preprocessing:  20%|█▉        | 1676/8455 [01:34<05:09, 21.89it/s]

Preprocessing:  20%|█▉        | 1679/8455 [01:34<05:04, 22.26it/s]

Preprocessing:  20%|█▉        | 1682/8455 [01:34<04:58, 22.70it/s]

Preprocessing:  20%|█▉        | 1685/8455 [01:35<04:51, 23.26it/s]

Preprocessing:  20%|█▉        | 1688/8455 [01:35<04:40, 24.17it/s]

Preprocessing:  20%|██        | 1691/8455 [01:35<04:34, 24.67it/s]

Preprocessing:  20%|██        | 1694/8455 [01:35<04:33, 24.73it/s]

Preprocessing:  20%|██        | 1697/8455 [01:35<04:37, 24.38it/s]

Preprocessing:  20%|██        | 1700/8455 [01:35<04:24, 25.52it/s]

Preprocessing:  20%|██        | 1703/8455 [01:35<04:19, 26.05it/s]

Preprocessing:  20%|██        | 1706/8455 [01:35<04:14, 26.55it/s]

Preprocessing:  20%|██        | 1709/8455 [01:35<04:27, 25.20it/s]

Preprocessing:  20%|██        | 1712/8455 [01:36<04:35, 24.44it/s]

Preprocessing:  20%|██        | 1715/8455 [01:36<04:55, 22.80it/s]

Preprocessing:  20%|██        | 1718/8455 [01:36<04:56, 22.74it/s]

Preprocessing:  20%|██        | 1721/8455 [01:36<04:39, 24.09it/s]

Preprocessing:  20%|██        | 1725/8455 [01:36<04:19, 25.92it/s]

Preprocessing:  20%|██        | 1729/8455 [01:36<04:09, 26.98it/s]

Preprocessing:  20%|██        | 1732/8455 [01:36<04:11, 26.75it/s]

Preprocessing:  21%|██        | 1735/8455 [01:36<04:11, 26.69it/s]

Preprocessing:  21%|██        | 1738/8455 [01:37<04:07, 27.12it/s]

Preprocessing:  21%|██        | 1742/8455 [01:37<04:05, 27.31it/s]

Preprocessing:  21%|██        | 1745/8455 [01:37<04:06, 27.23it/s]

Preprocessing:  21%|██        | 1749/8455 [01:37<03:56, 28.33it/s]

Preprocessing:  21%|██        | 1753/8455 [01:37<03:50, 29.07it/s]

Preprocessing:  21%|██        | 1757/8455 [01:37<03:42, 30.17it/s]

Preprocessing:  21%|██        | 1761/8455 [01:37<03:46, 29.52it/s]

Preprocessing:  21%|██        | 1765/8455 [01:37<03:40, 30.36it/s]

Preprocessing:  21%|██        | 1769/8455 [01:38<03:36, 30.84it/s]

Preprocessing:  21%|██        | 1773/8455 [01:38<03:35, 30.99it/s]

Preprocessing:  21%|██        | 1777/8455 [01:38<03:36, 30.80it/s]

Preprocessing:  21%|██        | 1781/8455 [01:38<03:54, 28.50it/s]

Preprocessing:  21%|██        | 1785/8455 [01:38<03:47, 29.35it/s]

Preprocessing:  21%|██        | 1788/8455 [01:38<03:46, 29.39it/s]

Preprocessing:  21%|██        | 1792/8455 [01:38<03:42, 29.94it/s]

Preprocessing:  21%|██        | 1796/8455 [01:39<03:38, 30.41it/s]

Preprocessing:  21%|██▏       | 1800/8455 [01:39<03:35, 30.94it/s]

Preprocessing:  21%|██▏       | 1804/8455 [01:39<03:40, 30.21it/s]

Preprocessing:  21%|██▏       | 1808/8455 [01:39<03:42, 29.81it/s]

Preprocessing:  21%|██▏       | 1811/8455 [01:39<03:49, 28.93it/s]

Preprocessing:  21%|██▏       | 1814/8455 [01:39<04:09, 26.64it/s]

Preprocessing:  21%|██▏       | 1817/8455 [01:39<04:11, 26.36it/s]

Preprocessing:  22%|██▏       | 1821/8455 [01:39<03:58, 27.85it/s]

Preprocessing:  22%|██▏       | 1825/8455 [01:40<03:47, 29.18it/s]

Preprocessing:  22%|██▏       | 1828/8455 [01:40<03:45, 29.37it/s]

Preprocessing:  22%|██▏       | 1831/8455 [01:40<03:48, 28.93it/s]

Preprocessing:  22%|██▏       | 1834/8455 [01:40<03:49, 28.87it/s]

Preprocessing:  22%|██▏       | 1837/8455 [01:40<03:51, 28.55it/s]

Preprocessing:  22%|██▏       | 1841/8455 [01:40<03:42, 29.71it/s]

Preprocessing:  22%|██▏       | 1844/8455 [01:40<03:45, 29.36it/s]

Preprocessing:  22%|██▏       | 1847/8455 [01:40<03:48, 28.90it/s]

Preprocessing:  22%|██▏       | 1850/8455 [01:40<03:47, 29.06it/s]

Preprocessing:  22%|██▏       | 1854/8455 [01:41<03:40, 30.00it/s]

Preprocessing:  22%|██▏       | 1857/8455 [01:41<04:04, 27.01it/s]

Preprocessing:  22%|██▏       | 1860/8455 [01:41<03:57, 27.78it/s]

Preprocessing:  22%|██▏       | 1864/8455 [01:41<03:44, 29.31it/s]

Preprocessing:  22%|██▏       | 1868/8455 [01:41<03:38, 30.08it/s]

Preprocessing:  22%|██▏       | 1872/8455 [01:41<03:39, 30.02it/s]

Preprocessing:  22%|██▏       | 1876/8455 [01:41<03:38, 30.06it/s]

Preprocessing:  22%|██▏       | 1880/8455 [01:41<03:35, 30.48it/s]

Preprocessing:  22%|██▏       | 1884/8455 [01:42<03:34, 30.62it/s]

Preprocessing:  22%|██▏       | 1888/8455 [01:42<03:34, 30.64it/s]

Preprocessing:  22%|██▏       | 1892/8455 [01:42<03:47, 28.80it/s]

Preprocessing:  22%|██▏       | 1895/8455 [01:42<04:13, 25.87it/s]

Preprocessing:  22%|██▏       | 1898/8455 [01:42<04:15, 25.62it/s]

Preprocessing:  22%|██▏       | 1901/8455 [01:42<05:00, 21.82it/s]

Preprocessing:  23%|██▎       | 1904/8455 [01:42<05:09, 21.17it/s]

Preprocessing:  23%|██▎       | 1907/8455 [01:43<05:05, 21.46it/s]

Preprocessing:  23%|██▎       | 1910/8455 [01:43<05:05, 21.43it/s]

Preprocessing:  23%|██▎       | 1913/8455 [01:43<04:41, 23.24it/s]

Preprocessing:  23%|██▎       | 1917/8455 [01:43<04:17, 25.43it/s]

Preprocessing:  23%|██▎       | 1921/8455 [01:43<03:58, 27.39it/s]

Preprocessing:  23%|██▎       | 1925/8455 [01:43<03:50, 28.30it/s]

Preprocessing:  23%|██▎       | 1928/8455 [01:43<03:54, 27.81it/s]

Preprocessing:  23%|██▎       | 1931/8455 [01:43<04:02, 26.91it/s]

Preprocessing:  23%|██▎       | 1934/8455 [01:44<03:59, 27.23it/s]

Preprocessing:  23%|██▎       | 1938/8455 [01:44<03:48, 28.48it/s]

Preprocessing:  23%|██▎       | 1942/8455 [01:44<03:41, 29.38it/s]

Preprocessing:  23%|██▎       | 1946/8455 [01:44<03:37, 29.99it/s]

Preprocessing:  23%|██▎       | 1950/8455 [01:44<03:33, 30.53it/s]

Preprocessing:  23%|██▎       | 1954/8455 [01:44<03:32, 30.62it/s]

Preprocessing:  23%|██▎       | 1958/8455 [01:44<03:29, 30.94it/s]

Preprocessing:  23%|██▎       | 1962/8455 [01:44<03:39, 29.63it/s]

Preprocessing:  23%|██▎       | 1965/8455 [01:45<03:46, 28.61it/s]

Preprocessing:  23%|██▎       | 1968/8455 [01:45<03:51, 27.97it/s]

Preprocessing:  23%|██▎       | 1971/8455 [01:45<03:48, 28.39it/s]

Preprocessing:  23%|██▎       | 1974/8455 [01:45<03:48, 28.31it/s]

Preprocessing:  23%|██▎       | 1977/8455 [01:45<03:52, 27.82it/s]

Preprocessing:  23%|██▎       | 1981/8455 [01:45<03:47, 28.43it/s]

Preprocessing:  23%|██▎       | 1984/8455 [01:45<03:49, 28.25it/s]

Preprocessing:  24%|██▎       | 1987/8455 [01:45<04:04, 26.44it/s]

Preprocessing:  24%|██▎       | 1990/8455 [01:45<03:59, 26.95it/s]

Preprocessing:  24%|██▎       | 1993/8455 [01:46<03:57, 27.26it/s]

Preprocessing:  24%|██▎       | 1996/8455 [01:46<04:18, 25.01it/s]

Preprocessing:  24%|██▎       | 1999/8455 [01:46<04:34, 23.53it/s]

Preprocessing:  24%|██▎       | 2002/8455 [01:46<04:21, 24.66it/s]

Preprocessing:  24%|██▎       | 2005/8455 [01:46<04:14, 25.38it/s]

Preprocessing:  24%|██▎       | 2008/8455 [01:46<04:07, 26.06it/s]

Preprocessing:  24%|██▍       | 2011/8455 [01:46<04:08, 25.90it/s]

Preprocessing:  24%|██▍       | 2014/8455 [01:46<04:02, 26.53it/s]

Preprocessing:  24%|██▍       | 2018/8455 [01:47<03:55, 27.36it/s]

Preprocessing:  24%|██▍       | 2021/8455 [01:47<04:19, 24.80it/s]

Preprocessing:  24%|██▍       | 2024/8455 [01:47<04:10, 25.62it/s]

Preprocessing:  24%|██▍       | 2027/8455 [01:47<04:07, 25.92it/s]

Preprocessing:  24%|██▍       | 2030/8455 [01:47<04:07, 25.96it/s]

Preprocessing:  24%|██▍       | 2033/8455 [01:47<04:00, 26.68it/s]

Preprocessing:  24%|██▍       | 2036/8455 [01:47<03:58, 26.86it/s]

Preprocessing:  24%|██▍       | 2040/8455 [01:47<03:49, 27.94it/s]

Preprocessing:  24%|██▍       | 2043/8455 [01:47<03:46, 28.36it/s]

Preprocessing:  24%|██▍       | 2046/8455 [01:48<03:43, 28.66it/s]

Preprocessing:  24%|██▍       | 2049/8455 [01:48<04:05, 26.04it/s]

Preprocessing:  24%|██▍       | 2052/8455 [01:48<04:05, 26.08it/s]

Preprocessing:  24%|██▍       | 2055/8455 [01:48<04:02, 26.40it/s]

Preprocessing:  24%|██▍       | 2058/8455 [01:48<04:12, 25.37it/s]

Preprocessing:  24%|██▍       | 2061/8455 [01:48<04:24, 24.15it/s]

Preprocessing:  24%|██▍       | 2064/8455 [01:48<04:17, 24.81it/s]

Preprocessing:  24%|██▍       | 2067/8455 [01:48<04:13, 25.24it/s]

Preprocessing:  24%|██▍       | 2070/8455 [01:49<04:02, 26.31it/s]

Preprocessing:  25%|██▍       | 2073/8455 [01:49<04:57, 21.42it/s]

Preprocessing:  25%|██▍       | 2076/8455 [01:49<05:36, 18.96it/s]

Preprocessing:  25%|██▍       | 2079/8455 [01:49<05:56, 17.90it/s]

Preprocessing:  25%|██▍       | 2082/8455 [01:49<05:20, 19.91it/s]

Preprocessing:  25%|██▍       | 2085/8455 [01:49<04:59, 21.30it/s]

Preprocessing:  25%|██▍       | 2088/8455 [01:50<04:45, 22.34it/s]

Preprocessing:  25%|██▍       | 2091/8455 [01:50<05:46, 18.38it/s]

Preprocessing:  25%|██▍       | 2094/8455 [01:50<05:14, 20.20it/s]

Preprocessing:  25%|██▍       | 2097/8455 [01:50<04:56, 21.45it/s]

Preprocessing:  25%|██▍       | 2100/8455 [01:50<05:10, 20.50it/s]

Preprocessing:  25%|██▍       | 2103/8455 [01:50<06:19, 16.73it/s]

Preprocessing:  25%|██▍       | 2105/8455 [01:51<06:22, 16.62it/s]

Preprocessing:  25%|██▍       | 2107/8455 [01:51<06:12, 17.02it/s]

Preprocessing:  25%|██▍       | 2109/8455 [01:51<06:04, 17.43it/s]

Preprocessing:  25%|██▍       | 2111/8455 [01:51<06:00, 17.62it/s]

Preprocessing:  25%|██▍       | 2113/8455 [01:51<05:49, 18.15it/s]

Preprocessing:  25%|██▌       | 2115/8455 [01:51<05:56, 17.78it/s]

Preprocessing:  25%|██▌       | 2117/8455 [01:51<05:47, 18.22it/s]

Preprocessing:  25%|██▌       | 2119/8455 [01:51<05:41, 18.56it/s]

Preprocessing:  25%|██▌       | 2121/8455 [01:51<05:37, 18.74it/s]

Preprocessing:  25%|██▌       | 2123/8455 [01:51<05:37, 18.76it/s]

Preprocessing:  25%|██▌       | 2125/8455 [01:52<05:33, 18.98it/s]

Preprocessing:  25%|██▌       | 2127/8455 [01:52<06:43, 15.67it/s]

Preprocessing:  25%|██▌       | 2129/8455 [01:52<07:22, 14.30it/s]

Preprocessing:  25%|██▌       | 2131/8455 [01:52<07:57, 13.24it/s]

Preprocessing:  25%|██▌       | 2133/8455 [01:52<08:01, 13.13it/s]

Preprocessing:  25%|██▌       | 2135/8455 [01:52<07:37, 13.82it/s]

Preprocessing:  25%|██▌       | 2137/8455 [01:53<07:29, 14.05it/s]

Preprocessing:  25%|██▌       | 2139/8455 [01:53<07:23, 14.23it/s]

Preprocessing:  25%|██▌       | 2141/8455 [01:53<07:24, 14.20it/s]

Preprocessing:  25%|██▌       | 2143/8455 [01:53<07:20, 14.32it/s]

Preprocessing:  25%|██▌       | 2145/8455 [01:53<07:06, 14.78it/s]

Preprocessing:  25%|██▌       | 2147/8455 [01:53<06:58, 15.08it/s]

Preprocessing:  25%|██▌       | 2149/8455 [01:53<07:12, 14.59it/s]

Preprocessing:  25%|██▌       | 2151/8455 [01:53<07:20, 14.32it/s]

Preprocessing:  25%|██▌       | 2153/8455 [01:54<07:10, 14.63it/s]

Preprocessing:  25%|██▌       | 2155/8455 [01:54<07:11, 14.62it/s]

Preprocessing:  26%|██▌       | 2157/8455 [01:54<07:09, 14.68it/s]

Preprocessing:  26%|██▌       | 2159/8455 [01:54<07:29, 14.01it/s]

Preprocessing:  26%|██▌       | 2161/8455 [01:54<07:21, 14.27it/s]

Preprocessing:  26%|██▌       | 2163/8455 [01:54<07:42, 13.60it/s]

Preprocessing:  26%|██▌       | 2165/8455 [01:54<07:42, 13.61it/s]

Preprocessing:  26%|██▌       | 2167/8455 [01:55<07:19, 14.31it/s]

Preprocessing:  26%|██▌       | 2169/8455 [01:55<07:10, 14.61it/s]

Preprocessing:  26%|██▌       | 2171/8455 [01:55<07:23, 14.17it/s]

Preprocessing:  26%|██▌       | 2173/8455 [01:55<08:47, 11.91it/s]

Preprocessing:  26%|██▌       | 2175/8455 [01:55<09:06, 11.49it/s]

Preprocessing:  26%|██▌       | 2177/8455 [01:55<08:53, 11.77it/s]

Preprocessing:  26%|██▌       | 2179/8455 [01:56<08:47, 11.89it/s]

Preprocessing:  26%|██▌       | 2181/8455 [01:56<08:09, 12.82it/s]

Preprocessing:  26%|██▌       | 2183/8455 [01:56<07:45, 13.49it/s]

Preprocessing:  26%|██▌       | 2185/8455 [01:56<07:25, 14.07it/s]

Preprocessing:  26%|██▌       | 2187/8455 [01:56<07:10, 14.57it/s]

Preprocessing:  26%|██▌       | 2189/8455 [01:56<06:57, 15.00it/s]

Preprocessing:  26%|██▌       | 2191/8455 [01:56<07:27, 14.01it/s]

Preprocessing:  26%|██▌       | 2193/8455 [01:57<08:16, 12.61it/s]

Preprocessing:  26%|██▌       | 2195/8455 [01:57<08:14, 12.65it/s]

Preprocessing:  26%|██▌       | 2197/8455 [01:57<08:12, 12.71it/s]

Preprocessing:  26%|██▌       | 2199/8455 [01:57<07:37, 13.69it/s]

Preprocessing:  26%|██▌       | 2201/8455 [01:57<07:33, 13.81it/s]

Preprocessing:  26%|██▌       | 2203/8455 [01:57<07:57, 13.09it/s]

Preprocessing:  26%|██▌       | 2205/8455 [01:58<07:54, 13.16it/s]

Preprocessing:  26%|██▌       | 2207/8455 [01:58<07:43, 13.47it/s]

Preprocessing:  26%|██▌       | 2209/8455 [01:58<08:00, 13.00it/s]

Preprocessing:  26%|██▌       | 2211/8455 [01:58<07:35, 13.70it/s]

Preprocessing:  26%|██▌       | 2213/8455 [01:58<07:46, 13.38it/s]

Preprocessing:  26%|██▌       | 2215/8455 [01:58<07:20, 14.15it/s]

Preprocessing:  26%|██▌       | 2217/8455 [01:58<07:04, 14.71it/s]

Preprocessing:  26%|██▌       | 2219/8455 [01:58<06:49, 15.22it/s]

Preprocessing:  26%|██▋       | 2221/8455 [01:59<06:45, 15.37it/s]

Preprocessing:  26%|██▋       | 2223/8455 [01:59<07:06, 14.60it/s]

Preprocessing:  26%|██▋       | 2225/8455 [01:59<06:48, 15.23it/s]

Preprocessing:  26%|██▋       | 2227/8455 [01:59<07:18, 14.19it/s]

Preprocessing:  26%|██▋       | 2229/8455 [01:59<08:12, 12.64it/s]

Preprocessing:  26%|██▋       | 2231/8455 [01:59<08:13, 12.60it/s]

Preprocessing:  26%|██▋       | 2233/8455 [02:00<08:43, 11.88it/s]

Preprocessing:  26%|██▋       | 2235/8455 [02:00<09:11, 11.27it/s]

Preprocessing:  26%|██▋       | 2237/8455 [02:00<08:23, 12.35it/s]

Preprocessing:  26%|██▋       | 2239/8455 [02:00<08:53, 11.66it/s]

Preprocessing:  27%|██▋       | 2241/8455 [02:00<08:04, 12.82it/s]

Preprocessing:  27%|██▋       | 2243/8455 [02:00<07:24, 13.98it/s]

Preprocessing:  27%|██▋       | 2245/8455 [02:00<07:17, 14.18it/s]

Preprocessing:  27%|██▋       | 2247/8455 [02:01<06:49, 15.14it/s]

Preprocessing:  27%|██▋       | 2249/8455 [02:01<06:39, 15.53it/s]

Preprocessing:  27%|██▋       | 2251/8455 [02:01<07:04, 14.62it/s]

Preprocessing:  27%|██▋       | 2253/8455 [02:01<08:02, 12.86it/s]

Preprocessing:  27%|██▋       | 2255/8455 [02:01<08:04, 12.80it/s]

Preprocessing:  27%|██▋       | 2257/8455 [02:01<08:38, 11.96it/s]

Preprocessing:  27%|██▋       | 2259/8455 [02:02<08:01, 12.86it/s]

Preprocessing:  27%|██▋       | 2261/8455 [02:02<08:35, 12.01it/s]

Preprocessing:  27%|██▋       | 2263/8455 [02:02<08:34, 12.05it/s]

Preprocessing:  27%|██▋       | 2265/8455 [02:02<09:05, 11.35it/s]

Preprocessing:  27%|██▋       | 2267/8455 [02:02<08:50, 11.66it/s]

Preprocessing:  27%|██▋       | 2269/8455 [02:02<08:15, 12.48it/s]

Preprocessing:  27%|██▋       | 2271/8455 [02:03<07:43, 13.33it/s]

Preprocessing:  27%|██▋       | 2273/8455 [02:03<08:39, 11.90it/s]

Preprocessing:  27%|██▋       | 2275/8455 [02:03<08:00, 12.85it/s]

Preprocessing:  27%|██▋       | 2277/8455 [02:03<08:05, 12.71it/s]

Preprocessing:  27%|██▋       | 2279/8455 [02:03<08:43, 11.79it/s]

Preprocessing:  27%|██▋       | 2281/8455 [02:03<09:08, 11.26it/s]

Preprocessing:  27%|██▋       | 2283/8455 [02:04<08:45, 11.75it/s]

Preprocessing:  27%|██▋       | 2285/8455 [02:04<08:52, 11.59it/s]

Preprocessing:  27%|██▋       | 2287/8455 [02:04<09:15, 11.11it/s]

Preprocessing:  27%|██▋       | 2289/8455 [02:04<09:54, 10.38it/s]

Preprocessing:  27%|██▋       | 2291/8455 [02:04<10:52,  9.45it/s]

Preprocessing:  27%|██▋       | 2293/8455 [02:05<11:42,  8.77it/s]

Preprocessing:  27%|██▋       | 2295/8455 [02:05<10:59,  9.34it/s]

Preprocessing:  27%|██▋       | 2297/8455 [02:05<10:02, 10.22it/s]

Preprocessing:  27%|██▋       | 2299/8455 [02:05<09:03, 11.33it/s]

Preprocessing:  27%|██▋       | 2301/8455 [02:05<08:33, 11.99it/s]

Preprocessing:  27%|██▋       | 2303/8455 [02:05<08:02, 12.75it/s]

Preprocessing:  27%|██▋       | 2305/8455 [02:06<08:23, 12.22it/s]

Preprocessing:  27%|██▋       | 2307/8455 [02:06<08:19, 12.31it/s]

Preprocessing:  27%|██▋       | 2309/8455 [02:06<09:02, 11.32it/s]

Preprocessing:  27%|██▋       | 2311/8455 [02:06<08:53, 11.51it/s]

Preprocessing:  27%|██▋       | 2313/8455 [02:06<08:10, 12.52it/s]

Preprocessing:  27%|██▋       | 2315/8455 [02:06<07:37, 13.43it/s]

Preprocessing:  27%|██▋       | 2317/8455 [02:07<07:21, 13.89it/s]

Preprocessing:  27%|██▋       | 2319/8455 [02:07<07:13, 14.16it/s]

Preprocessing:  27%|██▋       | 2321/8455 [02:07<06:54, 14.81it/s]

Preprocessing:  27%|██▋       | 2323/8455 [02:07<07:02, 14.53it/s]

Preprocessing:  27%|██▋       | 2325/8455 [02:07<07:17, 14.00it/s]

Preprocessing:  28%|██▊       | 2327/8455 [02:07<07:26, 13.72it/s]

Preprocessing:  28%|██▊       | 2329/8455 [02:07<06:57, 14.67it/s]

Preprocessing:  28%|██▊       | 2331/8455 [02:07<06:29, 15.71it/s]

Preprocessing:  28%|██▊       | 2333/8455 [02:08<06:11, 16.50it/s]

Preprocessing:  28%|██▊       | 2335/8455 [02:08<05:59, 17.02it/s]

Preprocessing:  28%|██▊       | 2337/8455 [02:08<06:25, 15.87it/s]

Preprocessing:  28%|██▊       | 2339/8455 [02:08<06:38, 15.37it/s]

Preprocessing:  28%|██▊       | 2341/8455 [02:08<06:56, 14.69it/s]

Preprocessing:  28%|██▊       | 2343/8455 [02:08<07:50, 12.98it/s]

Preprocessing:  28%|██▊       | 2345/8455 [02:08<08:00, 12.72it/s]

Preprocessing:  28%|██▊       | 2347/8455 [02:09<08:16, 12.29it/s]

Preprocessing:  28%|██▊       | 2349/8455 [02:09<07:32, 13.48it/s]

Preprocessing:  28%|██▊       | 2351/8455 [02:09<07:39, 13.29it/s]

Preprocessing:  28%|██▊       | 2353/8455 [02:09<07:14, 14.05it/s]

Preprocessing:  28%|██▊       | 2355/8455 [02:09<06:41, 15.20it/s]

Preprocessing:  28%|██▊       | 2357/8455 [02:09<06:16, 16.20it/s]

Preprocessing:  28%|██▊       | 2359/8455 [02:09<06:45, 15.03it/s]

Preprocessing:  28%|██▊       | 2361/8455 [02:10<06:56, 14.62it/s]

Preprocessing:  28%|██▊       | 2363/8455 [02:10<07:15, 14.00it/s]

Preprocessing:  28%|██▊       | 2365/8455 [02:10<07:20, 13.83it/s]

Preprocessing:  28%|██▊       | 2367/8455 [02:10<07:58, 12.73it/s]

Preprocessing:  28%|██▊       | 2369/8455 [02:10<07:17, 13.91it/s]

Preprocessing:  28%|██▊       | 2371/8455 [02:10<06:51, 14.79it/s]

Preprocessing:  28%|██▊       | 2373/8455 [02:10<06:43, 15.06it/s]

Preprocessing:  28%|██▊       | 2375/8455 [02:11<07:01, 14.43it/s]

Preprocessing:  28%|██▊       | 2377/8455 [02:11<07:24, 13.66it/s]

Preprocessing:  28%|██▊       | 2379/8455 [02:11<07:48, 12.96it/s]

Preprocessing:  28%|██▊       | 2381/8455 [02:11<08:07, 12.47it/s]

Preprocessing:  28%|██▊       | 2383/8455 [02:11<07:56, 12.74it/s]

Preprocessing:  28%|██▊       | 2385/8455 [02:11<08:13, 12.29it/s]

Preprocessing:  28%|██▊       | 2387/8455 [02:12<07:53, 12.81it/s]

Preprocessing:  28%|██▊       | 2389/8455 [02:12<07:44, 13.05it/s]

Preprocessing:  28%|██▊       | 2391/8455 [02:12<08:00, 12.61it/s]

Preprocessing:  28%|██▊       | 2393/8455 [02:12<07:20, 13.77it/s]

Preprocessing:  28%|██▊       | 2395/8455 [02:12<06:53, 14.66it/s]

Preprocessing:  28%|██▊       | 2397/8455 [02:12<06:47, 14.87it/s]

Preprocessing:  28%|██▊       | 2399/8455 [02:12<06:40, 15.11it/s]

Preprocessing:  28%|██▊       | 2401/8455 [02:12<06:26, 15.66it/s]

Preprocessing:  28%|██▊       | 2403/8455 [02:13<06:16, 16.07it/s]

Preprocessing:  28%|██▊       | 2405/8455 [02:13<06:29, 15.52it/s]

Preprocessing:  28%|██▊       | 2407/8455 [02:13<06:59, 14.40it/s]

Preprocessing:  28%|██▊       | 2409/8455 [02:13<07:12, 13.96it/s]

Preprocessing:  29%|██▊       | 2411/8455 [02:13<07:26, 13.53it/s]

Preprocessing:  29%|██▊       | 2413/8455 [02:13<07:17, 13.81it/s]

Preprocessing:  29%|██▊       | 2415/8455 [02:13<07:05, 14.18it/s]

Preprocessing:  29%|██▊       | 2417/8455 [02:14<07:13, 13.94it/s]

Preprocessing:  29%|██▊       | 2419/8455 [02:14<07:02, 14.28it/s]

Preprocessing:  29%|██▊       | 2421/8455 [02:14<06:57, 14.45it/s]

Preprocessing:  29%|██▊       | 2423/8455 [02:14<07:07, 14.12it/s]

Preprocessing:  29%|██▊       | 2425/8455 [02:14<07:00, 14.35it/s]

Preprocessing:  29%|██▊       | 2427/8455 [02:14<07:11, 13.96it/s]

Preprocessing:  29%|██▊       | 2429/8455 [02:14<07:10, 14.01it/s]

Preprocessing:  29%|██▉       | 2431/8455 [02:15<07:05, 14.15it/s]

Preprocessing:  29%|██▉       | 2433/8455 [02:15<06:55, 14.48it/s]

Preprocessing:  29%|██▉       | 2435/8455 [02:15<06:49, 14.70it/s]

Preprocessing:  29%|██▉       | 2437/8455 [02:15<06:48, 14.72it/s]

Preprocessing:  29%|██▉       | 2439/8455 [02:15<07:10, 13.97it/s]

Preprocessing:  29%|██▉       | 2441/8455 [02:15<06:50, 14.66it/s]

Preprocessing:  29%|██▉       | 2443/8455 [02:15<06:46, 14.80it/s]

Preprocessing:  29%|██▉       | 2445/8455 [02:16<07:17, 13.75it/s]

Preprocessing:  29%|██▉       | 2447/8455 [02:16<08:13, 12.18it/s]

Preprocessing:  29%|██▉       | 2449/8455 [02:16<08:24, 11.90it/s]

Preprocessing:  29%|██▉       | 2451/8455 [02:16<08:32, 11.71it/s]

Preprocessing:  29%|██▉       | 2453/8455 [02:16<09:28, 10.56it/s]

Preprocessing:  29%|██▉       | 2455/8455 [02:17<09:43, 10.28it/s]

Preprocessing:  29%|██▉       | 2457/8455 [02:17<09:16, 10.78it/s]

Preprocessing:  29%|██▉       | 2459/8455 [02:17<09:02, 11.05it/s]

Preprocessing:  29%|██▉       | 2461/8455 [02:17<09:09, 10.91it/s]

Preprocessing:  29%|██▉       | 2463/8455 [02:17<09:21, 10.67it/s]

Preprocessing:  29%|██▉       | 2465/8455 [02:17<08:55, 11.19it/s]

Preprocessing:  29%|██▉       | 2467/8455 [02:18<08:14, 12.12it/s]

Preprocessing:  29%|██▉       | 2469/8455 [02:18<08:28, 11.76it/s]

Preprocessing:  29%|██▉       | 2471/8455 [02:18<08:40, 11.51it/s]

Preprocessing:  29%|██▉       | 2473/8455 [02:18<08:33, 11.65it/s]

Preprocessing:  29%|██▉       | 2475/8455 [02:18<07:55, 12.57it/s]

Preprocessing:  29%|██▉       | 2477/8455 [02:18<08:17, 12.01it/s]

Preprocessing:  29%|██▉       | 2479/8455 [02:19<08:47, 11.33it/s]

Preprocessing:  29%|██▉       | 2481/8455 [02:19<08:49, 11.29it/s]

Preprocessing:  29%|██▉       | 2483/8455 [02:19<09:30, 10.47it/s]

Preprocessing:  29%|██▉       | 2485/8455 [02:19<09:33, 10.41it/s]

Preprocessing:  29%|██▉       | 2487/8455 [02:19<09:41, 10.26it/s]

Preprocessing:  29%|██▉       | 2489/8455 [02:20<09:03, 10.98it/s]

Preprocessing:  29%|██▉       | 2491/8455 [02:20<08:48, 11.28it/s]

Preprocessing:  29%|██▉       | 2493/8455 [02:20<08:18, 11.96it/s]

Preprocessing:  30%|██▉       | 2495/8455 [02:20<08:42, 11.40it/s]

Preprocessing:  30%|██▉       | 2497/8455 [02:20<09:17, 10.69it/s]

Preprocessing:  30%|██▉       | 2499/8455 [02:20<08:34, 11.57it/s]

Preprocessing:  30%|██▉       | 2501/8455 [02:21<07:56, 12.50it/s]

Preprocessing:  30%|██▉       | 2503/8455 [02:21<08:03, 12.32it/s]

Preprocessing:  30%|██▉       | 2505/8455 [02:21<07:38, 12.98it/s]

Preprocessing:  30%|██▉       | 2507/8455 [02:21<07:43, 12.83it/s]

Preprocessing:  30%|██▉       | 2509/8455 [02:21<07:49, 12.66it/s]

Preprocessing:  30%|██▉       | 2511/8455 [02:21<07:21, 13.45it/s]

Preprocessing:  30%|██▉       | 2513/8455 [02:21<07:25, 13.35it/s]

Preprocessing:  30%|██▉       | 2515/8455 [02:22<07:42, 12.84it/s]

Preprocessing:  30%|██▉       | 2517/8455 [02:22<07:17, 13.56it/s]

Preprocessing:  30%|██▉       | 2519/8455 [02:22<08:41, 11.39it/s]

Preprocessing:  30%|██▉       | 2521/8455 [02:22<08:36, 11.49it/s]

Preprocessing:  30%|██▉       | 2523/8455 [02:22<08:43, 11.33it/s]

Preprocessing:  30%|██▉       | 2525/8455 [02:23<09:42, 10.18it/s]

Preprocessing:  30%|██▉       | 2527/8455 [02:23<09:43, 10.16it/s]

Preprocessing:  30%|██▉       | 2529/8455 [02:23<09:33, 10.33it/s]

Preprocessing:  30%|██▉       | 2531/8455 [02:23<09:02, 10.93it/s]

Preprocessing:  30%|██▉       | 2533/8455 [02:23<08:04, 12.23it/s]

Preprocessing:  30%|██▉       | 2535/8455 [02:23<07:34, 13.03it/s]

Preprocessing:  30%|███       | 2537/8455 [02:24<07:37, 12.94it/s]

Preprocessing:  30%|███       | 2539/8455 [02:24<08:09, 12.08it/s]

Preprocessing:  30%|███       | 2541/8455 [02:24<08:05, 12.18it/s]

Preprocessing:  30%|███       | 2543/8455 [02:24<08:32, 11.53it/s]

Preprocessing:  30%|███       | 2545/8455 [02:24<08:07, 12.11it/s]

Preprocessing:  30%|███       | 2547/8455 [02:24<08:06, 12.15it/s]

Preprocessing:  30%|███       | 2549/8455 [02:25<08:27, 11.64it/s]

Preprocessing:  30%|███       | 2551/8455 [02:25<08:16, 11.90it/s]

Preprocessing:  30%|███       | 2553/8455 [02:25<08:14, 11.92it/s]

Preprocessing:  30%|███       | 2555/8455 [02:25<09:05, 10.82it/s]

Preprocessing:  30%|███       | 2557/8455 [02:25<09:36, 10.24it/s]

Preprocessing:  30%|███       | 2559/8455 [02:26<09:00, 10.91it/s]

Preprocessing:  30%|███       | 2561/8455 [02:26<08:48, 11.16it/s]

Preprocessing:  30%|███       | 2563/8455 [02:26<08:59, 10.92it/s]

Preprocessing:  30%|███       | 2565/8455 [02:26<09:14, 10.62it/s]

Preprocessing:  30%|███       | 2567/8455 [02:26<08:48, 11.15it/s]

Preprocessing:  30%|███       | 2569/8455 [02:26<07:59, 12.27it/s]

Preprocessing:  30%|███       | 2571/8455 [02:27<08:19, 11.78it/s]

Preprocessing:  30%|███       | 2573/8455 [02:27<08:18, 11.81it/s]

Preprocessing:  30%|███       | 2575/8455 [02:27<08:37, 11.36it/s]

Preprocessing:  30%|███       | 2577/8455 [02:27<09:01, 10.85it/s]

Preprocessing:  31%|███       | 2579/8455 [02:27<08:58, 10.91it/s]

Preprocessing:  31%|███       | 2581/8455 [02:27<08:53, 11.01it/s]

Preprocessing:  31%|███       | 2583/8455 [02:28<08:39, 11.30it/s]

Preprocessing:  31%|███       | 2585/8455 [02:28<09:15, 10.57it/s]

Preprocessing:  31%|███       | 2587/8455 [02:28<09:29, 10.30it/s]

Preprocessing:  31%|███       | 2589/8455 [02:28<08:56, 10.94it/s]

Preprocessing:  31%|███       | 2591/8455 [02:28<09:13, 10.60it/s]

Preprocessing:  31%|███       | 2593/8455 [02:29<09:28, 10.32it/s]

Preprocessing:  31%|███       | 2595/8455 [02:29<08:38, 11.31it/s]

Preprocessing:  31%|███       | 2597/8455 [02:29<08:04, 12.09it/s]

Preprocessing:  31%|███       | 2599/8455 [02:29<08:13, 11.86it/s]

Preprocessing:  31%|███       | 2601/8455 [02:29<08:13, 11.87it/s]

Preprocessing:  31%|███       | 2603/8455 [02:29<08:19, 11.72it/s]

Preprocessing:  31%|███       | 2605/8455 [02:30<08:47, 11.08it/s]

Preprocessing:  31%|███       | 2607/8455 [02:30<08:23, 11.62it/s]

Preprocessing:  31%|███       | 2609/8455 [02:30<08:50, 11.02it/s]

Preprocessing:  31%|███       | 2611/8455 [02:30<08:32, 11.40it/s]

Preprocessing:  31%|███       | 2613/8455 [02:30<08:38, 11.26it/s]

Preprocessing:  31%|███       | 2615/8455 [02:30<08:41, 11.20it/s]

Preprocessing:  31%|███       | 2617/8455 [02:31<08:52, 10.97it/s]

Preprocessing:  31%|███       | 2619/8455 [02:31<09:26, 10.31it/s]

Preprocessing:  31%|███       | 2621/8455 [02:31<09:51,  9.87it/s]

Preprocessing:  31%|███       | 2623/8455 [02:31<09:46,  9.94it/s]

Preprocessing:  31%|███       | 2625/8455 [02:31<09:04, 10.71it/s]

Preprocessing:  31%|███       | 2627/8455 [02:32<08:40, 11.19it/s]

Preprocessing:  31%|███       | 2629/8455 [02:32<08:36, 11.29it/s]

Preprocessing:  31%|███       | 2631/8455 [02:32<08:23, 11.58it/s]

Preprocessing:  31%|███       | 2633/8455 [02:32<08:47, 11.03it/s]

Preprocessing:  31%|███       | 2635/8455 [02:32<09:15, 10.47it/s]

Preprocessing:  31%|███       | 2637/8455 [02:33<10:09,  9.54it/s]

Preprocessing:  31%|███       | 2638/8455 [02:33<10:17,  9.43it/s]

Preprocessing:  31%|███       | 2640/8455 [02:33<09:49,  9.86it/s]

Preprocessing:  31%|███       | 2641/8455 [02:33<10:11,  9.50it/s]

Preprocessing:  31%|███       | 2642/8455 [02:33<10:18,  9.41it/s]

Preprocessing:  31%|███▏      | 2644/8455 [02:33<09:09, 10.57it/s]

Preprocessing:  31%|███▏      | 2646/8455 [02:34<09:09, 10.58it/s]

Preprocessing:  31%|███▏      | 2648/8455 [02:34<08:50, 10.94it/s]

Preprocessing:  31%|███▏      | 2650/8455 [02:34<08:19, 11.61it/s]

Preprocessing:  31%|███▏      | 2652/8455 [02:34<08:20, 11.60it/s]

Preprocessing:  31%|███▏      | 2654/8455 [02:34<08:30, 11.36it/s]

Preprocessing:  31%|███▏      | 2656/8455 [02:34<08:53, 10.88it/s]

Preprocessing:  31%|███▏      | 2658/8455 [02:35<09:35, 10.07it/s]

Preprocessing:  31%|███▏      | 2660/8455 [02:35<09:03, 10.66it/s]

Preprocessing:  31%|███▏      | 2662/8455 [02:35<09:02, 10.68it/s]

Preprocessing:  32%|███▏      | 2664/8455 [02:35<08:16, 11.66it/s]

Preprocessing:  32%|███▏      | 2666/8455 [02:35<08:27, 11.42it/s]

Preprocessing:  32%|███▏      | 2668/8455 [02:35<08:17, 11.62it/s]

Preprocessing:  32%|███▏      | 2670/8455 [02:36<08:18, 11.61it/s]

Preprocessing:  32%|███▏      | 2672/8455 [02:36<08:07, 11.87it/s]

Preprocessing:  32%|███▏      | 2674/8455 [02:36<07:47, 12.37it/s]

Preprocessing:  32%|███▏      | 2676/8455 [02:36<07:12, 13.35it/s]

Preprocessing:  32%|███▏      | 2678/8455 [02:36<06:59, 13.76it/s]

Preprocessing:  32%|███▏      | 2680/8455 [02:36<07:09, 13.45it/s]

Preprocessing:  32%|███▏      | 2682/8455 [02:37<07:39, 12.56it/s]

Preprocessing:  32%|███▏      | 2684/8455 [02:37<07:29, 12.83it/s]

Preprocessing:  32%|███▏      | 2686/8455 [02:37<07:05, 13.55it/s]

Preprocessing:  32%|███▏      | 2688/8455 [02:37<07:28, 12.86it/s]

Preprocessing:  32%|███▏      | 2690/8455 [02:37<06:52, 13.96it/s]

Preprocessing:  32%|███▏      | 2692/8455 [02:37<06:38, 14.45it/s]

Preprocessing:  32%|███▏      | 2694/8455 [02:37<07:00, 13.71it/s]

Preprocessing:  32%|███▏      | 2696/8455 [02:38<07:38, 12.55it/s]

Preprocessing:  32%|███▏      | 2698/8455 [02:38<08:09, 11.76it/s]

Preprocessing:  32%|███▏      | 2700/8455 [02:38<07:59, 11.99it/s]

Preprocessing:  32%|███▏      | 2702/8455 [02:38<08:32, 11.23it/s]

Preprocessing:  32%|███▏      | 2704/8455 [02:38<08:16, 11.58it/s]

Preprocessing:  32%|███▏      | 2706/8455 [02:38<08:05, 11.84it/s]

Preprocessing:  32%|███▏      | 2708/8455 [02:39<07:56, 12.07it/s]

Preprocessing:  32%|███▏      | 2710/8455 [02:39<07:15, 13.20it/s]

Preprocessing:  32%|███▏      | 2712/8455 [02:39<07:16, 13.16it/s]

Preprocessing:  32%|███▏      | 2714/8455 [02:39<07:12, 13.26it/s]

Preprocessing:  32%|███▏      | 2716/8455 [02:39<07:42, 12.40it/s]

Preprocessing:  32%|███▏      | 2718/8455 [02:39<07:33, 12.66it/s]

Preprocessing:  32%|███▏      | 2720/8455 [02:40<07:31, 12.71it/s]

Preprocessing:  32%|███▏      | 2722/8455 [02:40<07:31, 12.70it/s]

Preprocessing:  32%|███▏      | 2724/8455 [02:40<07:29, 12.75it/s]

Preprocessing:  32%|███▏      | 2726/8455 [02:40<06:50, 13.94it/s]

Preprocessing:  32%|███▏      | 2728/8455 [02:40<07:31, 12.69it/s]

Preprocessing:  32%|███▏      | 2730/8455 [02:40<08:04, 11.81it/s]

Preprocessing:  32%|███▏      | 2732/8455 [02:41<08:28, 11.25it/s]

Preprocessing:  32%|███▏      | 2734/8455 [02:41<08:22, 11.39it/s]

Preprocessing:  32%|███▏      | 2736/8455 [02:41<08:08, 11.71it/s]

Preprocessing:  32%|███▏      | 2738/8455 [02:41<08:34, 11.11it/s]

Preprocessing:  32%|███▏      | 2740/8455 [02:41<08:52, 10.73it/s]

Preprocessing:  32%|███▏      | 2742/8455 [02:41<08:29, 11.21it/s]

Preprocessing:  32%|███▏      | 2744/8455 [02:42<08:54, 10.69it/s]

Preprocessing:  32%|███▏      | 2746/8455 [02:42<08:58, 10.61it/s]

Preprocessing:  33%|███▎      | 2748/8455 [02:42<08:37, 11.02it/s]

Preprocessing:  33%|███▎      | 2750/8455 [02:42<08:22, 11.35it/s]

Preprocessing:  33%|███▎      | 2752/8455 [02:42<08:15, 11.50it/s]

Preprocessing:  33%|███▎      | 2754/8455 [02:43<08:35, 11.07it/s]

Preprocessing:  33%|███▎      | 2756/8455 [02:43<07:58, 11.90it/s]

Preprocessing:  33%|███▎      | 2758/8455 [02:43<07:49, 12.13it/s]

Preprocessing:  33%|███▎      | 2760/8455 [02:43<08:09, 11.63it/s]

Preprocessing:  33%|███▎      | 2762/8455 [02:43<08:12, 11.57it/s]

Preprocessing:  33%|███▎      | 2764/8455 [02:43<07:37, 12.43it/s]

Preprocessing:  33%|███▎      | 2766/8455 [02:43<07:11, 13.19it/s]

Preprocessing:  33%|███▎      | 2768/8455 [02:44<06:57, 13.63it/s]

Preprocessing:  33%|███▎      | 2770/8455 [02:44<06:49, 13.88it/s]

Preprocessing:  33%|███▎      | 2772/8455 [02:44<06:43, 14.07it/s]

Preprocessing:  33%|███▎      | 2774/8455 [02:44<06:39, 14.23it/s]

Preprocessing:  33%|███▎      | 2776/8455 [02:44<06:48, 13.92it/s]

Preprocessing:  33%|███▎      | 2778/8455 [02:44<06:57, 13.58it/s]

Preprocessing:  33%|███▎      | 2780/8455 [02:45<08:00, 11.82it/s]

Preprocessing:  33%|███▎      | 2782/8455 [02:45<08:11, 11.53it/s]

Preprocessing:  33%|███▎      | 2784/8455 [02:45<08:10, 11.56it/s]

Preprocessing:  33%|███▎      | 2786/8455 [02:45<07:42, 12.24it/s]

Preprocessing:  33%|███▎      | 2788/8455 [02:45<07:31, 12.55it/s]

Preprocessing:  33%|███▎      | 2790/8455 [02:45<07:02, 13.41it/s]

Preprocessing:  33%|███▎      | 2792/8455 [02:45<06:55, 13.64it/s]

Preprocessing:  33%|███▎      | 2794/8455 [02:46<07:20, 12.84it/s]

Preprocessing:  33%|███▎      | 2796/8455 [02:46<08:07, 11.61it/s]

Preprocessing:  33%|███▎      | 2798/8455 [02:46<08:07, 11.61it/s]

Preprocessing:  33%|███▎      | 2800/8455 [02:46<07:32, 12.49it/s]

Preprocessing:  33%|███▎      | 2802/8455 [02:46<08:02, 11.72it/s]

Preprocessing:  33%|███▎      | 2804/8455 [02:46<07:51, 11.97it/s]

Preprocessing:  33%|███▎      | 2806/8455 [02:47<07:52, 11.96it/s]

Preprocessing:  33%|███▎      | 2808/8455 [02:47<07:53, 11.94it/s]

Preprocessing:  33%|███▎      | 2810/8455 [02:47<07:51, 11.97it/s]

Preprocessing:  33%|███▎      | 2812/8455 [02:47<08:29, 11.07it/s]

Preprocessing:  33%|███▎      | 2814/8455 [02:47<08:33, 10.98it/s]

Preprocessing:  33%|███▎      | 2816/8455 [02:48<09:00, 10.44it/s]

Preprocessing:  33%|███▎      | 2818/8455 [02:48<08:01, 11.71it/s]

Preprocessing:  33%|███▎      | 2820/8455 [02:48<07:15, 12.94it/s]

Preprocessing:  33%|███▎      | 2822/8455 [02:48<06:55, 13.56it/s]

Preprocessing:  33%|███▎      | 2824/8455 [02:48<06:22, 14.72it/s]

Preprocessing:  33%|███▎      | 2826/8455 [02:48<06:08, 15.27it/s]

Preprocessing:  33%|███▎      | 2828/8455 [02:48<06:26, 14.58it/s]

Preprocessing:  33%|███▎      | 2830/8455 [02:48<06:08, 15.27it/s]

Preprocessing:  33%|███▎      | 2832/8455 [02:49<05:59, 15.65it/s]

Preprocessing:  34%|███▎      | 2834/8455 [02:49<06:18, 14.84it/s]

Preprocessing:  34%|███▎      | 2836/8455 [02:49<06:38, 14.09it/s]

Preprocessing:  34%|███▎      | 2838/8455 [02:49<06:47, 13.77it/s]

Preprocessing:  34%|███▎      | 2840/8455 [02:49<06:52, 13.61it/s]

Preprocessing:  34%|███▎      | 2842/8455 [02:49<07:12, 12.99it/s]

Preprocessing:  34%|███▎      | 2844/8455 [02:50<07:25, 12.58it/s]

Preprocessing:  34%|███▎      | 2846/8455 [02:50<07:30, 12.44it/s]

Preprocessing:  34%|███▎      | 2848/8455 [02:50<06:55, 13.50it/s]

Preprocessing:  34%|███▎      | 2850/8455 [02:50<07:22, 12.67it/s]

Preprocessing:  34%|███▎      | 2852/8455 [02:50<07:51, 11.89it/s]

Preprocessing:  34%|███▍      | 2854/8455 [02:50<08:20, 11.19it/s]

Preprocessing:  34%|███▍      | 2856/8455 [02:51<08:11, 11.39it/s]

Preprocessing:  34%|███▍      | 2858/8455 [02:51<08:17, 11.24it/s]

Preprocessing:  34%|███▍      | 2860/8455 [02:51<08:31, 10.94it/s]

Preprocessing:  34%|███▍      | 2862/8455 [02:51<08:34, 10.88it/s]

Preprocessing:  34%|███▍      | 2864/8455 [02:51<08:18, 11.22it/s]

Preprocessing:  34%|███▍      | 2866/8455 [02:51<08:06, 11.48it/s]

Preprocessing:  34%|███▍      | 2868/8455 [02:52<08:31, 10.93it/s]

Preprocessing:  34%|███▍      | 2870/8455 [02:52<08:15, 11.27it/s]

Preprocessing:  34%|███▍      | 2872/8455 [02:52<07:52, 11.81it/s]

Preprocessing:  34%|███▍      | 2874/8455 [02:52<07:44, 12.01it/s]

Preprocessing:  34%|███▍      | 2876/8455 [02:52<08:12, 11.34it/s]

Preprocessing:  34%|███▍      | 2878/8455 [02:53<08:29, 10.94it/s]

Preprocessing:  34%|███▍      | 2880/8455 [02:53<08:22, 11.09it/s]

Preprocessing:  34%|███▍      | 2882/8455 [02:53<08:48, 10.55it/s]

Preprocessing:  34%|███▍      | 2884/8455 [02:53<09:00, 10.30it/s]

Preprocessing:  34%|███▍      | 2886/8455 [02:53<08:21, 11.10it/s]

Preprocessing:  34%|███▍      | 2888/8455 [02:53<07:46, 11.93it/s]

Preprocessing:  34%|███▍      | 2890/8455 [02:54<07:13, 12.84it/s]

Preprocessing:  34%|███▍      | 2892/8455 [02:54<07:11, 12.89it/s]

Preprocessing:  34%|███▍      | 2894/8455 [02:54<07:37, 12.15it/s]

Preprocessing:  34%|███▍      | 2896/8455 [02:54<07:15, 12.76it/s]

Preprocessing:  34%|███▍      | 2898/8455 [02:54<07:19, 12.65it/s]

Preprocessing:  34%|███▍      | 2900/8455 [02:54<07:07, 12.99it/s]

Preprocessing:  34%|███▍      | 2902/8455 [02:54<07:06, 13.03it/s]

Preprocessing:  34%|███▍      | 2904/8455 [02:55<06:57, 13.29it/s]

Preprocessing:  34%|███▍      | 2906/8455 [02:55<06:44, 13.71it/s]

Preprocessing:  34%|███▍      | 2908/8455 [02:55<06:40, 13.87it/s]

Preprocessing:  34%|███▍      | 2910/8455 [02:55<06:33, 14.09it/s]

Preprocessing:  34%|███▍      | 2912/8455 [02:55<06:28, 14.27it/s]

Preprocessing:  34%|███▍      | 2914/8455 [02:55<06:24, 14.43it/s]

Preprocessing:  34%|███▍      | 2916/8455 [02:55<06:31, 14.15it/s]

Preprocessing:  35%|███▍      | 2918/8455 [02:56<06:21, 14.52it/s]

Preprocessing:  35%|███▍      | 2920/8455 [02:56<06:19, 14.57it/s]

Preprocessing:  35%|███▍      | 2922/8455 [02:56<06:15, 14.75it/s]

Preprocessing:  35%|███▍      | 2924/8455 [02:56<06:11, 14.87it/s]

Preprocessing:  35%|███▍      | 2926/8455 [02:56<06:07, 15.03it/s]

Preprocessing:  35%|███▍      | 2928/8455 [02:56<06:16, 14.68it/s]

Preprocessing:  35%|███▍      | 2930/8455 [02:56<06:17, 14.63it/s]

Preprocessing:  35%|███▍      | 2932/8455 [02:57<06:02, 15.24it/s]

Preprocessing:  35%|███▍      | 2934/8455 [02:57<06:06, 15.06it/s]

Preprocessing:  35%|███▍      | 2936/8455 [02:57<06:04, 15.13it/s]

Preprocessing:  35%|███▍      | 2938/8455 [02:57<06:11, 14.84it/s]

Preprocessing:  35%|███▍      | 2940/8455 [02:57<06:10, 14.90it/s]

Preprocessing:  35%|███▍      | 2942/8455 [02:57<06:25, 14.28it/s]

Preprocessing:  35%|███▍      | 2944/8455 [02:57<06:36, 13.89it/s]

Preprocessing:  35%|███▍      | 2946/8455 [02:58<06:46, 13.55it/s]

Preprocessing:  35%|███▍      | 2948/8455 [02:58<06:42, 13.69it/s]

Preprocessing:  35%|███▍      | 2950/8455 [02:58<06:44, 13.62it/s]

Preprocessing:  35%|███▍      | 2952/8455 [02:58<06:59, 13.13it/s]

Preprocessing:  35%|███▍      | 2954/8455 [02:58<06:49, 13.42it/s]

Preprocessing:  35%|███▍      | 2956/8455 [02:58<06:58, 13.13it/s]

Preprocessing:  35%|███▍      | 2958/8455 [02:58<06:46, 13.52it/s]

Preprocessing:  35%|███▌      | 2960/8455 [02:59<07:12, 12.71it/s]

Preprocessing:  35%|███▌      | 2962/8455 [02:59<07:03, 12.97it/s]

Preprocessing:  35%|███▌      | 2964/8455 [02:59<06:56, 13.19it/s]

Preprocessing:  35%|███▌      | 2966/8455 [02:59<06:43, 13.62it/s]

Preprocessing:  35%|███▌      | 2968/8455 [02:59<06:33, 13.94it/s]

Preprocessing:  35%|███▌      | 2970/8455 [02:59<06:23, 14.30it/s]

Preprocessing:  35%|███▌      | 2972/8455 [02:59<06:29, 14.06it/s]

Preprocessing:  35%|███▌      | 2974/8455 [03:00<06:27, 14.13it/s]

Preprocessing:  35%|███▌      | 2976/8455 [03:00<06:30, 14.01it/s]

Preprocessing:  35%|███▌      | 2978/8455 [03:00<06:29, 14.08it/s]

Preprocessing:  35%|███▌      | 2980/8455 [03:00<06:44, 13.54it/s]

Preprocessing:  35%|███▌      | 2982/8455 [03:00<07:23, 12.34it/s]

Preprocessing:  35%|███▌      | 2984/8455 [03:00<07:35, 12.00it/s]

Preprocessing:  35%|███▌      | 2986/8455 [03:01<07:15, 12.55it/s]

Preprocessing:  35%|███▌      | 2988/8455 [03:01<06:53, 13.23it/s]

Preprocessing:  35%|███▌      | 2990/8455 [03:01<06:46, 13.43it/s]

Preprocessing:  35%|███▌      | 2992/8455 [03:01<06:36, 13.77it/s]

Preprocessing:  35%|███▌      | 2994/8455 [03:01<06:31, 13.95it/s]

Preprocessing:  35%|███▌      | 2996/8455 [03:01<06:32, 13.90it/s]

Preprocessing:  35%|███▌      | 2998/8455 [03:01<06:18, 14.41it/s]

Preprocessing:  35%|███▌      | 3000/8455 [03:01<06:09, 14.78it/s]

Preprocessing:  36%|███▌      | 3002/8455 [03:02<06:10, 14.70it/s]

Preprocessing:  36%|███▌      | 3004/8455 [03:02<06:19, 14.37it/s]

Preprocessing:  36%|███▌      | 3006/8455 [03:02<06:13, 14.57it/s]

Preprocessing:  36%|███▌      | 3008/8455 [03:02<06:27, 14.06it/s]

Preprocessing:  36%|███▌      | 3010/8455 [03:02<06:42, 13.54it/s]

Preprocessing:  36%|███▌      | 3012/8455 [03:02<07:05, 12.79it/s]

Preprocessing:  36%|███▌      | 3014/8455 [03:03<07:08, 12.69it/s]

Preprocessing:  36%|███▌      | 3016/8455 [03:03<06:53, 13.16it/s]

Preprocessing:  36%|███▌      | 3018/8455 [03:03<06:33, 13.82it/s]

Preprocessing:  36%|███▌      | 3020/8455 [03:03<06:16, 14.44it/s]

Preprocessing:  36%|███▌      | 3022/8455 [03:03<06:27, 14.03it/s]

Preprocessing:  36%|███▌      | 3024/8455 [03:03<06:30, 13.90it/s]

Preprocessing:  36%|███▌      | 3026/8455 [03:03<06:27, 14.00it/s]

Preprocessing:  36%|███▌      | 3028/8455 [03:04<06:26, 14.03it/s]

Preprocessing:  36%|███▌      | 3030/8455 [03:04<06:43, 13.45it/s]

Preprocessing:  36%|███▌      | 3032/8455 [03:04<06:47, 13.31it/s]

Preprocessing:  36%|███▌      | 3034/8455 [03:04<06:39, 13.56it/s]

Preprocessing:  36%|███▌      | 3036/8455 [03:04<06:25, 14.07it/s]

Preprocessing:  36%|███▌      | 3038/8455 [03:04<06:19, 14.26it/s]

Preprocessing:  36%|███▌      | 3040/8455 [03:04<06:16, 14.40it/s]

Preprocessing:  36%|███▌      | 3042/8455 [03:05<06:20, 14.23it/s]

Preprocessing:  36%|███▌      | 3044/8455 [03:05<06:16, 14.38it/s]

Preprocessing:  36%|███▌      | 3046/8455 [03:05<06:39, 13.54it/s]

Preprocessing:  36%|███▌      | 3048/8455 [03:05<06:30, 13.86it/s]

Preprocessing:  36%|███▌      | 3050/8455 [03:05<06:28, 13.90it/s]

Preprocessing:  36%|███▌      | 3052/8455 [03:05<06:27, 13.95it/s]

Preprocessing:  36%|███▌      | 3054/8455 [03:05<06:24, 14.03it/s]

Preprocessing:  36%|███▌      | 3056/8455 [03:06<06:25, 14.01it/s]

Preprocessing:  36%|███▌      | 3058/8455 [03:06<06:15, 14.39it/s]

Preprocessing:  36%|███▌      | 3060/8455 [03:06<05:59, 15.02it/s]

Preprocessing:  36%|███▌      | 3062/8455 [03:06<06:12, 14.48it/s]

Preprocessing:  36%|███▌      | 3064/8455 [03:06<06:12, 14.46it/s]

Preprocessing:  36%|███▋      | 3066/8455 [03:06<06:22, 14.09it/s]

Preprocessing:  36%|███▋      | 3068/8455 [03:06<06:33, 13.69it/s]

Preprocessing:  36%|███▋      | 3070/8455 [03:07<06:37, 13.55it/s]

Preprocessing:  36%|███▋      | 3072/8455 [03:07<06:30, 13.80it/s]

Preprocessing:  36%|███▋      | 3074/8455 [03:07<06:23, 14.03it/s]

Preprocessing:  36%|███▋      | 3076/8455 [03:07<06:07, 14.63it/s]

Preprocessing:  36%|███▋      | 3078/8455 [03:07<06:07, 14.65it/s]

Preprocessing:  36%|███▋      | 3080/8455 [03:07<06:14, 14.37it/s]

Preprocessing:  36%|███▋      | 3082/8455 [03:07<06:30, 13.77it/s]

Preprocessing:  36%|███▋      | 3084/8455 [03:07<06:04, 14.74it/s]

Preprocessing:  37%|███▋      | 3087/8455 [03:08<05:09, 17.34it/s]

Preprocessing:  37%|███▋      | 3089/8455 [03:08<05:50, 15.31it/s]

Preprocessing:  37%|███▋      | 3091/8455 [03:08<05:40, 15.76it/s]

Preprocessing:  37%|███▋      | 3093/8455 [03:08<05:25, 16.47it/s]

Preprocessing:  37%|███▋      | 3095/8455 [03:08<05:26, 16.40it/s]

Preprocessing:  37%|███▋      | 3097/8455 [03:08<05:25, 16.47it/s]

Preprocessing:  37%|███▋      | 3100/8455 [03:08<04:46, 18.72it/s]

Preprocessing:  37%|███▋      | 3102/8455 [03:08<04:43, 18.89it/s]

Preprocessing:  37%|███▋      | 3104/8455 [03:09<04:43, 18.89it/s]

Preprocessing:  37%|███▋      | 3107/8455 [03:09<04:20, 20.49it/s]

Preprocessing:  37%|███▋      | 3110/8455 [03:09<04:08, 21.53it/s]

Preprocessing:  37%|███▋      | 3113/8455 [03:09<04:03, 21.95it/s]

Preprocessing:  37%|███▋      | 3116/8455 [03:09<03:55, 22.65it/s]

Preprocessing:  37%|███▋      | 3119/8455 [03:09<03:48, 23.33it/s]

Preprocessing:  37%|███▋      | 3122/8455 [03:09<03:58, 22.39it/s]

Preprocessing:  37%|███▋      | 3125/8455 [03:09<03:46, 23.52it/s]

Preprocessing:  37%|███▋      | 3128/8455 [03:10<03:39, 24.25it/s]

Preprocessing:  37%|███▋      | 3131/8455 [03:10<04:10, 21.24it/s]

Preprocessing:  37%|███▋      | 3134/8455 [03:10<03:56, 22.47it/s]

Preprocessing:  37%|███▋      | 3137/8455 [03:10<03:42, 23.85it/s]

Preprocessing:  37%|███▋      | 3140/8455 [03:10<03:34, 24.77it/s]

Preprocessing:  37%|███▋      | 3143/8455 [03:10<03:45, 23.51it/s]

Preprocessing:  37%|███▋      | 3146/8455 [03:10<03:55, 22.57it/s]

Preprocessing:  37%|███▋      | 3149/8455 [03:11<03:57, 22.31it/s]

Preprocessing:  37%|███▋      | 3152/8455 [03:11<03:48, 23.19it/s]

Preprocessing:  37%|███▋      | 3155/8455 [03:11<03:54, 22.62it/s]

Preprocessing:  37%|███▋      | 3158/8455 [03:11<03:48, 23.22it/s]

Preprocessing:  37%|███▋      | 3161/8455 [03:11<03:44, 23.56it/s]

Preprocessing:  37%|███▋      | 3164/8455 [03:11<03:39, 24.08it/s]

Preprocessing:  37%|███▋      | 3167/8455 [03:11<03:43, 23.65it/s]

Preprocessing:  37%|███▋      | 3170/8455 [03:11<03:40, 23.98it/s]

Preprocessing:  38%|███▊      | 3173/8455 [03:12<03:39, 24.12it/s]

Preprocessing:  38%|███▊      | 3176/8455 [03:12<03:36, 24.37it/s]

Preprocessing:  38%|███▊      | 3179/8455 [03:12<03:41, 23.82it/s]

Preprocessing:  38%|███▊      | 3182/8455 [03:12<03:37, 24.20it/s]

Preprocessing:  38%|███▊      | 3185/8455 [03:12<03:38, 24.10it/s]

Preprocessing:  38%|███▊      | 3188/8455 [03:12<03:41, 23.80it/s]

Preprocessing:  38%|███▊      | 3191/8455 [03:12<03:44, 23.45it/s]

Preprocessing:  38%|███▊      | 3194/8455 [03:13<04:31, 19.36it/s]

Preprocessing:  38%|███▊      | 3197/8455 [03:13<05:19, 16.47it/s]

Preprocessing:  38%|███▊      | 3199/8455 [03:13<05:33, 15.78it/s]

Preprocessing:  38%|███▊      | 3201/8455 [03:13<05:41, 15.37it/s]

Preprocessing:  38%|███▊      | 3203/8455 [03:13<05:40, 15.43it/s]

Preprocessing:  38%|███▊      | 3205/8455 [03:13<05:41, 15.39it/s]

Preprocessing:  38%|███▊      | 3207/8455 [03:13<05:59, 14.60it/s]

Preprocessing:  38%|███▊      | 3209/8455 [03:14<05:49, 15.01it/s]

Preprocessing:  38%|███▊      | 3211/8455 [03:14<05:47, 15.07it/s]

Preprocessing:  38%|███▊      | 3213/8455 [03:14<06:15, 13.94it/s]

Preprocessing:  38%|███▊      | 3215/8455 [03:14<06:48, 12.83it/s]

Preprocessing:  38%|███▊      | 3217/8455 [03:14<06:34, 13.27it/s]

Preprocessing:  38%|███▊      | 3219/8455 [03:14<06:28, 13.49it/s]

Preprocessing:  38%|███▊      | 3221/8455 [03:15<07:02, 12.39it/s]

Preprocessing:  38%|███▊      | 3223/8455 [03:15<06:30, 13.40it/s]

Preprocessing:  38%|███▊      | 3225/8455 [03:15<06:10, 14.12it/s]

Preprocessing:  38%|███▊      | 3227/8455 [03:15<06:03, 14.38it/s]

Preprocessing:  38%|███▊      | 3229/8455 [03:15<05:57, 14.63it/s]

Preprocessing:  38%|███▊      | 3231/8455 [03:15<05:50, 14.90it/s]

Preprocessing:  38%|███▊      | 3233/8455 [03:15<06:07, 14.19it/s]

Preprocessing:  38%|███▊      | 3235/8455 [03:15<06:29, 13.39it/s]

Preprocessing:  38%|███▊      | 3237/8455 [03:16<06:46, 12.85it/s]

Preprocessing:  38%|███▊      | 3239/8455 [03:16<06:55, 12.54it/s]

Preprocessing:  38%|███▊      | 3241/8455 [03:16<06:59, 12.43it/s]

Preprocessing:  38%|███▊      | 3243/8455 [03:16<07:01, 12.38it/s]

Preprocessing:  38%|███▊      | 3245/8455 [03:16<07:31, 11.53it/s]

Preprocessing:  38%|███▊      | 3247/8455 [03:17<07:25, 11.69it/s]

Preprocessing:  38%|███▊      | 3249/8455 [03:17<07:46, 11.17it/s]

Preprocessing:  38%|███▊      | 3251/8455 [03:17<07:31, 11.54it/s]

Preprocessing:  38%|███▊      | 3253/8455 [03:17<07:53, 11.00it/s]

Preprocessing:  38%|███▊      | 3255/8455 [03:17<08:08, 10.64it/s]

Preprocessing:  39%|███▊      | 3257/8455 [03:17<08:14, 10.52it/s]

Preprocessing:  39%|███▊      | 3259/8455 [03:18<07:20, 11.81it/s]

Preprocessing:  39%|███▊      | 3261/8455 [03:18<07:40, 11.28it/s]

Preprocessing:  39%|███▊      | 3263/8455 [03:18<07:04, 12.23it/s]

Preprocessing:  39%|███▊      | 3265/8455 [03:18<07:08, 12.10it/s]

Preprocessing:  39%|███▊      | 3267/8455 [03:18<07:13, 11.98it/s]

Preprocessing:  39%|███▊      | 3269/8455 [03:18<06:46, 12.77it/s]

Preprocessing:  39%|███▊      | 3271/8455 [03:19<06:58, 12.39it/s]

Preprocessing:  39%|███▊      | 3273/8455 [03:19<07:21, 11.73it/s]

Preprocessing:  39%|███▊      | 3275/8455 [03:19<07:25, 11.64it/s]

Preprocessing:  39%|███▉      | 3277/8455 [03:19<07:58, 10.82it/s]

Preprocessing:  39%|███▉      | 3279/8455 [03:19<07:47, 11.07it/s]

Preprocessing:  39%|███▉      | 3281/8455 [03:19<07:34, 11.39it/s]

Preprocessing:  39%|███▉      | 3283/8455 [03:20<07:57, 10.84it/s]

Preprocessing:  39%|███▉      | 3285/8455 [03:20<08:19, 10.36it/s]

Preprocessing:  39%|███▉      | 3287/8455 [03:20<08:24, 10.25it/s]

Preprocessing:  39%|███▉      | 3289/8455 [03:20<08:01, 10.73it/s]

Preprocessing:  39%|███▉      | 3291/8455 [03:20<07:52, 10.92it/s]

Preprocessing:  39%|███▉      | 3293/8455 [03:21<07:36, 11.32it/s]

Preprocessing:  39%|███▉      | 3295/8455 [03:21<07:28, 11.50it/s]

Preprocessing:  39%|███▉      | 3297/8455 [03:21<07:47, 11.03it/s]

Preprocessing:  39%|███▉      | 3299/8455 [03:21<07:37, 11.26it/s]

Preprocessing:  39%|███▉      | 3301/8455 [03:21<08:03, 10.66it/s]

Preprocessing:  39%|███▉      | 3303/8455 [03:22<08:23, 10.23it/s]

Preprocessing:  39%|███▉      | 3305/8455 [03:22<08:36,  9.97it/s]

Preprocessing:  39%|███▉      | 3307/8455 [03:22<08:09, 10.52it/s]

Preprocessing:  39%|███▉      | 3309/8455 [03:22<07:39, 11.19it/s]

Preprocessing:  39%|███▉      | 3311/8455 [03:22<07:22, 11.61it/s]

Preprocessing:  39%|███▉      | 3313/8455 [03:22<07:45, 11.04it/s]

Preprocessing:  39%|███▉      | 3315/8455 [03:23<07:59, 10.73it/s]

Preprocessing:  39%|███▉      | 3317/8455 [03:23<07:36, 11.26it/s]

Preprocessing:  39%|███▉      | 3319/8455 [03:23<06:54, 12.38it/s]

Preprocessing:  39%|███▉      | 3321/8455 [03:23<06:26, 13.28it/s]

Preprocessing:  39%|███▉      | 3323/8455 [03:23<06:08, 13.94it/s]

Preprocessing:  39%|███▉      | 3325/8455 [03:23<05:53, 14.53it/s]

Preprocessing:  39%|███▉      | 3327/8455 [03:23<05:44, 14.88it/s]

Preprocessing:  39%|███▉      | 3329/8455 [03:24<06:12, 13.77it/s]

Preprocessing:  39%|███▉      | 3331/8455 [03:24<06:55, 12.32it/s]

Preprocessing:  39%|███▉      | 3333/8455 [03:24<07:28, 11.42it/s]

Preprocessing:  39%|███▉      | 3335/8455 [03:24<07:56, 10.75it/s]

Preprocessing:  39%|███▉      | 3337/8455 [03:24<07:34, 11.26it/s]

Preprocessing:  39%|███▉      | 3339/8455 [03:25<07:59, 10.66it/s]

Preprocessing:  40%|███▉      | 3341/8455 [03:25<08:07, 10.49it/s]

Preprocessing:  40%|███▉      | 3343/8455 [03:25<08:21, 10.20it/s]

Preprocessing:  40%|███▉      | 3345/8455 [03:25<08:24, 10.12it/s]

Preprocessing:  40%|███▉      | 3347/8455 [03:25<08:03, 10.57it/s]

Preprocessing:  40%|███▉      | 3349/8455 [03:26<07:44, 10.99it/s]

Preprocessing:  40%|███▉      | 3351/8455 [03:26<07:28, 11.38it/s]

Preprocessing:  40%|███▉      | 3353/8455 [03:26<07:50, 10.84it/s]

Preprocessing:  40%|███▉      | 3355/8455 [03:26<07:39, 11.11it/s]

Preprocessing:  40%|███▉      | 3357/8455 [03:26<07:24, 11.47it/s]

Preprocessing:  40%|███▉      | 3359/8455 [03:26<06:52, 12.35it/s]

Preprocessing:  40%|███▉      | 3361/8455 [03:27<07:18, 11.62it/s]

Preprocessing:  40%|███▉      | 3363/8455 [03:27<07:07, 11.90it/s]

Preprocessing:  40%|███▉      | 3365/8455 [03:27<07:25, 11.43it/s]

Preprocessing:  40%|███▉      | 3367/8455 [03:27<07:44, 10.96it/s]

Preprocessing:  40%|███▉      | 3369/8455 [03:27<07:02, 12.04it/s]

Preprocessing:  40%|███▉      | 3371/8455 [03:27<07:01, 12.06it/s]

Preprocessing:  40%|███▉      | 3373/8455 [03:28<07:27, 11.35it/s]

Preprocessing:  40%|███▉      | 3375/8455 [03:28<07:45, 10.91it/s]

Preprocessing:  40%|███▉      | 3377/8455 [03:28<07:58, 10.61it/s]

Preprocessing:  40%|███▉      | 3379/8455 [03:28<07:37, 11.09it/s]

Preprocessing:  40%|███▉      | 3381/8455 [03:28<07:34, 11.17it/s]

Preprocessing:  40%|████      | 3383/8455 [03:29<07:23, 11.45it/s]

Preprocessing:  40%|████      | 3385/8455 [03:29<07:22, 11.45it/s]

Preprocessing:  40%|████      | 3387/8455 [03:29<07:05, 11.90it/s]

Preprocessing:  40%|████      | 3389/8455 [03:29<06:43, 12.54it/s]

Preprocessing:  40%|████      | 3391/8455 [03:29<06:46, 12.46it/s]

Preprocessing:  40%|████      | 3393/8455 [03:29<07:03, 11.97it/s]

Preprocessing:  40%|████      | 3395/8455 [03:30<07:22, 11.43it/s]

Preprocessing:  40%|████      | 3397/8455 [03:30<07:12, 11.70it/s]

Preprocessing:  40%|████      | 3399/8455 [03:30<08:02, 10.47it/s]

Preprocessing:  40%|████      | 3401/8455 [03:30<07:58, 10.55it/s]

Preprocessing:  40%|████      | 3403/8455 [03:30<07:48, 10.79it/s]

Preprocessing:  40%|████      | 3405/8455 [03:30<07:34, 11.12it/s]

Preprocessing:  40%|████      | 3407/8455 [03:31<07:14, 11.61it/s]

Preprocessing:  40%|████      | 3409/8455 [03:31<07:34, 11.11it/s]

Preprocessing:  40%|████      | 3411/8455 [03:31<07:25, 11.32it/s]

Preprocessing:  40%|████      | 3413/8455 [03:31<07:15, 11.59it/s]

Preprocessing:  40%|████      | 3415/8455 [03:31<07:15, 11.56it/s]

Preprocessing:  40%|████      | 3417/8455 [03:31<07:17, 11.50it/s]

Preprocessing:  40%|████      | 3419/8455 [03:32<07:14, 11.60it/s]

Preprocessing:  40%|████      | 3421/8455 [03:32<07:58, 10.53it/s]

Preprocessing:  40%|████      | 3423/8455 [03:32<07:38, 10.96it/s]

Preprocessing:  41%|████      | 3425/8455 [03:32<07:42, 10.87it/s]

Preprocessing:  41%|████      | 3427/8455 [03:32<07:46, 10.78it/s]

Preprocessing:  41%|████      | 3429/8455 [03:33<08:32,  9.80it/s]

Preprocessing:  41%|████      | 3431/8455 [03:33<08:39,  9.68it/s]

Preprocessing:  41%|████      | 3433/8455 [03:33<08:06, 10.33it/s]

Preprocessing:  41%|████      | 3435/8455 [03:33<08:12, 10.18it/s]

Preprocessing:  41%|████      | 3437/8455 [03:33<07:49, 10.68it/s]

Preprocessing:  41%|████      | 3439/8455 [03:34<08:20, 10.03it/s]

Preprocessing:  41%|████      | 3441/8455 [03:34<08:17, 10.08it/s]

Preprocessing:  41%|████      | 3443/8455 [03:34<09:02,  9.24it/s]

Preprocessing:  41%|████      | 3444/8455 [03:34<09:15,  9.03it/s]

Preprocessing:  41%|████      | 3445/8455 [03:34<09:31,  8.76it/s]

Preprocessing:  41%|████      | 3447/8455 [03:35<08:20, 10.01it/s]

Preprocessing:  41%|████      | 3449/8455 [03:35<08:19, 10.02it/s]

Preprocessing:  41%|████      | 3451/8455 [03:35<08:07, 10.25it/s]

Preprocessing:  41%|████      | 3453/8455 [03:35<07:39, 10.88it/s]

Preprocessing:  41%|████      | 3455/8455 [03:35<08:27,  9.85it/s]

Preprocessing:  41%|████      | 3457/8455 [03:35<07:59, 10.42it/s]

Preprocessing:  41%|████      | 3459/8455 [03:36<07:48, 10.66it/s]

Preprocessing:  41%|████      | 3461/8455 [03:36<08:19,  9.99it/s]

Preprocessing:  41%|████      | 3463/8455 [03:36<08:44,  9.51it/s]

Preprocessing:  41%|████      | 3464/8455 [03:36<08:55,  9.31it/s]

Preprocessing:  41%|████      | 3466/8455 [03:36<08:26,  9.86it/s]

Preprocessing:  41%|████      | 3468/8455 [03:37<08:13, 10.10it/s]

Preprocessing:  41%|████      | 3470/8455 [03:37<07:58, 10.41it/s]

Preprocessing:  41%|████      | 3472/8455 [03:37<07:40, 10.81it/s]

Preprocessing:  41%|████      | 3474/8455 [03:37<08:20,  9.96it/s]

Preprocessing:  41%|████      | 3476/8455 [03:37<08:21,  9.93it/s]

Preprocessing:  41%|████      | 3478/8455 [03:38<08:07, 10.22it/s]

Preprocessing:  41%|████      | 3480/8455 [03:38<08:04, 10.27it/s]

Preprocessing:  41%|████      | 3482/8455 [03:38<08:15, 10.03it/s]

Preprocessing:  41%|████      | 3484/8455 [03:38<08:45,  9.46it/s]

Preprocessing:  41%|████      | 3485/8455 [03:38<08:54,  9.31it/s]

Preprocessing:  41%|████      | 3487/8455 [03:38<08:11, 10.12it/s]

Preprocessing:  41%|████▏     | 3489/8455 [03:39<08:00, 10.34it/s]

Preprocessing:  41%|████▏     | 3491/8455 [03:39<07:59, 10.36it/s]

Preprocessing:  41%|████▏     | 3493/8455 [03:39<08:01, 10.31it/s]

Preprocessing:  41%|████▏     | 3495/8455 [03:39<08:09, 10.13it/s]

Preprocessing:  41%|████▏     | 3497/8455 [03:39<07:46, 10.64it/s]

Preprocessing:  41%|████▏     | 3499/8455 [03:40<07:50, 10.54it/s]

Preprocessing:  41%|████▏     | 3501/8455 [03:40<07:45, 10.63it/s]

Preprocessing:  41%|████▏     | 3503/8455 [03:40<07:33, 10.92it/s]

Preprocessing:  41%|████▏     | 3505/8455 [03:40<08:09, 10.12it/s]

Preprocessing:  41%|████▏     | 3507/8455 [03:40<08:00, 10.29it/s]

Preprocessing:  42%|████▏     | 3509/8455 [03:41<08:12, 10.04it/s]

Preprocessing:  42%|████▏     | 3511/8455 [03:41<08:06, 10.16it/s]

Preprocessing:  42%|████▏     | 3513/8455 [03:41<08:10, 10.08it/s]

Preprocessing:  42%|████▏     | 3515/8455 [03:41<07:53, 10.43it/s]

Preprocessing:  42%|████▏     | 3517/8455 [03:41<08:16,  9.94it/s]

Preprocessing:  42%|████▏     | 3519/8455 [03:42<08:57,  9.19it/s]

Preprocessing:  42%|████▏     | 3521/8455 [03:42<08:23,  9.80it/s]

Preprocessing:  42%|████▏     | 3523/8455 [03:42<08:35,  9.57it/s]

Preprocessing:  42%|████▏     | 3524/8455 [03:42<08:40,  9.47it/s]

Preprocessing:  42%|████▏     | 3525/8455 [03:42<08:51,  9.27it/s]

Preprocessing:  42%|████▏     | 3526/8455 [03:42<08:57,  9.17it/s]

Preprocessing:  42%|████▏     | 3528/8455 [03:43<08:30,  9.66it/s]

Preprocessing:  42%|████▏     | 3530/8455 [03:43<08:24,  9.77it/s]

Preprocessing:  42%|████▏     | 3532/8455 [03:43<07:50, 10.46it/s]

Preprocessing:  42%|████▏     | 3534/8455 [03:43<08:18,  9.88it/s]

Preprocessing:  42%|████▏     | 3535/8455 [03:43<08:20,  9.83it/s]

Preprocessing:  42%|████▏     | 3536/8455 [03:43<08:26,  9.72it/s]

Preprocessing:  42%|████▏     | 3538/8455 [03:44<07:42, 10.64it/s]

Preprocessing:  42%|████▏     | 3540/8455 [03:44<07:58, 10.26it/s]

Preprocessing:  42%|████▏     | 3542/8455 [03:44<08:03, 10.16it/s]

Preprocessing:  42%|████▏     | 3544/8455 [03:44<07:13, 11.34it/s]

Preprocessing:  42%|████▏     | 3546/8455 [03:44<07:34, 10.79it/s]

Preprocessing:  42%|████▏     | 3548/8455 [03:44<07:39, 10.68it/s]

Preprocessing:  42%|████▏     | 3550/8455 [03:45<07:52, 10.39it/s]

Preprocessing:  42%|████▏     | 3552/8455 [03:45<08:13,  9.93it/s]

Preprocessing:  42%|████▏     | 3554/8455 [03:45<08:28,  9.64it/s]

Preprocessing:  42%|████▏     | 3556/8455 [03:45<08:12,  9.96it/s]

Preprocessing:  42%|████▏     | 3558/8455 [03:46<08:20,  9.78it/s]

Preprocessing:  42%|████▏     | 3560/8455 [03:46<07:32, 10.82it/s]

Preprocessing:  42%|████▏     | 3562/8455 [03:46<07:06, 11.47it/s]

Preprocessing:  42%|████▏     | 3564/8455 [03:46<07:01, 11.60it/s]

Preprocessing:  42%|████▏     | 3566/8455 [03:46<07:15, 11.22it/s]

Preprocessing:  42%|████▏     | 3568/8455 [03:46<07:41, 10.60it/s]

Preprocessing:  42%|████▏     | 3570/8455 [03:47<07:43, 10.54it/s]

Preprocessing:  42%|████▏     | 3572/8455 [03:47<08:01, 10.15it/s]

Preprocessing:  42%|████▏     | 3574/8455 [03:47<08:14,  9.86it/s]

Preprocessing:  42%|████▏     | 3575/8455 [03:47<08:22,  9.72it/s]

Preprocessing:  42%|████▏     | 3576/8455 [03:47<08:27,  9.61it/s]

Preprocessing:  42%|████▏     | 3578/8455 [03:47<08:16,  9.82it/s]

Preprocessing:  42%|████▏     | 3580/8455 [03:48<07:56, 10.23it/s]

Preprocessing:  42%|████▏     | 3582/8455 [03:48<08:05, 10.04it/s]

Preprocessing:  42%|████▏     | 3584/8455 [03:48<07:11, 11.28it/s]

Preprocessing:  42%|████▏     | 3586/8455 [03:48<07:53, 10.28it/s]

Preprocessing:  42%|████▏     | 3588/8455 [03:48<07:48, 10.40it/s]

Preprocessing:  42%|████▏     | 3590/8455 [03:49<08:04, 10.05it/s]

Preprocessing:  42%|████▏     | 3592/8455 [03:49<08:20,  9.72it/s]

Preprocessing:  42%|████▏     | 3593/8455 [03:49<08:27,  9.59it/s]

Preprocessing:  43%|████▎     | 3595/8455 [03:49<07:38, 10.60it/s]

Preprocessing:  43%|████▎     | 3597/8455 [03:49<07:10, 11.29it/s]

Preprocessing:  43%|████▎     | 3599/8455 [03:49<06:43, 12.03it/s]

Preprocessing:  43%|████▎     | 3601/8455 [03:50<06:36, 12.25it/s]

Preprocessing:  43%|████▎     | 3603/8455 [03:50<07:23, 10.93it/s]

Preprocessing:  43%|████▎     | 3605/8455 [03:50<07:24, 10.91it/s]

Preprocessing:  43%|████▎     | 3607/8455 [03:50<07:12, 11.21it/s]

Preprocessing:  43%|████▎     | 3609/8455 [03:50<07:43, 10.46it/s]

Preprocessing:  43%|████▎     | 3611/8455 [03:50<07:30, 10.76it/s]

Preprocessing:  43%|████▎     | 3613/8455 [03:51<07:24, 10.88it/s]

Preprocessing:  43%|████▎     | 3615/8455 [03:51<07:38, 10.55it/s]

Preprocessing:  43%|████▎     | 3617/8455 [03:51<07:02, 11.46it/s]

Preprocessing:  43%|████▎     | 3619/8455 [03:51<07:21, 10.95it/s]

Preprocessing:  43%|████▎     | 3621/8455 [03:51<06:47, 11.85it/s]

Preprocessing:  43%|████▎     | 3623/8455 [03:51<06:39, 12.08it/s]

Preprocessing:  43%|████▎     | 3625/8455 [03:52<07:24, 10.86it/s]

Preprocessing:  43%|████▎     | 3627/8455 [03:52<07:38, 10.53it/s]

Preprocessing:  43%|████▎     | 3629/8455 [03:52<07:24, 10.86it/s]

Preprocessing:  43%|████▎     | 3631/8455 [03:52<07:02, 11.42it/s]

Preprocessing:  43%|████▎     | 3633/8455 [03:52<06:56, 11.58it/s]

Preprocessing:  43%|████▎     | 3635/8455 [03:53<06:52, 11.69it/s]

Preprocessing:  43%|████▎     | 3637/8455 [03:53<07:29, 10.71it/s]

Preprocessing:  43%|████▎     | 3639/8455 [03:53<07:40, 10.45it/s]

Preprocessing:  43%|████▎     | 3641/8455 [03:53<06:45, 11.87it/s]

Preprocessing:  43%|████▎     | 3643/8455 [03:53<06:42, 11.95it/s]

Preprocessing:  43%|████▎     | 3645/8455 [03:53<06:23, 12.56it/s]

Preprocessing:  43%|████▎     | 3647/8455 [03:54<05:47, 13.85it/s]

Preprocessing:  43%|████▎     | 3649/8455 [03:54<05:26, 14.71it/s]

Preprocessing:  43%|████▎     | 3651/8455 [03:54<05:35, 14.31it/s]

Preprocessing:  43%|████▎     | 3653/8455 [03:54<05:42, 14.02it/s]

Preprocessing:  43%|████▎     | 3655/8455 [03:54<06:03, 13.22it/s]

Preprocessing:  43%|████▎     | 3657/8455 [03:54<05:42, 14.02it/s]

Preprocessing:  43%|████▎     | 3659/8455 [03:54<05:27, 14.65it/s]

Preprocessing:  43%|████▎     | 3661/8455 [03:54<05:10, 15.44it/s]

Preprocessing:  43%|████▎     | 3663/8455 [03:55<05:23, 14.82it/s]

Preprocessing:  43%|████▎     | 3665/8455 [03:55<05:15, 15.20it/s]

Preprocessing:  43%|████▎     | 3667/8455 [03:55<05:03, 15.78it/s]

Preprocessing:  43%|████▎     | 3669/8455 [03:55<05:25, 14.70it/s]

Preprocessing:  43%|████▎     | 3671/8455 [03:55<05:48, 13.72it/s]

Preprocessing:  43%|████▎     | 3673/8455 [03:55<05:37, 14.16it/s]

Preprocessing:  43%|████▎     | 3675/8455 [03:55<05:38, 14.11it/s]

Preprocessing:  43%|████▎     | 3677/8455 [03:56<05:42, 13.94it/s]

Preprocessing:  44%|████▎     | 3679/8455 [03:56<05:34, 14.28it/s]

Preprocessing:  44%|████▎     | 3681/8455 [03:56<05:31, 14.41it/s]

Preprocessing:  44%|████▎     | 3683/8455 [03:56<05:17, 15.05it/s]

Preprocessing:  44%|████▎     | 3685/8455 [03:56<05:04, 15.68it/s]

Preprocessing:  44%|████▎     | 3687/8455 [03:56<05:21, 14.85it/s]

Preprocessing:  44%|████▎     | 3689/8455 [03:56<05:46, 13.77it/s]

Preprocessing:  44%|████▎     | 3691/8455 [03:57<05:44, 13.85it/s]

Preprocessing:  44%|████▎     | 3693/8455 [03:57<05:57, 13.33it/s]

Preprocessing:  44%|████▎     | 3695/8455 [03:57<06:09, 12.88it/s]

Preprocessing:  44%|████▎     | 3697/8455 [03:57<06:25, 12.35it/s]

Preprocessing:  44%|████▎     | 3699/8455 [03:57<06:37, 11.96it/s]

Preprocessing:  44%|████▍     | 3701/8455 [03:57<06:39, 11.89it/s]

Preprocessing:  44%|████▍     | 3703/8455 [03:58<06:44, 11.75it/s]

Preprocessing:  44%|████▍     | 3705/8455 [03:58<07:27, 10.62it/s]

Preprocessing:  44%|████▍     | 3707/8455 [03:58<07:34, 10.44it/s]

Preprocessing:  44%|████▍     | 3709/8455 [03:58<07:14, 10.94it/s]

Preprocessing:  44%|████▍     | 3711/8455 [03:58<06:37, 11.92it/s]

Preprocessing:  44%|████▍     | 3713/8455 [03:58<06:22, 12.39it/s]

Preprocessing:  44%|████▍     | 3715/8455 [03:59<06:18, 12.53it/s]

Preprocessing:  44%|████▍     | 3717/8455 [03:59<05:51, 13.49it/s]

Preprocessing:  44%|████▍     | 3719/8455 [03:59<05:47, 13.64it/s]

Preprocessing:  44%|████▍     | 3721/8455 [03:59<05:32, 14.26it/s]

Preprocessing:  44%|████▍     | 3723/8455 [03:59<05:18, 14.86it/s]

Preprocessing:  44%|████▍     | 3725/8455 [03:59<05:17, 14.91it/s]

Preprocessing:  44%|████▍     | 3727/8455 [03:59<05:53, 13.37it/s]

Preprocessing:  44%|████▍     | 3729/8455 [04:00<05:42, 13.80it/s]

Preprocessing:  44%|████▍     | 3731/8455 [04:00<06:02, 13.02it/s]

Preprocessing:  44%|████▍     | 3733/8455 [04:00<05:47, 13.60it/s]

Preprocessing:  44%|████▍     | 3735/8455 [04:00<05:30, 14.28it/s]

Preprocessing:  44%|████▍     | 3737/8455 [04:00<05:19, 14.75it/s]

Preprocessing:  44%|████▍     | 3739/8455 [04:00<05:05, 15.42it/s]

Preprocessing:  44%|████▍     | 3741/8455 [04:00<05:01, 15.62it/s]

Preprocessing:  44%|████▍     | 3743/8455 [04:01<04:53, 16.08it/s]

Preprocessing:  44%|████▍     | 3745/8455 [04:01<05:13, 15.00it/s]

Preprocessing:  44%|████▍     | 3747/8455 [04:01<05:46, 13.60it/s]

Preprocessing:  44%|████▍     | 3749/8455 [04:01<05:51, 13.39it/s]

Preprocessing:  44%|████▍     | 3751/8455 [04:01<06:35, 11.89it/s]

Preprocessing:  44%|████▍     | 3753/8455 [04:01<06:23, 12.27it/s]

Preprocessing:  44%|████▍     | 3755/8455 [04:01<06:00, 13.04it/s]

Preprocessing:  44%|████▍     | 3757/8455 [04:02<06:14, 12.53it/s]

Preprocessing:  44%|████▍     | 3759/8455 [04:02<06:29, 12.06it/s]

Preprocessing:  44%|████▍     | 3761/8455 [04:02<06:17, 12.44it/s]

Preprocessing:  45%|████▍     | 3763/8455 [04:02<05:52, 13.31it/s]

Preprocessing:  45%|████▍     | 3765/8455 [04:02<05:33, 14.08it/s]

Preprocessing:  45%|████▍     | 3768/8455 [04:02<04:44, 16.48it/s]

Preprocessing:  45%|████▍     | 3770/8455 [04:03<04:53, 15.97it/s]

Preprocessing:  45%|████▍     | 3772/8455 [04:03<04:45, 16.38it/s]

Preprocessing:  45%|████▍     | 3774/8455 [04:03<05:01, 15.53it/s]

Preprocessing:  45%|████▍     | 3776/8455 [04:03<05:07, 15.24it/s]

Preprocessing:  45%|████▍     | 3778/8455 [04:03<05:00, 15.57it/s]

Preprocessing:  45%|████▍     | 3780/8455 [04:03<04:56, 15.76it/s]

Preprocessing:  45%|████▍     | 3782/8455 [04:03<04:58, 15.63it/s]

Preprocessing:  45%|████▍     | 3784/8455 [04:03<05:27, 14.27it/s]

Preprocessing:  45%|████▍     | 3786/8455 [04:04<05:32, 14.03it/s]

Preprocessing:  45%|████▍     | 3788/8455 [04:04<06:16, 12.39it/s]

Preprocessing:  45%|████▍     | 3790/8455 [04:04<06:10, 12.59it/s]

Preprocessing:  45%|████▍     | 3792/8455 [04:04<06:38, 11.71it/s]

Preprocessing:  45%|████▍     | 3794/8455 [04:04<06:34, 11.82it/s]

Preprocessing:  45%|████▍     | 3796/8455 [04:04<06:04, 12.78it/s]

Preprocessing:  45%|████▍     | 3798/8455 [04:05<05:41, 13.64it/s]

Preprocessing:  45%|████▍     | 3800/8455 [04:05<06:01, 12.88it/s]

Preprocessing:  45%|████▍     | 3802/8455 [04:05<05:42, 13.60it/s]

Preprocessing:  45%|████▍     | 3804/8455 [04:05<05:25, 14.28it/s]

Preprocessing:  45%|████▌     | 3806/8455 [04:05<05:09, 15.03it/s]

Preprocessing:  45%|████▌     | 3808/8455 [04:05<05:04, 15.25it/s]

Preprocessing:  45%|████▌     | 3810/8455 [04:05<04:50, 16.01it/s]

Preprocessing:  45%|████▌     | 3812/8455 [04:05<04:40, 16.52it/s]

Preprocessing:  45%|████▌     | 3814/8455 [04:06<04:36, 16.76it/s]

Preprocessing:  45%|████▌     | 3816/8455 [04:06<04:40, 16.56it/s]

Preprocessing:  45%|████▌     | 3818/8455 [04:06<04:42, 16.39it/s]

Preprocessing:  45%|████▌     | 3820/8455 [04:06<04:34, 16.86it/s]

Preprocessing:  45%|████▌     | 3822/8455 [04:06<04:26, 17.38it/s]

Preprocessing:  45%|████▌     | 3824/8455 [04:06<05:16, 14.64it/s]

Preprocessing:  45%|████▌     | 3826/8455 [04:06<05:05, 15.15it/s]

Preprocessing:  45%|████▌     | 3828/8455 [04:07<05:16, 14.63it/s]

Preprocessing:  45%|████▌     | 3830/8455 [04:07<05:21, 14.41it/s]

Preprocessing:  45%|████▌     | 3832/8455 [04:07<06:01, 12.80it/s]

Preprocessing:  45%|████▌     | 3834/8455 [04:07<05:36, 13.73it/s]

Preprocessing:  45%|████▌     | 3836/8455 [04:07<06:04, 12.68it/s]

Preprocessing:  45%|████▌     | 3838/8455 [04:07<06:37, 11.61it/s]

Preprocessing:  45%|████▌     | 3840/8455 [04:08<06:24, 12.01it/s]

Preprocessing:  45%|████▌     | 3842/8455 [04:08<05:51, 13.11it/s]

Preprocessing:  45%|████▌     | 3844/8455 [04:08<06:17, 12.23it/s]

Preprocessing:  45%|████▌     | 3846/8455 [04:08<05:45, 13.32it/s]

Preprocessing:  46%|████▌     | 3848/8455 [04:08<05:29, 14.00it/s]

Preprocessing:  46%|████▌     | 3850/8455 [04:08<05:47, 13.24it/s]

Preprocessing:  46%|████▌     | 3852/8455 [04:08<05:57, 12.86it/s]

Preprocessing:  46%|████▌     | 3854/8455 [04:09<05:35, 13.73it/s]

Preprocessing:  46%|████▌     | 3856/8455 [04:09<05:17, 14.50it/s]

Preprocessing:  46%|████▌     | 3858/8455 [04:09<05:25, 14.10it/s]

Preprocessing:  46%|████▌     | 3860/8455 [04:09<05:31, 13.87it/s]

Preprocessing:  46%|████▌     | 3862/8455 [04:09<05:14, 14.58it/s]

Preprocessing:  46%|████▌     | 3864/8455 [04:09<05:18, 14.43it/s]

Preprocessing:  46%|████▌     | 3866/8455 [04:09<05:08, 14.86it/s]

Preprocessing:  46%|████▌     | 3868/8455 [04:09<05:17, 14.46it/s]

Preprocessing:  46%|████▌     | 3870/8455 [04:10<05:14, 14.59it/s]

Preprocessing:  46%|████▌     | 3872/8455 [04:10<05:15, 14.50it/s]

Preprocessing:  46%|████▌     | 3874/8455 [04:10<05:25, 14.08it/s]

Preprocessing:  46%|████▌     | 3876/8455 [04:10<05:39, 13.50it/s]

Preprocessing:  46%|████▌     | 3878/8455 [04:10<05:43, 13.34it/s]

Preprocessing:  46%|████▌     | 3880/8455 [04:10<05:27, 13.99it/s]

Preprocessing:  46%|████▌     | 3883/8455 [04:10<04:36, 16.51it/s]

Preprocessing:  46%|████▌     | 3886/8455 [04:11<04:07, 18.44it/s]

Preprocessing:  46%|████▌     | 3888/8455 [04:11<04:16, 17.83it/s]

Preprocessing:  46%|████▌     | 3890/8455 [04:11<04:19, 17.62it/s]

Preprocessing:  46%|████▌     | 3893/8455 [04:11<03:59, 19.07it/s]

Preprocessing:  46%|████▌     | 3896/8455 [04:11<03:42, 20.49it/s]

Preprocessing:  46%|████▌     | 3899/8455 [04:11<03:40, 20.68it/s]

Preprocessing:  46%|████▌     | 3902/8455 [04:11<03:52, 19.61it/s]

Preprocessing:  46%|████▌     | 3905/8455 [04:12<03:44, 20.30it/s]

Preprocessing:  46%|████▌     | 3908/8455 [04:12<03:31, 21.53it/s]

Preprocessing:  46%|████▋     | 3911/8455 [04:12<03:18, 22.91it/s]

Preprocessing:  46%|████▋     | 3914/8455 [04:12<03:12, 23.58it/s]

Preprocessing:  46%|████▋     | 3917/8455 [04:12<03:11, 23.73it/s]

Preprocessing:  46%|████▋     | 3920/8455 [04:12<03:18, 22.88it/s]

Preprocessing:  46%|████▋     | 3923/8455 [04:12<03:42, 20.39it/s]

Preprocessing:  46%|████▋     | 3926/8455 [04:13<04:13, 17.87it/s]

Preprocessing:  46%|████▋     | 3928/8455 [04:13<04:13, 17.83it/s]

Preprocessing:  46%|████▋     | 3931/8455 [04:13<04:02, 18.67it/s]

Preprocessing:  47%|████▋     | 3934/8455 [04:13<03:53, 19.38it/s]

Preprocessing:  47%|████▋     | 3937/8455 [04:13<03:43, 20.19it/s]

Preprocessing:  47%|████▋     | 3940/8455 [04:13<03:39, 20.58it/s]

Preprocessing:  47%|████▋     | 3943/8455 [04:13<03:35, 20.94it/s]

Preprocessing:  47%|████▋     | 3946/8455 [04:14<03:51, 19.52it/s]

Preprocessing:  47%|████▋     | 3948/8455 [04:14<04:17, 17.49it/s]

Preprocessing:  47%|████▋     | 3950/8455 [04:14<04:51, 15.46it/s]

Preprocessing:  47%|████▋     | 3952/8455 [04:14<05:12, 14.43it/s]

Preprocessing:  47%|████▋     | 3954/8455 [04:14<05:12, 14.39it/s]

Preprocessing:  47%|████▋     | 3956/8455 [04:14<05:18, 14.10it/s]

Preprocessing:  47%|████▋     | 3958/8455 [04:15<05:37, 13.32it/s]

Preprocessing:  47%|████▋     | 3960/8455 [04:15<05:52, 12.76it/s]

Preprocessing:  47%|████▋     | 3962/8455 [04:15<05:52, 12.73it/s]

Preprocessing:  47%|████▋     | 3964/8455 [04:15<05:57, 12.56it/s]

Preprocessing:  47%|████▋     | 3966/8455 [04:15<06:14, 11.97it/s]

Preprocessing:  47%|████▋     | 3968/8455 [04:15<06:10, 12.10it/s]

Preprocessing:  47%|████▋     | 3970/8455 [04:16<06:29, 11.52it/s]

Preprocessing:  47%|████▋     | 3972/8455 [04:16<06:41, 11.17it/s]

Preprocessing:  47%|████▋     | 3974/8455 [04:16<06:47, 10.99it/s]

Preprocessing:  47%|████▋     | 3976/8455 [04:16<06:28, 11.54it/s]

Preprocessing:  47%|████▋     | 3978/8455 [04:16<06:16, 11.90it/s]

Preprocessing:  47%|████▋     | 3980/8455 [04:16<06:09, 12.12it/s]

Preprocessing:  47%|████▋     | 3982/8455 [04:17<06:19, 11.78it/s]

Preprocessing:  47%|████▋     | 3984/8455 [04:17<06:46, 11.00it/s]

Preprocessing:  47%|████▋     | 3986/8455 [04:17<07:31,  9.90it/s]

Preprocessing:  47%|████▋     | 3988/8455 [04:17<07:44,  9.61it/s]

Preprocessing:  47%|████▋     | 3989/8455 [04:17<07:42,  9.66it/s]

Preprocessing:  47%|████▋     | 3990/8455 [04:17<07:50,  9.50it/s]

Preprocessing:  47%|████▋     | 3991/8455 [04:18<08:07,  9.16it/s]

Preprocessing:  47%|████▋     | 3992/8455 [04:18<08:18,  8.94it/s]

Preprocessing:  47%|████▋     | 3993/8455 [04:18<08:11,  9.08it/s]

Preprocessing:  47%|████▋     | 3995/8455 [04:18<07:36,  9.78it/s]

Preprocessing:  47%|████▋     | 3997/8455 [04:18<07:34,  9.81it/s]

Preprocessing:  47%|████▋     | 3999/8455 [04:18<07:10, 10.35it/s]

Preprocessing:  47%|████▋     | 4001/8455 [04:19<07:00, 10.59it/s]

Preprocessing:  47%|████▋     | 4003/8455 [04:19<07:07, 10.40it/s]

Preprocessing:  47%|████▋     | 4005/8455 [04:19<06:46, 10.95it/s]

Preprocessing:  47%|████▋     | 4007/8455 [04:19<06:44, 10.99it/s]

Preprocessing:  47%|████▋     | 4009/8455 [04:19<06:34, 11.28it/s]

Preprocessing:  47%|████▋     | 4011/8455 [04:19<06:51, 10.79it/s]

Preprocessing:  47%|████▋     | 4013/8455 [04:20<06:45, 10.94it/s]

Preprocessing:  47%|████▋     | 4015/8455 [04:20<06:30, 11.38it/s]

Preprocessing:  48%|████▊     | 4017/8455 [04:20<06:26, 11.48it/s]

Preprocessing:  48%|████▊     | 4019/8455 [04:20<06:30, 11.37it/s]

Preprocessing:  48%|████▊     | 4021/8455 [04:20<06:39, 11.10it/s]

Preprocessing:  48%|████▊     | 4023/8455 [04:21<06:39, 11.10it/s]

Preprocessing:  48%|████▊     | 4025/8455 [04:21<07:26,  9.93it/s]

Preprocessing:  48%|████▊     | 4027/8455 [04:21<06:45, 10.92it/s]

Preprocessing:  48%|████▊     | 4029/8455 [04:21<07:10, 10.29it/s]

Preprocessing:  48%|████▊     | 4031/8455 [04:21<07:32,  9.77it/s]

Preprocessing:  48%|████▊     | 4033/8455 [04:22<07:33,  9.75it/s]

Preprocessing:  48%|████▊     | 4035/8455 [04:22<07:08, 10.32it/s]

Preprocessing:  48%|████▊     | 4037/8455 [04:22<06:59, 10.52it/s]

Preprocessing:  48%|████▊     | 4039/8455 [04:22<06:38, 11.09it/s]

Preprocessing:  48%|████▊     | 4041/8455 [04:22<06:49, 10.77it/s]

Preprocessing:  48%|████▊     | 4043/8455 [04:22<06:32, 11.23it/s]

Preprocessing:  48%|████▊     | 4045/8455 [04:23<06:28, 11.34it/s]

Preprocessing:  48%|████▊     | 4047/8455 [04:23<06:11, 11.87it/s]

Preprocessing:  48%|████▊     | 4049/8455 [04:23<05:54, 12.44it/s]

Preprocessing:  48%|████▊     | 4051/8455 [04:23<05:39, 12.96it/s]

Preprocessing:  48%|████▊     | 4053/8455 [04:23<05:28, 13.39it/s]

Preprocessing:  48%|████▊     | 4055/8455 [04:23<05:10, 14.19it/s]

Preprocessing:  48%|████▊     | 4057/8455 [04:23<04:58, 14.75it/s]

Preprocessing:  48%|████▊     | 4059/8455 [04:24<04:51, 15.10it/s]

Preprocessing:  48%|████▊     | 4061/8455 [04:24<04:51, 15.06it/s]

Preprocessing:  48%|████▊     | 4063/8455 [04:24<04:53, 14.98it/s]

Preprocessing:  48%|████▊     | 4065/8455 [04:24<04:53, 14.96it/s]

Preprocessing:  48%|████▊     | 4067/8455 [04:24<04:58, 14.69it/s]

Preprocessing:  48%|████▊     | 4069/8455 [04:24<05:00, 14.58it/s]

Preprocessing:  48%|████▊     | 4071/8455 [04:24<05:06, 14.32it/s]

Preprocessing:  48%|████▊     | 4073/8455 [04:25<05:19, 13.72it/s]

Preprocessing:  48%|████▊     | 4075/8455 [04:25<05:05, 14.36it/s]

Preprocessing:  48%|████▊     | 4077/8455 [04:25<05:02, 14.45it/s]

Preprocessing:  48%|████▊     | 4079/8455 [04:25<05:04, 14.39it/s]

Preprocessing:  48%|████▊     | 4081/8455 [04:25<05:16, 13.81it/s]

Preprocessing:  48%|████▊     | 4083/8455 [04:25<05:19, 13.69it/s]

Preprocessing:  48%|████▊     | 4085/8455 [04:25<05:18, 13.71it/s]

Preprocessing:  48%|████▊     | 4087/8455 [04:26<05:18, 13.74it/s]

Preprocessing:  48%|████▊     | 4089/8455 [04:26<05:05, 14.27it/s]

Preprocessing:  48%|████▊     | 4091/8455 [04:26<04:49, 15.06it/s]

Preprocessing:  48%|████▊     | 4093/8455 [04:26<04:55, 14.74it/s]

Preprocessing:  48%|████▊     | 4095/8455 [04:26<06:24, 11.33it/s]

Preprocessing:  48%|████▊     | 4097/8455 [04:26<06:22, 11.40it/s]

Preprocessing:  48%|████▊     | 4099/8455 [04:27<05:57, 12.19it/s]

Preprocessing:  49%|████▊     | 4101/8455 [04:27<05:48, 12.51it/s]

Preprocessing:  49%|████▊     | 4103/8455 [04:27<05:28, 13.24it/s]

Preprocessing:  49%|████▊     | 4105/8455 [04:27<05:25, 13.36it/s]

Preprocessing:  49%|████▊     | 4107/8455 [04:27<05:49, 12.46it/s]

Preprocessing:  49%|████▊     | 4109/8455 [04:27<05:34, 13.00it/s]

Preprocessing:  49%|████▊     | 4111/8455 [04:27<05:14, 13.83it/s]

Preprocessing:  49%|████▊     | 4113/8455 [04:28<05:27, 13.25it/s]

Preprocessing:  49%|████▊     | 4115/8455 [04:28<05:38, 12.82it/s]

Preprocessing:  49%|████▊     | 4117/8455 [04:28<06:08, 11.76it/s]

Preprocessing:  49%|████▊     | 4119/8455 [04:28<06:40, 10.84it/s]

Preprocessing:  49%|████▊     | 4121/8455 [04:28<06:50, 10.55it/s]

Preprocessing:  49%|████▉     | 4123/8455 [04:29<06:43, 10.75it/s]

Preprocessing:  49%|████▉     | 4125/8455 [04:29<06:19, 11.40it/s]

Preprocessing:  49%|████▉     | 4127/8455 [04:29<05:57, 12.10it/s]

Preprocessing:  49%|████▉     | 4129/8455 [04:29<06:35, 10.93it/s]

Preprocessing:  49%|████▉     | 4131/8455 [04:29<06:57, 10.36it/s]

Preprocessing:  49%|████▉     | 4133/8455 [04:29<06:43, 10.72it/s]

Preprocessing:  49%|████▉     | 4135/8455 [04:30<06:31, 11.02it/s]

Preprocessing:  49%|████▉     | 4137/8455 [04:30<06:06, 11.77it/s]

Preprocessing:  49%|████▉     | 4139/8455 [04:30<05:42, 12.61it/s]

Preprocessing:  49%|████▉     | 4141/8455 [04:30<05:47, 12.40it/s]

Preprocessing:  49%|████▉     | 4143/8455 [04:30<05:42, 12.60it/s]

Preprocessing:  49%|████▉     | 4145/8455 [04:30<05:32, 12.96it/s]

Preprocessing:  49%|████▉     | 4147/8455 [04:31<05:50, 12.31it/s]

Preprocessing:  49%|████▉     | 4149/8455 [04:31<05:52, 12.23it/s]

Preprocessing:  49%|████▉     | 4151/8455 [04:31<05:29, 13.05it/s]

Preprocessing:  49%|████▉     | 4153/8455 [04:31<06:07, 11.71it/s]

Preprocessing:  49%|████▉     | 4155/8455 [04:31<06:25, 11.17it/s]

Preprocessing:  49%|████▉     | 4157/8455 [04:31<06:32, 10.94it/s]

Preprocessing:  49%|████▉     | 4159/8455 [04:32<06:12, 11.52it/s]

Preprocessing:  49%|████▉     | 4161/8455 [04:32<06:24, 11.17it/s]

Preprocessing:  49%|████▉     | 4163/8455 [04:32<05:40, 12.62it/s]

Preprocessing:  49%|████▉     | 4166/8455 [04:32<04:44, 15.07it/s]

Preprocessing:  49%|████▉     | 4168/8455 [04:32<04:56, 14.44it/s]

Preprocessing:  49%|████▉     | 4170/8455 [04:32<05:24, 13.19it/s]

Preprocessing:  49%|████▉     | 4172/8455 [04:33<05:39, 12.63it/s]

Preprocessing:  49%|████▉     | 4174/8455 [04:33<05:39, 12.61it/s]

Preprocessing:  49%|████▉     | 4176/8455 [04:33<05:37, 12.69it/s]

Preprocessing:  49%|████▉     | 4178/8455 [04:33<06:08, 11.60it/s]

Preprocessing:  49%|████▉     | 4180/8455 [04:33<05:52, 12.12it/s]

Preprocessing:  49%|████▉     | 4182/8455 [04:33<05:48, 12.28it/s]

Preprocessing:  49%|████▉     | 4184/8455 [04:34<05:46, 12.32it/s]

Preprocessing:  50%|████▉     | 4186/8455 [04:34<05:52, 12.10it/s]

Preprocessing:  50%|████▉     | 4188/8455 [04:34<05:46, 12.32it/s]

Preprocessing:  50%|████▉     | 4190/8455 [04:34<05:42, 12.47it/s]

Preprocessing:  50%|████▉     | 4192/8455 [04:34<06:04, 11.71it/s]

Preprocessing:  50%|████▉     | 4194/8455 [04:34<05:38, 12.59it/s]

Preprocessing:  50%|████▉     | 4196/8455 [04:34<05:04, 13.99it/s]

Preprocessing:  50%|████▉     | 4198/8455 [04:35<05:05, 13.94it/s]

Preprocessing:  50%|████▉     | 4200/8455 [04:35<04:50, 14.65it/s]

Preprocessing:  50%|████▉     | 4202/8455 [04:35<04:39, 15.22it/s]

Preprocessing:  50%|████▉     | 4204/8455 [04:35<04:31, 15.66it/s]

Preprocessing:  50%|████▉     | 4206/8455 [04:35<04:33, 15.53it/s]

Preprocessing:  50%|████▉     | 4208/8455 [04:35<04:44, 14.94it/s]

Preprocessing:  50%|████▉     | 4210/8455 [04:35<05:16, 13.40it/s]

Preprocessing:  50%|████▉     | 4212/8455 [04:36<05:05, 13.91it/s]

Preprocessing:  50%|████▉     | 4214/8455 [04:36<05:03, 13.96it/s]

Preprocessing:  50%|████▉     | 4216/8455 [04:36<04:51, 14.56it/s]

Preprocessing:  50%|████▉     | 4218/8455 [04:36<04:41, 15.05it/s]

Preprocessing:  50%|████▉     | 4220/8455 [04:36<04:54, 14.38it/s]

Preprocessing:  50%|████▉     | 4222/8455 [04:36<04:53, 14.41it/s]

Preprocessing:  50%|████▉     | 4224/8455 [04:36<04:59, 14.13it/s]

Preprocessing:  50%|████▉     | 4226/8455 [04:37<05:39, 12.45it/s]

Preprocessing:  50%|█████     | 4228/8455 [04:37<05:08, 13.69it/s]

Preprocessing:  50%|█████     | 4230/8455 [04:37<04:56, 14.26it/s]

Preprocessing:  50%|█████     | 4232/8455 [04:37<05:01, 13.99it/s]

Preprocessing:  50%|█████     | 4234/8455 [04:37<05:52, 11.97it/s]

Preprocessing:  50%|█████     | 4236/8455 [04:37<05:18, 13.25it/s]

Preprocessing:  50%|█████     | 4238/8455 [04:37<05:39, 12.42it/s]

Preprocessing:  50%|█████     | 4240/8455 [04:38<05:30, 12.75it/s]

Preprocessing:  50%|█████     | 4242/8455 [04:38<05:41, 12.33it/s]

Preprocessing:  50%|█████     | 4244/8455 [04:38<05:31, 12.70it/s]

Preprocessing:  50%|█████     | 4246/8455 [04:38<05:13, 13.42it/s]

Preprocessing:  50%|█████     | 4248/8455 [04:38<05:30, 12.74it/s]

Preprocessing:  50%|█████     | 4250/8455 [04:38<05:12, 13.45it/s]

Preprocessing:  50%|█████     | 4252/8455 [04:39<05:32, 12.63it/s]

Preprocessing:  50%|█████     | 4254/8455 [04:39<05:16, 13.26it/s]

Preprocessing:  50%|█████     | 4256/8455 [04:39<05:03, 13.81it/s]

Preprocessing:  50%|█████     | 4258/8455 [04:39<05:09, 13.57it/s]

Preprocessing:  50%|█████     | 4260/8455 [04:39<04:49, 14.47it/s]

Preprocessing:  50%|█████     | 4262/8455 [04:39<05:15, 13.27it/s]

Preprocessing:  50%|█████     | 4264/8455 [04:39<05:43, 12.20it/s]

Preprocessing:  50%|█████     | 4266/8455 [04:40<05:55, 11.77it/s]

Preprocessing:  50%|█████     | 4268/8455 [04:40<06:06, 11.42it/s]

Preprocessing:  51%|█████     | 4270/8455 [04:40<06:06, 11.43it/s]

Preprocessing:  51%|█████     | 4272/8455 [04:40<06:00, 11.60it/s]

Preprocessing:  51%|█████     | 4274/8455 [04:40<06:10, 11.28it/s]

Preprocessing:  51%|█████     | 4276/8455 [04:41<06:08, 11.35it/s]

Preprocessing:  51%|█████     | 4278/8455 [04:41<05:46, 12.07it/s]

Preprocessing:  51%|█████     | 4280/8455 [04:41<05:37, 12.36it/s]

Preprocessing:  51%|█████     | 4282/8455 [04:41<05:27, 12.74it/s]

Preprocessing:  51%|█████     | 4284/8455 [04:41<05:26, 12.77it/s]

Preprocessing:  51%|█████     | 4286/8455 [04:41<05:44, 12.10it/s]

Preprocessing:  51%|█████     | 4288/8455 [04:42<06:16, 11.05it/s]

Preprocessing:  51%|█████     | 4290/8455 [04:42<06:47, 10.23it/s]

Preprocessing:  51%|█████     | 4292/8455 [04:42<06:18, 10.99it/s]

Preprocessing:  51%|█████     | 4294/8455 [04:42<05:43, 12.13it/s]

Preprocessing:  51%|█████     | 4296/8455 [04:42<05:25, 12.78it/s]

Preprocessing:  51%|█████     | 4298/8455 [04:42<05:44, 12.06it/s]

Preprocessing:  51%|█████     | 4300/8455 [04:42<05:15, 13.17it/s]

Preprocessing:  51%|█████     | 4302/8455 [04:43<05:12, 13.29it/s]

Preprocessing:  51%|█████     | 4304/8455 [04:43<05:36, 12.34it/s]

Preprocessing:  51%|█████     | 4306/8455 [04:43<05:33, 12.45it/s]

Preprocessing:  51%|█████     | 4308/8455 [04:43<05:37, 12.30it/s]

Preprocessing:  51%|█████     | 4310/8455 [04:43<05:37, 12.28it/s]

Preprocessing:  51%|█████     | 4312/8455 [04:43<05:35, 12.36it/s]

Preprocessing:  51%|█████     | 4314/8455 [04:44<05:20, 12.93it/s]

Preprocessing:  51%|█████     | 4316/8455 [04:44<04:58, 13.85it/s]

Preprocessing:  51%|█████     | 4318/8455 [04:44<04:52, 14.16it/s]

Preprocessing:  51%|█████     | 4320/8455 [04:44<04:59, 13.82it/s]

Preprocessing:  51%|█████     | 4322/8455 [04:44<05:46, 11.91it/s]

Preprocessing:  51%|█████     | 4324/8455 [04:44<06:07, 11.24it/s]

Preprocessing:  51%|█████     | 4326/8455 [04:45<05:29, 12.54it/s]

Preprocessing:  51%|█████     | 4328/8455 [04:45<05:27, 12.61it/s]

Preprocessing:  51%|█████     | 4330/8455 [04:45<05:27, 12.59it/s]

Preprocessing:  51%|█████     | 4332/8455 [04:45<05:39, 12.14it/s]

Preprocessing:  51%|█████▏    | 4334/8455 [04:45<05:21, 12.81it/s]

Preprocessing:  51%|█████▏    | 4336/8455 [04:45<05:07, 13.39it/s]

Preprocessing:  51%|█████▏    | 4338/8455 [04:45<05:04, 13.54it/s]

Preprocessing:  51%|█████▏    | 4340/8455 [04:46<05:17, 12.94it/s]

Preprocessing:  51%|█████▏    | 4342/8455 [04:46<05:06, 13.43it/s]

Preprocessing:  51%|█████▏    | 4344/8455 [04:46<05:25, 12.61it/s]

Preprocessing:  51%|█████▏    | 4346/8455 [04:46<05:14, 13.05it/s]

Preprocessing:  51%|█████▏    | 4348/8455 [04:46<05:04, 13.50it/s]

Preprocessing:  51%|█████▏    | 4350/8455 [04:46<05:14, 13.04it/s]

Preprocessing:  51%|█████▏    | 4352/8455 [04:47<04:56, 13.82it/s]

Preprocessing:  51%|█████▏    | 4354/8455 [04:47<04:40, 14.62it/s]

Preprocessing:  52%|█████▏    | 4356/8455 [04:47<04:48, 14.19it/s]

Preprocessing:  52%|█████▏    | 4358/8455 [04:47<05:12, 13.13it/s]

Preprocessing:  52%|█████▏    | 4360/8455 [04:47<05:45, 11.85it/s]

Preprocessing:  52%|█████▏    | 4362/8455 [04:47<05:30, 12.37it/s]

Preprocessing:  52%|█████▏    | 4364/8455 [04:47<05:37, 12.14it/s]

Preprocessing:  52%|█████▏    | 4366/8455 [04:48<05:23, 12.62it/s]

Preprocessing:  52%|█████▏    | 4368/8455 [04:48<05:06, 13.33it/s]

Preprocessing:  52%|█████▏    | 4370/8455 [04:48<05:04, 13.41it/s]

Preprocessing:  52%|█████▏    | 4372/8455 [04:48<05:15, 12.92it/s]

Preprocessing:  52%|█████▏    | 4374/8455 [04:48<05:09, 13.17it/s]

Preprocessing:  52%|█████▏    | 4376/8455 [04:48<05:13, 13.00it/s]

Preprocessing:  52%|█████▏    | 4378/8455 [04:49<05:02, 13.48it/s]

Preprocessing:  52%|█████▏    | 4380/8455 [04:49<05:25, 12.53it/s]

Preprocessing:  52%|█████▏    | 4382/8455 [04:49<05:26, 12.46it/s]

Preprocessing:  52%|█████▏    | 4384/8455 [04:49<05:38, 12.03it/s]

Preprocessing:  52%|█████▏    | 4386/8455 [04:49<05:33, 12.20it/s]

Preprocessing:  52%|█████▏    | 4388/8455 [04:49<05:52, 11.54it/s]

Preprocessing:  52%|█████▏    | 4390/8455 [04:50<05:48, 11.65it/s]

Preprocessing:  52%|█████▏    | 4392/8455 [04:50<05:46, 11.73it/s]

Preprocessing:  52%|█████▏    | 4394/8455 [04:50<05:20, 12.69it/s]

Preprocessing:  52%|█████▏    | 4396/8455 [04:50<05:08, 13.15it/s]

Preprocessing:  52%|█████▏    | 4398/8455 [04:50<05:16, 12.82it/s]

Preprocessing:  52%|█████▏    | 4400/8455 [04:50<05:31, 12.23it/s]

Preprocessing:  52%|█████▏    | 4402/8455 [04:50<05:04, 13.31it/s]

Preprocessing:  52%|█████▏    | 4404/8455 [04:51<05:12, 12.97it/s]

Preprocessing:  52%|█████▏    | 4406/8455 [04:51<05:20, 12.65it/s]

Preprocessing:  52%|█████▏    | 4408/8455 [04:51<05:04, 13.31it/s]

Preprocessing:  52%|█████▏    | 4410/8455 [04:51<05:24, 12.48it/s]

Preprocessing:  52%|█████▏    | 4412/8455 [04:51<05:50, 11.52it/s]

Preprocessing:  52%|█████▏    | 4414/8455 [04:52<06:11, 10.89it/s]

Preprocessing:  52%|█████▏    | 4416/8455 [04:52<06:07, 10.98it/s]

Preprocessing:  52%|█████▏    | 4418/8455 [04:52<05:57, 11.30it/s]

Preprocessing:  52%|█████▏    | 4420/8455 [04:52<06:31, 10.31it/s]

Preprocessing:  52%|█████▏    | 4422/8455 [04:52<05:52, 11.43it/s]

Preprocessing:  52%|█████▏    | 4424/8455 [04:53<06:58,  9.64it/s]

Preprocessing:  52%|█████▏    | 4426/8455 [04:53<06:17, 10.69it/s]

Preprocessing:  52%|█████▏    | 4428/8455 [04:53<05:49, 11.52it/s]

Preprocessing:  52%|█████▏    | 4430/8455 [04:53<05:38, 11.88it/s]

Preprocessing:  52%|█████▏    | 4432/8455 [04:53<05:55, 11.32it/s]

Preprocessing:  52%|█████▏    | 4434/8455 [04:53<05:57, 11.25it/s]

Preprocessing:  52%|█████▏    | 4436/8455 [04:53<05:24, 12.40it/s]

Preprocessing:  52%|█████▏    | 4438/8455 [04:54<05:39, 11.82it/s]

Preprocessing:  53%|█████▎    | 4440/8455 [04:54<06:13, 10.74it/s]

Preprocessing:  53%|█████▎    | 4442/8455 [04:54<06:56,  9.62it/s]

Preprocessing:  53%|█████▎    | 4444/8455 [04:54<06:39, 10.04it/s]

Preprocessing:  53%|█████▎    | 4446/8455 [04:54<06:19, 10.56it/s]

Preprocessing:  53%|█████▎    | 4448/8455 [04:55<06:05, 10.96it/s]

Preprocessing:  53%|█████▎    | 4450/8455 [04:55<06:08, 10.86it/s]

Preprocessing:  53%|█████▎    | 4452/8455 [04:55<05:54, 11.31it/s]

Preprocessing:  53%|█████▎    | 4454/8455 [04:55<06:03, 11.01it/s]

Preprocessing:  53%|█████▎    | 4456/8455 [04:55<06:14, 10.68it/s]

Preprocessing:  53%|█████▎    | 4458/8455 [04:56<06:22, 10.46it/s]

Preprocessing:  53%|█████▎    | 4460/8455 [04:56<06:24, 10.39it/s]

Preprocessing:  53%|█████▎    | 4462/8455 [04:56<05:57, 11.16it/s]

Preprocessing:  53%|█████▎    | 4464/8455 [04:56<05:41, 11.68it/s]

Preprocessing:  53%|█████▎    | 4466/8455 [04:56<06:04, 10.94it/s]

Preprocessing:  53%|█████▎    | 4468/8455 [04:57<06:30, 10.20it/s]

Preprocessing:  53%|█████▎    | 4470/8455 [04:57<06:34, 10.11it/s]

Preprocessing:  53%|█████▎    | 4472/8455 [04:57<06:55,  9.59it/s]

Preprocessing:  53%|█████▎    | 4474/8455 [04:57<06:31, 10.17it/s]

Preprocessing:  53%|█████▎    | 4476/8455 [04:57<06:02, 10.97it/s]

Preprocessing:  53%|█████▎    | 4478/8455 [04:57<05:48, 11.41it/s]

Preprocessing:  53%|█████▎    | 4480/8455 [04:58<05:39, 11.70it/s]

Preprocessing:  53%|█████▎    | 4482/8455 [04:58<05:42, 11.59it/s]

Preprocessing:  53%|█████▎    | 4484/8455 [04:58<05:46, 11.47it/s]

Preprocessing:  53%|█████▎    | 4486/8455 [04:58<05:32, 11.94it/s]

Preprocessing:  53%|█████▎    | 4488/8455 [04:58<05:18, 12.47it/s]

Preprocessing:  53%|█████▎    | 4490/8455 [04:58<05:57, 11.09it/s]

Preprocessing:  53%|█████▎    | 4492/8455 [04:59<05:52, 11.24it/s]

Preprocessing:  53%|█████▎    | 4494/8455 [04:59<05:53, 11.20it/s]

Preprocessing:  53%|█████▎    | 4496/8455 [04:59<05:48, 11.35it/s]

Preprocessing:  53%|█████▎    | 4498/8455 [04:59<05:18, 12.41it/s]

Preprocessing:  53%|█████▎    | 4500/8455 [04:59<05:13, 12.64it/s]

Preprocessing:  53%|█████▎    | 4502/8455 [04:59<05:26, 12.12it/s]

Preprocessing:  53%|█████▎    | 4504/8455 [05:00<05:46, 11.39it/s]

Preprocessing:  53%|█████▎    | 4506/8455 [05:00<05:47, 11.37it/s]

Preprocessing:  53%|█████▎    | 4508/8455 [05:00<06:05, 10.79it/s]

Preprocessing:  53%|█████▎    | 4510/8455 [05:00<06:09, 10.68it/s]

Preprocessing:  53%|█████▎    | 4512/8455 [05:00<05:55, 11.09it/s]

Preprocessing:  53%|█████▎    | 4514/8455 [05:01<05:41, 11.56it/s]

Preprocessing:  53%|█████▎    | 4516/8455 [05:01<05:39, 11.59it/s]

Preprocessing:  53%|█████▎    | 4518/8455 [05:01<05:39, 11.61it/s]

Preprocessing:  53%|█████▎    | 4520/8455 [05:01<05:36, 11.68it/s]

Preprocessing:  53%|█████▎    | 4522/8455 [05:01<05:44, 11.40it/s]

Preprocessing:  54%|█████▎    | 4524/8455 [05:01<06:04, 10.80it/s]

Preprocessing:  54%|█████▎    | 4526/8455 [05:02<06:41,  9.78it/s]

Preprocessing:  54%|█████▎    | 4528/8455 [05:02<06:20, 10.32it/s]

Preprocessing:  54%|█████▎    | 4530/8455 [05:02<05:57, 10.99it/s]

Preprocessing:  54%|█████▎    | 4532/8455 [05:02<05:48, 11.26it/s]

Preprocessing:  54%|█████▎    | 4534/8455 [05:02<05:55, 11.03it/s]

Preprocessing:  54%|█████▎    | 4536/8455 [05:03<05:48, 11.26it/s]

Preprocessing:  54%|█████▎    | 4538/8455 [05:03<06:00, 10.87it/s]

Preprocessing:  54%|█████▎    | 4540/8455 [05:03<06:25, 10.15it/s]

Preprocessing:  54%|█████▎    | 4542/8455 [05:03<06:12, 10.50it/s]

Preprocessing:  54%|█████▎    | 4544/8455 [05:03<06:18, 10.33it/s]

Preprocessing:  54%|█████▍    | 4546/8455 [05:04<06:03, 10.76it/s]

Preprocessing:  54%|█████▍    | 4548/8455 [05:04<06:04, 10.72it/s]

Preprocessing:  54%|█████▍    | 4550/8455 [05:04<05:38, 11.52it/s]

Preprocessing:  54%|█████▍    | 4552/8455 [05:04<05:40, 11.46it/s]

Preprocessing:  54%|█████▍    | 4554/8455 [05:04<05:25, 11.97it/s]

Preprocessing:  54%|█████▍    | 4556/8455 [05:04<05:08, 12.66it/s]

Preprocessing:  54%|█████▍    | 4558/8455 [05:04<05:24, 12.01it/s]

Preprocessing:  54%|█████▍    | 4560/8455 [05:05<05:51, 11.09it/s]

Preprocessing:  54%|█████▍    | 4562/8455 [05:05<06:03, 10.71it/s]

Preprocessing:  54%|█████▍    | 4564/8455 [05:05<05:54, 10.99it/s]

Preprocessing:  54%|█████▍    | 4566/8455 [05:05<06:05, 10.63it/s]

Preprocessing:  54%|█████▍    | 4568/8455 [05:05<06:14, 10.39it/s]

Preprocessing:  54%|█████▍    | 4570/8455 [05:06<05:57, 10.86it/s]

Preprocessing:  54%|█████▍    | 4572/8455 [05:06<06:15, 10.34it/s]

Preprocessing:  54%|█████▍    | 4574/8455 [05:06<06:23, 10.11it/s]

Preprocessing:  54%|█████▍    | 4576/8455 [05:06<06:30,  9.94it/s]

Preprocessing:  54%|█████▍    | 4578/8455 [05:06<06:27, 10.02it/s]

Preprocessing:  54%|█████▍    | 4580/8455 [05:07<06:58,  9.26it/s]

Preprocessing:  54%|█████▍    | 4582/8455 [05:07<06:45,  9.54it/s]

Preprocessing:  54%|█████▍    | 4584/8455 [05:07<05:56, 10.87it/s]

Preprocessing:  54%|█████▍    | 4586/8455 [05:07<05:42, 11.30it/s]

Preprocessing:  54%|█████▍    | 4588/8455 [05:07<05:49, 11.05it/s]

Preprocessing:  54%|█████▍    | 4590/8455 [05:08<06:16, 10.25it/s]

Preprocessing:  54%|█████▍    | 4592/8455 [05:08<06:21, 10.12it/s]

Preprocessing:  54%|█████▍    | 4594/8455 [05:08<06:47,  9.47it/s]

Preprocessing:  54%|█████▍    | 4596/8455 [05:08<06:24, 10.04it/s]

Preprocessing:  54%|█████▍    | 4598/8455 [05:08<06:01, 10.67it/s]

Preprocessing:  54%|█████▍    | 4600/8455 [05:09<06:23, 10.04it/s]

Preprocessing:  54%|█████▍    | 4602/8455 [05:09<07:08,  8.98it/s]

Preprocessing:  54%|█████▍    | 4604/8455 [05:09<07:00,  9.16it/s]

Preprocessing:  54%|█████▍    | 4605/8455 [05:09<06:54,  9.30it/s]

Preprocessing:  54%|█████▍    | 4606/8455 [05:09<07:12,  8.91it/s]

Preprocessing:  54%|█████▍    | 4607/8455 [05:09<07:01,  9.12it/s]

Preprocessing:  55%|█████▍    | 4608/8455 [05:10<07:37,  8.41it/s]

Preprocessing:  55%|█████▍    | 4610/8455 [05:10<06:28,  9.89it/s]

Preprocessing:  55%|█████▍    | 4611/8455 [05:10<07:02,  9.11it/s]

Preprocessing:  55%|█████▍    | 4613/8455 [05:10<06:59,  9.15it/s]

Preprocessing:  55%|█████▍    | 4614/8455 [05:10<07:03,  9.08it/s]

Preprocessing:  55%|█████▍    | 4615/8455 [05:10<07:07,  8.99it/s]

Preprocessing:  55%|█████▍    | 4616/8455 [05:10<07:14,  8.84it/s]

Preprocessing:  55%|█████▍    | 4617/8455 [05:11<07:41,  8.31it/s]

Preprocessing:  55%|█████▍    | 4619/8455 [05:11<06:39,  9.60it/s]

Preprocessing:  55%|█████▍    | 4621/8455 [05:11<06:00, 10.63it/s]

Preprocessing:  55%|█████▍    | 4623/8455 [05:11<06:21, 10.04it/s]

Preprocessing:  55%|█████▍    | 4625/8455 [05:11<05:48, 10.99it/s]

Preprocessing:  55%|█████▍    | 4627/8455 [05:11<05:51, 10.88it/s]

Preprocessing:  55%|█████▍    | 4629/8455 [05:12<06:09, 10.34it/s]

Preprocessing:  55%|█████▍    | 4631/8455 [05:12<05:54, 10.78it/s]

Preprocessing:  55%|█████▍    | 4633/8455 [05:12<05:49, 10.95it/s]

Preprocessing:  55%|█████▍    | 4635/8455 [05:12<05:58, 10.66it/s]

Preprocessing:  55%|█████▍    | 4637/8455 [05:12<05:52, 10.84it/s]

Preprocessing:  55%|█████▍    | 4639/8455 [05:13<05:59, 10.62it/s]

Preprocessing:  55%|█████▍    | 4641/8455 [05:13<05:41, 11.15it/s]

Preprocessing:  55%|█████▍    | 4643/8455 [05:13<05:27, 11.62it/s]

Preprocessing:  55%|█████▍    | 4645/8455 [05:13<05:35, 11.35it/s]

Preprocessing:  55%|█████▍    | 4647/8455 [05:13<05:26, 11.66it/s]

Preprocessing:  55%|█████▍    | 4649/8455 [05:13<05:43, 11.09it/s]

Preprocessing:  55%|█████▌    | 4651/8455 [05:14<05:33, 11.39it/s]

Preprocessing:  55%|█████▌    | 4653/8455 [05:14<05:25, 11.69it/s]

Preprocessing:  55%|█████▌    | 4655/8455 [05:14<05:17, 11.98it/s]

Preprocessing:  55%|█████▌    | 4657/8455 [05:14<05:16, 12.00it/s]

Preprocessing:  55%|█████▌    | 4659/8455 [05:14<05:21, 11.81it/s]

Preprocessing:  55%|█████▌    | 4661/8455 [05:15<05:54, 10.70it/s]

Preprocessing:  55%|█████▌    | 4663/8455 [05:15<06:11, 10.20it/s]

Preprocessing:  55%|█████▌    | 4665/8455 [05:15<05:28, 11.55it/s]

Preprocessing:  55%|█████▌    | 4667/8455 [05:15<04:57, 12.75it/s]

Preprocessing:  55%|█████▌    | 4669/8455 [05:15<05:05, 12.38it/s]

Preprocessing:  55%|█████▌    | 4671/8455 [05:15<05:04, 12.45it/s]

Preprocessing:  55%|█████▌    | 4673/8455 [05:15<05:04, 12.40it/s]

Preprocessing:  55%|█████▌    | 4675/8455 [05:16<05:22, 11.72it/s]

Preprocessing:  55%|█████▌    | 4677/8455 [05:16<05:17, 11.89it/s]

Preprocessing:  55%|█████▌    | 4679/8455 [05:16<04:47, 13.12it/s]

Preprocessing:  55%|█████▌    | 4681/8455 [05:16<05:00, 12.56it/s]

Preprocessing:  55%|█████▌    | 4683/8455 [05:16<05:00, 12.57it/s]

Preprocessing:  55%|█████▌    | 4685/8455 [05:16<05:01, 12.49it/s]

Preprocessing:  55%|█████▌    | 4687/8455 [05:17<04:43, 13.29it/s]

Preprocessing:  55%|█████▌    | 4689/8455 [05:17<04:55, 12.73it/s]

Preprocessing:  55%|█████▌    | 4691/8455 [05:17<04:56, 12.70it/s]

Preprocessing:  56%|█████▌    | 4693/8455 [05:17<05:22, 11.65it/s]

Preprocessing:  56%|█████▌    | 4695/8455 [05:17<05:41, 11.02it/s]

Preprocessing:  56%|█████▌    | 4697/8455 [05:17<05:06, 12.25it/s]

Preprocessing:  56%|█████▌    | 4699/8455 [05:18<05:07, 12.23it/s]

Preprocessing:  56%|█████▌    | 4701/8455 [05:18<05:07, 12.21it/s]

Preprocessing:  56%|█████▌    | 4703/8455 [05:18<05:29, 11.40it/s]

Preprocessing:  56%|█████▌    | 4705/8455 [05:18<05:09, 12.13it/s]

Preprocessing:  56%|█████▌    | 4707/8455 [05:18<05:32, 11.28it/s]

Preprocessing:  56%|█████▌    | 4709/8455 [05:18<05:05, 12.26it/s]

Preprocessing:  56%|█████▌    | 4711/8455 [05:19<05:19, 11.74it/s]

Preprocessing:  56%|█████▌    | 4713/8455 [05:19<04:59, 12.49it/s]

Preprocessing:  56%|█████▌    | 4715/8455 [05:19<04:48, 12.96it/s]

Preprocessing:  56%|█████▌    | 4717/8455 [05:19<04:36, 13.53it/s]

Preprocessing:  56%|█████▌    | 4719/8455 [05:19<04:37, 13.48it/s]

Preprocessing:  56%|█████▌    | 4721/8455 [05:19<04:19, 14.39it/s]

Preprocessing:  56%|█████▌    | 4723/8455 [05:19<04:31, 13.76it/s]

Preprocessing:  56%|█████▌    | 4725/8455 [05:20<04:18, 14.42it/s]

Preprocessing:  56%|█████▌    | 4727/8455 [05:20<04:16, 14.55it/s]

Preprocessing:  56%|█████▌    | 4729/8455 [05:20<04:28, 13.89it/s]

Preprocessing:  56%|█████▌    | 4731/8455 [05:20<04:18, 14.40it/s]

Preprocessing:  56%|█████▌    | 4733/8455 [05:20<04:33, 13.62it/s]

Preprocessing:  56%|█████▌    | 4735/8455 [05:20<04:38, 13.36it/s]

Preprocessing:  56%|█████▌    | 4737/8455 [05:21<05:07, 12.10it/s]

Preprocessing:  56%|█████▌    | 4739/8455 [05:21<05:18, 11.68it/s]

Preprocessing:  56%|█████▌    | 4741/8455 [05:21<05:17, 11.68it/s]

Preprocessing:  56%|█████▌    | 4743/8455 [05:21<05:15, 11.77it/s]

Preprocessing:  56%|█████▌    | 4745/8455 [05:21<05:09, 11.97it/s]

Preprocessing:  56%|█████▌    | 4747/8455 [05:21<04:42, 13.13it/s]

Preprocessing:  56%|█████▌    | 4749/8455 [05:22<05:05, 12.13it/s]

Preprocessing:  56%|█████▌    | 4751/8455 [05:22<05:08, 12.02it/s]

Preprocessing:  56%|█████▌    | 4753/8455 [05:22<05:24, 11.42it/s]

Preprocessing:  56%|█████▌    | 4755/8455 [05:22<05:06, 12.06it/s]

Preprocessing:  56%|█████▋    | 4757/8455 [05:22<05:24, 11.41it/s]

Preprocessing:  56%|█████▋    | 4759/8455 [05:22<05:35, 11.02it/s]

Preprocessing:  56%|█████▋    | 4761/8455 [05:23<05:24, 11.39it/s]

Preprocessing:  56%|█████▋    | 4763/8455 [05:23<05:34, 11.04it/s]

Preprocessing:  56%|█████▋    | 4765/8455 [05:23<05:14, 11.74it/s]

Preprocessing:  56%|█████▋    | 4767/8455 [05:23<05:54, 10.41it/s]

Preprocessing:  56%|█████▋    | 4769/8455 [05:23<05:13, 11.75it/s]

Preprocessing:  56%|█████▋    | 4771/8455 [05:23<04:58, 12.33it/s]

Preprocessing:  56%|█████▋    | 4773/8455 [05:24<04:58, 12.32it/s]

Preprocessing:  56%|█████▋    | 4775/8455 [05:24<05:30, 11.13it/s]

Preprocessing:  56%|█████▋    | 4777/8455 [05:24<04:55, 12.46it/s]

Preprocessing:  57%|█████▋    | 4779/8455 [05:24<05:00, 12.22it/s]

Preprocessing:  57%|█████▋    | 4781/8455 [05:24<05:15, 11.63it/s]

Preprocessing:  57%|█████▋    | 4783/8455 [05:24<05:29, 11.13it/s]

Preprocessing:  57%|█████▋    | 4785/8455 [05:25<05:24, 11.29it/s]

Preprocessing:  57%|█████▋    | 4787/8455 [05:25<05:15, 11.64it/s]

Preprocessing:  57%|█████▋    | 4789/8455 [05:25<05:25, 11.25it/s]

Preprocessing:  57%|█████▋    | 4791/8455 [05:25<05:42, 10.69it/s]

Preprocessing:  57%|█████▋    | 4793/8455 [05:25<05:28, 11.16it/s]

Preprocessing:  57%|█████▋    | 4795/8455 [05:26<05:31, 11.02it/s]

Preprocessing:  57%|█████▋    | 4797/8455 [05:26<05:38, 10.81it/s]

Preprocessing:  57%|█████▋    | 4799/8455 [05:26<05:20, 11.39it/s]

Preprocessing:  57%|█████▋    | 4801/8455 [05:26<04:49, 12.63it/s]

Preprocessing:  57%|█████▋    | 4803/8455 [05:26<05:11, 11.72it/s]

Preprocessing:  57%|█████▋    | 4805/8455 [05:26<05:29, 11.08it/s]

Preprocessing:  57%|█████▋    | 4807/8455 [05:27<05:23, 11.28it/s]

Preprocessing:  57%|█████▋    | 4809/8455 [05:27<05:29, 11.07it/s]

Preprocessing:  57%|█████▋    | 4811/8455 [05:27<05:37, 10.80it/s]

Preprocessing:  57%|█████▋    | 4813/8455 [05:27<05:48, 10.44it/s]

Preprocessing:  57%|█████▋    | 4815/8455 [05:27<05:29, 11.05it/s]

Preprocessing:  57%|█████▋    | 4817/8455 [05:28<05:21, 11.32it/s]

Preprocessing:  57%|█████▋    | 4819/8455 [05:28<05:16, 11.50it/s]

Preprocessing:  57%|█████▋    | 4821/8455 [05:28<05:05, 11.88it/s]

Preprocessing:  57%|█████▋    | 4823/8455 [05:28<05:28, 11.07it/s]

Preprocessing:  57%|█████▋    | 4825/8455 [05:28<05:40, 10.66it/s]

Preprocessing:  57%|█████▋    | 4827/8455 [05:28<05:40, 10.66it/s]

Preprocessing:  57%|█████▋    | 4829/8455 [05:29<05:45, 10.48it/s]

Preprocessing:  57%|█████▋    | 4831/8455 [05:29<05:49, 10.37it/s]

Preprocessing:  57%|█████▋    | 4833/8455 [05:29<05:17, 11.39it/s]

Preprocessing:  57%|█████▋    | 4835/8455 [05:29<05:06, 11.81it/s]

Preprocessing:  57%|█████▋    | 4837/8455 [05:29<05:03, 11.92it/s]

Preprocessing:  57%|█████▋    | 4839/8455 [05:29<05:18, 11.35it/s]

Preprocessing:  57%|█████▋    | 4841/8455 [05:30<05:37, 10.72it/s]

Preprocessing:  57%|█████▋    | 4843/8455 [05:30<05:42, 10.55it/s]

Preprocessing:  57%|█████▋    | 4845/8455 [05:30<05:48, 10.36it/s]

Preprocessing:  57%|█████▋    | 4847/8455 [05:30<05:34, 10.77it/s]

Preprocessing:  57%|█████▋    | 4849/8455 [05:30<05:16, 11.38it/s]

Preprocessing:  57%|█████▋    | 4851/8455 [05:31<05:30, 10.92it/s]

Preprocessing:  57%|█████▋    | 4853/8455 [05:31<05:34, 10.76it/s]

Preprocessing:  57%|█████▋    | 4855/8455 [05:31<05:20, 11.22it/s]

Preprocessing:  57%|█████▋    | 4857/8455 [05:31<05:43, 10.46it/s]

Preprocessing:  57%|█████▋    | 4859/8455 [05:31<05:25, 11.05it/s]

Preprocessing:  57%|█████▋    | 4861/8455 [05:32<05:15, 11.39it/s]

Preprocessing:  58%|█████▊    | 4863/8455 [05:32<05:32, 10.81it/s]

Preprocessing:  58%|█████▊    | 4865/8455 [05:32<05:36, 10.66it/s]

Preprocessing:  58%|█████▊    | 4867/8455 [05:32<06:06,  9.78it/s]

Preprocessing:  58%|█████▊    | 4869/8455 [05:32<05:22, 11.12it/s]

Preprocessing:  58%|█████▊    | 4871/8455 [05:32<05:30, 10.85it/s]

Preprocessing:  58%|█████▊    | 4873/8455 [05:33<05:42, 10.47it/s]

Preprocessing:  58%|█████▊    | 4875/8455 [05:33<05:43, 10.41it/s]

Preprocessing:  58%|█████▊    | 4877/8455 [05:33<05:22, 11.08it/s]

Preprocessing:  58%|█████▊    | 4879/8455 [05:33<05:32, 10.77it/s]

Preprocessing:  58%|█████▊    | 4881/8455 [05:33<05:36, 10.63it/s]

Preprocessing:  58%|█████▊    | 4883/8455 [05:34<05:33, 10.72it/s]

Preprocessing:  58%|█████▊    | 4885/8455 [05:34<05:47, 10.28it/s]

Preprocessing:  58%|█████▊    | 4887/8455 [05:34<05:46, 10.29it/s]

Preprocessing:  58%|█████▊    | 4889/8455 [05:34<05:29, 10.81it/s]

Preprocessing:  58%|█████▊    | 4891/8455 [05:34<05:37, 10.57it/s]

Preprocessing:  58%|█████▊    | 4893/8455 [05:35<05:19, 11.16it/s]

Preprocessing:  58%|█████▊    | 4895/8455 [05:35<05:05, 11.66it/s]

Preprocessing:  58%|█████▊    | 4897/8455 [05:35<05:25, 10.93it/s]

Preprocessing:  58%|█████▊    | 4899/8455 [05:35<04:49, 12.27it/s]

Preprocessing:  58%|█████▊    | 4901/8455 [05:35<05:10, 11.44it/s]

Preprocessing:  58%|█████▊    | 4903/8455 [05:35<05:35, 10.58it/s]

Preprocessing:  58%|█████▊    | 4905/8455 [05:36<05:38, 10.48it/s]

Preprocessing:  58%|█████▊    | 4907/8455 [05:36<05:20, 11.08it/s]

Preprocessing:  58%|█████▊    | 4909/8455 [05:36<05:07, 11.53it/s]

Preprocessing:  58%|█████▊    | 4911/8455 [05:36<04:40, 12.63it/s]

Preprocessing:  58%|█████▊    | 4913/8455 [05:36<04:57, 11.89it/s]

Preprocessing:  58%|█████▊    | 4915/8455 [05:36<04:39, 12.66it/s]

Preprocessing:  58%|█████▊    | 4917/8455 [05:37<04:43, 12.50it/s]

Preprocessing:  58%|█████▊    | 4919/8455 [05:37<04:46, 12.36it/s]

Preprocessing:  58%|█████▊    | 4921/8455 [05:37<05:01, 11.74it/s]

Preprocessing:  58%|█████▊    | 4923/8455 [05:37<05:01, 11.71it/s]

Preprocessing:  58%|█████▊    | 4925/8455 [05:37<05:27, 10.78it/s]

Preprocessing:  58%|█████▊    | 4927/8455 [05:37<05:07, 11.46it/s]

Preprocessing:  58%|█████▊    | 4929/8455 [05:38<05:28, 10.72it/s]

Preprocessing:  58%|█████▊    | 4931/8455 [05:38<05:29, 10.68it/s]

Preprocessing:  58%|█████▊    | 4933/8455 [05:38<05:35, 10.49it/s]

Preprocessing:  58%|█████▊    | 4935/8455 [05:38<06:07,  9.58it/s]

Preprocessing:  58%|█████▊    | 4937/8455 [05:38<05:47, 10.12it/s]

Preprocessing:  58%|█████▊    | 4939/8455 [05:39<05:38, 10.40it/s]

Preprocessing:  58%|█████▊    | 4941/8455 [05:39<05:21, 10.93it/s]

Preprocessing:  58%|█████▊    | 4943/8455 [05:39<05:40, 10.30it/s]

Preprocessing:  58%|█████▊    | 4945/8455 [05:39<05:53,  9.92it/s]

Preprocessing:  59%|█████▊    | 4947/8455 [05:39<05:58,  9.78it/s]

Preprocessing:  59%|█████▊    | 4948/8455 [05:40<06:00,  9.74it/s]

Preprocessing:  59%|█████▊    | 4950/8455 [05:40<05:46, 10.12it/s]

Preprocessing:  59%|█████▊    | 4952/8455 [05:40<05:25, 10.75it/s]

Preprocessing:  59%|█████▊    | 4954/8455 [05:40<05:33, 10.49it/s]

Preprocessing:  59%|█████▊    | 4956/8455 [05:40<05:46, 10.08it/s]

Preprocessing:  59%|█████▊    | 4958/8455 [05:41<05:33, 10.48it/s]

Preprocessing:  59%|█████▊    | 4960/8455 [05:41<05:47, 10.06it/s]

Preprocessing:  59%|█████▊    | 4962/8455 [05:41<05:25, 10.73it/s]

Preprocessing:  59%|█████▊    | 4964/8455 [05:41<05:37, 10.34it/s]

Preprocessing:  59%|█████▊    | 4966/8455 [05:41<05:42, 10.17it/s]

Preprocessing:  59%|█████▉    | 4968/8455 [05:41<05:23, 10.77it/s]

Preprocessing:  59%|█████▉    | 4970/8455 [05:42<05:31, 10.52it/s]

Preprocessing:  59%|█████▉    | 4972/8455 [05:42<05:35, 10.39it/s]

Preprocessing:  59%|█████▉    | 4974/8455 [05:42<05:12, 11.14it/s]

Preprocessing:  59%|█████▉    | 4976/8455 [05:42<05:23, 10.74it/s]

Preprocessing:  59%|█████▉    | 4978/8455 [05:42<05:11, 11.15it/s]

Preprocessing:  59%|█████▉    | 4980/8455 [05:43<05:30, 10.50it/s]

Preprocessing:  59%|█████▉    | 4982/8455 [05:43<05:36, 10.32it/s]

Preprocessing:  59%|█████▉    | 4984/8455 [05:43<05:37, 10.27it/s]

Preprocessing:  59%|█████▉    | 4986/8455 [05:43<05:42, 10.13it/s]

Preprocessing:  59%|█████▉    | 4988/8455 [05:43<05:44, 10.07it/s]

Preprocessing:  59%|█████▉    | 4990/8455 [05:44<05:55,  9.76it/s]

Preprocessing:  59%|█████▉    | 4992/8455 [05:44<05:15, 10.98it/s]

Preprocessing:  59%|█████▉    | 4994/8455 [05:44<05:04, 11.36it/s]

Preprocessing:  59%|█████▉    | 4996/8455 [05:44<04:59, 11.57it/s]

Preprocessing:  59%|█████▉    | 4998/8455 [05:44<04:55, 11.72it/s]

Preprocessing:  59%|█████▉    | 5000/8455 [05:44<05:13, 11.02it/s]

Preprocessing:  59%|█████▉    | 5002/8455 [05:45<05:29, 10.49it/s]

Preprocessing:  59%|█████▉    | 5004/8455 [05:45<05:31, 10.40it/s]

Preprocessing:  59%|█████▉    | 5006/8455 [05:45<05:36, 10.24it/s]

Preprocessing:  59%|█████▉    | 5008/8455 [05:45<05:06, 11.25it/s]

Preprocessing:  59%|█████▉    | 5010/8455 [05:45<04:59, 11.50it/s]

Preprocessing:  59%|█████▉    | 5012/8455 [05:46<04:53, 11.74it/s]

Preprocessing:  59%|█████▉    | 5014/8455 [05:46<05:11, 11.03it/s]

Preprocessing:  59%|█████▉    | 5016/8455 [05:46<05:19, 10.77it/s]

Preprocessing:  59%|█████▉    | 5018/8455 [05:46<05:25, 10.56it/s]

Preprocessing:  59%|█████▉    | 5020/8455 [05:46<05:33, 10.30it/s]

Preprocessing:  59%|█████▉    | 5022/8455 [05:46<05:18, 10.79it/s]

Preprocessing:  59%|█████▉    | 5024/8455 [05:47<05:33, 10.29it/s]

Preprocessing:  59%|█████▉    | 5026/8455 [05:47<05:37, 10.17it/s]

Preprocessing:  59%|█████▉    | 5028/8455 [05:47<05:41, 10.04it/s]

Preprocessing:  59%|█████▉    | 5030/8455 [05:47<05:42, 10.01it/s]

Preprocessing:  60%|█████▉    | 5032/8455 [05:47<05:23, 10.59it/s]

Preprocessing:  60%|█████▉    | 5034/8455 [05:48<05:35, 10.21it/s]

Preprocessing:  60%|█████▉    | 5036/8455 [05:48<05:36, 10.16it/s]

Preprocessing:  60%|█████▉    | 5038/8455 [05:48<05:43,  9.95it/s]

Preprocessing:  60%|█████▉    | 5040/8455 [05:48<05:43,  9.95it/s]

Preprocessing:  60%|█████▉    | 5042/8455 [05:48<05:21, 10.61it/s]

Preprocessing:  60%|█████▉    | 5044/8455 [05:49<05:33, 10.22it/s]

Preprocessing:  60%|█████▉    | 5046/8455 [05:49<05:38, 10.07it/s]

Preprocessing:  60%|█████▉    | 5048/8455 [05:49<05:41,  9.98it/s]

Preprocessing:  60%|█████▉    | 5050/8455 [05:49<05:28, 10.36it/s]

Preprocessing:  60%|█████▉    | 5052/8455 [05:49<05:12, 10.90it/s]

Preprocessing:  60%|█████▉    | 5054/8455 [05:50<04:40, 12.14it/s]

Preprocessing:  60%|█████▉    | 5056/8455 [05:50<04:24, 12.86it/s]

Preprocessing:  60%|█████▉    | 5058/8455 [05:50<04:20, 13.05it/s]

Preprocessing:  60%|█████▉    | 5060/8455 [05:50<04:15, 13.29it/s]

Preprocessing:  60%|█████▉    | 5062/8455 [05:50<04:25, 12.76it/s]

Preprocessing:  60%|█████▉    | 5064/8455 [05:50<04:53, 11.56it/s]

Preprocessing:  60%|█████▉    | 5066/8455 [05:51<04:51, 11.64it/s]

Preprocessing:  60%|█████▉    | 5068/8455 [05:51<04:59, 11.32it/s]

Preprocessing:  60%|█████▉    | 5070/8455 [05:51<04:53, 11.53it/s]

Preprocessing:  60%|█████▉    | 5072/8455 [05:51<05:11, 10.86it/s]

Preprocessing:  60%|██████    | 5074/8455 [05:51<05:10, 10.89it/s]

Preprocessing:  60%|██████    | 5076/8455 [05:51<04:52, 11.55it/s]

Preprocessing:  60%|██████    | 5078/8455 [05:52<05:06, 11.03it/s]

Preprocessing:  60%|██████    | 5080/8455 [05:52<05:19, 10.55it/s]

Preprocessing:  60%|██████    | 5082/8455 [05:52<05:00, 11.24it/s]

Preprocessing:  60%|██████    | 5084/8455 [05:52<05:19, 10.56it/s]

Preprocessing:  60%|██████    | 5086/8455 [05:52<05:34, 10.08it/s]

Preprocessing:  60%|██████    | 5088/8455 [05:53<05:24, 10.37it/s]

Preprocessing:  60%|██████    | 5090/8455 [05:53<05:12, 10.77it/s]

Preprocessing:  60%|██████    | 5092/8455 [05:53<05:25, 10.33it/s]

Preprocessing:  60%|██████    | 5094/8455 [05:53<05:00, 11.19it/s]

Preprocessing:  60%|██████    | 5096/8455 [05:53<04:54, 11.41it/s]

Preprocessing:  60%|██████    | 5098/8455 [05:53<05:05, 10.99it/s]

Preprocessing:  60%|██████    | 5100/8455 [05:54<05:02, 11.10it/s]

Preprocessing:  60%|██████    | 5102/8455 [05:54<05:20, 10.47it/s]

Preprocessing:  60%|██████    | 5104/8455 [05:54<05:08, 10.88it/s]

Preprocessing:  60%|██████    | 5106/8455 [05:54<05:22, 10.40it/s]

Preprocessing:  60%|██████    | 5108/8455 [05:54<05:29, 10.15it/s]

Preprocessing:  60%|██████    | 5110/8455 [05:55<05:34, 10.00it/s]

Preprocessing:  60%|██████    | 5112/8455 [05:55<05:19, 10.47it/s]

Preprocessing:  60%|██████    | 5114/8455 [05:55<05:18, 10.49it/s]

Preprocessing:  61%|██████    | 5116/8455 [05:55<05:12, 10.68it/s]

Preprocessing:  61%|██████    | 5118/8455 [05:55<05:08, 10.82it/s]

Preprocessing:  61%|██████    | 5120/8455 [05:56<05:25, 10.26it/s]

Preprocessing:  61%|██████    | 5122/8455 [05:56<05:32, 10.01it/s]

Preprocessing:  61%|██████    | 5124/8455 [05:56<05:22, 10.33it/s]

Preprocessing:  61%|██████    | 5126/8455 [05:56<05:18, 10.47it/s]

Preprocessing:  61%|██████    | 5128/8455 [05:56<05:07, 10.82it/s]

Preprocessing:  61%|██████    | 5130/8455 [05:57<05:10, 10.70it/s]

Preprocessing:  61%|██████    | 5132/8455 [05:57<05:21, 10.33it/s]

Preprocessing:  61%|██████    | 5134/8455 [05:57<05:23, 10.28it/s]

Preprocessing:  61%|██████    | 5136/8455 [05:57<05:19, 10.39it/s]

Preprocessing:  61%|██████    | 5138/8455 [05:57<05:10, 10.69it/s]

Preprocessing:  61%|██████    | 5140/8455 [05:57<05:05, 10.86it/s]

Preprocessing:  61%|██████    | 5142/8455 [05:58<05:05, 10.86it/s]

Preprocessing:  61%|██████    | 5144/8455 [05:58<05:01, 10.98it/s]

Preprocessing:  61%|██████    | 5146/8455 [05:58<04:58, 11.10it/s]

Preprocessing:  61%|██████    | 5148/8455 [05:58<04:54, 11.25it/s]

Preprocessing:  61%|██████    | 5150/8455 [05:58<04:31, 12.18it/s]

Preprocessing:  61%|██████    | 5152/8455 [05:58<04:30, 12.21it/s]

Preprocessing:  61%|██████    | 5154/8455 [05:59<04:24, 12.48it/s]

Preprocessing:  61%|██████    | 5156/8455 [05:59<04:42, 11.69it/s]

Preprocessing:  61%|██████    | 5158/8455 [05:59<04:27, 12.31it/s]

Preprocessing:  61%|██████    | 5160/8455 [05:59<04:24, 12.47it/s]

Preprocessing:  61%|██████    | 5162/8455 [05:59<04:41, 11.69it/s]

Preprocessing:  61%|██████    | 5164/8455 [06:00<05:00, 10.95it/s]

Preprocessing:  61%|██████    | 5166/8455 [06:00<04:57, 11.05it/s]

Preprocessing:  61%|██████    | 5168/8455 [06:00<04:54, 11.14it/s]

Preprocessing:  61%|██████    | 5170/8455 [06:00<05:09, 10.60it/s]

Preprocessing:  61%|██████    | 5172/8455 [06:00<05:03, 10.83it/s]

Preprocessing:  61%|██████    | 5174/8455 [06:00<05:12, 10.49it/s]

Preprocessing:  61%|██████    | 5176/8455 [06:01<05:28,  9.98it/s]

Preprocessing:  61%|██████    | 5178/8455 [06:01<05:32,  9.85it/s]

Preprocessing:  61%|██████▏   | 5180/8455 [06:01<04:53, 11.16it/s]

Preprocessing:  61%|██████▏   | 5182/8455 [06:01<05:01, 10.86it/s]

Preprocessing:  61%|██████▏   | 5184/8455 [06:01<05:10, 10.54it/s]

Preprocessing:  61%|██████▏   | 5186/8455 [06:02<04:44, 11.49it/s]

Preprocessing:  61%|██████▏   | 5188/8455 [06:02<05:02, 10.80it/s]

Preprocessing:  61%|██████▏   | 5190/8455 [06:02<05:07, 10.61it/s]

Preprocessing:  61%|██████▏   | 5192/8455 [06:02<05:16, 10.30it/s]

Preprocessing:  61%|██████▏   | 5194/8455 [06:02<05:18, 10.25it/s]

Preprocessing:  61%|██████▏   | 5196/8455 [06:03<05:03, 10.73it/s]

Preprocessing:  61%|██████▏   | 5198/8455 [06:03<05:16, 10.30it/s]

Preprocessing:  62%|██████▏   | 5200/8455 [06:03<04:44, 11.43it/s]

Preprocessing:  62%|██████▏   | 5202/8455 [06:03<04:21, 12.44it/s]

Preprocessing:  62%|██████▏   | 5204/8455 [06:03<04:43, 11.47it/s]

Preprocessing:  62%|██████▏   | 5206/8455 [06:03<04:57, 10.93it/s]

Preprocessing:  62%|██████▏   | 5208/8455 [06:04<04:53, 11.05it/s]

Preprocessing:  62%|██████▏   | 5210/8455 [06:04<05:02, 10.71it/s]

Preprocessing:  62%|██████▏   | 5212/8455 [06:04<05:08, 10.52it/s]

Preprocessing:  62%|██████▏   | 5214/8455 [06:04<04:55, 10.96it/s]

Preprocessing:  62%|██████▏   | 5216/8455 [06:04<04:59, 10.80it/s]

Preprocessing:  62%|██████▏   | 5218/8455 [06:05<05:12, 10.36it/s]

Preprocessing:  62%|██████▏   | 5220/8455 [06:05<05:16, 10.22it/s]

Preprocessing:  62%|██████▏   | 5222/8455 [06:05<05:19, 10.13it/s]

Preprocessing:  62%|██████▏   | 5224/8455 [06:05<05:24,  9.95it/s]

Preprocessing:  62%|██████▏   | 5226/8455 [06:05<05:21, 10.06it/s]

Preprocessing:  62%|██████▏   | 5228/8455 [06:06<05:05, 10.56it/s]

Preprocessing:  62%|██████▏   | 5230/8455 [06:06<05:19, 10.10it/s]

Preprocessing:  62%|██████▏   | 5232/8455 [06:06<05:04, 10.57it/s]

Preprocessing:  62%|██████▏   | 5234/8455 [06:06<04:31, 11.84it/s]

Preprocessing:  62%|██████▏   | 5236/8455 [06:06<04:36, 11.64it/s]

Preprocessing:  62%|██████▏   | 5238/8455 [06:06<05:07, 10.45it/s]

Preprocessing:  62%|██████▏   | 5240/8455 [06:07<05:26,  9.83it/s]

Preprocessing:  62%|██████▏   | 5242/8455 [06:07<05:07, 10.45it/s]

Preprocessing:  62%|██████▏   | 5244/8455 [06:07<04:43, 11.33it/s]

Preprocessing:  62%|██████▏   | 5246/8455 [06:07<05:13, 10.24it/s]

Preprocessing:  62%|██████▏   | 5248/8455 [06:07<05:16, 10.12it/s]

Preprocessing:  62%|██████▏   | 5250/8455 [06:08<05:05, 10.49it/s]

Preprocessing:  62%|██████▏   | 5252/8455 [06:08<05:30,  9.68it/s]

Preprocessing:  62%|██████▏   | 5254/8455 [06:08<05:59,  8.91it/s]

Preprocessing:  62%|██████▏   | 5256/8455 [06:08<05:30,  9.67it/s]

Preprocessing:  62%|██████▏   | 5258/8455 [06:08<05:22,  9.91it/s]

Preprocessing:  62%|██████▏   | 5260/8455 [06:09<05:25,  9.80it/s]

Preprocessing:  62%|██████▏   | 5262/8455 [06:09<05:07, 10.40it/s]

Preprocessing:  62%|██████▏   | 5264/8455 [06:09<04:47, 11.11it/s]

Preprocessing:  62%|██████▏   | 5266/8455 [06:09<04:33, 11.68it/s]

Preprocessing:  62%|██████▏   | 5268/8455 [06:09<04:22, 12.13it/s]

Preprocessing:  62%|██████▏   | 5270/8455 [06:09<04:08, 12.84it/s]

Preprocessing:  62%|██████▏   | 5272/8455 [06:10<05:01, 10.56it/s]

Preprocessing:  62%|██████▏   | 5274/8455 [06:10<04:35, 11.55it/s]

Preprocessing:  62%|██████▏   | 5276/8455 [06:10<04:29, 11.78it/s]

Preprocessing:  62%|██████▏   | 5278/8455 [06:10<04:14, 12.47it/s]

Preprocessing:  62%|██████▏   | 5280/8455 [06:10<04:05, 12.91it/s]

Preprocessing:  62%|██████▏   | 5282/8455 [06:10<04:03, 13.04it/s]

Preprocessing:  62%|██████▏   | 5284/8455 [06:11<04:06, 12.86it/s]

Preprocessing:  63%|██████▎   | 5286/8455 [06:11<04:05, 12.93it/s]

Preprocessing:  63%|██████▎   | 5288/8455 [06:11<03:52, 13.61it/s]

Preprocessing:  63%|██████▎   | 5290/8455 [06:11<03:41, 14.27it/s]

Preprocessing:  63%|██████▎   | 5292/8455 [06:11<03:53, 13.57it/s]

Preprocessing:  63%|██████▎   | 5294/8455 [06:11<03:55, 13.41it/s]

Preprocessing:  63%|██████▎   | 5296/8455 [06:11<03:52, 13.57it/s]

Preprocessing:  63%|██████▎   | 5298/8455 [06:12<03:44, 14.08it/s]

Preprocessing:  63%|██████▎   | 5300/8455 [06:12<04:15, 12.34it/s]

Preprocessing:  63%|██████▎   | 5302/8455 [06:12<04:21, 12.07it/s]

Preprocessing:  63%|██████▎   | 5304/8455 [06:12<04:12, 12.46it/s]

Preprocessing:  63%|██████▎   | 5306/8455 [06:12<04:16, 12.26it/s]

Preprocessing:  63%|██████▎   | 5308/8455 [06:12<04:01, 13.05it/s]

Preprocessing:  63%|██████▎   | 5310/8455 [06:13<03:53, 13.45it/s]

Preprocessing:  63%|██████▎   | 5312/8455 [06:13<03:44, 14.00it/s]

Preprocessing:  63%|██████▎   | 5314/8455 [06:13<03:39, 14.31it/s]

Preprocessing:  63%|██████▎   | 5316/8455 [06:13<03:30, 14.95it/s]

Preprocessing:  63%|██████▎   | 5318/8455 [06:13<03:48, 13.76it/s]

Preprocessing:  63%|██████▎   | 5320/8455 [06:13<03:36, 14.49it/s]

Preprocessing:  63%|██████▎   | 5322/8455 [06:13<03:46, 13.81it/s]

Preprocessing:  63%|██████▎   | 5324/8455 [06:14<03:38, 14.33it/s]

Preprocessing:  63%|██████▎   | 5326/8455 [06:14<03:33, 14.64it/s]

Preprocessing:  63%|██████▎   | 5328/8455 [06:14<03:31, 14.77it/s]

Preprocessing:  63%|██████▎   | 5330/8455 [06:14<03:26, 15.14it/s]

Preprocessing:  63%|██████▎   | 5332/8455 [06:14<03:26, 15.11it/s]

Preprocessing:  63%|██████▎   | 5334/8455 [06:14<03:19, 15.62it/s]

Preprocessing:  63%|██████▎   | 5336/8455 [06:14<03:32, 14.69it/s]

Preprocessing:  63%|██████▎   | 5338/8455 [06:15<04:06, 12.67it/s]

Preprocessing:  63%|██████▎   | 5340/8455 [06:15<04:02, 12.84it/s]

Preprocessing:  63%|██████▎   | 5342/8455 [06:15<04:22, 11.88it/s]

Preprocessing:  63%|██████▎   | 5344/8455 [06:15<04:06, 12.63it/s]

Preprocessing:  63%|██████▎   | 5346/8455 [06:15<04:21, 11.90it/s]

Preprocessing:  63%|██████▎   | 5348/8455 [06:15<04:51, 10.65it/s]

Preprocessing:  63%|██████▎   | 5350/8455 [06:16<04:41, 11.04it/s]

Preprocessing:  63%|██████▎   | 5352/8455 [06:16<04:24, 11.73it/s]

Preprocessing:  63%|██████▎   | 5354/8455 [06:16<04:19, 11.93it/s]

Preprocessing:  63%|██████▎   | 5356/8455 [06:16<04:13, 12.24it/s]

Preprocessing:  63%|██████▎   | 5358/8455 [06:16<03:53, 13.24it/s]

Preprocessing:  63%|██████▎   | 5360/8455 [06:16<03:47, 13.60it/s]

Preprocessing:  63%|██████▎   | 5362/8455 [06:16<03:45, 13.74it/s]

Preprocessing:  63%|██████▎   | 5364/8455 [06:17<03:46, 13.66it/s]

Preprocessing:  63%|██████▎   | 5366/8455 [06:17<03:52, 13.31it/s]

Preprocessing:  63%|██████▎   | 5368/8455 [06:17<04:02, 12.71it/s]

Preprocessing:  64%|██████▎   | 5370/8455 [06:17<04:00, 12.84it/s]

Preprocessing:  64%|██████▎   | 5372/8455 [06:17<04:17, 11.99it/s]

Preprocessing:  64%|██████▎   | 5374/8455 [06:17<04:15, 12.05it/s]

Preprocessing:  64%|██████▎   | 5376/8455 [06:18<04:10, 12.27it/s]

Preprocessing:  64%|██████▎   | 5378/8455 [06:18<04:20, 11.83it/s]

Preprocessing:  64%|██████▎   | 5380/8455 [06:18<04:12, 12.18it/s]

Preprocessing:  64%|██████▎   | 5382/8455 [06:18<04:11, 12.21it/s]

Preprocessing:  64%|██████▎   | 5384/8455 [06:18<04:04, 12.58it/s]

Preprocessing:  64%|██████▎   | 5386/8455 [06:18<04:05, 12.48it/s]

Preprocessing:  64%|██████▎   | 5388/8455 [06:19<03:56, 12.95it/s]

Preprocessing:  64%|██████▎   | 5390/8455 [06:19<04:18, 11.85it/s]

Preprocessing:  64%|██████▍   | 5392/8455 [06:19<04:37, 11.04it/s]

Preprocessing:  64%|██████▍   | 5394/8455 [06:19<04:55, 10.37it/s]

Preprocessing:  64%|██████▍   | 5396/8455 [06:19<04:36, 11.04it/s]

Preprocessing:  64%|██████▍   | 5398/8455 [06:20<04:30, 11.29it/s]

Preprocessing:  64%|██████▍   | 5400/8455 [06:20<04:28, 11.36it/s]

Preprocessing:  64%|██████▍   | 5402/8455 [06:20<04:33, 11.18it/s]

Preprocessing:  64%|██████▍   | 5404/8455 [06:20<04:43, 10.76it/s]

Preprocessing:  64%|██████▍   | 5406/8455 [06:20<04:49, 10.54it/s]

Preprocessing:  64%|██████▍   | 5408/8455 [06:20<04:39, 10.88it/s]

Preprocessing:  64%|██████▍   | 5410/8455 [06:21<05:15,  9.65it/s]

Preprocessing:  64%|██████▍   | 5412/8455 [06:21<04:51, 10.46it/s]

Preprocessing:  64%|██████▍   | 5414/8455 [06:21<04:32, 11.16it/s]

Preprocessing:  64%|██████▍   | 5416/8455 [06:21<04:41, 10.78it/s]

Preprocessing:  64%|██████▍   | 5418/8455 [06:21<04:26, 11.38it/s]

Preprocessing:  64%|██████▍   | 5420/8455 [06:22<04:26, 11.38it/s]

Preprocessing:  64%|██████▍   | 5422/8455 [06:22<04:37, 10.93it/s]

Preprocessing:  64%|██████▍   | 5424/8455 [06:22<04:27, 11.31it/s]

Preprocessing:  64%|██████▍   | 5426/8455 [06:22<04:24, 11.43it/s]

Preprocessing:  64%|██████▍   | 5428/8455 [06:22<04:27, 11.32it/s]

Preprocessing:  64%|██████▍   | 5430/8455 [06:22<04:34, 11.02it/s]

Preprocessing:  64%|██████▍   | 5432/8455 [06:23<04:39, 10.80it/s]

Preprocessing:  64%|██████▍   | 5434/8455 [06:23<04:22, 11.52it/s]

Preprocessing:  64%|██████▍   | 5436/8455 [06:23<04:41, 10.74it/s]

Preprocessing:  64%|██████▍   | 5438/8455 [06:23<04:24, 11.41it/s]

Preprocessing:  64%|██████▍   | 5440/8455 [06:23<04:31, 11.10it/s]

Preprocessing:  64%|██████▍   | 5442/8455 [06:24<04:43, 10.64it/s]

Preprocessing:  64%|██████▍   | 5444/8455 [06:24<04:34, 10.95it/s]

Preprocessing:  64%|██████▍   | 5446/8455 [06:24<04:26, 11.29it/s]

Preprocessing:  64%|██████▍   | 5448/8455 [06:24<04:35, 10.91it/s]

Preprocessing:  64%|██████▍   | 5450/8455 [06:24<04:31, 11.06it/s]

Preprocessing:  64%|██████▍   | 5452/8455 [06:24<04:28, 11.18it/s]

Preprocessing:  65%|██████▍   | 5454/8455 [06:25<04:30, 11.11it/s]

Preprocessing:  65%|██████▍   | 5456/8455 [06:25<04:31, 11.03it/s]

Preprocessing:  65%|██████▍   | 5458/8455 [06:25<04:27, 11.21it/s]

Preprocessing:  65%|██████▍   | 5460/8455 [06:25<04:20, 11.49it/s]

Preprocessing:  65%|██████▍   | 5462/8455 [06:25<04:22, 11.39it/s]

Preprocessing:  65%|██████▍   | 5464/8455 [06:25<04:21, 11.44it/s]

Preprocessing:  65%|██████▍   | 5466/8455 [06:26<04:49, 10.34it/s]

Preprocessing:  65%|██████▍   | 5468/8455 [06:26<04:31, 11.00it/s]

Preprocessing:  65%|██████▍   | 5470/8455 [06:26<04:21, 11.41it/s]

Preprocessing:  65%|██████▍   | 5472/8455 [06:26<04:22, 11.36it/s]

Preprocessing:  65%|██████▍   | 5474/8455 [06:26<04:11, 11.87it/s]

Preprocessing:  65%|██████▍   | 5476/8455 [06:27<04:10, 11.91it/s]

Preprocessing:  65%|██████▍   | 5478/8455 [06:27<04:06, 12.08it/s]

Preprocessing:  65%|██████▍   | 5480/8455 [06:27<04:25, 11.19it/s]

Preprocessing:  65%|██████▍   | 5482/8455 [06:27<04:44, 10.46it/s]

Preprocessing:  65%|██████▍   | 5484/8455 [06:27<05:11,  9.52it/s]

Preprocessing:  65%|██████▍   | 5485/8455 [06:27<05:20,  9.28it/s]

Preprocessing:  65%|██████▍   | 5486/8455 [06:28<05:29,  9.00it/s]

Preprocessing:  65%|██████▍   | 5487/8455 [06:28<05:28,  9.03it/s]

Preprocessing:  65%|██████▍   | 5488/8455 [06:28<05:22,  9.21it/s]

Preprocessing:  65%|██████▍   | 5490/8455 [06:28<04:59,  9.90it/s]

Preprocessing:  65%|██████▍   | 5491/8455 [06:28<04:59,  9.89it/s]

Preprocessing:  65%|██████▍   | 5492/8455 [06:28<05:01,  9.84it/s]

Preprocessing:  65%|██████▍   | 5493/8455 [06:28<05:00,  9.87it/s]

Preprocessing:  65%|██████▍   | 5495/8455 [06:28<04:29, 11.00it/s]

Preprocessing:  65%|██████▌   | 5497/8455 [06:29<04:12, 11.72it/s]

Preprocessing:  65%|██████▌   | 5499/8455 [06:29<03:50, 12.82it/s]

Preprocessing:  65%|██████▌   | 5501/8455 [06:29<03:34, 13.76it/s]

Preprocessing:  65%|██████▌   | 5503/8455 [06:29<03:23, 14.52it/s]

Preprocessing:  65%|██████▌   | 5505/8455 [06:29<03:20, 14.72it/s]

Preprocessing:  65%|██████▌   | 5507/8455 [06:29<03:19, 14.81it/s]

Preprocessing:  65%|██████▌   | 5509/8455 [06:29<03:21, 14.63it/s]

Preprocessing:  65%|██████▌   | 5511/8455 [06:30<03:20, 14.66it/s]

Preprocessing:  65%|██████▌   | 5513/8455 [06:30<03:22, 14.53it/s]

Preprocessing:  65%|██████▌   | 5515/8455 [06:30<03:18, 14.79it/s]

Preprocessing:  65%|██████▌   | 5517/8455 [06:30<03:13, 15.17it/s]

Preprocessing:  65%|██████▌   | 5519/8455 [06:30<03:11, 15.33it/s]

Preprocessing:  65%|██████▌   | 5521/8455 [06:30<03:21, 14.53it/s]

Preprocessing:  65%|██████▌   | 5523/8455 [06:30<03:37, 13.46it/s]

Preprocessing:  65%|██████▌   | 5525/8455 [06:31<04:06, 11.88it/s]

Preprocessing:  65%|██████▌   | 5527/8455 [06:31<04:04, 11.96it/s]

Preprocessing:  65%|██████▌   | 5529/8455 [06:31<03:54, 12.48it/s]

Preprocessing:  65%|██████▌   | 5531/8455 [06:31<03:49, 12.76it/s]

Preprocessing:  65%|██████▌   | 5533/8455 [06:31<03:39, 13.31it/s]

Preprocessing:  65%|██████▌   | 5535/8455 [06:31<03:37, 13.41it/s]

Preprocessing:  65%|██████▌   | 5537/8455 [06:32<04:13, 11.52it/s]

Preprocessing:  66%|██████▌   | 5539/8455 [06:32<04:39, 10.44it/s]

Preprocessing:  66%|██████▌   | 5541/8455 [06:32<04:46, 10.17it/s]

Preprocessing:  66%|██████▌   | 5543/8455 [06:32<04:55,  9.87it/s]

Preprocessing:  66%|██████▌   | 5545/8455 [06:32<04:42, 10.30it/s]

Preprocessing:  66%|██████▌   | 5547/8455 [06:33<05:13,  9.27it/s]

Preprocessing:  66%|██████▌   | 5549/8455 [06:33<05:07,  9.46it/s]

Preprocessing:  66%|██████▌   | 5551/8455 [06:33<04:38, 10.43it/s]

Preprocessing:  66%|██████▌   | 5553/8455 [06:33<04:21, 11.11it/s]

Preprocessing:  66%|██████▌   | 5555/8455 [06:33<03:53, 12.41it/s]

Preprocessing:  66%|██████▌   | 5557/8455 [06:33<03:38, 13.28it/s]

Preprocessing:  66%|██████▌   | 5559/8455 [06:34<03:45, 12.84it/s]

Preprocessing:  66%|██████▌   | 5561/8455 [06:34<03:28, 13.85it/s]

Preprocessing:  66%|██████▌   | 5564/8455 [06:34<02:59, 16.07it/s]

Preprocessing:  66%|██████▌   | 5567/8455 [06:34<02:39, 18.14it/s]

Preprocessing:  66%|██████▌   | 5569/8455 [06:34<02:39, 18.12it/s]

Preprocessing:  66%|██████▌   | 5571/8455 [06:34<02:50, 16.93it/s]

Preprocessing:  66%|██████▌   | 5573/8455 [06:34<02:57, 16.23it/s]

Preprocessing:  66%|██████▌   | 5575/8455 [06:35<03:11, 15.02it/s]

Preprocessing:  66%|██████▌   | 5577/8455 [06:35<03:09, 15.18it/s]

Preprocessing:  66%|██████▌   | 5579/8455 [06:35<03:07, 15.31it/s]

Preprocessing:  66%|██████▌   | 5581/8455 [06:35<03:13, 14.84it/s]

Preprocessing:  66%|██████▌   | 5583/8455 [06:35<03:02, 15.71it/s]

Preprocessing:  66%|██████▌   | 5585/8455 [06:35<02:54, 16.40it/s]

Preprocessing:  66%|██████▌   | 5587/8455 [06:35<02:58, 16.05it/s]

Preprocessing:  66%|██████▌   | 5589/8455 [06:35<03:00, 15.88it/s]

Preprocessing:  66%|██████▌   | 5592/8455 [06:36<02:46, 17.18it/s]

Preprocessing:  66%|██████▌   | 5594/8455 [06:36<02:57, 16.09it/s]

Preprocessing:  66%|██████▌   | 5596/8455 [06:36<02:56, 16.19it/s]

Preprocessing:  66%|██████▌   | 5598/8455 [06:36<02:48, 16.98it/s]

Preprocessing:  66%|██████▌   | 5601/8455 [06:36<02:33, 18.65it/s]

Preprocessing:  66%|██████▋   | 5603/8455 [06:36<02:33, 18.56it/s]

Preprocessing:  66%|██████▋   | 5605/8455 [06:36<02:33, 18.60it/s]

Preprocessing:  66%|██████▋   | 5607/8455 [06:36<02:33, 18.57it/s]

Preprocessing:  66%|██████▋   | 5609/8455 [06:36<02:33, 18.60it/s]

Preprocessing:  66%|██████▋   | 5612/8455 [06:37<02:25, 19.56it/s]

Preprocessing:  66%|██████▋   | 5614/8455 [06:37<02:26, 19.40it/s]

Preprocessing:  66%|██████▋   | 5616/8455 [06:37<02:28, 19.13it/s]

Preprocessing:  66%|██████▋   | 5618/8455 [06:37<02:30, 18.80it/s]

Preprocessing:  66%|██████▋   | 5620/8455 [06:37<02:31, 18.76it/s]

Preprocessing:  66%|██████▋   | 5622/8455 [06:37<02:30, 18.84it/s]

Preprocessing:  67%|██████▋   | 5624/8455 [06:37<02:31, 18.65it/s]

Preprocessing:  67%|██████▋   | 5627/8455 [06:37<02:24, 19.61it/s]

Preprocessing:  67%|██████▋   | 5630/8455 [06:38<02:18, 20.34it/s]

Preprocessing:  67%|██████▋   | 5633/8455 [06:38<02:15, 20.80it/s]

Preprocessing:  67%|██████▋   | 5636/8455 [06:38<02:16, 20.68it/s]

Preprocessing:  67%|██████▋   | 5639/8455 [06:38<02:18, 20.32it/s]

Preprocessing:  67%|██████▋   | 5642/8455 [06:38<02:19, 20.22it/s]

Preprocessing:  67%|██████▋   | 5645/8455 [06:38<02:27, 19.11it/s]

Preprocessing:  67%|██████▋   | 5647/8455 [06:38<02:30, 18.66it/s]

Preprocessing:  67%|██████▋   | 5649/8455 [06:39<02:28, 18.92it/s]

Preprocessing:  67%|██████▋   | 5652/8455 [06:39<02:35, 18.08it/s]

Preprocessing:  67%|██████▋   | 5654/8455 [06:39<02:48, 16.59it/s]

Preprocessing:  67%|██████▋   | 5656/8455 [06:39<02:51, 16.30it/s]

Preprocessing:  67%|██████▋   | 5659/8455 [06:39<02:39, 17.57it/s]

Preprocessing:  67%|██████▋   | 5661/8455 [06:39<02:50, 16.39it/s]

Preprocessing:  67%|██████▋   | 5663/8455 [06:39<02:42, 17.18it/s]

Preprocessing:  67%|██████▋   | 5666/8455 [06:40<02:30, 18.51it/s]

Preprocessing:  67%|██████▋   | 5669/8455 [06:40<02:26, 19.06it/s]

Preprocessing:  67%|██████▋   | 5671/8455 [06:40<02:38, 17.58it/s]

Preprocessing:  67%|██████▋   | 5673/8455 [06:40<02:36, 17.77it/s]

Preprocessing:  67%|██████▋   | 5676/8455 [06:40<02:29, 18.57it/s]

Preprocessing:  67%|██████▋   | 5679/8455 [06:40<02:24, 19.18it/s]

Preprocessing:  67%|██████▋   | 5681/8455 [06:40<02:36, 17.69it/s]

Preprocessing:  67%|██████▋   | 5683/8455 [06:40<02:44, 16.88it/s]

Preprocessing:  67%|██████▋   | 5685/8455 [06:41<03:05, 14.97it/s]

Preprocessing:  67%|██████▋   | 5687/8455 [06:41<03:09, 14.60it/s]

Preprocessing:  67%|██████▋   | 5689/8455 [06:41<02:59, 15.42it/s]

Preprocessing:  67%|██████▋   | 5692/8455 [06:41<02:42, 17.02it/s]

Preprocessing:  67%|██████▋   | 5694/8455 [06:41<02:44, 16.80it/s]

Preprocessing:  67%|██████▋   | 5696/8455 [06:41<02:46, 16.58it/s]

Preprocessing:  67%|██████▋   | 5699/8455 [06:41<02:32, 18.05it/s]

Preprocessing:  67%|██████▋   | 5701/8455 [06:42<02:31, 18.16it/s]

Preprocessing:  67%|██████▋   | 5704/8455 [06:42<02:25, 18.93it/s]

Preprocessing:  67%|██████▋   | 5706/8455 [06:42<02:25, 18.90it/s]

Preprocessing:  68%|██████▊   | 5708/8455 [06:42<02:43, 16.85it/s]

Preprocessing:  68%|██████▊   | 5710/8455 [06:42<02:43, 16.81it/s]

Preprocessing:  68%|██████▊   | 5712/8455 [06:42<02:39, 17.17it/s]

Preprocessing:  68%|██████▊   | 5715/8455 [06:42<02:21, 19.33it/s]

Preprocessing:  68%|██████▊   | 5718/8455 [06:42<02:20, 19.52it/s]

Preprocessing:  68%|██████▊   | 5721/8455 [06:43<02:19, 19.58it/s]

Preprocessing:  68%|██████▊   | 5723/8455 [06:43<02:24, 18.88it/s]

Preprocessing:  68%|██████▊   | 5725/8455 [06:43<02:22, 19.10it/s]

Preprocessing:  68%|██████▊   | 5728/8455 [06:43<02:16, 20.03it/s]

Preprocessing:  68%|██████▊   | 5731/8455 [06:43<02:07, 21.38it/s]

Preprocessing:  68%|██████▊   | 5734/8455 [06:43<02:10, 20.92it/s]

Preprocessing:  68%|██████▊   | 5737/8455 [06:43<02:11, 20.63it/s]

Preprocessing:  68%|██████▊   | 5740/8455 [06:44<02:10, 20.77it/s]

Preprocessing:  68%|██████▊   | 5743/8455 [06:44<02:19, 19.50it/s]

Preprocessing:  68%|██████▊   | 5746/8455 [06:44<02:10, 20.78it/s]

Preprocessing:  68%|██████▊   | 5749/8455 [06:44<02:07, 21.26it/s]

Preprocessing:  68%|██████▊   | 5752/8455 [06:44<02:27, 18.30it/s]

Preprocessing:  68%|██████▊   | 5754/8455 [06:44<02:37, 17.16it/s]

Preprocessing:  68%|██████▊   | 5756/8455 [06:44<02:42, 16.59it/s]

Preprocessing:  68%|██████▊   | 5758/8455 [06:45<02:47, 16.09it/s]

Preprocessing:  68%|██████▊   | 5760/8455 [06:45<02:44, 16.40it/s]

Preprocessing:  68%|██████▊   | 5763/8455 [06:45<02:27, 18.28it/s]

Preprocessing:  68%|██████▊   | 5765/8455 [06:45<02:24, 18.67it/s]

Preprocessing:  68%|██████▊   | 5768/8455 [06:45<02:13, 20.18it/s]

Preprocessing:  68%|██████▊   | 5771/8455 [06:45<02:15, 19.87it/s]

Preprocessing:  68%|██████▊   | 5774/8455 [06:45<02:10, 20.54it/s]

Preprocessing:  68%|██████▊   | 5777/8455 [06:46<02:30, 17.83it/s]

Preprocessing:  68%|██████▊   | 5779/8455 [06:46<02:43, 16.40it/s]

Preprocessing:  68%|██████▊   | 5781/8455 [06:46<02:49, 15.75it/s]

Preprocessing:  68%|██████▊   | 5783/8455 [06:46<02:51, 15.55it/s]

Preprocessing:  68%|██████▊   | 5786/8455 [06:46<02:43, 16.36it/s]

Preprocessing:  68%|██████▊   | 5788/8455 [06:46<02:44, 16.23it/s]

Preprocessing:  68%|██████▊   | 5790/8455 [06:46<02:41, 16.49it/s]

Preprocessing:  69%|██████▊   | 5792/8455 [06:47<02:37, 16.94it/s]

Preprocessing:  69%|██████▊   | 5794/8455 [06:47<02:34, 17.18it/s]

Preprocessing:  69%|██████▊   | 5796/8455 [06:47<02:42, 16.31it/s]

Preprocessing:  69%|██████▊   | 5798/8455 [06:47<02:35, 17.04it/s]

Preprocessing:  69%|██████▊   | 5800/8455 [06:47<02:30, 17.68it/s]

Preprocessing:  69%|██████▊   | 5803/8455 [06:47<02:17, 19.31it/s]

Preprocessing:  69%|██████▊   | 5806/8455 [06:47<02:12, 19.96it/s]

Preprocessing:  69%|██████▊   | 5808/8455 [06:47<02:28, 17.87it/s]

Preprocessing:  69%|██████▊   | 5810/8455 [06:48<02:46, 15.85it/s]

Preprocessing:  69%|██████▊   | 5812/8455 [06:48<03:05, 14.28it/s]

Preprocessing:  69%|██████▉   | 5814/8455 [06:48<03:09, 13.96it/s]

Preprocessing:  69%|██████▉   | 5816/8455 [06:48<03:01, 14.51it/s]

Preprocessing:  69%|██████▉   | 5818/8455 [06:48<03:01, 14.50it/s]

Preprocessing:  69%|██████▉   | 5820/8455 [06:48<03:01, 14.49it/s]

Preprocessing:  69%|██████▉   | 5822/8455 [06:48<02:59, 14.64it/s]

Preprocessing:  69%|██████▉   | 5824/8455 [06:49<03:07, 14.01it/s]

Preprocessing:  69%|██████▉   | 5826/8455 [06:49<03:06, 14.09it/s]

Preprocessing:  69%|██████▉   | 5828/8455 [06:49<03:08, 13.94it/s]

Preprocessing:  69%|██████▉   | 5830/8455 [06:49<03:01, 14.46it/s]

Preprocessing:  69%|██████▉   | 5832/8455 [06:49<02:56, 14.82it/s]

Preprocessing:  69%|██████▉   | 5834/8455 [06:49<02:52, 15.23it/s]

Preprocessing:  69%|██████▉   | 5836/8455 [06:49<02:51, 15.26it/s]

Preprocessing:  69%|██████▉   | 5838/8455 [06:50<02:52, 15.13it/s]

Preprocessing:  69%|██████▉   | 5840/8455 [06:50<03:06, 14.00it/s]

Preprocessing:  69%|██████▉   | 5842/8455 [06:50<03:22, 12.88it/s]

Preprocessing:  69%|██████▉   | 5844/8455 [06:50<03:27, 12.58it/s]

Preprocessing:  69%|██████▉   | 5846/8455 [06:50<03:14, 13.39it/s]

Preprocessing:  69%|██████▉   | 5848/8455 [06:50<03:11, 13.63it/s]

Preprocessing:  69%|██████▉   | 5850/8455 [06:50<03:12, 13.56it/s]

Preprocessing:  69%|██████▉   | 5852/8455 [06:51<03:02, 14.29it/s]

Preprocessing:  69%|██████▉   | 5854/8455 [06:51<02:58, 14.56it/s]

Preprocessing:  69%|██████▉   | 5856/8455 [06:51<03:00, 14.44it/s]

Preprocessing:  69%|██████▉   | 5858/8455 [06:51<03:03, 14.12it/s]

Preprocessing:  69%|██████▉   | 5860/8455 [06:51<03:03, 14.18it/s]

Preprocessing:  69%|██████▉   | 5862/8455 [06:51<02:57, 14.57it/s]

Preprocessing:  69%|██████▉   | 5864/8455 [06:51<02:51, 15.14it/s]

Preprocessing:  69%|██████▉   | 5866/8455 [06:52<02:57, 14.55it/s]

Preprocessing:  69%|██████▉   | 5868/8455 [06:52<03:01, 14.26it/s]

Preprocessing:  69%|██████▉   | 5870/8455 [06:52<03:10, 13.58it/s]

Preprocessing:  69%|██████▉   | 5872/8455 [06:52<03:24, 12.64it/s]

Preprocessing:  69%|██████▉   | 5874/8455 [06:52<03:24, 12.64it/s]

Preprocessing:  69%|██████▉   | 5876/8455 [06:52<03:16, 13.13it/s]

Preprocessing:  70%|██████▉   | 5878/8455 [06:52<03:19, 12.95it/s]

Preprocessing:  70%|██████▉   | 5880/8455 [06:53<03:17, 13.04it/s]

Preprocessing:  70%|██████▉   | 5882/8455 [06:53<03:13, 13.27it/s]

Preprocessing:  70%|██████▉   | 5884/8455 [06:53<03:09, 13.60it/s]

Preprocessing:  70%|██████▉   | 5886/8455 [06:53<03:06, 13.81it/s]

Preprocessing:  70%|██████▉   | 5888/8455 [06:53<03:02, 14.10it/s]

Preprocessing:  70%|██████▉   | 5890/8455 [06:53<03:04, 13.93it/s]

Preprocessing:  70%|██████▉   | 5892/8455 [06:54<03:08, 13.63it/s]

Preprocessing:  70%|██████▉   | 5894/8455 [06:54<03:00, 14.21it/s]

Preprocessing:  70%|██████▉   | 5896/8455 [06:54<02:54, 14.68it/s]

Preprocessing:  70%|██████▉   | 5898/8455 [06:54<02:54, 14.64it/s]

Preprocessing:  70%|██████▉   | 5900/8455 [06:54<02:51, 14.94it/s]

Preprocessing:  70%|██████▉   | 5902/8455 [06:54<02:59, 14.22it/s]

Preprocessing:  70%|██████▉   | 5904/8455 [06:54<02:51, 14.91it/s]

Preprocessing:  70%|██████▉   | 5906/8455 [06:55<03:20, 12.69it/s]

Preprocessing:  70%|██████▉   | 5908/8455 [06:55<03:46, 11.23it/s]

Preprocessing:  70%|██████▉   | 5910/8455 [06:55<03:48, 11.13it/s]

Preprocessing:  70%|██████▉   | 5912/8455 [06:55<03:44, 11.34it/s]

Preprocessing:  70%|██████▉   | 5914/8455 [06:55<03:51, 10.96it/s]

Preprocessing:  70%|██████▉   | 5916/8455 [06:55<03:44, 11.32it/s]

Preprocessing:  70%|██████▉   | 5918/8455 [06:56<03:52, 10.90it/s]

Preprocessing:  70%|███████   | 5920/8455 [06:56<04:02, 10.44it/s]

Preprocessing:  70%|███████   | 5922/8455 [06:56<04:07, 10.22it/s]

Preprocessing:  70%|███████   | 5924/8455 [06:56<04:11, 10.05it/s]

Preprocessing:  70%|███████   | 5926/8455 [06:56<04:20,  9.70it/s]

Preprocessing:  70%|███████   | 5928/8455 [06:57<04:05, 10.28it/s]

Preprocessing:  70%|███████   | 5930/8455 [06:57<03:56, 10.68it/s]

Preprocessing:  70%|███████   | 5932/8455 [06:57<03:49, 10.98it/s]

Preprocessing:  70%|███████   | 5934/8455 [06:57<03:44, 11.21it/s]

Preprocessing:  70%|███████   | 5936/8455 [06:57<03:32, 11.85it/s]

Preprocessing:  70%|███████   | 5938/8455 [06:57<03:10, 13.23it/s]

Preprocessing:  70%|███████   | 5940/8455 [06:58<03:03, 13.72it/s]

Preprocessing:  70%|███████   | 5942/8455 [06:58<02:58, 14.04it/s]

Preprocessing:  70%|███████   | 5944/8455 [06:58<03:04, 13.58it/s]

Preprocessing:  70%|███████   | 5946/8455 [06:58<04:07, 10.12it/s]

Preprocessing:  70%|███████   | 5948/8455 [06:58<04:09, 10.05it/s]

Preprocessing:  70%|███████   | 5950/8455 [06:59<04:14,  9.84it/s]

Preprocessing:  70%|███████   | 5952/8455 [06:59<04:09, 10.02it/s]

Preprocessing:  70%|███████   | 5954/8455 [06:59<03:50, 10.85it/s]

Preprocessing:  70%|███████   | 5956/8455 [06:59<03:25, 12.15it/s]

Preprocessing:  70%|███████   | 5958/8455 [06:59<03:48, 10.95it/s]

Preprocessing:  70%|███████   | 5960/8455 [06:59<03:33, 11.66it/s]

Preprocessing:  71%|███████   | 5962/8455 [07:00<03:16, 12.70it/s]

Preprocessing:  71%|███████   | 5964/8455 [07:00<03:06, 13.38it/s]

Preprocessing:  71%|███████   | 5966/8455 [07:00<02:57, 14.02it/s]

Preprocessing:  71%|███████   | 5968/8455 [07:00<02:50, 14.59it/s]

Preprocessing:  71%|███████   | 5970/8455 [07:00<02:54, 14.25it/s]

Preprocessing:  71%|███████   | 5972/8455 [07:00<03:12, 12.88it/s]

Preprocessing:  71%|███████   | 5974/8455 [07:00<03:21, 12.30it/s]

Preprocessing:  71%|███████   | 5976/8455 [07:01<03:31, 11.70it/s]

Preprocessing:  71%|███████   | 5978/8455 [07:01<03:33, 11.59it/s]

Preprocessing:  71%|███████   | 5980/8455 [07:01<03:29, 11.82it/s]

Preprocessing:  71%|███████   | 5982/8455 [07:01<03:20, 12.34it/s]

Preprocessing:  71%|███████   | 5984/8455 [07:01<03:38, 11.33it/s]

Preprocessing:  71%|███████   | 5986/8455 [07:02<03:53, 10.57it/s]

Preprocessing:  71%|███████   | 5988/8455 [07:02<03:49, 10.73it/s]

Preprocessing:  71%|███████   | 5990/8455 [07:02<03:39, 11.22it/s]

Preprocessing:  71%|███████   | 5992/8455 [07:02<03:43, 11.01it/s]

Preprocessing:  71%|███████   | 5994/8455 [07:02<03:34, 11.47it/s]

Preprocessing:  71%|███████   | 5996/8455 [07:02<03:34, 11.49it/s]

Preprocessing:  71%|███████   | 5998/8455 [07:03<03:56, 10.37it/s]

Preprocessing:  71%|███████   | 6000/8455 [07:03<04:02, 10.11it/s]

Preprocessing:  71%|███████   | 6002/8455 [07:03<04:04, 10.03it/s]

Preprocessing:  71%|███████   | 6004/8455 [07:03<04:09,  9.83it/s]

Preprocessing:  71%|███████   | 6005/8455 [07:03<04:11,  9.76it/s]

Preprocessing:  71%|███████   | 6006/8455 [07:03<04:13,  9.65it/s]

Preprocessing:  71%|███████   | 6007/8455 [07:04<04:13,  9.67it/s]

Preprocessing:  71%|███████   | 6008/8455 [07:04<04:16,  9.53it/s]

Preprocessing:  71%|███████   | 6009/8455 [07:04<04:15,  9.56it/s]

Preprocessing:  71%|███████   | 6010/8455 [07:04<04:21,  9.35it/s]

Preprocessing:  71%|███████   | 6012/8455 [07:04<04:06,  9.93it/s]

Preprocessing:  71%|███████   | 6013/8455 [07:04<04:19,  9.42it/s]

Preprocessing:  71%|███████   | 6014/8455 [07:04<04:42,  8.63it/s]

Preprocessing:  71%|███████   | 6016/8455 [07:05<04:25,  9.18it/s]

Preprocessing:  71%|███████   | 6017/8455 [07:05<04:30,  9.02it/s]

Preprocessing:  71%|███████   | 6019/8455 [07:05<04:14,  9.59it/s]

Preprocessing:  71%|███████   | 6021/8455 [07:05<03:42, 10.94it/s]

Preprocessing:  71%|███████   | 6023/8455 [07:05<03:38, 11.14it/s]

Preprocessing:  71%|███████▏  | 6025/8455 [07:05<04:04,  9.95it/s]

Preprocessing:  71%|███████▏  | 6027/8455 [07:06<04:09,  9.71it/s]

Preprocessing:  71%|███████▏  | 6028/8455 [07:06<04:11,  9.65it/s]

Preprocessing:  71%|███████▏  | 6030/8455 [07:06<03:51, 10.48it/s]

Preprocessing:  71%|███████▏  | 6032/8455 [07:06<03:34, 11.28it/s]

Preprocessing:  71%|███████▏  | 6034/8455 [07:06<03:38, 11.07it/s]

Preprocessing:  71%|███████▏  | 6036/8455 [07:06<03:49, 10.54it/s]

Preprocessing:  71%|███████▏  | 6038/8455 [07:07<03:34, 11.28it/s]

Preprocessing:  71%|███████▏  | 6040/8455 [07:07<03:35, 11.19it/s]

Preprocessing:  71%|███████▏  | 6042/8455 [07:07<03:32, 11.35it/s]

Preprocessing:  71%|███████▏  | 6044/8455 [07:07<03:53, 10.34it/s]

Preprocessing:  72%|███████▏  | 6046/8455 [07:07<03:42, 10.84it/s]

Preprocessing:  72%|███████▏  | 6048/8455 [07:08<03:40, 10.92it/s]

Preprocessing:  72%|███████▏  | 6050/8455 [07:08<03:46, 10.64it/s]

Preprocessing:  72%|███████▏  | 6052/8455 [07:08<03:40, 10.89it/s]

Preprocessing:  72%|███████▏  | 6054/8455 [07:08<03:44, 10.69it/s]

Preprocessing:  72%|███████▏  | 6056/8455 [07:08<03:35, 11.13it/s]

Preprocessing:  72%|███████▏  | 6058/8455 [07:08<03:20, 11.97it/s]

Preprocessing:  72%|███████▏  | 6060/8455 [07:09<03:40, 10.84it/s]

Preprocessing:  72%|███████▏  | 6062/8455 [07:09<03:37, 10.99it/s]

Preprocessing:  72%|███████▏  | 6064/8455 [07:09<03:41, 10.78it/s]

Preprocessing:  72%|███████▏  | 6066/8455 [07:09<04:01,  9.88it/s]

Preprocessing:  72%|███████▏  | 6068/8455 [07:09<04:08,  9.59it/s]

Preprocessing:  72%|███████▏  | 6070/8455 [07:10<03:52, 10.27it/s]

Preprocessing:  72%|███████▏  | 6072/8455 [07:10<03:46, 10.53it/s]

Preprocessing:  72%|███████▏  | 6074/8455 [07:10<03:35, 11.07it/s]

Preprocessing:  72%|███████▏  | 6076/8455 [07:10<03:39, 10.85it/s]

Preprocessing:  72%|███████▏  | 6078/8455 [07:10<03:51, 10.26it/s]

Preprocessing:  72%|███████▏  | 6080/8455 [07:11<03:55, 10.09it/s]

Preprocessing:  72%|███████▏  | 6082/8455 [07:11<03:53, 10.17it/s]

Preprocessing:  72%|███████▏  | 6084/8455 [07:11<03:40, 10.76it/s]

Preprocessing:  72%|███████▏  | 6086/8455 [07:11<03:28, 11.36it/s]

Preprocessing:  72%|███████▏  | 6088/8455 [07:11<03:30, 11.26it/s]

Preprocessing:  72%|███████▏  | 6090/8455 [07:11<03:46, 10.42it/s]

Preprocessing:  72%|███████▏  | 6092/8455 [07:12<03:54, 10.06it/s]

Preprocessing:  72%|███████▏  | 6094/8455 [07:12<03:47, 10.40it/s]

Preprocessing:  72%|███████▏  | 6096/8455 [07:12<03:54, 10.04it/s]

Preprocessing:  72%|███████▏  | 6098/8455 [07:12<04:07,  9.54it/s]

Preprocessing:  72%|███████▏  | 6099/8455 [07:12<04:15,  9.22it/s]

Preprocessing:  72%|███████▏  | 6100/8455 [07:13<04:31,  8.67it/s]

Preprocessing:  72%|███████▏  | 6101/8455 [07:13<04:33,  8.61it/s]

Preprocessing:  72%|███████▏  | 6103/8455 [07:13<04:28,  8.75it/s]

Preprocessing:  72%|███████▏  | 6105/8455 [07:13<04:23,  8.91it/s]

Preprocessing:  72%|███████▏  | 6106/8455 [07:13<04:27,  8.78it/s]

Preprocessing:  72%|███████▏  | 6107/8455 [07:13<04:33,  8.60it/s]

Preprocessing:  72%|███████▏  | 6109/8455 [07:14<04:21,  8.98it/s]

Preprocessing:  72%|███████▏  | 6110/8455 [07:14<04:29,  8.69it/s]

Preprocessing:  72%|███████▏  | 6111/8455 [07:14<04:29,  8.68it/s]

Preprocessing:  72%|███████▏  | 6113/8455 [07:14<04:13,  9.24it/s]

Preprocessing:  72%|███████▏  | 6115/8455 [07:14<03:45, 10.39it/s]

Preprocessing:  72%|███████▏  | 6117/8455 [07:14<03:51, 10.08it/s]

Preprocessing:  72%|███████▏  | 6119/8455 [07:15<03:52, 10.03it/s]

Preprocessing:  72%|███████▏  | 6121/8455 [07:15<03:52, 10.02it/s]

Preprocessing:  72%|███████▏  | 6123/8455 [07:15<03:40, 10.59it/s]

Preprocessing:  72%|███████▏  | 6125/8455 [07:15<03:57,  9.80it/s]

Preprocessing:  72%|███████▏  | 6127/8455 [07:15<03:59,  9.72it/s]

Preprocessing:  72%|███████▏  | 6128/8455 [07:16<04:08,  9.38it/s]

Preprocessing:  72%|███████▏  | 6129/8455 [07:16<04:16,  9.06it/s]

Preprocessing:  73%|███████▎  | 6131/8455 [07:16<04:11,  9.25it/s]

Preprocessing:  73%|███████▎  | 6132/8455 [07:16<04:18,  9.00it/s]

Preprocessing:  73%|███████▎  | 6134/8455 [07:16<03:57,  9.78it/s]

Preprocessing:  73%|███████▎  | 6135/8455 [07:16<04:00,  9.66it/s]

Preprocessing:  73%|███████▎  | 6136/8455 [07:16<04:03,  9.53it/s]

Preprocessing:  73%|███████▎  | 6138/8455 [07:17<04:03,  9.52it/s]

Preprocessing:  73%|███████▎  | 6139/8455 [07:17<04:06,  9.39it/s]

Preprocessing:  73%|███████▎  | 6141/8455 [07:17<03:57,  9.76it/s]

Preprocessing:  73%|███████▎  | 6142/8455 [07:17<03:58,  9.69it/s]

Preprocessing:  73%|███████▎  | 6143/8455 [07:17<04:04,  9.45it/s]

Preprocessing:  73%|███████▎  | 6144/8455 [07:17<04:06,  9.37it/s]

Preprocessing:  73%|███████▎  | 6145/8455 [07:17<04:08,  9.30it/s]

Preprocessing:  73%|███████▎  | 6146/8455 [07:17<04:14,  9.06it/s]

Preprocessing:  73%|███████▎  | 6147/8455 [07:18<04:12,  9.15it/s]

Preprocessing:  73%|███████▎  | 6148/8455 [07:18<04:11,  9.16it/s]

Preprocessing:  73%|███████▎  | 6150/8455 [07:18<03:44, 10.27it/s]

Preprocessing:  73%|███████▎  | 6152/8455 [07:18<03:59,  9.63it/s]

Preprocessing:  73%|███████▎  | 6154/8455 [07:18<03:49, 10.02it/s]

Preprocessing:  73%|███████▎  | 6155/8455 [07:18<03:55,  9.78it/s]

Preprocessing:  73%|███████▎  | 6156/8455 [07:18<04:04,  9.40it/s]

Preprocessing:  73%|███████▎  | 6158/8455 [07:19<03:54,  9.80it/s]

Preprocessing:  73%|███████▎  | 6160/8455 [07:19<03:46, 10.12it/s]

Preprocessing:  73%|███████▎  | 6162/8455 [07:19<03:25, 11.18it/s]

Preprocessing:  73%|███████▎  | 6164/8455 [07:19<03:26, 11.08it/s]

Preprocessing:  73%|███████▎  | 6166/8455 [07:19<03:40, 10.37it/s]

Preprocessing:  73%|███████▎  | 6168/8455 [07:20<03:47, 10.06it/s]

Preprocessing:  73%|███████▎  | 6170/8455 [07:20<03:43, 10.23it/s]

Preprocessing:  73%|███████▎  | 6172/8455 [07:20<03:49,  9.97it/s]

Preprocessing:  73%|███████▎  | 6174/8455 [07:20<03:58,  9.57it/s]

Preprocessing:  73%|███████▎  | 6175/8455 [07:20<04:01,  9.45it/s]

Preprocessing:  73%|███████▎  | 6176/8455 [07:20<04:00,  9.47it/s]

Preprocessing:  73%|███████▎  | 6178/8455 [07:21<03:54,  9.73it/s]

Preprocessing:  73%|███████▎  | 6179/8455 [07:21<03:56,  9.64it/s]

Preprocessing:  73%|███████▎  | 6180/8455 [07:21<04:01,  9.40it/s]

Preprocessing:  73%|███████▎  | 6182/8455 [07:21<03:40, 10.32it/s]

Preprocessing:  73%|███████▎  | 6184/8455 [07:21<03:37, 10.45it/s]

Preprocessing:  73%|███████▎  | 6186/8455 [07:21<03:33, 10.61it/s]

Preprocessing:  73%|███████▎  | 6188/8455 [07:22<03:46, 10.02it/s]

Preprocessing:  73%|███████▎  | 6190/8455 [07:22<03:41, 10.22it/s]

Preprocessing:  73%|███████▎  | 6192/8455 [07:22<03:37, 10.39it/s]

Preprocessing:  73%|███████▎  | 6194/8455 [07:22<03:48,  9.88it/s]

Preprocessing:  73%|███████▎  | 6195/8455 [07:22<03:54,  9.63it/s]

Preprocessing:  73%|███████▎  | 6196/8455 [07:22<03:55,  9.61it/s]

Preprocessing:  73%|███████▎  | 6197/8455 [07:23<04:02,  9.30it/s]

Preprocessing:  73%|███████▎  | 6198/8455 [07:23<03:59,  9.40it/s]

Preprocessing:  73%|███████▎  | 6199/8455 [07:23<04:00,  9.38it/s]

Preprocessing:  73%|███████▎  | 6200/8455 [07:23<03:58,  9.46it/s]

Preprocessing:  73%|███████▎  | 6201/8455 [07:23<04:12,  8.92it/s]

Preprocessing:  73%|███████▎  | 6203/8455 [07:23<04:05,  9.16it/s]

Preprocessing:  73%|███████▎  | 6204/8455 [07:23<04:14,  8.84it/s]

Preprocessing:  73%|███████▎  | 6205/8455 [07:23<04:22,  8.57it/s]

Preprocessing:  73%|███████▎  | 6206/8455 [07:24<04:23,  8.53it/s]

Preprocessing:  73%|███████▎  | 6208/8455 [07:24<03:58,  9.43it/s]

Preprocessing:  73%|███████▎  | 6209/8455 [07:24<04:04,  9.20it/s]

Preprocessing:  73%|███████▎  | 6210/8455 [07:24<04:15,  8.78it/s]

Preprocessing:  73%|███████▎  | 6211/8455 [07:24<04:33,  8.22it/s]

Preprocessing:  73%|███████▎  | 6212/8455 [07:24<04:44,  7.90it/s]

Preprocessing:  73%|███████▎  | 6213/8455 [07:24<04:53,  7.64it/s]

Preprocessing:  73%|███████▎  | 6214/8455 [07:25<04:47,  7.80it/s]

Preprocessing:  74%|███████▎  | 6215/8455 [07:25<04:44,  7.87it/s]

Preprocessing:  74%|███████▎  | 6216/8455 [07:25<04:31,  8.23it/s]

Preprocessing:  74%|███████▎  | 6217/8455 [07:25<04:33,  8.18it/s]

Preprocessing:  74%|███████▎  | 6218/8455 [07:25<04:32,  8.21it/s]

Preprocessing:  74%|███████▎  | 6219/8455 [07:25<04:33,  8.18it/s]

Preprocessing:  74%|███████▎  | 6220/8455 [07:25<04:26,  8.37it/s]

Preprocessing:  74%|███████▎  | 6221/8455 [07:25<04:28,  8.33it/s]

Preprocessing:  74%|███████▎  | 6222/8455 [07:26<04:20,  8.56it/s]

Preprocessing:  74%|███████▎  | 6223/8455 [07:26<04:38,  8.02it/s]

Preprocessing:  74%|███████▎  | 6224/8455 [07:26<04:47,  7.76it/s]

Preprocessing:  74%|███████▎  | 6225/8455 [07:26<04:39,  7.99it/s]

Preprocessing:  74%|███████▎  | 6227/8455 [07:26<04:09,  8.95it/s]

Preprocessing:  74%|███████▎  | 6229/8455 [07:26<03:58,  9.35it/s]

Preprocessing:  74%|███████▎  | 6231/8455 [07:27<03:51,  9.62it/s]

Preprocessing:  74%|███████▎  | 6233/8455 [07:27<03:50,  9.62it/s]

Preprocessing:  74%|███████▎  | 6234/8455 [07:27<03:51,  9.59it/s]

Preprocessing:  74%|███████▎  | 6235/8455 [07:27<03:53,  9.51it/s]

Preprocessing:  74%|███████▍  | 6236/8455 [07:27<03:55,  9.42it/s]

Preprocessing:  74%|███████▍  | 6237/8455 [07:27<04:22,  8.45it/s]

Preprocessing:  74%|███████▍  | 6239/8455 [07:27<03:42,  9.97it/s]

Preprocessing:  74%|███████▍  | 6240/8455 [07:27<03:48,  9.69it/s]

Preprocessing:  74%|███████▍  | 6242/8455 [07:28<03:28, 10.59it/s]

Preprocessing:  74%|███████▍  | 6244/8455 [07:28<03:32, 10.41it/s]

Preprocessing:  74%|███████▍  | 6246/8455 [07:28<03:42,  9.94it/s]

Preprocessing:  74%|███████▍  | 6248/8455 [07:28<03:33, 10.33it/s]

Preprocessing:  74%|███████▍  | 6250/8455 [07:28<03:30, 10.48it/s]

Preprocessing:  74%|███████▍  | 6252/8455 [07:29<03:31, 10.42it/s]

Preprocessing:  74%|███████▍  | 6254/8455 [07:29<03:55,  9.34it/s]

Preprocessing:  74%|███████▍  | 6256/8455 [07:29<03:43,  9.84it/s]

Preprocessing:  74%|███████▍  | 6258/8455 [07:29<03:52,  9.45it/s]

Preprocessing:  74%|███████▍  | 6259/8455 [07:29<03:52,  9.44it/s]

Preprocessing:  74%|███████▍  | 6260/8455 [07:29<03:54,  9.36it/s]

Preprocessing:  74%|███████▍  | 6261/8455 [07:30<03:53,  9.38it/s]

Preprocessing:  74%|███████▍  | 6262/8455 [07:30<04:05,  8.94it/s]

Preprocessing:  74%|███████▍  | 6264/8455 [07:30<03:49,  9.53it/s]

Preprocessing:  74%|███████▍  | 6265/8455 [07:30<03:55,  9.30it/s]

Preprocessing:  74%|███████▍  | 6267/8455 [07:30<03:32, 10.29it/s]

Preprocessing:  74%|███████▍  | 6269/8455 [07:30<03:33, 10.23it/s]

Preprocessing:  74%|███████▍  | 6271/8455 [07:31<03:47,  9.61it/s]

Preprocessing:  74%|███████▍  | 6272/8455 [07:31<03:50,  9.46it/s]

Preprocessing:  74%|███████▍  | 6274/8455 [07:31<03:24, 10.68it/s]

Preprocessing:  74%|███████▍  | 6276/8455 [07:31<03:35, 10.11it/s]

Preprocessing:  74%|███████▍  | 6278/8455 [07:31<03:24, 10.67it/s]

Preprocessing:  74%|███████▍  | 6280/8455 [07:31<03:30, 10.35it/s]

Preprocessing:  74%|███████▍  | 6282/8455 [07:32<03:27, 10.49it/s]

Preprocessing:  74%|███████▍  | 6284/8455 [07:32<03:39,  9.88it/s]

Preprocessing:  74%|███████▍  | 6286/8455 [07:32<03:39,  9.90it/s]

Preprocessing:  74%|███████▍  | 6288/8455 [07:32<03:51,  9.36it/s]

Preprocessing:  74%|███████▍  | 6289/8455 [07:32<03:54,  9.23it/s]

Preprocessing:  74%|███████▍  | 6291/8455 [07:33<03:37,  9.95it/s]

Preprocessing:  74%|███████▍  | 6292/8455 [07:33<03:40,  9.81it/s]

Preprocessing:  74%|███████▍  | 6294/8455 [07:33<03:37,  9.92it/s]

Preprocessing:  74%|███████▍  | 6295/8455 [07:33<03:53,  9.25it/s]

Preprocessing:  74%|███████▍  | 6297/8455 [07:33<03:43,  9.66it/s]

Preprocessing:  74%|███████▍  | 6298/8455 [07:33<03:45,  9.57it/s]

Preprocessing:  75%|███████▍  | 6299/8455 [07:33<03:50,  9.36it/s]

Preprocessing:  75%|███████▍  | 6300/8455 [07:34<03:54,  9.17it/s]

Preprocessing:  75%|███████▍  | 6301/8455 [07:34<03:56,  9.11it/s]

Preprocessing:  75%|███████▍  | 6302/8455 [07:34<04:08,  8.65it/s]

Preprocessing:  75%|███████▍  | 6303/8455 [07:34<04:15,  8.43it/s]

Preprocessing:  75%|███████▍  | 6304/8455 [07:34<04:16,  8.40it/s]

Preprocessing:  75%|███████▍  | 6306/8455 [07:34<04:00,  8.93it/s]

Preprocessing:  75%|███████▍  | 6308/8455 [07:34<03:48,  9.40it/s]

Preprocessing:  75%|███████▍  | 6310/8455 [07:35<03:35,  9.95it/s]

Preprocessing:  75%|███████▍  | 6312/8455 [07:35<03:35,  9.92it/s]

Preprocessing:  75%|███████▍  | 6313/8455 [07:35<03:39,  9.75it/s]

Preprocessing:  75%|███████▍  | 6314/8455 [07:35<03:53,  9.16it/s]

Preprocessing:  75%|███████▍  | 6315/8455 [07:35<03:59,  8.93it/s]

Preprocessing:  75%|███████▍  | 6316/8455 [07:35<03:57,  9.01it/s]

Preprocessing:  75%|███████▍  | 6317/8455 [07:36<04:33,  7.81it/s]

Preprocessing:  75%|███████▍  | 6318/8455 [07:36<04:39,  7.64it/s]

Preprocessing:  75%|███████▍  | 6319/8455 [07:36<04:43,  7.52it/s]

Preprocessing:  75%|███████▍  | 6321/8455 [07:36<04:08,  8.59it/s]

Preprocessing:  75%|███████▍  | 6323/8455 [07:36<03:42,  9.56it/s]

Preprocessing:  75%|███████▍  | 6325/8455 [07:36<03:25, 10.35it/s]

Preprocessing:  75%|███████▍  | 6327/8455 [07:36<03:09, 11.21it/s]

Preprocessing:  75%|███████▍  | 6329/8455 [07:37<03:05, 11.47it/s]

Preprocessing:  75%|███████▍  | 6331/8455 [07:37<03:11, 11.10it/s]

Preprocessing:  75%|███████▍  | 6333/8455 [07:37<03:12, 11.03it/s]

Preprocessing:  75%|███████▍  | 6335/8455 [07:37<03:13, 10.97it/s]

Preprocessing:  75%|███████▍  | 6337/8455 [07:37<03:06, 11.38it/s]

Preprocessing:  75%|███████▍  | 6339/8455 [07:38<03:08, 11.21it/s]

Preprocessing:  75%|███████▍  | 6341/8455 [07:38<03:10, 11.07it/s]

Preprocessing:  75%|███████▌  | 6343/8455 [07:38<03:21, 10.49it/s]

Preprocessing:  75%|███████▌  | 6345/8455 [07:38<03:17, 10.67it/s]

Preprocessing:  75%|███████▌  | 6347/8455 [07:38<03:17, 10.66it/s]

Preprocessing:  75%|███████▌  | 6349/8455 [07:38<03:16, 10.71it/s]

Preprocessing:  75%|███████▌  | 6351/8455 [07:39<03:12, 10.93it/s]

Preprocessing:  75%|███████▌  | 6353/8455 [07:39<03:10, 11.03it/s]

Preprocessing:  75%|███████▌  | 6355/8455 [07:39<03:14, 10.78it/s]

Preprocessing:  75%|███████▌  | 6357/8455 [07:39<03:21, 10.40it/s]

Preprocessing:  75%|███████▌  | 6359/8455 [07:39<03:15, 10.73it/s]

Preprocessing:  75%|███████▌  | 6361/8455 [07:40<03:09, 11.07it/s]

Preprocessing:  75%|███████▌  | 6363/8455 [07:40<03:11, 10.91it/s]

Preprocessing:  75%|███████▌  | 6365/8455 [07:40<03:01, 11.54it/s]

Preprocessing:  75%|███████▌  | 6367/8455 [07:40<02:54, 11.99it/s]

Preprocessing:  75%|███████▌  | 6369/8455 [07:40<02:57, 11.75it/s]

Preprocessing:  75%|███████▌  | 6371/8455 [07:40<03:00, 11.54it/s]

Preprocessing:  75%|███████▌  | 6373/8455 [07:41<03:01, 11.49it/s]

Preprocessing:  75%|███████▌  | 6375/8455 [07:41<03:09, 11.00it/s]

Preprocessing:  75%|███████▌  | 6377/8455 [07:41<03:10, 10.92it/s]

Preprocessing:  75%|███████▌  | 6379/8455 [07:41<03:15, 10.64it/s]

Preprocessing:  75%|███████▌  | 6381/8455 [07:41<03:20, 10.35it/s]

Preprocessing:  75%|███████▌  | 6383/8455 [07:42<03:09, 10.95it/s]

Preprocessing:  76%|███████▌  | 6385/8455 [07:42<03:00, 11.48it/s]

Preprocessing:  76%|███████▌  | 6387/8455 [07:42<02:52, 11.98it/s]

Preprocessing:  76%|███████▌  | 6389/8455 [07:42<03:01, 11.36it/s]

Preprocessing:  76%|███████▌  | 6391/8455 [07:42<02:38, 12.99it/s]

Preprocessing:  76%|███████▌  | 6393/8455 [07:42<02:25, 14.17it/s]

Preprocessing:  76%|███████▌  | 6395/8455 [07:42<02:17, 14.96it/s]

Preprocessing:  76%|███████▌  | 6397/8455 [07:43<02:14, 15.29it/s]

Preprocessing:  76%|███████▌  | 6399/8455 [07:43<02:08, 15.94it/s]

Preprocessing:  76%|███████▌  | 6401/8455 [07:43<02:06, 16.27it/s]

Preprocessing:  76%|███████▌  | 6403/8455 [07:43<02:14, 15.31it/s]

Preprocessing:  76%|███████▌  | 6406/8455 [07:43<02:04, 16.43it/s]

Preprocessing:  76%|███████▌  | 6409/8455 [07:43<01:54, 17.82it/s]

Preprocessing:  76%|███████▌  | 6411/8455 [07:43<01:54, 17.82it/s]

Preprocessing:  76%|███████▌  | 6413/8455 [07:43<01:56, 17.50it/s]

Preprocessing:  76%|███████▌  | 6415/8455 [07:44<02:06, 16.08it/s]

Preprocessing:  76%|███████▌  | 6417/8455 [07:44<02:01, 16.78it/s]

Preprocessing:  76%|███████▌  | 6419/8455 [07:44<01:57, 17.31it/s]

Preprocessing:  76%|███████▌  | 6421/8455 [07:44<02:01, 16.68it/s]

Preprocessing:  76%|███████▌  | 6423/8455 [07:44<02:08, 15.76it/s]

Preprocessing:  76%|███████▌  | 6425/8455 [07:44<02:18, 14.63it/s]

Preprocessing:  76%|███████▌  | 6427/8455 [07:44<02:17, 14.78it/s]

Preprocessing:  76%|███████▌  | 6429/8455 [07:44<02:15, 14.94it/s]

Preprocessing:  76%|███████▌  | 6431/8455 [07:45<02:29, 13.55it/s]

Preprocessing:  76%|███████▌  | 6433/8455 [07:45<02:26, 13.81it/s]

Preprocessing:  76%|███████▌  | 6435/8455 [07:45<02:25, 13.91it/s]

Preprocessing:  76%|███████▌  | 6437/8455 [07:45<02:21, 14.25it/s]

Preprocessing:  76%|███████▌  | 6439/8455 [07:45<02:30, 13.41it/s]

Preprocessing:  76%|███████▌  | 6441/8455 [07:45<02:46, 12.06it/s]

Preprocessing:  76%|███████▌  | 6443/8455 [07:46<02:57, 11.35it/s]

Preprocessing:  76%|███████▌  | 6445/8455 [07:46<03:03, 10.97it/s]

Preprocessing:  76%|███████▋  | 6447/8455 [07:46<03:10, 10.51it/s]

Preprocessing:  76%|███████▋  | 6449/8455 [07:46<03:04, 10.89it/s]

Preprocessing:  76%|███████▋  | 6451/8455 [07:46<03:06, 10.75it/s]

Preprocessing:  76%|███████▋  | 6453/8455 [07:47<03:16, 10.18it/s]

Preprocessing:  76%|███████▋  | 6455/8455 [07:47<03:24,  9.79it/s]

Preprocessing:  76%|███████▋  | 6457/8455 [07:47<03:15, 10.20it/s]

Preprocessing:  76%|███████▋  | 6459/8455 [07:47<03:10, 10.46it/s]

Preprocessing:  76%|███████▋  | 6461/8455 [07:47<03:15, 10.22it/s]

Preprocessing:  76%|███████▋  | 6463/8455 [07:48<03:12, 10.37it/s]

Preprocessing:  76%|███████▋  | 6465/8455 [07:48<03:05, 10.71it/s]

Preprocessing:  76%|███████▋  | 6467/8455 [07:48<02:58, 11.13it/s]

Preprocessing:  77%|███████▋  | 6469/8455 [07:48<02:51, 11.56it/s]

Preprocessing:  77%|███████▋  | 6471/8455 [07:48<02:37, 12.60it/s]

Preprocessing:  77%|███████▋  | 6473/8455 [07:48<02:41, 12.26it/s]

Preprocessing:  77%|███████▋  | 6475/8455 [07:49<02:45, 11.94it/s]

Preprocessing:  77%|███████▋  | 6477/8455 [07:49<02:46, 11.89it/s]

Preprocessing:  77%|███████▋  | 6479/8455 [07:49<02:59, 11.00it/s]

Preprocessing:  77%|███████▋  | 6481/8455 [07:49<03:05, 10.67it/s]

Preprocessing:  77%|███████▋  | 6483/8455 [07:49<02:57, 11.13it/s]

Preprocessing:  77%|███████▋  | 6485/8455 [07:49<02:43, 12.03it/s]

Preprocessing:  77%|███████▋  | 6487/8455 [07:50<02:45, 11.89it/s]

Preprocessing:  77%|███████▋  | 6489/8455 [07:50<02:55, 11.18it/s]

Preprocessing:  77%|███████▋  | 6491/8455 [07:50<03:10, 10.30it/s]

Preprocessing:  77%|███████▋  | 6493/8455 [07:50<03:04, 10.64it/s]

Preprocessing:  77%|███████▋  | 6495/8455 [07:50<03:09, 10.33it/s]

Preprocessing:  77%|███████▋  | 6497/8455 [07:51<03:04, 10.62it/s]

Preprocessing:  77%|███████▋  | 6499/8455 [07:51<03:01, 10.77it/s]

Preprocessing:  77%|███████▋  | 6501/8455 [07:51<03:01, 10.75it/s]

Preprocessing:  77%|███████▋  | 6503/8455 [07:51<02:57, 11.03it/s]

Preprocessing:  77%|███████▋  | 6505/8455 [07:51<02:48, 11.55it/s]

Preprocessing:  77%|███████▋  | 6507/8455 [07:51<02:48, 11.58it/s]

Preprocessing:  77%|███████▋  | 6509/8455 [07:52<03:12, 10.11it/s]

Preprocessing:  77%|███████▋  | 6511/8455 [07:52<03:26,  9.42it/s]

Preprocessing:  77%|███████▋  | 6513/8455 [07:52<03:11, 10.16it/s]

Preprocessing:  77%|███████▋  | 6515/8455 [07:52<03:18,  9.76it/s]

Preprocessing:  77%|███████▋  | 6517/8455 [07:53<03:11, 10.15it/s]

Preprocessing:  77%|███████▋  | 6519/8455 [07:53<03:08, 10.29it/s]

Preprocessing:  77%|███████▋  | 6521/8455 [07:53<03:12, 10.03it/s]

Preprocessing:  77%|███████▋  | 6523/8455 [07:53<03:08, 10.24it/s]

Preprocessing:  77%|███████▋  | 6525/8455 [07:53<03:10, 10.14it/s]

Preprocessing:  77%|███████▋  | 6527/8455 [07:54<03:13,  9.95it/s]

Preprocessing:  77%|███████▋  | 6529/8455 [07:54<03:13,  9.96it/s]

Preprocessing:  77%|███████▋  | 6531/8455 [07:54<03:32,  9.07it/s]

Preprocessing:  77%|███████▋  | 6533/8455 [07:54<03:16,  9.77it/s]

Preprocessing:  77%|███████▋  | 6535/8455 [07:54<03:31,  9.07it/s]

Preprocessing:  77%|███████▋  | 6536/8455 [07:55<03:34,  8.97it/s]

Preprocessing:  77%|███████▋  | 6537/8455 [07:55<03:52,  8.24it/s]

Preprocessing:  77%|███████▋  | 6538/8455 [07:55<03:46,  8.45it/s]

Preprocessing:  77%|███████▋  | 6539/8455 [07:55<03:51,  8.28it/s]

Preprocessing:  77%|███████▋  | 6540/8455 [07:55<03:56,  8.11it/s]

Preprocessing:  77%|███████▋  | 6542/8455 [07:55<03:34,  8.94it/s]

Preprocessing:  77%|███████▋  | 6543/8455 [07:55<03:30,  9.09it/s]

Preprocessing:  77%|███████▋  | 6545/8455 [07:56<03:18,  9.60it/s]

Preprocessing:  77%|███████▋  | 6547/8455 [07:56<03:14,  9.80it/s]

Preprocessing:  77%|███████▋  | 6549/8455 [07:56<03:09, 10.04it/s]

Preprocessing:  77%|███████▋  | 6551/8455 [07:56<03:06, 10.21it/s]

Preprocessing:  78%|███████▊  | 6553/8455 [07:56<03:04, 10.34it/s]

Preprocessing:  78%|███████▊  | 6555/8455 [07:57<03:08, 10.08it/s]

Preprocessing:  78%|███████▊  | 6557/8455 [07:57<03:20,  9.48it/s]

Preprocessing:  78%|███████▊  | 6558/8455 [07:57<03:23,  9.31it/s]

Preprocessing:  78%|███████▊  | 6559/8455 [07:57<03:23,  9.33it/s]

Preprocessing:  78%|███████▊  | 6561/8455 [07:57<03:18,  9.55it/s]

Preprocessing:  78%|███████▊  | 6562/8455 [07:57<03:34,  8.83it/s]

Preprocessing:  78%|███████▊  | 6563/8455 [07:57<03:29,  9.01it/s]

Preprocessing:  78%|███████▊  | 6565/8455 [07:58<03:14,  9.71it/s]

Preprocessing:  78%|███████▊  | 6567/8455 [07:58<03:04, 10.25it/s]

Preprocessing:  78%|███████▊  | 6569/8455 [07:58<02:58, 10.59it/s]

Preprocessing:  78%|███████▊  | 6571/8455 [07:58<02:56, 10.70it/s]

Preprocessing:  78%|███████▊  | 6573/8455 [07:58<02:52, 10.93it/s]

Preprocessing:  78%|███████▊  | 6575/8455 [07:59<02:44, 11.45it/s]

Preprocessing:  78%|███████▊  | 6577/8455 [07:59<02:37, 11.89it/s]

Preprocessing:  78%|███████▊  | 6579/8455 [07:59<02:39, 11.74it/s]

Preprocessing:  78%|███████▊  | 6581/8455 [07:59<02:43, 11.43it/s]

Preprocessing:  78%|███████▊  | 6583/8455 [07:59<02:51, 10.91it/s]

Preprocessing:  78%|███████▊  | 6585/8455 [07:59<02:50, 10.97it/s]

Preprocessing:  78%|███████▊  | 6587/8455 [08:00<02:48, 11.08it/s]

Preprocessing:  78%|███████▊  | 6589/8455 [08:00<02:57, 10.50it/s]

Preprocessing:  78%|███████▊  | 6591/8455 [08:00<03:08,  9.91it/s]

Preprocessing:  78%|███████▊  | 6593/8455 [08:00<03:12,  9.68it/s]

Preprocessing:  78%|███████▊  | 6595/8455 [08:00<02:55, 10.58it/s]

Preprocessing:  78%|███████▊  | 6597/8455 [08:01<03:09,  9.80it/s]

Preprocessing:  78%|███████▊  | 6599/8455 [08:01<03:13,  9.60it/s]

Preprocessing:  78%|███████▊  | 6601/8455 [08:01<03:21,  9.19it/s]

Preprocessing:  78%|███████▊  | 6603/8455 [08:01<03:05,  9.98it/s]

Preprocessing:  78%|███████▊  | 6605/8455 [08:01<02:57, 10.44it/s]

Preprocessing:  78%|███████▊  | 6607/8455 [08:02<02:51, 10.76it/s]

Preprocessing:  78%|███████▊  | 6609/8455 [08:02<03:05,  9.93it/s]

Preprocessing:  78%|███████▊  | 6611/8455 [08:02<02:52, 10.68it/s]

Preprocessing:  78%|███████▊  | 6613/8455 [08:02<02:53, 10.63it/s]

Preprocessing:  78%|███████▊  | 6615/8455 [08:02<02:56, 10.42it/s]

Preprocessing:  78%|███████▊  | 6617/8455 [08:03<02:51, 10.73it/s]

Preprocessing:  78%|███████▊  | 6619/8455 [08:03<02:57, 10.34it/s]

Preprocessing:  78%|███████▊  | 6621/8455 [08:03<02:57, 10.32it/s]

Preprocessing:  78%|███████▊  | 6623/8455 [08:03<03:08,  9.70it/s]

Preprocessing:  78%|███████▊  | 6624/8455 [08:03<03:12,  9.50it/s]

Preprocessing:  78%|███████▊  | 6625/8455 [08:03<03:12,  9.52it/s]

Preprocessing:  78%|███████▊  | 6626/8455 [08:04<03:14,  9.41it/s]

Preprocessing:  78%|███████▊  | 6627/8455 [08:04<03:17,  9.26it/s]

Preprocessing:  78%|███████▊  | 6628/8455 [08:04<03:18,  9.20it/s]

Preprocessing:  78%|███████▊  | 6629/8455 [08:04<03:22,  9.01it/s]

Preprocessing:  78%|███████▊  | 6631/8455 [08:04<03:05,  9.82it/s]

Preprocessing:  78%|███████▊  | 6633/8455 [08:04<02:54, 10.45it/s]

Preprocessing:  78%|███████▊  | 6635/8455 [08:04<03:07,  9.68it/s]

Preprocessing:  78%|███████▊  | 6637/8455 [08:05<02:55, 10.34it/s]

Preprocessing:  79%|███████▊  | 6639/8455 [08:05<02:51, 10.59it/s]

Preprocessing:  79%|███████▊  | 6641/8455 [08:05<02:48, 10.79it/s]

Preprocessing:  79%|███████▊  | 6643/8455 [08:05<02:42, 11.12it/s]

Preprocessing:  79%|███████▊  | 6645/8455 [08:05<02:39, 11.32it/s]

Preprocessing:  79%|███████▊  | 6647/8455 [08:05<02:35, 11.63it/s]

Preprocessing:  79%|███████▊  | 6649/8455 [08:06<02:38, 11.43it/s]

Preprocessing:  79%|███████▊  | 6651/8455 [08:06<02:42, 11.10it/s]

Preprocessing:  79%|███████▊  | 6653/8455 [08:06<02:48, 10.67it/s]

Preprocessing:  79%|███████▊  | 6655/8455 [08:06<02:55, 10.23it/s]

Preprocessing:  79%|███████▊  | 6657/8455 [08:06<02:51, 10.49it/s]

Preprocessing:  79%|███████▉  | 6659/8455 [08:07<02:46, 10.80it/s]

Preprocessing:  79%|███████▉  | 6661/8455 [08:07<02:50, 10.50it/s]

Preprocessing:  79%|███████▉  | 6663/8455 [08:07<02:51, 10.44it/s]

Preprocessing:  79%|███████▉  | 6665/8455 [08:07<02:45, 10.79it/s]

Preprocessing:  79%|███████▉  | 6667/8455 [08:07<02:38, 11.28it/s]

Preprocessing:  79%|███████▉  | 6669/8455 [08:08<02:44, 10.83it/s]

Preprocessing:  79%|███████▉  | 6671/8455 [08:08<02:55, 10.15it/s]

Preprocessing:  79%|███████▉  | 6673/8455 [08:08<02:50, 10.45it/s]

Preprocessing:  79%|███████▉  | 6675/8455 [08:08<02:53, 10.24it/s]

Preprocessing:  79%|███████▉  | 6677/8455 [08:08<03:10,  9.32it/s]

Preprocessing:  79%|███████▉  | 6679/8455 [08:09<03:04,  9.64it/s]

Preprocessing:  79%|███████▉  | 6681/8455 [08:09<03:06,  9.53it/s]

Preprocessing:  79%|███████▉  | 6683/8455 [08:09<02:57,  9.97it/s]

Preprocessing:  79%|███████▉  | 6685/8455 [08:09<03:08,  9.40it/s]

Preprocessing:  79%|███████▉  | 6686/8455 [08:09<03:18,  8.92it/s]

Preprocessing:  79%|███████▉  | 6688/8455 [08:10<03:02,  9.66it/s]

Preprocessing:  79%|███████▉  | 6690/8455 [08:10<02:53, 10.15it/s]

Preprocessing:  79%|███████▉  | 6692/8455 [08:10<03:05,  9.50it/s]

Preprocessing:  79%|███████▉  | 6694/8455 [08:10<02:54, 10.11it/s]

Preprocessing:  79%|███████▉  | 6696/8455 [08:10<02:50, 10.34it/s]

Preprocessing:  79%|███████▉  | 6698/8455 [08:10<02:46, 10.55it/s]

Preprocessing:  79%|███████▉  | 6700/8455 [08:11<02:43, 10.75it/s]

Preprocessing:  79%|███████▉  | 6702/8455 [08:11<02:54, 10.06it/s]

Preprocessing:  79%|███████▉  | 6704/8455 [08:11<02:52, 10.17it/s]

Preprocessing:  79%|███████▉  | 6706/8455 [08:11<02:43, 10.67it/s]

Preprocessing:  79%|███████▉  | 6708/8455 [08:11<02:36, 11.19it/s]

Preprocessing:  79%|███████▉  | 6710/8455 [08:12<02:41, 10.79it/s]

Preprocessing:  79%|███████▉  | 6712/8455 [08:12<02:54, 10.01it/s]

Preprocessing:  79%|███████▉  | 6714/8455 [08:12<02:49, 10.26it/s]

Preprocessing:  79%|███████▉  | 6716/8455 [08:12<02:59,  9.70it/s]

Preprocessing:  79%|███████▉  | 6718/8455 [08:12<02:59,  9.67it/s]

Preprocessing:  79%|███████▉  | 6719/8455 [08:13<03:03,  9.46it/s]

Preprocessing:  79%|███████▉  | 6721/8455 [08:13<02:56,  9.83it/s]

Preprocessing:  80%|███████▉  | 6722/8455 [08:13<02:56,  9.85it/s]

Preprocessing:  80%|███████▉  | 6724/8455 [08:13<02:46, 10.42it/s]

Preprocessing:  80%|███████▉  | 6726/8455 [08:13<03:00,  9.58it/s]

Preprocessing:  80%|███████▉  | 6727/8455 [08:13<03:03,  9.41it/s]

Preprocessing:  80%|███████▉  | 6728/8455 [08:14<03:08,  9.15it/s]

Preprocessing:  80%|███████▉  | 6729/8455 [08:14<03:09,  9.09it/s]

Preprocessing:  80%|███████▉  | 6731/8455 [08:14<02:52, 10.01it/s]

Preprocessing:  80%|███████▉  | 6732/8455 [08:14<02:59,  9.62it/s]

Preprocessing:  80%|███████▉  | 6733/8455 [08:14<03:05,  9.29it/s]

Preprocessing:  80%|███████▉  | 6734/8455 [08:14<03:09,  9.08it/s]

Preprocessing:  80%|███████▉  | 6735/8455 [08:14<03:10,  9.02it/s]

Preprocessing:  80%|███████▉  | 6736/8455 [08:14<03:10,  9.04it/s]

Preprocessing:  80%|███████▉  | 6737/8455 [08:15<03:12,  8.92it/s]

Preprocessing:  80%|███████▉  | 6738/8455 [08:15<03:11,  8.96it/s]

Preprocessing:  80%|███████▉  | 6739/8455 [08:15<03:11,  8.94it/s]

Preprocessing:  80%|███████▉  | 6740/8455 [08:15<03:17,  8.68it/s]

Preprocessing:  80%|███████▉  | 6741/8455 [08:15<03:13,  8.87it/s]

Preprocessing:  80%|███████▉  | 6742/8455 [08:15<03:23,  8.43it/s]

Preprocessing:  80%|███████▉  | 6744/8455 [08:15<02:52,  9.90it/s]

Preprocessing:  80%|███████▉  | 6745/8455 [08:15<03:02,  9.39it/s]

Preprocessing:  80%|███████▉  | 6747/8455 [08:16<02:56,  9.69it/s]

Preprocessing:  80%|███████▉  | 6749/8455 [08:16<02:52,  9.91it/s]

Preprocessing:  80%|███████▉  | 6750/8455 [08:16<02:58,  9.54it/s]

Preprocessing:  80%|███████▉  | 6751/8455 [08:16<03:04,  9.25it/s]

Preprocessing:  80%|███████▉  | 6752/8455 [08:16<03:10,  8.95it/s]

Preprocessing:  80%|███████▉  | 6754/8455 [08:16<03:02,  9.31it/s]

Preprocessing:  80%|███████▉  | 6755/8455 [08:16<03:26,  8.23it/s]

Preprocessing:  80%|███████▉  | 6756/8455 [08:17<03:25,  8.28it/s]

Preprocessing:  80%|███████▉  | 6758/8455 [08:17<03:07,  9.06it/s]

Preprocessing:  80%|███████▉  | 6759/8455 [08:17<03:10,  8.91it/s]

Preprocessing:  80%|███████▉  | 6760/8455 [08:17<03:11,  8.83it/s]

Preprocessing:  80%|███████▉  | 6762/8455 [08:17<03:07,  9.05it/s]

Preprocessing:  80%|███████▉  | 6763/8455 [08:17<03:14,  8.68it/s]

Preprocessing:  80%|████████  | 6765/8455 [08:18<03:01,  9.30it/s]

Preprocessing:  80%|████████  | 6766/8455 [08:18<03:00,  9.34it/s]

Preprocessing:  80%|████████  | 6767/8455 [08:18<03:03,  9.21it/s]

Preprocessing:  80%|████████  | 6769/8455 [08:18<02:54,  9.68it/s]

Preprocessing:  80%|████████  | 6770/8455 [08:18<02:59,  9.39it/s]

Preprocessing:  80%|████████  | 6771/8455 [08:18<03:02,  9.23it/s]

Preprocessing:  80%|████████  | 6772/8455 [08:18<03:05,  9.07it/s]

Preprocessing:  80%|████████  | 6774/8455 [08:19<03:03,  9.14it/s]

Preprocessing:  80%|████████  | 6775/8455 [08:19<03:00,  9.31it/s]

Preprocessing:  80%|████████  | 6777/8455 [08:19<02:42, 10.34it/s]

Preprocessing:  80%|████████  | 6779/8455 [08:19<02:41, 10.38it/s]

Preprocessing:  80%|████████  | 6781/8455 [08:19<02:34, 10.83it/s]

Preprocessing:  80%|████████  | 6783/8455 [08:19<02:44, 10.18it/s]

Preprocessing:  80%|████████  | 6785/8455 [08:20<02:42, 10.28it/s]

Preprocessing:  80%|████████  | 6787/8455 [08:20<02:51,  9.73it/s]

Preprocessing:  80%|████████  | 6788/8455 [08:20<02:53,  9.63it/s]

Preprocessing:  80%|████████  | 6789/8455 [08:20<03:00,  9.23it/s]

Preprocessing:  80%|████████  | 6790/8455 [08:20<03:04,  9.02it/s]

Preprocessing:  80%|████████  | 6791/8455 [08:20<03:08,  8.85it/s]

Preprocessing:  80%|████████  | 6792/8455 [08:20<03:09,  8.79it/s]

Preprocessing:  80%|████████  | 6793/8455 [08:21<03:07,  8.85it/s]

Preprocessing:  80%|████████  | 6794/8455 [08:21<03:03,  9.06it/s]

Preprocessing:  80%|████████  | 6795/8455 [08:21<03:04,  8.99it/s]

Preprocessing:  80%|████████  | 6796/8455 [08:21<03:02,  9.10it/s]

Preprocessing:  80%|████████  | 6797/8455 [08:21<03:04,  8.99it/s]

Preprocessing:  80%|████████  | 6798/8455 [08:21<03:07,  8.82it/s]

Preprocessing:  80%|████████  | 6799/8455 [08:21<03:10,  8.70it/s]

Preprocessing:  80%|████████  | 6800/8455 [08:21<03:11,  8.64it/s]

Preprocessing:  80%|████████  | 6801/8455 [08:21<03:09,  8.72it/s]

Preprocessing:  80%|████████  | 6803/8455 [08:22<02:47,  9.85it/s]

Preprocessing:  80%|████████  | 6804/8455 [08:22<02:53,  9.50it/s]

Preprocessing:  80%|████████  | 6805/8455 [08:22<02:58,  9.22it/s]

Preprocessing:  81%|████████  | 6807/8455 [08:22<02:41, 10.19it/s]

Preprocessing:  81%|████████  | 6808/8455 [08:22<02:47,  9.85it/s]

Preprocessing:  81%|████████  | 6810/8455 [08:22<02:44,  9.98it/s]

Preprocessing:  81%|████████  | 6811/8455 [08:22<02:52,  9.53it/s]

Preprocessing:  81%|████████  | 6813/8455 [08:23<02:36, 10.47it/s]

Preprocessing:  81%|████████  | 6815/8455 [08:23<02:48,  9.75it/s]

Preprocessing:  81%|████████  | 6816/8455 [08:23<02:53,  9.47it/s]

Preprocessing:  81%|████████  | 6817/8455 [08:23<02:59,  9.12it/s]

Preprocessing:  81%|████████  | 6818/8455 [08:23<03:00,  9.08it/s]

Preprocessing:  81%|████████  | 6820/8455 [08:23<02:40, 10.20it/s]

Preprocessing:  81%|████████  | 6822/8455 [08:24<02:42, 10.05it/s]

Preprocessing:  81%|████████  | 6824/8455 [08:24<02:33, 10.60it/s]

Preprocessing:  81%|████████  | 6826/8455 [08:24<02:45,  9.82it/s]

Preprocessing:  81%|████████  | 6827/8455 [08:24<02:52,  9.45it/s]

Preprocessing:  81%|████████  | 6828/8455 [08:24<02:56,  9.24it/s]

Preprocessing:  81%|████████  | 6829/8455 [08:24<02:54,  9.33it/s]

Preprocessing:  81%|████████  | 6830/8455 [08:24<02:57,  9.18it/s]

Preprocessing:  81%|████████  | 6831/8455 [08:24<02:53,  9.35it/s]

Preprocessing:  81%|████████  | 6833/8455 [08:25<02:40, 10.12it/s]

Preprocessing:  81%|████████  | 6835/8455 [08:25<02:39, 10.17it/s]

Preprocessing:  81%|████████  | 6837/8455 [08:25<02:49,  9.56it/s]

Preprocessing:  81%|████████  | 6838/8455 [08:25<02:52,  9.35it/s]

Preprocessing:  81%|████████  | 6839/8455 [08:25<02:56,  9.17it/s]

Preprocessing:  81%|████████  | 6840/8455 [08:25<02:59,  9.02it/s]

Preprocessing:  81%|████████  | 6842/8455 [08:26<02:37, 10.23it/s]

Preprocessing:  81%|████████  | 6844/8455 [08:26<03:00,  8.93it/s]

Preprocessing:  81%|████████  | 6845/8455 [08:26<03:08,  8.55it/s]

Preprocessing:  81%|████████  | 6846/8455 [08:26<03:11,  8.40it/s]

Preprocessing:  81%|████████  | 6847/8455 [08:26<03:11,  8.38it/s]

Preprocessing:  81%|████████  | 6848/8455 [08:26<03:10,  8.45it/s]

Preprocessing:  81%|████████  | 6849/8455 [08:26<03:06,  8.60it/s]

Preprocessing:  81%|████████  | 6851/8455 [08:27<02:58,  9.00it/s]

Preprocessing:  81%|████████  | 6852/8455 [08:27<02:59,  8.92it/s]

Preprocessing:  81%|████████  | 6853/8455 [08:27<03:04,  8.67it/s]

Preprocessing:  81%|████████  | 6854/8455 [08:27<03:07,  8.55it/s]

Preprocessing:  81%|████████  | 6855/8455 [08:27<03:08,  8.49it/s]

Preprocessing:  81%|████████  | 6856/8455 [08:27<03:07,  8.52it/s]

Preprocessing:  81%|████████  | 6858/8455 [08:27<02:57,  9.00it/s]

Preprocessing:  81%|████████  | 6860/8455 [08:28<02:45,  9.66it/s]

Preprocessing:  81%|████████  | 6862/8455 [08:28<02:36, 10.19it/s]

Preprocessing:  81%|████████  | 6864/8455 [08:28<02:40,  9.92it/s]

Preprocessing:  81%|████████  | 6866/8455 [08:28<02:40,  9.93it/s]

Preprocessing:  81%|████████  | 6868/8455 [08:28<02:31, 10.49it/s]

Preprocessing:  81%|████████▏ | 6870/8455 [08:29<02:30, 10.55it/s]

Preprocessing:  81%|████████▏ | 6872/8455 [08:29<02:26, 10.82it/s]

Preprocessing:  81%|████████▏ | 6874/8455 [08:29<02:31, 10.44it/s]

Preprocessing:  81%|████████▏ | 6876/8455 [08:29<02:28, 10.65it/s]

Preprocessing:  81%|████████▏ | 6878/8455 [08:29<02:39,  9.88it/s]

Preprocessing:  81%|████████▏ | 6880/8455 [08:30<02:36, 10.08it/s]

Preprocessing:  81%|████████▏ | 6882/8455 [08:30<02:34, 10.20it/s]

Preprocessing:  81%|████████▏ | 6884/8455 [08:30<02:35, 10.13it/s]

Preprocessing:  81%|████████▏ | 6886/8455 [08:30<02:49,  9.28it/s]

Preprocessing:  81%|████████▏ | 6887/8455 [08:30<02:53,  9.06it/s]

Preprocessing:  81%|████████▏ | 6889/8455 [08:31<02:42,  9.66it/s]

Preprocessing:  81%|████████▏ | 6890/8455 [08:31<02:45,  9.47it/s]

Preprocessing:  82%|████████▏ | 6891/8455 [08:31<02:49,  9.21it/s]

Preprocessing:  82%|████████▏ | 6893/8455 [08:31<02:46,  9.37it/s]

Preprocessing:  82%|████████▏ | 6894/8455 [08:31<02:48,  9.27it/s]

Preprocessing:  82%|████████▏ | 6895/8455 [08:31<02:51,  9.11it/s]

Preprocessing:  82%|████████▏ | 6896/8455 [08:31<02:53,  8.99it/s]

Preprocessing:  82%|████████▏ | 6898/8455 [08:32<02:35, 10.00it/s]

Preprocessing:  82%|████████▏ | 6899/8455 [08:32<02:43,  9.54it/s]

Preprocessing:  82%|████████▏ | 6901/8455 [08:32<02:40,  9.70it/s]

Preprocessing:  82%|████████▏ | 6902/8455 [08:32<02:45,  9.36it/s]

Preprocessing:  82%|████████▏ | 6903/8455 [08:32<02:50,  9.08it/s]

Preprocessing:  82%|████████▏ | 6905/8455 [08:32<02:39,  9.69it/s]

Preprocessing:  82%|████████▏ | 6906/8455 [08:32<02:44,  9.41it/s]

Preprocessing:  82%|████████▏ | 6907/8455 [08:32<02:48,  9.19it/s]

Preprocessing:  82%|████████▏ | 6908/8455 [08:33<02:49,  9.12it/s]

Preprocessing:  82%|████████▏ | 6909/8455 [08:33<02:53,  8.89it/s]

Preprocessing:  82%|████████▏ | 6910/8455 [08:33<02:56,  8.76it/s]

Preprocessing:  82%|████████▏ | 6912/8455 [08:33<02:44,  9.35it/s]

Preprocessing:  82%|████████▏ | 6914/8455 [08:33<02:44,  9.39it/s]

Preprocessing:  82%|████████▏ | 6915/8455 [08:33<02:48,  9.16it/s]

Preprocessing:  82%|████████▏ | 6916/8455 [08:33<02:46,  9.24it/s]

Preprocessing:  82%|████████▏ | 6918/8455 [08:34<02:39,  9.62it/s]

Preprocessing:  82%|████████▏ | 6919/8455 [08:34<02:40,  9.55it/s]

Preprocessing:  82%|████████▏ | 6920/8455 [08:34<02:46,  9.24it/s]

Preprocessing:  82%|████████▏ | 6922/8455 [08:34<02:42,  9.42it/s]

Preprocessing:  82%|████████▏ | 6924/8455 [08:34<02:33,  9.94it/s]

Preprocessing:  82%|████████▏ | 6926/8455 [08:34<02:34,  9.87it/s]

Preprocessing:  82%|████████▏ | 6927/8455 [08:35<02:37,  9.70it/s]

Preprocessing:  82%|████████▏ | 6928/8455 [08:35<02:39,  9.56it/s]

Preprocessing:  82%|████████▏ | 6929/8455 [08:35<02:43,  9.36it/s]

Preprocessing:  82%|████████▏ | 6930/8455 [08:35<02:48,  9.04it/s]

Preprocessing:  82%|████████▏ | 6932/8455 [08:35<02:41,  9.43it/s]

Preprocessing:  82%|████████▏ | 6933/8455 [08:35<02:47,  9.10it/s]

Preprocessing:  82%|████████▏ | 6935/8455 [08:35<02:39,  9.53it/s]

Preprocessing:  82%|████████▏ | 6937/8455 [08:36<02:35,  9.76it/s]

Preprocessing:  82%|████████▏ | 6938/8455 [08:36<02:38,  9.56it/s]

Preprocessing:  82%|████████▏ | 6940/8455 [08:36<02:34,  9.83it/s]

Preprocessing:  82%|████████▏ | 6942/8455 [08:36<02:22, 10.60it/s]

Preprocessing:  82%|████████▏ | 6944/8455 [08:36<02:24, 10.46it/s]

Preprocessing:  82%|████████▏ | 6946/8455 [08:37<02:30, 10.00it/s]

Preprocessing:  82%|████████▏ | 6948/8455 [08:37<02:31,  9.92it/s]

Preprocessing:  82%|████████▏ | 6949/8455 [08:37<02:35,  9.69it/s]

Preprocessing:  82%|████████▏ | 6950/8455 [08:37<02:40,  9.37it/s]

Preprocessing:  82%|████████▏ | 6952/8455 [08:37<02:38,  9.48it/s]

Preprocessing:  82%|████████▏ | 6954/8455 [08:37<02:25, 10.29it/s]

Preprocessing:  82%|████████▏ | 6956/8455 [08:38<02:24, 10.37it/s]

Preprocessing:  82%|████████▏ | 6958/8455 [08:38<02:24, 10.36it/s]

Preprocessing:  82%|████████▏ | 6960/8455 [08:38<02:27, 10.14it/s]

Preprocessing:  82%|████████▏ | 6962/8455 [08:38<02:37,  9.48it/s]

Preprocessing:  82%|████████▏ | 6964/8455 [08:38<02:38,  9.38it/s]

Preprocessing:  82%|████████▏ | 6966/8455 [08:39<02:31,  9.84it/s]

Preprocessing:  82%|████████▏ | 6968/8455 [08:39<02:27, 10.08it/s]

Preprocessing:  82%|████████▏ | 6970/8455 [08:39<02:24, 10.26it/s]

Preprocessing:  82%|████████▏ | 6972/8455 [08:39<02:32,  9.73it/s]

Preprocessing:  82%|████████▏ | 6974/8455 [08:39<02:25, 10.20it/s]

Preprocessing:  83%|████████▎ | 6976/8455 [08:40<02:28,  9.96it/s]

Preprocessing:  83%|████████▎ | 6978/8455 [08:40<02:36,  9.46it/s]

Preprocessing:  83%|████████▎ | 6979/8455 [08:40<02:40,  9.18it/s]

Preprocessing:  83%|████████▎ | 6981/8455 [08:40<02:37,  9.37it/s]

Preprocessing:  83%|████████▎ | 6982/8455 [08:40<02:41,  9.10it/s]

Preprocessing:  83%|████████▎ | 6984/8455 [08:40<02:35,  9.46it/s]

Preprocessing:  83%|████████▎ | 6986/8455 [08:41<02:22, 10.34it/s]

Preprocessing:  83%|████████▎ | 6988/8455 [08:41<02:22, 10.29it/s]

Preprocessing:  83%|████████▎ | 6990/8455 [08:41<02:30,  9.75it/s]

Preprocessing:  83%|████████▎ | 6991/8455 [08:41<02:34,  9.49it/s]

Preprocessing:  83%|████████▎ | 6992/8455 [08:41<02:37,  9.29it/s]

Preprocessing:  83%|████████▎ | 6993/8455 [08:41<02:43,  8.96it/s]

Preprocessing:  83%|████████▎ | 6995/8455 [08:42<02:34,  9.45it/s]

Preprocessing:  83%|████████▎ | 6996/8455 [08:42<02:37,  9.25it/s]

Preprocessing:  83%|████████▎ | 6997/8455 [08:42<02:40,  9.09it/s]

Preprocessing:  83%|████████▎ | 6998/8455 [08:42<02:45,  8.81it/s]

Preprocessing:  83%|████████▎ | 6999/8455 [08:42<02:51,  8.48it/s]

Preprocessing:  83%|████████▎ | 7000/8455 [08:42<02:50,  8.55it/s]

Preprocessing:  83%|████████▎ | 7001/8455 [08:42<02:51,  8.49it/s]

Preprocessing:  83%|████████▎ | 7002/8455 [08:42<02:48,  8.61it/s]

Preprocessing:  83%|████████▎ | 7004/8455 [08:43<02:34,  9.37it/s]

Preprocessing:  83%|████████▎ | 7006/8455 [08:43<02:19, 10.41it/s]

Preprocessing:  83%|████████▎ | 7008/8455 [08:43<02:13, 10.81it/s]

Preprocessing:  83%|████████▎ | 7010/8455 [08:43<02:19, 10.33it/s]

Preprocessing:  83%|████████▎ | 7012/8455 [08:43<02:22, 10.13it/s]

Preprocessing:  83%|████████▎ | 7014/8455 [08:44<02:29,  9.63it/s]

Preprocessing:  83%|████████▎ | 7015/8455 [08:44<02:42,  8.87it/s]

Preprocessing:  83%|████████▎ | 7016/8455 [08:44<02:38,  9.06it/s]

Preprocessing:  83%|████████▎ | 7018/8455 [08:44<02:36,  9.19it/s]

Preprocessing:  83%|████████▎ | 7019/8455 [08:44<02:36,  9.16it/s]

Preprocessing:  83%|████████▎ | 7020/8455 [08:44<02:35,  9.25it/s]

Preprocessing:  83%|████████▎ | 7021/8455 [08:44<02:35,  9.20it/s]

Preprocessing:  83%|████████▎ | 7022/8455 [08:44<02:37,  9.12it/s]

Preprocessing:  83%|████████▎ | 7023/8455 [08:45<02:36,  9.17it/s]

Preprocessing:  83%|████████▎ | 7024/8455 [08:45<02:41,  8.89it/s]

Preprocessing:  83%|████████▎ | 7026/8455 [08:45<02:30,  9.50it/s]

Preprocessing:  83%|████████▎ | 7027/8455 [08:45<02:36,  9.14it/s]

Preprocessing:  83%|████████▎ | 7028/8455 [08:45<02:48,  8.48it/s]

Preprocessing:  83%|████████▎ | 7030/8455 [08:45<02:33,  9.26it/s]

Preprocessing:  83%|████████▎ | 7032/8455 [08:46<02:26,  9.73it/s]

Preprocessing:  83%|████████▎ | 7034/8455 [08:46<02:26,  9.67it/s]

Preprocessing:  83%|████████▎ | 7036/8455 [08:46<02:18, 10.21it/s]

Preprocessing:  83%|████████▎ | 7038/8455 [08:46<02:27,  9.62it/s]

Preprocessing:  83%|████████▎ | 7040/8455 [08:46<02:26,  9.68it/s]

Preprocessing:  83%|████████▎ | 7041/8455 [08:47<02:31,  9.36it/s]

Preprocessing:  83%|████████▎ | 7042/8455 [08:47<02:30,  9.39it/s]

Preprocessing:  83%|████████▎ | 7043/8455 [08:47<02:34,  9.13it/s]

Preprocessing:  83%|████████▎ | 7044/8455 [08:47<02:37,  8.95it/s]

Preprocessing:  83%|████████▎ | 7045/8455 [08:47<02:39,  8.82it/s]

Preprocessing:  83%|████████▎ | 7047/8455 [08:47<02:30,  9.38it/s]

Preprocessing:  83%|████████▎ | 7048/8455 [08:47<02:36,  8.99it/s]

Preprocessing:  83%|████████▎ | 7049/8455 [08:47<02:38,  8.87it/s]

Preprocessing:  83%|████████▎ | 7051/8455 [08:48<02:24,  9.73it/s]

Preprocessing:  83%|████████▎ | 7052/8455 [08:48<02:23,  9.77it/s]

Preprocessing:  83%|████████▎ | 7054/8455 [08:48<02:26,  9.59it/s]

Preprocessing:  83%|████████▎ | 7056/8455 [08:48<02:21,  9.86it/s]

Preprocessing:  83%|████████▎ | 7057/8455 [08:48<02:26,  9.54it/s]

Preprocessing:  83%|████████▎ | 7058/8455 [08:48<02:29,  9.32it/s]

Preprocessing:  83%|████████▎ | 7059/8455 [08:48<02:34,  9.03it/s]

Preprocessing:  84%|████████▎ | 7060/8455 [08:49<02:35,  8.96it/s]

Preprocessing:  84%|████████▎ | 7062/8455 [08:49<02:20,  9.89it/s]

Preprocessing:  84%|████████▎ | 7064/8455 [08:49<02:18, 10.07it/s]

Preprocessing:  84%|████████▎ | 7065/8455 [08:49<02:24,  9.61it/s]

Preprocessing:  84%|████████▎ | 7066/8455 [08:49<02:25,  9.53it/s]

Preprocessing:  84%|████████▎ | 7068/8455 [08:49<02:15, 10.24it/s]

Preprocessing:  84%|████████▎ | 7069/8455 [08:49<02:21,  9.78it/s]

Preprocessing:  84%|████████▎ | 7070/8455 [08:50<02:26,  9.45it/s]

Preprocessing:  84%|████████▎ | 7071/8455 [08:50<02:32,  9.10it/s]

Preprocessing:  84%|████████▎ | 7072/8455 [08:50<02:30,  9.22it/s]

Preprocessing:  84%|████████▎ | 7073/8455 [08:50<02:32,  9.06it/s]

Preprocessing:  84%|████████▎ | 7074/8455 [08:50<02:35,  8.90it/s]

Preprocessing:  84%|████████▎ | 7075/8455 [08:50<02:35,  8.87it/s]

Preprocessing:  84%|████████▎ | 7076/8455 [08:50<02:41,  8.51it/s]

Preprocessing:  84%|████████▎ | 7077/8455 [08:50<02:39,  8.63it/s]

Preprocessing:  84%|████████▎ | 7078/8455 [08:50<02:40,  8.58it/s]

Preprocessing:  84%|████████▎ | 7079/8455 [08:51<02:41,  8.54it/s]

Preprocessing:  84%|████████▎ | 7081/8455 [08:51<02:17,  9.96it/s]

Preprocessing:  84%|████████▍ | 7082/8455 [08:51<02:24,  9.52it/s]

Preprocessing:  84%|████████▍ | 7083/8455 [08:51<02:31,  9.05it/s]

Preprocessing:  84%|████████▍ | 7085/8455 [08:51<02:37,  8.72it/s]

Preprocessing:  84%|████████▍ | 7087/8455 [08:51<02:29,  9.14it/s]

Preprocessing:  84%|████████▍ | 7088/8455 [08:52<02:32,  8.97it/s]

Preprocessing:  84%|████████▍ | 7089/8455 [08:52<02:34,  8.83it/s]

Preprocessing:  84%|████████▍ | 7090/8455 [08:52<02:36,  8.70it/s]

Preprocessing:  84%|████████▍ | 7091/8455 [08:52<02:37,  8.68it/s]

Preprocessing:  84%|████████▍ | 7092/8455 [08:52<02:36,  8.72it/s]

Preprocessing:  84%|████████▍ | 7093/8455 [08:52<02:53,  7.87it/s]

Preprocessing:  84%|████████▍ | 7095/8455 [08:52<02:36,  8.69it/s]

Preprocessing:  84%|████████▍ | 7096/8455 [08:53<02:37,  8.64it/s]

Preprocessing:  84%|████████▍ | 7097/8455 [08:53<02:37,  8.63it/s]

Preprocessing:  84%|████████▍ | 7098/8455 [08:53<02:35,  8.71it/s]

Preprocessing:  84%|████████▍ | 7099/8455 [08:53<02:38,  8.57it/s]

Preprocessing:  84%|████████▍ | 7101/8455 [08:53<02:26,  9.23it/s]

Preprocessing:  84%|████████▍ | 7103/8455 [08:53<02:23,  9.39it/s]

Preprocessing:  84%|████████▍ | 7104/8455 [08:53<02:29,  9.02it/s]

Preprocessing:  84%|████████▍ | 7105/8455 [08:54<02:28,  9.07it/s]

Preprocessing:  84%|████████▍ | 7106/8455 [08:54<02:30,  8.98it/s]

Preprocessing:  84%|████████▍ | 7108/8455 [08:54<02:25,  9.25it/s]

Preprocessing:  84%|████████▍ | 7110/8455 [08:54<02:24,  9.30it/s]

Preprocessing:  84%|████████▍ | 7111/8455 [08:54<02:34,  8.73it/s]

Preprocessing:  84%|████████▍ | 7112/8455 [08:54<02:31,  8.84it/s]

Preprocessing:  84%|████████▍ | 7113/8455 [08:54<02:31,  8.85it/s]

Preprocessing:  84%|████████▍ | 7114/8455 [08:55<02:34,  8.69it/s]

Preprocessing:  84%|████████▍ | 7116/8455 [08:55<02:23,  9.34it/s]

Preprocessing:  84%|████████▍ | 7117/8455 [08:55<02:29,  8.96it/s]

Preprocessing:  84%|████████▍ | 7118/8455 [08:55<02:31,  8.80it/s]

Preprocessing:  84%|████████▍ | 7119/8455 [08:55<02:34,  8.65it/s]

Preprocessing:  84%|████████▍ | 7120/8455 [08:55<02:34,  8.62it/s]

Preprocessing:  84%|████████▍ | 7121/8455 [08:55<02:35,  8.55it/s]

Preprocessing:  84%|████████▍ | 7122/8455 [08:55<02:36,  8.51it/s]

Preprocessing:  84%|████████▍ | 7123/8455 [08:56<02:36,  8.49it/s]

Preprocessing:  84%|████████▍ | 7125/8455 [08:56<02:17,  9.71it/s]

Preprocessing:  84%|████████▍ | 7126/8455 [08:56<02:22,  9.36it/s]

Preprocessing:  84%|████████▍ | 7127/8455 [08:56<02:24,  9.21it/s]

Preprocessing:  84%|████████▍ | 7128/8455 [08:56<02:28,  8.93it/s]

Preprocessing:  84%|████████▍ | 7129/8455 [08:56<02:32,  8.68it/s]

Preprocessing:  84%|████████▍ | 7130/8455 [08:56<02:28,  8.90it/s]

Preprocessing:  84%|████████▍ | 7131/8455 [08:56<02:32,  8.70it/s]

Preprocessing:  84%|████████▍ | 7132/8455 [08:57<02:35,  8.53it/s]

Preprocessing:  84%|████████▍ | 7134/8455 [08:57<02:19,  9.49it/s]

Preprocessing:  84%|████████▍ | 7136/8455 [08:57<02:14,  9.77it/s]

Preprocessing:  84%|████████▍ | 7137/8455 [08:57<02:18,  9.55it/s]

Preprocessing:  84%|████████▍ | 7138/8455 [08:57<02:21,  9.29it/s]

Preprocessing:  84%|████████▍ | 7139/8455 [08:57<02:25,  9.02it/s]

Preprocessing:  84%|████████▍ | 7140/8455 [08:57<02:29,  8.77it/s]

Preprocessing:  84%|████████▍ | 7141/8455 [08:58<02:30,  8.73it/s]

Preprocessing:  84%|████████▍ | 7142/8455 [08:58<02:34,  8.51it/s]

Preprocessing:  84%|████████▍ | 7144/8455 [08:58<02:26,  8.96it/s]

Preprocessing:  85%|████████▍ | 7146/8455 [08:58<02:25,  8.99it/s]

Preprocessing:  85%|████████▍ | 7147/8455 [08:58<02:28,  8.82it/s]

Preprocessing:  85%|████████▍ | 7148/8455 [08:58<02:30,  8.68it/s]

Preprocessing:  85%|████████▍ | 7149/8455 [08:58<02:31,  8.62it/s]

Preprocessing:  85%|████████▍ | 7150/8455 [08:59<02:34,  8.43it/s]

Preprocessing:  85%|████████▍ | 7151/8455 [08:59<02:34,  8.45it/s]

Preprocessing:  85%|████████▍ | 7152/8455 [08:59<02:35,  8.40it/s]

Preprocessing:  85%|████████▍ | 7153/8455 [08:59<02:37,  8.26it/s]

Preprocessing:  85%|████████▍ | 7154/8455 [08:59<02:38,  8.20it/s]

Preprocessing:  85%|████████▍ | 7155/8455 [08:59<02:41,  8.06it/s]

Preprocessing:  85%|████████▍ | 7156/8455 [08:59<02:39,  8.13it/s]

Preprocessing:  85%|████████▍ | 7157/8455 [08:59<02:40,  8.09it/s]

Preprocessing:  85%|████████▍ | 7159/8455 [09:00<02:20,  9.22it/s]

Preprocessing:  85%|████████▍ | 7161/8455 [09:00<02:16,  9.48it/s]

Preprocessing:  85%|████████▍ | 7163/8455 [09:00<02:13,  9.67it/s]

Preprocessing:  85%|████████▍ | 7164/8455 [09:00<02:19,  9.26it/s]

Preprocessing:  85%|████████▍ | 7166/8455 [09:00<02:16,  9.47it/s]

Preprocessing:  85%|████████▍ | 7167/8455 [09:00<02:21,  9.10it/s]

Preprocessing:  85%|████████▍ | 7168/8455 [09:01<02:25,  8.85it/s]

Preprocessing:  85%|████████▍ | 7169/8455 [09:01<02:27,  8.71it/s]

Preprocessing:  85%|████████▍ | 7170/8455 [09:01<02:29,  8.57it/s]

Preprocessing:  85%|████████▍ | 7172/8455 [09:01<02:17,  9.36it/s]

Preprocessing:  85%|████████▍ | 7173/8455 [09:01<02:19,  9.16it/s]

Preprocessing:  85%|████████▍ | 7174/8455 [09:01<02:23,  8.95it/s]

Preprocessing:  85%|████████▍ | 7175/8455 [09:01<02:42,  7.87it/s]

Preprocessing:  85%|████████▍ | 7176/8455 [09:02<02:33,  8.32it/s]

Preprocessing:  85%|████████▍ | 7177/8455 [09:02<02:28,  8.63it/s]

Preprocessing:  85%|████████▍ | 7178/8455 [09:02<02:29,  8.56it/s]

Preprocessing:  85%|████████▍ | 7179/8455 [09:02<02:27,  8.62it/s]

Preprocessing:  85%|████████▍ | 7180/8455 [09:02<02:31,  8.44it/s]

Preprocessing:  85%|████████▍ | 7181/8455 [09:02<02:30,  8.46it/s]

Preprocessing:  85%|████████▍ | 7182/8455 [09:02<02:31,  8.38it/s]

Preprocessing:  85%|████████▍ | 7184/8455 [09:02<02:21,  9.00it/s]

Preprocessing:  85%|████████▍ | 7186/8455 [09:03<02:13,  9.52it/s]

Preprocessing:  85%|████████▌ | 7188/8455 [09:03<01:59, 10.64it/s]

Preprocessing:  85%|████████▌ | 7190/8455 [09:03<02:00, 10.46it/s]

Preprocessing:  85%|████████▌ | 7192/8455 [09:03<02:11,  9.64it/s]

Preprocessing:  85%|████████▌ | 7193/8455 [09:03<02:15,  9.28it/s]

Preprocessing:  85%|████████▌ | 7194/8455 [09:03<02:18,  9.08it/s]

Preprocessing:  85%|████████▌ | 7195/8455 [09:04<02:21,  8.93it/s]

Preprocessing:  85%|████████▌ | 7196/8455 [09:04<02:19,  9.03it/s]

Preprocessing:  85%|████████▌ | 7198/8455 [09:04<02:13,  9.41it/s]

Preprocessing:  85%|████████▌ | 7199/8455 [09:04<02:17,  9.14it/s]

Preprocessing:  85%|████████▌ | 7200/8455 [09:04<02:21,  8.84it/s]

Preprocessing:  85%|████████▌ | 7202/8455 [09:04<02:18,  9.05it/s]

Preprocessing:  85%|████████▌ | 7203/8455 [09:04<02:19,  8.96it/s]

Preprocessing:  85%|████████▌ | 7204/8455 [09:05<02:21,  8.83it/s]

Preprocessing:  85%|████████▌ | 7205/8455 [09:05<02:24,  8.67it/s]

Preprocessing:  85%|████████▌ | 7207/8455 [09:05<02:14,  9.30it/s]

Preprocessing:  85%|████████▌ | 7209/8455 [09:05<02:13,  9.33it/s]

Preprocessing:  85%|████████▌ | 7210/8455 [09:05<02:16,  9.12it/s]

Preprocessing:  85%|████████▌ | 7211/8455 [09:05<02:19,  8.89it/s]

Preprocessing:  85%|████████▌ | 7212/8455 [09:05<02:21,  8.75it/s]

Preprocessing:  85%|████████▌ | 7214/8455 [09:06<02:18,  8.96it/s]

Preprocessing:  85%|████████▌ | 7215/8455 [09:06<02:19,  8.90it/s]

Preprocessing:  85%|████████▌ | 7216/8455 [09:06<02:23,  8.65it/s]

Preprocessing:  85%|████████▌ | 7217/8455 [09:06<02:23,  8.60it/s]

Preprocessing:  85%|████████▌ | 7218/8455 [09:06<02:24,  8.54it/s]

Preprocessing:  85%|████████▌ | 7219/8455 [09:06<02:28,  8.32it/s]

Preprocessing:  85%|████████▌ | 7220/8455 [09:06<02:29,  8.24it/s]

Preprocessing:  85%|████████▌ | 7221/8455 [09:07<02:30,  8.20it/s]

Preprocessing:  85%|████████▌ | 7222/8455 [09:07<02:31,  8.14it/s]

Preprocessing:  85%|████████▌ | 7224/8455 [09:07<02:20,  8.76it/s]

Preprocessing:  85%|████████▌ | 7225/8455 [09:07<02:26,  8.40it/s]

Preprocessing:  85%|████████▌ | 7226/8455 [09:07<02:29,  8.20it/s]

Preprocessing:  85%|████████▌ | 7227/8455 [09:07<02:31,  8.10it/s]

Preprocessing:  85%|████████▌ | 7228/8455 [09:07<02:34,  7.93it/s]

Preprocessing:  86%|████████▌ | 7230/8455 [09:08<02:25,  8.42it/s]

Preprocessing:  86%|████████▌ | 7231/8455 [09:08<02:20,  8.71it/s]

Preprocessing:  86%|████████▌ | 7233/8455 [09:08<02:17,  8.89it/s]

Preprocessing:  86%|████████▌ | 7235/8455 [09:08<02:13,  9.11it/s]

Preprocessing:  86%|████████▌ | 7236/8455 [09:08<02:17,  8.89it/s]

Preprocessing:  86%|████████▌ | 7237/8455 [09:08<02:19,  8.71it/s]

Preprocessing:  86%|████████▌ | 7238/8455 [09:09<02:22,  8.55it/s]

Preprocessing:  86%|████████▌ | 7239/8455 [09:09<02:24,  8.44it/s]

Preprocessing:  86%|████████▌ | 7241/8455 [09:09<02:18,  8.75it/s]

Preprocessing:  86%|████████▌ | 7242/8455 [09:09<02:27,  8.21it/s]

Preprocessing:  86%|████████▌ | 7243/8455 [09:09<02:21,  8.57it/s]

Preprocessing:  86%|████████▌ | 7244/8455 [09:09<02:16,  8.87it/s]

Preprocessing:  86%|████████▌ | 7245/8455 [09:09<02:13,  9.06it/s]

Preprocessing:  86%|████████▌ | 7246/8455 [09:09<02:15,  8.92it/s]

Preprocessing:  86%|████████▌ | 7248/8455 [09:10<01:59, 10.11it/s]

Preprocessing:  86%|████████▌ | 7249/8455 [09:10<02:12,  9.10it/s]

Preprocessing:  86%|████████▌ | 7251/8455 [09:10<02:04,  9.66it/s]

Preprocessing:  86%|████████▌ | 7252/8455 [09:10<02:06,  9.51it/s]

Preprocessing:  86%|████████▌ | 7253/8455 [09:10<02:08,  9.37it/s]

Preprocessing:  86%|████████▌ | 7254/8455 [09:10<02:07,  9.45it/s]

Preprocessing:  86%|████████▌ | 7256/8455 [09:10<02:04,  9.60it/s]

Preprocessing:  86%|████████▌ | 7258/8455 [09:11<01:58, 10.10it/s]

Preprocessing:  86%|████████▌ | 7260/8455 [09:11<01:46, 11.24it/s]

Preprocessing:  86%|████████▌ | 7262/8455 [09:11<01:42, 11.60it/s]

Preprocessing:  86%|████████▌ | 7264/8455 [09:11<01:36, 12.33it/s]

Preprocessing:  86%|████████▌ | 7266/8455 [09:11<01:35, 12.48it/s]

Preprocessing:  86%|████████▌ | 7268/8455 [09:11<01:37, 12.16it/s]

Preprocessing:  86%|████████▌ | 7270/8455 [09:12<01:33, 12.64it/s]

Preprocessing:  86%|████████▌ | 7272/8455 [09:12<01:31, 12.91it/s]

Preprocessing:  86%|████████▌ | 7274/8455 [09:12<01:30, 13.05it/s]

Preprocessing:  86%|████████▌ | 7276/8455 [09:12<01:34, 12.45it/s]

Preprocessing:  86%|████████▌ | 7278/8455 [09:12<01:33, 12.61it/s]

Preprocessing:  86%|████████▌ | 7280/8455 [09:12<01:45, 11.17it/s]

Preprocessing:  86%|████████▌ | 7282/8455 [09:13<01:54, 10.25it/s]

Preprocessing:  86%|████████▌ | 7284/8455 [09:13<01:51, 10.51it/s]

Preprocessing:  86%|████████▌ | 7286/8455 [09:13<01:43, 11.25it/s]

Preprocessing:  86%|████████▌ | 7288/8455 [09:13<01:37, 12.00it/s]

Preprocessing:  86%|████████▌ | 7290/8455 [09:13<01:44, 11.16it/s]

Preprocessing:  86%|████████▌ | 7292/8455 [09:13<01:38, 11.82it/s]

Preprocessing:  86%|████████▋ | 7294/8455 [09:14<01:46, 10.94it/s]

Preprocessing:  86%|████████▋ | 7296/8455 [09:14<01:45, 11.03it/s]

Preprocessing:  86%|████████▋ | 7298/8455 [09:14<01:51, 10.41it/s]

Preprocessing:  86%|████████▋ | 7300/8455 [09:14<01:55, 10.00it/s]

Preprocessing:  86%|████████▋ | 7302/8455 [09:15<02:00,  9.57it/s]

Preprocessing:  86%|████████▋ | 7304/8455 [09:15<01:48, 10.60it/s]

Preprocessing:  86%|████████▋ | 7306/8455 [09:15<01:40, 11.45it/s]

Preprocessing:  86%|████████▋ | 7308/8455 [09:15<01:42, 11.21it/s]

Preprocessing:  86%|████████▋ | 7310/8455 [09:15<01:50, 10.40it/s]

Preprocessing:  86%|████████▋ | 7312/8455 [09:15<01:56,  9.77it/s]

Preprocessing:  87%|████████▋ | 7314/8455 [09:16<01:58,  9.64it/s]

Preprocessing:  87%|████████▋ | 7315/8455 [09:16<02:02,  9.29it/s]

Preprocessing:  87%|████████▋ | 7316/8455 [09:16<02:06,  9.02it/s]

Preprocessing:  87%|████████▋ | 7317/8455 [09:16<02:08,  8.84it/s]

Preprocessing:  87%|████████▋ | 7318/8455 [09:16<02:09,  8.75it/s]

Preprocessing:  87%|████████▋ | 7319/8455 [09:16<02:11,  8.64it/s]

Preprocessing:  87%|████████▋ | 7320/8455 [09:16<02:12,  8.57it/s]

Preprocessing:  87%|████████▋ | 7321/8455 [09:17<02:12,  8.59it/s]

Preprocessing:  87%|████████▋ | 7322/8455 [09:17<02:10,  8.68it/s]

Preprocessing:  87%|████████▋ | 7323/8455 [09:17<02:24,  7.84it/s]

Preprocessing:  87%|████████▋ | 7324/8455 [09:17<02:23,  7.86it/s]

Preprocessing:  87%|████████▋ | 7325/8455 [09:17<02:15,  8.33it/s]

Preprocessing:  87%|████████▋ | 7327/8455 [09:17<02:05,  8.98it/s]

Preprocessing:  87%|████████▋ | 7328/8455 [09:17<02:08,  8.80it/s]

Preprocessing:  87%|████████▋ | 7329/8455 [09:17<02:09,  8.67it/s]

Preprocessing:  87%|████████▋ | 7330/8455 [09:18<02:08,  8.74it/s]

Preprocessing:  87%|████████▋ | 7331/8455 [09:18<02:19,  8.06it/s]

Preprocessing:  87%|████████▋ | 7332/8455 [09:18<02:24,  7.75it/s]

Preprocessing:  87%|████████▋ | 7334/8455 [09:18<01:55,  9.68it/s]

Preprocessing:  87%|████████▋ | 7336/8455 [09:18<01:34, 11.79it/s]

Preprocessing:  87%|████████▋ | 7339/8455 [09:18<01:23, 13.41it/s]

Preprocessing:  87%|████████▋ | 7341/8455 [09:18<01:16, 14.63it/s]

Preprocessing:  87%|████████▋ | 7343/8455 [09:19<01:20, 13.89it/s]

Preprocessing:  87%|████████▋ | 7345/8455 [09:19<01:23, 13.34it/s]

Preprocessing:  87%|████████▋ | 7347/8455 [09:19<01:22, 13.47it/s]

Preprocessing:  87%|████████▋ | 7349/8455 [09:19<01:24, 13.16it/s]

Preprocessing:  87%|████████▋ | 7351/8455 [09:19<01:28, 12.49it/s]

Preprocessing:  87%|████████▋ | 7353/8455 [09:19<01:38, 11.19it/s]

Preprocessing:  87%|████████▋ | 7355/8455 [09:20<01:43, 10.62it/s]

Preprocessing:  87%|████████▋ | 7357/8455 [09:20<01:43, 10.65it/s]

Preprocessing:  87%|████████▋ | 7359/8455 [09:20<01:47, 10.22it/s]

Preprocessing:  87%|████████▋ | 7361/8455 [09:20<01:52,  9.76it/s]

Preprocessing:  87%|████████▋ | 7362/8455 [09:20<01:57,  9.27it/s]

Preprocessing:  87%|████████▋ | 7363/8455 [09:21<01:56,  9.39it/s]

Preprocessing:  87%|████████▋ | 7365/8455 [09:21<01:56,  9.36it/s]

Preprocessing:  87%|████████▋ | 7366/8455 [09:21<01:56,  9.31it/s]

Preprocessing:  87%|████████▋ | 7367/8455 [09:21<01:55,  9.39it/s]

Preprocessing:  87%|████████▋ | 7368/8455 [09:21<02:01,  8.98it/s]

Preprocessing:  87%|████████▋ | 7369/8455 [09:21<02:05,  8.67it/s]

Preprocessing:  87%|████████▋ | 7370/8455 [09:21<02:07,  8.52it/s]

Preprocessing:  87%|████████▋ | 7371/8455 [09:21<02:13,  8.11it/s]

Preprocessing:  87%|████████▋ | 7372/8455 [09:22<02:13,  8.14it/s]

Preprocessing:  87%|████████▋ | 7373/8455 [09:22<02:14,  8.07it/s]

Preprocessing:  87%|████████▋ | 7375/8455 [09:22<01:55,  9.36it/s]

Preprocessing:  87%|████████▋ | 7376/8455 [09:22<02:03,  8.77it/s]

Preprocessing:  87%|████████▋ | 7378/8455 [09:22<01:59,  9.03it/s]

Preprocessing:  87%|████████▋ | 7379/8455 [09:22<02:02,  8.77it/s]

Preprocessing:  87%|████████▋ | 7381/8455 [09:23<01:57,  9.14it/s]

Preprocessing:  87%|████████▋ | 7382/8455 [09:23<01:57,  9.13it/s]

Preprocessing:  87%|████████▋ | 7383/8455 [09:23<02:00,  8.89it/s]

Preprocessing:  87%|████████▋ | 7384/8455 [09:23<02:06,  8.48it/s]

Preprocessing:  87%|████████▋ | 7386/8455 [09:23<01:59,  8.98it/s]

Preprocessing:  87%|████████▋ | 7387/8455 [09:23<01:59,  8.96it/s]

Preprocessing:  87%|████████▋ | 7388/8455 [09:23<02:01,  8.76it/s]

Preprocessing:  87%|████████▋ | 7389/8455 [09:23<02:04,  8.58it/s]

Preprocessing:  87%|████████▋ | 7390/8455 [09:24<02:03,  8.65it/s]

Preprocessing:  87%|████████▋ | 7391/8455 [09:24<02:00,  8.85it/s]

Preprocessing:  87%|████████▋ | 7392/8455 [09:24<02:00,  8.84it/s]

Preprocessing:  87%|████████▋ | 7393/8455 [09:24<02:05,  8.49it/s]

Preprocessing:  87%|████████▋ | 7394/8455 [09:24<02:09,  8.22it/s]

Preprocessing:  87%|████████▋ | 7395/8455 [09:24<02:10,  8.12it/s]

Preprocessing:  87%|████████▋ | 7396/8455 [09:24<02:10,  8.12it/s]

Preprocessing:  87%|████████▋ | 7397/8455 [09:24<02:10,  8.09it/s]

Preprocessing:  87%|████████▋ | 7398/8455 [09:25<02:05,  8.40it/s]

Preprocessing:  88%|████████▊ | 7400/8455 [09:25<01:56,  9.09it/s]

Preprocessing:  88%|████████▊ | 7401/8455 [09:25<01:54,  9.23it/s]

Preprocessing:  88%|████████▊ | 7402/8455 [09:25<01:57,  8.98it/s]

Preprocessing:  88%|████████▊ | 7403/8455 [09:25<02:01,  8.66it/s]

Preprocessing:  88%|████████▊ | 7405/8455 [09:25<01:53,  9.28it/s]

Preprocessing:  88%|████████▊ | 7406/8455 [09:25<01:59,  8.80it/s]

Preprocessing:  88%|████████▊ | 7407/8455 [09:26<01:59,  8.77it/s]

Preprocessing:  88%|████████▊ | 7408/8455 [09:26<01:58,  8.80it/s]

Preprocessing:  88%|████████▊ | 7409/8455 [09:26<02:01,  8.64it/s]

Preprocessing:  88%|████████▊ | 7410/8455 [09:26<01:56,  8.94it/s]

Preprocessing:  88%|████████▊ | 7411/8455 [09:26<01:58,  8.80it/s]

Preprocessing:  88%|████████▊ | 7412/8455 [09:26<02:01,  8.60it/s]

Preprocessing:  88%|████████▊ | 7413/8455 [09:26<02:02,  8.47it/s]

Preprocessing:  88%|████████▊ | 7414/8455 [09:26<02:02,  8.48it/s]

Preprocessing:  88%|████████▊ | 7415/8455 [09:26<02:01,  8.54it/s]

Preprocessing:  88%|████████▊ | 7416/8455 [09:27<01:56,  8.88it/s]

Preprocessing:  88%|████████▊ | 7418/8455 [09:27<01:54,  9.04it/s]

Preprocessing:  88%|████████▊ | 7420/8455 [09:27<01:45,  9.82it/s]

Preprocessing:  88%|████████▊ | 7422/8455 [09:27<01:37, 10.64it/s]

Preprocessing:  88%|████████▊ | 7424/8455 [09:27<01:38, 10.47it/s]

Preprocessing:  88%|████████▊ | 7426/8455 [09:28<01:42, 10.00it/s]

Preprocessing:  88%|████████▊ | 7428/8455 [09:28<01:42, 10.01it/s]

Preprocessing:  88%|████████▊ | 7430/8455 [09:28<01:46,  9.60it/s]

Preprocessing:  88%|████████▊ | 7431/8455 [09:28<01:49,  9.38it/s]

Preprocessing:  88%|████████▊ | 7432/8455 [09:28<01:51,  9.14it/s]

Preprocessing:  88%|████████▊ | 7434/8455 [09:28<01:49,  9.33it/s]

Preprocessing:  88%|████████▊ | 7435/8455 [09:29<01:53,  8.97it/s]

Preprocessing:  88%|████████▊ | 7437/8455 [09:29<01:41, 10.02it/s]

Preprocessing:  88%|████████▊ | 7438/8455 [09:29<01:46,  9.56it/s]

Preprocessing:  88%|████████▊ | 7439/8455 [09:29<01:55,  8.81it/s]

Preprocessing:  88%|████████▊ | 7441/8455 [09:29<01:42,  9.91it/s]

Preprocessing:  88%|████████▊ | 7442/8455 [09:29<01:48,  9.33it/s]

Preprocessing:  88%|████████▊ | 7443/8455 [09:29<01:52,  9.03it/s]

Preprocessing:  88%|████████▊ | 7444/8455 [09:29<01:52,  8.97it/s]

Preprocessing:  88%|████████▊ | 7445/8455 [09:30<01:49,  9.18it/s]

Preprocessing:  88%|████████▊ | 7446/8455 [09:30<01:51,  9.08it/s]

Preprocessing:  88%|████████▊ | 7447/8455 [09:30<01:56,  8.65it/s]

Preprocessing:  88%|████████▊ | 7448/8455 [09:30<01:58,  8.49it/s]

Preprocessing:  88%|████████▊ | 7450/8455 [09:30<01:43,  9.73it/s]

Preprocessing:  88%|████████▊ | 7451/8455 [09:30<01:46,  9.39it/s]

Preprocessing:  88%|████████▊ | 7452/8455 [09:30<01:50,  9.06it/s]

Preprocessing:  88%|████████▊ | 7453/8455 [09:31<01:55,  8.66it/s]

Preprocessing:  88%|████████▊ | 7454/8455 [09:31<01:53,  8.79it/s]

Preprocessing:  88%|████████▊ | 7455/8455 [09:31<01:53,  8.82it/s]

Preprocessing:  88%|████████▊ | 7457/8455 [09:31<01:47,  9.26it/s]

Preprocessing:  88%|████████▊ | 7458/8455 [09:31<01:51,  8.97it/s]

Preprocessing:  88%|████████▊ | 7459/8455 [09:31<01:53,  8.78it/s]

Preprocessing:  88%|████████▊ | 7460/8455 [09:31<01:54,  8.69it/s]

Preprocessing:  88%|████████▊ | 7461/8455 [09:31<01:59,  8.34it/s]

Preprocessing:  88%|████████▊ | 7463/8455 [09:32<01:49,  9.09it/s]

Preprocessing:  88%|████████▊ | 7464/8455 [09:32<01:51,  8.91it/s]

Preprocessing:  88%|████████▊ | 7465/8455 [09:32<01:48,  9.15it/s]

Preprocessing:  88%|████████▊ | 7467/8455 [09:32<01:44,  9.41it/s]

Preprocessing:  88%|████████▊ | 7468/8455 [09:32<01:47,  9.14it/s]

Preprocessing:  88%|████████▊ | 7469/8455 [09:32<01:50,  8.95it/s]

Preprocessing:  88%|████████▊ | 7470/8455 [09:32<01:53,  8.68it/s]

Preprocessing:  88%|████████▊ | 7471/8455 [09:33<01:52,  8.76it/s]

Preprocessing:  88%|████████▊ | 7473/8455 [09:33<01:43,  9.52it/s]

Preprocessing:  88%|████████▊ | 7474/8455 [09:33<01:47,  9.14it/s]

Preprocessing:  88%|████████▊ | 7475/8455 [09:33<01:45,  9.29it/s]

Preprocessing:  88%|████████▊ | 7477/8455 [09:33<01:41,  9.63it/s]

Preprocessing:  88%|████████▊ | 7479/8455 [09:33<01:42,  9.55it/s]

Preprocessing:  88%|████████▊ | 7480/8455 [09:33<01:46,  9.18it/s]

Preprocessing:  88%|████████▊ | 7481/8455 [09:34<01:45,  9.23it/s]

Preprocessing:  89%|████████▊ | 7483/8455 [09:34<01:41,  9.56it/s]

Preprocessing:  89%|████████▊ | 7485/8455 [09:34<01:35, 10.13it/s]

Preprocessing:  89%|████████▊ | 7486/8455 [09:34<01:42,  9.44it/s]

Preprocessing:  89%|████████▊ | 7488/8455 [09:34<01:40,  9.59it/s]

Preprocessing:  89%|████████▊ | 7490/8455 [09:34<01:39,  9.70it/s]

Preprocessing:  89%|████████▊ | 7492/8455 [09:35<01:33, 10.33it/s]

Preprocessing:  89%|████████▊ | 7494/8455 [09:35<01:40,  9.56it/s]

Preprocessing:  89%|████████▊ | 7496/8455 [09:35<01:37,  9.88it/s]

Preprocessing:  89%|████████▊ | 7497/8455 [09:35<01:40,  9.54it/s]

Preprocessing:  89%|████████▊ | 7498/8455 [09:35<01:43,  9.29it/s]

Preprocessing:  89%|████████▊ | 7499/8455 [09:35<01:47,  8.88it/s]

Preprocessing:  89%|████████▊ | 7500/8455 [09:36<01:48,  8.84it/s]

Preprocessing:  89%|████████▊ | 7501/8455 [09:36<01:47,  8.90it/s]

Preprocessing:  89%|████████▊ | 7502/8455 [09:36<01:49,  8.68it/s]

Preprocessing:  89%|████████▊ | 7503/8455 [09:36<01:58,  8.06it/s]

Preprocessing:  89%|████████▉ | 7505/8455 [09:36<01:48,  8.75it/s]

Preprocessing:  89%|████████▉ | 7506/8455 [09:36<01:49,  8.69it/s]

Preprocessing:  89%|████████▉ | 7507/8455 [09:36<01:52,  8.44it/s]

Preprocessing:  89%|████████▉ | 7508/8455 [09:37<01:51,  8.47it/s]

Preprocessing:  89%|████████▉ | 7509/8455 [09:37<01:49,  8.63it/s]

Preprocessing:  89%|████████▉ | 7510/8455 [09:37<01:46,  8.89it/s]

Preprocessing:  89%|████████▉ | 7511/8455 [09:37<01:48,  8.73it/s]

Preprocessing:  89%|████████▉ | 7512/8455 [09:37<01:48,  8.69it/s]

Preprocessing:  89%|████████▉ | 7514/8455 [09:37<01:36,  9.77it/s]

Preprocessing:  89%|████████▉ | 7516/8455 [09:37<01:33, 10.09it/s]

Preprocessing:  89%|████████▉ | 7517/8455 [09:37<01:38,  9.52it/s]

Preprocessing:  89%|████████▉ | 7518/8455 [09:38<01:39,  9.39it/s]

Preprocessing:  89%|████████▉ | 7519/8455 [09:38<01:44,  8.91it/s]

Preprocessing:  89%|████████▉ | 7520/8455 [09:38<01:52,  8.34it/s]

Preprocessing:  89%|████████▉ | 7521/8455 [09:38<01:52,  8.29it/s]

Preprocessing:  89%|████████▉ | 7522/8455 [09:38<01:56,  8.04it/s]

Preprocessing:  89%|████████▉ | 7524/8455 [09:38<01:48,  8.55it/s]

Preprocessing:  89%|████████▉ | 7525/8455 [09:38<02:04,  7.47it/s]

Preprocessing:  89%|████████▉ | 7526/8455 [09:39<01:56,  7.95it/s]

Preprocessing:  89%|████████▉ | 7528/8455 [09:39<01:42,  9.01it/s]

Preprocessing:  89%|████████▉ | 7529/8455 [09:39<01:41,  9.10it/s]

Preprocessing:  89%|████████▉ | 7531/8455 [09:39<01:35,  9.66it/s]

Preprocessing:  89%|████████▉ | 7533/8455 [09:39<01:34,  9.72it/s]

Preprocessing:  89%|████████▉ | 7534/8455 [09:39<01:48,  8.46it/s]

Preprocessing:  89%|████████▉ | 7536/8455 [09:40<01:31,  9.99it/s]

Preprocessing:  89%|████████▉ | 7538/8455 [09:40<01:29, 10.28it/s]

Preprocessing:  89%|████████▉ | 7540/8455 [09:40<01:23, 10.97it/s]

Preprocessing:  89%|████████▉ | 7542/8455 [09:40<01:20, 11.32it/s]

Preprocessing:  89%|████████▉ | 7544/8455 [09:40<01:30, 10.06it/s]

Preprocessing:  89%|████████▉ | 7546/8455 [09:41<01:30, 10.08it/s]

Preprocessing:  89%|████████▉ | 7548/8455 [09:41<01:27, 10.41it/s]

Preprocessing:  89%|████████▉ | 7550/8455 [09:41<01:20, 11.20it/s]

Preprocessing:  89%|████████▉ | 7552/8455 [09:41<01:15, 11.96it/s]

Preprocessing:  89%|████████▉ | 7554/8455 [09:41<01:10, 12.81it/s]

Preprocessing:  89%|████████▉ | 7556/8455 [09:41<01:04, 13.95it/s]

Preprocessing:  89%|████████▉ | 7558/8455 [09:41<01:00, 14.87it/s]

Preprocessing:  89%|████████▉ | 7560/8455 [09:41<00:56, 15.87it/s]

Preprocessing:  89%|████████▉ | 7562/8455 [09:42<00:57, 15.65it/s]

Preprocessing:  89%|████████▉ | 7564/8455 [09:42<01:10, 12.55it/s]

Preprocessing:  89%|████████▉ | 7566/8455 [09:42<01:18, 11.33it/s]

Preprocessing:  90%|████████▉ | 7568/8455 [09:42<01:20, 10.97it/s]

Preprocessing:  90%|████████▉ | 7570/8455 [09:42<01:27, 10.14it/s]

Preprocessing:  90%|████████▉ | 7572/8455 [09:43<01:28, 10.03it/s]

Preprocessing:  90%|████████▉ | 7574/8455 [09:43<01:29,  9.82it/s]

Preprocessing:  90%|████████▉ | 7576/8455 [09:43<01:26, 10.12it/s]

Preprocessing:  90%|████████▉ | 7578/8455 [09:43<01:26, 10.09it/s]

Preprocessing:  90%|████████▉ | 7580/8455 [09:43<01:23, 10.48it/s]

Preprocessing:  90%|████████▉ | 7582/8455 [09:44<01:20, 10.86it/s]

Preprocessing:  90%|████████▉ | 7584/8455 [09:44<01:17, 11.23it/s]

Preprocessing:  90%|████████▉ | 7586/8455 [09:44<01:17, 11.27it/s]

Preprocessing:  90%|████████▉ | 7588/8455 [09:44<01:17, 11.12it/s]

Preprocessing:  90%|████████▉ | 7590/8455 [09:44<01:19, 10.93it/s]

Preprocessing:  90%|████████▉ | 7592/8455 [09:45<01:18, 10.99it/s]

Preprocessing:  90%|████████▉ | 7594/8455 [09:45<01:15, 11.37it/s]

Preprocessing:  90%|████████▉ | 7596/8455 [09:45<01:17, 11.08it/s]

Preprocessing:  90%|████████▉ | 7598/8455 [09:45<01:20, 10.64it/s]

Preprocessing:  90%|████████▉ | 7600/8455 [09:45<01:24, 10.07it/s]

Preprocessing:  90%|████████▉ | 7602/8455 [09:45<01:24, 10.07it/s]

Preprocessing:  90%|████████▉ | 7604/8455 [09:46<01:23, 10.16it/s]

Preprocessing:  90%|████████▉ | 7606/8455 [09:46<01:27,  9.74it/s]

Preprocessing:  90%|████████▉ | 7607/8455 [09:46<01:34,  9.02it/s]

Preprocessing:  90%|████████▉ | 7608/8455 [09:46<01:38,  8.63it/s]

Preprocessing:  90%|████████▉ | 7609/8455 [09:46<01:40,  8.40it/s]

Preprocessing:  90%|█████████ | 7610/8455 [09:46<01:40,  8.37it/s]

Preprocessing:  90%|█████████ | 7611/8455 [09:47<01:42,  8.26it/s]

Preprocessing:  90%|█████████ | 7612/8455 [09:47<01:38,  8.53it/s]

Preprocessing:  90%|█████████ | 7614/8455 [09:47<01:28,  9.49it/s]

Preprocessing:  90%|█████████ | 7615/8455 [09:47<01:27,  9.60it/s]

Preprocessing:  90%|█████████ | 7616/8455 [09:47<01:35,  8.80it/s]

Preprocessing:  90%|█████████ | 7618/8455 [09:47<01:28,  9.50it/s]

Preprocessing:  90%|█████████ | 7620/8455 [09:47<01:25,  9.78it/s]

Preprocessing:  90%|█████████ | 7622/8455 [09:48<01:22, 10.13it/s]

Preprocessing:  90%|█████████ | 7624/8455 [09:48<01:16, 10.91it/s]

Preprocessing:  90%|█████████ | 7626/8455 [09:48<01:10, 11.68it/s]

Preprocessing:  90%|█████████ | 7628/8455 [09:48<01:09, 11.85it/s]

Preprocessing:  90%|█████████ | 7630/8455 [09:48<01:12, 11.37it/s]

Preprocessing:  90%|█████████ | 7632/8455 [09:48<01:09, 11.83it/s]

Preprocessing:  90%|█████████ | 7634/8455 [09:49<01:08, 11.90it/s]

Preprocessing:  90%|█████████ | 7636/8455 [09:49<01:06, 12.23it/s]

Preprocessing:  90%|█████████ | 7638/8455 [09:49<01:06, 12.22it/s]

Preprocessing:  90%|█████████ | 7640/8455 [09:49<01:06, 12.25it/s]

Preprocessing:  90%|█████████ | 7642/8455 [09:49<01:06, 12.14it/s]

Preprocessing:  90%|█████████ | 7644/8455 [09:50<01:17, 10.45it/s]

Preprocessing:  90%|█████████ | 7646/8455 [09:50<01:19, 10.12it/s]

Preprocessing:  90%|█████████ | 7648/8455 [09:50<01:17, 10.48it/s]

Preprocessing:  90%|█████████ | 7650/8455 [09:50<01:23,  9.61it/s]

Preprocessing:  91%|█████████ | 7652/8455 [09:50<01:20,  9.93it/s]

Preprocessing:  91%|█████████ | 7654/8455 [09:51<01:17, 10.28it/s]

Preprocessing:  91%|█████████ | 7656/8455 [09:51<01:20,  9.92it/s]

Preprocessing:  91%|█████████ | 7658/8455 [09:51<01:22,  9.69it/s]

Preprocessing:  91%|█████████ | 7659/8455 [09:51<01:23,  9.53it/s]

Preprocessing:  91%|█████████ | 7660/8455 [09:51<01:25,  9.34it/s]

Preprocessing:  91%|█████████ | 7661/8455 [09:51<01:26,  9.18it/s]

Preprocessing:  91%|█████████ | 7662/8455 [09:51<01:27,  9.07it/s]

Preprocessing:  91%|█████████ | 7664/8455 [09:52<01:24,  9.38it/s]

Preprocessing:  91%|█████████ | 7665/8455 [09:52<01:27,  8.98it/s]

Preprocessing:  91%|█████████ | 7667/8455 [09:52<01:28,  8.92it/s]

Preprocessing:  91%|█████████ | 7668/8455 [09:52<01:36,  8.14it/s]

Preprocessing:  91%|█████████ | 7669/8455 [09:52<01:39,  7.92it/s]

Preprocessing:  91%|█████████ | 7670/8455 [09:52<01:37,  8.01it/s]

Preprocessing:  91%|█████████ | 7671/8455 [09:53<01:35,  8.17it/s]

Preprocessing:  91%|█████████ | 7672/8455 [09:53<01:33,  8.37it/s]

Preprocessing:  91%|█████████ | 7673/8455 [09:53<01:34,  8.28it/s]

Preprocessing:  91%|█████████ | 7674/8455 [09:53<01:33,  8.35it/s]

Preprocessing:  91%|█████████ | 7675/8455 [09:53<01:34,  8.26it/s]

Preprocessing:  91%|█████████ | 7676/8455 [09:53<01:45,  7.41it/s]

Preprocessing:  91%|█████████ | 7677/8455 [09:53<01:38,  7.92it/s]

Preprocessing:  91%|█████████ | 7678/8455 [09:53<01:38,  7.92it/s]

Preprocessing:  91%|█████████ | 7679/8455 [09:54<01:34,  8.25it/s]

Preprocessing:  91%|█████████ | 7680/8455 [09:54<01:32,  8.42it/s]

Preprocessing:  91%|█████████ | 7681/8455 [09:54<01:33,  8.26it/s]

Preprocessing:  91%|█████████ | 7682/8455 [09:54<01:33,  8.30it/s]

Preprocessing:  91%|█████████ | 7684/8455 [09:54<01:26,  8.93it/s]

Preprocessing:  91%|█████████ | 7686/8455 [09:54<01:23,  9.24it/s]

Preprocessing:  91%|█████████ | 7687/8455 [09:54<01:26,  8.89it/s]

Preprocessing:  91%|█████████ | 7689/8455 [09:55<01:15, 10.09it/s]

Preprocessing:  91%|█████████ | 7691/8455 [09:55<01:18,  9.70it/s]

Preprocessing:  91%|█████████ | 7692/8455 [09:55<01:20,  9.42it/s]

Preprocessing:  91%|█████████ | 7693/8455 [09:55<01:28,  8.59it/s]

Preprocessing:  91%|█████████ | 7695/8455 [09:55<01:24,  8.97it/s]

Preprocessing:  91%|█████████ | 7697/8455 [09:55<01:24,  8.94it/s]

Preprocessing:  91%|█████████ | 7698/8455 [09:56<01:32,  8.23it/s]

Preprocessing:  91%|█████████ | 7699/8455 [09:56<01:32,  8.14it/s]

Preprocessing:  91%|█████████ | 7701/8455 [09:56<01:15, 10.03it/s]

Preprocessing:  91%|█████████ | 7703/8455 [09:56<01:01, 12.13it/s]

Preprocessing:  91%|█████████ | 7705/8455 [09:56<00:59, 12.71it/s]

Preprocessing:  91%|█████████ | 7707/8455 [09:56<01:03, 11.85it/s]

Preprocessing:  91%|█████████ | 7709/8455 [09:57<01:04, 11.58it/s]

Preprocessing:  91%|█████████ | 7711/8455 [09:57<01:05, 11.32it/s]

Preprocessing:  91%|█████████ | 7713/8455 [09:57<01:08, 10.82it/s]

Preprocessing:  91%|█████████ | 7715/8455 [09:57<01:06, 11.05it/s]

Preprocessing:  91%|█████████▏| 7717/8455 [09:57<01:06, 11.05it/s]

Preprocessing:  91%|█████████▏| 7719/8455 [09:57<01:10, 10.40it/s]

Preprocessing:  91%|█████████▏| 7721/8455 [09:58<01:13,  9.99it/s]

Preprocessing:  91%|█████████▏| 7723/8455 [09:58<01:16,  9.52it/s]

Preprocessing:  91%|█████████▏| 7725/8455 [09:58<01:12, 10.08it/s]

Preprocessing:  91%|█████████▏| 7727/8455 [09:58<01:16,  9.50it/s]

Preprocessing:  91%|█████████▏| 7729/8455 [09:59<01:15,  9.64it/s]

Preprocessing:  91%|█████████▏| 7731/8455 [09:59<01:14,  9.75it/s]

Preprocessing:  91%|█████████▏| 7732/8455 [09:59<01:17,  9.39it/s]

Preprocessing:  91%|█████████▏| 7733/8455 [09:59<01:17,  9.35it/s]

Preprocessing:  91%|█████████▏| 7735/8455 [09:59<01:13,  9.77it/s]

Preprocessing:  92%|█████████▏| 7737/8455 [09:59<01:08, 10.47it/s]

Preprocessing:  92%|█████████▏| 7739/8455 [10:00<01:07, 10.64it/s]

Preprocessing:  92%|█████████▏| 7741/8455 [10:00<01:10, 10.12it/s]

Preprocessing:  92%|█████████▏| 7743/8455 [10:00<01:11, 10.01it/s]

Preprocessing:  92%|█████████▏| 7745/8455 [10:00<01:11,  9.91it/s]

Preprocessing:  92%|█████████▏| 7746/8455 [10:00<01:13,  9.68it/s]

Preprocessing:  92%|█████████▏| 7747/8455 [10:00<01:14,  9.50it/s]

Preprocessing:  92%|█████████▏| 7748/8455 [10:00<01:14,  9.46it/s]

Preprocessing:  92%|█████████▏| 7749/8455 [10:01<01:19,  8.91it/s]

Preprocessing:  92%|█████████▏| 7750/8455 [10:01<01:23,  8.43it/s]

Preprocessing:  92%|█████████▏| 7752/8455 [10:01<01:20,  8.76it/s]

Preprocessing:  92%|█████████▏| 7753/8455 [10:01<01:22,  8.50it/s]

Preprocessing:  92%|█████████▏| 7754/8455 [10:01<01:20,  8.75it/s]

Preprocessing:  92%|█████████▏| 7756/8455 [10:01<01:15,  9.25it/s]

Preprocessing:  92%|█████████▏| 7757/8455 [10:02<01:17,  8.96it/s]

Preprocessing:  92%|█████████▏| 7759/8455 [10:02<01:13,  9.47it/s]

Preprocessing:  92%|█████████▏| 7760/8455 [10:02<01:15,  9.24it/s]

Preprocessing:  92%|█████████▏| 7762/8455 [10:02<01:07, 10.27it/s]

Preprocessing:  92%|█████████▏| 7764/8455 [10:02<01:04, 10.66it/s]

Preprocessing:  92%|█████████▏| 7766/8455 [10:02<01:11,  9.70it/s]

Preprocessing:  92%|█████████▏| 7767/8455 [10:03<01:12,  9.54it/s]

Preprocessing:  92%|█████████▏| 7768/8455 [10:03<01:15,  9.15it/s]

Preprocessing:  92%|█████████▏| 7769/8455 [10:03<01:14,  9.21it/s]

Preprocessing:  92%|█████████▏| 7771/8455 [10:03<01:10,  9.66it/s]

Preprocessing:  92%|█████████▏| 7772/8455 [10:03<01:12,  9.43it/s]

Preprocessing:  92%|█████████▏| 7774/8455 [10:03<01:13,  9.24it/s]

Preprocessing:  92%|█████████▏| 7775/8455 [10:03<01:16,  8.88it/s]

Preprocessing:  92%|█████████▏| 7776/8455 [10:04<01:19,  8.56it/s]

Preprocessing:  92%|█████████▏| 7777/8455 [10:04<01:19,  8.55it/s]

Preprocessing:  92%|█████████▏| 7778/8455 [10:04<01:19,  8.52it/s]

Preprocessing:  92%|█████████▏| 7779/8455 [10:04<01:19,  8.54it/s]

Preprocessing:  92%|█████████▏| 7780/8455 [10:04<01:20,  8.40it/s]

Preprocessing:  92%|█████████▏| 7781/8455 [10:04<01:20,  8.42it/s]

Preprocessing:  92%|█████████▏| 7782/8455 [10:04<01:22,  8.18it/s]

Preprocessing:  92%|█████████▏| 7783/8455 [10:04<01:22,  8.11it/s]

Preprocessing:  92%|█████████▏| 7784/8455 [10:05<01:20,  8.29it/s]

Preprocessing:  92%|█████████▏| 7785/8455 [10:05<01:19,  8.41it/s]

Preprocessing:  92%|█████████▏| 7786/8455 [10:05<01:21,  8.25it/s]

Preprocessing:  92%|█████████▏| 7787/8455 [10:05<01:24,  7.94it/s]

Preprocessing:  92%|█████████▏| 7788/8455 [10:05<01:20,  8.31it/s]

Preprocessing:  92%|█████████▏| 7790/8455 [10:05<01:17,  8.55it/s]

Preprocessing:  92%|█████████▏| 7791/8455 [10:05<01:18,  8.49it/s]

Preprocessing:  92%|█████████▏| 7792/8455 [10:05<01:18,  8.44it/s]

Preprocessing:  92%|█████████▏| 7793/8455 [10:06<01:17,  8.59it/s]

Preprocessing:  92%|█████████▏| 7794/8455 [10:06<01:18,  8.40it/s]

Preprocessing:  92%|█████████▏| 7795/8455 [10:06<01:19,  8.34it/s]

Preprocessing:  92%|█████████▏| 7796/8455 [10:06<01:19,  8.31it/s]

Preprocessing:  92%|█████████▏| 7797/8455 [10:06<01:20,  8.19it/s]

Preprocessing:  92%|█████████▏| 7798/8455 [10:06<01:22,  7.99it/s]

Preprocessing:  92%|█████████▏| 7800/8455 [10:06<01:17,  8.48it/s]

Preprocessing:  92%|█████████▏| 7801/8455 [10:07<01:16,  8.54it/s]

Preprocessing:  92%|█████████▏| 7802/8455 [10:07<01:16,  8.53it/s]

Preprocessing:  92%|█████████▏| 7803/8455 [10:07<01:17,  8.46it/s]

Preprocessing:  92%|█████████▏| 7805/8455 [10:07<01:11,  9.03it/s]

Preprocessing:  92%|█████████▏| 7806/8455 [10:07<01:13,  8.87it/s]

Preprocessing:  92%|█████████▏| 7808/8455 [10:07<01:14,  8.74it/s]

Preprocessing:  92%|█████████▏| 7810/8455 [10:08<01:10,  9.21it/s]

Preprocessing:  92%|█████████▏| 7811/8455 [10:08<01:10,  9.18it/s]

Preprocessing:  92%|█████████▏| 7812/8455 [10:08<01:12,  8.86it/s]

Preprocessing:  92%|█████████▏| 7813/8455 [10:08<01:15,  8.54it/s]

Preprocessing:  92%|█████████▏| 7814/8455 [10:08<01:16,  8.37it/s]

Preprocessing:  92%|█████████▏| 7815/8455 [10:08<01:17,  8.29it/s]

Preprocessing:  92%|█████████▏| 7816/8455 [10:08<01:13,  8.68it/s]

Preprocessing:  92%|█████████▏| 7817/8455 [10:08<01:18,  8.12it/s]

Preprocessing:  92%|█████████▏| 7818/8455 [10:09<01:18,  8.14it/s]

Preprocessing:  92%|█████████▏| 7819/8455 [10:09<01:16,  8.30it/s]

Preprocessing:  93%|█████████▎| 7821/8455 [10:09<01:09,  9.13it/s]

Preprocessing:  93%|█████████▎| 7823/8455 [10:09<01:10,  8.93it/s]

Preprocessing:  93%|█████████▎| 7824/8455 [10:09<01:14,  8.44it/s]

Preprocessing:  93%|█████████▎| 7825/8455 [10:09<01:14,  8.41it/s]

Preprocessing:  93%|█████████▎| 7827/8455 [10:10<01:14,  8.44it/s]

Preprocessing:  93%|█████████▎| 7828/8455 [10:10<01:15,  8.29it/s]

Preprocessing:  93%|█████████▎| 7829/8455 [10:10<01:17,  8.04it/s]

Preprocessing:  93%|█████████▎| 7830/8455 [10:10<01:18,  7.96it/s]

Preprocessing:  93%|█████████▎| 7831/8455 [10:10<01:17,  8.03it/s]

Preprocessing:  93%|█████████▎| 7832/8455 [10:10<01:18,  7.92it/s]

Preprocessing:  93%|█████████▎| 7833/8455 [10:10<01:17,  8.01it/s]

Preprocessing:  93%|█████████▎| 7834/8455 [10:10<01:13,  8.39it/s]

Preprocessing:  93%|█████████▎| 7835/8455 [10:11<01:13,  8.47it/s]

Preprocessing:  93%|█████████▎| 7837/8455 [10:11<01:09,  8.87it/s]

Preprocessing:  93%|█████████▎| 7838/8455 [10:11<01:08,  9.04it/s]

Preprocessing:  93%|█████████▎| 7839/8455 [10:11<01:08,  8.95it/s]

Preprocessing:  93%|█████████▎| 7840/8455 [10:11<01:09,  8.79it/s]

Preprocessing:  93%|█████████▎| 7841/8455 [10:11<01:17,  7.91it/s]

Preprocessing:  93%|█████████▎| 7842/8455 [10:11<01:13,  8.33it/s]

Preprocessing:  93%|█████████▎| 7843/8455 [10:11<01:13,  8.32it/s]

Preprocessing:  93%|█████████▎| 7844/8455 [10:12<01:12,  8.41it/s]

Preprocessing:  93%|█████████▎| 7846/8455 [10:12<01:07,  9.08it/s]

Preprocessing:  93%|█████████▎| 7847/8455 [10:12<01:08,  8.89it/s]

Preprocessing:  93%|█████████▎| 7848/8455 [10:12<01:09,  8.74it/s]

Preprocessing:  93%|█████████▎| 7849/8455 [10:12<01:11,  8.42it/s]

Preprocessing:  93%|█████████▎| 7850/8455 [10:12<01:12,  8.35it/s]

Preprocessing:  93%|█████████▎| 7851/8455 [10:12<01:13,  8.20it/s]

Preprocessing:  93%|█████████▎| 7853/8455 [10:13<01:06,  9.03it/s]

Preprocessing:  93%|█████████▎| 7854/8455 [10:13<01:08,  8.83it/s]

Preprocessing:  93%|█████████▎| 7855/8455 [10:13<01:08,  8.71it/s]

Preprocessing:  93%|█████████▎| 7856/8455 [10:13<01:07,  8.90it/s]

Preprocessing:  93%|█████████▎| 7857/8455 [10:13<01:09,  8.66it/s]

Preprocessing:  93%|█████████▎| 7858/8455 [10:13<01:12,  8.22it/s]

Preprocessing:  93%|█████████▎| 7859/8455 [10:13<01:13,  8.14it/s]

Preprocessing:  93%|█████████▎| 7860/8455 [10:13<01:12,  8.20it/s]

Preprocessing:  93%|█████████▎| 7861/8455 [10:14<01:12,  8.24it/s]

Preprocessing:  93%|█████████▎| 7863/8455 [10:14<01:06,  8.88it/s]

Preprocessing:  93%|█████████▎| 7865/8455 [10:14<01:02,  9.44it/s]

Preprocessing:  93%|█████████▎| 7866/8455 [10:14<01:04,  9.20it/s]

Preprocessing:  93%|█████████▎| 7868/8455 [10:14<01:02,  9.36it/s]

Preprocessing:  93%|█████████▎| 7869/8455 [10:14<01:04,  9.03it/s]

Preprocessing:  93%|█████████▎| 7870/8455 [10:15<01:05,  8.98it/s]

Preprocessing:  93%|█████████▎| 7871/8455 [10:15<01:05,  8.94it/s]

Preprocessing:  93%|█████████▎| 7872/8455 [10:15<01:11,  8.10it/s]

Preprocessing:  93%|█████████▎| 7874/8455 [10:15<01:07,  8.66it/s]

Preprocessing:  93%|█████████▎| 7876/8455 [10:15<01:04,  8.92it/s]

Preprocessing:  93%|█████████▎| 7877/8455 [10:15<01:07,  8.51it/s]

Preprocessing:  93%|█████████▎| 7879/8455 [10:16<01:05,  8.84it/s]

Preprocessing:  93%|█████████▎| 7880/8455 [10:16<01:03,  9.02it/s]

Preprocessing:  93%|█████████▎| 7881/8455 [10:16<01:11,  8.03it/s]

Preprocessing:  93%|█████████▎| 7883/8455 [10:16<01:03,  9.01it/s]

Preprocessing:  93%|█████████▎| 7884/8455 [10:16<01:06,  8.59it/s]

Preprocessing:  93%|█████████▎| 7885/8455 [10:16<01:07,  8.39it/s]

Preprocessing:  93%|█████████▎| 7886/8455 [10:16<01:07,  8.44it/s]

Preprocessing:  93%|█████████▎| 7887/8455 [10:17<01:06,  8.56it/s]

Preprocessing:  93%|█████████▎| 7888/8455 [10:17<01:06,  8.51it/s]

Preprocessing:  93%|█████████▎| 7890/8455 [10:17<00:59,  9.46it/s]

Preprocessing:  93%|█████████▎| 7892/8455 [10:17<00:55, 10.20it/s]

Preprocessing:  93%|█████████▎| 7894/8455 [10:17<00:56,  9.87it/s]

Preprocessing:  93%|█████████▎| 7895/8455 [10:17<00:58,  9.63it/s]

Preprocessing:  93%|█████████▎| 7896/8455 [10:17<00:57,  9.64it/s]

Preprocessing:  93%|█████████▎| 7898/8455 [10:18<00:55, 10.05it/s]

Preprocessing:  93%|█████████▎| 7900/8455 [10:18<00:52, 10.65it/s]

Preprocessing:  93%|█████████▎| 7902/8455 [10:18<00:55, 10.04it/s]

Preprocessing:  93%|█████████▎| 7904/8455 [10:18<00:55,  9.88it/s]

Preprocessing:  94%|█████████▎| 7906/8455 [10:18<00:54, 10.01it/s]

Preprocessing:  94%|█████████▎| 7908/8455 [10:19<00:57,  9.44it/s]

Preprocessing:  94%|█████████▎| 7909/8455 [10:19<00:57,  9.52it/s]

Preprocessing:  94%|█████████▎| 7911/8455 [10:19<00:55,  9.88it/s]

Preprocessing:  94%|█████████▎| 7913/8455 [10:19<00:53, 10.19it/s]

Preprocessing:  94%|█████████▎| 7915/8455 [10:19<00:53, 10.09it/s]

Preprocessing:  94%|█████████▎| 7917/8455 [10:19<00:50, 10.61it/s]

Preprocessing:  94%|█████████▎| 7919/8455 [10:20<00:50, 10.67it/s]

Preprocessing:  94%|█████████▎| 7921/8455 [10:20<00:50, 10.64it/s]

Preprocessing:  94%|█████████▎| 7923/8455 [10:20<00:50, 10.61it/s]

Preprocessing:  94%|█████████▎| 7925/8455 [10:20<00:50, 10.45it/s]

Preprocessing:  94%|█████████▍| 7927/8455 [10:20<00:48, 10.78it/s]

Preprocessing:  94%|█████████▍| 7929/8455 [10:21<00:46, 11.43it/s]

Preprocessing:  94%|█████████▍| 7931/8455 [10:21<00:45, 11.51it/s]

Preprocessing:  94%|█████████▍| 7933/8455 [10:21<00:46, 11.26it/s]

Preprocessing:  94%|█████████▍| 7935/8455 [10:21<00:45, 11.50it/s]

Preprocessing:  94%|█████████▍| 7937/8455 [10:21<00:45, 11.37it/s]

Preprocessing:  94%|█████████▍| 7939/8455 [10:21<00:45, 11.44it/s]

Preprocessing:  94%|█████████▍| 7941/8455 [10:22<00:46, 11.11it/s]

Preprocessing:  94%|█████████▍| 7943/8455 [10:22<00:48, 10.54it/s]

Preprocessing:  94%|█████████▍| 7945/8455 [10:22<00:52,  9.69it/s]

Preprocessing:  94%|█████████▍| 7946/8455 [10:22<00:54,  9.35it/s]

Preprocessing:  94%|█████████▍| 7947/8455 [10:22<00:55,  9.13it/s]

Preprocessing:  94%|█████████▍| 7948/8455 [10:22<00:56,  8.94it/s]

Preprocessing:  94%|█████████▍| 7950/8455 [10:23<00:52,  9.55it/s]

Preprocessing:  94%|█████████▍| 7952/8455 [10:23<00:50, 10.00it/s]

Preprocessing:  94%|█████████▍| 7953/8455 [10:23<00:53,  9.41it/s]

Preprocessing:  94%|█████████▍| 7954/8455 [10:23<00:55,  9.06it/s]

Preprocessing:  94%|█████████▍| 7955/8455 [10:23<00:58,  8.60it/s]

Preprocessing:  94%|█████████▍| 7957/8455 [10:23<00:55,  9.05it/s]

Preprocessing:  94%|█████████▍| 7958/8455 [10:24<00:54,  9.20it/s]

Preprocessing:  94%|█████████▍| 7959/8455 [10:24<00:54,  9.10it/s]

Preprocessing:  94%|█████████▍| 7960/8455 [10:24<00:55,  8.99it/s]

Preprocessing:  94%|█████████▍| 7961/8455 [10:24<00:57,  8.66it/s]

Preprocessing:  94%|█████████▍| 7962/8455 [10:24<00:58,  8.50it/s]

Preprocessing:  94%|█████████▍| 7963/8455 [10:24<01:03,  7.73it/s]

Preprocessing:  94%|█████████▍| 7965/8455 [10:24<01:00,  8.16it/s]

Preprocessing:  94%|█████████▍| 7967/8455 [10:25<00:52,  9.32it/s]

Preprocessing:  94%|█████████▍| 7968/8455 [10:25<00:53,  9.17it/s]

Preprocessing:  94%|█████████▍| 7969/8455 [10:25<00:54,  8.86it/s]

Preprocessing:  94%|█████████▍| 7970/8455 [10:25<00:56,  8.53it/s]

Preprocessing:  94%|█████████▍| 7971/8455 [10:25<00:57,  8.47it/s]

Preprocessing:  94%|█████████▍| 7973/8455 [10:25<00:51,  9.27it/s]

Preprocessing:  94%|█████████▍| 7974/8455 [10:25<00:52,  9.22it/s]

Preprocessing:  94%|█████████▍| 7975/8455 [10:25<00:54,  8.78it/s]

Preprocessing:  94%|█████████▍| 7976/8455 [10:26<00:55,  8.58it/s]

Preprocessing:  94%|█████████▍| 7977/8455 [10:26<00:57,  8.31it/s]

Preprocessing:  94%|█████████▍| 7978/8455 [10:26<00:59,  8.04it/s]

Preprocessing:  94%|█████████▍| 7980/8455 [10:26<00:54,  8.64it/s]

Preprocessing:  94%|█████████▍| 7981/8455 [10:26<00:53,  8.91it/s]

Preprocessing:  94%|█████████▍| 7982/8455 [10:26<00:54,  8.70it/s]

Preprocessing:  94%|█████████▍| 7983/8455 [10:26<00:52,  8.96it/s]

Preprocessing:  94%|█████████▍| 7984/8455 [10:27<00:52,  8.90it/s]

Preprocessing:  94%|█████████▍| 7985/8455 [10:27<00:52,  9.02it/s]

Preprocessing:  94%|█████████▍| 7986/8455 [10:27<00:52,  8.96it/s]

Preprocessing:  94%|█████████▍| 7987/8455 [10:27<00:54,  8.63it/s]

Preprocessing:  94%|█████████▍| 7988/8455 [10:27<00:54,  8.53it/s]

Preprocessing:  94%|█████████▍| 7989/8455 [10:27<00:55,  8.38it/s]

Preprocessing:  95%|█████████▍| 7991/8455 [10:27<00:49,  9.34it/s]

Preprocessing:  95%|█████████▍| 7993/8455 [10:28<00:50,  9.20it/s]

Preprocessing:  95%|█████████▍| 7995/8455 [10:28<00:46,  9.94it/s]

Preprocessing:  95%|█████████▍| 7996/8455 [10:28<00:47,  9.58it/s]

Preprocessing:  95%|█████████▍| 7997/8455 [10:28<00:49,  9.23it/s]

Preprocessing:  95%|█████████▍| 7998/8455 [10:28<00:51,  8.80it/s]

Preprocessing:  95%|█████████▍| 7999/8455 [10:28<00:52,  8.64it/s]

Preprocessing:  95%|█████████▍| 8000/8455 [10:28<01:00,  7.53it/s]

Preprocessing:  95%|█████████▍| 8002/8455 [10:29<00:54,  8.36it/s]

Preprocessing:  95%|█████████▍| 8003/8455 [10:29<00:53,  8.48it/s]

Preprocessing:  95%|█████████▍| 8005/8455 [10:29<00:49,  9.04it/s]

Preprocessing:  95%|█████████▍| 8006/8455 [10:29<00:51,  8.76it/s]

Preprocessing:  95%|█████████▍| 8008/8455 [10:29<00:47,  9.48it/s]

Preprocessing:  95%|█████████▍| 8009/8455 [10:29<00:48,  9.21it/s]

Preprocessing:  95%|█████████▍| 8010/8455 [10:29<00:50,  8.82it/s]

Preprocessing:  95%|█████████▍| 8011/8455 [10:30<00:50,  8.78it/s]

Preprocessing:  95%|█████████▍| 8012/8455 [10:30<00:53,  8.34it/s]

Preprocessing:  95%|█████████▍| 8013/8455 [10:30<00:53,  8.30it/s]

Preprocessing:  95%|█████████▍| 8014/8455 [10:30<00:54,  8.15it/s]

Preprocessing:  95%|█████████▍| 8016/8455 [10:30<00:50,  8.71it/s]

Preprocessing:  95%|█████████▍| 8018/8455 [10:30<00:49,  8.79it/s]

Preprocessing:  95%|█████████▍| 8019/8455 [10:30<00:49,  8.73it/s]

Preprocessing:  95%|█████████▍| 8020/8455 [10:31<00:49,  8.85it/s]

Preprocessing:  95%|█████████▍| 8021/8455 [10:31<00:50,  8.64it/s]

Preprocessing:  95%|█████████▍| 8022/8455 [10:31<00:51,  8.45it/s]

Preprocessing:  95%|█████████▍| 8023/8455 [10:31<00:52,  8.22it/s]

Preprocessing:  95%|█████████▍| 8024/8455 [10:31<00:53,  8.06it/s]

Preprocessing:  95%|█████████▍| 8025/8455 [10:31<00:54,  7.83it/s]

Preprocessing:  95%|█████████▍| 8026/8455 [10:31<00:54,  7.84it/s]

Preprocessing:  95%|█████████▍| 8027/8455 [10:31<00:53,  7.98it/s]

Preprocessing:  95%|█████████▍| 8028/8455 [10:32<00:50,  8.42it/s]

Preprocessing:  95%|█████████▍| 8029/8455 [10:32<00:50,  8.40it/s]

Preprocessing:  95%|█████████▍| 8030/8455 [10:32<00:52,  8.04it/s]

Preprocessing:  95%|█████████▍| 8032/8455 [10:32<00:48,  8.75it/s]

Preprocessing:  95%|█████████▌| 8033/8455 [10:32<00:49,  8.45it/s]

Preprocessing:  95%|█████████▌| 8034/8455 [10:32<00:50,  8.31it/s]

Preprocessing:  95%|█████████▌| 8036/8455 [10:33<00:47,  8.80it/s]

Preprocessing:  95%|█████████▌| 8037/8455 [10:33<00:49,  8.45it/s]

Preprocessing:  95%|█████████▌| 8039/8455 [10:33<00:47,  8.74it/s]

Preprocessing:  95%|█████████▌| 8040/8455 [10:33<00:49,  8.45it/s]

Preprocessing:  95%|█████████▌| 8042/8455 [10:33<00:51,  8.06it/s]

Preprocessing:  95%|█████████▌| 8044/8455 [10:33<00:47,  8.66it/s]

Preprocessing:  95%|█████████▌| 8045/8455 [10:34<00:46,  8.90it/s]

Preprocessing:  95%|█████████▌| 8046/8455 [10:34<00:46,  8.80it/s]

Preprocessing:  95%|█████████▌| 8047/8455 [10:34<00:46,  8.72it/s]

Preprocessing:  95%|█████████▌| 8048/8455 [10:34<00:47,  8.51it/s]

Preprocessing:  95%|█████████▌| 8049/8455 [10:34<00:48,  8.37it/s]

Preprocessing:  95%|█████████▌| 8050/8455 [10:34<00:50,  7.95it/s]

Preprocessing:  95%|█████████▌| 8051/8455 [10:34<00:50,  8.00it/s]

Preprocessing:  95%|█████████▌| 8053/8455 [10:35<00:47,  8.50it/s]

Preprocessing:  95%|█████████▌| 8054/8455 [10:35<00:48,  8.31it/s]

Preprocessing:  95%|█████████▌| 8055/8455 [10:35<00:48,  8.16it/s]

Preprocessing:  95%|█████████▌| 8056/8455 [10:35<00:48,  8.21it/s]

Preprocessing:  95%|█████████▌| 8057/8455 [10:35<00:48,  8.18it/s]

Preprocessing:  95%|█████████▌| 8058/8455 [10:35<00:49,  7.99it/s]

Preprocessing:  95%|█████████▌| 8059/8455 [10:35<00:48,  8.12it/s]

Preprocessing:  95%|█████████▌| 8060/8455 [10:35<00:49,  8.00it/s]

Preprocessing:  95%|█████████▌| 8061/8455 [10:36<00:49,  8.02it/s]

Preprocessing:  95%|█████████▌| 8062/8455 [10:36<00:49,  7.99it/s]

Preprocessing:  95%|█████████▌| 8063/8455 [10:36<00:48,  8.06it/s]

Preprocessing:  95%|█████████▌| 8064/8455 [10:36<00:48,  8.09it/s]

Preprocessing:  95%|█████████▌| 8066/8455 [10:36<00:41,  9.46it/s]

Preprocessing:  95%|█████████▌| 8067/8455 [10:36<00:48,  8.02it/s]

Preprocessing:  95%|█████████▌| 8068/8455 [10:36<00:48,  7.93it/s]

Preprocessing:  95%|█████████▌| 8070/8455 [10:37<00:42,  9.07it/s]

Preprocessing:  95%|█████████▌| 8071/8455 [10:37<00:44,  8.55it/s]

Preprocessing:  95%|█████████▌| 8073/8455 [10:37<00:40,  9.44it/s]

Preprocessing:  95%|█████████▌| 8074/8455 [10:37<00:45,  8.41it/s]

Preprocessing:  96%|█████████▌| 8076/8455 [10:37<00:43,  8.75it/s]

Preprocessing:  96%|█████████▌| 8078/8455 [10:37<00:39,  9.50it/s]

Preprocessing:  96%|█████████▌| 8079/8455 [10:38<00:40,  9.26it/s]

Preprocessing:  96%|█████████▌| 8080/8455 [10:38<00:41,  9.04it/s]

Preprocessing:  96%|█████████▌| 8081/8455 [10:38<00:43,  8.65it/s]

Preprocessing:  96%|█████████▌| 8082/8455 [10:38<00:44,  8.40it/s]

Preprocessing:  96%|█████████▌| 8084/8455 [10:38<00:42,  8.68it/s]

Preprocessing:  96%|█████████▌| 8085/8455 [10:38<00:43,  8.55it/s]

Preprocessing:  96%|█████████▌| 8086/8455 [10:38<00:44,  8.30it/s]

Preprocessing:  96%|█████████▌| 8088/8455 [10:39<00:38,  9.50it/s]

Preprocessing:  96%|█████████▌| 8090/8455 [10:39<00:39,  9.14it/s]

Preprocessing:  96%|█████████▌| 8091/8455 [10:39<00:39,  9.14it/s]

Preprocessing:  96%|█████████▌| 8093/8455 [10:39<00:38,  9.31it/s]

Preprocessing:  96%|█████████▌| 8094/8455 [10:39<00:40,  8.88it/s]

Preprocessing:  96%|█████████▌| 8095/8455 [10:39<00:40,  8.84it/s]

Preprocessing:  96%|█████████▌| 8097/8455 [10:40<00:36,  9.88it/s]

Preprocessing:  96%|█████████▌| 8098/8455 [10:40<00:37,  9.52it/s]

Preprocessing:  96%|█████████▌| 8099/8455 [10:40<00:39,  8.91it/s]

Preprocessing:  96%|█████████▌| 8100/8455 [10:40<00:38,  9.11it/s]

Preprocessing:  96%|█████████▌| 8102/8455 [10:40<00:39,  9.05it/s]

Preprocessing:  96%|█████████▌| 8103/8455 [10:40<00:41,  8.57it/s]

Preprocessing:  96%|█████████▌| 8104/8455 [10:40<00:40,  8.74it/s]

Preprocessing:  96%|█████████▌| 8105/8455 [10:40<00:40,  8.57it/s]

Preprocessing:  96%|█████████▌| 8107/8455 [10:41<00:38,  9.13it/s]

Preprocessing:  96%|█████████▌| 8108/8455 [10:41<00:38,  8.98it/s]

Preprocessing:  96%|█████████▌| 8109/8455 [10:41<00:39,  8.78it/s]

Preprocessing:  96%|█████████▌| 8110/8455 [10:41<00:38,  9.06it/s]

Preprocessing:  96%|█████████▌| 8111/8455 [10:41<00:39,  8.62it/s]

Preprocessing:  96%|█████████▌| 8112/8455 [10:41<00:40,  8.37it/s]

Preprocessing:  96%|█████████▌| 8113/8455 [10:41<00:42,  8.05it/s]

Preprocessing:  96%|█████████▌| 8114/8455 [10:42<00:40,  8.49it/s]

Preprocessing:  96%|█████████▌| 8115/8455 [10:42<00:39,  8.63it/s]

Preprocessing:  96%|█████████▌| 8116/8455 [10:42<00:42,  8.05it/s]

Preprocessing:  96%|█████████▌| 8117/8455 [10:42<00:40,  8.27it/s]

Preprocessing:  96%|█████████▌| 8118/8455 [10:42<00:42,  7.96it/s]

Preprocessing:  96%|█████████▌| 8119/8455 [10:42<00:43,  7.65it/s]

Preprocessing:  96%|█████████▌| 8120/8455 [10:42<00:45,  7.37it/s]

Preprocessing:  96%|█████████▌| 8122/8455 [10:43<00:40,  8.14it/s]

Preprocessing:  96%|█████████▌| 8124/8455 [10:43<00:38,  8.52it/s]

Preprocessing:  96%|█████████▌| 8126/8455 [10:43<00:36,  9.04it/s]

Preprocessing:  96%|█████████▌| 8127/8455 [10:43<00:37,  8.80it/s]

Preprocessing:  96%|█████████▌| 8128/8455 [10:43<00:41,  7.79it/s]

Preprocessing:  96%|█████████▌| 8130/8455 [10:43<00:39,  8.24it/s]

Preprocessing:  96%|█████████▌| 8131/8455 [10:44<00:37,  8.55it/s]

Preprocessing:  96%|█████████▌| 8133/8455 [10:44<00:36,  8.72it/s]

Preprocessing:  96%|█████████▌| 8134/8455 [10:44<00:37,  8.47it/s]

Preprocessing:  96%|█████████▌| 8136/8455 [10:44<00:35,  9.06it/s]

Preprocessing:  96%|█████████▌| 8137/8455 [10:44<00:37,  8.50it/s]

Preprocessing:  96%|█████████▋| 8138/8455 [10:44<00:38,  8.23it/s]

Preprocessing:  96%|█████████▋| 8140/8455 [10:45<00:36,  8.59it/s]

Preprocessing:  96%|█████████▋| 8141/8455 [10:45<00:39,  7.94it/s]

Preprocessing:  96%|█████████▋| 8142/8455 [10:45<00:38,  8.21it/s]

Preprocessing:  96%|█████████▋| 8144/8455 [10:45<00:34,  9.08it/s]

Preprocessing:  96%|█████████▋| 8146/8455 [10:45<00:31,  9.91it/s]

Preprocessing:  96%|█████████▋| 8148/8455 [10:45<00:27, 11.00it/s]

Preprocessing:  96%|█████████▋| 8150/8455 [10:46<00:28, 10.70it/s]

Preprocessing:  96%|█████████▋| 8152/8455 [10:46<00:29, 10.20it/s]

Preprocessing:  96%|█████████▋| 8154/8455 [10:46<00:28, 10.58it/s]

Preprocessing:  96%|█████████▋| 8156/8455 [10:46<00:27, 10.68it/s]

Preprocessing:  96%|█████████▋| 8158/8455 [10:46<00:31,  9.55it/s]

Preprocessing:  97%|█████████▋| 8160/8455 [10:47<00:27, 10.85it/s]

Preprocessing:  97%|█████████▋| 8162/8455 [10:47<00:24, 12.06it/s]

Preprocessing:  97%|█████████▋| 8164/8455 [10:47<00:23, 12.61it/s]

Preprocessing:  97%|█████████▋| 8166/8455 [10:47<00:21, 13.22it/s]

Preprocessing:  97%|█████████▋| 8168/8455 [10:47<00:22, 12.89it/s]

Preprocessing:  97%|█████████▋| 8170/8455 [10:47<00:26, 10.83it/s]

Preprocessing:  97%|█████████▋| 8172/8455 [10:48<00:27, 10.21it/s]

Preprocessing:  97%|█████████▋| 8174/8455 [10:48<00:27, 10.24it/s]

Preprocessing:  97%|█████████▋| 8176/8455 [10:48<00:27, 10.29it/s]

Preprocessing:  97%|█████████▋| 8178/8455 [10:48<00:27,  9.91it/s]

Preprocessing:  97%|█████████▋| 8180/8455 [10:48<00:27,  9.91it/s]

Preprocessing:  97%|█████████▋| 8182/8455 [10:49<00:26, 10.30it/s]

Preprocessing:  97%|█████████▋| 8184/8455 [10:49<00:25, 10.62it/s]

Preprocessing:  97%|█████████▋| 8186/8455 [10:49<00:24, 10.96it/s]

Preprocessing:  97%|█████████▋| 8188/8455 [10:49<00:24, 11.00it/s]

Preprocessing:  97%|█████████▋| 8190/8455 [10:49<00:23, 11.14it/s]

Preprocessing:  97%|█████████▋| 8192/8455 [10:49<00:23, 11.01it/s]

Preprocessing:  97%|█████████▋| 8194/8455 [10:50<00:24, 10.74it/s]

Preprocessing:  97%|█████████▋| 8196/8455 [10:50<00:24, 10.42it/s]

Preprocessing:  97%|█████████▋| 8198/8455 [10:50<00:24, 10.42it/s]

Preprocessing:  97%|█████████▋| 8200/8455 [10:50<00:24, 10.58it/s]

Preprocessing:  97%|█████████▋| 8202/8455 [10:50<00:23, 10.80it/s]

Preprocessing:  97%|█████████▋| 8204/8455 [10:51<00:23, 10.84it/s]

Preprocessing:  97%|█████████▋| 8206/8455 [10:51<00:24, 10.33it/s]

Preprocessing:  97%|█████████▋| 8208/8455 [10:51<00:25,  9.54it/s]

Preprocessing:  97%|█████████▋| 8209/8455 [10:51<00:26,  9.33it/s]

Preprocessing:  97%|█████████▋| 8210/8455 [10:51<00:27,  9.07it/s]

Preprocessing:  97%|█████████▋| 8211/8455 [10:51<00:26,  9.17it/s]

Preprocessing:  97%|█████████▋| 8213/8455 [10:52<00:25,  9.66it/s]

Preprocessing:  97%|█████████▋| 8214/8455 [10:52<00:24,  9.69it/s]

Preprocessing:  97%|█████████▋| 8215/8455 [10:52<00:25,  9.27it/s]

Preprocessing:  97%|█████████▋| 8217/8455 [10:52<00:25,  9.42it/s]

Preprocessing:  97%|█████████▋| 8218/8455 [10:52<00:25,  9.38it/s]

Preprocessing:  97%|█████████▋| 8220/8455 [10:52<00:22, 10.45it/s]

Preprocessing:  97%|█████████▋| 8222/8455 [10:52<00:20, 11.14it/s]

Preprocessing:  97%|█████████▋| 8224/8455 [10:53<00:21, 10.84it/s]

Preprocessing:  97%|█████████▋| 8226/8455 [10:53<00:20, 11.31it/s]

Preprocessing:  97%|█████████▋| 8228/8455 [10:53<00:20, 11.29it/s]

Preprocessing:  97%|█████████▋| 8230/8455 [10:53<00:19, 11.44it/s]

Preprocessing:  97%|█████████▋| 8232/8455 [10:53<00:19, 11.71it/s]

Preprocessing:  97%|█████████▋| 8234/8455 [10:54<00:21, 10.31it/s]

Preprocessing:  97%|█████████▋| 8236/8455 [10:54<00:22,  9.84it/s]

Preprocessing:  97%|█████████▋| 8238/8455 [10:54<00:22,  9.64it/s]

Preprocessing:  97%|█████████▋| 8240/8455 [10:54<00:21, 10.06it/s]

Preprocessing:  97%|█████████▋| 8242/8455 [10:54<00:19, 10.66it/s]

Preprocessing:  98%|█████████▊| 8244/8455 [10:54<00:18, 11.27it/s]

Preprocessing:  98%|█████████▊| 8246/8455 [10:55<00:17, 11.67it/s]

Preprocessing:  98%|█████████▊| 8248/8455 [10:55<00:17, 11.74it/s]

Preprocessing:  98%|█████████▊| 8250/8455 [10:55<00:17, 11.87it/s]

Preprocessing:  98%|█████████▊| 8252/8455 [10:55<00:16, 11.97it/s]

Preprocessing:  98%|█████████▊| 8254/8455 [10:55<00:16, 12.15it/s]

Preprocessing:  98%|█████████▊| 8256/8455 [10:56<00:17, 11.06it/s]

Preprocessing:  98%|█████████▊| 8258/8455 [10:56<00:18, 10.61it/s]

Preprocessing:  98%|█████████▊| 8260/8455 [10:56<00:18, 10.76it/s]

Preprocessing:  98%|█████████▊| 8262/8455 [10:56<00:19,  9.94it/s]

Preprocessing:  98%|█████████▊| 8264/8455 [10:56<00:19,  9.60it/s]

Preprocessing:  98%|█████████▊| 8265/8455 [10:56<00:20,  9.50it/s]

Preprocessing:  98%|█████████▊| 8266/8455 [10:57<00:20,  9.19it/s]

Preprocessing:  98%|█████████▊| 8268/8455 [10:57<00:19,  9.58it/s]

Preprocessing:  98%|█████████▊| 8269/8455 [10:57<00:19,  9.38it/s]

Preprocessing:  98%|█████████▊| 8270/8455 [10:57<00:20,  9.17it/s]

Preprocessing:  98%|█████████▊| 8271/8455 [10:57<00:19,  9.26it/s]

Preprocessing:  98%|█████████▊| 8273/8455 [10:57<00:17, 10.56it/s]

Preprocessing:  98%|█████████▊| 8275/8455 [10:57<00:17, 10.45it/s]

Preprocessing:  98%|█████████▊| 8277/8455 [10:58<00:16, 10.68it/s]

Preprocessing:  98%|█████████▊| 8279/8455 [10:58<00:17, 10.05it/s]

Preprocessing:  98%|█████████▊| 8281/8455 [10:58<00:17,  9.96it/s]

Preprocessing:  98%|█████████▊| 8283/8455 [10:58<00:17,  9.90it/s]

Preprocessing:  98%|█████████▊| 8285/8455 [10:58<00:16, 10.18it/s]

Preprocessing:  98%|█████████▊| 8287/8455 [10:59<00:15, 10.87it/s]

Preprocessing:  98%|█████████▊| 8289/8455 [10:59<00:16, 10.14it/s]

Preprocessing:  98%|█████████▊| 8291/8455 [10:59<00:16,  9.85it/s]

Preprocessing:  98%|█████████▊| 8293/8455 [10:59<00:17,  9.42it/s]

Preprocessing:  98%|█████████▊| 8295/8455 [11:00<00:16,  9.55it/s]

Preprocessing:  98%|█████████▊| 8297/8455 [11:00<00:15, 10.01it/s]

Preprocessing:  98%|█████████▊| 8299/8455 [11:00<00:14, 11.09it/s]

Preprocessing:  98%|█████████▊| 8301/8455 [11:00<00:12, 12.41it/s]

Preprocessing:  98%|█████████▊| 8303/8455 [11:00<00:11, 13.35it/s]

Preprocessing:  98%|█████████▊| 8305/8455 [11:00<00:11, 12.97it/s]

Preprocessing:  98%|█████████▊| 8307/8455 [11:00<00:12, 11.97it/s]

Preprocessing:  98%|█████████▊| 8309/8455 [11:01<00:11, 12.26it/s]

Preprocessing:  98%|█████████▊| 8311/8455 [11:01<00:13, 10.78it/s]

Preprocessing:  98%|█████████▊| 8313/8455 [11:01<00:13, 10.48it/s]

Preprocessing:  98%|█████████▊| 8315/8455 [11:01<00:14,  9.42it/s]

Preprocessing:  98%|█████████▊| 8316/8455 [11:01<00:15,  9.24it/s]

Preprocessing:  98%|█████████▊| 8318/8455 [11:02<00:13,  9.89it/s]

Preprocessing:  98%|█████████▊| 8320/8455 [11:02<00:13, 10.09it/s]

Preprocessing:  98%|█████████▊| 8322/8455 [11:02<00:13,  9.96it/s]

Preprocessing:  98%|█████████▊| 8324/8455 [11:02<00:13,  9.52it/s]

Preprocessing:  98%|█████████▊| 8325/8455 [11:02<00:14,  9.12it/s]

Preprocessing:  98%|█████████▊| 8326/8455 [11:02<00:14,  9.11it/s]

Preprocessing:  98%|█████████▊| 8328/8455 [11:03<00:13,  9.49it/s]

Preprocessing:  99%|█████████▊| 8330/8455 [11:03<00:12,  9.75it/s]

Preprocessing:  99%|█████████▊| 8331/8455 [11:03<00:12,  9.74it/s]

Preprocessing:  99%|█████████▊| 8333/8455 [11:03<00:11, 10.23it/s]

Preprocessing:  99%|█████████▊| 8335/8455 [11:03<00:12,  9.78it/s]

Preprocessing:  99%|█████████▊| 8337/8455 [11:04<00:11, 10.24it/s]

Preprocessing:  99%|█████████▊| 8339/8455 [11:04<00:10, 10.57it/s]

Preprocessing:  99%|█████████▊| 8341/8455 [11:04<00:10, 10.71it/s]

Preprocessing:  99%|█████████▊| 8343/8455 [11:04<00:11,  9.94it/s]

Preprocessing:  99%|█████████▊| 8345/8455 [11:04<00:11,  9.27it/s]

Preprocessing:  99%|█████████▊| 8346/8455 [11:04<00:11,  9.14it/s]

Preprocessing:  99%|█████████▊| 8347/8455 [11:05<00:11,  9.01it/s]

Preprocessing:  99%|█████████▊| 8349/8455 [11:05<00:11,  8.98it/s]

Preprocessing:  99%|█████████▉| 8350/8455 [11:05<00:11,  8.81it/s]

Preprocessing:  99%|█████████▉| 8351/8455 [11:05<00:11,  8.71it/s]

Preprocessing:  99%|█████████▉| 8352/8455 [11:05<00:12,  8.53it/s]

Preprocessing:  99%|█████████▉| 8354/8455 [11:05<00:11,  8.65it/s]

Preprocessing:  99%|█████████▉| 8356/8455 [11:06<00:11,  8.72it/s]

Preprocessing:  99%|█████████▉| 8357/8455 [11:06<00:12,  8.13it/s]

Preprocessing:  99%|█████████▉| 8359/8455 [11:06<00:11,  8.25it/s]

Preprocessing:  99%|█████████▉| 8360/8455 [11:06<00:11,  8.12it/s]

Preprocessing:  99%|█████████▉| 8361/8455 [11:06<00:12,  7.62it/s]

Preprocessing:  99%|█████████▉| 8363/8455 [11:07<00:11,  8.22it/s]

Preprocessing:  99%|█████████▉| 8365/8455 [11:07<00:09,  9.06it/s]

Preprocessing:  99%|█████████▉| 8367/8455 [11:07<00:09,  9.10it/s]

Preprocessing:  99%|█████████▉| 8368/8455 [11:07<00:09,  8.84it/s]

Preprocessing:  99%|█████████▉| 8369/8455 [11:07<00:09,  8.66it/s]

Preprocessing:  99%|█████████▉| 8370/8455 [11:07<00:10,  8.24it/s]

Preprocessing:  99%|█████████▉| 8372/8455 [11:07<00:09,  9.14it/s]

Preprocessing:  99%|█████████▉| 8374/8455 [11:08<00:08,  9.39it/s]

Preprocessing:  99%|█████████▉| 8375/8455 [11:08<00:08,  8.99it/s]

Preprocessing:  99%|█████████▉| 8377/8455 [11:08<00:08,  9.54it/s]

Preprocessing:  99%|█████████▉| 8379/8455 [11:08<00:07, 10.03it/s]

Preprocessing:  99%|█████████▉| 8380/8455 [11:08<00:08,  9.13it/s]

Preprocessing:  99%|█████████▉| 8382/8455 [11:09<00:07,  9.58it/s]

Preprocessing:  99%|█████████▉| 8383/8455 [11:09<00:07,  9.38it/s]

Preprocessing:  99%|█████████▉| 8385/8455 [11:09<00:06, 10.17it/s]

Preprocessing:  99%|█████████▉| 8386/8455 [11:09<00:07,  9.69it/s]

Preprocessing:  99%|█████████▉| 8387/8455 [11:09<00:07,  9.27it/s]

Preprocessing:  99%|█████████▉| 8388/8455 [11:09<00:07,  9.08it/s]

Preprocessing:  99%|█████████▉| 8389/8455 [11:09<00:07,  8.65it/s]

Preprocessing:  99%|█████████▉| 8391/8455 [11:09<00:06,  9.88it/s]

Preprocessing:  99%|█████████▉| 8393/8455 [11:10<00:06, 10.11it/s]

Preprocessing:  99%|█████████▉| 8394/8455 [11:10<00:06,  9.53it/s]

Preprocessing:  99%|█████████▉| 8396/8455 [11:10<00:05, 10.14it/s]

Preprocessing:  99%|█████████▉| 8397/8455 [11:10<00:06,  9.02it/s]

Preprocessing:  99%|█████████▉| 8399/8455 [11:10<00:05,  9.52it/s]

Preprocessing:  99%|█████████▉| 8401/8455 [11:11<00:05,  9.85it/s]

Preprocessing:  99%|█████████▉| 8402/8455 [11:11<00:05,  9.69it/s]

Preprocessing:  99%|█████████▉| 8403/8455 [11:11<00:05,  9.31it/s]

Preprocessing:  99%|█████████▉| 8405/8455 [11:11<00:05,  9.85it/s]

Preprocessing:  99%|█████████▉| 8406/8455 [11:11<00:05,  9.47it/s]

Preprocessing:  99%|█████████▉| 8407/8455 [11:11<00:05,  9.32it/s]

Preprocessing:  99%|█████████▉| 8408/8455 [11:11<00:05,  9.07it/s]

Preprocessing:  99%|█████████▉| 8409/8455 [11:11<00:05,  9.15it/s]

Preprocessing:  99%|█████████▉| 8410/8455 [11:11<00:05,  9.00it/s]

Preprocessing:  99%|█████████▉| 8411/8455 [11:12<00:04,  9.06it/s]

Preprocessing:  99%|█████████▉| 8412/8455 [11:12<00:04,  8.93it/s]

Preprocessing: 100%|█████████▉| 8413/8455 [11:12<00:04,  8.78it/s]

Preprocessing: 100%|█████████▉| 8415/8455 [11:12<00:04,  9.88it/s]

Preprocessing: 100%|█████████▉| 8416/8455 [11:12<00:04,  9.64it/s]

Preprocessing: 100%|█████████▉| 8417/8455 [11:12<00:04,  9.37it/s]

Preprocessing: 100%|█████████▉| 8418/8455 [11:12<00:04,  9.19it/s]

Preprocessing: 100%|█████████▉| 8419/8455 [11:12<00:03,  9.03it/s]

Preprocessing: 100%|█████████▉| 8420/8455 [11:13<00:03,  9.20it/s]

Preprocessing: 100%|█████████▉| 8421/8455 [11:13<00:03,  9.34it/s]

Preprocessing: 100%|█████████▉| 8423/8455 [11:13<00:03,  9.68it/s]

Preprocessing: 100%|█████████▉| 8425/8455 [11:13<00:02, 10.21it/s]

Preprocessing: 100%|█████████▉| 8427/8455 [11:13<00:02, 10.49it/s]

Preprocessing: 100%|█████████▉| 8429/8455 [11:13<00:02, 10.96it/s]

Preprocessing: 100%|█████████▉| 8431/8455 [11:14<00:02, 11.33it/s]

Preprocessing: 100%|█████████▉| 8433/8455 [11:14<00:01, 11.67it/s]

Preprocessing: 100%|█████████▉| 8435/8455 [11:14<00:01, 11.75it/s]

Preprocessing: 100%|█████████▉| 8437/8455 [11:14<00:01, 11.94it/s]

Preprocessing: 100%|█████████▉| 8439/8455 [11:14<00:01, 11.77it/s]

Preprocessing: 100%|█████████▉| 8441/8455 [11:14<00:01, 11.45it/s]

Preprocessing: 100%|█████████▉| 8443/8455 [11:15<00:01, 10.88it/s]

Preprocessing: 100%|█████████▉| 8445/8455 [11:15<00:00, 10.30it/s]

Preprocessing: 100%|█████████▉| 8447/8455 [11:15<00:00,  9.93it/s]

Preprocessing: 100%|█████████▉| 8449/8455 [11:15<00:00,  9.16it/s]

Preprocessing: 100%|█████████▉| 8450/8455 [11:16<00:00,  7.97it/s]

Preprocessing: 100%|█████████▉| 8452/8455 [11:16<00:00,  8.50it/s]

Preprocessing: 100%|█████████▉| 8453/8455 [11:16<00:00,  8.18it/s]

Preprocessing: 100%|█████████▉| 8454/8455 [11:16<00:00,  8.01it/s]

Preprocessing: 100%|██████████| 8455/8455 [11:16<00:00,  7.88it/s]

Preprocessing: 100%|██████████| 8455/8455 [11:16<00:00, 12.50it/s]

## Visualisasi Preprocessing Bertahap

Melihat efek dari setiap tahapan preprocessing secara bertahap.

In [ ]:
# Visualisasi Preprocessing Bertahap secara otomatis untuk semua tahapan
visualize_pipeline_steps(images, labels, PIPELINE)

In [5]:
# Konversi hasil preprocessing ke grayscale khusus untuk ekstraksi fitur GLCM & LBP
print("Mengonversi gambar preprocessed ke grayscale...")
images_preprocessed = np.array([
    cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) for img in tqdm(images_preprocessed_color, desc="Converting to grayscale")
])

Mengonversi gambar preprocessed ke grayscale...

Converting to grayscale:   0%|          | 0/8455 [00:00<?, ?it/s]

Converting to grayscale:   1%|▏         | 123/8455 [00:00<00:06, 1227.83it/s]

Converting to grayscale:   3%|▎         | 263/8455 [00:00<00:06, 1321.23it/s]

Converting to grayscale:   5%|▍         | 396/8455 [00:00<00:06, 1225.49it/s]

Converting to grayscale:   6%|▋         | 545/8455 [00:00<00:06, 1314.26it/s]

Converting to grayscale:  10%|▉         | 831/8455 [00:00<00:04, 1837.19it/s]

Converting to grayscale:  20%|█▉        | 1681/8455 [00:00<00:01, 4014.39it/s]

Converting to grayscale:  31%|███       | 2602/8455 [00:00<00:01, 5644.83it/s]

Converting to grayscale:  40%|████      | 3413/8455 [00:00<00:00, 6402.28it/s]

Converting to grayscale:  51%|█████     | 4310/8455 [00:00<00:00, 7182.72it/s]

Converting to grayscale:  62%|██████▏   | 5202/8455 [00:01<00:00, 7708.77it/s]

Converting to grayscale:  72%|███████▏  | 6078/8455 [00:01<00:00, 8020.22it/s]

Converting to grayscale:  83%|████████▎ | 6996/8455 [00:01<00:00, 8355.17it/s]

Converting to grayscale:  94%|█████████▎| 7907/8455 [00:01<00:00, 8532.69it/s]

Converting to grayscale: 100%|██████████| 8455/8455 [00:01<00:00, 6081.26it/s]

## Feature Extraction - Color & Texture

Kita mengekstrak:
- **HSV Color Stats & Histograms**
- **NRBR Color Stats & Histograms**
- **LBP Texture Histograms**
- **GLCM Texture Features**

In [6]:
# Ekstrasi Fitur Warna HSV
print("Mengekstrak fitur HSV...")
h_hists, s_hists, v_hists, \
h_means, h_stds, h_skews, h_kurts, \
s_means, s_stds, s_skews, s_kurts, \
v_means, v_stds, v_skews, v_kurts = extract_hsv_features(images_preprocessed_color)

# Ekstraksi Fitur Warna NRBR (Normalized Red-Blue Ratio)
print("Mengekstrak fitur NRBR...")
nrbr_hists, nrbr_means, nrbr_stds, nrbr_skews, nrbr_kurts = extract_nrbr_features(images_preprocessed_color)

# Ekstraksi Fitur Tekstur LBP (Local Binary Pattern)
print("Mengekstrak fitur LBP...")
lbp_hists = extract_lbp_features(images_preprocessed, bins=8)

Mengekstrak fitur HSV...

Mengekstrak fitur NRBR...

Mengekstrak fitur LBP...

In [7]:
# Ekstraksi Fitur Tekstur GLCM
def glcm(image, angle):
    if angle == 0:
        angles = [0]
    elif angle == 45:
        angles = [np.pi / 4]
    elif angle == 90:
        angles = [np.pi / 2]
    elif angle == 135:
        angles = [3 * np.pi / 4]
    else:
        raise ValueError("Sudut tidak valid. Gunakan 0, 45, 90, atau 135.")
    return graycomatrix(image, [1], angles, 256, symmetric=True, normed=True)

def correlation(matriks):
    return graycoprops(matriks, 'correlation')[0, 0]
def dissimilarity(matriks):
    return graycoprops(matriks, 'dissimilarity')[0, 0]
def homogenity(matriks):
    return graycoprops(matriks, 'homogeneity')[0, 0]
def contrast(matriks):
    return graycoprops(matriks, 'contrast')[0, 0]
def ASM(matriks):
    return graycoprops(matriks, 'ASM')[0, 0]
def energy(matriks):
    return graycoprops(matriks, 'energy')[0, 0]
def entropyGlcm(matriks):
    return entropy(matriks.ravel())

Kontras0, Kontras45, Kontras90, Kontras135 = [], [], [], []
dissimilarity0, dissimilarity45, dissimilarity90, dissimilarity135 = [], [], [], []
homogenity0, homogenity45, homogenity90, homogenity135 = [], [], [], []
entropy0, entropy45, entropy90, entropy135 = [], [], [], []
ASM0, ASM45, ASM90, ASM135 = [], [], [], []
energy0, energy45, energy90, energy135 = [], [], [], []
correlation0, correlation45, correlation90, correlation135 = [], [], [], []

for i in tqdm(range(len(images_preprocessed)), desc="Extracting GLCM features"):
    g0 = glcm(images_preprocessed[i], 0)
    g45 = glcm(images_preprocessed[i], 45)
    g90 = glcm(images_preprocessed[i], 90)
    g135 = glcm(images_preprocessed[i], 135)
    
    Kontras0.append(contrast(g0))
    Kontras45.append(contrast(g45))
    Kontras90.append(contrast(g90))
    Kontras135.append(contrast(g135))
    
    dissimilarity0.append(dissimilarity(g0))
    dissimilarity45.append(dissimilarity(g45))
    dissimilarity90.append(dissimilarity(g90))
    dissimilarity135.append(dissimilarity(g135))
    
    homogenity0.append(homogenity(g0))
    homogenity45.append(homogenity(g45))
    homogenity90.append(homogenity(g90))
    homogenity135.append(homogenity(g135))
    
    entropy0.append(entropyGlcm(g0))
    entropy45.append(entropyGlcm(g45))
    entropy90.append(entropyGlcm(g90))
    entropy135.append(entropyGlcm(g135))
    
    ASM0.append(ASM(g0))
    ASM45.append(ASM(g45))
    ASM90.append(ASM(g90))
    ASM135.append(ASM(g135))
    
    energy0.append(energy(g0))
    energy45.append(energy(g45))
    energy90.append(energy(g90))
    energy135.append(energy(g135))
    
    correlation0.append(correlation(g0))
    correlation45.append(correlation(g45))
    correlation90.append(correlation(g90))
    correlation135.append(correlation(g135))

Extracting GLCM features:   0%|          | 0/8455 [00:00<?, ?it/s]

Extracting GLCM features:   0%|          | 4/8455 [00:00<03:42, 38.02it/s]

Extracting GLCM features:   0%|          | 9/8455 [00:00<03:39, 38.51it/s]

Extracting GLCM features:   0%|          | 14/8455 [00:00<03:15, 43.07it/s]

Extracting GLCM features:   0%|          | 20/8455 [00:00<02:57, 47.47it/s]

Extracting GLCM features:   0%|          | 25/8455 [00:00<02:58, 47.13it/s]

Extracting GLCM features:   0%|          | 30/8455 [00:00<03:36, 38.87it/s]

Extracting GLCM features:   0%|          | 36/8455 [00:00<03:13, 43.61it/s]

Extracting GLCM features:   0%|          | 42/8455 [00:00<02:58, 47.08it/s]

Extracting GLCM features:   1%|          | 47/8455 [00:01<03:00, 46.70it/s]

Extracting GLCM features:   1%|          | 52/8455 [00:01<03:17, 42.57it/s]

Extracting GLCM features:   1%|          | 57/8455 [00:01<03:08, 44.44it/s]

Extracting GLCM features:   1%|          | 62/8455 [00:01<03:04, 45.56it/s]

Extracting GLCM features:   1%|          | 67/8455 [00:01<03:04, 45.40it/s]

Extracting GLCM features:   1%|          | 73/8455 [00:01<02:57, 47.19it/s]

Extracting GLCM features:   1%|          | 78/8455 [00:01<03:27, 40.36it/s]

Extracting GLCM features:   1%|          | 84/8455 [00:01<03:13, 43.30it/s]

Extracting GLCM features:   1%|          | 89/8455 [00:02<03:11, 43.76it/s]

Extracting GLCM features:   1%|          | 94/8455 [00:02<03:10, 43.90it/s]

Extracting GLCM features:   1%|          | 99/8455 [00:02<03:11, 43.54it/s]

Extracting GLCM features:   1%|          | 105/8455 [00:02<03:03, 45.49it/s]

Extracting GLCM features:   1%|▏         | 110/8455 [00:02<03:19, 41.90it/s]

Extracting GLCM features:   1%|▏         | 115/8455 [00:02<03:17, 42.30it/s]

Extracting GLCM features:   1%|▏         | 120/8455 [00:02<03:19, 41.82it/s]

Extracting GLCM features:   1%|▏         | 125/8455 [00:02<03:23, 40.91it/s]

Extracting GLCM features:   2%|▏         | 131/8455 [00:03<03:12, 43.15it/s]

Extracting GLCM features:   2%|▏         | 137/8455 [00:03<02:57, 46.99it/s]

Extracting GLCM features:   2%|▏         | 142/8455 [00:03<03:09, 43.77it/s]

Extracting GLCM features:   2%|▏         | 148/8455 [00:03<03:00, 46.04it/s]

Extracting GLCM features:   2%|▏         | 153/8455 [00:03<02:58, 46.52it/s]

Extracting GLCM features:   2%|▏         | 158/8455 [00:03<02:55, 47.21it/s]

Extracting GLCM features:   2%|▏         | 163/8455 [00:03<02:54, 47.63it/s]

Extracting GLCM features:   2%|▏         | 169/8455 [00:03<02:43, 50.82it/s]

Extracting GLCM features:   2%|▏         | 176/8455 [00:03<02:33, 53.79it/s]

Extracting GLCM features:   2%|▏         | 182/8455 [00:04<02:52, 47.84it/s]

Extracting GLCM features:   2%|▏         | 188/8455 [00:04<02:43, 50.45it/s]

Extracting GLCM features:   2%|▏         | 194/8455 [00:04<02:38, 52.28it/s]

Extracting GLCM features:   2%|▏         | 200/8455 [00:04<02:37, 52.57it/s]

Extracting GLCM features:   2%|▏         | 206/8455 [00:04<02:58, 46.30it/s]

Extracting GLCM features:   3%|▎         | 212/8455 [00:04<02:51, 47.95it/s]

Extracting GLCM features:   3%|▎         | 218/8455 [00:04<02:42, 50.81it/s]

Extracting GLCM features:   3%|▎         | 224/8455 [00:04<02:34, 53.19it/s]

Extracting GLCM features:   3%|▎         | 231/8455 [00:04<02:28, 55.35it/s]

Extracting GLCM features:   3%|▎         | 237/8455 [00:05<02:45, 49.66it/s]

Extracting GLCM features:   3%|▎         | 243/8455 [00:05<02:50, 48.30it/s]

Extracting GLCM features:   3%|▎         | 248/8455 [00:05<02:48, 48.67it/s]

Extracting GLCM features:   3%|▎         | 254/8455 [00:05<02:40, 51.10it/s]

Extracting GLCM features:   3%|▎         | 260/8455 [00:05<02:38, 51.72it/s]

Extracting GLCM features:   3%|▎         | 266/8455 [00:05<02:43, 50.09it/s]

Extracting GLCM features:   3%|▎         | 272/8455 [00:05<02:49, 48.20it/s]

Extracting GLCM features:   3%|▎         | 279/8455 [00:05<02:37, 51.87it/s]

Extracting GLCM features:   3%|▎         | 285/8455 [00:06<02:38, 51.40it/s]

Extracting GLCM features:   3%|▎         | 291/8455 [00:06<02:35, 52.34it/s]

Extracting GLCM features:   4%|▎         | 297/8455 [00:06<02:36, 52.12it/s]

Extracting GLCM features:   4%|▎         | 303/8455 [00:06<02:34, 52.73it/s]

Extracting GLCM features:   4%|▎         | 309/8455 [00:06<02:35, 52.47it/s]

Extracting GLCM features:   4%|▎         | 315/8455 [00:06<02:34, 52.76it/s]

Extracting GLCM features:   4%|▍         | 322/8455 [00:06<02:29, 54.54it/s]

Extracting GLCM features:   4%|▍         | 328/8455 [00:06<02:27, 54.99it/s]

Extracting GLCM features:   4%|▍         | 334/8455 [00:06<02:27, 55.04it/s]

Extracting GLCM features:   4%|▍         | 340/8455 [00:07<02:30, 53.88it/s]

Extracting GLCM features:   4%|▍         | 346/8455 [00:07<02:32, 53.27it/s]

Extracting GLCM features:   4%|▍         | 352/8455 [00:07<02:36, 51.83it/s]

Extracting GLCM features:   4%|▍         | 358/8455 [00:07<02:40, 50.42it/s]

Extracting GLCM features:   4%|▍         | 364/8455 [00:07<02:40, 50.30it/s]

Extracting GLCM features:   4%|▍         | 370/8455 [00:07<02:34, 52.27it/s]

Extracting GLCM features:   4%|▍         | 376/8455 [00:07<02:29, 54.18it/s]

Extracting GLCM features:   5%|▍         | 383/8455 [00:07<02:22, 56.83it/s]

Extracting GLCM features:   5%|▍         | 389/8455 [00:07<02:20, 57.39it/s]

Extracting GLCM features:   5%|▍         | 395/8455 [00:08<02:23, 56.19it/s]

Extracting GLCM features:   5%|▍         | 401/8455 [00:08<02:29, 53.89it/s]

Extracting GLCM features:   5%|▍         | 407/8455 [00:08<02:41, 49.74it/s]

Extracting GLCM features:   5%|▍         | 413/8455 [00:08<02:40, 50.20it/s]

Extracting GLCM features:   5%|▍         | 419/8455 [00:08<02:40, 50.20it/s]

Extracting GLCM features:   5%|▌         | 425/8455 [00:08<02:42, 49.36it/s]

Extracting GLCM features:   5%|▌         | 431/8455 [00:08<02:42, 49.32it/s]

Extracting GLCM features:   5%|▌         | 437/8455 [00:08<02:41, 49.55it/s]

Extracting GLCM features:   5%|▌         | 442/8455 [00:09<02:48, 47.64it/s]

Extracting GLCM features:   5%|▌         | 448/8455 [00:09<02:43, 49.07it/s]

Extracting GLCM features:   5%|▌         | 454/8455 [00:09<02:37, 50.69it/s]

Extracting GLCM features:   5%|▌         | 460/8455 [00:09<02:38, 50.47it/s]

Extracting GLCM features:   6%|▌         | 466/8455 [00:09<02:40, 49.90it/s]

Extracting GLCM features:   6%|▌         | 471/8455 [00:09<02:42, 49.25it/s]

Extracting GLCM features:   6%|▌         | 477/8455 [00:09<02:34, 51.62it/s]

Extracting GLCM features:   6%|▌         | 483/8455 [00:09<02:30, 52.82it/s]

Extracting GLCM features:   6%|▌         | 489/8455 [00:09<02:25, 54.82it/s]

Extracting GLCM features:   6%|▌         | 495/8455 [00:10<02:25, 54.76it/s]

Extracting GLCM features:   6%|▌         | 501/8455 [00:10<02:23, 55.39it/s]

Extracting GLCM features:   6%|▌         | 507/8455 [00:10<02:23, 55.52it/s]

Extracting GLCM features:   6%|▌         | 513/8455 [00:10<02:26, 54.17it/s]

Extracting GLCM features:   6%|▌         | 519/8455 [00:10<02:24, 55.10it/s]

Extracting GLCM features:   6%|▌         | 525/8455 [00:10<02:24, 55.07it/s]

Extracting GLCM features:   6%|▋         | 531/8455 [00:10<02:23, 55.15it/s]

Extracting GLCM features:   6%|▋         | 537/8455 [00:10<02:21, 55.79it/s]

Extracting GLCM features:   6%|▋         | 543/8455 [00:10<02:19, 56.70it/s]

Extracting GLCM features:   6%|▋         | 549/8455 [00:11<02:33, 51.37it/s]

Extracting GLCM features:   7%|▋         | 555/8455 [00:11<02:31, 52.11it/s]

Extracting GLCM features:   7%|▋         | 561/8455 [00:11<02:28, 53.09it/s]

Extracting GLCM features:   7%|▋         | 567/8455 [00:11<02:43, 48.36it/s]

Extracting GLCM features:   7%|▋         | 573/8455 [00:11<02:40, 48.99it/s]

Extracting GLCM features:   7%|▋         | 579/8455 [00:11<02:32, 51.54it/s]

Extracting GLCM features:   7%|▋         | 585/8455 [00:11<02:27, 53.32it/s]

Extracting GLCM features:   7%|▋         | 591/8455 [00:11<02:24, 54.30it/s]

Extracting GLCM features:   7%|▋         | 597/8455 [00:11<02:21, 55.35it/s]

Extracting GLCM features:   7%|▋         | 603/8455 [00:12<02:23, 54.62it/s]

Extracting GLCM features:   7%|▋         | 609/8455 [00:12<02:23, 54.72it/s]

Extracting GLCM features:   7%|▋         | 616/8455 [00:12<02:19, 56.30it/s]

Extracting GLCM features:   7%|▋         | 622/8455 [00:12<02:23, 54.77it/s]

Extracting GLCM features:   7%|▋         | 628/8455 [00:12<02:24, 54.27it/s]

Extracting GLCM features:   7%|▋         | 634/8455 [00:12<02:24, 54.23it/s]

Extracting GLCM features:   8%|▊         | 640/8455 [00:12<02:21, 55.18it/s]

Extracting GLCM features:   8%|▊         | 647/8455 [00:12<02:16, 57.12it/s]

Extracting GLCM features:   8%|▊         | 653/8455 [00:12<02:17, 56.69it/s]

Extracting GLCM features:   8%|▊         | 659/8455 [00:13<02:17, 56.64it/s]

Extracting GLCM features:   8%|▊         | 665/8455 [00:13<02:19, 56.04it/s]

Extracting GLCM features:   8%|▊         | 672/8455 [00:13<02:17, 56.50it/s]

Extracting GLCM features:   8%|▊         | 678/8455 [00:13<02:17, 56.76it/s]

Extracting GLCM features:   8%|▊         | 684/8455 [00:13<02:21, 54.95it/s]

Extracting GLCM features:   8%|▊         | 690/8455 [00:13<02:19, 55.81it/s]

Extracting GLCM features:   8%|▊         | 696/8455 [00:13<02:41, 48.02it/s]

Extracting GLCM features:   8%|▊         | 702/8455 [00:13<02:33, 50.56it/s]

Extracting GLCM features:   8%|▊         | 708/8455 [00:14<02:29, 51.74it/s]

Extracting GLCM features:   8%|▊         | 714/8455 [00:14<02:26, 53.00it/s]

Extracting GLCM features:   9%|▊         | 720/8455 [00:14<02:29, 51.72it/s]

Extracting GLCM features:   9%|▊         | 726/8455 [00:14<02:36, 49.53it/s]

Extracting GLCM features:   9%|▊         | 732/8455 [00:14<02:33, 50.39it/s]

Extracting GLCM features:   9%|▊         | 738/8455 [00:14<02:32, 50.58it/s]

Extracting GLCM features:   9%|▉         | 744/8455 [00:14<02:28, 51.81it/s]

Extracting GLCM features:   9%|▉         | 751/8455 [00:14<02:21, 54.45it/s]

Extracting GLCM features:   9%|▉         | 757/8455 [00:14<02:19, 55.14it/s]

Extracting GLCM features:   9%|▉         | 763/8455 [00:15<02:22, 54.06it/s]

Extracting GLCM features:   9%|▉         | 769/8455 [00:15<02:20, 54.64it/s]

Extracting GLCM features:   9%|▉         | 775/8455 [00:15<02:20, 54.76it/s]

Extracting GLCM features:   9%|▉         | 781/8455 [00:15<02:21, 54.07it/s]

Extracting GLCM features:   9%|▉         | 787/8455 [00:15<02:22, 53.70it/s]

Extracting GLCM features:   9%|▉         | 793/8455 [00:15<02:24, 52.94it/s]

Extracting GLCM features:   9%|▉         | 799/8455 [00:15<02:26, 52.27it/s]

Extracting GLCM features:  10%|▉         | 805/8455 [00:15<02:22, 53.84it/s]

Extracting GLCM features:  10%|▉         | 811/8455 [00:15<02:19, 54.66it/s]

Extracting GLCM features:  10%|▉         | 817/8455 [00:16<02:25, 52.52it/s]

Extracting GLCM features:  10%|▉         | 823/8455 [00:16<02:24, 52.85it/s]

Extracting GLCM features:  10%|▉         | 829/8455 [00:16<02:19, 54.66it/s]

Extracting GLCM features:  10%|▉         | 835/8455 [00:16<02:19, 54.49it/s]

Extracting GLCM features:  10%|▉         | 841/8455 [00:16<02:20, 54.23it/s]

Extracting GLCM features:  10%|█         | 847/8455 [00:16<02:21, 53.91it/s]

Extracting GLCM features:  10%|█         | 853/8455 [00:16<02:18, 54.87it/s]

Extracting GLCM features:  10%|█         | 859/8455 [00:16<02:18, 54.82it/s]

Extracting GLCM features:  10%|█         | 866/8455 [00:16<02:15, 56.13it/s]

Extracting GLCM features:  10%|█         | 872/8455 [00:17<02:16, 55.49it/s]

Extracting GLCM features:  10%|█         | 878/8455 [00:17<02:21, 53.71it/s]

Extracting GLCM features:  10%|█         | 884/8455 [00:17<02:25, 52.18it/s]

Extracting GLCM features:  11%|█         | 890/8455 [00:17<02:34, 49.11it/s]

Extracting GLCM features:  11%|█         | 895/8455 [00:17<02:45, 45.72it/s]

Extracting GLCM features:  11%|█         | 901/8455 [00:17<02:39, 47.34it/s]

Extracting GLCM features:  11%|█         | 907/8455 [00:17<02:30, 50.08it/s]

Extracting GLCM features:  11%|█         | 913/8455 [00:17<02:23, 52.46it/s]

Extracting GLCM features:  11%|█         | 919/8455 [00:18<02:25, 51.91it/s]

Extracting GLCM features:  11%|█         | 925/8455 [00:18<02:22, 52.82it/s]

Extracting GLCM features:  11%|█         | 931/8455 [00:18<02:23, 52.39it/s]

Extracting GLCM features:  11%|█         | 937/8455 [00:18<02:29, 50.34it/s]

Extracting GLCM features:  11%|█         | 943/8455 [00:18<02:37, 47.66it/s]

Extracting GLCM features:  11%|█         | 949/8455 [00:18<02:33, 49.04it/s]

Extracting GLCM features:  11%|█▏        | 955/8455 [00:18<02:27, 50.68it/s]

Extracting GLCM features:  11%|█▏        | 961/8455 [00:18<02:25, 51.44it/s]

Extracting GLCM features:  11%|█▏        | 968/8455 [00:18<02:18, 53.97it/s]

Extracting GLCM features:  12%|█▏        | 974/8455 [00:19<02:21, 52.91it/s]

Extracting GLCM features:  12%|█▏        | 980/8455 [00:19<02:18, 53.79it/s]

Extracting GLCM features:  12%|█▏        | 986/8455 [00:19<02:34, 48.30it/s]

Extracting GLCM features:  12%|█▏        | 991/8455 [00:19<02:34, 48.30it/s]

Extracting GLCM features:  12%|█▏        | 996/8455 [00:19<02:44, 45.31it/s]

Extracting GLCM features:  12%|█▏        | 1001/8455 [00:19<02:42, 45.79it/s]

Extracting GLCM features:  12%|█▏        | 1006/8455 [00:19<02:48, 44.33it/s]

Extracting GLCM features:  12%|█▏        | 1013/8455 [00:19<02:33, 48.52it/s]

Extracting GLCM features:  12%|█▏        | 1018/8455 [00:20<02:34, 48.27it/s]

Extracting GLCM features:  12%|█▏        | 1023/8455 [00:20<02:42, 45.62it/s]

Extracting GLCM features:  12%|█▏        | 1029/8455 [00:20<02:32, 48.82it/s]

Extracting GLCM features:  12%|█▏        | 1034/8455 [00:20<02:37, 47.02it/s]

Extracting GLCM features:  12%|█▏        | 1040/8455 [00:20<02:31, 49.10it/s]

Extracting GLCM features:  12%|█▏        | 1046/8455 [00:20<02:27, 50.32it/s]

Extracting GLCM features:  12%|█▏        | 1052/8455 [00:20<02:21, 52.47it/s]

Extracting GLCM features:  13%|█▎        | 1059/8455 [00:20<02:13, 55.28it/s]

Extracting GLCM features:  13%|█▎        | 1066/8455 [00:20<02:09, 57.19it/s]

Extracting GLCM features:  13%|█▎        | 1072/8455 [00:21<02:22, 51.71it/s]

Extracting GLCM features:  13%|█▎        | 1078/8455 [00:21<02:23, 51.56it/s]

Extracting GLCM features:  13%|█▎        | 1084/8455 [00:21<02:29, 49.37it/s]

Extracting GLCM features:  13%|█▎        | 1089/8455 [00:21<02:32, 48.19it/s]

Extracting GLCM features:  13%|█▎        | 1094/8455 [00:21<02:33, 47.88it/s]

Extracting GLCM features:  13%|█▎        | 1099/8455 [00:21<02:32, 48.36it/s]

Extracting GLCM features:  13%|█▎        | 1105/8455 [00:21<02:25, 50.36it/s]

Extracting GLCM features:  13%|█▎        | 1112/8455 [00:21<02:18, 53.07it/s]

Extracting GLCM features:  13%|█▎        | 1119/8455 [00:22<02:15, 54.29it/s]

Extracting GLCM features:  13%|█▎        | 1125/8455 [00:22<02:12, 55.15it/s]

Extracting GLCM features:  13%|█▎        | 1131/8455 [00:22<02:14, 54.48it/s]

Extracting GLCM features:  13%|█▎        | 1138/8455 [00:22<02:10, 56.05it/s]

Extracting GLCM features:  14%|█▎        | 1144/8455 [00:22<02:09, 56.43it/s]

Extracting GLCM features:  14%|█▎        | 1150/8455 [00:22<02:12, 55.08it/s]

Extracting GLCM features:  14%|█▎        | 1156/8455 [00:22<02:10, 55.91it/s]

Extracting GLCM features:  14%|█▍        | 1163/8455 [00:22<02:05, 58.04it/s]

Extracting GLCM features:  14%|█▍        | 1169/8455 [00:22<02:18, 52.73it/s]

Extracting GLCM features:  14%|█▍        | 1175/8455 [00:23<02:17, 53.11it/s]

Extracting GLCM features:  14%|█▍        | 1181/8455 [00:23<02:12, 54.94it/s]

Extracting GLCM features:  14%|█▍        | 1187/8455 [00:23<02:11, 55.07it/s]

Extracting GLCM features:  14%|█▍        | 1193/8455 [00:23<02:14, 53.83it/s]

Extracting GLCM features:  14%|█▍        | 1199/8455 [00:23<02:17, 52.83it/s]

Extracting GLCM features:  14%|█▍        | 1205/8455 [00:23<02:20, 51.75it/s]

Extracting GLCM features:  14%|█▍        | 1211/8455 [00:23<02:18, 52.46it/s]

Extracting GLCM features:  14%|█▍        | 1217/8455 [00:23<02:13, 54.26it/s]

Extracting GLCM features:  14%|█▍        | 1223/8455 [00:23<02:10, 55.32it/s]

Extracting GLCM features:  15%|█▍        | 1229/8455 [00:24<02:11, 54.91it/s]

Extracting GLCM features:  15%|█▍        | 1235/8455 [00:24<02:18, 52.25it/s]

Extracting GLCM features:  15%|█▍        | 1241/8455 [00:24<02:19, 51.68it/s]

Extracting GLCM features:  15%|█▍        | 1247/8455 [00:24<02:19, 51.54it/s]

Extracting GLCM features:  15%|█▍        | 1253/8455 [00:24<02:23, 50.21it/s]

Extracting GLCM features:  15%|█▍        | 1259/8455 [00:24<02:24, 49.74it/s]

Extracting GLCM features:  15%|█▍        | 1265/8455 [00:24<02:19, 51.69it/s]

Extracting GLCM features:  15%|█▌        | 1272/8455 [00:24<02:11, 54.73it/s]

Extracting GLCM features:  15%|█▌        | 1278/8455 [00:24<02:10, 55.12it/s]

Extracting GLCM features:  15%|█▌        | 1284/8455 [00:25<02:13, 53.72it/s]

Extracting GLCM features:  15%|█▌        | 1290/8455 [00:25<02:14, 53.12it/s]

Extracting GLCM features:  15%|█▌        | 1296/8455 [00:25<02:12, 54.03it/s]

Extracting GLCM features:  15%|█▌        | 1302/8455 [00:25<02:10, 54.87it/s]

Extracting GLCM features:  15%|█▌        | 1308/8455 [00:25<02:11, 54.27it/s]

Extracting GLCM features:  16%|█▌        | 1314/8455 [00:25<02:12, 53.87it/s]

Extracting GLCM features:  16%|█▌        | 1320/8455 [00:25<02:10, 54.72it/s]

Extracting GLCM features:  16%|█▌        | 1326/8455 [00:25<02:08, 55.41it/s]

Extracting GLCM features:  16%|█▌        | 1332/8455 [00:25<02:07, 55.90it/s]

Extracting GLCM features:  16%|█▌        | 1338/8455 [00:26<02:13, 53.43it/s]

Extracting GLCM features:  16%|█▌        | 1344/8455 [00:26<02:10, 54.60it/s]

Extracting GLCM features:  16%|█▌        | 1351/8455 [00:26<02:06, 55.97it/s]

Extracting GLCM features:  16%|█▌        | 1357/8455 [00:26<02:06, 56.02it/s]

Extracting GLCM features:  16%|█▌        | 1363/8455 [00:26<02:04, 57.01it/s]

Extracting GLCM features:  16%|█▌        | 1369/8455 [00:26<02:09, 54.80it/s]

Extracting GLCM features:  16%|█▋        | 1375/8455 [00:26<02:07, 55.56it/s]

Extracting GLCM features:  16%|█▋        | 1381/8455 [00:26<02:06, 55.80it/s]

Extracting GLCM features:  16%|█▋        | 1388/8455 [00:26<02:01, 57.95it/s]

Extracting GLCM features:  16%|█▋        | 1394/8455 [00:27<02:04, 56.87it/s]

Extracting GLCM features:  17%|█▋        | 1400/8455 [00:27<02:05, 56.41it/s]

Extracting GLCM features:  17%|█▋        | 1406/8455 [00:27<02:05, 55.99it/s]

Extracting GLCM features:  17%|█▋        | 1412/8455 [00:27<02:08, 54.98it/s]

Extracting GLCM features:  17%|█▋        | 1418/8455 [00:27<02:18, 50.98it/s]

Extracting GLCM features:  17%|█▋        | 1424/8455 [00:27<02:16, 51.67it/s]

Extracting GLCM features:  17%|█▋        | 1430/8455 [00:27<02:12, 53.14it/s]

Extracting GLCM features:  17%|█▋        | 1436/8455 [00:27<02:11, 53.43it/s]

Extracting GLCM features:  17%|█▋        | 1443/8455 [00:27<02:04, 56.27it/s]

Extracting GLCM features:  17%|█▋        | 1449/8455 [00:28<02:09, 54.22it/s]

Extracting GLCM features:  17%|█▋        | 1455/8455 [00:28<02:09, 54.22it/s]

Extracting GLCM features:  17%|█▋        | 1461/8455 [00:28<02:13, 52.48it/s]

Extracting GLCM features:  17%|█▋        | 1467/8455 [00:28<02:21, 49.44it/s]

Extracting GLCM features:  17%|█▋        | 1472/8455 [00:28<02:25, 47.96it/s]

Extracting GLCM features:  17%|█▋        | 1477/8455 [00:28<02:23, 48.49it/s]

Extracting GLCM features:  18%|█▊        | 1483/8455 [00:28<02:18, 50.21it/s]

Extracting GLCM features:  18%|█▊        | 1489/8455 [00:28<02:12, 52.63it/s]

Extracting GLCM features:  18%|█▊        | 1495/8455 [00:29<02:33, 45.31it/s]

Extracting GLCM features:  18%|█▊        | 1500/8455 [00:29<02:33, 45.42it/s]

Extracting GLCM features:  18%|█▊        | 1505/8455 [00:29<02:38, 43.97it/s]

Extracting GLCM features:  18%|█▊        | 1510/8455 [00:29<02:45, 41.86it/s]

Extracting GLCM features:  18%|█▊        | 1515/8455 [00:29<02:47, 41.53it/s]

Extracting GLCM features:  18%|█▊        | 1521/8455 [00:29<02:33, 45.26it/s]

Extracting GLCM features:  18%|█▊        | 1527/8455 [00:29<02:22, 48.62it/s]

Extracting GLCM features:  18%|█▊        | 1533/8455 [00:29<02:16, 50.60it/s]

Extracting GLCM features:  18%|█▊        | 1539/8455 [00:30<02:19, 49.57it/s]

Extracting GLCM features:  18%|█▊        | 1545/8455 [00:30<02:20, 49.25it/s]

Extracting GLCM features:  18%|█▊        | 1551/8455 [00:30<02:21, 48.72it/s]

Extracting GLCM features:  18%|█▊        | 1556/8455 [00:30<02:21, 48.85it/s]

Extracting GLCM features:  18%|█▊        | 1561/8455 [00:30<02:31, 45.56it/s]

Extracting GLCM features:  19%|█▊        | 1566/8455 [00:30<02:40, 43.03it/s]

Extracting GLCM features:  19%|█▊        | 1571/8455 [00:30<02:53, 39.78it/s]

Extracting GLCM features:  19%|█▊        | 1576/8455 [00:30<02:54, 39.39it/s]

Extracting GLCM features:  19%|█▊        | 1581/8455 [00:31<02:50, 40.27it/s]

Extracting GLCM features:  19%|█▉        | 1586/8455 [00:31<02:57, 38.77it/s]

Extracting GLCM features:  19%|█▉        | 1590/8455 [00:31<03:02, 37.70it/s]

Extracting GLCM features:  19%|█▉        | 1594/8455 [00:31<03:04, 37.14it/s]

Extracting GLCM features:  19%|█▉        | 1598/8455 [00:31<03:04, 37.15it/s]

Extracting GLCM features:  19%|█▉        | 1602/8455 [00:31<03:06, 36.77it/s]

Extracting GLCM features:  19%|█▉        | 1606/8455 [00:31<03:06, 36.80it/s]

Extracting GLCM features:  19%|█▉        | 1611/8455 [00:31<02:59, 38.15it/s]

Extracting GLCM features:  19%|█▉        | 1615/8455 [00:31<03:05, 36.86it/s]

Extracting GLCM features:  19%|█▉        | 1619/8455 [00:32<03:04, 37.01it/s]

Extracting GLCM features:  19%|█▉        | 1624/8455 [00:32<02:54, 39.24it/s]

Extracting GLCM features:  19%|█▉        | 1629/8455 [00:32<02:43, 41.77it/s]

Extracting GLCM features:  19%|█▉        | 1635/8455 [00:32<02:30, 45.23it/s]

Extracting GLCM features:  19%|█▉        | 1641/8455 [00:32<02:25, 46.78it/s]

Extracting GLCM features:  19%|█▉        | 1647/8455 [00:32<02:18, 49.08it/s]

Extracting GLCM features:  20%|█▉        | 1654/8455 [00:32<02:07, 53.15it/s]

Extracting GLCM features:  20%|█▉        | 1660/8455 [00:32<02:05, 54.10it/s]

Extracting GLCM features:  20%|█▉        | 1667/8455 [00:32<01:59, 56.77it/s]

Extracting GLCM features:  20%|█▉        | 1673/8455 [00:33<01:59, 56.90it/s]

Extracting GLCM features:  20%|█▉        | 1680/8455 [00:33<01:56, 58.38it/s]

Extracting GLCM features:  20%|█▉        | 1686/8455 [00:33<02:08, 52.82it/s]

Extracting GLCM features:  20%|██        | 1692/8455 [00:33<02:03, 54.64it/s]

Extracting GLCM features:  20%|██        | 1698/8455 [00:33<02:01, 55.82it/s]

Extracting GLCM features:  20%|██        | 1704/8455 [00:33<02:03, 54.80it/s]

Extracting GLCM features:  20%|██        | 1710/8455 [00:33<02:00, 55.96it/s]

Extracting GLCM features:  20%|██        | 1716/8455 [00:33<02:00, 55.87it/s]

Extracting GLCM features:  20%|██        | 1722/8455 [00:33<02:02, 54.97it/s]

Extracting GLCM features:  20%|██        | 1728/8455 [00:34<02:16, 49.17it/s]

Extracting GLCM features:  21%|██        | 1734/8455 [00:34<02:12, 50.64it/s]

Extracting GLCM features:  21%|██        | 1740/8455 [00:34<02:10, 51.63it/s]

Extracting GLCM features:  21%|██        | 1746/8455 [00:34<02:05, 53.33it/s]

Extracting GLCM features:  21%|██        | 1752/8455 [00:34<02:03, 54.10it/s]

Extracting GLCM features:  21%|██        | 1758/8455 [00:34<02:04, 53.96it/s]

Extracting GLCM features:  21%|██        | 1765/8455 [00:34<01:59, 55.88it/s]

Extracting GLCM features:  21%|██        | 1772/8455 [00:34<01:55, 57.80it/s]

Extracting GLCM features:  21%|██        | 1778/8455 [00:34<01:56, 57.21it/s]

Extracting GLCM features:  21%|██        | 1784/8455 [00:35<01:59, 55.60it/s]

Extracting GLCM features:  21%|██        | 1790/8455 [00:35<02:02, 54.47it/s]

Extracting GLCM features:  21%|██        | 1796/8455 [00:35<02:05, 53.19it/s]

Extracting GLCM features:  21%|██▏       | 1803/8455 [00:35<02:01, 54.92it/s]

Extracting GLCM features:  21%|██▏       | 1809/8455 [00:35<02:06, 52.62it/s]

Extracting GLCM features:  21%|██▏       | 1815/8455 [00:35<02:03, 53.89it/s]

Extracting GLCM features:  22%|██▏       | 1821/8455 [00:35<02:02, 54.00it/s]

Extracting GLCM features:  22%|██▏       | 1827/8455 [00:35<01:59, 55.50it/s]

Extracting GLCM features:  22%|██▏       | 1833/8455 [00:36<02:06, 52.52it/s]

Extracting GLCM features:  22%|██▏       | 1839/8455 [00:36<02:20, 47.25it/s]

Extracting GLCM features:  22%|██▏       | 1844/8455 [00:36<02:28, 44.59it/s]

Extracting GLCM features:  22%|██▏       | 1849/8455 [00:36<02:26, 45.11it/s]

Extracting GLCM features:  22%|██▏       | 1855/8455 [00:36<02:20, 46.94it/s]

Extracting GLCM features:  22%|██▏       | 1861/8455 [00:36<02:13, 49.24it/s]

Extracting GLCM features:  22%|██▏       | 1867/8455 [00:36<02:12, 49.69it/s]

Extracting GLCM features:  22%|██▏       | 1873/8455 [00:36<02:07, 51.73it/s]

Extracting GLCM features:  22%|██▏       | 1880/8455 [00:36<02:01, 54.00it/s]

Extracting GLCM features:  22%|██▏       | 1886/8455 [00:37<02:02, 53.51it/s]

Extracting GLCM features:  22%|██▏       | 1892/8455 [00:37<02:00, 54.45it/s]

Extracting GLCM features:  22%|██▏       | 1898/8455 [00:37<01:59, 55.07it/s]

Extracting GLCM features:  23%|██▎       | 1905/8455 [00:37<01:56, 56.45it/s]

Extracting GLCM features:  23%|██▎       | 1911/8455 [00:37<01:59, 54.95it/s]

Extracting GLCM features:  23%|██▎       | 1917/8455 [00:37<01:56, 56.18it/s]

Extracting GLCM features:  23%|██▎       | 1923/8455 [00:37<01:57, 55.81it/s]

Extracting GLCM features:  23%|██▎       | 1929/8455 [00:37<01:54, 56.84it/s]

Extracting GLCM features:  23%|██▎       | 1935/8455 [00:37<01:53, 57.66it/s]

Extracting GLCM features:  23%|██▎       | 1941/8455 [00:38<01:55, 56.38it/s]

Extracting GLCM features:  23%|██▎       | 1947/8455 [00:38<02:07, 50.95it/s]

Extracting GLCM features:  23%|██▎       | 1953/8455 [00:38<02:03, 52.77it/s]

Extracting GLCM features:  23%|██▎       | 1959/8455 [00:38<01:59, 54.38it/s]

Extracting GLCM features:  23%|██▎       | 1965/8455 [00:38<01:57, 55.44it/s]

Extracting GLCM features:  23%|██▎       | 1971/8455 [00:38<01:54, 56.52it/s]

Extracting GLCM features:  23%|██▎       | 1977/8455 [00:38<01:54, 56.60it/s]

Extracting GLCM features:  23%|██▎       | 1984/8455 [00:38<01:52, 57.71it/s]

Extracting GLCM features:  24%|██▎       | 1991/8455 [00:38<01:49, 58.98it/s]

Extracting GLCM features:  24%|██▎       | 1997/8455 [00:39<01:54, 56.42it/s]

Extracting GLCM features:  24%|██▎       | 2003/8455 [00:39<02:08, 50.38it/s]

Extracting GLCM features:  24%|██▍       | 2009/8455 [00:39<02:02, 52.61it/s]

Extracting GLCM features:  24%|██▍       | 2015/8455 [00:39<02:00, 53.49it/s]

Extracting GLCM features:  24%|██▍       | 2021/8455 [00:39<02:16, 47.26it/s]

Extracting GLCM features:  24%|██▍       | 2026/8455 [00:39<02:16, 47.22it/s]

Extracting GLCM features:  24%|██▍       | 2032/8455 [00:39<02:09, 49.69it/s]

Extracting GLCM features:  24%|██▍       | 2039/8455 [00:39<01:57, 54.44it/s]

Extracting GLCM features:  24%|██▍       | 2045/8455 [00:40<01:57, 54.45it/s]

Extracting GLCM features:  24%|██▍       | 2051/8455 [00:40<01:56, 54.77it/s]

Extracting GLCM features:  24%|██▍       | 2057/8455 [00:40<02:02, 52.37it/s]

Extracting GLCM features:  24%|██▍       | 2063/8455 [00:40<02:17, 46.47it/s]

Extracting GLCM features:  24%|██▍       | 2069/8455 [00:40<02:12, 48.23it/s]

Extracting GLCM features:  25%|██▍       | 2075/8455 [00:40<02:05, 50.78it/s]

Extracting GLCM features:  25%|██▍       | 2081/8455 [00:40<02:00, 52.81it/s]

Extracting GLCM features:  25%|██▍       | 2088/8455 [00:40<01:54, 55.61it/s]

Extracting GLCM features:  25%|██▍       | 2095/8455 [00:40<01:51, 56.84it/s]

Extracting GLCM features:  25%|██▍       | 2101/8455 [00:41<01:58, 53.62it/s]

Extracting GLCM features:  25%|██▍       | 2107/8455 [00:41<02:01, 52.20it/s]

Extracting GLCM features:  25%|██▍       | 2113/8455 [00:41<02:05, 50.62it/s]

Extracting GLCM features:  25%|██▌       | 2119/8455 [00:41<02:07, 49.69it/s]

Extracting GLCM features:  25%|██▌       | 2125/8455 [00:41<02:05, 50.29it/s]

Extracting GLCM features:  25%|██▌       | 2131/8455 [00:41<02:14, 46.90it/s]

Extracting GLCM features:  25%|██▌       | 2138/8455 [00:41<02:03, 51.19it/s]

Extracting GLCM features:  25%|██▌       | 2145/8455 [00:41<01:56, 54.18it/s]

Extracting GLCM features:  25%|██▌       | 2151/8455 [00:42<01:56, 53.94it/s]

Extracting GLCM features:  26%|██▌       | 2157/8455 [00:42<01:53, 55.40it/s]

Extracting GLCM features:  26%|██▌       | 2163/8455 [00:42<01:51, 56.40it/s]

Extracting GLCM features:  26%|██▌       | 2170/8455 [00:42<01:47, 58.39it/s]

Extracting GLCM features:  26%|██▌       | 2177/8455 [00:42<01:44, 59.93it/s]

Extracting GLCM features:  26%|██▌       | 2184/8455 [00:42<01:47, 58.50it/s]

Extracting GLCM features:  26%|██▌       | 2191/8455 [00:42<01:46, 58.86it/s]

Extracting GLCM features:  26%|██▌       | 2197/8455 [00:42<01:48, 57.84it/s]

Extracting GLCM features:  26%|██▌       | 2203/8455 [00:42<01:56, 53.80it/s]

Extracting GLCM features:  26%|██▌       | 2209/8455 [00:43<01:54, 54.33it/s]

Extracting GLCM features:  26%|██▌       | 2215/8455 [00:43<01:52, 55.57it/s]

Extracting GLCM features:  26%|██▋       | 2221/8455 [00:43<01:50, 56.24it/s]

Extracting GLCM features:  26%|██▋       | 2227/8455 [00:43<01:50, 56.48it/s]

Extracting GLCM features:  26%|██▋       | 2233/8455 [00:43<01:50, 56.37it/s]

Extracting GLCM features:  26%|██▋       | 2239/8455 [00:43<01:51, 55.83it/s]

Extracting GLCM features:  27%|██▋       | 2246/8455 [00:43<01:47, 57.66it/s]

Extracting GLCM features:  27%|██▋       | 2252/8455 [00:43<01:51, 55.71it/s]

Extracting GLCM features:  27%|██▋       | 2258/8455 [00:43<01:57, 52.63it/s]

Extracting GLCM features:  27%|██▋       | 2264/8455 [00:44<02:04, 49.77it/s]

Extracting GLCM features:  27%|██▋       | 2271/8455 [00:44<01:54, 53.92it/s]

Extracting GLCM features:  27%|██▋       | 2277/8455 [00:44<02:06, 48.89it/s]

Extracting GLCM features:  27%|██▋       | 2283/8455 [00:44<02:04, 49.73it/s]

Extracting GLCM features:  27%|██▋       | 2289/8455 [00:44<02:09, 47.49it/s]

Extracting GLCM features:  27%|██▋       | 2295/8455 [00:44<02:03, 49.99it/s]

Extracting GLCM features:  27%|██▋       | 2302/8455 [00:44<01:53, 54.19it/s]

Extracting GLCM features:  27%|██▋       | 2309/8455 [00:44<01:49, 56.27it/s]

Extracting GLCM features:  27%|██▋       | 2315/8455 [00:45<01:56, 52.89it/s]

Extracting GLCM features:  27%|██▋       | 2321/8455 [00:45<01:58, 51.68it/s]

Extracting GLCM features:  28%|██▊       | 2327/8455 [00:45<01:58, 51.88it/s]

Extracting GLCM features:  28%|██▊       | 2333/8455 [00:45<01:55, 53.22it/s]

Extracting GLCM features:  28%|██▊       | 2339/8455 [00:45<01:55, 52.97it/s]

Extracting GLCM features:  28%|██▊       | 2345/8455 [00:45<01:55, 52.70it/s]

Extracting GLCM features:  28%|██▊       | 2351/8455 [00:45<01:55, 52.80it/s]

Extracting GLCM features:  28%|██▊       | 2357/8455 [00:45<02:00, 50.73it/s]

Extracting GLCM features:  28%|██▊       | 2363/8455 [00:46<02:06, 48.05it/s]

Extracting GLCM features:  28%|██▊       | 2368/8455 [00:46<02:05, 48.40it/s]

Extracting GLCM features:  28%|██▊       | 2374/8455 [00:46<02:03, 49.23it/s]

Extracting GLCM features:  28%|██▊       | 2380/8455 [00:46<01:59, 50.99it/s]

Extracting GLCM features:  28%|██▊       | 2387/8455 [00:46<01:51, 54.58it/s]

Extracting GLCM features:  28%|██▊       | 2393/8455 [00:46<01:53, 53.31it/s]

Extracting GLCM features:  28%|██▊       | 2399/8455 [00:46<01:51, 54.54it/s]

Extracting GLCM features:  28%|██▊       | 2406/8455 [00:46<01:46, 56.56it/s]

Extracting GLCM features:  29%|██▊       | 2413/8455 [00:46<01:43, 58.18it/s]

Extracting GLCM features:  29%|██▊       | 2419/8455 [00:47<01:51, 54.22it/s]

Extracting GLCM features:  29%|██▊       | 2426/8455 [00:47<01:46, 56.54it/s]

Extracting GLCM features:  29%|██▉       | 2432/8455 [00:47<01:44, 57.36it/s]

Extracting GLCM features:  29%|██▉       | 2439/8455 [00:47<01:41, 58.99it/s]

Extracting GLCM features:  29%|██▉       | 2445/8455 [00:47<01:42, 58.83it/s]

Extracting GLCM features:  29%|██▉       | 2451/8455 [00:47<01:45, 57.08it/s]

Extracting GLCM features:  29%|██▉       | 2457/8455 [00:47<01:43, 57.69it/s]

Extracting GLCM features:  29%|██▉       | 2464/8455 [00:47<01:39, 60.04it/s]

Extracting GLCM features:  29%|██▉       | 2471/8455 [00:47<01:39, 60.33it/s]

Extracting GLCM features:  29%|██▉       | 2478/8455 [00:48<01:43, 57.94it/s]

Extracting GLCM features:  29%|██▉       | 2484/8455 [00:48<01:46, 56.29it/s]

Extracting GLCM features:  29%|██▉       | 2490/8455 [00:48<01:52, 53.19it/s]

Extracting GLCM features:  30%|██▉       | 2496/8455 [00:48<01:51, 53.67it/s]

Extracting GLCM features:  30%|██▉       | 2502/8455 [00:48<01:49, 54.33it/s]

Extracting GLCM features:  30%|██▉       | 2509/8455 [00:48<01:46, 56.02it/s]

Extracting GLCM features:  30%|██▉       | 2516/8455 [00:48<01:41, 58.67it/s]

Extracting GLCM features:  30%|██▉       | 2523/8455 [00:48<01:39, 59.46it/s]

Extracting GLCM features:  30%|██▉       | 2530/8455 [00:48<01:37, 60.85it/s]

Extracting GLCM features:  30%|███       | 2537/8455 [00:49<01:37, 60.54it/s]

Extracting GLCM features:  30%|███       | 2544/8455 [00:49<01:35, 61.94it/s]

Extracting GLCM features:  30%|███       | 2551/8455 [00:49<01:35, 62.07it/s]

Extracting GLCM features:  30%|███       | 2558/8455 [00:49<01:34, 62.44it/s]

Extracting GLCM features:  30%|███       | 2565/8455 [00:49<01:51, 52.88it/s]

Extracting GLCM features:  30%|███       | 2571/8455 [00:49<01:53, 51.97it/s]

Extracting GLCM features:  30%|███       | 2577/8455 [00:49<01:53, 51.81it/s]

Extracting GLCM features:  31%|███       | 2583/8455 [00:49<01:54, 51.24it/s]

Extracting GLCM features:  31%|███       | 2589/8455 [00:50<01:58, 49.36it/s]

Extracting GLCM features:  31%|███       | 2595/8455 [00:50<01:57, 49.68it/s]

Extracting GLCM features:  31%|███       | 2601/8455 [00:50<01:56, 50.24it/s]

Extracting GLCM features:  31%|███       | 2607/8455 [00:50<01:54, 50.89it/s]

Extracting GLCM features:  31%|███       | 2613/8455 [00:50<01:54, 50.88it/s]

Extracting GLCM features:  31%|███       | 2619/8455 [00:50<01:58, 49.05it/s]

Extracting GLCM features:  31%|███       | 2626/8455 [00:50<01:50, 52.81it/s]

Extracting GLCM features:  31%|███       | 2633/8455 [00:50<01:45, 55.28it/s]

Extracting GLCM features:  31%|███       | 2639/8455 [00:51<01:48, 53.84it/s]

Extracting GLCM features:  31%|███▏      | 2645/8455 [00:51<01:47, 53.91it/s]

Extracting GLCM features:  31%|███▏      | 2651/8455 [00:51<01:46, 54.67it/s]

Extracting GLCM features:  31%|███▏      | 2657/8455 [00:51<01:45, 54.74it/s]

Extracting GLCM features:  31%|███▏      | 2663/8455 [00:51<01:43, 56.10it/s]

Extracting GLCM features:  32%|███▏      | 2669/8455 [00:51<01:51, 51.82it/s]

Extracting GLCM features:  32%|███▏      | 2675/8455 [00:51<01:50, 52.48it/s]

Extracting GLCM features:  32%|███▏      | 2681/8455 [00:51<01:45, 54.48it/s]

Extracting GLCM features:  32%|███▏      | 2688/8455 [00:51<01:41, 56.86it/s]

Extracting GLCM features:  32%|███▏      | 2694/8455 [00:52<01:53, 50.95it/s]

Extracting GLCM features:  32%|███▏      | 2700/8455 [00:52<01:49, 52.78it/s]

Extracting GLCM features:  32%|███▏      | 2706/8455 [00:52<01:45, 54.44it/s]

Extracting GLCM features:  32%|███▏      | 2712/8455 [00:52<01:43, 55.62it/s]

Extracting GLCM features:  32%|███▏      | 2718/8455 [00:52<01:42, 56.08it/s]

Extracting GLCM features:  32%|███▏      | 2724/8455 [00:52<01:44, 54.95it/s]

Extracting GLCM features:  32%|███▏      | 2730/8455 [00:52<01:42, 55.85it/s]

Extracting GLCM features:  32%|███▏      | 2736/8455 [00:52<01:40, 56.81it/s]

Extracting GLCM features:  32%|███▏      | 2743/8455 [00:52<01:39, 57.45it/s]

Extracting GLCM features:  33%|███▎      | 2749/8455 [00:53<01:39, 57.15it/s]

Extracting GLCM features:  33%|███▎      | 2755/8455 [00:53<01:41, 56.36it/s]

Extracting GLCM features:  33%|███▎      | 2761/8455 [00:53<01:41, 55.97it/s]

Extracting GLCM features:  33%|███▎      | 2767/8455 [00:53<01:47, 53.06it/s]

Extracting GLCM features:  33%|███▎      | 2773/8455 [00:53<01:43, 54.78it/s]

Extracting GLCM features:  33%|███▎      | 2779/8455 [00:53<01:44, 54.57it/s]

Extracting GLCM features:  33%|███▎      | 2785/8455 [00:53<01:45, 53.51it/s]

Extracting GLCM features:  33%|███▎      | 2791/8455 [00:53<01:44, 54.28it/s]

Extracting GLCM features:  33%|███▎      | 2797/8455 [00:53<01:42, 55.16it/s]

Extracting GLCM features:  33%|███▎      | 2803/8455 [00:54<01:59, 47.41it/s]

Extracting GLCM features:  33%|███▎      | 2809/8455 [00:54<01:57, 48.17it/s]

Extracting GLCM features:  33%|███▎      | 2815/8455 [00:54<01:53, 49.83it/s]

Extracting GLCM features:  33%|███▎      | 2821/8455 [00:54<01:51, 50.65it/s]

Extracting GLCM features:  33%|███▎      | 2827/8455 [00:54<01:52, 50.00it/s]

Extracting GLCM features:  34%|███▎      | 2833/8455 [00:54<01:48, 51.65it/s]

Extracting GLCM features:  34%|███▎      | 2839/8455 [00:54<01:53, 49.56it/s]

Extracting GLCM features:  34%|███▎      | 2845/8455 [00:54<01:51, 50.54it/s]

Extracting GLCM features:  34%|███▎      | 2851/8455 [00:54<01:49, 51.27it/s]

Extracting GLCM features:  34%|███▍      | 2857/8455 [00:55<01:49, 51.17it/s]

Extracting GLCM features:  34%|███▍      | 2863/8455 [00:55<01:46, 52.29it/s]

Extracting GLCM features:  34%|███▍      | 2869/8455 [00:55<01:43, 53.80it/s]

Extracting GLCM features:  34%|███▍      | 2875/8455 [00:55<01:41, 54.87it/s]

Extracting GLCM features:  34%|███▍      | 2881/8455 [00:55<01:44, 53.44it/s]

Extracting GLCM features:  34%|███▍      | 2887/8455 [00:55<01:53, 48.86it/s]

Extracting GLCM features:  34%|███▍      | 2893/8455 [00:55<01:49, 50.66it/s]

Extracting GLCM features:  34%|███▍      | 2899/8455 [00:55<01:46, 52.13it/s]

Extracting GLCM features:  34%|███▍      | 2905/8455 [00:56<01:46, 52.10it/s]

Extracting GLCM features:  34%|███▍      | 2911/8455 [00:56<01:47, 51.58it/s]

Extracting GLCM features:  35%|███▍      | 2917/8455 [00:56<01:42, 53.77it/s]

Extracting GLCM features:  35%|███▍      | 2923/8455 [00:56<01:41, 54.71it/s]

Extracting GLCM features:  35%|███▍      | 2929/8455 [00:56<01:41, 54.26it/s]

Extracting GLCM features:  35%|███▍      | 2935/8455 [00:56<01:43, 53.18it/s]

Extracting GLCM features:  35%|███▍      | 2942/8455 [00:56<01:40, 55.10it/s]

Extracting GLCM features:  35%|███▍      | 2949/8455 [00:56<01:35, 57.72it/s]

Extracting GLCM features:  35%|███▍      | 2955/8455 [00:56<01:34, 58.21it/s]

Extracting GLCM features:  35%|███▌      | 2961/8455 [00:57<01:34, 57.90it/s]

Extracting GLCM features:  35%|███▌      | 2967/8455 [00:57<01:43, 53.18it/s]

Extracting GLCM features:  35%|███▌      | 2974/8455 [00:57<01:38, 55.84it/s]

Extracting GLCM features:  35%|███▌      | 2981/8455 [00:57<01:36, 57.02it/s]

Extracting GLCM features:  35%|███▌      | 2988/8455 [00:57<01:34, 58.05it/s]

Extracting GLCM features:  35%|███▌      | 2995/8455 [00:57<01:33, 58.69it/s]

Extracting GLCM features:  36%|███▌      | 3002/8455 [00:57<01:32, 58.86it/s]

Extracting GLCM features:  36%|███▌      | 3009/8455 [00:57<01:28, 61.26it/s]

Extracting GLCM features:  36%|███▌      | 3016/8455 [00:57<01:27, 62.26it/s]

Extracting GLCM features:  36%|███▌      | 3023/8455 [00:58<01:29, 60.75it/s]

Extracting GLCM features:  36%|███▌      | 3030/8455 [00:58<01:28, 61.08it/s]

Extracting GLCM features:  36%|███▌      | 3037/8455 [00:58<01:29, 60.62it/s]

Extracting GLCM features:  36%|███▌      | 3044/8455 [00:58<01:28, 61.01it/s]

Extracting GLCM features:  36%|███▌      | 3051/8455 [00:58<01:28, 60.77it/s]

Extracting GLCM features:  36%|███▌      | 3058/8455 [00:58<01:28, 61.04it/s]

Extracting GLCM features:  36%|███▋      | 3065/8455 [00:58<01:27, 61.32it/s]

Extracting GLCM features:  36%|███▋      | 3072/8455 [00:58<01:26, 62.39it/s]

Extracting GLCM features:  36%|███▋      | 3079/8455 [00:58<01:24, 63.95it/s]

Extracting GLCM features:  36%|███▋      | 3086/8455 [00:59<01:28, 61.00it/s]

Extracting GLCM features:  37%|███▋      | 3093/8455 [00:59<01:26, 61.82it/s]

Extracting GLCM features:  37%|███▋      | 3100/8455 [00:59<01:25, 62.57it/s]

Extracting GLCM features:  37%|███▋      | 3107/8455 [00:59<01:24, 63.41it/s]

Extracting GLCM features:  37%|███▋      | 3114/8455 [00:59<01:28, 60.68it/s]

Extracting GLCM features:  37%|███▋      | 3121/8455 [00:59<01:27, 60.73it/s]

Extracting GLCM features:  37%|███▋      | 3128/8455 [00:59<01:49, 48.80it/s]

Extracting GLCM features:  37%|███▋      | 3135/8455 [00:59<01:41, 52.35it/s]

Extracting GLCM features:  37%|███▋      | 3141/8455 [01:00<01:40, 52.67it/s]

Extracting GLCM features:  37%|███▋      | 3147/8455 [01:00<01:38, 54.14it/s]

Extracting GLCM features:  37%|███▋      | 3154/8455 [01:00<01:33, 56.51it/s]

Extracting GLCM features:  37%|███▋      | 3160/8455 [01:00<01:34, 56.30it/s]

Extracting GLCM features:  37%|███▋      | 3167/8455 [01:00<01:31, 57.98it/s]

Extracting GLCM features:  38%|███▊      | 3173/8455 [01:00<01:32, 57.11it/s]

Extracting GLCM features:  38%|███▊      | 3180/8455 [01:00<01:29, 59.14it/s]

Extracting GLCM features:  38%|███▊      | 3187/8455 [01:00<01:27, 59.87it/s]

Extracting GLCM features:  38%|███▊      | 3194/8455 [01:00<01:25, 61.79it/s]

Extracting GLCM features:  38%|███▊      | 3201/8455 [01:01<01:25, 61.51it/s]

Extracting GLCM features:  38%|███▊      | 3208/8455 [01:01<01:25, 61.54it/s]

Extracting GLCM features:  38%|███▊      | 3215/8455 [01:01<01:24, 61.96it/s]

Extracting GLCM features:  38%|███▊      | 3222/8455 [01:01<01:24, 62.01it/s]

Extracting GLCM features:  38%|███▊      | 3229/8455 [01:01<01:24, 61.66it/s]

Extracting GLCM features:  38%|███▊      | 3236/8455 [01:01<01:23, 62.81it/s]

Extracting GLCM features:  38%|███▊      | 3243/8455 [01:01<01:52, 46.15it/s]

Extracting GLCM features:  38%|███▊      | 3249/8455 [01:02<01:57, 44.28it/s]

Extracting GLCM features:  38%|███▊      | 3255/8455 [01:02<01:49, 47.29it/s]

Extracting GLCM features:  39%|███▊      | 3262/8455 [01:02<01:40, 51.43it/s]

Extracting GLCM features:  39%|███▊      | 3269/8455 [01:02<01:35, 54.22it/s]

Extracting GLCM features:  39%|███▊      | 3276/8455 [01:02<01:30, 57.50it/s]

Extracting GLCM features:  39%|███▉      | 3282/8455 [01:02<01:33, 55.40it/s]

Extracting GLCM features:  39%|███▉      | 3288/8455 [01:02<01:31, 56.36it/s]

Extracting GLCM features:  39%|███▉      | 3295/8455 [01:02<01:26, 59.84it/s]

Extracting GLCM features:  39%|███▉      | 3302/8455 [01:02<01:25, 60.28it/s]

Extracting GLCM features:  39%|███▉      | 3309/8455 [01:03<01:25, 60.49it/s]

Extracting GLCM features:  39%|███▉      | 3316/8455 [01:03<01:23, 61.73it/s]

Extracting GLCM features:  39%|███▉      | 3323/8455 [01:03<01:49, 46.92it/s]

Extracting GLCM features:  39%|███▉      | 3330/8455 [01:03<01:41, 50.28it/s]

Extracting GLCM features:  39%|███▉      | 3336/8455 [01:03<01:40, 51.10it/s]

Extracting GLCM features:  40%|███▉      | 3342/8455 [01:03<01:39, 51.43it/s]

Extracting GLCM features:  40%|███▉      | 3349/8455 [01:03<01:33, 54.34it/s]

Extracting GLCM features:  40%|███▉      | 3356/8455 [01:03<01:31, 55.54it/s]

Extracting GLCM features:  40%|███▉      | 3362/8455 [01:04<01:32, 55.00it/s]

Extracting GLCM features:  40%|███▉      | 3368/8455 [01:04<01:36, 52.97it/s]

Extracting GLCM features:  40%|███▉      | 3374/8455 [01:04<01:41, 50.26it/s]

Extracting GLCM features:  40%|███▉      | 3381/8455 [01:04<01:34, 53.94it/s]

Extracting GLCM features:  40%|████      | 3387/8455 [01:04<01:43, 49.12it/s]

Extracting GLCM features:  40%|████      | 3394/8455 [01:04<01:36, 52.71it/s]

Extracting GLCM features:  40%|████      | 3401/8455 [01:04<01:30, 55.77it/s]

Extracting GLCM features:  40%|████      | 3408/8455 [01:04<01:26, 58.54it/s]

Extracting GLCM features:  40%|████      | 3415/8455 [01:05<01:25, 58.66it/s]

Extracting GLCM features:  40%|████      | 3421/8455 [01:05<01:27, 57.54it/s]

Extracting GLCM features:  41%|████      | 3427/8455 [01:05<01:26, 57.93it/s]

Extracting GLCM features:  41%|████      | 3433/8455 [01:05<01:25, 58.44it/s]

Extracting GLCM features:  41%|████      | 3439/8455 [01:05<01:28, 56.69it/s]

Extracting GLCM features:  41%|████      | 3445/8455 [01:05<01:40, 49.98it/s]

Extracting GLCM features:  41%|████      | 3451/8455 [01:05<01:35, 52.36it/s]

Extracting GLCM features:  41%|████      | 3457/8455 [01:05<01:32, 54.09it/s]

Extracting GLCM features:  41%|████      | 3464/8455 [01:05<01:27, 56.81it/s]

Extracting GLCM features:  41%|████      | 3471/8455 [01:06<01:23, 59.64it/s]

Extracting GLCM features:  41%|████      | 3478/8455 [01:06<01:24, 59.25it/s]

Extracting GLCM features:  41%|████      | 3484/8455 [01:06<01:23, 59.27it/s]

Extracting GLCM features:  41%|████▏     | 3491/8455 [01:06<01:22, 59.85it/s]

Extracting GLCM features:  41%|████▏     | 3498/8455 [01:06<01:24, 58.65it/s]

Extracting GLCM features:  41%|████▏     | 3504/8455 [01:06<01:27, 56.60it/s]

Extracting GLCM features:  42%|████▏     | 3511/8455 [01:06<01:25, 58.13it/s]

Extracting GLCM features:  42%|████▏     | 3518/8455 [01:06<01:22, 59.50it/s]

Extracting GLCM features:  42%|████▏     | 3524/8455 [01:06<01:23, 59.14it/s]

Extracting GLCM features:  42%|████▏     | 3530/8455 [01:07<01:27, 56.24it/s]

Extracting GLCM features:  42%|████▏     | 3537/8455 [01:07<01:23, 58.68it/s]

Extracting GLCM features:  42%|████▏     | 3544/8455 [01:07<01:22, 59.35it/s]

Extracting GLCM features:  42%|████▏     | 3551/8455 [01:07<01:20, 60.79it/s]

Extracting GLCM features:  42%|████▏     | 3558/8455 [01:07<01:24, 57.99it/s]

Extracting GLCM features:  42%|████▏     | 3564/8455 [01:07<01:30, 53.85it/s]

Extracting GLCM features:  42%|████▏     | 3570/8455 [01:07<01:32, 52.90it/s]

Extracting GLCM features:  42%|████▏     | 3576/8455 [01:07<01:29, 54.69it/s]

Extracting GLCM features:  42%|████▏     | 3583/8455 [01:07<01:23, 58.63it/s]

Extracting GLCM features:  42%|████▏     | 3589/8455 [01:08<01:24, 57.76it/s]

Extracting GLCM features:  43%|████▎     | 3596/8455 [01:08<01:21, 59.80it/s]

Extracting GLCM features:  43%|████▎     | 3603/8455 [01:08<01:28, 54.85it/s]

Extracting GLCM features:  43%|████▎     | 3610/8455 [01:08<01:25, 57.00it/s]

Extracting GLCM features:  43%|████▎     | 3616/8455 [01:08<01:24, 57.11it/s]

Extracting GLCM features:  43%|████▎     | 3622/8455 [01:08<01:31, 52.67it/s]

Extracting GLCM features:  43%|████▎     | 3628/8455 [01:08<01:29, 54.02it/s]

Extracting GLCM features:  43%|████▎     | 3635/8455 [01:08<01:23, 57.40it/s]

Extracting GLCM features:  43%|████▎     | 3642/8455 [01:08<01:20, 59.50it/s]

Extracting GLCM features:  43%|████▎     | 3649/8455 [01:09<01:21, 58.87it/s]

Extracting GLCM features:  43%|████▎     | 3656/8455 [01:09<01:20, 59.93it/s]

Extracting GLCM features:  43%|████▎     | 3663/8455 [01:09<01:31, 52.40it/s]

Extracting GLCM features:  43%|████▎     | 3669/8455 [01:09<01:38, 48.52it/s]

Extracting GLCM features:  43%|████▎     | 3675/8455 [01:09<01:37, 49.20it/s]

Extracting GLCM features:  44%|████▎     | 3681/8455 [01:09<01:33, 51.29it/s]

Extracting GLCM features:  44%|████▎     | 3687/8455 [01:09<01:30, 52.68it/s]

Extracting GLCM features:  44%|████▎     | 3694/8455 [01:09<01:27, 54.37it/s]

Extracting GLCM features:  44%|████▍     | 3700/8455 [01:10<01:26, 54.72it/s]

Extracting GLCM features:  44%|████▍     | 3706/8455 [01:10<01:27, 54.25it/s]

Extracting GLCM features:  44%|████▍     | 3712/8455 [01:10<01:28, 53.64it/s]

Extracting GLCM features:  44%|████▍     | 3718/8455 [01:10<01:28, 53.49it/s]

Extracting GLCM features:  44%|████▍     | 3724/8455 [01:10<01:27, 53.84it/s]

Extracting GLCM features:  44%|████▍     | 3730/8455 [01:10<01:27, 54.28it/s]

Extracting GLCM features:  44%|████▍     | 3736/8455 [01:10<01:26, 54.84it/s]

Extracting GLCM features:  44%|████▍     | 3742/8455 [01:10<01:24, 55.45it/s]

Extracting GLCM features:  44%|████▍     | 3748/8455 [01:10<01:24, 55.44it/s]

Extracting GLCM features:  44%|████▍     | 3754/8455 [01:11<01:27, 54.02it/s]

Extracting GLCM features:  44%|████▍     | 3760/8455 [01:11<01:26, 54.47it/s]

Extracting GLCM features:  45%|████▍     | 3766/8455 [01:11<01:24, 55.26it/s]

Extracting GLCM features:  45%|████▍     | 3772/8455 [01:11<01:25, 54.89it/s]

Extracting GLCM features:  45%|████▍     | 3778/8455 [01:11<01:27, 53.44it/s]

Extracting GLCM features:  45%|████▍     | 3784/8455 [01:11<01:26, 53.96it/s]

Extracting GLCM features:  45%|████▍     | 3790/8455 [01:11<01:25, 54.45it/s]

Extracting GLCM features:  45%|████▍     | 3796/8455 [01:11<01:25, 54.35it/s]

Extracting GLCM features:  45%|████▍     | 3802/8455 [01:11<01:24, 54.79it/s]

Extracting GLCM features:  45%|████▌     | 3808/8455 [01:12<01:24, 54.97it/s]

Extracting GLCM features:  45%|████▌     | 3815/8455 [01:12<01:21, 57.27it/s]

Extracting GLCM features:  45%|████▌     | 3822/8455 [01:12<01:19, 58.49it/s]

Extracting GLCM features:  45%|████▌     | 3828/8455 [01:12<01:19, 58.48it/s]

Extracting GLCM features:  45%|████▌     | 3834/8455 [01:12<01:19, 58.22it/s]

Extracting GLCM features:  45%|████▌     | 3840/8455 [01:12<01:18, 58.49it/s]

Extracting GLCM features:  45%|████▌     | 3846/8455 [01:12<01:19, 57.96it/s]

Extracting GLCM features:  46%|████▌     | 3852/8455 [01:12<01:23, 54.91it/s]

Extracting GLCM features:  46%|████▌     | 3859/8455 [01:12<01:20, 57.06it/s]

Extracting GLCM features:  46%|████▌     | 3865/8455 [01:13<01:20, 56.68it/s]

Extracting GLCM features:  46%|████▌     | 3872/8455 [01:13<01:19, 57.99it/s]

Extracting GLCM features:  46%|████▌     | 3878/8455 [01:13<01:18, 58.06it/s]

Extracting GLCM features:  46%|████▌     | 3884/8455 [01:13<01:20, 56.82it/s]

Extracting GLCM features:  46%|████▌     | 3890/8455 [01:13<01:23, 54.71it/s]

Extracting GLCM features:  46%|████▌     | 3896/8455 [01:13<01:23, 54.31it/s]

Extracting GLCM features:  46%|████▌     | 3903/8455 [01:13<01:19, 57.07it/s]

Extracting GLCM features:  46%|████▌     | 3909/8455 [01:13<01:19, 57.35it/s]

Extracting GLCM features:  46%|████▋     | 3916/8455 [01:13<01:16, 59.61it/s]

Extracting GLCM features:  46%|████▋     | 3922/8455 [01:14<01:16, 59.57it/s]

Extracting GLCM features:  46%|████▋     | 3929/8455 [01:14<01:15, 60.28it/s]

Extracting GLCM features:  47%|████▋     | 3936/8455 [01:14<01:12, 62.10it/s]

Extracting GLCM features:  47%|████▋     | 3943/8455 [01:14<01:13, 61.38it/s]

Extracting GLCM features:  47%|████▋     | 3950/8455 [01:14<01:14, 60.79it/s]

Extracting GLCM features:  47%|████▋     | 3957/8455 [01:14<01:16, 58.82it/s]

Extracting GLCM features:  47%|████▋     | 3963/8455 [01:14<01:16, 58.80it/s]

Extracting GLCM features:  47%|████▋     | 3970/8455 [01:14<01:14, 59.91it/s]

Extracting GLCM features:  47%|████▋     | 3977/8455 [01:14<01:15, 59.41it/s]

Extracting GLCM features:  47%|████▋     | 3983/8455 [01:15<01:16, 58.82it/s]

Extracting GLCM features:  47%|████▋     | 3990/8455 [01:15<01:15, 59.35it/s]

Extracting GLCM features:  47%|████▋     | 3996/8455 [01:15<01:22, 53.73it/s]

Extracting GLCM features:  47%|████▋     | 4002/8455 [01:15<01:20, 55.21it/s]

Extracting GLCM features:  47%|████▋     | 4009/8455 [01:15<01:18, 56.29it/s]

Extracting GLCM features:  47%|████▋     | 4016/8455 [01:15<01:17, 57.17it/s]

Extracting GLCM features:  48%|████▊     | 4023/8455 [01:15<01:15, 58.90it/s]

Extracting GLCM features:  48%|████▊     | 4030/8455 [01:15<01:13, 60.39it/s]

Extracting GLCM features:  48%|████▊     | 4037/8455 [01:15<01:12, 61.05it/s]

Extracting GLCM features:  48%|████▊     | 4044/8455 [01:16<01:12, 61.18it/s]

Extracting GLCM features:  48%|████▊     | 4051/8455 [01:16<01:11, 61.71it/s]

Extracting GLCM features:  48%|████▊     | 4058/8455 [01:16<01:09, 62.97it/s]

Extracting GLCM features:  48%|████▊     | 4065/8455 [01:16<01:09, 63.12it/s]

Extracting GLCM features:  48%|████▊     | 4072/8455 [01:16<01:18, 55.97it/s]

Extracting GLCM features:  48%|████▊     | 4079/8455 [01:16<01:17, 56.74it/s]

Extracting GLCM features:  48%|████▊     | 4086/8455 [01:16<01:13, 59.55it/s]

Extracting GLCM features:  48%|████▊     | 4093/8455 [01:16<01:11, 60.92it/s]

Extracting GLCM features:  48%|████▊     | 4100/8455 [01:17<01:10, 61.90it/s]

Extracting GLCM features:  49%|████▊     | 4107/8455 [01:17<01:11, 60.83it/s]

Extracting GLCM features:  49%|████▊     | 4114/8455 [01:17<01:10, 61.55it/s]

Extracting GLCM features:  49%|████▊     | 4121/8455 [01:17<01:11, 60.99it/s]

Extracting GLCM features:  49%|████▉     | 4128/8455 [01:17<01:18, 54.97it/s]

Extracting GLCM features:  49%|████▉     | 4135/8455 [01:17<01:15, 56.85it/s]

Extracting GLCM features:  49%|████▉     | 4141/8455 [01:17<01:21, 52.66it/s]

Extracting GLCM features:  49%|████▉     | 4148/8455 [01:17<01:18, 54.81it/s]

Extracting GLCM features:  49%|████▉     | 4154/8455 [01:18<01:17, 55.61it/s]

Extracting GLCM features:  49%|████▉     | 4160/8455 [01:18<01:17, 55.44it/s]

Extracting GLCM features:  49%|████▉     | 4166/8455 [01:18<01:16, 55.74it/s]

Extracting GLCM features:  49%|████▉     | 4173/8455 [01:18<01:15, 56.69it/s]

Extracting GLCM features:  49%|████▉     | 4180/8455 [01:18<01:13, 58.24it/s]

Extracting GLCM features:  50%|████▉     | 4186/8455 [01:18<01:16, 55.90it/s]

Extracting GLCM features:  50%|████▉     | 4192/8455 [01:18<01:14, 56.90it/s]

Extracting GLCM features:  50%|████▉     | 4199/8455 [01:18<01:12, 58.59it/s]

Extracting GLCM features:  50%|████▉     | 4206/8455 [01:18<01:10, 60.09it/s]

Extracting GLCM features:  50%|████▉     | 4213/8455 [01:19<01:11, 59.16it/s]

Extracting GLCM features:  50%|████▉     | 4219/8455 [01:19<01:12, 58.65it/s]

Extracting GLCM features:  50%|████▉     | 4226/8455 [01:19<01:10, 59.57it/s]

Extracting GLCM features:  50%|█████     | 4232/8455 [01:19<01:11, 59.21it/s]

Extracting GLCM features:  50%|█████     | 4239/8455 [01:19<01:09, 60.23it/s]

Extracting GLCM features:  50%|█████     | 4246/8455 [01:19<01:13, 57.57it/s]

Extracting GLCM features:  50%|█████     | 4252/8455 [01:19<01:13, 56.99it/s]

Extracting GLCM features:  50%|█████     | 4258/8455 [01:19<01:12, 57.78it/s]

Extracting GLCM features:  50%|█████     | 4265/8455 [01:19<01:10, 59.71it/s]

Extracting GLCM features:  51%|█████     | 4271/8455 [01:20<01:11, 58.68it/s]

Extracting GLCM features:  51%|█████     | 4277/8455 [01:20<01:11, 58.29it/s]

Extracting GLCM features:  51%|█████     | 4283/8455 [01:20<01:11, 58.33it/s]

Extracting GLCM features:  51%|█████     | 4290/8455 [01:20<01:10, 59.16it/s]

Extracting GLCM features:  51%|█████     | 4296/8455 [01:20<01:10, 59.05it/s]

Extracting GLCM features:  51%|█████     | 4302/8455 [01:20<01:12, 57.48it/s]

Extracting GLCM features:  51%|█████     | 4309/8455 [01:20<01:10, 59.09it/s]

Extracting GLCM features:  51%|█████     | 4316/8455 [01:20<01:08, 60.08it/s]

Extracting GLCM features:  51%|█████     | 4323/8455 [01:20<01:07, 61.41it/s]

Extracting GLCM features:  51%|█████     | 4330/8455 [01:20<01:06, 61.76it/s]

Extracting GLCM features:  51%|█████▏    | 4337/8455 [01:21<01:08, 59.82it/s]

Extracting GLCM features:  51%|█████▏    | 4344/8455 [01:21<01:08, 60.13it/s]

Extracting GLCM features:  51%|█████▏    | 4351/8455 [01:21<01:07, 60.57it/s]

Extracting GLCM features:  52%|█████▏    | 4358/8455 [01:21<01:08, 60.12it/s]

Extracting GLCM features:  52%|█████▏    | 4365/8455 [01:21<01:09, 58.92it/s]

Extracting GLCM features:  52%|█████▏    | 4371/8455 [01:21<01:14, 54.52it/s]

Extracting GLCM features:  52%|█████▏    | 4378/8455 [01:21<01:10, 57.90it/s]

Extracting GLCM features:  52%|█████▏    | 4385/8455 [01:21<01:07, 59.98it/s]

Extracting GLCM features:  52%|█████▏    | 4392/8455 [01:22<01:09, 58.68it/s]

Extracting GLCM features:  52%|█████▏    | 4398/8455 [01:22<01:09, 58.56it/s]

Extracting GLCM features:  52%|█████▏    | 4404/8455 [01:22<01:09, 58.38it/s]

Extracting GLCM features:  52%|█████▏    | 4411/8455 [01:22<01:07, 60.00it/s]

Extracting GLCM features:  52%|█████▏    | 4418/8455 [01:22<01:06, 60.80it/s]

Extracting GLCM features:  52%|█████▏    | 4425/8455 [01:22<01:13, 54.64it/s]

Extracting GLCM features:  52%|█████▏    | 4432/8455 [01:22<01:09, 57.55it/s]

Extracting GLCM features:  53%|█████▎    | 4439/8455 [01:22<01:07, 59.88it/s]

Extracting GLCM features:  53%|█████▎    | 4446/8455 [01:22<01:09, 57.61it/s]

Extracting GLCM features:  53%|█████▎    | 4452/8455 [01:23<01:09, 57.32it/s]

Extracting GLCM features:  53%|█████▎    | 4458/8455 [01:23<01:09, 57.73it/s]

Extracting GLCM features:  53%|█████▎    | 4464/8455 [01:23<01:08, 58.32it/s]

Extracting GLCM features:  53%|█████▎    | 4471/8455 [01:23<01:07, 59.30it/s]

Extracting GLCM features:  53%|█████▎    | 4477/8455 [01:23<01:08, 58.41it/s]

Extracting GLCM features:  53%|█████▎    | 4484/8455 [01:23<01:06, 59.61it/s]

Extracting GLCM features:  53%|█████▎    | 4491/8455 [01:23<01:05, 60.27it/s]

Extracting GLCM features:  53%|█████▎    | 4498/8455 [01:23<01:08, 57.55it/s]

Extracting GLCM features:  53%|█████▎    | 4504/8455 [01:23<01:12, 54.31it/s]

Extracting GLCM features:  53%|█████▎    | 4510/8455 [01:24<01:15, 52.27it/s]

Extracting GLCM features:  53%|█████▎    | 4516/8455 [01:24<01:19, 49.58it/s]

Extracting GLCM features:  53%|█████▎    | 4522/8455 [01:24<01:21, 48.43it/s]

Extracting GLCM features:  54%|█████▎    | 4528/8455 [01:24<01:18, 50.32it/s]

Extracting GLCM features:  54%|█████▎    | 4534/8455 [01:24<01:18, 50.03it/s]

Extracting GLCM features:  54%|█████▎    | 4541/8455 [01:24<01:13, 53.22it/s]

Extracting GLCM features:  54%|█████▍    | 4547/8455 [01:24<01:12, 54.01it/s]

Extracting GLCM features:  54%|█████▍    | 4554/8455 [01:24<01:08, 57.05it/s]

Extracting GLCM features:  54%|█████▍    | 4560/8455 [01:25<01:10, 55.64it/s]

Extracting GLCM features:  54%|█████▍    | 4566/8455 [01:25<01:08, 56.45it/s]

Extracting GLCM features:  54%|█████▍    | 4572/8455 [01:25<01:09, 55.69it/s]

Extracting GLCM features:  54%|█████▍    | 4578/8455 [01:25<01:10, 55.18it/s]

Extracting GLCM features:  54%|█████▍    | 4584/8455 [01:25<01:10, 54.84it/s]

Extracting GLCM features:  54%|█████▍    | 4590/8455 [01:25<01:11, 54.13it/s]

Extracting GLCM features:  54%|█████▍    | 4596/8455 [01:25<01:10, 55.01it/s]

Extracting GLCM features:  54%|█████▍    | 4602/8455 [01:25<01:09, 55.43it/s]

Extracting GLCM features:  55%|█████▍    | 4608/8455 [01:25<01:14, 51.67it/s]

Extracting GLCM features:  55%|█████▍    | 4614/8455 [01:26<01:14, 51.78it/s]

Extracting GLCM features:  55%|█████▍    | 4620/8455 [01:26<01:13, 52.24it/s]

Extracting GLCM features:  55%|█████▍    | 4626/8455 [01:26<01:12, 52.90it/s]

Extracting GLCM features:  55%|█████▍    | 4632/8455 [01:26<01:09, 54.82it/s]

Extracting GLCM features:  55%|█████▍    | 4638/8455 [01:26<01:08, 55.93it/s]

Extracting GLCM features:  55%|█████▍    | 4644/8455 [01:26<01:07, 56.47it/s]

Extracting GLCM features:  55%|█████▍    | 4650/8455 [01:26<01:12, 52.41it/s]

Extracting GLCM features:  55%|█████▌    | 4657/8455 [01:26<01:07, 56.22it/s]

Extracting GLCM features:  55%|█████▌    | 4664/8455 [01:26<01:04, 58.43it/s]

Extracting GLCM features:  55%|█████▌    | 4670/8455 [01:27<01:14, 50.48it/s]

Extracting GLCM features:  55%|█████▌    | 4676/8455 [01:27<01:20, 46.84it/s]

Extracting GLCM features:  55%|█████▌    | 4681/8455 [01:27<01:21, 46.49it/s]

Extracting GLCM features:  55%|█████▌    | 4686/8455 [01:27<01:20, 46.56it/s]

Extracting GLCM features:  55%|█████▌    | 4692/8455 [01:27<01:16, 49.29it/s]

Extracting GLCM features:  56%|█████▌    | 4698/8455 [01:27<01:18, 47.73it/s]

Extracting GLCM features:  56%|█████▌    | 4703/8455 [01:27<01:18, 47.65it/s]

Extracting GLCM features:  56%|█████▌    | 4708/8455 [01:27<01:24, 44.28it/s]

Extracting GLCM features:  56%|█████▌    | 4716/8455 [01:28<01:12, 51.92it/s]

Extracting GLCM features:  56%|█████▌    | 4725/8455 [01:28<01:01, 60.17it/s]

Extracting GLCM features:  56%|█████▌    | 4733/8455 [01:28<00:57, 65.05it/s]

Extracting GLCM features:  56%|█████▌    | 4741/8455 [01:28<00:53, 68.79it/s]

Extracting GLCM features:  56%|█████▌    | 4751/8455 [01:28<00:48, 75.68it/s]

Extracting GLCM features:  56%|█████▋    | 4759/8455 [01:28<00:48, 76.89it/s]

Extracting GLCM features:  56%|█████▋    | 4767/8455 [01:28<00:47, 77.66it/s]

Extracting GLCM features:  56%|█████▋    | 4775/8455 [01:28<00:49, 75.05it/s]

Extracting GLCM features:  57%|█████▋    | 4783/8455 [01:28<00:52, 69.75it/s]

Extracting GLCM features:  57%|█████▋    | 4791/8455 [01:29<00:54, 67.27it/s]

Extracting GLCM features:  57%|█████▋    | 4798/8455 [01:29<00:54, 67.62it/s]

Extracting GLCM features:  57%|█████▋    | 4806/8455 [01:29<00:52, 70.17it/s]

Extracting GLCM features:  57%|█████▋    | 4815/8455 [01:29<00:49, 73.89it/s]

Extracting GLCM features:  57%|█████▋    | 4823/8455 [01:29<00:50, 72.39it/s]

Extracting GLCM features:  57%|█████▋    | 4832/8455 [01:29<00:47, 75.96it/s]

Extracting GLCM features:  57%|█████▋    | 4840/8455 [01:29<00:47, 75.85it/s]

Extracting GLCM features:  57%|█████▋    | 4848/8455 [01:29<00:51, 70.33it/s]

Extracting GLCM features:  57%|█████▋    | 4856/8455 [01:29<00:52, 68.94it/s]

Extracting GLCM features:  58%|█████▊    | 4863/8455 [01:30<00:55, 64.75it/s]

Extracting GLCM features:  58%|█████▊    | 4870/8455 [01:30<00:57, 62.51it/s]

Extracting GLCM features:  58%|█████▊    | 4878/8455 [01:30<00:54, 65.56it/s]

Extracting GLCM features:  58%|█████▊    | 4888/8455 [01:30<00:49, 72.54it/s]

Extracting GLCM features:  58%|█████▊    | 4896/8455 [01:30<00:50, 70.94it/s]

Extracting GLCM features:  58%|█████▊    | 4904/8455 [01:30<00:49, 72.40it/s]

Extracting GLCM features:  58%|█████▊    | 4913/8455 [01:30<00:46, 76.74it/s]

Extracting GLCM features:  58%|█████▊    | 4923/8455 [01:30<00:43, 81.43it/s]

Extracting GLCM features:  58%|█████▊    | 4932/8455 [01:30<00:43, 81.82it/s]

Extracting GLCM features:  58%|█████▊    | 4941/8455 [01:31<00:49, 70.71it/s]

Extracting GLCM features:  59%|█████▊    | 4949/8455 [01:31<00:52, 67.29it/s]

Extracting GLCM features:  59%|█████▊    | 4956/8455 [01:31<00:51, 67.95it/s]

Extracting GLCM features:  59%|█████▊    | 4964/8455 [01:31<00:51, 67.54it/s]

Extracting GLCM features:  59%|█████▉    | 4971/8455 [01:31<00:55, 62.96it/s]

Extracting GLCM features:  59%|█████▉    | 4980/8455 [01:31<00:51, 67.41it/s]

Extracting GLCM features:  59%|█████▉    | 4988/8455 [01:31<00:49, 70.37it/s]

Extracting GLCM features:  59%|█████▉    | 4996/8455 [01:31<00:50, 68.67it/s]

Extracting GLCM features:  59%|█████▉    | 5003/8455 [01:32<00:50, 68.82it/s]

Extracting GLCM features:  59%|█████▉    | 5011/8455 [01:32<00:48, 71.48it/s]

Extracting GLCM features:  59%|█████▉    | 5019/8455 [01:32<00:48, 70.82it/s]

Extracting GLCM features:  59%|█████▉    | 5027/8455 [01:32<00:49, 68.65it/s]

Extracting GLCM features:  60%|█████▉    | 5034/8455 [01:32<00:51, 67.06it/s]

Extracting GLCM features:  60%|█████▉    | 5041/8455 [01:32<00:52, 64.46it/s]

Extracting GLCM features:  60%|█████▉    | 5048/8455 [01:32<00:52, 64.91it/s]

Extracting GLCM features:  60%|█████▉    | 5056/8455 [01:32<00:50, 67.70it/s]

Extracting GLCM features:  60%|█████▉    | 5064/8455 [01:32<00:48, 70.12it/s]

Extracting GLCM features:  60%|█████▉    | 5072/8455 [01:33<00:49, 69.03it/s]

Extracting GLCM features:  60%|██████    | 5079/8455 [01:33<00:48, 69.17it/s]

Extracting GLCM features:  60%|██████    | 5086/8455 [01:33<00:49, 68.21it/s]

Extracting GLCM features:  60%|██████    | 5093/8455 [01:33<00:51, 65.30it/s]

Extracting GLCM features:  60%|██████    | 5100/8455 [01:33<00:51, 65.11it/s]

Extracting GLCM features:  60%|██████    | 5108/8455 [01:33<00:49, 67.14it/s]

Extracting GLCM features:  61%|██████    | 5116/8455 [01:33<00:48, 69.33it/s]

Extracting GLCM features:  61%|██████    | 5124/8455 [01:33<00:46, 71.99it/s]

Extracting GLCM features:  61%|██████    | 5132/8455 [01:33<00:44, 73.92it/s]

Extracting GLCM features:  61%|██████    | 5140/8455 [01:34<00:44, 74.12it/s]

Extracting GLCM features:  61%|██████    | 5148/8455 [01:34<00:45, 72.76it/s]

Extracting GLCM features:  61%|██████    | 5156/8455 [01:34<00:45, 72.66it/s]

Extracting GLCM features:  61%|██████    | 5165/8455 [01:34<00:43, 75.58it/s]

Extracting GLCM features:  61%|██████    | 5173/8455 [01:34<00:44, 73.76it/s]

Extracting GLCM features:  61%|██████▏   | 5181/8455 [01:34<00:48, 67.03it/s]

Extracting GLCM features:  61%|██████▏   | 5188/8455 [01:34<00:54, 60.01it/s]

Extracting GLCM features:  61%|██████▏   | 5196/8455 [01:34<00:50, 64.33it/s]

Extracting GLCM features:  62%|██████▏   | 5203/8455 [01:35<00:53, 60.71it/s]

Extracting GLCM features:  62%|██████▏   | 5210/8455 [01:35<00:54, 59.45it/s]

Extracting GLCM features:  62%|██████▏   | 5218/8455 [01:35<00:50, 63.75it/s]

Extracting GLCM features:  62%|██████▏   | 5225/8455 [01:35<00:51, 63.04it/s]

Extracting GLCM features:  62%|██████▏   | 5232/8455 [01:35<00:55, 57.92it/s]

Extracting GLCM features:  62%|██████▏   | 5239/8455 [01:35<00:52, 60.77it/s]

Extracting GLCM features:  62%|██████▏   | 5247/8455 [01:35<00:50, 63.44it/s]

Extracting GLCM features:  62%|██████▏   | 5254/8455 [01:35<00:55, 57.45it/s]

Extracting GLCM features:  62%|██████▏   | 5260/8455 [01:36<00:57, 55.17it/s]

Extracting GLCM features:  62%|██████▏   | 5267/8455 [01:36<00:54, 58.19it/s]

Extracting GLCM features:  62%|██████▏   | 5274/8455 [01:36<00:53, 59.35it/s]

Extracting GLCM features:  62%|██████▏   | 5281/8455 [01:36<00:53, 59.55it/s]

Extracting GLCM features:  63%|██████▎   | 5288/8455 [01:36<00:51, 61.32it/s]

Extracting GLCM features:  63%|██████▎   | 5295/8455 [01:36<00:51, 61.82it/s]

Extracting GLCM features:  63%|██████▎   | 5303/8455 [01:36<00:49, 63.50it/s]

Extracting GLCM features:  63%|██████▎   | 5311/8455 [01:36<00:47, 66.77it/s]

Extracting GLCM features:  63%|██████▎   | 5318/8455 [01:36<00:52, 60.17it/s]

Extracting GLCM features:  63%|██████▎   | 5325/8455 [01:37<00:53, 58.89it/s]

Extracting GLCM features:  63%|██████▎   | 5333/8455 [01:37<00:49, 62.73it/s]

Extracting GLCM features:  63%|██████▎   | 5341/8455 [01:37<00:46, 67.29it/s]

Extracting GLCM features:  63%|██████▎   | 5351/8455 [01:37<00:44, 70.27it/s]

Extracting GLCM features:  63%|██████▎   | 5361/8455 [01:37<00:39, 77.90it/s]

Extracting GLCM features:  64%|██████▎   | 5370/8455 [01:37<00:38, 80.40it/s]

Extracting GLCM features:  64%|██████▎   | 5379/8455 [01:37<00:37, 81.69it/s]

Extracting GLCM features:  64%|██████▎   | 5388/8455 [01:37<00:36, 83.54it/s]

Extracting GLCM features:  64%|██████▍   | 5397/8455 [01:37<00:36, 84.18it/s]

Extracting GLCM features:  64%|██████▍   | 5406/8455 [01:38<00:39, 78.16it/s]

Extracting GLCM features:  64%|██████▍   | 5414/8455 [01:38<00:46, 66.09it/s]

Extracting GLCM features:  64%|██████▍   | 5423/8455 [01:38<00:43, 70.05it/s]

Extracting GLCM features:  64%|██████▍   | 5432/8455 [01:38<00:40, 74.12it/s]

Extracting GLCM features:  64%|██████▍   | 5441/8455 [01:38<00:38, 77.69it/s]

Extracting GLCM features:  64%|██████▍   | 5451/8455 [01:38<00:36, 81.61it/s]

Extracting GLCM features:  65%|██████▍   | 5460/8455 [01:38<00:36, 82.31it/s]

Extracting GLCM features:  65%|██████▍   | 5469/8455 [01:38<00:35, 84.42it/s]

Extracting GLCM features:  65%|██████▍   | 5478/8455 [01:38<00:34, 85.56it/s]

Extracting GLCM features:  65%|██████▍   | 5487/8455 [01:39<00:34, 84.89it/s]

Extracting GLCM features:  65%|██████▌   | 5496/8455 [01:39<00:34, 85.31it/s]

Extracting GLCM features:  65%|██████▌   | 5505/8455 [01:39<00:34, 84.82it/s]

Extracting GLCM features:  65%|██████▌   | 5514/8455 [01:39<00:34, 85.11it/s]

Extracting GLCM features:  65%|██████▌   | 5523/8455 [01:39<00:34, 85.70it/s]

Extracting GLCM features:  65%|██████▌   | 5532/8455 [01:39<00:33, 86.48it/s]

Extracting GLCM features:  66%|██████▌   | 5541/8455 [01:39<00:35, 82.21it/s]

Extracting GLCM features:  66%|██████▌   | 5550/8455 [01:39<00:35, 82.29it/s]

Extracting GLCM features:  66%|██████▌   | 5559/8455 [01:39<00:35, 80.98it/s]

Extracting GLCM features:  66%|██████▌   | 5568/8455 [01:40<00:35, 81.23it/s]

Extracting GLCM features:  66%|██████▌   | 5577/8455 [01:40<00:35, 80.10it/s]

Extracting GLCM features:  66%|██████▌   | 5586/8455 [01:40<00:35, 81.49it/s]

Extracting GLCM features:  66%|██████▌   | 5596/8455 [01:40<00:33, 84.35it/s]

Extracting GLCM features:  66%|██████▋   | 5605/8455 [01:40<00:33, 85.90it/s]

Extracting GLCM features:  66%|██████▋   | 5615/8455 [01:40<00:31, 88.92it/s]

Extracting GLCM features:  67%|██████▋   | 5624/8455 [01:40<00:31, 88.95it/s]

Extracting GLCM features:  67%|██████▋   | 5633/8455 [01:40<00:31, 88.75it/s]

Extracting GLCM features:  67%|██████▋   | 5643/8455 [01:40<00:34, 81.31it/s]

Extracting GLCM features:  67%|██████▋   | 5653/8455 [01:41<00:33, 84.10it/s]

Extracting GLCM features:  67%|██████▋   | 5663/8455 [01:41<00:32, 87.02it/s]

Extracting GLCM features:  67%|██████▋   | 5672/8455 [01:41<00:32, 86.19it/s]

Extracting GLCM features:  67%|██████▋   | 5681/8455 [01:41<00:32, 86.60it/s]

Extracting GLCM features:  67%|██████▋   | 5691/8455 [01:41<00:30, 89.30it/s]

Extracting GLCM features:  67%|██████▋   | 5700/8455 [01:41<00:34, 80.31it/s]

Extracting GLCM features:  68%|██████▊   | 5709/8455 [01:41<00:33, 81.61it/s]

Extracting GLCM features:  68%|██████▊   | 5718/8455 [01:41<00:32, 83.75it/s]

Extracting GLCM features:  68%|██████▊   | 5727/8455 [01:41<00:37, 72.08it/s]

Extracting GLCM features:  68%|██████▊   | 5735/8455 [01:42<00:39, 69.41it/s]

Extracting GLCM features:  68%|██████▊   | 5744/8455 [01:42<00:37, 72.61it/s]

Extracting GLCM features:  68%|██████▊   | 5753/8455 [01:42<00:35, 76.81it/s]

Extracting GLCM features:  68%|██████▊   | 5763/8455 [01:42<00:33, 81.36it/s]

Extracting GLCM features:  68%|██████▊   | 5773/8455 [01:42<00:32, 83.56it/s]

Extracting GLCM features:  68%|██████▊   | 5783/8455 [01:42<00:30, 86.39it/s]

Extracting GLCM features:  69%|██████▊   | 5792/8455 [01:42<00:31, 85.39it/s]

Extracting GLCM features:  69%|██████▊   | 5801/8455 [01:42<00:31, 84.08it/s]

Extracting GLCM features:  69%|██████▊   | 5810/8455 [01:42<00:31, 85.22it/s]

Extracting GLCM features:  69%|██████▉   | 5819/8455 [01:43<00:33, 78.48it/s]

Extracting GLCM features:  69%|██████▉   | 5827/8455 [01:43<00:35, 74.41it/s]

Extracting GLCM features:  69%|██████▉   | 5836/8455 [01:43<00:34, 76.35it/s]

Extracting GLCM features:  69%|██████▉   | 5845/8455 [01:43<00:33, 78.97it/s]

Extracting GLCM features:  69%|██████▉   | 5854/8455 [01:43<00:32, 81.02it/s]

Extracting GLCM features:  69%|██████▉   | 5863/8455 [01:43<00:31, 81.78it/s]

Extracting GLCM features:  69%|██████▉   | 5872/8455 [01:43<00:31, 81.82it/s]

Extracting GLCM features:  70%|██████▉   | 5881/8455 [01:43<00:30, 83.13it/s]

Extracting GLCM features:  70%|██████▉   | 5890/8455 [01:43<00:30, 83.75it/s]

Extracting GLCM features:  70%|██████▉   | 5899/8455 [01:44<00:34, 75.18it/s]

Extracting GLCM features:  70%|██████▉   | 5907/8455 [01:44<00:34, 73.04it/s]

Extracting GLCM features:  70%|██████▉   | 5916/8455 [01:44<00:33, 75.10it/s]

Extracting GLCM features:  70%|███████   | 5925/8455 [01:44<00:32, 78.16it/s]

Extracting GLCM features:  70%|███████   | 5935/8455 [01:44<00:31, 81.22it/s]

Extracting GLCM features:  70%|███████   | 5944/8455 [01:44<00:31, 80.08it/s]

Extracting GLCM features:  70%|███████   | 5953/8455 [01:44<00:31, 78.23it/s]

Extracting GLCM features:  71%|███████   | 5961/8455 [01:44<00:33, 75.40it/s]

Extracting GLCM features:  71%|███████   | 5969/8455 [01:45<00:32, 76.49it/s]

Extracting GLCM features:  71%|███████   | 5978/8455 [01:45<00:31, 78.14it/s]

Extracting GLCM features:  71%|███████   | 5986/8455 [01:45<00:34, 72.58it/s]

Extracting GLCM features:  71%|███████   | 5994/8455 [01:45<00:33, 72.62it/s]

Extracting GLCM features:  71%|███████   | 6002/8455 [01:45<00:40, 59.93it/s]

Extracting GLCM features:  71%|███████   | 6009/8455 [01:45<00:45, 53.68it/s]

Extracting GLCM features:  71%|███████   | 6015/8455 [01:45<00:45, 53.94it/s]

Extracting GLCM features:  71%|███████   | 6021/8455 [01:45<00:45, 53.76it/s]

Extracting GLCM features:  71%|███████▏  | 6027/8455 [01:46<00:45, 53.82it/s]

Extracting GLCM features:  71%|███████▏  | 6033/8455 [01:46<00:47, 51.28it/s]

Extracting GLCM features:  71%|███████▏  | 6039/8455 [01:46<00:48, 49.49it/s]

Extracting GLCM features:  71%|███████▏  | 6045/8455 [01:46<00:49, 48.76it/s]

Extracting GLCM features:  72%|███████▏  | 6051/8455 [01:46<00:48, 49.51it/s]

Extracting GLCM features:  72%|███████▏  | 6057/8455 [01:46<00:48, 49.48it/s]

Extracting GLCM features:  72%|███████▏  | 6063/8455 [01:46<00:47, 50.22it/s]

Extracting GLCM features:  72%|███████▏  | 6069/8455 [01:46<00:45, 52.15it/s]

Extracting GLCM features:  72%|███████▏  | 6075/8455 [01:47<00:45, 52.84it/s]

Extracting GLCM features:  72%|███████▏  | 6081/8455 [01:47<00:47, 50.32it/s]

Extracting GLCM features:  72%|███████▏  | 6087/8455 [01:47<00:48, 48.63it/s]

Extracting GLCM features:  72%|███████▏  | 6092/8455 [01:47<00:48, 48.41it/s]

Extracting GLCM features:  72%|███████▏  | 6097/8455 [01:47<00:48, 48.37it/s]

Extracting GLCM features:  72%|███████▏  | 6103/8455 [01:47<00:46, 50.36it/s]

Extracting GLCM features:  72%|███████▏  | 6109/8455 [01:47<00:46, 50.96it/s]

Extracting GLCM features:  72%|███████▏  | 6115/8455 [01:47<00:45, 51.00it/s]

Extracting GLCM features:  72%|███████▏  | 6121/8455 [01:47<00:46, 49.96it/s]

Extracting GLCM features:  72%|███████▏  | 6128/8455 [01:48<00:43, 53.29it/s]

Extracting GLCM features:  73%|███████▎  | 6134/8455 [01:48<00:42, 53.98it/s]

Extracting GLCM features:  73%|███████▎  | 6140/8455 [01:48<00:43, 53.70it/s]

Extracting GLCM features:  73%|███████▎  | 6146/8455 [01:48<00:41, 54.98it/s]

Extracting GLCM features:  73%|███████▎  | 6152/8455 [01:48<00:41, 55.16it/s]

Extracting GLCM features:  73%|███████▎  | 6158/8455 [01:48<00:41, 55.84it/s]

Extracting GLCM features:  73%|███████▎  | 6164/8455 [01:48<00:43, 53.25it/s]

Extracting GLCM features:  73%|███████▎  | 6170/8455 [01:48<00:43, 52.57it/s]

Extracting GLCM features:  73%|███████▎  | 6176/8455 [01:48<00:44, 51.48it/s]

Extracting GLCM features:  73%|███████▎  | 6182/8455 [01:49<00:43, 52.04it/s]

Extracting GLCM features:  73%|███████▎  | 6188/8455 [01:49<00:44, 51.34it/s]

Extracting GLCM features:  73%|███████▎  | 6194/8455 [01:49<00:44, 50.51it/s]

Extracting GLCM features:  73%|███████▎  | 6200/8455 [01:49<00:46, 48.73it/s]

Extracting GLCM features:  73%|███████▎  | 6205/8455 [01:49<00:48, 46.34it/s]

Extracting GLCM features:  73%|███████▎  | 6210/8455 [01:49<00:52, 43.06it/s]

Extracting GLCM features:  74%|███████▎  | 6215/8455 [01:49<00:54, 41.18it/s]

Extracting GLCM features:  74%|███████▎  | 6220/8455 [01:50<00:58, 38.06it/s]

Extracting GLCM features:  74%|███████▎  | 6224/8455 [01:50<01:01, 36.39it/s]

Extracting GLCM features:  74%|███████▎  | 6228/8455 [01:50<01:00, 36.53it/s]

Extracting GLCM features:  74%|███████▎  | 6233/8455 [01:50<00:57, 38.87it/s]

Extracting GLCM features:  74%|███████▍  | 6238/8455 [01:50<00:55, 39.73it/s]

Extracting GLCM features:  74%|███████▍  | 6243/8455 [01:50<00:52, 41.75it/s]

Extracting GLCM features:  74%|███████▍  | 6249/8455 [01:50<00:49, 44.37it/s]

Extracting GLCM features:  74%|███████▍  | 6254/8455 [01:50<00:48, 45.72it/s]

Extracting GLCM features:  74%|███████▍  | 6260/8455 [01:50<00:45, 48.73it/s]

Extracting GLCM features:  74%|███████▍  | 6267/8455 [01:51<00:42, 51.36it/s]

Extracting GLCM features:  74%|███████▍  | 6273/8455 [01:51<00:42, 50.76it/s]

Extracting GLCM features:  74%|███████▍  | 6279/8455 [01:51<00:45, 48.32it/s]

Extracting GLCM features:  74%|███████▍  | 6284/8455 [01:51<00:49, 43.96it/s]

Extracting GLCM features:  74%|███████▍  | 6289/8455 [01:51<00:52, 40.98it/s]

Extracting GLCM features:  74%|███████▍  | 6296/8455 [01:51<00:44, 47.99it/s]

Extracting GLCM features:  75%|███████▍  | 6302/8455 [01:51<00:43, 49.67it/s]

Extracting GLCM features:  75%|███████▍  | 6311/8455 [01:51<00:36, 58.59it/s]

Extracting GLCM features:  75%|███████▍  | 6318/8455 [01:52<00:36, 59.16it/s]

Extracting GLCM features:  75%|███████▍  | 6326/8455 [01:52<00:32, 64.72it/s]

Extracting GLCM features:  75%|███████▍  | 6334/8455 [01:52<00:31, 67.13it/s]

Extracting GLCM features:  75%|███████▌  | 6342/8455 [01:52<00:30, 70.30it/s]

Extracting GLCM features:  75%|███████▌  | 6352/8455 [01:52<00:26, 78.42it/s]

Extracting GLCM features:  75%|███████▌  | 6361/8455 [01:52<00:25, 81.38it/s]

Extracting GLCM features:  75%|███████▌  | 6371/8455 [01:52<00:25, 83.07it/s]

Extracting GLCM features:  75%|███████▌  | 6382/8455 [01:52<00:23, 88.31it/s]

Extracting GLCM features:  76%|███████▌  | 6392/8455 [01:52<00:22, 91.49it/s]

Extracting GLCM features:  76%|███████▌  | 6402/8455 [01:52<00:22, 90.69it/s]

Extracting GLCM features:  76%|███████▌  | 6413/8455 [01:53<00:21, 93.83it/s]

Extracting GLCM features:  76%|███████▌  | 6423/8455 [01:53<00:21, 93.09it/s]

Extracting GLCM features:  76%|███████▌  | 6433/8455 [01:53<00:21, 93.20it/s]

Extracting GLCM features:  76%|███████▌  | 6444/8455 [01:53<00:21, 95.33it/s]

Extracting GLCM features:  76%|███████▋  | 6455/8455 [01:53<00:20, 96.79it/s]

Extracting GLCM features:  76%|███████▋  | 6465/8455 [01:53<00:20, 97.07it/s]

Extracting GLCM features:  77%|███████▋  | 6475/8455 [01:53<00:20, 95.21it/s]

Extracting GLCM features:  77%|███████▋  | 6485/8455 [01:53<00:20, 95.88it/s]

Extracting GLCM features:  77%|███████▋  | 6495/8455 [01:53<00:20, 96.31it/s]

Extracting GLCM features:  77%|███████▋  | 6505/8455 [01:54<00:20, 96.12it/s]

Extracting GLCM features:  77%|███████▋  | 6515/8455 [01:54<00:20, 94.34it/s]

Extracting GLCM features:  77%|███████▋  | 6525/8455 [01:54<00:20, 92.33it/s]

Extracting GLCM features:  77%|███████▋  | 6535/8455 [01:54<00:20, 91.59it/s]

Extracting GLCM features:  77%|███████▋  | 6545/8455 [01:54<00:20, 92.73it/s]

Extracting GLCM features:  78%|███████▊  | 6555/8455 [01:54<00:21, 89.90it/s]

Extracting GLCM features:  78%|███████▊  | 6565/8455 [01:54<00:24, 78.68it/s]

Extracting GLCM features:  78%|███████▊  | 6574/8455 [01:54<00:26, 70.56it/s]

Extracting GLCM features:  78%|███████▊  | 6582/8455 [01:55<00:26, 71.20it/s]

Extracting GLCM features:  78%|███████▊  | 6590/8455 [01:55<00:27, 68.36it/s]

Extracting GLCM features:  78%|███████▊  | 6597/8455 [01:55<00:27, 68.74it/s]

Extracting GLCM features:  78%|███████▊  | 6605/8455 [01:55<00:25, 71.65it/s]

Extracting GLCM features:  78%|███████▊  | 6614/8455 [01:55<00:24, 75.38it/s]

Extracting GLCM features:  78%|███████▊  | 6623/8455 [01:55<00:23, 77.39it/s]

Extracting GLCM features:  78%|███████▊  | 6631/8455 [01:55<00:23, 76.03it/s]

Extracting GLCM features:  79%|███████▊  | 6639/8455 [01:55<00:25, 72.06it/s]

Extracting GLCM features:  79%|███████▊  | 6648/8455 [01:55<00:23, 75.96it/s]

Extracting GLCM features:  79%|███████▊  | 6656/8455 [01:56<00:23, 76.56it/s]

Extracting GLCM features:  79%|███████▉  | 6665/8455 [01:56<00:22, 78.64it/s]

Extracting GLCM features:  79%|███████▉  | 6674/8455 [01:56<00:22, 80.76it/s]

Extracting GLCM features:  79%|███████▉  | 6683/8455 [01:56<00:21, 82.47it/s]

Extracting GLCM features:  79%|███████▉  | 6693/8455 [01:56<00:20, 84.83it/s]

Extracting GLCM features:  79%|███████▉  | 6702/8455 [01:56<00:23, 73.34it/s]

Extracting GLCM features:  79%|███████▉  | 6710/8455 [01:56<00:23, 74.16it/s]

Extracting GLCM features:  79%|███████▉  | 6718/8455 [01:56<00:23, 75.38it/s]

Extracting GLCM features:  80%|███████▉  | 6727/8455 [01:56<00:22, 76.85it/s]

Extracting GLCM features:  80%|███████▉  | 6735/8455 [01:57<00:22, 76.21it/s]

Extracting GLCM features:  80%|███████▉  | 6744/8455 [01:57<00:21, 78.06it/s]

Extracting GLCM features:  80%|███████▉  | 6753/8455 [01:57<00:21, 78.83it/s]

Extracting GLCM features:  80%|███████▉  | 6761/8455 [01:57<00:24, 69.20it/s]

Extracting GLCM features:  80%|████████  | 6769/8455 [01:57<00:31, 53.62it/s]

Extracting GLCM features:  80%|████████  | 6778/8455 [01:57<00:28, 59.87it/s]

Extracting GLCM features:  80%|████████  | 6785/8455 [01:57<00:27, 60.29it/s]

Extracting GLCM features:  80%|████████  | 6792/8455 [01:57<00:27, 59.79it/s]

Extracting GLCM features:  80%|████████  | 6799/8455 [01:58<00:26, 62.06it/s]

Extracting GLCM features:  80%|████████  | 6806/8455 [01:58<00:26, 63.37it/s]

Extracting GLCM features:  81%|████████  | 6814/8455 [01:58<00:25, 65.55it/s]

Extracting GLCM features:  81%|████████  | 6821/8455 [01:58<00:24, 65.57it/s]

Extracting GLCM features:  81%|████████  | 6829/8455 [01:58<00:24, 67.37it/s]

Extracting GLCM features:  81%|████████  | 6837/8455 [01:58<00:23, 68.73it/s]

Extracting GLCM features:  81%|████████  | 6845/8455 [01:58<00:22, 71.38it/s]

Extracting GLCM features:  81%|████████  | 6853/8455 [01:58<00:22, 71.77it/s]

Extracting GLCM features:  81%|████████  | 6861/8455 [01:58<00:22, 71.59it/s]

Extracting GLCM features:  81%|████████  | 6869/8455 [01:59<00:22, 70.44it/s]

Extracting GLCM features:  81%|████████▏ | 6877/8455 [01:59<00:22, 70.86it/s]

Extracting GLCM features:  81%|████████▏ | 6885/8455 [01:59<00:22, 68.83it/s]

Extracting GLCM features:  82%|████████▏ | 6892/8455 [01:59<00:23, 67.71it/s]

Extracting GLCM features:  82%|████████▏ | 6900/8455 [01:59<00:22, 69.60it/s]

Extracting GLCM features:  82%|████████▏ | 6908/8455 [01:59<00:21, 70.70it/s]

Extracting GLCM features:  82%|████████▏ | 6916/8455 [01:59<00:22, 69.39it/s]

Extracting GLCM features:  82%|████████▏ | 6923/8455 [01:59<00:23, 64.33it/s]

Extracting GLCM features:  82%|████████▏ | 6930/8455 [02:00<00:26, 58.42it/s]

Extracting GLCM features:  82%|████████▏ | 6936/8455 [02:00<00:27, 56.21it/s]

Extracting GLCM features:  82%|████████▏ | 6943/8455 [02:00<00:25, 58.84it/s]

Extracting GLCM features:  82%|████████▏ | 6949/8455 [02:00<00:26, 57.90it/s]

Extracting GLCM features:  82%|████████▏ | 6955/8455 [02:00<00:26, 57.11it/s]

Extracting GLCM features:  82%|████████▏ | 6962/8455 [02:00<00:25, 59.12it/s]

Extracting GLCM features:  82%|████████▏ | 6970/8455 [02:00<00:23, 62.63it/s]

Extracting GLCM features:  83%|████████▎ | 6978/8455 [02:00<00:22, 65.42it/s]

Extracting GLCM features:  83%|████████▎ | 6985/8455 [02:00<00:22, 64.65it/s]

Extracting GLCM features:  83%|████████▎ | 6992/8455 [02:01<00:23, 62.77it/s]

Extracting GLCM features:  83%|████████▎ | 6999/8455 [02:01<00:23, 61.92it/s]

Extracting GLCM features:  83%|████████▎ | 7006/8455 [02:01<00:24, 59.55it/s]

Extracting GLCM features:  83%|████████▎ | 7012/8455 [02:01<00:25, 57.40it/s]

Extracting GLCM features:  83%|████████▎ | 7019/8455 [02:01<00:24, 58.97it/s]

Extracting GLCM features:  83%|████████▎ | 7025/8455 [02:01<00:29, 48.27it/s]

Extracting GLCM features:  83%|████████▎ | 7031/8455 [02:01<00:32, 43.97it/s]

Extracting GLCM features:  83%|████████▎ | 7036/8455 [02:01<00:33, 42.46it/s]

Extracting GLCM features:  83%|████████▎ | 7041/8455 [02:02<00:35, 39.38it/s]

Extracting GLCM features:  83%|████████▎ | 7046/8455 [02:02<00:38, 36.60it/s]

Extracting GLCM features:  83%|████████▎ | 7050/8455 [02:02<00:39, 36.01it/s]

Extracting GLCM features:  83%|████████▎ | 7055/8455 [02:02<00:37, 37.63it/s]

Extracting GLCM features:  84%|████████▎ | 7060/8455 [02:02<00:35, 38.98it/s]

Extracting GLCM features:  84%|████████▎ | 7065/8455 [02:02<00:35, 39.69it/s]

Extracting GLCM features:  84%|████████▎ | 7070/8455 [02:02<00:34, 39.73it/s]

Extracting GLCM features:  84%|████████▎ | 7075/8455 [02:03<00:34, 39.89it/s]

Extracting GLCM features:  84%|████████▎ | 7080/8455 [02:03<00:34, 39.87it/s]

Extracting GLCM features:  84%|████████▍ | 7085/8455 [02:03<00:34, 39.16it/s]

Extracting GLCM features:  84%|████████▍ | 7089/8455 [02:03<00:36, 37.87it/s]

Extracting GLCM features:  84%|████████▍ | 7093/8455 [02:03<00:36, 37.01it/s]

Extracting GLCM features:  84%|████████▍ | 7097/8455 [02:03<00:36, 36.96it/s]

Extracting GLCM features:  84%|████████▍ | 7101/8455 [02:03<00:36, 37.40it/s]

Extracting GLCM features:  84%|████████▍ | 7106/8455 [02:03<00:35, 38.01it/s]

Extracting GLCM features:  84%|████████▍ | 7110/8455 [02:03<00:36, 36.60it/s]

Extracting GLCM features:  84%|████████▍ | 7115/8455 [02:04<00:33, 40.12it/s]

Extracting GLCM features:  84%|████████▍ | 7120/8455 [02:04<00:31, 41.72it/s]

Extracting GLCM features:  84%|████████▍ | 7125/8455 [02:04<00:33, 39.16it/s]

Extracting GLCM features:  84%|████████▍ | 7129/8455 [02:04<00:35, 36.89it/s]

Extracting GLCM features:  84%|████████▍ | 7133/8455 [02:04<00:39, 33.45it/s]

Extracting GLCM features:  84%|████████▍ | 7137/8455 [02:04<00:40, 32.19it/s]

Extracting GLCM features:  84%|████████▍ | 7141/8455 [02:04<00:38, 33.81it/s]

Extracting GLCM features:  85%|████████▍ | 7146/8455 [02:04<00:35, 37.27it/s]

Extracting GLCM features:  85%|████████▍ | 7151/8455 [02:05<00:32, 40.60it/s]

Extracting GLCM features:  85%|████████▍ | 7156/8455 [02:05<00:31, 40.82it/s]

Extracting GLCM features:  85%|████████▍ | 7162/8455 [02:05<00:28, 45.06it/s]

Extracting GLCM features:  85%|████████▍ | 7168/8455 [02:05<00:27, 46.62it/s]

Extracting GLCM features:  85%|████████▍ | 7173/8455 [02:05<00:27, 46.18it/s]

Extracting GLCM features:  85%|████████▍ | 7179/8455 [02:05<00:26, 47.93it/s]

Extracting GLCM features:  85%|████████▍ | 7185/8455 [02:05<00:25, 49.82it/s]

Extracting GLCM features:  85%|████████▌ | 7191/8455 [02:05<00:24, 52.15it/s]

Extracting GLCM features:  85%|████████▌ | 7197/8455 [02:05<00:23, 52.93it/s]

Extracting GLCM features:  85%|████████▌ | 7203/8455 [02:06<00:22, 54.69it/s]

Extracting GLCM features:  85%|████████▌ | 7210/8455 [02:06<00:21, 57.73it/s]

Extracting GLCM features:  85%|████████▌ | 7217/8455 [02:06<00:20, 59.24it/s]

Extracting GLCM features:  85%|████████▌ | 7223/8455 [02:06<00:21, 57.40it/s]

Extracting GLCM features:  85%|████████▌ | 7229/8455 [02:06<00:21, 57.25it/s]

Extracting GLCM features:  86%|████████▌ | 7236/8455 [02:06<00:20, 59.71it/s]

Extracting GLCM features:  86%|████████▌ | 7243/8455 [02:06<00:19, 61.59it/s]

Extracting GLCM features:  86%|████████▌ | 7250/8455 [02:06<00:21, 55.62it/s]

Extracting GLCM features:  86%|████████▌ | 7256/8455 [02:07<00:23, 51.60it/s]

Extracting GLCM features:  86%|████████▌ | 7262/8455 [02:07<00:22, 53.66it/s]

Extracting GLCM features:  86%|████████▌ | 7268/8455 [02:07<00:23, 49.54it/s]

Extracting GLCM features:  86%|████████▌ | 7275/8455 [02:07<00:23, 51.24it/s]

Extracting GLCM features:  86%|████████▌ | 7281/8455 [02:07<00:22, 51.57it/s]

Extracting GLCM features:  86%|████████▌ | 7287/8455 [02:07<00:21, 53.21it/s]

Extracting GLCM features:  86%|████████▋ | 7294/8455 [02:07<00:20, 55.46it/s]

Extracting GLCM features:  86%|████████▋ | 7301/8455 [02:07<00:19, 58.25it/s]

Extracting GLCM features:  86%|████████▋ | 7307/8455 [02:07<00:19, 58.63it/s]

Extracting GLCM features:  87%|████████▋ | 7314/8455 [02:08<00:19, 59.78it/s]

Extracting GLCM features:  87%|████████▋ | 7321/8455 [02:08<00:20, 55.10it/s]

Extracting GLCM features:  87%|████████▋ | 7327/8455 [02:08<00:20, 55.39it/s]

Extracting GLCM features:  87%|████████▋ | 7333/8455 [02:08<00:21, 52.87it/s]

Extracting GLCM features:  87%|████████▋ | 7339/8455 [02:08<00:21, 52.64it/s]

Extracting GLCM features:  87%|████████▋ | 7345/8455 [02:08<00:21, 52.58it/s]

Extracting GLCM features:  87%|████████▋ | 7351/8455 [02:08<00:22, 49.10it/s]

Extracting GLCM features:  87%|████████▋ | 7357/8455 [02:08<00:21, 50.74it/s]

Extracting GLCM features:  87%|████████▋ | 7364/8455 [02:09<00:20, 54.06it/s]

Extracting GLCM features:  87%|████████▋ | 7371/8455 [02:09<00:19, 56.28it/s]

Extracting GLCM features:  87%|████████▋ | 7377/8455 [02:09<00:19, 55.43it/s]

Extracting GLCM features:  87%|████████▋ | 7383/8455 [02:09<00:19, 55.97it/s]

Extracting GLCM features:  87%|████████▋ | 7389/8455 [02:09<00:19, 55.99it/s]

Extracting GLCM features:  87%|████████▋ | 7395/8455 [02:09<00:20, 52.44it/s]

Extracting GLCM features:  88%|████████▊ | 7402/8455 [02:09<00:19, 55.03it/s]

Extracting GLCM features:  88%|████████▊ | 7409/8455 [02:09<00:18, 56.62it/s]

Extracting GLCM features:  88%|████████▊ | 7415/8455 [02:09<00:19, 53.74it/s]

Extracting GLCM features:  88%|████████▊ | 7422/8455 [02:10<00:18, 55.79it/s]

Extracting GLCM features:  88%|████████▊ | 7429/8455 [02:10<00:17, 57.74it/s]

Extracting GLCM features:  88%|████████▊ | 7436/8455 [02:10<00:17, 58.80it/s]

Extracting GLCM features:  88%|████████▊ | 7442/8455 [02:10<00:17, 58.19it/s]

Extracting GLCM features:  88%|████████▊ | 7448/8455 [02:10<00:17, 57.88it/s]

Extracting GLCM features:  88%|████████▊ | 7455/8455 [02:10<00:16, 59.01it/s]

Extracting GLCM features:  88%|████████▊ | 7461/8455 [02:10<00:18, 53.20it/s]

Extracting GLCM features:  88%|████████▊ | 7467/8455 [02:10<00:19, 50.60it/s]

Extracting GLCM features:  88%|████████▊ | 7474/8455 [02:10<00:17, 55.47it/s]

Extracting GLCM features:  88%|████████▊ | 7481/8455 [02:11<00:16, 57.73it/s]

Extracting GLCM features:  89%|████████▊ | 7487/8455 [02:11<00:16, 57.12it/s]

Extracting GLCM features:  89%|████████▊ | 7493/8455 [02:11<00:18, 50.99it/s]

Extracting GLCM features:  89%|████████▊ | 7499/8455 [02:11<00:19, 47.98it/s]

Extracting GLCM features:  89%|████████▉ | 7504/8455 [02:11<00:20, 45.32it/s]

Extracting GLCM features:  89%|████████▉ | 7509/8455 [02:11<00:21, 44.54it/s]

Extracting GLCM features:  89%|████████▉ | 7514/8455 [02:11<00:20, 45.79it/s]

Extracting GLCM features:  89%|████████▉ | 7519/8455 [02:11<00:20, 44.98it/s]

Extracting GLCM features:  89%|████████▉ | 7526/8455 [02:12<00:18, 51.29it/s]

Extracting GLCM features:  89%|████████▉ | 7535/8455 [02:12<00:15, 60.32it/s]

Extracting GLCM features:  89%|████████▉ | 7542/8455 [02:12<00:15, 57.57it/s]

Extracting GLCM features:  89%|████████▉ | 7552/8455 [02:12<00:13, 67.24it/s]

Extracting GLCM features:  89%|████████▉ | 7559/8455 [02:12<00:13, 66.90it/s]

Extracting GLCM features:  89%|████████▉ | 7566/8455 [02:12<00:13, 65.58it/s]

Extracting GLCM features:  90%|████████▉ | 7573/8455 [02:12<00:13, 63.96it/s]

Extracting GLCM features:  90%|████████▉ | 7580/8455 [02:12<00:15, 58.01it/s]

Extracting GLCM features:  90%|████████▉ | 7587/8455 [02:12<00:14, 60.49it/s]

Extracting GLCM features:  90%|████████▉ | 7594/8455 [02:13<00:14, 60.28it/s]

Extracting GLCM features:  90%|████████▉ | 7601/8455 [02:13<00:14, 59.81it/s]

Extracting GLCM features:  90%|████████▉ | 7608/8455 [02:13<00:14, 59.43it/s]

Extracting GLCM features:  90%|█████████ | 7614/8455 [02:13<00:14, 58.58it/s]

Extracting GLCM features:  90%|█████████ | 7621/8455 [02:13<00:14, 59.53it/s]

Extracting GLCM features:  90%|█████████ | 7628/8455 [02:13<00:13, 61.06it/s]

Extracting GLCM features:  90%|█████████ | 7635/8455 [02:13<00:13, 61.21it/s]

Extracting GLCM features:  90%|█████████ | 7642/8455 [02:13<00:13, 62.44it/s]

Extracting GLCM features:  90%|█████████ | 7649/8455 [02:14<00:13, 59.07it/s]

Extracting GLCM features:  91%|█████████ | 7656/8455 [02:14<00:13, 60.19it/s]

Extracting GLCM features:  91%|█████████ | 7663/8455 [02:14<00:13, 59.07it/s]

Extracting GLCM features:  91%|█████████ | 7670/8455 [02:14<00:13, 60.07it/s]

Extracting GLCM features:  91%|█████████ | 7677/8455 [02:14<00:12, 60.81it/s]

Extracting GLCM features:  91%|█████████ | 7684/8455 [02:14<00:12, 61.75it/s]

Extracting GLCM features:  91%|█████████ | 7691/8455 [02:14<00:12, 61.89it/s]

Extracting GLCM features:  91%|█████████ | 7698/8455 [02:14<00:13, 54.56it/s]

Extracting GLCM features:  91%|█████████ | 7705/8455 [02:14<00:13, 57.66it/s]

Extracting GLCM features:  91%|█████████ | 7711/8455 [02:15<00:13, 54.71it/s]

Extracting GLCM features:  91%|█████████▏| 7717/8455 [02:15<00:13, 56.04it/s]

Extracting GLCM features:  91%|█████████▏| 7723/8455 [02:15<00:13, 52.63it/s]

Extracting GLCM features:  91%|█████████▏| 7729/8455 [02:15<00:14, 51.69it/s]

Extracting GLCM features:  91%|█████████▏| 7735/8455 [02:15<00:14, 50.72it/s]

Extracting GLCM features:  92%|█████████▏| 7741/8455 [02:15<00:15, 47.28it/s]

Extracting GLCM features:  92%|█████████▏| 7747/8455 [02:15<00:14, 49.99it/s]

Extracting GLCM features:  92%|█████████▏| 7753/8455 [02:15<00:14, 47.16it/s]

Extracting GLCM features:  92%|█████████▏| 7758/8455 [02:16<00:15, 46.41it/s]

Extracting GLCM features:  92%|█████████▏| 7765/8455 [02:16<00:13, 51.09it/s]

Extracting GLCM features:  92%|█████████▏| 7771/8455 [02:16<00:14, 46.35it/s]

Extracting GLCM features:  92%|█████████▏| 7776/8455 [02:16<00:15, 44.81it/s]

Extracting GLCM features:  92%|█████████▏| 7782/8455 [02:16<00:13, 48.09it/s]

Extracting GLCM features:  92%|█████████▏| 7789/8455 [02:16<00:12, 52.16it/s]

Extracting GLCM features:  92%|█████████▏| 7795/8455 [02:16<00:12, 53.85it/s]

Extracting GLCM features:  92%|█████████▏| 7802/8455 [02:16<00:11, 56.98it/s]

Extracting GLCM features:  92%|█████████▏| 7809/8455 [02:17<00:11, 58.57it/s]

Extracting GLCM features:  92%|█████████▏| 7815/8455 [02:17<00:11, 56.97it/s]

Extracting GLCM features:  93%|█████████▎| 7821/8455 [02:17<00:11, 57.39it/s]

Extracting GLCM features:  93%|█████████▎| 7827/8455 [02:17<00:11, 55.47it/s]

Extracting GLCM features:  93%|█████████▎| 7833/8455 [02:17<00:11, 55.73it/s]

Extracting GLCM features:  93%|█████████▎| 7839/8455 [02:17<00:11, 55.10it/s]

Extracting GLCM features:  93%|█████████▎| 7845/8455 [02:17<00:11, 54.88it/s]

Extracting GLCM features:  93%|█████████▎| 7851/8455 [02:17<00:11, 54.04it/s]

Extracting GLCM features:  93%|█████████▎| 7858/8455 [02:17<00:10, 55.89it/s]

Extracting GLCM features:  93%|█████████▎| 7864/8455 [02:18<00:10, 55.73it/s]

Extracting GLCM features:  93%|█████████▎| 7870/8455 [02:18<00:11, 52.53it/s]

Extracting GLCM features:  93%|█████████▎| 7878/8455 [02:18<00:09, 59.49it/s]

Extracting GLCM features:  93%|█████████▎| 7885/8455 [02:18<00:10, 54.12it/s]

Extracting GLCM features:  93%|█████████▎| 7893/8455 [02:18<00:09, 59.52it/s]

Extracting GLCM features:  93%|█████████▎| 7903/8455 [02:18<00:07, 69.33it/s]

Extracting GLCM features:  94%|█████████▎| 7914/8455 [02:18<00:06, 78.50it/s]

Extracting GLCM features:  94%|█████████▎| 7923/8455 [02:18<00:06, 81.64it/s]

Extracting GLCM features:  94%|█████████▍| 7932/8455 [02:18<00:06, 81.06it/s]

Extracting GLCM features:  94%|█████████▍| 7941/8455 [02:19<00:06, 82.65it/s]

Extracting GLCM features:  94%|█████████▍| 7951/8455 [02:19<00:05, 86.49it/s]

Extracting GLCM features:  94%|█████████▍| 7960/8455 [02:19<00:05, 83.26it/s]

Extracting GLCM features:  94%|█████████▍| 7969/8455 [02:19<00:05, 82.52it/s]

Extracting GLCM features:  94%|█████████▍| 7978/8455 [02:19<00:05, 83.04it/s]

Extracting GLCM features:  94%|█████████▍| 7987/8455 [02:19<00:06, 77.89it/s]

Extracting GLCM features:  95%|█████████▍| 7995/8455 [02:19<00:06, 76.43it/s]

Extracting GLCM features:  95%|█████████▍| 8003/8455 [02:19<00:06, 73.78it/s]

Extracting GLCM features:  95%|█████████▍| 8012/8455 [02:19<00:05, 76.17it/s]

Extracting GLCM features:  95%|█████████▍| 8020/8455 [02:20<00:06, 71.06it/s]

Extracting GLCM features:  95%|█████████▍| 8028/8455 [02:20<00:06, 64.31it/s]

Extracting GLCM features:  95%|█████████▌| 8036/8455 [02:20<00:06, 67.10it/s]

Extracting GLCM features:  95%|█████████▌| 8045/8455 [02:20<00:05, 71.36it/s]

Extracting GLCM features:  95%|█████████▌| 8054/8455 [02:20<00:05, 73.72it/s]

Extracting GLCM features:  95%|█████████▌| 8062/8455 [02:20<00:06, 63.94it/s]

Extracting GLCM features:  95%|█████████▌| 8069/8455 [02:20<00:06, 60.02it/s]

Extracting GLCM features:  96%|█████████▌| 8076/8455 [02:21<00:07, 48.36it/s]

Extracting GLCM features:  96%|█████████▌| 8082/8455 [02:21<00:08, 43.13it/s]

Extracting GLCM features:  96%|█████████▌| 8087/8455 [02:21<00:08, 41.06it/s]

Extracting GLCM features:  96%|█████████▌| 8092/8455 [02:21<00:09, 38.77it/s]

Extracting GLCM features:  96%|█████████▌| 8097/8455 [02:21<00:09, 38.64it/s]

Extracting GLCM features:  96%|█████████▌| 8102/8455 [02:21<00:08, 39.84it/s]

Extracting GLCM features:  96%|█████████▌| 8107/8455 [02:21<00:08, 39.44it/s]

Extracting GLCM features:  96%|█████████▌| 8112/8455 [02:22<00:08, 38.21it/s]

Extracting GLCM features:  96%|█████████▌| 8116/8455 [02:22<00:09, 36.08it/s]

Extracting GLCM features:  96%|█████████▌| 8120/8455 [02:22<00:09, 34.58it/s]

Extracting GLCM features:  96%|█████████▌| 8124/8455 [02:22<00:09, 33.90it/s]

Extracting GLCM features:  96%|█████████▌| 8128/8455 [02:22<00:09, 33.76it/s]

Extracting GLCM features:  96%|█████████▌| 8133/8455 [02:22<00:08, 36.09it/s]

Extracting GLCM features:  96%|█████████▌| 8137/8455 [02:22<00:08, 36.51it/s]

Extracting GLCM features:  96%|█████████▋| 8142/8455 [02:22<00:08, 38.70it/s]

Extracting GLCM features:  96%|█████████▋| 8147/8455 [02:23<00:07, 39.99it/s]

Extracting GLCM features:  96%|█████████▋| 8152/8455 [02:23<00:07, 41.31it/s]

Extracting GLCM features:  96%|█████████▋| 8157/8455 [02:23<00:07, 42.19it/s]

Extracting GLCM features:  97%|█████████▋| 8162/8455 [02:23<00:06, 41.87it/s]

Extracting GLCM features:  97%|█████████▋| 8167/8455 [02:23<00:06, 42.11it/s]

Extracting GLCM features:  97%|█████████▋| 8172/8455 [02:23<00:06, 41.27it/s]

Extracting GLCM features:  97%|█████████▋| 8177/8455 [02:23<00:07, 37.62it/s]

Extracting GLCM features:  97%|█████████▋| 8182/8455 [02:23<00:06, 39.11it/s]

Extracting GLCM features:  97%|█████████▋| 8187/8455 [02:24<00:06, 40.60it/s]

Extracting GLCM features:  97%|█████████▋| 8192/8455 [02:24<00:06, 41.36it/s]

Extracting GLCM features:  97%|█████████▋| 8197/8455 [02:24<00:06, 42.06it/s]

Extracting GLCM features:  97%|█████████▋| 8202/8455 [02:24<00:05, 43.61it/s]

Extracting GLCM features:  97%|█████████▋| 8207/8455 [02:24<00:05, 43.74it/s]

Extracting GLCM features:  97%|█████████▋| 8212/8455 [02:24<00:05, 43.52it/s]

Extracting GLCM features:  97%|█████████▋| 8217/8455 [02:24<00:05, 42.55it/s]

Extracting GLCM features:  97%|█████████▋| 8222/8455 [02:24<00:05, 43.66it/s]

Extracting GLCM features:  97%|█████████▋| 8228/8455 [02:24<00:05, 45.09it/s]

Extracting GLCM features:  97%|█████████▋| 8233/8455 [02:25<00:05, 44.27it/s]

Extracting GLCM features:  97%|█████████▋| 8238/8455 [02:25<00:05, 41.96it/s]

Extracting GLCM features:  97%|█████████▋| 8243/8455 [02:25<00:05, 41.79it/s]

Extracting GLCM features:  98%|█████████▊| 8249/8455 [02:25<00:04, 44.67it/s]

Extracting GLCM features:  98%|█████████▊| 8255/8455 [02:25<00:04, 48.27it/s]

Extracting GLCM features:  98%|█████████▊| 8260/8455 [02:25<00:04, 48.18it/s]

Extracting GLCM features:  98%|█████████▊| 8266/8455 [02:25<00:03, 50.40it/s]

Extracting GLCM features:  98%|█████████▊| 8272/8455 [02:25<00:03, 51.98it/s]

Extracting GLCM features:  98%|█████████▊| 8278/8455 [02:25<00:03, 53.23it/s]

Extracting GLCM features:  98%|█████████▊| 8284/8455 [02:26<00:03, 54.37it/s]

Extracting GLCM features:  98%|█████████▊| 8291/8455 [02:26<00:02, 55.91it/s]

Extracting GLCM features:  98%|█████████▊| 8298/8455 [02:26<00:02, 56.73it/s]

Extracting GLCM features:  98%|█████████▊| 8305/8455 [02:26<00:02, 58.05it/s]

Extracting GLCM features:  98%|█████████▊| 8312/8455 [02:26<00:02, 59.75it/s]

Extracting GLCM features:  98%|█████████▊| 8318/8455 [02:26<00:02, 54.12it/s]

Extracting GLCM features:  98%|█████████▊| 8324/8455 [02:26<00:02, 51.64it/s]

Extracting GLCM features:  99%|█████████▊| 8331/8455 [02:26<00:02, 54.72it/s]

Extracting GLCM features:  99%|█████████▊| 8338/8455 [02:27<00:02, 55.02it/s]

Extracting GLCM features:  99%|█████████▊| 8344/8455 [02:27<00:02, 49.38it/s]

Extracting GLCM features:  99%|█████████▉| 8350/8455 [02:27<00:02, 46.32it/s]

Extracting GLCM features:  99%|█████████▉| 8355/8455 [02:27<00:02, 45.04it/s]

Extracting GLCM features:  99%|█████████▉| 8360/8455 [02:27<00:02, 43.68it/s]

Extracting GLCM features:  99%|█████████▉| 8365/8455 [02:27<00:02, 42.98it/s]

Extracting GLCM features:  99%|█████████▉| 8371/8455 [02:27<00:01, 45.86it/s]

Extracting GLCM features:  99%|█████████▉| 8378/8455 [02:27<00:01, 50.60it/s]

Extracting GLCM features:  99%|█████████▉| 8385/8455 [02:28<00:01, 53.78it/s]

Extracting GLCM features:  99%|█████████▉| 8392/8455 [02:28<00:01, 56.91it/s]

Extracting GLCM features:  99%|█████████▉| 8398/8455 [02:28<00:00, 57.46it/s]

Extracting GLCM features:  99%|█████████▉| 8404/8455 [02:28<00:00, 56.45it/s]

Extracting GLCM features:  99%|█████████▉| 8410/8455 [02:28<00:00, 55.14it/s]

Extracting GLCM features: 100%|█████████▉| 8416/8455 [02:28<00:00, 56.23it/s]

Extracting GLCM features: 100%|█████████▉| 8423/8455 [02:28<00:00, 57.16it/s]

Extracting GLCM features: 100%|█████████▉| 8430/8455 [02:28<00:00, 58.88it/s]

Extracting GLCM features: 100%|█████████▉| 8437/8455 [02:28<00:00, 61.51it/s]

Extracting GLCM features: 100%|█████████▉| 8444/8455 [02:29<00:00, 60.79it/s]

Extracting GLCM features: 100%|█████████▉| 8451/8455 [02:29<00:00, 60.60it/s]

Extracting GLCM features: 100%|██████████| 8455/8455 [02:29<00:00, 56.66it/s]

In [8]:
# Gabungkan semua fitur ke dalam satu DataFrame
dataTable = {
    'Filename': filenames,
    'Label': labels,
    # GLCM
    'Contrast0': Kontras0, 'Contrast45': Kontras45, 'Contrast90': Kontras90, 'Contrast135': Kontras135,
    'Homogeneity0': homogenity0, 'Homogeneity45': homogenity45, 'Homogeneity90': homogenity90, 'Homogeneity135': homogenity135,
    'Dissimilarity0': dissimilarity0, 'Dissimilarity45': dissimilarity45, 'Dissimilarity90': dissimilarity90, 'Dissimilarity135': dissimilarity135,
    'Entropy0': entropy0, 'Entropy45': entropy45, 'Entropy90': entropy90, 'Entropy135': entropy135,
    'ASM0': ASM0, 'ASM45': ASM45, 'ASM90': ASM90, 'ASM135': ASM135,
    'Energy0': energy0, 'Energy45': energy45, 'Energy90': energy90, 'Energy135': energy135,
    'Correlation0': correlation0, 'Correlation45': correlation45, 'Correlation90': correlation90, 'Correlation135': correlation135,
    # HSV Stats
    'HSV_H_Mean': h_means, 'HSV_H_Std': h_stds, 'HSV_H_Skew': h_skews, 'HSV_H_Kurt': h_kurts,
    'HSV_S_Mean': s_means, 'HSV_S_Std': s_stds, 'HSV_S_Skew': s_skews, 'HSV_S_Kurt': s_kurts,
    'HSV_V_Mean': v_means, 'HSV_V_Std': v_stds, 'HSV_V_Skew': v_skews, 'HSV_V_Kurt': v_kurts,
    # NRBR Stats
    'NRBR_Mean': nrbr_means, 'NRBR_Std': nrbr_stds, 'NRBR_Skew': nrbr_skews, 'NRBR_Kurt': nrbr_kurts,
}

# Tambahkan HSV Histograms
for b in range(16):
    dataTable[f'HSV_H_Hist_Bin_{b}'] = h_hists[:, b]
for b in range(8):
    dataTable[f'HSV_S_Hist_Bin_{b}'] = s_hists[:, b]
for b in range(8):
    dataTable[f'HSV_V_Hist_Bin_{b}'] = v_hists[:, b]

# Tambahkan NRBR Histograms
for b in range(16):
    dataTable[f'NRBR_Hist_Bin_{b}'] = nrbr_hists[:, b]

# Tambahkan LBP Histograms
for b in range(8):
    dataTable[f'LBP_Hist_Bin_{b}'] = lbp_hists[:, b]

df = pd.DataFrame(dataTable)
csv_path = f'hasil_ekstraksi_{EXPERIMENT_NAME}.csv'
df.to_csv(csv_path, index=False)
print(f'Fitur gabungan berhasil disimpan ke {csv_path}')
df.head()

Fitur gabungan berhasil disimpan ke hasil_ekstraksi_experiment11.csv

,Filename,Label,Contrast0,Contrast45,Contrast90,Contrast135,Homogeneity0,Homogeneity45,Homogeneity90,Homogeneity135,...,NRBR_Hist_Bin_14,NRBR_Hist_Bin_15,LBP_Hist_Bin_0,LBP_Hist_Bin_1,LBP_Hist_Bin_2,LBP_Hist_Bin_3,LBP_Hist_Bin_4,LBP_Hist_Bin_5,LBP_Hist_Bin_6,LBP_Hist_Bin_7
0,2_altocumulus_001371.jpg,altocumulus,45.162577,75.582253,59.245910,121.971334,0.447410,0.359880,0.417410,0.355261,...,0.0,0.0,0.004988,0.002035,0.000191,0.003497,0.002592,0.000248,0.003528,0.014171
1,2_altocumulus_000676.jpg,altocumulus,49.989017,116.052349,76.616268,129.307805,0.196684,0.133417,0.159579,0.128522,...,0.0,0.0,0.009366,0.003005,0.000189,0.003342,0.003275,0.000199,0.003188,0.008687
2,2_altocumulus_001452.jpg,altocumulus,48.850169,109.175840,63.478248,111.653641,0.216695,0.145136,0.196193,0.160454,...,0.0,0.0,0.008274,0.003619,0.000090,0.003450,0.003171,0.000108,0.003575,0.008963
3,2_altocumulus_000336.jpg,altocumulus,72.228294,151.205506,106.456679,193.714295,0.365773,0.281365,0.305556,0.252029,...,0.0,0.0,0.007523,0.002544,0.000189,0.003487,0.002777,0.000214,0.002666,0.011851
4,2_altocumulus_000201.jpg,altocumulus,32.023621,99.316417,86.434528,132.880415,0.303837,0.210173,0.234145,0.192863,...,0.0,0.0,0.009930,0.001874,0.000150,0.002567,0.002887,0.000167,0.003197,0.010479

## Train-Test Split & Normalization

In [9]:
# Pisahkan fitur dan label
X = df.drop(columns=['Filename', 'Label']).values
y = df['Label'].values

# Split 80/20 secara acak dan terstratifikasi
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Z-score Normalization (dengan epsilon 1e-8 untuk menghindari pembagian dengan nol)
mean_train = X_train.mean(axis=0)
std_train = X_train.std(axis=0)
X_train_norm = (X_train - mean_train) / (std_train + 1e-8)
X_test_norm = (X_test - mean_train) / (std_train + 1e-8)
print(f"Train shape: {X_train_norm.shape}")
print(f"Test shape: {X_test_norm.shape}")

Train shape: (6764, 100)
Test shape: (1691, 100)

## Classifiers Training & Evaluation

In [10]:
def evaluate_model(clf, X_tr, y_tr, X_ts, y_ts, name):
    clf.fit(X_tr, y_tr)
    y_pred_tr = clf.predict(X_tr)
    y_pred_ts = clf.predict(X_ts)
    
    print(f"\n====== {name} - Training Set ======")
    print(classification_report(y_tr, y_pred_tr, zero_division=0))
    print(f"Accuracy: {accuracy_score(y_tr, y_pred_tr):.4f}")
    
    print(f"\n====== {name} - Testing Set ======")
    print(classification_report(y_ts, y_pred_ts, zero_division=0))
    print(confusion_matrix(y_ts, y_pred_ts))
    print(f"Accuracy: {accuracy_score(y_ts, y_pred_ts):.4f}")
    return y_pred_ts

# Definisikan model dengan class_weight='balanced' untuk penanganan optimal jika ada minor imbalans
rf = RandomForestClassifier(n_estimators=150, random_state=42, class_weight='balanced')
svm = SVC(kernel='rbf', C=2.0, random_state=42, class_weight='balanced')
knn = KNeighborsClassifier(n_neighbors=5, weights='distance')

y_pred_rf_test = evaluate_model(rf, X_train_norm, y_train, X_test_norm, y_test, "Random Forest")
y_pred_svm_test = evaluate_model(svm, X_train_norm, y_train, X_test_norm, y_test, "SVM")
y_pred_knn_test = evaluate_model(knn, X_train_norm, y_train, X_test_norm, y_test, "KNN")

====== Random Forest - Training Set ======
               precision    recall  f1-score   support

  altocumulus       1.00      1.00      1.00      1000
       cirrus       1.00      1.00      1.00      1000
     clearsky       1.00      1.00      1.00      1000
 cumulonimbus       1.00      1.00      1.00      1000
      cumulus       1.00      1.00      1.00      1000
        mixed       1.00      1.00      1.00       764
stratocumulus       1.00      1.00      1.00      1000

     accuracy                           1.00      6764
    macro avg       1.00      1.00      1.00      6764
 weighted avg       1.00      1.00      1.00      6764

Accuracy: 1.0000

====== Random Forest - Testing Set ======
               precision    recall  f1-score   support

  altocumulus       0.84      0.87      0.86       250
       cirrus       0.82      0.77      0.80       250
     clearsky       0.96      0.96      0.96       250
 cumulonimbus       0.75      0.79      0.77       250
      cumulus       0.88      0.89      0.89       250
        mixed       0.68      0.65      0.67       191
stratocumulus       0.76      0.76      0.76       250

     accuracy                           0.82      1691
    macro avg       0.81      0.81      0.81      1691
 weighted avg       0.82      0.82      0.82      1691

[[218   7   0   4   8  10   3]
 [ 10 193   2   4   8  15  18]
 [  0   5 239   1   0   0   5]
 [  5   2   1 197   1  11  33]
 [  2   9   0   0 223  16   0]
 [ 21  12   0  18  13 125   2]
 [  3   6   6  38   0   7 190]]
Accuracy: 0.8190

====== SVM - Training Set ======
               precision    recall  f1-score   support

  altocumulus       0.89      0.87      0.88      1000
       cirrus       0.86      0.87      0.86      1000
     clearsky       0.98      0.99      0.98      1000
 cumulonimbus       0.86      0.85      0.86      1000
      cumulus       0.92      0.91      0.91      1000
        mixed       0.79      0.79      0.79       764
stratocumulus       0.83      0.85      0.84      1000

     accuracy                           0.88      6764
    macro avg       0.87      0.87      0.87      6764
 weighted avg       0.88      0.88      0.88      6764

Accuracy: 0.8771

====== SVM - Testing Set ======
               precision    recall  f1-score   support

  altocumulus       0.86      0.88      0.87       250
       cirrus       0.83      0.80      0.81       250
     clearsky       0.96      0.97      0.96       250
 cumulonimbus       0.76      0.79      0.78       250
      cumulus       0.89      0.84      0.87       250
        mixed       0.73      0.68      0.70       191
stratocumulus       0.74      0.78      0.76       250

     accuracy                           0.83      1691
    macro avg       0.82      0.82      0.82      1691
 weighted avg       0.83      0.83      0.83      1691

[[220   4   0   2   7  11   6]
 [ 10 199   4   3   5  13  16]
 [  0   3 243   2   0   0   2]
 [  2   1   1 198   0   7  41]
 [  8  15   0   0 211  16   0]
 [ 13  11   1  18  14 130   4]
 [  4   7   5  37   0   2 195]]
Accuracy: 0.8255

====== KNN - Training Set ======
               precision    recall  f1-score   support

  altocumulus       1.00      1.00      1.00      1000
       cirrus       1.00      1.00      1.00      1000
     clearsky       1.00      1.00      1.00      1000
 cumulonimbus       1.00      1.00      1.00      1000
      cumulus       1.00      1.00      1.00      1000
        mixed       1.00      1.00      1.00       764
stratocumulus       1.00      1.00      1.00      1000

     accuracy                           1.00      6764
    macro avg       1.00      1.00      1.00      6764
 weighted avg       1.00      1.00      1.00      6764

Accuracy: 1.0000

====== KNN - Testing Set ======
               precision    recall  f1-score   support

  altocumulus       0.79      0.83      0.81       250
       cirrus       0.78      0.69      0.73       250
     clearsky       0.95      0.96      0.95       250
 cumulonimbus       0.66      0.78      0.72       250
      cumulus       0.82      0.82      0.82       250
        mixed       0.68      0.63      0.65       191
stratocumulus       0.76      0.69      0.72       250

     accuracy                           0.78      1691
    macro avg       0.78      0.77      0.77      1691
 weighted avg       0.78      0.78      0.78      1691

[[207  10   0   2  10  18   3]
 [ 15 173   8  16  13  11  14]
 [  0   5 241   2   0   0   2]
 [  8   2   1 195   4   8  32]
 [  8  14   0   3 206  19   0]
 [ 20   6   0  23  17 121   4]
 [  5  11   5  53   2   2 172]]
Accuracy: 0.7776

## Save Experiment Metrics & Auto-update README

In [11]:
from pathlib import Path
METRICS_PATH = Path('../results/metrics.csv')
METRICS_PATH.parent.mkdir(parents=True, exist_ok=True)

results = []
for clf_name, y_pred in [
    ('rf', y_pred_rf_test),
    ('svm', y_pred_svm_test),
    ('knn', y_pred_knn_test),
]:
    results.append({
        'experiment_name': EXPERIMENT_NAME,
        'classifier': clf_name,
        'accuracy': accuracy_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred, average='weighted', zero_division=0),
        'recall': recall_score(y_test, y_pred, average='weighted', zero_division=0),
        'f1': f1_score(y_test, y_pred, average='weighted', zero_division=0),
    })

new_rows = pd.DataFrame(results)

if METRICS_PATH.exists() and METRICS_PATH.stat().st_size > 0:
    all_metrics = pd.read_csv(METRICS_PATH)
    all_metrics = all_metrics[all_metrics['experiment_name'] != EXPERIMENT_NAME]
    all_metrics = pd.concat([all_metrics, new_rows], ignore_index=True)
else:
    all_metrics = new_rows

all_metrics.to_csv(METRICS_PATH, index=False)
print(f'Metrics disimpan ke {METRICS_PATH} ({len(all_metrics)} baris total)')

# Jalankan script generate_metrics_table.py untuk memperbarui tabel hasil di README.md secara otomatis
import subprocess
try:
    subprocess.run(["python", "../src/generate_metrics_table.py"], check=True)
    print("README.md berhasil diperbarui dengan tabel hasil terbaru!")
except Exception as e:
    print(f"Peringatan: Gagal meng-update README.md: {e}")

all_metrics

Metrics disimpan ke ..\results\metrics.csv (33 baris total)

README.md berhasil diperbarui dengan tabel hasil terbaru!

   experiment_name classifier  accuracy  precision    recall        f1
0      experiment9         rf  0.575789   0.564385  0.575789  0.562935
1      experiment9        svm  0.563158   0.548167  0.563158  0.531862
2      experiment9        knn  0.522632   0.506224  0.522632  0.506076
3      experiment1         rf  0.532105   0.519583  0.532105  0.516108
4      experiment1        svm  0.533158   0.532211  0.533158  0.493381
5      experiment1        knn  0.483684   0.464744  0.483684  0.464786
6      experiment2         rf  0.553421   0.537102  0.553421  0.540455
7      experiment2        svm  0.540789   0.528985  0.540789  0.512945
8      experiment2        knn  0.516316   0.503454  0.516316  0.505084
9      experiment3         rf  0.561842   0.550465  0.561842  0.550986
10     experiment3        svm  0.527105   0.517347  0.527105  0.497040
11     experiment3        knn  0.498158   0.488751  0.498158  0.488039
12     experiment4         rf  0.514737   0.503177  0.514737  0.501549
13     experiment4        svm  0.516579   0.505093  0.516579  0.478473
14     experiment4        knn  0.476316   0.466278  0.476316  0.465367
15     experiment5         rf  0.821316   0.821657  0.821316  0.821135
16     experiment5        svm  0.787632   0.802315  0.787632  0.792130
17     experiment5        knn  0.782895   0.776283  0.782895  0.776533
18     experiment6         rf  0.829737   0.829593  0.829737  0.829322
19     experiment6        svm  0.793158   0.802144  0.793158  0.796048
20     experiment6        knn  0.780263   0.773187  0.780263  0.774127
21     experiment7         rf  0.655789   0.654693  0.655789  0.653106
22     experiment7        svm  0.609211   0.621162  0.609211  0.603450
23     experiment7        knn  0.621053   0.615394  0.621053  0.613233
24     experiment8         rf  0.832105   0.831199  0.832105  0.831413
25     experiment8        svm  0.791842   0.800839  0.791842  0.794697
26     experiment8        knn  0.776579   0.769591  0.776579  0.770272
27        baseline         rf  0.513897   0.514438  0.513897  0.513258
28        baseline        svm  0.498522   0.528703  0.498522  0.504854
29        baseline        knn  0.479598   0.479948  0.479598  0.477134
30    experiment11         rf  0.819042   0.818971  0.819042  0.818742
31    experiment11        svm  0.825547   0.826023  0.825547  0.825399
32    experiment11        knn  0.777646   0.779104  0.777646  0.776845

## Analisis Eksperimen 11

Silakan berikan ulasan analisis Anda di sini.