# Experiment 7: Resize + Normalisasi Min-Max + CLAHE HSV + Gaussian Blur + Gamma Correction (balanced dataset)

Eksperimen ini berfokus pada alur preprocessing lengkap:
1. **Resize** ke 256x256 piksel (otomatis saat pemuatan dataset).
2. **Normalisasi Min-Max** untuk meratakan kontras global citra ke rentang [0, 255].
3. **CLAHE pada HSV** (kontras lokal ditingkatkan pada S & V) untuk memperjelas batas awan.
4. **Gaussian Blur (kernel 5x5, sigma=1.0)** untuk meredam noise sensor dan menekan amplifikasi noise akibat operasi kontras.
5. **Gamma Correction (gamma=1.2)** untuk meningkatkan detail pada area midtone/shadows awan.
6. **RGB/Color-based Extraction & Texture Extraction** (HSV, NRBR, LBP, dan GLCM) untuk melatih model klasifikasi.

In [1]:
import sys
sys.path.append('..')  # supaya src/ bisa diimport dari notebooks/

import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from scipy.stats import skew, kurtosis, entropy
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from skimage.feature import graycomatrix, graycoprops
from src.loader import get_dataset_root, load_dataset
from src.image_processing import *

EXPERIMENT_NAME = "experiment7"

c:\Users\Mahesa\miniconda3\envs\imgproc\Lib\site-packages\cupy\_environment.py:284: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(

CuPy tidak aktif atau tidak berfungsi (fallback ke CPU/NumPy): Failed to find CUDA headers. Please install CUDA toolkit headers (e.g., pip install cupy-cuda12x[ctk]) or specify CUDA_PATH environment variable.

## Data Loading (Balanced to Max 1250 per Class)

In [2]:
DATASET_ROOT = get_dataset_root()
# Muat gambar warna (color=True) agar ekstraksi HSV dan NRBR bisa dilakukan
# Default max_per_class=1250 dan target_size=(256, 256) otomatis digunakan
images, labels, filenames = load_dataset(DATASET_ROOT, target_size=(256, 256), color=True)
print(f"Dataset loaded: {len(images)} gambar warna, {len(set(labels))} kelas")

Environment: Lokal
DATASET_ROOT dari .env: D:\INFORMATICS\SEMESTER 4\IMAGE PROCESSING\Praktikum\Project\GCD

Loading altocumulus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading altocumulus:   1%|          | 13/1250 [00:00<00:10, 119.81it/s]

Loading altocumulus:   2%|▏         | 29/1250 [00:00<00:08, 140.95it/s]

Loading altocumulus:   4%|▎         | 44/1250 [00:00<00:08, 144.97it/s]

Loading altocumulus:   5%|▌         | 64/1250 [00:00<00:07, 166.15it/s]

Loading altocumulus:   6%|▋         | 81/1250 [00:00<00:07, 165.29it/s]

Loading altocumulus:   8%|▊         | 98/1250 [00:00<00:07, 154.62it/s]

Loading altocumulus:   9%|▉         | 116/1250 [00:00<00:07, 159.46it/s]

Loading altocumulus:  11%|█         | 133/1250 [00:00<00:07, 140.99it/s]

Loading altocumulus:  12%|█▏        | 148/1250 [00:01<00:08, 136.63it/s]

Loading altocumulus:  13%|█▎        | 163/1250 [00:01<00:07, 137.05it/s]

Loading altocumulus:  14%|█▍        | 177/1250 [00:01<00:08, 124.72it/s]

Loading altocumulus:  15%|█▌        | 191/1250 [00:01<00:08, 128.22it/s]

Loading altocumulus:  16%|█▋        | 205/1250 [00:01<00:08, 125.18it/s]

Loading altocumulus:  17%|█▋        | 218/1250 [00:01<00:08, 119.78it/s]

Loading altocumulus:  18%|█▊        | 231/1250 [00:01<00:08, 119.23it/s]

Loading altocumulus:  20%|█▉        | 247/1250 [00:01<00:07, 128.12it/s]

Loading altocumulus:  21%|██        | 260/1250 [00:01<00:07, 125.38it/s]

Loading altocumulus:  22%|██▏       | 273/1250 [00:02<00:07, 122.24it/s]

Loading altocumulus:  23%|██▎       | 286/1250 [00:02<00:07, 120.91it/s]

Loading altocumulus:  24%|██▍       | 300/1250 [00:02<00:07, 125.54it/s]

Loading altocumulus:  25%|██▌       | 313/1250 [00:02<00:07, 119.70it/s]

Loading altocumulus:  26%|██▌       | 327/1250 [00:02<00:07, 122.23it/s]

Loading altocumulus:  27%|██▋       | 340/1250 [00:02<00:07, 114.82it/s]

Loading altocumulus:  28%|██▊       | 354/1250 [00:02<00:07, 119.76it/s]

Loading altocumulus:  29%|██▉       | 367/1250 [00:02<00:07, 119.70it/s]

Loading altocumulus:  31%|███       | 383/1250 [00:02<00:06, 128.07it/s]

Loading altocumulus:  32%|███▏      | 398/1250 [00:03<00:06, 133.73it/s]

Loading altocumulus:  33%|███▎      | 416/1250 [00:03<00:05, 144.71it/s]

Loading altocumulus:  34%|███▍      | 431/1250 [00:03<00:06, 132.85it/s]

Loading altocumulus:  36%|███▌      | 445/1250 [00:03<00:06, 126.91it/s]

Loading altocumulus:  37%|███▋      | 459/1250 [00:03<00:06, 129.10it/s]

Loading altocumulus:  38%|███▊      | 477/1250 [00:03<00:05, 142.72it/s]

Loading altocumulus:  40%|████      | 506/1250 [00:03<00:04, 179.81it/s]

Loading altocumulus:  42%|████▏     | 525/1250 [00:03<00:04, 180.09it/s]

Loading altocumulus:  44%|████▎     | 545/1250 [00:03<00:03, 185.08it/s]

Loading altocumulus:  46%|████▌     | 572/1250 [00:04<00:03, 205.26it/s]

Loading altocumulus:  48%|████▊     | 604/1250 [00:04<00:02, 237.99it/s]

Loading altocumulus:  50%|█████     | 628/1250 [00:04<00:02, 226.33it/s]

Loading altocumulus:  52%|█████▏    | 651/1250 [00:04<00:03, 195.26it/s]

Loading altocumulus:  54%|█████▍    | 673/1250 [00:04<00:02, 193.89it/s]

Loading altocumulus:  55%|█████▌    | 693/1250 [00:04<00:03, 171.06it/s]

Loading altocumulus:  57%|█████▋    | 718/1250 [00:04<00:02, 190.26it/s]

Loading altocumulus:  59%|█████▉    | 738/1250 [00:04<00:02, 189.92it/s]

Loading altocumulus:  61%|██████    | 758/1250 [00:05<00:02, 179.14it/s]

Loading altocumulus:  63%|██████▎   | 786/1250 [00:05<00:02, 205.55it/s]

Loading altocumulus:  66%|██████▌   | 828/1250 [00:05<00:01, 263.07it/s]

Loading altocumulus:  69%|██████▉   | 867/1250 [00:05<00:01, 297.12it/s]

Loading altocumulus:  72%|███████▏  | 903/1250 [00:05<00:01, 313.72it/s]

Loading altocumulus:  75%|███████▌  | 938/1250 [00:05<00:00, 322.34it/s]

Loading altocumulus:  78%|███████▊  | 974/1250 [00:05<00:00, 332.14it/s]

Loading altocumulus:  81%|████████  | 1010/1250 [00:05<00:00, 339.47it/s]

Loading altocumulus:  84%|████████▍ | 1047/1250 [00:05<00:00, 346.02it/s]

Loading altocumulus:  87%|████████▋ | 1084/1250 [00:05<00:00, 352.19it/s]

Loading altocumulus:  90%|█████████ | 1125/1250 [00:06<00:00, 366.37it/s]

Loading altocumulus:  93%|█████████▎| 1162/1250 [00:06<00:00, 316.08it/s]

Loading altocumulus:  96%|█████████▌| 1195/1250 [00:06<00:00, 307.15it/s]

Loading altocumulus:  99%|█████████▉| 1235/1250 [00:06<00:00, 329.60it/s]

Loading cirrus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading cirrus:   3%|▎         | 42/1250 [00:00<00:02, 413.04it/s]

Loading cirrus:   7%|▋         | 85/1250 [00:00<00:02, 415.75it/s]

Loading cirrus:  10%|█         | 127/1250 [00:00<00:02, 405.62it/s]

Loading cirrus:  13%|█▎        | 168/1250 [00:00<00:02, 397.35it/s]

Loading cirrus:  17%|█▋        | 214/1250 [00:00<00:02, 417.96it/s]

Loading cirrus:  21%|██        | 261/1250 [00:00<00:02, 435.19it/s]

Loading cirrus:  25%|██▍       | 311/1250 [00:00<00:02, 454.97it/s]

Loading cirrus:  29%|██▉       | 364/1250 [00:00<00:01, 476.66it/s]

Loading cirrus:  33%|███▎      | 417/1250 [00:00<00:01, 492.17it/s]

Loading cirrus:  37%|███▋      | 467/1250 [00:01<00:01, 482.67it/s]

Loading cirrus:  41%|████▏     | 516/1250 [00:01<00:01, 476.26it/s]

Loading cirrus:  45%|████▌     | 564/1250 [00:01<00:01, 462.03it/s]

Loading cirrus:  49%|████▉     | 611/1250 [00:01<00:01, 464.22it/s]

Loading cirrus:  53%|█████▎    | 658/1250 [00:01<00:01, 459.37it/s]

Loading cirrus:  56%|█████▋    | 704/1250 [00:01<00:01, 437.28it/s]

Loading cirrus:  60%|█████▉    | 749/1250 [00:01<00:01, 439.31it/s]

Loading cirrus:  64%|██████▎   | 794/1250 [00:01<00:01, 430.31it/s]

Loading cirrus:  67%|██████▋   | 838/1250 [00:01<00:00, 426.70it/s]

Loading cirrus:  70%|███████   | 881/1250 [00:01<00:00, 423.11it/s]

Loading cirrus:  74%|███████▍  | 924/1250 [00:02<00:00, 422.00it/s]

Loading cirrus:  78%|███████▊  | 969/1250 [00:02<00:00, 427.83it/s]

Loading cirrus:  81%|████████  | 1012/1250 [00:02<00:00, 425.23it/s]

Loading cirrus:  84%|████████▍ | 1056/1250 [00:02<00:00, 426.30it/s]

Loading cirrus:  88%|████████▊ | 1103/1250 [00:02<00:00, 435.64it/s]

Loading cirrus:  92%|█████████▏| 1149/1250 [00:02<00:00, 441.59it/s]

Loading cirrus:  96%|█████████▌| 1194/1250 [00:02<00:00, 439.49it/s]

Loading cirrus:  99%|█████████▉| 1238/1250 [00:02<00:00, 434.93it/s]

Loading clearsky:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading clearsky:   4%|▍         | 49/1250 [00:00<00:02, 474.13it/s]

Loading clearsky:   8%|▊         | 99/1250 [00:00<00:02, 476.94it/s]

Loading clearsky:  12%|█▏        | 147/1250 [00:00<00:02, 457.63it/s]

Loading clearsky:  16%|█▌        | 195/1250 [00:00<00:02, 461.51it/s]

Loading clearsky:  19%|█▉        | 242/1250 [00:00<00:02, 461.21it/s]

Loading clearsky:  23%|██▎       | 292/1250 [00:00<00:02, 472.08it/s]

Loading clearsky:  27%|██▋       | 340/1250 [00:00<00:01, 470.45it/s]

Loading clearsky:  31%|███       | 389/1250 [00:00<00:01, 472.96it/s]

Loading clearsky:  35%|███▌      | 439/1250 [00:00<00:01, 479.72it/s]

Loading clearsky:  39%|███▉      | 487/1250 [00:01<00:01, 478.04it/s]

Loading clearsky:  43%|████▎     | 535/1250 [00:01<00:01, 466.26it/s]

Loading clearsky:  47%|████▋     | 583/1250 [00:01<00:01, 468.77it/s]

Loading clearsky:  50%|█████     | 630/1250 [00:01<00:01, 469.07it/s]

Loading clearsky:  54%|█████▍    | 679/1250 [00:01<00:01, 471.91it/s]

Loading clearsky:  58%|█████▊    | 727/1250 [00:01<00:01, 466.72it/s]

Loading clearsky:  62%|██████▏   | 774/1250 [00:01<00:01, 451.15it/s]

Loading clearsky:  66%|██████▌   | 820/1250 [00:01<00:00, 451.29it/s]

Loading clearsky:  69%|██████▉   | 867/1250 [00:01<00:00, 454.31it/s]

Loading clearsky:  73%|███████▎  | 915/1250 [00:01<00:00, 458.38it/s]

Loading clearsky:  77%|███████▋  | 964/1250 [00:02<00:00, 459.22it/s]

Loading clearsky:  81%|████████  | 1010/1250 [00:02<00:00, 455.63it/s]

Loading clearsky:  84%|████████▍ | 1056/1250 [00:02<00:00, 451.10it/s]

Loading clearsky:  88%|████████▊ | 1102/1250 [00:02<00:00, 445.46it/s]

Loading clearsky:  92%|█████████▏| 1147/1250 [00:02<00:00, 400.43it/s]

Loading clearsky:  95%|█████████▌| 1188/1250 [00:02<00:00, 398.76it/s]

Loading clearsky:  99%|█████████▉| 1237/1250 [00:02<00:00, 420.18it/s]

Loading cumulonimbus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading cumulonimbus:   4%|▍         | 49/1250 [00:00<00:02, 486.37it/s]

Loading cumulonimbus:   8%|▊         | 98/1250 [00:00<00:02, 469.38it/s]

Loading cumulonimbus:  12%|█▏        | 145/1250 [00:00<00:02, 457.13it/s]

Loading cumulonimbus:  15%|█▌        | 191/1250 [00:00<00:02, 452.28it/s]

Loading cumulonimbus:  19%|█▉        | 238/1250 [00:00<00:02, 451.73it/s]

Loading cumulonimbus:  23%|██▎       | 284/1250 [00:00<00:02, 450.88it/s]

Loading cumulonimbus:  26%|██▋       | 331/1250 [00:00<00:02, 450.85it/s]

Loading cumulonimbus:  30%|███       | 379/1250 [00:00<00:01, 452.22it/s]

Loading cumulonimbus:  34%|███▍      | 426/1250 [00:00<00:01, 457.44it/s]

Loading cumulonimbus:  38%|███▊      | 472/1250 [00:01<00:01, 456.42it/s]

Loading cumulonimbus:  41%|████▏     | 518/1250 [00:01<00:01, 449.01it/s]

Loading cumulonimbus:  45%|████▌     | 563/1250 [00:01<00:01, 437.15it/s]

Loading cumulonimbus:  49%|████▊     | 607/1250 [00:01<00:01, 432.27it/s]

Loading cumulonimbus:  52%|█████▏    | 651/1250 [00:01<00:01, 421.52it/s]

Loading cumulonimbus:  56%|█████▌    | 698/1250 [00:01<00:01, 432.00it/s]

Loading cumulonimbus:  60%|█████▉    | 744/1250 [00:01<00:01, 436.42it/s]

Loading cumulonimbus:  63%|██████▎   | 790/1250 [00:01<00:01, 440.42it/s]

Loading cumulonimbus:  67%|██████▋   | 835/1250 [00:01<00:00, 437.69it/s]

Loading cumulonimbus:  70%|███████   | 879/1250 [00:01<00:00, 437.16it/s]

Loading cumulonimbus:  74%|███████▍  | 924/1250 [00:02<00:00, 440.06it/s]

Loading cumulonimbus:  78%|███████▊  | 969/1250 [00:02<00:00, 437.59it/s]

Loading cumulonimbus:  81%|████████  | 1013/1250 [00:02<00:00, 434.29it/s]

Loading cumulonimbus:  85%|████████▍ | 1057/1250 [00:02<00:00, 427.80it/s]

Loading cumulonimbus:  88%|████████▊ | 1100/1250 [00:02<00:00, 407.03it/s]

Loading cumulonimbus:  91%|█████████▏| 1141/1250 [00:02<00:00, 390.94it/s]

Loading cumulonimbus:  94%|█████████▍| 1181/1250 [00:02<00:00, 386.01it/s]

Loading cumulonimbus:  98%|█████████▊| 1224/1250 [00:02<00:00, 398.16it/s]

Loading cumulus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading cumulus:   3%|▎         | 37/1250 [00:00<00:03, 369.32it/s]

Loading cumulus:   6%|▌         | 77/1250 [00:00<00:03, 384.19it/s]

Loading cumulus:   9%|▉         | 118/1250 [00:00<00:02, 395.89it/s]

Loading cumulus:  13%|█▎        | 158/1250 [00:00<00:02, 396.63it/s]

Loading cumulus:  16%|█▌        | 198/1250 [00:00<00:02, 391.72it/s]

Loading cumulus:  19%|█▉        | 238/1250 [00:00<00:02, 388.68it/s]

Loading cumulus:  22%|██▏       | 277/1250 [00:00<00:02, 387.35it/s]

Loading cumulus:  25%|██▌       | 316/1250 [00:00<00:02, 376.16it/s]

Loading cumulus:  28%|██▊       | 354/1250 [00:00<00:02, 371.76it/s]

Loading cumulus:  31%|███▏      | 392/1250 [00:01<00:02, 359.78it/s]

Loading cumulus:  34%|███▍      | 429/1250 [00:01<00:02, 350.49it/s]

Loading cumulus:  37%|███▋      | 465/1250 [00:01<00:02, 352.92it/s]

Loading cumulus:  40%|████      | 501/1250 [00:01<00:02, 351.84it/s]

Loading cumulus:  43%|████▎     | 537/1250 [00:01<00:02, 345.21it/s]

Loading cumulus:  46%|████▌     | 573/1250 [00:01<00:01, 347.46it/s]

Loading cumulus:  49%|████▊     | 609/1250 [00:01<00:01, 348.34it/s]

Loading cumulus:  52%|█████▏    | 645/1250 [00:01<00:01, 350.47it/s]

Loading cumulus:  54%|█████▍    | 681/1250 [00:01<00:01, 350.65it/s]

Loading cumulus:  57%|█████▋    | 717/1250 [00:01<00:01, 350.50it/s]

Loading cumulus:  60%|██████    | 754/1250 [00:02<00:01, 354.90it/s]

Loading cumulus:  63%|██████▎   | 793/1250 [00:02<00:01, 364.66it/s]

Loading cumulus:  67%|██████▋   | 833/1250 [00:02<00:01, 373.38it/s]

Loading cumulus:  70%|██████▉   | 871/1250 [00:02<00:01, 372.66it/s]

Loading cumulus:  73%|███████▎  | 909/1250 [00:02<00:00, 368.64it/s]

Loading cumulus:  76%|███████▌  | 946/1250 [00:02<00:00, 365.49it/s]

Loading cumulus:  79%|███████▊  | 983/1250 [00:02<00:00, 361.47it/s]

Loading cumulus:  82%|████████▏ | 1020/1250 [00:02<00:00, 360.01it/s]

Loading cumulus:  85%|████████▍ | 1057/1250 [00:02<00:00, 352.71it/s]

Loading cumulus:  88%|████████▊ | 1094/1250 [00:03<00:00, 353.58it/s]

Loading cumulus:  91%|█████████ | 1133/1250 [00:03<00:00, 360.53it/s]

Loading cumulus:  94%|█████████▍| 1178/1250 [00:03<00:00, 385.09it/s]

Loading cumulus:  98%|█████████▊| 1224/1250 [00:03<00:00, 403.59it/s]

Loading mixed:   0%|          | 0/955 [00:00<?, ?it/s]

Loading mixed:   5%|▍         | 44/955 [00:00<00:02, 424.62it/s]

Loading mixed:   9%|▉         | 89/955 [00:00<00:02, 423.75it/s]

Loading mixed:  14%|█▍        | 133/955 [00:00<00:01, 426.20it/s]

Loading mixed:  19%|█▊        | 177/955 [00:00<00:01, 425.71it/s]

Loading mixed:  23%|██▎       | 220/955 [00:00<00:01, 394.48it/s]

Loading mixed:  28%|██▊       | 266/955 [00:00<00:01, 413.20it/s]

Loading mixed:  32%|███▏      | 309/955 [00:00<00:01, 417.48it/s]

Loading mixed:  37%|███▋      | 354/955 [00:00<00:01, 426.71it/s]

Loading mixed:  42%|████▏     | 398/955 [00:00<00:01, 428.98it/s]

Loading mixed:  46%|████▋     | 442/955 [00:01<00:01, 431.63it/s]

Loading mixed:  51%|█████     | 487/955 [00:01<00:01, 436.50it/s]

Loading mixed:  56%|█████▌    | 531/955 [00:01<00:00, 436.68it/s]

Loading mixed:  60%|██████    | 575/955 [00:01<00:00, 427.43it/s]

Loading mixed:  65%|██████▍   | 618/955 [00:01<00:00, 427.89it/s]

Loading mixed:  69%|██████▉   | 662/955 [00:01<00:00, 430.86it/s]

Loading mixed:  74%|███████▍  | 706/955 [00:01<00:00, 426.54it/s]

Loading mixed:  79%|███████▊  | 751/955 [00:01<00:00, 433.40it/s]

Loading mixed:  83%|████████▎ | 795/955 [00:01<00:00, 435.16it/s]

Loading mixed:  88%|████████▊ | 841/955 [00:01<00:00, 439.59it/s]

Loading mixed:  93%|█████████▎| 885/955 [00:02<00:00, 428.73it/s]

Loading mixed:  97%|█████████▋| 928/955 [00:02<00:00, 425.18it/s]

Loading stratocumulus:   0%|          | 0/1250 [00:00<?, ?it/s]

Loading stratocumulus:   4%|▍         | 49/1250 [00:00<00:02, 468.74it/s]

Loading stratocumulus:   8%|▊         | 96/1250 [00:00<00:02, 465.40it/s]

Loading stratocumulus:  12%|█▏        | 144/1250 [00:00<00:02, 464.26it/s]

Loading stratocumulus:  15%|█▌        | 193/1250 [00:00<00:02, 467.42it/s]

Loading stratocumulus:  20%|█▉        | 244/1250 [00:00<00:02, 474.34it/s]

Loading stratocumulus:  24%|██▍       | 298/1250 [00:00<00:01, 490.19it/s]

Loading stratocumulus:  28%|██▊       | 348/1250 [00:00<00:01, 492.90it/s]

Loading stratocumulus:  32%|███▏      | 398/1250 [00:00<00:01, 483.70it/s]

Loading stratocumulus:  36%|███▌      | 447/1250 [00:00<00:01, 465.54it/s]

Loading stratocumulus:  40%|███▉      | 494/1250 [00:01<00:01, 457.67it/s]

Loading stratocumulus:  43%|████▎     | 540/1250 [00:01<00:01, 437.42it/s]

Loading stratocumulus:  47%|████▋     | 584/1250 [00:01<00:01, 429.11it/s]

Loading stratocumulus:  50%|█████     | 628/1250 [00:01<00:01, 432.09it/s]

Loading stratocumulus:  54%|█████▍    | 674/1250 [00:01<00:01, 437.30it/s]

Loading stratocumulus:  58%|█████▊    | 725/1250 [00:01<00:01, 457.40it/s]

Loading stratocumulus:  62%|██████▏   | 776/1250 [00:01<00:01, 471.24it/s]

Loading stratocumulus:  66%|██████▌   | 824/1250 [00:01<00:00, 467.65it/s]

Loading stratocumulus:  70%|██████▉   | 872/1250 [00:01<00:00, 465.81it/s]

Loading stratocumulus:  74%|███████▎  | 919/1250 [00:01<00:00, 465.84it/s]

Loading stratocumulus:  77%|███████▋  | 966/1250 [00:02<00:00, 460.08it/s]

Loading stratocumulus:  81%|████████  | 1013/1250 [00:02<00:00, 460.33it/s]

Loading stratocumulus:  85%|████████▍ | 1062/1250 [00:02<00:00, 465.68it/s]

Loading stratocumulus:  89%|████████▊ | 1109/1250 [00:02<00:00, 462.25it/s]

Loading stratocumulus:  93%|█████████▎| 1159/1250 [00:02<00:00, 470.16it/s]

Loading stratocumulus:  97%|█████████▋| 1213/1250 [00:02<00:00, 485.58it/s]

Dataset loaded: 8455 gambar, 7 kelas, ukuran=(256, 256)
Dataset loaded: 8455 gambar warna, 7 kelas

## Preprocessing Pipeline (Normalisasi -> CLAHE HSV -> Gaussian Blur -> Gamma Correction)

In [3]:
# ================================================================
# EDIT BAGIAN INI untuk mengubah pipeline preprocessing
# Tambah, hapus, atau ganti fungsi sesuai experiment
# ================================================================

PIPELINE = [
    lambda img: normalize_minmax(img),
    lambda img: clahe_hsv(img, tile_size=8, clip_limit=2.0),
    lambda img: gaussian_filter(img, kernel_size=5, sigma=1.0),
    lambda img: gamma_correction(img, gamma=1.2),
]

# ================================================================
# Jangan edit di bawah ini
# ================================================================

def apply_pipeline(image: np.ndarray, pipeline: list) -> np.ndarray:
    for fn in pipeline:
        image = fn(image)
    return image

In [4]:
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor

def process_one(img):
    return apply_pipeline(img, PIPELINE)

print("Menjalankan Preprocessing Pipeline...")
if USING_GPU:
    print("Menggunakan ThreadPoolExecutor (GPU aktif)...")
    with ThreadPoolExecutor(max_workers=4) as executor:
        images_preprocessed_color = list(tqdm(
            executor.map(process_one, images),
            total=len(images),
            desc="Preprocessing"
        ))
else:
    print("Menggunakan Pemrosesan Sekuensial CPU...")
    images_preprocessed_color = [process_one(img) for img in tqdm(images, desc="Preprocessing")]
    
images_preprocessed_color = np.array(images_preprocessed_color)

Menjalankan Preprocessing Pipeline...
Menggunakan Pemrosesan Sekuensial CPU...

Preprocessing:   0%|          | 0/8455 [00:00<?, ?it/s]

Preprocessing:   0%|          | 1/8455 [00:00<19:18,  7.30it/s]

Preprocessing:   0%|          | 2/8455 [00:00<16:18,  8.64it/s]

Preprocessing:   0%|          | 3/8455 [00:00<17:49,  7.91it/s]

Preprocessing:   0%|          | 4/8455 [00:00<16:20,  8.62it/s]

Preprocessing:   0%|          | 5/8455 [00:00<16:02,  8.78it/s]

Preprocessing:   0%|          | 6/8455 [00:00<16:02,  8.78it/s]

Preprocessing:   0%|          | 7/8455 [00:00<15:58,  8.82it/s]

Preprocessing:   0%|          | 9/8455 [00:01<14:46,  9.53it/s]

Preprocessing:   0%|          | 11/8455 [00:01<13:26, 10.47it/s]

Preprocessing:   0%|          | 13/8455 [00:01<12:41, 11.08it/s]

Preprocessing:   0%|          | 15/8455 [00:01<12:02, 11.68it/s]

Preprocessing:   0%|          | 17/8455 [00:01<11:26, 12.29it/s]

Preprocessing:   0%|          | 19/8455 [00:01<11:00, 12.78it/s]

Preprocessing:   0%|          | 21/8455 [00:01<10:38, 13.20it/s]

Preprocessing:   0%|          | 23/8455 [00:02<10:40, 13.17it/s]

Preprocessing:   0%|          | 25/8455 [00:02<11:03, 12.71it/s]

Preprocessing:   0%|          | 27/8455 [00:02<10:48, 12.99it/s]

Preprocessing:   0%|          | 29/8455 [00:02<10:42, 13.12it/s]

Preprocessing:   0%|          | 31/8455 [00:02<10:25, 13.47it/s]

Preprocessing:   0%|          | 33/8455 [00:02<10:12, 13.75it/s]

Preprocessing:   0%|          | 35/8455 [00:02<10:27, 13.42it/s]

Preprocessing:   0%|          | 37/8455 [00:03<10:28, 13.40it/s]

Preprocessing:   0%|          | 39/8455 [00:03<09:59, 14.04it/s]

Preprocessing:   0%|          | 41/8455 [00:03<10:14, 13.69it/s]

Preprocessing:   1%|          | 43/8455 [00:03<10:09, 13.81it/s]

Preprocessing:   1%|          | 45/8455 [00:03<10:04, 13.92it/s]

Preprocessing:   1%|          | 47/8455 [00:03<09:55, 14.11it/s]

Preprocessing:   1%|          | 49/8455 [00:03<10:29, 13.35it/s]

Preprocessing:   1%|          | 51/8455 [00:04<09:56, 14.10it/s]

Preprocessing:   1%|          | 53/8455 [00:04<09:49, 14.24it/s]

Preprocessing:   1%|          | 55/8455 [00:04<09:42, 14.41it/s]

Preprocessing:   1%|          | 57/8455 [00:04<09:44, 14.37it/s]

Preprocessing:   1%|          | 59/8455 [00:04<09:33, 14.63it/s]

Preprocessing:   1%|          | 61/8455 [00:04<09:30, 14.73it/s]

Preprocessing:   1%|          | 63/8455 [00:04<09:40, 14.46it/s]

Preprocessing:   1%|          | 65/8455 [00:05<09:43, 14.38it/s]

Preprocessing:   1%|          | 67/8455 [00:05<09:27, 14.78it/s]

Preprocessing:   1%|          | 69/8455 [00:05<09:28, 14.74it/s]

Preprocessing:   1%|          | 71/8455 [00:05<09:39, 14.48it/s]

Preprocessing:   1%|          | 73/8455 [00:05<09:56, 14.04it/s]

Preprocessing:   1%|          | 75/8455 [00:05<09:55, 14.07it/s]

Preprocessing:   1%|          | 77/8455 [00:05<09:33, 14.61it/s]

Preprocessing:   1%|          | 79/8455 [00:06<09:55, 14.06it/s]

Preprocessing:   1%|          | 81/8455 [00:06<10:37, 13.13it/s]

Preprocessing:   1%|          | 83/8455 [00:06<11:11, 12.48it/s]

Preprocessing:   1%|          | 85/8455 [00:06<11:29, 12.14it/s]

Preprocessing:   1%|          | 87/8455 [00:06<11:05, 12.57it/s]

Preprocessing:   1%|          | 89/8455 [00:06<10:54, 12.78it/s]

Preprocessing:   1%|          | 91/8455 [00:06<10:06, 13.78it/s]

Preprocessing:   1%|          | 93/8455 [00:07<09:41, 14.37it/s]

Preprocessing:   1%|          | 95/8455 [00:07<10:46, 12.94it/s]

Preprocessing:   1%|          | 97/8455 [00:07<10:22, 13.43it/s]

Preprocessing:   1%|          | 99/8455 [00:07<11:11, 12.44it/s]

Preprocessing:   1%|          | 101/8455 [00:07<10:28, 13.29it/s]

Preprocessing:   1%|          | 103/8455 [00:07<10:07, 13.74it/s]

Preprocessing:   1%|          | 105/8455 [00:08<10:04, 13.82it/s]

Preprocessing:   1%|▏         | 107/8455 [00:08<09:59, 13.94it/s]

Preprocessing:   1%|▏         | 109/8455 [00:08<09:55, 14.03it/s]

Preprocessing:   1%|▏         | 111/8455 [00:08<09:58, 13.93it/s]

Preprocessing:   1%|▏         | 113/8455 [00:08<09:49, 14.16it/s]

Preprocessing:   1%|▏         | 115/8455 [00:08<09:52, 14.08it/s]

Preprocessing:   1%|▏         | 117/8455 [00:08<09:27, 14.70it/s]

Preprocessing:   1%|▏         | 119/8455 [00:09<09:48, 14.16it/s]

Preprocessing:   1%|▏         | 121/8455 [00:09<09:35, 14.49it/s]

Preprocessing:   1%|▏         | 123/8455 [00:09<09:24, 14.76it/s]

Preprocessing:   1%|▏         | 125/8455 [00:09<09:28, 14.64it/s]

Preprocessing:   2%|▏         | 127/8455 [00:09<09:20, 14.85it/s]

Preprocessing:   2%|▏         | 129/8455 [00:09<09:06, 15.23it/s]

Preprocessing:   2%|▏         | 131/8455 [00:09<09:03, 15.33it/s]

Preprocessing:   2%|▏         | 133/8455 [00:09<09:10, 15.11it/s]

Preprocessing:   2%|▏         | 135/8455 [00:10<09:03, 15.30it/s]

Preprocessing:   2%|▏         | 137/8455 [00:10<08:52, 15.63it/s]

Preprocessing:   2%|▏         | 139/8455 [00:10<09:19, 14.86it/s]

Preprocessing:   2%|▏         | 141/8455 [00:10<09:08, 15.16it/s]

Preprocessing:   2%|▏         | 143/8455 [00:10<09:19, 14.85it/s]

Preprocessing:   2%|▏         | 145/8455 [00:10<09:20, 14.83it/s]

Preprocessing:   2%|▏         | 147/8455 [00:10<10:18, 13.44it/s]

Preprocessing:   2%|▏         | 149/8455 [00:11<09:48, 14.12it/s]

Preprocessing:   2%|▏         | 151/8455 [00:11<10:51, 12.76it/s]

Preprocessing:   2%|▏         | 153/8455 [00:11<10:23, 13.31it/s]

Preprocessing:   2%|▏         | 156/8455 [00:11<08:26, 16.37it/s]

Preprocessing:   2%|▏         | 159/8455 [00:11<07:13, 19.15it/s]

Preprocessing:   2%|▏         | 162/8455 [00:11<06:30, 21.26it/s]

Preprocessing:   2%|▏         | 165/8455 [00:11<06:12, 22.24it/s]

Preprocessing:   2%|▏         | 168/8455 [00:11<05:50, 23.67it/s]

Preprocessing:   2%|▏         | 171/8455 [00:12<05:33, 24.84it/s]

Preprocessing:   2%|▏         | 174/8455 [00:12<05:21, 25.80it/s]

Preprocessing:   2%|▏         | 177/8455 [00:12<05:17, 26.06it/s]

Preprocessing:   2%|▏         | 180/8455 [00:12<05:19, 25.87it/s]

Preprocessing:   2%|▏         | 183/8455 [00:12<05:12, 26.50it/s]

Preprocessing:   2%|▏         | 186/8455 [00:12<05:03, 27.26it/s]

Preprocessing:   2%|▏         | 190/8455 [00:12<04:50, 28.44it/s]

Preprocessing:   2%|▏         | 193/8455 [00:12<05:08, 26.82it/s]

Preprocessing:   2%|▏         | 196/8455 [00:12<05:13, 26.33it/s]

Preprocessing:   2%|▏         | 199/8455 [00:13<05:36, 24.52it/s]

Preprocessing:   2%|▏         | 202/8455 [00:13<06:23, 21.52it/s]

Preprocessing:   2%|▏         | 205/8455 [00:13<07:19, 18.79it/s]

Preprocessing:   2%|▏         | 207/8455 [00:13<07:40, 17.91it/s]

Preprocessing:   2%|▏         | 209/8455 [00:13<07:37, 18.02it/s]

Preprocessing:   2%|▏         | 211/8455 [00:13<07:34, 18.13it/s]

Preprocessing:   3%|▎         | 214/8455 [00:13<07:04, 19.44it/s]

Preprocessing:   3%|▎         | 217/8455 [00:14<06:33, 20.96it/s]

Preprocessing:   3%|▎         | 220/8455 [00:14<06:17, 21.84it/s]

Preprocessing:   3%|▎         | 223/8455 [00:14<06:07, 22.40it/s]

Preprocessing:   3%|▎         | 226/8455 [00:14<05:56, 23.08it/s]

Preprocessing:   3%|▎         | 229/8455 [00:14<05:50, 23.47it/s]

Preprocessing:   3%|▎         | 232/8455 [00:14<05:51, 23.41it/s]

Preprocessing:   3%|▎         | 235/8455 [00:14<05:43, 23.91it/s]

Preprocessing:   3%|▎         | 238/8455 [00:14<05:34, 24.54it/s]

Preprocessing:   3%|▎         | 241/8455 [00:15<05:42, 23.96it/s]

Preprocessing:   3%|▎         | 244/8455 [00:15<05:55, 23.10it/s]

Preprocessing:   3%|▎         | 247/8455 [00:15<06:10, 22.17it/s]

Preprocessing:   3%|▎         | 250/8455 [00:15<06:13, 21.97it/s]

Preprocessing:   3%|▎         | 253/8455 [00:15<06:19, 21.59it/s]

Preprocessing:   3%|▎         | 256/8455 [00:15<06:19, 21.60it/s]

Preprocessing:   3%|▎         | 259/8455 [00:15<06:17, 21.71it/s]

Preprocessing:   3%|▎         | 262/8455 [00:16<06:12, 21.99it/s]

Preprocessing:   3%|▎         | 265/8455 [00:16<05:48, 23.47it/s]

Preprocessing:   3%|▎         | 268/8455 [00:16<05:52, 23.23it/s]

Preprocessing:   3%|▎         | 271/8455 [00:16<05:59, 22.77it/s]

Preprocessing:   3%|▎         | 274/8455 [00:16<05:49, 23.39it/s]

Preprocessing:   3%|▎         | 277/8455 [00:16<05:51, 23.28it/s]

Preprocessing:   3%|▎         | 280/8455 [00:16<05:35, 24.36it/s]

Preprocessing:   3%|▎         | 283/8455 [00:16<05:41, 23.96it/s]

Preprocessing:   3%|▎         | 286/8455 [00:17<06:10, 22.08it/s]

Preprocessing:   3%|▎         | 289/8455 [00:17<06:32, 20.80it/s]

Preprocessing:   3%|▎         | 292/8455 [00:17<06:09, 22.08it/s]

Preprocessing:   3%|▎         | 295/8455 [00:17<05:51, 23.22it/s]

Preprocessing:   4%|▎         | 298/8455 [00:17<05:42, 23.83it/s]

Preprocessing:   4%|▎         | 301/8455 [00:17<05:47, 23.47it/s]

Preprocessing:   4%|▎         | 304/8455 [00:17<05:40, 23.93it/s]

Preprocessing:   4%|▎         | 307/8455 [00:18<05:46, 23.51it/s]

Preprocessing:   4%|▎         | 310/8455 [00:18<05:45, 23.60it/s]

Preprocessing:   4%|▎         | 313/8455 [00:18<05:39, 24.01it/s]

Preprocessing:   4%|▎         | 316/8455 [00:18<05:41, 23.87it/s]

Preprocessing:   4%|▍         | 319/8455 [00:18<05:31, 24.53it/s]

Preprocessing:   4%|▍         | 322/8455 [00:18<05:33, 24.39it/s]

Preprocessing:   4%|▍         | 325/8455 [00:18<05:25, 24.96it/s]

Preprocessing:   4%|▍         | 328/8455 [00:18<05:22, 25.20it/s]

Preprocessing:   4%|▍         | 331/8455 [00:18<05:15, 25.73it/s]

Preprocessing:   4%|▍         | 334/8455 [00:19<05:10, 26.16it/s]

Preprocessing:   4%|▍         | 337/8455 [00:19<05:13, 25.86it/s]

Preprocessing:   4%|▍         | 340/8455 [00:19<05:20, 25.31it/s]

Preprocessing:   4%|▍         | 343/8455 [00:19<05:15, 25.75it/s]

Preprocessing:   4%|▍         | 346/8455 [00:19<05:27, 24.76it/s]

Preprocessing:   4%|▍         | 349/8455 [00:19<05:39, 23.85it/s]

Preprocessing:   4%|▍         | 352/8455 [00:19<05:41, 23.74it/s]

Preprocessing:   4%|▍         | 355/8455 [00:19<05:28, 24.64it/s]

Preprocessing:   4%|▍         | 358/8455 [00:20<05:36, 24.04it/s]

Preprocessing:   4%|▍         | 361/8455 [00:20<05:37, 23.96it/s]

Preprocessing:   4%|▍         | 364/8455 [00:20<05:35, 24.14it/s]

Preprocessing:   4%|▍         | 367/8455 [00:20<05:43, 23.54it/s]

Preprocessing:   4%|▍         | 370/8455 [00:20<05:49, 23.13it/s]

Preprocessing:   4%|▍         | 373/8455 [00:20<05:48, 23.21it/s]

Preprocessing:   4%|▍         | 376/8455 [00:20<05:53, 22.88it/s]

Preprocessing:   4%|▍         | 379/8455 [00:20<05:52, 22.92it/s]

Preprocessing:   5%|▍         | 382/8455 [00:21<05:49, 23.11it/s]

Preprocessing:   5%|▍         | 385/8455 [00:21<06:15, 21.51it/s]

Preprocessing:   5%|▍         | 388/8455 [00:21<06:13, 21.57it/s]

Preprocessing:   5%|▍         | 391/8455 [00:21<06:38, 20.21it/s]

Preprocessing:   5%|▍         | 394/8455 [00:21<06:31, 20.57it/s]

Preprocessing:   5%|▍         | 397/8455 [00:21<06:25, 20.90it/s]

Preprocessing:   5%|▍         | 400/8455 [00:22<06:30, 20.63it/s]

Preprocessing:   5%|▍         | 403/8455 [00:22<06:43, 19.96it/s]

Preprocessing:   5%|▍         | 406/8455 [00:22<07:19, 18.32it/s]

Preprocessing:   5%|▍         | 408/8455 [00:22<07:25, 18.06it/s]

Preprocessing:   5%|▍         | 410/8455 [00:22<07:28, 17.95it/s]

Preprocessing:   5%|▍         | 412/8455 [00:22<07:29, 17.88it/s]

Preprocessing:   5%|▍         | 414/8455 [00:22<07:35, 17.65it/s]

Preprocessing:   5%|▍         | 416/8455 [00:22<07:28, 17.92it/s]

Preprocessing:   5%|▍         | 418/8455 [00:23<07:18, 18.35it/s]

Preprocessing:   5%|▍         | 421/8455 [00:23<06:54, 19.40it/s]

Preprocessing:   5%|▌         | 423/8455 [00:23<06:53, 19.43it/s]

Preprocessing:   5%|▌         | 425/8455 [00:23<06:53, 19.42it/s]

Preprocessing:   5%|▌         | 428/8455 [00:23<06:25, 20.85it/s]

Preprocessing:   5%|▌         | 431/8455 [00:23<06:10, 21.65it/s]

Preprocessing:   5%|▌         | 434/8455 [00:23<05:54, 22.63it/s]

Preprocessing:   5%|▌         | 437/8455 [00:23<05:43, 23.37it/s]

Preprocessing:   5%|▌         | 440/8455 [00:23<05:38, 23.69it/s]

Preprocessing:   5%|▌         | 443/8455 [00:24<05:46, 23.09it/s]

Preprocessing:   5%|▌         | 446/8455 [00:24<05:51, 22.79it/s]

Preprocessing:   5%|▌         | 449/8455 [00:24<06:03, 22.01it/s]

Preprocessing:   5%|▌         | 452/8455 [00:24<06:12, 21.46it/s]

Preprocessing:   5%|▌         | 455/8455 [00:24<06:07, 21.74it/s]

Preprocessing:   5%|▌         | 458/8455 [00:24<06:20, 21.03it/s]

Preprocessing:   5%|▌         | 461/8455 [00:24<06:06, 21.81it/s]

Preprocessing:   5%|▌         | 464/8455 [00:25<05:49, 22.84it/s]

Preprocessing:   6%|▌         | 467/8455 [00:25<05:48, 22.90it/s]

Preprocessing:   6%|▌         | 470/8455 [00:25<05:47, 22.96it/s]

Preprocessing:   6%|▌         | 473/8455 [00:25<05:50, 22.79it/s]

Preprocessing:   6%|▌         | 476/8455 [00:25<05:51, 22.72it/s]

Preprocessing:   6%|▌         | 479/8455 [00:25<05:45, 23.11it/s]

Preprocessing:   6%|▌         | 482/8455 [00:25<05:35, 23.74it/s]

Preprocessing:   6%|▌         | 485/8455 [00:25<05:33, 23.89it/s]

Preprocessing:   6%|▌         | 488/8455 [00:26<05:45, 23.04it/s]

Preprocessing:   6%|▌         | 491/8455 [00:26<06:16, 21.17it/s]

Preprocessing:   6%|▌         | 494/8455 [00:26<06:23, 20.74it/s]

Preprocessing:   6%|▌         | 497/8455 [00:26<06:00, 22.07it/s]

Preprocessing:   6%|▌         | 500/8455 [00:26<06:41, 19.83it/s]

Preprocessing:   6%|▌         | 503/8455 [00:26<06:27, 20.51it/s]

Preprocessing:   6%|▌         | 506/8455 [00:26<06:05, 21.73it/s]

Preprocessing:   6%|▌         | 509/8455 [00:27<06:02, 21.91it/s]

Preprocessing:   6%|▌         | 512/8455 [00:27<06:11, 21.40it/s]

Preprocessing:   6%|▌         | 515/8455 [00:27<06:02, 21.93it/s]

Preprocessing:   6%|▌         | 518/8455 [00:27<05:49, 22.68it/s]

Preprocessing:   6%|▌         | 521/8455 [00:27<05:45, 22.99it/s]

Preprocessing:   6%|▌         | 524/8455 [00:27<06:16, 21.08it/s]

Preprocessing:   6%|▌         | 527/8455 [00:27<06:38, 19.91it/s]

Preprocessing:   6%|▋         | 530/8455 [00:28<06:37, 19.94it/s]

Preprocessing:   6%|▋         | 533/8455 [00:28<06:32, 20.17it/s]

Preprocessing:   6%|▋         | 536/8455 [00:28<06:19, 20.89it/s]

Preprocessing:   6%|▋         | 539/8455 [00:28<05:59, 22.04it/s]

Preprocessing:   6%|▋         | 542/8455 [00:28<06:06, 21.62it/s]

Preprocessing:   6%|▋         | 545/8455 [00:28<06:15, 21.06it/s]

Preprocessing:   6%|▋         | 548/8455 [00:28<06:04, 21.68it/s]

Preprocessing:   7%|▋         | 551/8455 [00:29<05:52, 22.40it/s]

Preprocessing:   7%|▋         | 554/8455 [00:29<06:08, 21.42it/s]

Preprocessing:   7%|▋         | 557/8455 [00:29<06:47, 19.39it/s]

Preprocessing:   7%|▋         | 559/8455 [00:29<07:03, 18.66it/s]

Preprocessing:   7%|▋         | 561/8455 [00:29<07:07, 18.46it/s]

Preprocessing:   7%|▋         | 563/8455 [00:29<08:37, 15.25it/s]

Preprocessing:   7%|▋         | 565/8455 [00:29<08:09, 16.10it/s]

Preprocessing:   7%|▋         | 567/8455 [00:30<07:53, 16.64it/s]

Preprocessing:   7%|▋         | 569/8455 [00:30<07:33, 17.38it/s]

Preprocessing:   7%|▋         | 572/8455 [00:30<07:00, 18.74it/s]

Preprocessing:   7%|▋         | 575/8455 [00:30<06:55, 18.97it/s]

Preprocessing:   7%|▋         | 577/8455 [00:30<07:03, 18.62it/s]

Preprocessing:   7%|▋         | 580/8455 [00:30<06:49, 19.25it/s]

Preprocessing:   7%|▋         | 582/8455 [00:30<06:47, 19.33it/s]

Preprocessing:   7%|▋         | 585/8455 [00:30<06:27, 20.33it/s]

Preprocessing:   7%|▋         | 588/8455 [00:31<06:01, 21.79it/s]

Preprocessing:   7%|▋         | 591/8455 [00:31<06:00, 21.83it/s]

Preprocessing:   7%|▋         | 594/8455 [00:31<05:55, 22.11it/s]

Preprocessing:   7%|▋         | 597/8455 [00:31<05:45, 22.72it/s]

Preprocessing:   7%|▋         | 600/8455 [00:31<05:56, 22.01it/s]

Preprocessing:   7%|▋         | 603/8455 [00:31<06:01, 21.73it/s]

Preprocessing:   7%|▋         | 606/8455 [00:31<06:01, 21.71it/s]

Preprocessing:   7%|▋         | 609/8455 [00:32<06:19, 20.69it/s]

Preprocessing:   7%|▋         | 612/8455 [00:32<06:16, 20.84it/s]

Preprocessing:   7%|▋         | 615/8455 [00:32<06:04, 21.49it/s]

Preprocessing:   7%|▋         | 618/8455 [00:32<05:49, 22.43it/s]

Preprocessing:   7%|▋         | 621/8455 [00:32<05:36, 23.26it/s]

Preprocessing:   7%|▋         | 624/8455 [00:32<05:25, 24.05it/s]

Preprocessing:   7%|▋         | 627/8455 [00:32<05:27, 23.92it/s]

Preprocessing:   7%|▋         | 630/8455 [00:32<05:21, 24.35it/s]

Preprocessing:   7%|▋         | 633/8455 [00:33<05:23, 24.18it/s]

Preprocessing:   8%|▊         | 636/8455 [00:33<06:04, 21.44it/s]

Preprocessing:   8%|▊         | 639/8455 [00:33<05:54, 22.05it/s]

Preprocessing:   8%|▊         | 642/8455 [00:33<05:43, 22.75it/s]

Preprocessing:   8%|▊         | 645/8455 [00:33<05:45, 22.59it/s]

Preprocessing:   8%|▊         | 648/8455 [00:33<06:01, 21.61it/s]

Preprocessing:   8%|▊         | 651/8455 [00:33<06:27, 20.15it/s]

Preprocessing:   8%|▊         | 654/8455 [00:34<06:33, 19.81it/s]

Preprocessing:   8%|▊         | 657/8455 [00:34<06:26, 20.19it/s]

Preprocessing:   8%|▊         | 660/8455 [00:34<06:10, 21.06it/s]

Preprocessing:   8%|▊         | 663/8455 [00:34<05:52, 22.11it/s]

Preprocessing:   8%|▊         | 666/8455 [00:34<05:32, 23.44it/s]

Preprocessing:   8%|▊         | 669/8455 [00:34<05:29, 23.65it/s]

Preprocessing:   8%|▊         | 672/8455 [00:34<05:20, 24.28it/s]

Preprocessing:   8%|▊         | 675/8455 [00:34<05:17, 24.49it/s]

Preprocessing:   8%|▊         | 678/8455 [00:35<05:15, 24.63it/s]

Preprocessing:   8%|▊         | 681/8455 [00:35<05:29, 23.57it/s]

Preprocessing:   8%|▊         | 684/8455 [00:35<05:15, 24.59it/s]

Preprocessing:   8%|▊         | 687/8455 [00:35<05:22, 24.11it/s]

Preprocessing:   8%|▊         | 690/8455 [00:35<05:18, 24.37it/s]

Preprocessing:   8%|▊         | 693/8455 [00:35<05:09, 25.08it/s]

Preprocessing:   8%|▊         | 696/8455 [00:35<05:06, 25.30it/s]

Preprocessing:   8%|▊         | 699/8455 [00:35<05:04, 25.44it/s]

Preprocessing:   8%|▊         | 702/8455 [00:36<05:06, 25.28it/s]

Preprocessing:   8%|▊         | 705/8455 [00:36<05:04, 25.47it/s]

Preprocessing:   8%|▊         | 708/8455 [00:36<05:16, 24.44it/s]

Preprocessing:   8%|▊         | 711/8455 [00:36<05:12, 24.79it/s]

Preprocessing:   8%|▊         | 714/8455 [00:36<05:07, 25.19it/s]

Preprocessing:   8%|▊         | 717/8455 [00:36<05:04, 25.38it/s]

Preprocessing:   9%|▊         | 720/8455 [00:36<05:04, 25.40it/s]

Preprocessing:   9%|▊         | 723/8455 [00:36<05:11, 24.82it/s]

Preprocessing:   9%|▊         | 726/8455 [00:37<05:13, 24.63it/s]

Preprocessing:   9%|▊         | 729/8455 [00:37<05:19, 24.22it/s]

Preprocessing:   9%|▊         | 732/8455 [00:37<05:39, 22.78it/s]

Preprocessing:   9%|▊         | 735/8455 [00:37<05:29, 23.41it/s]

Preprocessing:   9%|▊         | 738/8455 [00:37<05:25, 23.71it/s]

Preprocessing:   9%|▉         | 741/8455 [00:37<05:24, 23.79it/s]

Preprocessing:   9%|▉         | 744/8455 [00:37<05:17, 24.26it/s]

Preprocessing:   9%|▉         | 747/8455 [00:37<05:19, 24.16it/s]

Preprocessing:   9%|▉         | 750/8455 [00:38<05:20, 24.02it/s]

Preprocessing:   9%|▉         | 753/8455 [00:38<05:20, 24.01it/s]

Preprocessing:   9%|▉         | 756/8455 [00:38<05:22, 23.90it/s]

Preprocessing:   9%|▉         | 759/8455 [00:38<05:14, 24.51it/s]

Preprocessing:   9%|▉         | 762/8455 [00:38<05:22, 23.88it/s]

Preprocessing:   9%|▉         | 765/8455 [00:38<05:11, 24.69it/s]

Preprocessing:   9%|▉         | 768/8455 [00:38<05:17, 24.18it/s]

Preprocessing:   9%|▉         | 771/8455 [00:38<05:36, 22.81it/s]

Preprocessing:   9%|▉         | 774/8455 [00:39<06:07, 20.91it/s]

Preprocessing:   9%|▉         | 777/8455 [00:39<06:05, 21.03it/s]

Preprocessing:   9%|▉         | 780/8455 [00:39<05:46, 22.13it/s]

Preprocessing:   9%|▉         | 783/8455 [00:39<05:37, 22.72it/s]

Preprocessing:   9%|▉         | 786/8455 [00:39<05:28, 23.34it/s]

Preprocessing:   9%|▉         | 789/8455 [00:39<05:22, 23.76it/s]

Preprocessing:   9%|▉         | 792/8455 [00:39<05:24, 23.62it/s]

Preprocessing:   9%|▉         | 795/8455 [00:39<05:15, 24.25it/s]

Preprocessing:   9%|▉         | 798/8455 [00:40<05:12, 24.47it/s]

Preprocessing:   9%|▉         | 801/8455 [00:40<05:12, 24.47it/s]

Preprocessing:  10%|▉         | 804/8455 [00:40<05:11, 24.55it/s]

Preprocessing:  10%|▉         | 807/8455 [00:40<05:08, 24.75it/s]

Preprocessing:  10%|▉         | 810/8455 [00:40<05:06, 24.98it/s]

Preprocessing:  10%|▉         | 813/8455 [00:40<05:02, 25.29it/s]

Preprocessing:  10%|▉         | 816/8455 [00:40<05:02, 25.22it/s]

Preprocessing:  10%|▉         | 819/8455 [00:40<05:07, 24.85it/s]

Preprocessing:  10%|▉         | 822/8455 [00:41<05:06, 24.89it/s]

Preprocessing:  10%|▉         | 825/8455 [00:41<05:07, 24.82it/s]

Preprocessing:  10%|▉         | 828/8455 [00:41<05:06, 24.85it/s]

Preprocessing:  10%|▉         | 831/8455 [00:41<05:10, 24.57it/s]

Preprocessing:  10%|▉         | 834/8455 [00:41<05:06, 24.84it/s]

Preprocessing:  10%|▉         | 837/8455 [00:41<05:04, 25.01it/s]

Preprocessing:  10%|▉         | 840/8455 [00:41<05:03, 25.06it/s]

Preprocessing:  10%|▉         | 843/8455 [00:41<05:07, 24.75it/s]

Preprocessing:  10%|█         | 846/8455 [00:42<05:11, 24.42it/s]

Preprocessing:  10%|█         | 849/8455 [00:42<05:11, 24.39it/s]

Preprocessing:  10%|█         | 852/8455 [00:42<05:06, 24.77it/s]

Preprocessing:  10%|█         | 855/8455 [00:42<05:07, 24.68it/s]

Preprocessing:  10%|█         | 858/8455 [00:42<05:09, 24.54it/s]

Preprocessing:  10%|█         | 861/8455 [00:42<05:04, 24.97it/s]

Preprocessing:  10%|█         | 864/8455 [00:42<05:04, 24.90it/s]

Preprocessing:  10%|█         | 867/8455 [00:42<05:00, 25.23it/s]

Preprocessing:  10%|█         | 870/8455 [00:42<05:07, 24.66it/s]

Preprocessing:  10%|█         | 873/8455 [00:43<05:07, 24.62it/s]

Preprocessing:  10%|█         | 876/8455 [00:43<05:01, 25.14it/s]

Preprocessing:  10%|█         | 879/8455 [00:43<04:58, 25.36it/s]

Preprocessing:  10%|█         | 882/8455 [00:43<05:06, 24.73it/s]

Preprocessing:  10%|█         | 885/8455 [00:43<05:20, 23.61it/s]

Preprocessing:  11%|█         | 888/8455 [00:43<05:15, 23.98it/s]

Preprocessing:  11%|█         | 891/8455 [00:43<05:07, 24.60it/s]

Preprocessing:  11%|█         | 894/8455 [00:43<05:02, 24.99it/s]

Preprocessing:  11%|█         | 897/8455 [00:44<05:01, 25.05it/s]

Preprocessing:  11%|█         | 900/8455 [00:44<05:01, 25.06it/s]

Preprocessing:  11%|█         | 903/8455 [00:44<04:59, 25.19it/s]

Preprocessing:  11%|█         | 906/8455 [00:44<04:57, 25.40it/s]

Preprocessing:  11%|█         | 909/8455 [00:44<04:58, 25.29it/s]

Preprocessing:  11%|█         | 912/8455 [00:44<04:59, 25.20it/s]

Preprocessing:  11%|█         | 915/8455 [00:44<04:57, 25.34it/s]

Preprocessing:  11%|█         | 918/8455 [00:44<04:57, 25.38it/s]

Preprocessing:  11%|█         | 921/8455 [00:45<04:56, 25.40it/s]

Preprocessing:  11%|█         | 924/8455 [00:45<04:55, 25.46it/s]

Preprocessing:  11%|█         | 927/8455 [00:45<04:56, 25.43it/s]

Preprocessing:  11%|█         | 930/8455 [00:45<05:04, 24.73it/s]

Preprocessing:  11%|█         | 933/8455 [00:45<05:04, 24.74it/s]

Preprocessing:  11%|█         | 936/8455 [00:45<05:04, 24.67it/s]

Preprocessing:  11%|█         | 939/8455 [00:45<05:06, 24.51it/s]

Preprocessing:  11%|█         | 942/8455 [00:45<05:02, 24.81it/s]

Preprocessing:  11%|█         | 945/8455 [00:45<05:00, 25.00it/s]

Preprocessing:  11%|█         | 948/8455 [00:46<04:59, 25.10it/s]

Preprocessing:  11%|█         | 951/8455 [00:46<05:06, 24.48it/s]

Preprocessing:  11%|█▏        | 954/8455 [00:46<05:00, 24.95it/s]

Preprocessing:  11%|█▏        | 957/8455 [00:46<04:58, 25.14it/s]

Preprocessing:  11%|█▏        | 960/8455 [00:46<04:56, 25.31it/s]

Preprocessing:  11%|█▏        | 963/8455 [00:46<04:57, 25.14it/s]

Preprocessing:  11%|█▏        | 966/8455 [00:46<05:01, 24.86it/s]

Preprocessing:  11%|█▏        | 969/8455 [00:46<04:59, 25.03it/s]

Preprocessing:  11%|█▏        | 972/8455 [00:47<04:57, 25.15it/s]

Preprocessing:  12%|█▏        | 975/8455 [00:47<04:55, 25.32it/s]

Preprocessing:  12%|█▏        | 978/8455 [00:47<04:57, 25.13it/s]

Preprocessing:  12%|█▏        | 981/8455 [00:47<05:01, 24.78it/s]

Preprocessing:  12%|█▏        | 984/8455 [00:47<05:10, 24.09it/s]

Preprocessing:  12%|█▏        | 987/8455 [00:47<05:09, 24.15it/s]

Preprocessing:  12%|█▏        | 990/8455 [00:47<05:04, 24.49it/s]

Preprocessing:  12%|█▏        | 993/8455 [00:47<05:11, 23.95it/s]

Preprocessing:  12%|█▏        | 996/8455 [00:48<05:07, 24.28it/s]

Preprocessing:  12%|█▏        | 999/8455 [00:48<05:07, 24.24it/s]

Preprocessing:  12%|█▏        | 1002/8455 [00:48<04:58, 24.96it/s]

Preprocessing:  12%|█▏        | 1005/8455 [00:48<05:01, 24.68it/s]

Preprocessing:  12%|█▏        | 1008/8455 [00:48<05:05, 24.39it/s]

Preprocessing:  12%|█▏        | 1011/8455 [00:48<05:05, 24.39it/s]

Preprocessing:  12%|█▏        | 1014/8455 [00:48<05:00, 24.74it/s]

Preprocessing:  12%|█▏        | 1017/8455 [00:48<05:00, 24.72it/s]

Preprocessing:  12%|█▏        | 1020/8455 [00:49<05:01, 24.65it/s]

Preprocessing:  12%|█▏        | 1023/8455 [00:49<05:24, 22.91it/s]

Preprocessing:  12%|█▏        | 1026/8455 [00:49<05:16, 23.44it/s]

Preprocessing:  12%|█▏        | 1029/8455 [00:49<05:13, 23.66it/s]

Preprocessing:  12%|█▏        | 1032/8455 [00:49<05:09, 23.99it/s]

Preprocessing:  12%|█▏        | 1035/8455 [00:49<05:05, 24.28it/s]

Preprocessing:  12%|█▏        | 1038/8455 [00:49<05:03, 24.47it/s]

Preprocessing:  12%|█▏        | 1041/8455 [00:49<05:22, 22.96it/s]

Preprocessing:  12%|█▏        | 1044/8455 [00:50<05:18, 23.29it/s]

Preprocessing:  12%|█▏        | 1047/8455 [00:50<05:11, 23.82it/s]

Preprocessing:  12%|█▏        | 1050/8455 [00:50<05:09, 23.91it/s]

Preprocessing:  12%|█▏        | 1053/8455 [00:50<05:26, 22.68it/s]

Preprocessing:  12%|█▏        | 1056/8455 [00:50<05:52, 21.00it/s]

Preprocessing:  13%|█▎        | 1059/8455 [00:50<05:59, 20.58it/s]

Preprocessing:  13%|█▎        | 1062/8455 [00:50<05:51, 21.03it/s]

Preprocessing:  13%|█▎        | 1065/8455 [00:51<05:42, 21.56it/s]

Preprocessing:  13%|█▎        | 1068/8455 [00:51<05:42, 21.55it/s]

Preprocessing:  13%|█▎        | 1071/8455 [00:51<05:36, 21.93it/s]

Preprocessing:  13%|█▎        | 1074/8455 [00:51<05:29, 22.42it/s]

Preprocessing:  13%|█▎        | 1077/8455 [00:51<05:20, 23.04it/s]

Preprocessing:  13%|█▎        | 1080/8455 [00:51<05:14, 23.48it/s]

Preprocessing:  13%|█▎        | 1083/8455 [00:51<05:16, 23.29it/s]

Preprocessing:  13%|█▎        | 1086/8455 [00:51<05:13, 23.50it/s]

Preprocessing:  13%|█▎        | 1089/8455 [00:52<05:19, 23.06it/s]

Preprocessing:  13%|█▎        | 1092/8455 [00:52<05:16, 23.26it/s]

Preprocessing:  13%|█▎        | 1095/8455 [00:52<05:26, 22.57it/s]

Preprocessing:  13%|█▎        | 1098/8455 [00:52<05:31, 22.19it/s]

Preprocessing:  13%|█▎        | 1101/8455 [00:52<05:35, 21.89it/s]

Preprocessing:  13%|█▎        | 1104/8455 [00:52<05:26, 22.53it/s]

Preprocessing:  13%|█▎        | 1107/8455 [00:52<05:28, 22.35it/s]

Preprocessing:  13%|█▎        | 1110/8455 [00:53<05:20, 22.91it/s]

Preprocessing:  13%|█▎        | 1113/8455 [00:53<05:13, 23.39it/s]

Preprocessing:  13%|█▎        | 1116/8455 [00:53<05:08, 23.79it/s]

Preprocessing:  13%|█▎        | 1119/8455 [00:53<05:08, 23.79it/s]

Preprocessing:  13%|█▎        | 1122/8455 [00:53<05:03, 24.15it/s]

Preprocessing:  13%|█▎        | 1125/8455 [00:53<04:56, 24.72it/s]

Preprocessing:  13%|█▎        | 1128/8455 [00:53<04:55, 24.76it/s]

Preprocessing:  13%|█▎        | 1131/8455 [00:53<04:53, 24.97it/s]

Preprocessing:  13%|█▎        | 1134/8455 [00:53<04:55, 24.79it/s]

Preprocessing:  13%|█▎        | 1137/8455 [00:54<04:57, 24.62it/s]

Preprocessing:  13%|█▎        | 1140/8455 [00:54<04:56, 24.68it/s]

Preprocessing:  14%|█▎        | 1143/8455 [00:54<04:53, 24.93it/s]

Preprocessing:  14%|█▎        | 1146/8455 [00:54<04:47, 25.43it/s]

Preprocessing:  14%|█▎        | 1149/8455 [00:54<04:48, 25.30it/s]

Preprocessing:  14%|█▎        | 1152/8455 [00:54<04:50, 25.10it/s]

Preprocessing:  14%|█▎        | 1155/8455 [00:54<04:50, 25.16it/s]

Preprocessing:  14%|█▎        | 1158/8455 [00:54<04:56, 24.61it/s]

Preprocessing:  14%|█▎        | 1161/8455 [00:55<04:56, 24.62it/s]

Preprocessing:  14%|█▍        | 1164/8455 [00:55<04:57, 24.52it/s]

Preprocessing:  14%|█▍        | 1167/8455 [00:55<04:54, 24.75it/s]

Preprocessing:  14%|█▍        | 1170/8455 [00:55<05:04, 23.95it/s]

Preprocessing:  14%|█▍        | 1173/8455 [00:55<05:09, 23.50it/s]

Preprocessing:  14%|█▍        | 1176/8455 [00:55<05:14, 23.12it/s]

Preprocessing:  14%|█▍        | 1179/8455 [00:55<05:19, 22.77it/s]

Preprocessing:  14%|█▍        | 1182/8455 [00:55<05:20, 22.71it/s]

Preprocessing:  14%|█▍        | 1185/8455 [00:56<05:24, 22.40it/s]

Preprocessing:  14%|█▍        | 1188/8455 [00:56<05:27, 22.21it/s]

Preprocessing:  14%|█▍        | 1191/8455 [00:56<05:26, 22.27it/s]

Preprocessing:  14%|█▍        | 1194/8455 [00:56<05:35, 21.66it/s]

Preprocessing:  14%|█▍        | 1197/8455 [00:56<05:38, 21.47it/s]

Preprocessing:  14%|█▍        | 1200/8455 [00:56<05:30, 21.93it/s]

Preprocessing:  14%|█▍        | 1203/8455 [00:56<05:37, 21.47it/s]

Preprocessing:  14%|█▍        | 1206/8455 [00:57<06:03, 19.94it/s]

Preprocessing:  14%|█▍        | 1209/8455 [00:57<07:49, 15.42it/s]

Preprocessing:  14%|█▍        | 1211/8455 [00:57<07:44, 15.60it/s]

Preprocessing:  14%|█▍        | 1214/8455 [00:57<07:03, 17.09it/s]

Preprocessing:  14%|█▍        | 1217/8455 [00:57<06:39, 18.11it/s]

Preprocessing:  14%|█▍        | 1220/8455 [00:57<06:21, 18.98it/s]

Preprocessing:  14%|█▍        | 1223/8455 [00:58<06:05, 19.81it/s]

Preprocessing:  15%|█▍        | 1226/8455 [00:58<07:05, 16.99it/s]

Preprocessing:  15%|█▍        | 1228/8455 [00:58<07:17, 16.53it/s]

Preprocessing:  15%|█▍        | 1231/8455 [00:58<06:52, 17.53it/s]

Preprocessing:  15%|█▍        | 1233/8455 [00:58<06:53, 17.48it/s]

Preprocessing:  15%|█▍        | 1235/8455 [00:58<06:52, 17.48it/s]

Preprocessing:  15%|█▍        | 1237/8455 [00:58<06:54, 17.41it/s]

Preprocessing:  15%|█▍        | 1239/8455 [00:59<06:49, 17.63it/s]

Preprocessing:  15%|█▍        | 1241/8455 [00:59<06:39, 18.07it/s]

Preprocessing:  15%|█▍        | 1244/8455 [00:59<06:26, 18.67it/s]

Preprocessing:  15%|█▍        | 1246/8455 [00:59<07:15, 16.55it/s]

Preprocessing:  15%|█▍        | 1248/8455 [00:59<07:24, 16.20it/s]

Preprocessing:  15%|█▍        | 1250/8455 [00:59<07:14, 16.58it/s]

Preprocessing:  15%|█▍        | 1252/8455 [00:59<07:28, 16.05it/s]

Preprocessing:  15%|█▍        | 1254/8455 [01:00<08:29, 14.14it/s]

Preprocessing:  15%|█▍        | 1256/8455 [01:00<09:05, 13.20it/s]

Preprocessing:  15%|█▍        | 1258/8455 [01:00<09:24, 12.74it/s]

Preprocessing:  15%|█▍        | 1260/8455 [01:00<09:07, 13.14it/s]

Preprocessing:  15%|█▍        | 1262/8455 [01:00<08:56, 13.42it/s]

Preprocessing:  15%|█▍        | 1264/8455 [01:00<08:37, 13.91it/s]

Preprocessing:  15%|█▍        | 1266/8455 [01:00<08:23, 14.28it/s]

Preprocessing:  15%|█▍        | 1268/8455 [01:01<08:05, 14.80it/s]

Preprocessing:  15%|█▌        | 1270/8455 [01:01<07:54, 15.14it/s]

Preprocessing:  15%|█▌        | 1272/8455 [01:01<07:35, 15.78it/s]

Preprocessing:  15%|█▌        | 1274/8455 [01:01<08:06, 14.75it/s]

Preprocessing:  15%|█▌        | 1276/8455 [01:01<08:38, 13.86it/s]

Preprocessing:  15%|█▌        | 1278/8455 [01:01<08:31, 14.04it/s]

Preprocessing:  15%|█▌        | 1280/8455 [01:01<08:45, 13.64it/s]

Preprocessing:  15%|█▌        | 1282/8455 [01:02<08:23, 14.26it/s]

Preprocessing:  15%|█▌        | 1284/8455 [01:02<08:15, 14.46it/s]

Preprocessing:  15%|█▌        | 1286/8455 [01:02<08:10, 14.61it/s]

Preprocessing:  15%|█▌        | 1288/8455 [01:02<07:55, 15.08it/s]

Preprocessing:  15%|█▌        | 1290/8455 [01:02<07:53, 15.13it/s]

Preprocessing:  15%|█▌        | 1292/8455 [01:02<07:53, 15.13it/s]

Preprocessing:  15%|█▌        | 1294/8455 [01:02<07:42, 15.48it/s]

Preprocessing:  15%|█▌        | 1296/8455 [01:02<07:37, 15.66it/s]

Preprocessing:  15%|█▌        | 1298/8455 [01:03<07:31, 15.85it/s]

Preprocessing:  15%|█▌        | 1300/8455 [01:03<07:33, 15.78it/s]

Preprocessing:  15%|█▌        | 1302/8455 [01:03<07:36, 15.67it/s]

Preprocessing:  15%|█▌        | 1304/8455 [01:03<07:59, 14.90it/s]

Preprocessing:  15%|█▌        | 1306/8455 [01:03<08:00, 14.88it/s]

Preprocessing:  15%|█▌        | 1308/8455 [01:03<08:04, 14.74it/s]

Preprocessing:  15%|█▌        | 1310/8455 [01:03<08:08, 14.62it/s]

Preprocessing:  16%|█▌        | 1312/8455 [01:04<08:44, 13.62it/s]

Preprocessing:  16%|█▌        | 1314/8455 [01:04<08:18, 14.34it/s]

Preprocessing:  16%|█▌        | 1316/8455 [01:04<08:08, 14.60it/s]

Preprocessing:  16%|█▌        | 1318/8455 [01:04<07:56, 14.97it/s]

Preprocessing:  16%|█▌        | 1320/8455 [01:04<08:06, 14.66it/s]

Preprocessing:  16%|█▌        | 1322/8455 [01:04<07:50, 15.17it/s]

Preprocessing:  16%|█▌        | 1324/8455 [01:04<07:35, 15.66it/s]

Preprocessing:  16%|█▌        | 1326/8455 [01:04<07:35, 15.66it/s]

Preprocessing:  16%|█▌        | 1328/8455 [01:05<07:49, 15.17it/s]

Preprocessing:  16%|█▌        | 1330/8455 [01:05<07:52, 15.08it/s]

Preprocessing:  16%|█▌        | 1332/8455 [01:05<07:44, 15.34it/s]

Preprocessing:  16%|█▌        | 1334/8455 [01:05<07:46, 15.27it/s]

Preprocessing:  16%|█▌        | 1336/8455 [01:05<07:44, 15.33it/s]

Preprocessing:  16%|█▌        | 1338/8455 [01:05<07:49, 15.16it/s]

Preprocessing:  16%|█▌        | 1340/8455 [01:05<07:57, 14.89it/s]

Preprocessing:  16%|█▌        | 1342/8455 [01:06<07:46, 15.25it/s]

Preprocessing:  16%|█▌        | 1344/8455 [01:06<07:51, 15.07it/s]

Preprocessing:  16%|█▌        | 1346/8455 [01:06<07:52, 15.03it/s]

Preprocessing:  16%|█▌        | 1348/8455 [01:06<07:45, 15.27it/s]

Preprocessing:  16%|█▌        | 1350/8455 [01:06<07:56, 14.91it/s]

Preprocessing:  16%|█▌        | 1352/8455 [01:06<08:11, 14.46it/s]

Preprocessing:  16%|█▌        | 1354/8455 [01:06<08:18, 14.24it/s]

Preprocessing:  16%|█▌        | 1356/8455 [01:07<08:39, 13.67it/s]

Preprocessing:  16%|█▌        | 1358/8455 [01:07<08:27, 14.00it/s]

Preprocessing:  16%|█▌        | 1360/8455 [01:07<08:34, 13.79it/s]

Preprocessing:  16%|█▌        | 1362/8455 [01:07<08:22, 14.12it/s]

Preprocessing:  16%|█▌        | 1364/8455 [01:07<08:16, 14.29it/s]

Preprocessing:  16%|█▌        | 1366/8455 [01:07<08:05, 14.60it/s]

Preprocessing:  16%|█▌        | 1368/8455 [01:07<08:38, 13.66it/s]

Preprocessing:  16%|█▌        | 1370/8455 [01:07<08:31, 13.86it/s]

Preprocessing:  16%|█▌        | 1372/8455 [01:08<08:22, 14.10it/s]

Preprocessing:  16%|█▋        | 1374/8455 [01:08<08:15, 14.28it/s]

Preprocessing:  16%|█▋        | 1376/8455 [01:08<07:54, 14.91it/s]

Preprocessing:  16%|█▋        | 1378/8455 [01:08<07:48, 15.09it/s]

Preprocessing:  16%|█▋        | 1380/8455 [01:08<07:42, 15.31it/s]

Preprocessing:  16%|█▋        | 1382/8455 [01:08<07:35, 15.52it/s]

Preprocessing:  16%|█▋        | 1384/8455 [01:08<07:37, 15.47it/s]

Preprocessing:  16%|█▋        | 1386/8455 [01:09<07:44, 15.21it/s]

Preprocessing:  16%|█▋        | 1388/8455 [01:09<07:42, 15.29it/s]

Preprocessing:  16%|█▋        | 1390/8455 [01:09<07:34, 15.53it/s]

Preprocessing:  16%|█▋        | 1392/8455 [01:09<07:38, 15.42it/s]

Preprocessing:  16%|█▋        | 1394/8455 [01:09<07:32, 15.61it/s]

Preprocessing:  17%|█▋        | 1396/8455 [01:09<07:11, 16.35it/s]

Preprocessing:  17%|█▋        | 1398/8455 [01:09<06:53, 17.09it/s]

Preprocessing:  17%|█▋        | 1400/8455 [01:09<06:36, 17.77it/s]

Preprocessing:  17%|█▋        | 1403/8455 [01:10<06:14, 18.81it/s]

Preprocessing:  17%|█▋        | 1405/8455 [01:10<06:12, 18.92it/s]

Preprocessing:  17%|█▋        | 1408/8455 [01:10<05:52, 19.99it/s]

Preprocessing:  17%|█▋        | 1410/8455 [01:10<06:17, 18.66it/s]

Preprocessing:  17%|█▋        | 1412/8455 [01:10<06:18, 18.62it/s]

Preprocessing:  17%|█▋        | 1414/8455 [01:10<06:16, 18.72it/s]

Preprocessing:  17%|█▋        | 1417/8455 [01:10<05:51, 20.02it/s]

Preprocessing:  17%|█▋        | 1420/8455 [01:10<05:51, 20.01it/s]

Preprocessing:  17%|█▋        | 1423/8455 [01:11<05:48, 20.18it/s]

Preprocessing:  17%|█▋        | 1426/8455 [01:11<05:43, 20.44it/s]

Preprocessing:  17%|█▋        | 1429/8455 [01:11<05:41, 20.59it/s]

Preprocessing:  17%|█▋        | 1432/8455 [01:11<05:30, 21.24it/s]

Preprocessing:  17%|█▋        | 1435/8455 [01:11<05:42, 20.47it/s]

Preprocessing:  17%|█▋        | 1438/8455 [01:11<05:30, 21.20it/s]

Preprocessing:  17%|█▋        | 1441/8455 [01:11<05:21, 21.84it/s]

Preprocessing:  17%|█▋        | 1444/8455 [01:11<05:18, 22.02it/s]

Preprocessing:  17%|█▋        | 1447/8455 [01:12<05:14, 22.28it/s]

Preprocessing:  17%|█▋        | 1450/8455 [01:12<05:04, 22.97it/s]

Preprocessing:  17%|█▋        | 1453/8455 [01:12<04:58, 23.49it/s]

Preprocessing:  17%|█▋        | 1456/8455 [01:12<04:52, 23.91it/s]

Preprocessing:  17%|█▋        | 1459/8455 [01:12<05:12, 22.42it/s]

Preprocessing:  17%|█▋        | 1462/8455 [01:12<05:09, 22.62it/s]

Preprocessing:  17%|█▋        | 1465/8455 [01:12<05:00, 23.30it/s]

Preprocessing:  17%|█▋        | 1468/8455 [01:12<04:47, 24.34it/s]

Preprocessing:  17%|█▋        | 1471/8455 [01:13<04:47, 24.29it/s]

Preprocessing:  17%|█▋        | 1474/8455 [01:13<04:46, 24.38it/s]

Preprocessing:  17%|█▋        | 1477/8455 [01:13<04:40, 24.84it/s]

Preprocessing:  18%|█▊        | 1480/8455 [01:13<04:40, 24.86it/s]

Preprocessing:  18%|█▊        | 1483/8455 [01:13<04:39, 24.96it/s]

Preprocessing:  18%|█▊        | 1486/8455 [01:13<04:38, 25.05it/s]

Preprocessing:  18%|█▊        | 1489/8455 [01:13<04:40, 24.81it/s]

Preprocessing:  18%|█▊        | 1492/8455 [01:13<04:41, 24.73it/s]

Preprocessing:  18%|█▊        | 1495/8455 [01:14<04:42, 24.61it/s]

Preprocessing:  18%|█▊        | 1498/8455 [01:14<04:42, 24.66it/s]

Preprocessing:  18%|█▊        | 1501/8455 [01:14<04:50, 23.97it/s]

Preprocessing:  18%|█▊        | 1504/8455 [01:14<04:46, 24.30it/s]

Preprocessing:  18%|█▊        | 1507/8455 [01:14<04:44, 24.40it/s]

Preprocessing:  18%|█▊        | 1510/8455 [01:14<04:42, 24.59it/s]

Preprocessing:  18%|█▊        | 1513/8455 [01:14<04:37, 24.99it/s]

Preprocessing:  18%|█▊        | 1516/8455 [01:14<04:37, 25.00it/s]

Preprocessing:  18%|█▊        | 1519/8455 [01:15<04:41, 24.68it/s]

Preprocessing:  18%|█▊        | 1522/8455 [01:15<04:38, 24.86it/s]

Preprocessing:  18%|█▊        | 1525/8455 [01:15<04:44, 24.39it/s]

Preprocessing:  18%|█▊        | 1528/8455 [01:15<04:38, 24.91it/s]

Preprocessing:  18%|█▊        | 1531/8455 [01:15<04:36, 25.06it/s]

Preprocessing:  18%|█▊        | 1534/8455 [01:15<04:40, 24.69it/s]

Preprocessing:  18%|█▊        | 1537/8455 [01:15<04:41, 24.55it/s]

Preprocessing:  18%|█▊        | 1540/8455 [01:15<04:46, 24.11it/s]

Preprocessing:  18%|█▊        | 1543/8455 [01:16<04:43, 24.37it/s]

Preprocessing:  18%|█▊        | 1546/8455 [01:16<04:41, 24.52it/s]

Preprocessing:  18%|█▊        | 1549/8455 [01:16<04:43, 24.33it/s]

Preprocessing:  18%|█▊        | 1552/8455 [01:16<04:41, 24.50it/s]

Preprocessing:  18%|█▊        | 1555/8455 [01:16<04:36, 24.97it/s]

Preprocessing:  18%|█▊        | 1558/8455 [01:16<04:39, 24.68it/s]

Preprocessing:  18%|█▊        | 1561/8455 [01:16<04:39, 24.68it/s]

Preprocessing:  18%|█▊        | 1564/8455 [01:16<04:46, 24.03it/s]

Preprocessing:  19%|█▊        | 1567/8455 [01:17<05:09, 22.24it/s]

Preprocessing:  19%|█▊        | 1570/8455 [01:17<05:03, 22.67it/s]

Preprocessing:  19%|█▊        | 1573/8455 [01:17<04:56, 23.20it/s]

Preprocessing:  19%|█▊        | 1576/8455 [01:17<04:57, 23.10it/s]

Preprocessing:  19%|█▊        | 1579/8455 [01:17<04:56, 23.20it/s]

Preprocessing:  19%|█▊        | 1582/8455 [01:17<04:53, 23.44it/s]

Preprocessing:  19%|█▊        | 1585/8455 [01:17<04:52, 23.46it/s]

Preprocessing:  19%|█▉        | 1588/8455 [01:17<04:49, 23.72it/s]

Preprocessing:  19%|█▉        | 1591/8455 [01:18<04:42, 24.31it/s]

Preprocessing:  19%|█▉        | 1594/8455 [01:18<04:39, 24.56it/s]

Preprocessing:  19%|█▉        | 1597/8455 [01:18<04:43, 24.17it/s]

Preprocessing:  19%|█▉        | 1600/8455 [01:18<04:41, 24.38it/s]

Preprocessing:  19%|█▉        | 1603/8455 [01:18<05:06, 22.36it/s]

Preprocessing:  19%|█▉        | 1606/8455 [01:18<05:35, 20.39it/s]

Preprocessing:  19%|█▉        | 1609/8455 [01:18<05:38, 20.20it/s]

Preprocessing:  19%|█▉        | 1612/8455 [01:19<05:29, 20.74it/s]

Preprocessing:  19%|█▉        | 1615/8455 [01:19<05:15, 21.65it/s]

Preprocessing:  19%|█▉        | 1618/8455 [01:19<05:04, 22.43it/s]

Preprocessing:  19%|█▉        | 1621/8455 [01:19<04:52, 23.36it/s]

Preprocessing:  19%|█▉        | 1624/8455 [01:19<04:46, 23.88it/s]

Preprocessing:  19%|█▉        | 1627/8455 [01:19<04:42, 24.17it/s]

Preprocessing:  19%|█▉        | 1630/8455 [01:19<04:40, 24.29it/s]

Preprocessing:  19%|█▉        | 1633/8455 [01:19<04:38, 24.50it/s]

Preprocessing:  19%|█▉        | 1636/8455 [01:20<05:12, 21.79it/s]

Preprocessing:  19%|█▉        | 1639/8455 [01:20<05:49, 19.51it/s]

Preprocessing:  19%|█▉        | 1642/8455 [01:20<05:31, 20.55it/s]

Preprocessing:  19%|█▉        | 1645/8455 [01:20<05:13, 21.70it/s]

Preprocessing:  19%|█▉        | 1648/8455 [01:20<05:01, 22.61it/s]

Preprocessing:  20%|█▉        | 1651/8455 [01:20<04:53, 23.19it/s]

Preprocessing:  20%|█▉        | 1654/8455 [01:20<04:45, 23.80it/s]

Preprocessing:  20%|█▉        | 1657/8455 [01:20<04:42, 24.06it/s]

Preprocessing:  20%|█▉        | 1660/8455 [01:21<04:38, 24.38it/s]

Preprocessing:  20%|█▉        | 1663/8455 [01:21<04:38, 24.37it/s]

Preprocessing:  20%|█▉        | 1666/8455 [01:21<04:38, 24.42it/s]

Preprocessing:  20%|█▉        | 1669/8455 [01:21<04:31, 24.99it/s]

Preprocessing:  20%|█▉        | 1672/8455 [01:21<04:30, 25.08it/s]

Preprocessing:  20%|█▉        | 1675/8455 [01:21<04:30, 25.08it/s]

Preprocessing:  20%|█▉        | 1678/8455 [01:21<04:31, 24.94it/s]

Preprocessing:  20%|█▉        | 1681/8455 [01:21<04:43, 23.86it/s]

Preprocessing:  20%|█▉        | 1684/8455 [01:22<05:08, 21.93it/s]

Preprocessing:  20%|█▉        | 1687/8455 [01:22<05:25, 20.76it/s]

Preprocessing:  20%|█▉        | 1690/8455 [01:22<05:39, 19.93it/s]

Preprocessing:  20%|██        | 1693/8455 [01:22<05:40, 19.87it/s]

Preprocessing:  20%|██        | 1696/8455 [01:22<05:42, 19.71it/s]

Preprocessing:  20%|██        | 1698/8455 [01:22<05:47, 19.44it/s]

Preprocessing:  20%|██        | 1700/8455 [01:22<05:51, 19.21it/s]

Preprocessing:  20%|██        | 1702/8455 [01:23<05:51, 19.23it/s]

Preprocessing:  20%|██        | 1704/8455 [01:23<05:54, 19.05it/s]

Preprocessing:  20%|██        | 1706/8455 [01:23<06:04, 18.53it/s]

Preprocessing:  20%|██        | 1708/8455 [01:23<06:08, 18.31it/s]

Preprocessing:  20%|██        | 1710/8455 [01:23<06:16, 17.94it/s]

Preprocessing:  20%|██        | 1712/8455 [01:23<06:14, 17.99it/s]

Preprocessing:  20%|██        | 1714/8455 [01:23<06:09, 18.22it/s]

Preprocessing:  20%|██        | 1716/8455 [01:23<06:02, 18.57it/s]

Preprocessing:  20%|██        | 1718/8455 [01:23<06:15, 17.94it/s]

Preprocessing:  20%|██        | 1721/8455 [01:24<05:50, 19.21it/s]

Preprocessing:  20%|██        | 1724/8455 [01:24<05:26, 20.60it/s]

Preprocessing:  20%|██        | 1727/8455 [01:24<05:14, 21.39it/s]

Preprocessing:  20%|██        | 1730/8455 [01:24<05:00, 22.38it/s]

Preprocessing:  20%|██        | 1733/8455 [01:24<05:07, 21.86it/s]

Preprocessing:  21%|██        | 1736/8455 [01:24<04:56, 22.65it/s]

Preprocessing:  21%|██        | 1739/8455 [01:24<04:47, 23.33it/s]

Preprocessing:  21%|██        | 1742/8455 [01:24<04:42, 23.77it/s]

Preprocessing:  21%|██        | 1745/8455 [01:25<04:42, 23.73it/s]

Preprocessing:  21%|██        | 1748/8455 [01:25<04:59, 22.38it/s]

Preprocessing:  21%|██        | 1751/8455 [01:25<04:57, 22.54it/s]

Preprocessing:  21%|██        | 1754/8455 [01:25<04:52, 22.89it/s]

Preprocessing:  21%|██        | 1757/8455 [01:25<04:48, 23.20it/s]

Preprocessing:  21%|██        | 1760/8455 [01:25<04:48, 23.23it/s]

Preprocessing:  21%|██        | 1763/8455 [01:25<04:47, 23.29it/s]

Preprocessing:  21%|██        | 1766/8455 [01:26<05:31, 20.18it/s]

Preprocessing:  21%|██        | 1769/8455 [01:26<06:30, 17.14it/s]

Preprocessing:  21%|██        | 1771/8455 [01:26<06:41, 16.63it/s]

Preprocessing:  21%|██        | 1773/8455 [01:26<07:08, 15.58it/s]

Preprocessing:  21%|██        | 1775/8455 [01:26<07:28, 14.90it/s]

Preprocessing:  21%|██        | 1777/8455 [01:26<07:36, 14.64it/s]

Preprocessing:  21%|██        | 1779/8455 [01:27<07:34, 14.67it/s]

Preprocessing:  21%|██        | 1781/8455 [01:27<07:49, 14.23it/s]

Preprocessing:  21%|██        | 1783/8455 [01:27<07:46, 14.32it/s]

Preprocessing:  21%|██        | 1785/8455 [01:27<07:38, 14.54it/s]

Preprocessing:  21%|██        | 1787/8455 [01:27<07:41, 14.46it/s]

Preprocessing:  21%|██        | 1789/8455 [01:27<07:44, 14.37it/s]

Preprocessing:  21%|██        | 1791/8455 [01:27<07:46, 14.27it/s]

Preprocessing:  21%|██        | 1793/8455 [01:28<07:55, 14.02it/s]

Preprocessing:  21%|██        | 1795/8455 [01:28<07:49, 14.17it/s]

Preprocessing:  21%|██▏       | 1797/8455 [01:28<08:04, 13.74it/s]

Preprocessing:  21%|██▏       | 1799/8455 [01:28<08:01, 13.82it/s]

Preprocessing:  21%|██▏       | 1801/8455 [01:28<07:42, 14.38it/s]

Preprocessing:  21%|██▏       | 1803/8455 [01:28<07:30, 14.75it/s]

Preprocessing:  21%|██▏       | 1805/8455 [01:28<07:24, 14.96it/s]

Preprocessing:  21%|██▏       | 1807/8455 [01:29<08:06, 13.66it/s]

Preprocessing:  21%|██▏       | 1809/8455 [01:29<08:30, 13.02it/s]

Preprocessing:  21%|██▏       | 1811/8455 [01:29<08:50, 12.51it/s]

Preprocessing:  21%|██▏       | 1813/8455 [01:29<09:00, 12.30it/s]

Preprocessing:  21%|██▏       | 1815/8455 [01:29<09:31, 11.62it/s]

Preprocessing:  21%|██▏       | 1817/8455 [01:29<09:57, 11.11it/s]

Preprocessing:  22%|██▏       | 1819/8455 [01:30<09:34, 11.56it/s]

Preprocessing:  22%|██▏       | 1821/8455 [01:30<09:11, 12.02it/s]

Preprocessing:  22%|██▏       | 1823/8455 [01:30<08:58, 12.31it/s]

Preprocessing:  22%|██▏       | 1825/8455 [01:30<08:59, 12.30it/s]

Preprocessing:  22%|██▏       | 1827/8455 [01:30<08:50, 12.50it/s]

Preprocessing:  22%|██▏       | 1829/8455 [01:30<08:42, 12.69it/s]

Preprocessing:  22%|██▏       | 1831/8455 [01:31<08:49, 12.51it/s]

Preprocessing:  22%|██▏       | 1833/8455 [01:31<09:00, 12.25it/s]

Preprocessing:  22%|██▏       | 1835/8455 [01:31<08:23, 13.14it/s]

Preprocessing:  22%|██▏       | 1837/8455 [01:31<08:05, 13.64it/s]

Preprocessing:  22%|██▏       | 1839/8455 [01:31<08:04, 13.65it/s]

Preprocessing:  22%|██▏       | 1841/8455 [01:31<08:46, 12.56it/s]

Preprocessing:  22%|██▏       | 1843/8455 [01:31<09:07, 12.08it/s]

Preprocessing:  22%|██▏       | 1845/8455 [01:32<08:32, 12.90it/s]

Preprocessing:  22%|██▏       | 1847/8455 [01:32<08:03, 13.66it/s]

Preprocessing:  22%|██▏       | 1849/8455 [01:32<09:07, 12.07it/s]

Preprocessing:  22%|██▏       | 1851/8455 [01:32<08:32, 12.89it/s]

Preprocessing:  22%|██▏       | 1853/8455 [01:32<08:09, 13.48it/s]

Preprocessing:  22%|██▏       | 1855/8455 [01:32<08:07, 13.54it/s]

Preprocessing:  22%|██▏       | 1857/8455 [01:33<08:01, 13.70it/s]

Preprocessing:  22%|██▏       | 1859/8455 [01:33<07:48, 14.07it/s]

Preprocessing:  22%|██▏       | 1861/8455 [01:33<07:33, 14.55it/s]

Preprocessing:  22%|██▏       | 1863/8455 [01:33<07:17, 15.06it/s]

Preprocessing:  22%|██▏       | 1865/8455 [01:33<07:26, 14.77it/s]

Preprocessing:  22%|██▏       | 1867/8455 [01:33<07:33, 14.52it/s]

Preprocessing:  22%|██▏       | 1869/8455 [01:33<08:13, 13.35it/s]

Preprocessing:  22%|██▏       | 1871/8455 [01:34<08:08, 13.49it/s]

Preprocessing:  22%|██▏       | 1873/8455 [01:34<07:54, 13.89it/s]

Preprocessing:  22%|██▏       | 1875/8455 [01:34<07:34, 14.49it/s]

Preprocessing:  22%|██▏       | 1877/8455 [01:34<07:29, 14.62it/s]

Preprocessing:  22%|██▏       | 1879/8455 [01:34<07:16, 15.07it/s]

Preprocessing:  22%|██▏       | 1881/8455 [01:34<07:08, 15.35it/s]

Preprocessing:  22%|██▏       | 1883/8455 [01:34<07:14, 15.11it/s]

Preprocessing:  22%|██▏       | 1885/8455 [01:34<07:03, 15.52it/s]

Preprocessing:  22%|██▏       | 1887/8455 [01:35<06:52, 15.92it/s]

Preprocessing:  22%|██▏       | 1889/8455 [01:35<06:44, 16.22it/s]

Preprocessing:  22%|██▏       | 1891/8455 [01:35<06:42, 16.30it/s]

Preprocessing:  22%|██▏       | 1893/8455 [01:35<07:10, 15.26it/s]

Preprocessing:  22%|██▏       | 1895/8455 [01:35<07:09, 15.29it/s]

Preprocessing:  22%|██▏       | 1897/8455 [01:35<07:07, 15.33it/s]

Preprocessing:  22%|██▏       | 1899/8455 [01:35<07:12, 15.15it/s]

Preprocessing:  22%|██▏       | 1901/8455 [01:35<07:04, 15.46it/s]

Preprocessing:  23%|██▎       | 1903/8455 [01:36<06:58, 15.64it/s]

Preprocessing:  23%|██▎       | 1905/8455 [01:36<06:57, 15.67it/s]

Preprocessing:  23%|██▎       | 1907/8455 [01:36<07:09, 15.24it/s]

Preprocessing:  23%|██▎       | 1909/8455 [01:36<06:56, 15.72it/s]

Preprocessing:  23%|██▎       | 1911/8455 [01:36<06:54, 15.79it/s]

Preprocessing:  23%|██▎       | 1913/8455 [01:36<06:51, 15.88it/s]

Preprocessing:  23%|██▎       | 1915/8455 [01:36<07:07, 15.31it/s]

Preprocessing:  23%|██▎       | 1917/8455 [01:36<06:58, 15.62it/s]

Preprocessing:  23%|██▎       | 1919/8455 [01:37<06:51, 15.87it/s]

Preprocessing:  23%|██▎       | 1921/8455 [01:37<06:46, 16.08it/s]

Preprocessing:  23%|██▎       | 1923/8455 [01:37<06:50, 15.90it/s]

Preprocessing:  23%|██▎       | 1925/8455 [01:37<06:42, 16.22it/s]

Preprocessing:  23%|██▎       | 1927/8455 [01:37<06:39, 16.33it/s]

Preprocessing:  23%|██▎       | 1929/8455 [01:37<06:33, 16.57it/s]

Preprocessing:  23%|██▎       | 1931/8455 [01:37<06:34, 16.52it/s]

Preprocessing:  23%|██▎       | 1933/8455 [01:37<06:39, 16.31it/s]

Preprocessing:  23%|██▎       | 1935/8455 [01:38<06:56, 15.64it/s]

Preprocessing:  23%|██▎       | 1937/8455 [01:38<06:50, 15.89it/s]

Preprocessing:  23%|██▎       | 1939/8455 [01:38<06:43, 16.13it/s]

Preprocessing:  23%|██▎       | 1941/8455 [01:38<06:42, 16.17it/s]

Preprocessing:  23%|██▎       | 1943/8455 [01:38<06:41, 16.21it/s]

Preprocessing:  23%|██▎       | 1945/8455 [01:38<06:45, 16.07it/s]

Preprocessing:  23%|██▎       | 1947/8455 [01:38<06:51, 15.82it/s]

Preprocessing:  23%|██▎       | 1949/8455 [01:38<07:10, 15.10it/s]

Preprocessing:  23%|██▎       | 1951/8455 [01:39<07:01, 15.44it/s]

Preprocessing:  23%|██▎       | 1953/8455 [01:39<06:53, 15.73it/s]

Preprocessing:  23%|██▎       | 1955/8455 [01:39<06:44, 16.07it/s]

Preprocessing:  23%|██▎       | 1957/8455 [01:39<06:43, 16.12it/s]

Preprocessing:  23%|██▎       | 1959/8455 [01:39<06:58, 15.52it/s]

Preprocessing:  23%|██▎       | 1961/8455 [01:39<06:53, 15.72it/s]

Preprocessing:  23%|██▎       | 1963/8455 [01:39<06:51, 15.79it/s]

Preprocessing:  23%|██▎       | 1965/8455 [01:39<06:53, 15.70it/s]

Preprocessing:  23%|██▎       | 1967/8455 [01:40<06:43, 16.07it/s]

Preprocessing:  23%|██▎       | 1969/8455 [01:40<06:43, 16.08it/s]

Preprocessing:  23%|██▎       | 1971/8455 [01:40<06:49, 15.83it/s]

Preprocessing:  23%|██▎       | 1973/8455 [01:40<06:44, 16.04it/s]

Preprocessing:  23%|██▎       | 1975/8455 [01:40<06:43, 16.06it/s]

Preprocessing:  23%|██▎       | 1977/8455 [01:40<06:49, 15.82it/s]

Preprocessing:  23%|██▎       | 1979/8455 [01:40<06:49, 15.81it/s]

Preprocessing:  23%|██▎       | 1981/8455 [01:40<06:46, 15.93it/s]

Preprocessing:  23%|██▎       | 1983/8455 [01:41<06:45, 15.95it/s]

Preprocessing:  23%|██▎       | 1985/8455 [01:41<06:42, 16.09it/s]

Preprocessing:  24%|██▎       | 1987/8455 [01:41<06:38, 16.25it/s]

Preprocessing:  24%|██▎       | 1989/8455 [01:41<06:38, 16.23it/s]

Preprocessing:  24%|██▎       | 1991/8455 [01:41<06:34, 16.37it/s]

Preprocessing:  24%|██▎       | 1993/8455 [01:41<06:55, 15.56it/s]

Preprocessing:  24%|██▎       | 1995/8455 [01:41<07:38, 14.09it/s]

Preprocessing:  24%|██▎       | 1997/8455 [01:42<07:19, 14.69it/s]

Preprocessing:  24%|██▎       | 1999/8455 [01:42<07:14, 14.85it/s]

Preprocessing:  24%|██▎       | 2001/8455 [01:42<07:10, 15.00it/s]

Preprocessing:  24%|██▎       | 2003/8455 [01:42<06:58, 15.43it/s]

Preprocessing:  24%|██▎       | 2005/8455 [01:42<06:48, 15.78it/s]

Preprocessing:  24%|██▎       | 2007/8455 [01:42<06:45, 15.92it/s]

Preprocessing:  24%|██▍       | 2009/8455 [01:42<06:50, 15.71it/s]

Preprocessing:  24%|██▍       | 2011/8455 [01:42<06:43, 15.96it/s]

Preprocessing:  24%|██▍       | 2013/8455 [01:43<06:43, 15.96it/s]

Preprocessing:  24%|██▍       | 2015/8455 [01:43<06:56, 15.48it/s]

Preprocessing:  24%|██▍       | 2017/8455 [01:43<07:07, 15.07it/s]

Preprocessing:  24%|██▍       | 2019/8455 [01:43<06:49, 15.72it/s]

Preprocessing:  24%|██▍       | 2021/8455 [01:43<06:45, 15.85it/s]

Preprocessing:  24%|██▍       | 2023/8455 [01:43<06:38, 16.12it/s]

Preprocessing:  24%|██▍       | 2025/8455 [01:43<06:42, 15.97it/s]

Preprocessing:  24%|██▍       | 2027/8455 [01:43<06:42, 15.96it/s]

Preprocessing:  24%|██▍       | 2029/8455 [01:44<06:41, 16.02it/s]

Preprocessing:  24%|██▍       | 2031/8455 [01:44<06:37, 16.14it/s]

Preprocessing:  24%|██▍       | 2033/8455 [01:44<06:49, 15.69it/s]

Preprocessing:  24%|██▍       | 2035/8455 [01:44<06:54, 15.48it/s]

Preprocessing:  24%|██▍       | 2037/8455 [01:44<06:44, 15.88it/s]

Preprocessing:  24%|██▍       | 2039/8455 [01:44<06:57, 15.38it/s]

Preprocessing:  24%|██▍       | 2041/8455 [01:44<06:49, 15.68it/s]

Preprocessing:  24%|██▍       | 2043/8455 [01:44<06:39, 16.07it/s]

Preprocessing:  24%|██▍       | 2045/8455 [01:45<06:38, 16.07it/s]

Preprocessing:  24%|██▍       | 2047/8455 [01:45<06:37, 16.13it/s]

Preprocessing:  24%|██▍       | 2049/8455 [01:45<06:34, 16.25it/s]

Preprocessing:  24%|██▍       | 2051/8455 [01:45<06:28, 16.47it/s]

Preprocessing:  24%|██▍       | 2053/8455 [01:45<06:36, 16.13it/s]

Preprocessing:  24%|██▍       | 2055/8455 [01:45<06:31, 16.34it/s]

Preprocessing:  24%|██▍       | 2057/8455 [01:45<06:30, 16.39it/s]

Preprocessing:  24%|██▍       | 2059/8455 [01:45<06:29, 16.44it/s]

Preprocessing:  24%|██▍       | 2061/8455 [01:46<06:30, 16.36it/s]

Preprocessing:  24%|██▍       | 2063/8455 [01:46<06:27, 16.51it/s]

Preprocessing:  24%|██▍       | 2065/8455 [01:46<06:27, 16.47it/s]

Preprocessing:  24%|██▍       | 2067/8455 [01:46<06:28, 16.42it/s]

Preprocessing:  24%|██▍       | 2069/8455 [01:46<06:27, 16.47it/s]

Preprocessing:  24%|██▍       | 2071/8455 [01:46<06:28, 16.42it/s]

Preprocessing:  25%|██▍       | 2073/8455 [01:46<06:33, 16.20it/s]

Preprocessing:  25%|██▍       | 2075/8455 [01:46<06:34, 16.18it/s]

Preprocessing:  25%|██▍       | 2077/8455 [01:46<06:35, 16.14it/s]

Preprocessing:  25%|██▍       | 2079/8455 [01:47<06:29, 16.36it/s]

Preprocessing:  25%|██▍       | 2081/8455 [01:47<06:50, 15.51it/s]

Preprocessing:  25%|██▍       | 2083/8455 [01:47<06:40, 15.92it/s]

Preprocessing:  25%|██▍       | 2085/8455 [01:47<06:35, 16.12it/s]

Preprocessing:  25%|██▍       | 2087/8455 [01:47<06:47, 15.63it/s]

Preprocessing:  25%|██▍       | 2089/8455 [01:47<06:42, 15.83it/s]

Preprocessing:  25%|██▍       | 2091/8455 [01:47<06:38, 15.97it/s]

Preprocessing:  25%|██▍       | 2093/8455 [01:47<06:38, 15.96it/s]

Preprocessing:  25%|██▍       | 2095/8455 [01:48<06:41, 15.85it/s]

Preprocessing:  25%|██▍       | 2097/8455 [01:48<06:36, 16.02it/s]

Preprocessing:  25%|██▍       | 2099/8455 [01:48<06:49, 15.52it/s]

Preprocessing:  25%|██▍       | 2101/8455 [01:48<06:42, 15.77it/s]

Preprocessing:  25%|██▍       | 2103/8455 [01:48<06:36, 16.03it/s]

Preprocessing:  25%|██▍       | 2105/8455 [01:48<06:32, 16.16it/s]

Preprocessing:  25%|██▍       | 2107/8455 [01:48<06:35, 16.04it/s]

Preprocessing:  25%|██▍       | 2109/8455 [01:49<07:01, 15.05it/s]

Preprocessing:  25%|██▍       | 2111/8455 [01:49<06:53, 15.36it/s]

Preprocessing:  25%|██▍       | 2113/8455 [01:49<06:43, 15.73it/s]

Preprocessing:  25%|██▌       | 2115/8455 [01:49<06:35, 16.01it/s]

Preprocessing:  25%|██▌       | 2117/8455 [01:49<06:34, 16.08it/s]

Preprocessing:  25%|██▌       | 2119/8455 [01:49<06:38, 15.90it/s]

Preprocessing:  25%|██▌       | 2121/8455 [01:49<06:39, 15.84it/s]

Preprocessing:  25%|██▌       | 2123/8455 [01:49<07:01, 15.02it/s]

Preprocessing:  25%|██▌       | 2125/8455 [01:50<06:51, 15.40it/s]

Preprocessing:  25%|██▌       | 2127/8455 [01:50<06:46, 15.57it/s]

Preprocessing:  25%|██▌       | 2129/8455 [01:50<06:44, 15.65it/s]

Preprocessing:  25%|██▌       | 2131/8455 [01:50<06:55, 15.21it/s]

Preprocessing:  25%|██▌       | 2133/8455 [01:50<06:44, 15.62it/s]

Preprocessing:  25%|██▌       | 2135/8455 [01:50<06:37, 15.91it/s]

Preprocessing:  25%|██▌       | 2137/8455 [01:50<06:38, 15.86it/s]

Preprocessing:  25%|██▌       | 2139/8455 [01:50<06:47, 15.51it/s]

Preprocessing:  25%|██▌       | 2141/8455 [01:51<07:13, 14.55it/s]

Preprocessing:  25%|██▌       | 2143/8455 [01:51<07:05, 14.83it/s]

Preprocessing:  25%|██▌       | 2145/8455 [01:51<06:56, 15.16it/s]

Preprocessing:  25%|██▌       | 2147/8455 [01:51<06:45, 15.56it/s]

Preprocessing:  25%|██▌       | 2149/8455 [01:51<06:53, 15.26it/s]

Preprocessing:  25%|██▌       | 2151/8455 [01:51<07:03, 14.88it/s]

Preprocessing:  25%|██▌       | 2153/8455 [01:51<06:49, 15.39it/s]

Preprocessing:  25%|██▌       | 2155/8455 [01:51<06:41, 15.67it/s]

Preprocessing:  26%|██▌       | 2157/8455 [01:52<06:35, 15.92it/s]

Preprocessing:  26%|██▌       | 2159/8455 [01:52<06:40, 15.73it/s]

Preprocessing:  26%|██▌       | 2161/8455 [01:52<06:35, 15.92it/s]

Preprocessing:  26%|██▌       | 2163/8455 [01:52<06:29, 16.13it/s]

Preprocessing:  26%|██▌       | 2165/8455 [01:52<06:27, 16.25it/s]

Preprocessing:  26%|██▌       | 2167/8455 [01:52<06:28, 16.18it/s]

Preprocessing:  26%|██▌       | 2169/8455 [01:52<06:28, 16.16it/s]

Preprocessing:  26%|██▌       | 2171/8455 [01:52<06:29, 16.15it/s]

Preprocessing:  26%|██▌       | 2173/8455 [01:53<07:01, 14.91it/s]

Preprocessing:  26%|██▌       | 2175/8455 [01:53<06:59, 14.97it/s]

Preprocessing:  26%|██▌       | 2177/8455 [01:53<06:46, 15.44it/s]

Preprocessing:  26%|██▌       | 2179/8455 [01:53<06:43, 15.57it/s]

Preprocessing:  26%|██▌       | 2181/8455 [01:53<06:36, 15.83it/s]

Preprocessing:  26%|██▌       | 2183/8455 [01:53<06:28, 16.14it/s]

Preprocessing:  26%|██▌       | 2185/8455 [01:53<06:26, 16.22it/s]

Preprocessing:  26%|██▌       | 2187/8455 [01:53<06:20, 16.47it/s]

Preprocessing:  26%|██▌       | 2189/8455 [01:54<06:23, 16.35it/s]

Preprocessing:  26%|██▌       | 2191/8455 [01:54<06:25, 16.24it/s]

Preprocessing:  26%|██▌       | 2193/8455 [01:54<06:36, 15.81it/s]

Preprocessing:  26%|██▌       | 2195/8455 [01:54<06:32, 15.96it/s]

Preprocessing:  26%|██▌       | 2197/8455 [01:54<06:27, 16.16it/s]

Preprocessing:  26%|██▌       | 2199/8455 [01:54<06:27, 16.14it/s]

Preprocessing:  26%|██▌       | 2201/8455 [01:54<06:41, 15.58it/s]

Preprocessing:  26%|██▌       | 2203/8455 [01:55<06:51, 15.19it/s]

Preprocessing:  26%|██▌       | 2205/8455 [01:55<06:52, 15.14it/s]

Preprocessing:  26%|██▌       | 2207/8455 [01:55<07:02, 14.78it/s]

Preprocessing:  26%|██▌       | 2209/8455 [01:55<06:47, 15.34it/s]

Preprocessing:  26%|██▌       | 2211/8455 [01:55<06:56, 15.00it/s]

Preprocessing:  26%|██▌       | 2213/8455 [01:55<06:51, 15.18it/s]

Preprocessing:  26%|██▌       | 2215/8455 [01:55<06:47, 15.32it/s]

Preprocessing:  26%|██▌       | 2217/8455 [01:55<06:56, 14.97it/s]

Preprocessing:  26%|██▌       | 2219/8455 [01:56<06:49, 15.22it/s]

Preprocessing:  26%|██▋       | 2221/8455 [01:56<06:44, 15.40it/s]

Preprocessing:  26%|██▋       | 2223/8455 [01:56<07:05, 14.66it/s]

Preprocessing:  26%|██▋       | 2225/8455 [01:56<07:03, 14.70it/s]

Preprocessing:  26%|██▋       | 2227/8455 [01:56<06:48, 15.25it/s]

Preprocessing:  26%|██▋       | 2229/8455 [01:56<06:37, 15.66it/s]

Preprocessing:  26%|██▋       | 2231/8455 [01:56<06:31, 15.90it/s]

Preprocessing:  26%|██▋       | 2233/8455 [01:56<06:26, 16.11it/s]

Preprocessing:  26%|██▋       | 2235/8455 [01:57<06:27, 16.03it/s]

Preprocessing:  26%|██▋       | 2237/8455 [01:57<06:45, 15.33it/s]

Preprocessing:  26%|██▋       | 2239/8455 [01:57<06:53, 15.02it/s]

Preprocessing:  27%|██▋       | 2241/8455 [01:57<06:40, 15.51it/s]

Preprocessing:  27%|██▋       | 2243/8455 [01:57<06:59, 14.79it/s]

Preprocessing:  27%|██▋       | 2245/8455 [01:57<06:47, 15.24it/s]

Preprocessing:  27%|██▋       | 2247/8455 [01:57<06:58, 14.83it/s]

Preprocessing:  27%|██▋       | 2249/8455 [01:58<06:46, 15.26it/s]

Preprocessing:  27%|██▋       | 2251/8455 [01:58<06:35, 15.68it/s]

Preprocessing:  27%|██▋       | 2253/8455 [01:58<06:30, 15.88it/s]

Preprocessing:  27%|██▋       | 2255/8455 [01:58<06:23, 16.18it/s]

Preprocessing:  27%|██▋       | 2257/8455 [01:58<06:44, 15.33it/s]

Preprocessing:  27%|██▋       | 2259/8455 [01:58<06:36, 15.61it/s]

Preprocessing:  27%|██▋       | 2261/8455 [01:58<06:35, 15.66it/s]

Preprocessing:  27%|██▋       | 2263/8455 [01:58<06:28, 15.94it/s]

Preprocessing:  27%|██▋       | 2265/8455 [01:59<06:26, 16.01it/s]

Preprocessing:  27%|██▋       | 2267/8455 [01:59<06:25, 16.07it/s]

Preprocessing:  27%|██▋       | 2269/8455 [01:59<06:21, 16.22it/s]

Preprocessing:  27%|██▋       | 2271/8455 [01:59<06:20, 16.25it/s]

Preprocessing:  27%|██▋       | 2273/8455 [01:59<06:24, 16.06it/s]

Preprocessing:  27%|██▋       | 2275/8455 [01:59<06:41, 15.41it/s]

Preprocessing:  27%|██▋       | 2277/8455 [01:59<06:46, 15.21it/s]

Preprocessing:  27%|██▋       | 2279/8455 [01:59<06:40, 15.41it/s]

Preprocessing:  27%|██▋       | 2281/8455 [02:00<06:39, 15.44it/s]

Preprocessing:  27%|██▋       | 2283/8455 [02:00<06:32, 15.74it/s]

Preprocessing:  27%|██▋       | 2285/8455 [02:00<06:29, 15.83it/s]

Preprocessing:  27%|██▋       | 2287/8455 [02:00<06:22, 16.12it/s]

Preprocessing:  27%|██▋       | 2289/8455 [02:00<06:44, 15.24it/s]

Preprocessing:  27%|██▋       | 2291/8455 [02:00<06:49, 15.04it/s]

Preprocessing:  27%|██▋       | 2293/8455 [02:00<06:42, 15.33it/s]

Preprocessing:  27%|██▋       | 2295/8455 [02:00<06:37, 15.51it/s]

Preprocessing:  27%|██▋       | 2297/8455 [02:01<06:28, 15.83it/s]

Preprocessing:  27%|██▋       | 2299/8455 [02:01<06:23, 16.07it/s]

Preprocessing:  27%|██▋       | 2301/8455 [02:01<06:21, 16.12it/s]

Preprocessing:  27%|██▋       | 2303/8455 [02:01<06:20, 16.17it/s]

Preprocessing:  27%|██▋       | 2305/8455 [02:01<06:11, 16.57it/s]

Preprocessing:  27%|██▋       | 2307/8455 [02:01<06:10, 16.57it/s]

Preprocessing:  27%|██▋       | 2309/8455 [02:01<06:05, 16.82it/s]

Preprocessing:  27%|██▋       | 2311/8455 [02:01<06:03, 16.89it/s]

Preprocessing:  27%|██▋       | 2313/8455 [02:02<06:04, 16.87it/s]

Preprocessing:  27%|██▋       | 2315/8455 [02:02<06:06, 16.75it/s]

Preprocessing:  27%|██▋       | 2317/8455 [02:02<06:04, 16.85it/s]

Preprocessing:  27%|██▋       | 2319/8455 [02:02<06:01, 16.98it/s]

Preprocessing:  27%|██▋       | 2321/8455 [02:02<06:07, 16.67it/s]

Preprocessing:  27%|██▋       | 2323/8455 [02:02<06:07, 16.70it/s]

Preprocessing:  27%|██▋       | 2325/8455 [02:02<06:04, 16.81it/s]

Preprocessing:  28%|██▊       | 2327/8455 [02:02<06:03, 16.84it/s]

Preprocessing:  28%|██▊       | 2329/8455 [02:02<06:03, 16.86it/s]

Preprocessing:  28%|██▊       | 2331/8455 [02:03<06:02, 16.87it/s]

Preprocessing:  28%|██▊       | 2333/8455 [02:03<06:23, 15.96it/s]

Preprocessing:  28%|██▊       | 2335/8455 [02:03<06:16, 16.26it/s]

Preprocessing:  28%|██▊       | 2337/8455 [02:03<06:12, 16.41it/s]

Preprocessing:  28%|██▊       | 2339/8455 [02:03<06:34, 15.50it/s]

Preprocessing:  28%|██▊       | 2341/8455 [02:03<07:20, 13.89it/s]

Preprocessing:  28%|██▊       | 2343/8455 [02:03<06:57, 14.63it/s]

Preprocessing:  28%|██▊       | 2345/8455 [02:04<06:39, 15.31it/s]

Preprocessing:  28%|██▊       | 2347/8455 [02:04<06:27, 15.78it/s]

Preprocessing:  28%|██▊       | 2349/8455 [02:04<06:22, 15.98it/s]

Preprocessing:  28%|██▊       | 2351/8455 [02:04<06:13, 16.36it/s]

Preprocessing:  28%|██▊       | 2353/8455 [02:04<06:08, 16.54it/s]

Preprocessing:  28%|██▊       | 2355/8455 [02:04<06:00, 16.90it/s]

Preprocessing:  28%|██▊       | 2357/8455 [02:04<06:01, 16.85it/s]

Preprocessing:  28%|██▊       | 2359/8455 [02:04<05:59, 16.95it/s]

Preprocessing:  28%|██▊       | 2361/8455 [02:04<05:57, 17.02it/s]

Preprocessing:  28%|██▊       | 2363/8455 [02:05<05:56, 17.10it/s]

Preprocessing:  28%|██▊       | 2365/8455 [02:05<05:55, 17.11it/s]

Preprocessing:  28%|██▊       | 2367/8455 [02:05<05:55, 17.11it/s]

Preprocessing:  28%|██▊       | 2369/8455 [02:05<05:51, 17.30it/s]

Preprocessing:  28%|██▊       | 2371/8455 [02:05<05:55, 17.09it/s]

Preprocessing:  28%|██▊       | 2373/8455 [02:05<05:54, 17.17it/s]

Preprocessing:  28%|██▊       | 2375/8455 [02:05<05:52, 17.25it/s]

Preprocessing:  28%|██▊       | 2377/8455 [02:05<05:57, 17.00it/s]

Preprocessing:  28%|██▊       | 2379/8455 [02:06<05:52, 17.25it/s]

Preprocessing:  28%|██▊       | 2381/8455 [02:06<05:53, 17.18it/s]

Preprocessing:  28%|██▊       | 2383/8455 [02:06<05:55, 17.07it/s]

Preprocessing:  28%|██▊       | 2385/8455 [02:06<05:58, 16.94it/s]

Preprocessing:  28%|██▊       | 2387/8455 [02:06<06:00, 16.85it/s]

Preprocessing:  28%|██▊       | 2389/8455 [02:06<05:55, 17.06it/s]

Preprocessing:  28%|██▊       | 2391/8455 [02:06<05:59, 16.86it/s]

Preprocessing:  28%|██▊       | 2393/8455 [02:06<06:28, 15.60it/s]

Preprocessing:  28%|██▊       | 2395/8455 [02:07<07:01, 14.38it/s]

Preprocessing:  28%|██▊       | 2397/8455 [02:07<07:10, 14.08it/s]

Preprocessing:  28%|██▊       | 2399/8455 [02:07<06:53, 14.65it/s]

Preprocessing:  28%|██▊       | 2401/8455 [02:07<06:42, 15.03it/s]

Preprocessing:  28%|██▊       | 2403/8455 [02:07<06:47, 14.84it/s]

Preprocessing:  28%|██▊       | 2405/8455 [02:07<06:33, 15.39it/s]

Preprocessing:  28%|██▊       | 2407/8455 [02:07<06:25, 15.69it/s]

Preprocessing:  28%|██▊       | 2409/8455 [02:07<06:21, 15.83it/s]

Preprocessing:  29%|██▊       | 2411/8455 [02:08<06:15, 16.08it/s]

Preprocessing:  29%|██▊       | 2413/8455 [02:08<06:19, 15.92it/s]

Preprocessing:  29%|██▊       | 2415/8455 [02:08<06:25, 15.68it/s]

Preprocessing:  29%|██▊       | 2417/8455 [02:08<06:20, 15.86it/s]

Preprocessing:  29%|██▊       | 2419/8455 [02:08<06:29, 15.50it/s]

Preprocessing:  29%|██▊       | 2421/8455 [02:08<06:21, 15.82it/s]

Preprocessing:  29%|██▊       | 2423/8455 [02:08<06:32, 15.35it/s]

Preprocessing:  29%|██▊       | 2425/8455 [02:08<06:41, 15.02it/s]

Preprocessing:  29%|██▊       | 2427/8455 [02:09<06:30, 15.45it/s]

Preprocessing:  29%|██▊       | 2429/8455 [02:09<06:37, 15.17it/s]

Preprocessing:  29%|██▉       | 2431/8455 [02:09<06:28, 15.52it/s]

Preprocessing:  29%|██▉       | 2433/8455 [02:09<06:41, 14.99it/s]

Preprocessing:  29%|██▉       | 2435/8455 [02:09<06:47, 14.77it/s]

Preprocessing:  29%|██▉       | 2437/8455 [02:09<06:38, 15.09it/s]

Preprocessing:  29%|██▉       | 2439/8455 [02:09<06:51, 14.62it/s]

Preprocessing:  29%|██▉       | 2441/8455 [02:10<06:51, 14.61it/s]

Preprocessing:  29%|██▉       | 2443/8455 [02:10<06:56, 14.42it/s]

Preprocessing:  29%|██▉       | 2445/8455 [02:10<06:41, 14.97it/s]

Preprocessing:  29%|██▉       | 2447/8455 [02:10<06:30, 15.39it/s]

Preprocessing:  29%|██▉       | 2449/8455 [02:10<06:41, 14.97it/s]

Preprocessing:  29%|██▉       | 2451/8455 [02:10<06:33, 15.25it/s]

Preprocessing:  29%|██▉       | 2453/8455 [02:10<06:37, 15.09it/s]

Preprocessing:  29%|██▉       | 2455/8455 [02:10<06:36, 15.12it/s]

Preprocessing:  29%|██▉       | 2457/8455 [02:11<06:35, 15.17it/s]

Preprocessing:  29%|██▉       | 2459/8455 [02:11<06:30, 15.36it/s]

Preprocessing:  29%|██▉       | 2461/8455 [02:11<06:37, 15.09it/s]

Preprocessing:  29%|██▉       | 2463/8455 [02:11<06:30, 15.35it/s]

Preprocessing:  29%|██▉       | 2465/8455 [02:11<06:23, 15.60it/s]

Preprocessing:  29%|██▉       | 2467/8455 [02:11<06:14, 15.98it/s]

Preprocessing:  29%|██▉       | 2469/8455 [02:11<06:08, 16.25it/s]

Preprocessing:  29%|██▉       | 2471/8455 [02:12<06:22, 15.64it/s]

Preprocessing:  29%|██▉       | 2473/8455 [02:12<06:26, 15.48it/s]

Preprocessing:  29%|██▉       | 2475/8455 [02:12<06:44, 14.78it/s]

Preprocessing:  29%|██▉       | 2477/8455 [02:12<06:34, 15.15it/s]

Preprocessing:  29%|██▉       | 2479/8455 [02:12<06:32, 15.22it/s]

Preprocessing:  29%|██▉       | 2481/8455 [02:12<06:22, 15.62it/s]

Preprocessing:  29%|██▉       | 2483/8455 [02:12<06:19, 15.75it/s]

Preprocessing:  29%|██▉       | 2485/8455 [02:12<06:29, 15.32it/s]

Preprocessing:  29%|██▉       | 2487/8455 [02:13<06:23, 15.57it/s]

Preprocessing:  29%|██▉       | 2489/8455 [02:13<06:36, 15.06it/s]

Preprocessing:  29%|██▉       | 2491/8455 [02:13<06:33, 15.16it/s]

Preprocessing:  29%|██▉       | 2493/8455 [02:13<07:03, 14.09it/s]

Preprocessing:  30%|██▉       | 2495/8455 [02:13<07:15, 13.69it/s]

Preprocessing:  30%|██▉       | 2497/8455 [02:13<06:54, 14.39it/s]

Preprocessing:  30%|██▉       | 2499/8455 [02:13<06:54, 14.39it/s]

Preprocessing:  30%|██▉       | 2501/8455 [02:14<06:37, 14.99it/s]

Preprocessing:  30%|██▉       | 2503/8455 [02:14<06:42, 14.79it/s]

Preprocessing:  30%|██▉       | 2505/8455 [02:14<06:26, 15.40it/s]

Preprocessing:  30%|██▉       | 2507/8455 [02:14<06:20, 15.64it/s]

Preprocessing:  30%|██▉       | 2509/8455 [02:14<06:12, 15.98it/s]

Preprocessing:  30%|██▉       | 2511/8455 [02:14<06:05, 16.26it/s]

Preprocessing:  30%|██▉       | 2513/8455 [02:14<06:07, 16.16it/s]

Preprocessing:  30%|██▉       | 2515/8455 [02:14<06:02, 16.40it/s]

Preprocessing:  30%|██▉       | 2517/8455 [02:15<06:06, 16.21it/s]

Preprocessing:  30%|██▉       | 2519/8455 [02:15<06:06, 16.20it/s]

Preprocessing:  30%|██▉       | 2521/8455 [02:15<06:14, 15.86it/s]

Preprocessing:  30%|██▉       | 2523/8455 [02:15<06:13, 15.90it/s]

Preprocessing:  30%|██▉       | 2525/8455 [02:15<06:12, 15.92it/s]

Preprocessing:  30%|██▉       | 2527/8455 [02:15<06:30, 15.18it/s]

Preprocessing:  30%|██▉       | 2529/8455 [02:15<06:26, 15.32it/s]

Preprocessing:  30%|██▉       | 2531/8455 [02:15<06:19, 15.60it/s]

Preprocessing:  30%|██▉       | 2533/8455 [02:16<06:10, 15.97it/s]

Preprocessing:  30%|██▉       | 2535/8455 [02:16<06:10, 15.98it/s]

Preprocessing:  30%|███       | 2537/8455 [02:16<06:04, 16.25it/s]

Preprocessing:  30%|███       | 2539/8455 [02:16<05:59, 16.44it/s]

Preprocessing:  30%|███       | 2541/8455 [02:16<05:50, 16.87it/s]

Preprocessing:  30%|███       | 2543/8455 [02:16<05:57, 16.55it/s]

Preprocessing:  30%|███       | 2545/8455 [02:16<06:14, 15.79it/s]

Preprocessing:  30%|███       | 2547/8455 [02:16<06:23, 15.41it/s]

Preprocessing:  30%|███       | 2549/8455 [02:17<06:31, 15.07it/s]

Preprocessing:  30%|███       | 2551/8455 [02:17<06:18, 15.60it/s]

Preprocessing:  30%|███       | 2553/8455 [02:17<06:09, 15.97it/s]

Preprocessing:  30%|███       | 2555/8455 [02:17<06:03, 16.24it/s]

Preprocessing:  30%|███       | 2557/8455 [02:17<05:59, 16.40it/s]

Preprocessing:  30%|███       | 2559/8455 [02:17<05:58, 16.43it/s]

Preprocessing:  30%|███       | 2561/8455 [02:17<05:56, 16.56it/s]

Preprocessing:  30%|███       | 2563/8455 [02:17<05:58, 16.42it/s]

Preprocessing:  30%|███       | 2565/8455 [02:18<05:58, 16.42it/s]

Preprocessing:  30%|███       | 2567/8455 [02:18<06:01, 16.29it/s]

Preprocessing:  30%|███       | 2569/8455 [02:18<06:07, 16.04it/s]

Preprocessing:  30%|███       | 2571/8455 [02:18<06:06, 16.07it/s]

Preprocessing:  30%|███       | 2573/8455 [02:18<06:19, 15.51it/s]

Preprocessing:  30%|███       | 2575/8455 [02:18<06:17, 15.60it/s]

Preprocessing:  30%|███       | 2577/8455 [02:18<06:47, 14.44it/s]

Preprocessing:  31%|███       | 2579/8455 [02:18<06:55, 14.13it/s]

Preprocessing:  31%|███       | 2581/8455 [02:19<06:53, 14.21it/s]

Preprocessing:  31%|███       | 2583/8455 [02:19<07:10, 13.65it/s]

Preprocessing:  31%|███       | 2585/8455 [02:19<06:49, 14.35it/s]

Preprocessing:  31%|███       | 2587/8455 [02:19<06:55, 14.13it/s]

Preprocessing:  31%|███       | 2589/8455 [02:19<06:36, 14.79it/s]

Preprocessing:  31%|███       | 2591/8455 [02:19<06:32, 14.93it/s]

Preprocessing:  31%|███       | 2593/8455 [02:19<06:28, 15.10it/s]

Preprocessing:  31%|███       | 2595/8455 [02:20<07:02, 13.88it/s]

Preprocessing:  31%|███       | 2597/8455 [02:20<07:44, 12.62it/s]

Preprocessing:  31%|███       | 2599/8455 [02:20<07:51, 12.42it/s]

Preprocessing:  31%|███       | 2601/8455 [02:20<07:24, 13.18it/s]

Preprocessing:  31%|███       | 2603/8455 [02:20<07:04, 13.78it/s]

Preprocessing:  31%|███       | 2605/8455 [02:20<06:53, 14.15it/s]

Preprocessing:  31%|███       | 2607/8455 [02:20<06:38, 14.66it/s]

Preprocessing:  31%|███       | 2609/8455 [02:21<06:21, 15.34it/s]

Preprocessing:  31%|███       | 2611/8455 [02:21<06:13, 15.65it/s]

Preprocessing:  31%|███       | 2613/8455 [02:21<06:10, 15.78it/s]

Preprocessing:  31%|███       | 2615/8455 [02:21<06:45, 14.41it/s]

Preprocessing:  31%|███       | 2617/8455 [02:21<06:32, 14.88it/s]

Preprocessing:  31%|███       | 2619/8455 [02:21<06:36, 14.72it/s]

Preprocessing:  31%|███       | 2621/8455 [02:21<06:39, 14.59it/s]

Preprocessing:  31%|███       | 2623/8455 [02:22<06:33, 14.83it/s]

Preprocessing:  31%|███       | 2625/8455 [02:22<06:23, 15.19it/s]

Preprocessing:  31%|███       | 2627/8455 [02:22<06:41, 14.51it/s]

Preprocessing:  31%|███       | 2629/8455 [02:22<07:13, 13.43it/s]

Preprocessing:  31%|███       | 2631/8455 [02:22<07:57, 12.21it/s]

Preprocessing:  31%|███       | 2633/8455 [02:22<07:44, 12.52it/s]

Preprocessing:  31%|███       | 2635/8455 [02:22<07:52, 12.31it/s]

Preprocessing:  31%|███       | 2637/8455 [02:23<07:47, 12.44it/s]

Preprocessing:  31%|███       | 2639/8455 [02:23<07:53, 12.29it/s]

Preprocessing:  31%|███       | 2641/8455 [02:23<07:03, 13.72it/s]

Preprocessing:  31%|███▏      | 2643/8455 [02:23<06:24, 15.11it/s]

Preprocessing:  31%|███▏      | 2645/8455 [02:23<05:59, 16.17it/s]

Preprocessing:  31%|███▏      | 2647/8455 [02:23<05:48, 16.66it/s]

Preprocessing:  31%|███▏      | 2650/8455 [02:23<05:22, 18.02it/s]

Preprocessing:  31%|███▏      | 2652/8455 [02:23<05:17, 18.30it/s]

Preprocessing:  31%|███▏      | 2654/8455 [02:24<05:14, 18.42it/s]

Preprocessing:  31%|███▏      | 2656/8455 [02:24<05:12, 18.54it/s]

Preprocessing:  31%|███▏      | 2658/8455 [02:24<05:19, 18.14it/s]

Preprocessing:  31%|███▏      | 2660/8455 [02:24<05:39, 17.06it/s]

Preprocessing:  31%|███▏      | 2663/8455 [02:24<05:19, 18.12it/s]

Preprocessing:  32%|███▏      | 2665/8455 [02:24<05:16, 18.28it/s]

Preprocessing:  32%|███▏      | 2667/8455 [02:24<05:10, 18.63it/s]

Preprocessing:  32%|███▏      | 2669/8455 [02:24<05:08, 18.78it/s]

Preprocessing:  32%|███▏      | 2671/8455 [02:25<05:04, 19.00it/s]

Preprocessing:  32%|███▏      | 2673/8455 [02:25<05:02, 19.14it/s]

Preprocessing:  32%|███▏      | 2675/8455 [02:25<05:07, 18.81it/s]

Preprocessing:  32%|███▏      | 2678/8455 [02:25<05:03, 19.04it/s]

Preprocessing:  32%|███▏      | 2681/8455 [02:25<04:57, 19.42it/s]

Preprocessing:  32%|███▏      | 2684/8455 [02:25<04:56, 19.48it/s]

Preprocessing:  32%|███▏      | 2686/8455 [02:25<05:01, 19.16it/s]

Preprocessing:  32%|███▏      | 2688/8455 [02:25<05:05, 18.89it/s]

Preprocessing:  32%|███▏      | 2690/8455 [02:26<05:04, 18.90it/s]

Preprocessing:  32%|███▏      | 2692/8455 [02:26<05:03, 18.99it/s]

Preprocessing:  32%|███▏      | 2694/8455 [02:26<05:09, 18.61it/s]

Preprocessing:  32%|███▏      | 2696/8455 [02:26<05:04, 18.94it/s]

Preprocessing:  32%|███▏      | 2698/8455 [02:26<05:04, 18.89it/s]

Preprocessing:  32%|███▏      | 2700/8455 [02:26<05:00, 19.17it/s]

Preprocessing:  32%|███▏      | 2703/8455 [02:26<04:54, 19.51it/s]

Preprocessing:  32%|███▏      | 2705/8455 [02:26<04:58, 19.25it/s]

Preprocessing:  32%|███▏      | 2707/8455 [02:26<04:59, 19.17it/s]

Preprocessing:  32%|███▏      | 2709/8455 [02:27<05:37, 17.05it/s]

Preprocessing:  32%|███▏      | 2711/8455 [02:27<06:43, 14.24it/s]

Preprocessing:  32%|███▏      | 2713/8455 [02:27<07:08, 13.39it/s]

Preprocessing:  32%|███▏      | 2715/8455 [02:27<06:44, 14.19it/s]

Preprocessing:  32%|███▏      | 2717/8455 [02:27<06:13, 15.38it/s]

Preprocessing:  32%|███▏      | 2719/8455 [02:27<05:50, 16.35it/s]

Preprocessing:  32%|███▏      | 2721/8455 [02:27<05:38, 16.92it/s]

Preprocessing:  32%|███▏      | 2723/8455 [02:27<05:29, 17.39it/s]

Preprocessing:  32%|███▏      | 2726/8455 [02:28<05:13, 18.27it/s]

Preprocessing:  32%|███▏      | 2728/8455 [02:28<05:07, 18.63it/s]

Preprocessing:  32%|███▏      | 2730/8455 [02:28<05:08, 18.58it/s]

Preprocessing:  32%|███▏      | 2732/8455 [02:28<05:18, 17.96it/s]

Preprocessing:  32%|███▏      | 2734/8455 [02:28<05:12, 18.29it/s]

Preprocessing:  32%|███▏      | 2736/8455 [02:28<05:13, 18.27it/s]

Preprocessing:  32%|███▏      | 2739/8455 [02:28<05:07, 18.57it/s]

Preprocessing:  32%|███▏      | 2742/8455 [02:28<05:05, 18.73it/s]

Preprocessing:  32%|███▏      | 2744/8455 [02:29<05:01, 18.92it/s]

Preprocessing:  32%|███▏      | 2746/8455 [02:29<05:03, 18.83it/s]

Preprocessing:  33%|███▎      | 2748/8455 [02:29<05:04, 18.73it/s]

Preprocessing:  33%|███▎      | 2750/8455 [02:29<05:04, 18.72it/s]

Preprocessing:  33%|███▎      | 2752/8455 [02:29<05:01, 18.90it/s]

Preprocessing:  33%|███▎      | 2754/8455 [02:29<05:01, 18.91it/s]

Preprocessing:  33%|███▎      | 2756/8455 [02:29<06:57, 13.66it/s]

Preprocessing:  33%|███▎      | 2758/8455 [02:29<06:42, 14.14it/s]

Preprocessing:  33%|███▎      | 2760/8455 [02:30<06:11, 15.32it/s]

Preprocessing:  33%|███▎      | 2762/8455 [02:30<05:57, 15.94it/s]

Preprocessing:  33%|███▎      | 2764/8455 [02:30<05:49, 16.30it/s]

Preprocessing:  33%|███▎      | 2766/8455 [02:30<05:48, 16.32it/s]

Preprocessing:  33%|███▎      | 2768/8455 [02:30<06:02, 15.70it/s]

Preprocessing:  33%|███▎      | 2770/8455 [02:30<07:30, 12.61it/s]

Preprocessing:  33%|███▎      | 2772/8455 [02:30<07:37, 12.42it/s]

Preprocessing:  33%|███▎      | 2774/8455 [02:31<07:05, 13.34it/s]

Preprocessing:  33%|███▎      | 2776/8455 [02:31<06:41, 14.15it/s]

Preprocessing:  33%|███▎      | 2778/8455 [02:31<06:31, 14.48it/s]

Preprocessing:  33%|███▎      | 2780/8455 [02:31<06:32, 14.45it/s]

Preprocessing:  33%|███▎      | 2782/8455 [02:31<06:16, 15.09it/s]

Preprocessing:  33%|███▎      | 2784/8455 [02:31<06:11, 15.26it/s]

Preprocessing:  33%|███▎      | 2786/8455 [02:31<06:06, 15.46it/s]

Preprocessing:  33%|███▎      | 2788/8455 [02:31<06:05, 15.51it/s]

Preprocessing:  33%|███▎      | 2790/8455 [02:32<05:58, 15.82it/s]

Preprocessing:  33%|███▎      | 2792/8455 [02:32<05:55, 15.92it/s]

Preprocessing:  33%|███▎      | 2794/8455 [02:32<05:59, 15.73it/s]

Preprocessing:  33%|███▎      | 2796/8455 [02:32<05:59, 15.76it/s]

Preprocessing:  33%|███▎      | 2798/8455 [02:32<06:08, 15.34it/s]

Preprocessing:  33%|███▎      | 2800/8455 [02:32<06:01, 15.66it/s]

Preprocessing:  33%|███▎      | 2802/8455 [02:32<05:57, 15.83it/s]

Preprocessing:  33%|███▎      | 2804/8455 [02:33<06:12, 15.17it/s]

Preprocessing:  33%|███▎      | 2806/8455 [02:33<06:06, 15.43it/s]

Preprocessing:  33%|███▎      | 2808/8455 [02:33<06:23, 14.74it/s]

Preprocessing:  33%|███▎      | 2810/8455 [02:33<06:29, 14.51it/s]

Preprocessing:  33%|███▎      | 2812/8455 [02:33<06:36, 14.22it/s]

Preprocessing:  33%|███▎      | 2814/8455 [02:33<06:58, 13.47it/s]

Preprocessing:  33%|███▎      | 2816/8455 [02:33<06:42, 14.01it/s]

Preprocessing:  33%|███▎      | 2818/8455 [02:34<06:32, 14.37it/s]

Preprocessing:  33%|███▎      | 2820/8455 [02:34<06:20, 14.79it/s]

Preprocessing:  33%|███▎      | 2822/8455 [02:34<06:18, 14.89it/s]

Preprocessing:  33%|███▎      | 2824/8455 [02:34<06:56, 13.52it/s]

Preprocessing:  33%|███▎      | 2826/8455 [02:34<07:19, 12.82it/s]

Preprocessing:  33%|███▎      | 2828/8455 [02:34<07:42, 12.16it/s]

Preprocessing:  33%|███▎      | 2830/8455 [02:34<07:10, 13.05it/s]

Preprocessing:  33%|███▎      | 2832/8455 [02:35<06:47, 13.79it/s]

Preprocessing:  34%|███▎      | 2834/8455 [02:35<07:15, 12.91it/s]

Preprocessing:  34%|███▎      | 2836/8455 [02:35<07:14, 12.93it/s]

Preprocessing:  34%|███▎      | 2838/8455 [02:35<06:47, 13.77it/s]

Preprocessing:  34%|███▎      | 2840/8455 [02:35<06:32, 14.29it/s]

Preprocessing:  34%|███▎      | 2842/8455 [02:35<06:25, 14.56it/s]

Preprocessing:  34%|███▎      | 2844/8455 [02:35<06:28, 14.45it/s]

Preprocessing:  34%|███▎      | 2846/8455 [02:36<06:20, 14.72it/s]

Preprocessing:  34%|███▎      | 2848/8455 [02:36<06:37, 14.12it/s]

Preprocessing:  34%|███▎      | 2850/8455 [02:36<06:23, 14.63it/s]

Preprocessing:  34%|███▎      | 2852/8455 [02:36<06:12, 15.04it/s]

Preprocessing:  34%|███▍      | 2854/8455 [02:36<06:12, 15.06it/s]

Preprocessing:  34%|███▍      | 2856/8455 [02:36<06:09, 15.16it/s]

Preprocessing:  34%|███▍      | 2858/8455 [02:36<06:22, 14.64it/s]

Preprocessing:  34%|███▍      | 2860/8455 [02:36<06:12, 15.03it/s]

Preprocessing:  34%|███▍      | 2862/8455 [02:37<06:04, 15.32it/s]

Preprocessing:  34%|███▍      | 2864/8455 [02:37<06:08, 15.19it/s]

Preprocessing:  34%|███▍      | 2866/8455 [02:37<06:00, 15.50it/s]

Preprocessing:  34%|███▍      | 2868/8455 [02:37<06:15, 14.88it/s]

Preprocessing:  34%|███▍      | 2870/8455 [02:37<06:06, 15.24it/s]

Preprocessing:  34%|███▍      | 2872/8455 [02:37<06:23, 14.56it/s]

Preprocessing:  34%|███▍      | 2874/8455 [02:37<06:22, 14.58it/s]

Preprocessing:  34%|███▍      | 2876/8455 [02:38<06:17, 14.78it/s]

Preprocessing:  34%|███▍      | 2878/8455 [02:38<06:20, 14.65it/s]

Preprocessing:  34%|███▍      | 2880/8455 [02:38<06:28, 14.35it/s]

Preprocessing:  34%|███▍      | 2882/8455 [02:38<06:33, 14.17it/s]

Preprocessing:  34%|███▍      | 2884/8455 [02:38<06:25, 14.46it/s]

Preprocessing:  34%|███▍      | 2886/8455 [02:38<06:25, 14.43it/s]

Preprocessing:  34%|███▍      | 2888/8455 [02:38<06:14, 14.86it/s]

Preprocessing:  34%|███▍      | 2890/8455 [02:39<06:20, 14.61it/s]

Preprocessing:  34%|███▍      | 2892/8455 [02:39<06:20, 14.62it/s]

Preprocessing:  34%|███▍      | 2894/8455 [02:39<06:27, 14.34it/s]

Preprocessing:  34%|███▍      | 2896/8455 [02:39<06:14, 14.83it/s]

Preprocessing:  34%|███▍      | 2898/8455 [02:39<06:12, 14.93it/s]

Preprocessing:  34%|███▍      | 2900/8455 [02:39<06:04, 15.25it/s]

Preprocessing:  34%|███▍      | 2902/8455 [02:39<06:05, 15.18it/s]

Preprocessing:  34%|███▍      | 2904/8455 [02:39<06:03, 15.26it/s]

Preprocessing:  34%|███▍      | 2906/8455 [02:40<05:57, 15.51it/s]

Preprocessing:  34%|███▍      | 2908/8455 [02:40<06:17, 14.70it/s]

Preprocessing:  34%|███▍      | 2910/8455 [02:40<06:05, 15.16it/s]

Preprocessing:  34%|███▍      | 2912/8455 [02:40<06:00, 15.38it/s]

Preprocessing:  34%|███▍      | 2914/8455 [02:40<05:56, 15.55it/s]

Preprocessing:  34%|███▍      | 2916/8455 [02:40<06:22, 14.48it/s]

Preprocessing:  35%|███▍      | 2918/8455 [02:40<06:11, 14.91it/s]

Preprocessing:  35%|███▍      | 2920/8455 [02:41<06:04, 15.18it/s]

Preprocessing:  35%|███▍      | 2922/8455 [02:41<05:57, 15.46it/s]

Preprocessing:  35%|███▍      | 2924/8455 [02:41<05:55, 15.58it/s]

Preprocessing:  35%|███▍      | 2926/8455 [02:41<05:49, 15.82it/s]

Preprocessing:  35%|███▍      | 2928/8455 [02:41<05:45, 16.01it/s]

Preprocessing:  35%|███▍      | 2930/8455 [02:41<05:45, 16.00it/s]

Preprocessing:  35%|███▍      | 2932/8455 [02:41<05:52, 15.68it/s]

Preprocessing:  35%|███▍      | 2934/8455 [02:41<05:54, 15.58it/s]

Preprocessing:  35%|███▍      | 2936/8455 [02:42<05:53, 15.60it/s]

Preprocessing:  35%|███▍      | 2938/8455 [02:42<05:58, 15.40it/s]

Preprocessing:  35%|███▍      | 2940/8455 [02:42<06:26, 14.28it/s]

Preprocessing:  35%|███▍      | 2942/8455 [02:42<06:33, 14.02it/s]

Preprocessing:  35%|███▍      | 2944/8455 [02:42<06:11, 14.83it/s]

Preprocessing:  35%|███▍      | 2946/8455 [02:42<06:08, 14.96it/s]

Preprocessing:  35%|███▍      | 2948/8455 [02:42<06:29, 14.16it/s]

Preprocessing:  35%|███▍      | 2950/8455 [02:43<06:30, 14.11it/s]

Preprocessing:  35%|███▍      | 2952/8455 [02:43<06:36, 13.88it/s]

Preprocessing:  35%|███▍      | 2954/8455 [02:43<06:55, 13.24it/s]

Preprocessing:  35%|███▍      | 2956/8455 [02:43<06:57, 13.17it/s]

Preprocessing:  35%|███▍      | 2958/8455 [02:43<06:50, 13.41it/s]

Preprocessing:  35%|███▌      | 2960/8455 [02:43<06:59, 13.10it/s]

Preprocessing:  35%|███▌      | 2962/8455 [02:43<07:06, 12.88it/s]

Preprocessing:  35%|███▌      | 2964/8455 [02:44<07:23, 12.39it/s]

Preprocessing:  35%|███▌      | 2966/8455 [02:44<07:36, 12.03it/s]

Preprocessing:  35%|███▌      | 2968/8455 [02:44<07:55, 11.53it/s]

Preprocessing:  35%|███▌      | 2970/8455 [02:44<07:56, 11.51it/s]

Preprocessing:  35%|███▌      | 2972/8455 [02:44<07:50, 11.65it/s]

Preprocessing:  35%|███▌      | 2974/8455 [02:44<07:38, 11.96it/s]

Preprocessing:  35%|███▌      | 2976/8455 [02:45<07:34, 12.06it/s]

Preprocessing:  35%|███▌      | 2978/8455 [02:45<07:35, 12.02it/s]

Preprocessing:  35%|███▌      | 2980/8455 [02:45<07:37, 11.96it/s]

Preprocessing:  35%|███▌      | 2982/8455 [02:45<07:40, 11.89it/s]

Preprocessing:  35%|███▌      | 2984/8455 [02:45<07:33, 12.07it/s]

Preprocessing:  35%|███▌      | 2986/8455 [02:46<07:45, 11.75it/s]

Preprocessing:  35%|███▌      | 2988/8455 [02:46<07:41, 11.85it/s]

Preprocessing:  35%|███▌      | 2990/8455 [02:46<07:51, 11.59it/s]

Preprocessing:  35%|███▌      | 2992/8455 [02:46<07:50, 11.62it/s]

Preprocessing:  35%|███▌      | 2994/8455 [02:46<07:37, 11.94it/s]

Preprocessing:  35%|███▌      | 2996/8455 [02:46<07:01, 12.94it/s]

Preprocessing:  35%|███▌      | 2998/8455 [02:46<06:50, 13.31it/s]

Preprocessing:  35%|███▌      | 3000/8455 [02:47<06:29, 14.02it/s]

Preprocessing:  36%|███▌      | 3002/8455 [02:47<06:13, 14.60it/s]

Preprocessing:  36%|███▌      | 3004/8455 [02:47<06:13, 14.58it/s]

Preprocessing:  36%|███▌      | 3006/8455 [02:47<06:17, 14.43it/s]

Preprocessing:  36%|███▌      | 3008/8455 [02:47<06:10, 14.71it/s]

Preprocessing:  36%|███▌      | 3010/8455 [02:47<06:02, 15.01it/s]

Preprocessing:  36%|███▌      | 3012/8455 [02:47<05:55, 15.30it/s]

Preprocessing:  36%|███▌      | 3014/8455 [02:47<05:56, 15.24it/s]

Preprocessing:  36%|███▌      | 3016/8455 [02:48<06:10, 14.69it/s]

Preprocessing:  36%|███▌      | 3018/8455 [02:48<05:59, 15.14it/s]

Preprocessing:  36%|███▌      | 3020/8455 [02:48<06:10, 14.69it/s]

Preprocessing:  36%|███▌      | 3022/8455 [02:48<06:18, 14.35it/s]

Preprocessing:  36%|███▌      | 3024/8455 [02:48<06:09, 14.69it/s]

Preprocessing:  36%|███▌      | 3026/8455 [02:48<06:29, 13.92it/s]

Preprocessing:  36%|███▌      | 3028/8455 [02:48<06:11, 14.60it/s]

Preprocessing:  36%|███▌      | 3030/8455 [02:49<06:00, 15.06it/s]

Preprocessing:  36%|███▌      | 3032/8455 [02:49<06:30, 13.87it/s]

Preprocessing:  36%|███▌      | 3034/8455 [02:49<06:46, 13.33it/s]

Preprocessing:  36%|███▌      | 3036/8455 [02:49<06:26, 14.02it/s]

Preprocessing:  36%|███▌      | 3038/8455 [02:49<06:11, 14.56it/s]

Preprocessing:  36%|███▌      | 3040/8455 [02:49<06:25, 14.03it/s]

Preprocessing:  36%|███▌      | 3042/8455 [02:49<06:10, 14.63it/s]

Preprocessing:  36%|███▌      | 3044/8455 [02:50<06:01, 14.97it/s]

Preprocessing:  36%|███▌      | 3046/8455 [02:50<05:50, 15.45it/s]

Preprocessing:  36%|███▌      | 3048/8455 [02:50<05:45, 15.67it/s]

Preprocessing:  36%|███▌      | 3050/8455 [02:50<05:49, 15.46it/s]

Preprocessing:  36%|███▌      | 3052/8455 [02:50<05:44, 15.67it/s]

Preprocessing:  36%|███▌      | 3054/8455 [02:50<05:43, 15.74it/s]

Preprocessing:  36%|███▌      | 3056/8455 [02:50<05:38, 15.94it/s]

Preprocessing:  36%|███▌      | 3058/8455 [02:50<05:36, 16.04it/s]

Preprocessing:  36%|███▌      | 3060/8455 [02:51<05:35, 16.08it/s]

Preprocessing:  36%|███▌      | 3062/8455 [02:51<05:36, 16.03it/s]

Preprocessing:  36%|███▌      | 3064/8455 [02:51<05:46, 15.58it/s]

Preprocessing:  36%|███▋      | 3066/8455 [02:51<05:55, 15.16it/s]

Preprocessing:  36%|███▋      | 3068/8455 [02:51<05:45, 15.57it/s]

Preprocessing:  36%|███▋      | 3070/8455 [02:51<05:41, 15.79it/s]

Preprocessing:  36%|███▋      | 3072/8455 [02:51<06:14, 14.37it/s]

Preprocessing:  36%|███▋      | 3074/8455 [02:52<06:08, 14.61it/s]

Preprocessing:  36%|███▋      | 3076/8455 [02:52<06:15, 14.32it/s]

Preprocessing:  36%|███▋      | 3078/8455 [02:52<06:12, 14.43it/s]

Preprocessing:  36%|███▋      | 3080/8455 [02:52<05:58, 15.00it/s]

Preprocessing:  36%|███▋      | 3082/8455 [02:52<05:49, 15.36it/s]

Preprocessing:  36%|███▋      | 3084/8455 [02:52<05:46, 15.48it/s]

Preprocessing:  36%|███▋      | 3086/8455 [02:52<05:51, 15.28it/s]

Preprocessing:  37%|███▋      | 3088/8455 [02:52<05:44, 15.60it/s]

Preprocessing:  37%|███▋      | 3090/8455 [02:53<05:56, 15.07it/s]

Preprocessing:  37%|███▋      | 3092/8455 [02:53<05:53, 15.18it/s]

Preprocessing:  37%|███▋      | 3094/8455 [02:53<05:48, 15.39it/s]

Preprocessing:  37%|███▋      | 3096/8455 [02:53<05:50, 15.28it/s]

Preprocessing:  37%|███▋      | 3098/8455 [02:53<05:44, 15.55it/s]

Preprocessing:  37%|███▋      | 3100/8455 [02:53<05:40, 15.70it/s]

Preprocessing:  37%|███▋      | 3102/8455 [02:53<05:52, 15.18it/s]

Preprocessing:  37%|███▋      | 3104/8455 [02:53<05:49, 15.31it/s]

Preprocessing:  37%|███▋      | 3106/8455 [02:54<05:58, 14.93it/s]

Preprocessing:  37%|███▋      | 3108/8455 [02:54<05:50, 15.27it/s]

Preprocessing:  37%|███▋      | 3110/8455 [02:54<05:43, 15.56it/s]

Preprocessing:  37%|███▋      | 3112/8455 [02:54<06:10, 14.42it/s]

Preprocessing:  37%|███▋      | 3114/8455 [02:54<05:57, 14.93it/s]

Preprocessing:  37%|███▋      | 3116/8455 [02:54<05:47, 15.39it/s]

Preprocessing:  37%|███▋      | 3118/8455 [02:54<05:48, 15.30it/s]

Preprocessing:  37%|███▋      | 3120/8455 [02:55<05:56, 14.96it/s]

Preprocessing:  37%|███▋      | 3122/8455 [02:55<05:50, 15.21it/s]

Preprocessing:  37%|███▋      | 3124/8455 [02:55<05:44, 15.47it/s]

Preprocessing:  37%|███▋      | 3126/8455 [02:55<05:53, 15.08it/s]

Preprocessing:  37%|███▋      | 3128/8455 [02:55<05:58, 14.85it/s]

Preprocessing:  37%|███▋      | 3130/8455 [02:55<05:52, 15.09it/s]

Preprocessing:  37%|███▋      | 3132/8455 [02:55<06:05, 14.58it/s]

Preprocessing:  37%|███▋      | 3134/8455 [02:55<05:55, 14.96it/s]

Preprocessing:  37%|███▋      | 3136/8455 [02:56<05:55, 14.95it/s]

Preprocessing:  37%|███▋      | 3138/8455 [02:56<05:48, 15.27it/s]

Preprocessing:  37%|███▋      | 3140/8455 [02:56<05:42, 15.53it/s]

Preprocessing:  37%|███▋      | 3142/8455 [02:56<05:37, 15.74it/s]

Preprocessing:  37%|███▋      | 3144/8455 [02:56<05:33, 15.92it/s]

Preprocessing:  37%|███▋      | 3146/8455 [02:56<05:41, 15.56it/s]

Preprocessing:  37%|███▋      | 3148/8455 [02:56<05:42, 15.50it/s]

Preprocessing:  37%|███▋      | 3150/8455 [02:57<05:56, 14.86it/s]

Preprocessing:  37%|███▋      | 3152/8455 [02:57<06:38, 13.32it/s]

Preprocessing:  37%|███▋      | 3154/8455 [02:57<06:50, 12.92it/s]

Preprocessing:  37%|███▋      | 3156/8455 [02:57<06:23, 13.82it/s]

Preprocessing:  37%|███▋      | 3158/8455 [02:57<06:07, 14.43it/s]

Preprocessing:  37%|███▋      | 3160/8455 [02:57<05:57, 14.81it/s]

Preprocessing:  37%|███▋      | 3162/8455 [02:57<05:55, 14.90it/s]

Preprocessing:  37%|███▋      | 3164/8455 [02:57<05:45, 15.32it/s]

Preprocessing:  37%|███▋      | 3166/8455 [02:58<05:49, 15.14it/s]

Preprocessing:  37%|███▋      | 3168/8455 [02:58<05:59, 14.72it/s]

Preprocessing:  37%|███▋      | 3170/8455 [02:58<06:02, 14.58it/s]

Preprocessing:  38%|███▊      | 3172/8455 [02:58<06:06, 14.43it/s]

Preprocessing:  38%|███▊      | 3174/8455 [02:58<06:01, 14.63it/s]

Preprocessing:  38%|███▊      | 3176/8455 [02:58<06:02, 14.58it/s]

Preprocessing:  38%|███▊      | 3178/8455 [02:58<05:56, 14.81it/s]

Preprocessing:  38%|███▊      | 3180/8455 [02:59<05:54, 14.87it/s]

Preprocessing:  38%|███▊      | 3182/8455 [02:59<06:22, 13.79it/s]

Preprocessing:  38%|███▊      | 3184/8455 [02:59<06:20, 13.84it/s]

Preprocessing:  38%|███▊      | 3186/8455 [02:59<06:35, 13.32it/s]

Preprocessing:  38%|███▊      | 3188/8455 [02:59<06:29, 13.53it/s]

Preprocessing:  38%|███▊      | 3190/8455 [02:59<06:35, 13.31it/s]

Preprocessing:  38%|███▊      | 3192/8455 [03:00<06:49, 12.85it/s]

Preprocessing:  38%|███▊      | 3194/8455 [03:00<06:22, 13.76it/s]

Preprocessing:  38%|███▊      | 3196/8455 [03:00<06:05, 14.39it/s]

Preprocessing:  38%|███▊      | 3198/8455 [03:00<05:55, 14.79it/s]

Preprocessing:  38%|███▊      | 3200/8455 [03:00<05:47, 15.11it/s]

Preprocessing:  38%|███▊      | 3202/8455 [03:00<05:41, 15.38it/s]

Preprocessing:  38%|███▊      | 3204/8455 [03:00<05:39, 15.48it/s]

Preprocessing:  38%|███▊      | 3206/8455 [03:00<05:37, 15.53it/s]

Preprocessing:  38%|███▊      | 3208/8455 [03:01<05:38, 15.52it/s]

Preprocessing:  38%|███▊      | 3210/8455 [03:01<05:53, 14.85it/s]

Preprocessing:  38%|███▊      | 3212/8455 [03:01<05:47, 15.08it/s]

Preprocessing:  38%|███▊      | 3214/8455 [03:01<05:43, 15.26it/s]

Preprocessing:  38%|███▊      | 3216/8455 [03:01<05:59, 14.57it/s]

Preprocessing:  38%|███▊      | 3218/8455 [03:01<05:50, 14.94it/s]

Preprocessing:  38%|███▊      | 3220/8455 [03:01<05:44, 15.21it/s]

Preprocessing:  38%|███▊      | 3222/8455 [03:01<05:52, 14.85it/s]

Preprocessing:  38%|███▊      | 3224/8455 [03:02<05:43, 15.24it/s]

Preprocessing:  38%|███▊      | 3226/8455 [03:02<05:38, 15.47it/s]

Preprocessing:  38%|███▊      | 3228/8455 [03:02<05:33, 15.66it/s]

Preprocessing:  38%|███▊      | 3230/8455 [03:02<05:51, 14.87it/s]

Preprocessing:  38%|███▊      | 3232/8455 [03:02<05:49, 14.93it/s]

Preprocessing:  38%|███▊      | 3234/8455 [03:02<05:47, 15.03it/s]

Preprocessing:  38%|███▊      | 3236/8455 [03:02<05:48, 14.99it/s]

Preprocessing:  38%|███▊      | 3238/8455 [03:03<05:59, 14.50it/s]

Preprocessing:  38%|███▊      | 3240/8455 [03:03<06:07, 14.19it/s]

Preprocessing:  38%|███▊      | 3242/8455 [03:03<05:55, 14.65it/s]

Preprocessing:  38%|███▊      | 3244/8455 [03:03<06:19, 13.74it/s]

Preprocessing:  38%|███▊      | 3246/8455 [03:03<06:24, 13.54it/s]

Preprocessing:  38%|███▊      | 3248/8455 [03:03<06:19, 13.74it/s]

Preprocessing:  38%|███▊      | 3250/8455 [03:03<06:02, 14.37it/s]

Preprocessing:  38%|███▊      | 3252/8455 [03:04<05:51, 14.79it/s]

Preprocessing:  38%|███▊      | 3254/8455 [03:04<05:45, 15.06it/s]

Preprocessing:  39%|███▊      | 3256/8455 [03:04<05:40, 15.29it/s]

Preprocessing:  39%|███▊      | 3258/8455 [03:04<05:42, 15.18it/s]

Preprocessing:  39%|███▊      | 3260/8455 [03:04<05:54, 14.65it/s]

Preprocessing:  39%|███▊      | 3262/8455 [03:04<05:45, 15.01it/s]

Preprocessing:  39%|███▊      | 3264/8455 [03:04<05:37, 15.36it/s]

Preprocessing:  39%|███▊      | 3266/8455 [03:04<05:35, 15.47it/s]

Preprocessing:  39%|███▊      | 3268/8455 [03:05<05:43, 15.12it/s]

Preprocessing:  39%|███▊      | 3270/8455 [03:05<05:49, 14.83it/s]

Preprocessing:  39%|███▊      | 3272/8455 [03:05<05:48, 14.86it/s]

Preprocessing:  39%|███▊      | 3274/8455 [03:05<05:41, 15.15it/s]

Preprocessing:  39%|███▊      | 3276/8455 [03:05<05:34, 15.49it/s]

Preprocessing:  39%|███▉      | 3278/8455 [03:05<05:26, 15.85it/s]

Preprocessing:  39%|███▉      | 3280/8455 [03:05<05:30, 15.68it/s]

Preprocessing:  39%|███▉      | 3282/8455 [03:05<05:23, 15.99it/s]

Preprocessing:  39%|███▉      | 3284/8455 [03:06<05:21, 16.07it/s]

Preprocessing:  39%|███▉      | 3286/8455 [03:06<05:22, 16.04it/s]

Preprocessing:  39%|███▉      | 3288/8455 [03:06<05:26, 15.81it/s]

Preprocessing:  39%|███▉      | 3290/8455 [03:06<05:36, 15.37it/s]

Preprocessing:  39%|███▉      | 3292/8455 [03:06<05:45, 14.95it/s]

Preprocessing:  39%|███▉      | 3294/8455 [03:06<05:38, 15.23it/s]

Preprocessing:  39%|███▉      | 3296/8455 [03:06<05:33, 15.47it/s]

Preprocessing:  39%|███▉      | 3298/8455 [03:07<05:35, 15.36it/s]

Preprocessing:  39%|███▉      | 3300/8455 [03:07<05:31, 15.57it/s]

Preprocessing:  39%|███▉      | 3302/8455 [03:07<05:32, 15.48it/s]

Preprocessing:  39%|███▉      | 3304/8455 [03:07<05:38, 15.21it/s]

Preprocessing:  39%|███▉      | 3306/8455 [03:07<05:55, 14.48it/s]

Preprocessing:  39%|███▉      | 3308/8455 [03:07<05:50, 14.68it/s]

Preprocessing:  39%|███▉      | 3310/8455 [03:07<05:44, 14.95it/s]

Preprocessing:  39%|███▉      | 3312/8455 [03:07<05:39, 15.16it/s]

Preprocessing:  39%|███▉      | 3314/8455 [03:08<05:38, 15.20it/s]

Preprocessing:  39%|███▉      | 3316/8455 [03:08<05:38, 15.17it/s]

Preprocessing:  39%|███▉      | 3318/8455 [03:08<05:36, 15.28it/s]

Preprocessing:  39%|███▉      | 3320/8455 [03:08<05:30, 15.53it/s]

Preprocessing:  39%|███▉      | 3322/8455 [03:08<05:26, 15.74it/s]

Preprocessing:  39%|███▉      | 3324/8455 [03:08<05:29, 15.58it/s]

Preprocessing:  39%|███▉      | 3326/8455 [03:08<05:46, 14.81it/s]

Preprocessing:  39%|███▉      | 3328/8455 [03:09<06:02, 14.15it/s]

Preprocessing:  39%|███▉      | 3330/8455 [03:09<05:48, 14.70it/s]

Preprocessing:  39%|███▉      | 3332/8455 [03:09<05:52, 14.51it/s]

Preprocessing:  39%|███▉      | 3334/8455 [03:09<05:54, 14.43it/s]

Preprocessing:  39%|███▉      | 3336/8455 [03:09<05:46, 14.75it/s]

Preprocessing:  39%|███▉      | 3338/8455 [03:09<05:39, 15.09it/s]

Preprocessing:  40%|███▉      | 3340/8455 [03:09<05:38, 15.13it/s]

Preprocessing:  40%|███▉      | 3342/8455 [03:09<05:34, 15.31it/s]

Preprocessing:  40%|███▉      | 3344/8455 [03:10<05:30, 15.47it/s]

Preprocessing:  40%|███▉      | 3346/8455 [03:10<05:37, 15.15it/s]

Preprocessing:  40%|███▉      | 3348/8455 [03:10<05:31, 15.42it/s]

Preprocessing:  40%|███▉      | 3350/8455 [03:10<05:26, 15.61it/s]

Preprocessing:  40%|███▉      | 3352/8455 [03:10<05:28, 15.52it/s]

Preprocessing:  40%|███▉      | 3354/8455 [03:10<06:03, 14.03it/s]

Preprocessing:  40%|███▉      | 3356/8455 [03:10<05:50, 14.56it/s]

Preprocessing:  40%|███▉      | 3358/8455 [03:11<05:47, 14.67it/s]

Preprocessing:  40%|███▉      | 3360/8455 [03:11<05:39, 15.00it/s]

Preprocessing:  40%|███▉      | 3362/8455 [03:11<05:31, 15.36it/s]

Preprocessing:  40%|███▉      | 3364/8455 [03:11<05:42, 14.86it/s]

Preprocessing:  40%|███▉      | 3366/8455 [03:11<05:58, 14.18it/s]

Preprocessing:  40%|███▉      | 3368/8455 [03:11<06:12, 13.67it/s]

Preprocessing:  40%|███▉      | 3370/8455 [03:11<06:22, 13.31it/s]

Preprocessing:  40%|███▉      | 3372/8455 [03:12<06:19, 13.41it/s]

Preprocessing:  40%|███▉      | 3374/8455 [03:12<06:01, 14.06it/s]

Preprocessing:  40%|███▉      | 3376/8455 [03:12<06:05, 13.90it/s]

Preprocessing:  40%|███▉      | 3378/8455 [03:12<06:37, 12.78it/s]

Preprocessing:  40%|███▉      | 3380/8455 [03:12<06:56, 12.20it/s]

Preprocessing:  40%|████      | 3382/8455 [03:12<06:50, 12.37it/s]

Preprocessing:  40%|████      | 3384/8455 [03:12<06:28, 13.06it/s]

Preprocessing:  40%|████      | 3386/8455 [03:13<06:19, 13.36it/s]

Preprocessing:  40%|████      | 3388/8455 [03:13<06:09, 13.70it/s]

Preprocessing:  40%|████      | 3390/8455 [03:13<06:05, 13.86it/s]

Preprocessing:  40%|████      | 3392/8455 [03:13<06:11, 13.64it/s]

Preprocessing:  40%|████      | 3394/8455 [03:13<06:17, 13.39it/s]

Preprocessing:  40%|████      | 3396/8455 [03:13<06:07, 13.76it/s]

Preprocessing:  40%|████      | 3398/8455 [03:13<06:10, 13.66it/s]

Preprocessing:  40%|████      | 3400/8455 [03:14<06:08, 13.71it/s]

Preprocessing:  40%|████      | 3402/8455 [03:14<06:19, 13.33it/s]

Preprocessing:  40%|████      | 3404/8455 [03:14<06:18, 13.33it/s]

Preprocessing:  40%|████      | 3406/8455 [03:14<06:17, 13.38it/s]

Preprocessing:  40%|████      | 3408/8455 [03:14<06:09, 13.65it/s]

Preprocessing:  40%|████      | 3410/8455 [03:14<05:59, 14.05it/s]

Preprocessing:  40%|████      | 3412/8455 [03:15<05:53, 14.26it/s]

Preprocessing:  40%|████      | 3414/8455 [03:15<05:59, 14.01it/s]

Preprocessing:  40%|████      | 3416/8455 [03:15<05:54, 14.20it/s]

Preprocessing:  40%|████      | 3418/8455 [03:15<05:56, 14.11it/s]

Preprocessing:  40%|████      | 3420/8455 [03:15<06:02, 13.88it/s]

Preprocessing:  40%|████      | 3422/8455 [03:15<05:59, 14.01it/s]

Preprocessing:  40%|████      | 3424/8455 [03:15<05:57, 14.07it/s]

Preprocessing:  41%|████      | 3426/8455 [03:16<05:58, 14.04it/s]

Preprocessing:  41%|████      | 3428/8455 [03:16<06:17, 13.32it/s]

Preprocessing:  41%|████      | 3430/8455 [03:16<06:19, 13.22it/s]

Preprocessing:  41%|████      | 3432/8455 [03:16<06:16, 13.34it/s]

Preprocessing:  41%|████      | 3434/8455 [03:16<06:13, 13.43it/s]

Preprocessing:  41%|████      | 3436/8455 [03:16<06:13, 13.43it/s]

Preprocessing:  41%|████      | 3438/8455 [03:16<06:15, 13.35it/s]

Preprocessing:  41%|████      | 3440/8455 [03:17<06:21, 13.13it/s]

Preprocessing:  41%|████      | 3442/8455 [03:17<06:37, 12.61it/s]

Preprocessing:  41%|████      | 3444/8455 [03:17<06:42, 12.45it/s]

Preprocessing:  41%|████      | 3446/8455 [03:17<06:51, 12.17it/s]

Preprocessing:  41%|████      | 3448/8455 [03:17<06:57, 12.00it/s]

Preprocessing:  41%|████      | 3450/8455 [03:17<06:55, 12.06it/s]

Preprocessing:  41%|████      | 3452/8455 [03:18<06:46, 12.31it/s]

Preprocessing:  41%|████      | 3454/8455 [03:18<06:36, 12.62it/s]

Preprocessing:  41%|████      | 3456/8455 [03:18<06:36, 12.62it/s]

Preprocessing:  41%|████      | 3458/8455 [03:18<06:37, 12.56it/s]

Preprocessing:  41%|████      | 3460/8455 [03:18<06:58, 11.94it/s]

Preprocessing:  41%|████      | 3462/8455 [03:18<07:05, 11.72it/s]

Preprocessing:  41%|████      | 3464/8455 [03:19<06:57, 11.97it/s]

Preprocessing:  41%|████      | 3466/8455 [03:19<06:48, 12.22it/s]

Preprocessing:  41%|████      | 3468/8455 [03:19<06:43, 12.37it/s]

Preprocessing:  41%|████      | 3470/8455 [03:19<06:48, 12.20it/s]

Preprocessing:  41%|████      | 3472/8455 [03:19<06:36, 12.57it/s]

Preprocessing:  41%|████      | 3474/8455 [03:19<06:42, 12.38it/s]

Preprocessing:  41%|████      | 3476/8455 [03:20<06:23, 12.99it/s]

Preprocessing:  41%|████      | 3478/8455 [03:20<06:02, 13.73it/s]

Preprocessing:  41%|████      | 3480/8455 [03:20<05:46, 14.38it/s]

Preprocessing:  41%|████      | 3482/8455 [03:20<06:10, 13.42it/s]

Preprocessing:  41%|████      | 3484/8455 [03:20<05:53, 14.04it/s]

Preprocessing:  41%|████      | 3486/8455 [03:20<05:41, 14.57it/s]

Preprocessing:  41%|████▏     | 3488/8455 [03:20<05:36, 14.75it/s]

Preprocessing:  41%|████▏     | 3490/8455 [03:20<05:28, 15.12it/s]

Preprocessing:  41%|████▏     | 3492/8455 [03:21<05:24, 15.30it/s]

Preprocessing:  41%|████▏     | 3494/8455 [03:21<05:24, 15.29it/s]

Preprocessing:  41%|████▏     | 3496/8455 [03:21<05:24, 15.29it/s]

Preprocessing:  41%|████▏     | 3498/8455 [03:21<05:28, 15.11it/s]

Preprocessing:  41%|████▏     | 3500/8455 [03:21<05:20, 15.46it/s]

Preprocessing:  41%|████▏     | 3502/8455 [03:21<05:14, 15.72it/s]

Preprocessing:  41%|████▏     | 3504/8455 [03:21<05:14, 15.72it/s]

Preprocessing:  41%|████▏     | 3506/8455 [03:21<05:14, 15.74it/s]

Preprocessing:  41%|████▏     | 3508/8455 [03:22<05:27, 15.12it/s]

Preprocessing:  42%|████▏     | 3510/8455 [03:22<05:24, 15.26it/s]

Preprocessing:  42%|████▏     | 3512/8455 [03:22<05:24, 15.21it/s]

Preprocessing:  42%|████▏     | 3514/8455 [03:22<05:21, 15.39it/s]

Preprocessing:  42%|████▏     | 3516/8455 [03:22<05:45, 14.31it/s]

Preprocessing:  42%|████▏     | 3518/8455 [03:22<05:50, 14.08it/s]

Preprocessing:  42%|████▏     | 3520/8455 [03:22<05:38, 14.59it/s]

Preprocessing:  42%|████▏     | 3522/8455 [03:23<05:39, 14.52it/s]

Preprocessing:  42%|████▏     | 3524/8455 [03:23<05:43, 14.36it/s]

Preprocessing:  42%|████▏     | 3526/8455 [03:23<05:29, 14.94it/s]

Preprocessing:  42%|████▏     | 3528/8455 [03:23<05:23, 15.21it/s]

Preprocessing:  42%|████▏     | 3530/8455 [03:23<05:17, 15.50it/s]

Preprocessing:  42%|████▏     | 3532/8455 [03:23<05:20, 15.35it/s]

Preprocessing:  42%|████▏     | 3534/8455 [03:23<05:41, 14.43it/s]

Preprocessing:  42%|████▏     | 3536/8455 [03:24<06:07, 13.39it/s]

Preprocessing:  42%|████▏     | 3538/8455 [03:24<06:01, 13.61it/s]

Preprocessing:  42%|████▏     | 3540/8455 [03:24<05:46, 14.17it/s]

Preprocessing:  42%|████▏     | 3542/8455 [03:24<05:47, 14.13it/s]

Preprocessing:  42%|████▏     | 3544/8455 [03:24<05:35, 14.63it/s]

Preprocessing:  42%|████▏     | 3546/8455 [03:24<05:44, 14.26it/s]

Preprocessing:  42%|████▏     | 3548/8455 [03:24<05:52, 13.91it/s]

Preprocessing:  42%|████▏     | 3550/8455 [03:25<06:17, 12.99it/s]

Preprocessing:  42%|████▏     | 3552/8455 [03:25<06:30, 12.56it/s]

Preprocessing:  42%|████▏     | 3554/8455 [03:25<06:36, 12.35it/s]

Preprocessing:  42%|████▏     | 3556/8455 [03:25<06:39, 12.25it/s]

Preprocessing:  42%|████▏     | 3558/8455 [03:25<06:39, 12.26it/s]

Preprocessing:  42%|████▏     | 3560/8455 [03:25<06:49, 11.97it/s]

Preprocessing:  42%|████▏     | 3562/8455 [03:26<07:00, 11.63it/s]

Preprocessing:  42%|████▏     | 3564/8455 [03:26<07:03, 11.56it/s]

Preprocessing:  42%|████▏     | 3566/8455 [03:26<07:02, 11.57it/s]

Preprocessing:  42%|████▏     | 3568/8455 [03:26<07:03, 11.55it/s]

Preprocessing:  42%|████▏     | 3570/8455 [03:26<07:16, 11.19it/s]

Preprocessing:  42%|████▏     | 3572/8455 [03:26<07:16, 11.18it/s]

Preprocessing:  42%|████▏     | 3574/8455 [03:27<07:16, 11.18it/s]

Preprocessing:  42%|████▏     | 3576/8455 [03:27<07:27, 10.91it/s]

Preprocessing:  42%|████▏     | 3578/8455 [03:27<07:13, 11.25it/s]

Preprocessing:  42%|████▏     | 3580/8455 [03:27<06:38, 12.24it/s]

Preprocessing:  42%|████▏     | 3582/8455 [03:27<06:17, 12.89it/s]

Preprocessing:  42%|████▏     | 3584/8455 [03:27<06:04, 13.35it/s]

Preprocessing:  42%|████▏     | 3586/8455 [03:28<05:49, 13.92it/s]

Preprocessing:  42%|████▏     | 3588/8455 [03:28<05:48, 13.95it/s]

Preprocessing:  42%|████▏     | 3590/8455 [03:28<05:48, 13.98it/s]

Preprocessing:  42%|████▏     | 3592/8455 [03:28<05:38, 14.36it/s]

Preprocessing:  43%|████▎     | 3594/8455 [03:28<05:31, 14.67it/s]

Preprocessing:  43%|████▎     | 3596/8455 [03:28<05:27, 14.85it/s]

Preprocessing:  43%|████▎     | 3598/8455 [03:28<05:24, 14.96it/s]

Preprocessing:  43%|████▎     | 3600/8455 [03:28<05:24, 14.97it/s]

Preprocessing:  43%|████▎     | 3602/8455 [03:29<05:32, 14.62it/s]

Preprocessing:  43%|████▎     | 3604/8455 [03:29<05:25, 14.90it/s]

Preprocessing:  43%|████▎     | 3606/8455 [03:29<05:32, 14.60it/s]

Preprocessing:  43%|████▎     | 3608/8455 [03:29<05:33, 14.53it/s]

Preprocessing:  43%|████▎     | 3610/8455 [03:29<05:29, 14.70it/s]

Preprocessing:  43%|████▎     | 3612/8455 [03:29<05:32, 14.58it/s]

Preprocessing:  43%|████▎     | 3614/8455 [03:29<05:35, 14.42it/s]

Preprocessing:  43%|████▎     | 3616/8455 [03:30<05:30, 14.62it/s]

Preprocessing:  43%|████▎     | 3618/8455 [03:30<05:45, 13.98it/s]

Preprocessing:  43%|████▎     | 3620/8455 [03:30<05:45, 13.98it/s]

Preprocessing:  43%|████▎     | 3622/8455 [03:30<05:34, 14.44it/s]

Preprocessing:  43%|████▎     | 3624/8455 [03:30<05:26, 14.79it/s]

Preprocessing:  43%|████▎     | 3626/8455 [03:30<05:43, 14.05it/s]

Preprocessing:  43%|████▎     | 3628/8455 [03:30<05:37, 14.32it/s]

Preprocessing:  43%|████▎     | 3630/8455 [03:31<05:29, 14.66it/s]

Preprocessing:  43%|████▎     | 3632/8455 [03:31<05:28, 14.67it/s]

Preprocessing:  43%|████▎     | 3634/8455 [03:31<05:44, 13.98it/s]

Preprocessing:  43%|████▎     | 3636/8455 [03:31<05:40, 14.17it/s]

Preprocessing:  43%|████▎     | 3638/8455 [03:31<05:38, 14.24it/s]

Preprocessing:  43%|████▎     | 3640/8455 [03:31<05:30, 14.55it/s]

Preprocessing:  43%|████▎     | 3642/8455 [03:31<05:35, 14.33it/s]

Preprocessing:  43%|████▎     | 3644/8455 [03:32<05:48, 13.82it/s]

Preprocessing:  43%|████▎     | 3646/8455 [03:32<05:59, 13.39it/s]

Preprocessing:  43%|████▎     | 3648/8455 [03:32<05:41, 14.07it/s]

Preprocessing:  43%|████▎     | 3650/8455 [03:32<05:29, 14.60it/s]

Preprocessing:  43%|████▎     | 3652/8455 [03:32<05:25, 14.77it/s]

Preprocessing:  43%|████▎     | 3654/8455 [03:32<05:34, 14.37it/s]

Preprocessing:  43%|████▎     | 3656/8455 [03:32<05:26, 14.72it/s]

Preprocessing:  43%|████▎     | 3658/8455 [03:33<05:27, 14.65it/s]

Preprocessing:  43%|████▎     | 3660/8455 [03:33<05:30, 14.49it/s]

Preprocessing:  43%|████▎     | 3662/8455 [03:33<05:35, 14.29it/s]

Preprocessing:  43%|████▎     | 3664/8455 [03:33<05:49, 13.71it/s]

Preprocessing:  43%|████▎     | 3666/8455 [03:33<05:46, 13.81it/s]

Preprocessing:  43%|████▎     | 3668/8455 [03:33<05:48, 13.72it/s]

Preprocessing:  43%|████▎     | 3670/8455 [03:33<05:59, 13.32it/s]

Preprocessing:  43%|████▎     | 3672/8455 [03:34<05:55, 13.45it/s]

Preprocessing:  43%|████▎     | 3674/8455 [03:34<05:44, 13.87it/s]

Preprocessing:  43%|████▎     | 3676/8455 [03:34<05:47, 13.77it/s]

Preprocessing:  44%|████▎     | 3678/8455 [03:34<05:43, 13.90it/s]

Preprocessing:  44%|████▎     | 3680/8455 [03:34<05:37, 14.13it/s]

Preprocessing:  44%|████▎     | 3682/8455 [03:34<05:31, 14.39it/s]

Preprocessing:  44%|████▎     | 3684/8455 [03:34<05:52, 13.52it/s]

Preprocessing:  44%|████▎     | 3686/8455 [03:35<05:50, 13.59it/s]

Preprocessing:  44%|████▎     | 3688/8455 [03:35<05:49, 13.66it/s]

Preprocessing:  44%|████▎     | 3690/8455 [03:35<05:49, 13.65it/s]

Preprocessing:  44%|████▎     | 3692/8455 [03:35<05:37, 14.13it/s]

Preprocessing:  44%|████▎     | 3694/8455 [03:35<05:46, 13.74it/s]

Preprocessing:  44%|████▎     | 3696/8455 [03:35<05:54, 13.42it/s]

Preprocessing:  44%|████▎     | 3698/8455 [03:35<05:59, 13.23it/s]

Preprocessing:  44%|████▍     | 3700/8455 [03:36<06:08, 12.91it/s]

Preprocessing:  44%|████▍     | 3702/8455 [03:36<05:53, 13.43it/s]

Preprocessing:  44%|████▍     | 3704/8455 [03:36<05:46, 13.73it/s]

Preprocessing:  44%|████▍     | 3706/8455 [03:36<05:47, 13.68it/s]

Preprocessing:  44%|████▍     | 3708/8455 [03:36<05:52, 13.46it/s]

Preprocessing:  44%|████▍     | 3710/8455 [03:36<05:50, 13.56it/s]

Preprocessing:  44%|████▍     | 3712/8455 [03:36<05:38, 14.00it/s]

Preprocessing:  44%|████▍     | 3714/8455 [03:37<05:33, 14.20it/s]

Preprocessing:  44%|████▍     | 3716/8455 [03:37<05:40, 13.90it/s]

Preprocessing:  44%|████▍     | 3718/8455 [03:37<05:40, 13.92it/s]

Preprocessing:  44%|████▍     | 3720/8455 [03:37<05:29, 14.39it/s]

Preprocessing:  44%|████▍     | 3722/8455 [03:37<05:34, 14.17it/s]

Preprocessing:  44%|████▍     | 3724/8455 [03:37<05:48, 13.56it/s]

Preprocessing:  44%|████▍     | 3726/8455 [03:37<05:46, 13.64it/s]

Preprocessing:  44%|████▍     | 3728/8455 [03:38<05:45, 13.69it/s]

Preprocessing:  44%|████▍     | 3730/8455 [03:38<05:44, 13.70it/s]

Preprocessing:  44%|████▍     | 3732/8455 [03:38<05:37, 14.00it/s]

Preprocessing:  44%|████▍     | 3734/8455 [03:38<05:49, 13.52it/s]

Preprocessing:  44%|████▍     | 3736/8455 [03:38<05:37, 13.98it/s]

Preprocessing:  44%|████▍     | 3738/8455 [03:38<05:27, 14.41it/s]

Preprocessing:  44%|████▍     | 3740/8455 [03:38<05:37, 13.98it/s]

Preprocessing:  44%|████▍     | 3742/8455 [03:39<05:37, 13.97it/s]

Preprocessing:  44%|████▍     | 3744/8455 [03:39<05:44, 13.66it/s]

Preprocessing:  44%|████▍     | 3746/8455 [03:39<05:35, 14.02it/s]

Preprocessing:  44%|████▍     | 3748/8455 [03:39<05:45, 13.63it/s]

Preprocessing:  44%|████▍     | 3750/8455 [03:39<05:35, 14.01it/s]

Preprocessing:  44%|████▍     | 3752/8455 [03:39<05:35, 14.03it/s]

Preprocessing:  44%|████▍     | 3754/8455 [03:40<05:40, 13.79it/s]

Preprocessing:  44%|████▍     | 3756/8455 [03:40<05:32, 14.15it/s]

Preprocessing:  44%|████▍     | 3758/8455 [03:40<05:40, 13.81it/s]

Preprocessing:  44%|████▍     | 3760/8455 [03:40<06:23, 12.25it/s]

Preprocessing:  44%|████▍     | 3762/8455 [03:40<06:04, 12.87it/s]

Preprocessing:  45%|████▍     | 3764/8455 [03:40<06:07, 12.76it/s]

Preprocessing:  45%|████▍     | 3766/8455 [03:40<06:02, 12.93it/s]

Preprocessing:  45%|████▍     | 3768/8455 [03:41<05:42, 13.69it/s]

Preprocessing:  45%|████▍     | 3770/8455 [03:41<05:35, 13.97it/s]

Preprocessing:  45%|████▍     | 3772/8455 [03:41<05:41, 13.71it/s]

Preprocessing:  45%|████▍     | 3774/8455 [03:41<05:27, 14.29it/s]

Preprocessing:  45%|████▍     | 3776/8455 [03:41<05:37, 13.86it/s]

Preprocessing:  45%|████▍     | 3778/8455 [03:41<05:33, 14.04it/s]

Preprocessing:  45%|████▍     | 3780/8455 [03:41<05:31, 14.11it/s]

Preprocessing:  45%|████▍     | 3782/8455 [03:42<05:31, 14.09it/s]

Preprocessing:  45%|████▍     | 3784/8455 [03:42<05:17, 14.72it/s]

Preprocessing:  45%|████▍     | 3786/8455 [03:42<05:23, 14.43it/s]

Preprocessing:  45%|████▍     | 3788/8455 [03:42<05:20, 14.58it/s]

Preprocessing:  45%|████▍     | 3790/8455 [03:42<05:23, 14.41it/s]

Preprocessing:  45%|████▍     | 3792/8455 [03:42<05:16, 14.72it/s]

Preprocessing:  45%|████▍     | 3794/8455 [03:42<05:21, 14.50it/s]

Preprocessing:  45%|████▍     | 3796/8455 [03:43<05:24, 14.37it/s]

Preprocessing:  45%|████▍     | 3798/8455 [03:43<05:29, 14.15it/s]

Preprocessing:  45%|████▍     | 3800/8455 [03:43<05:32, 14.00it/s]

Preprocessing:  45%|████▍     | 3802/8455 [03:43<05:32, 14.00it/s]

Preprocessing:  45%|████▍     | 3804/8455 [03:43<05:39, 13.71it/s]

Preprocessing:  45%|████▌     | 3806/8455 [03:43<05:39, 13.69it/s]

Preprocessing:  45%|████▌     | 3808/8455 [03:43<05:51, 13.21it/s]

Preprocessing:  45%|████▌     | 3810/8455 [03:44<05:48, 13.32it/s]

Preprocessing:  45%|████▌     | 3812/8455 [03:44<05:43, 13.52it/s]

Preprocessing:  45%|████▌     | 3814/8455 [03:44<05:35, 13.81it/s]

Preprocessing:  45%|████▌     | 3816/8455 [03:44<05:22, 14.39it/s]

Preprocessing:  45%|████▌     | 3818/8455 [03:44<05:24, 14.29it/s]

Preprocessing:  45%|████▌     | 3820/8455 [03:44<05:28, 14.10it/s]

Preprocessing:  45%|████▌     | 3822/8455 [03:44<05:31, 13.98it/s]

Preprocessing:  45%|████▌     | 3824/8455 [03:45<05:21, 14.41it/s]

Preprocessing:  45%|████▌     | 3826/8455 [03:45<05:18, 14.53it/s]

Preprocessing:  45%|████▌     | 3828/8455 [03:45<05:24, 14.26it/s]

Preprocessing:  45%|████▌     | 3830/8455 [03:45<05:15, 14.65it/s]

Preprocessing:  45%|████▌     | 3832/8455 [03:45<05:20, 14.44it/s]

Preprocessing:  45%|████▌     | 3834/8455 [03:45<05:24, 14.26it/s]

Preprocessing:  45%|████▌     | 3836/8455 [03:45<05:23, 14.27it/s]

Preprocessing:  45%|████▌     | 3838/8455 [03:46<05:27, 14.10it/s]

Preprocessing:  45%|████▌     | 3840/8455 [03:46<05:16, 14.60it/s]

Preprocessing:  45%|████▌     | 3842/8455 [03:46<05:14, 14.65it/s]

Preprocessing:  45%|████▌     | 3844/8455 [03:46<05:16, 14.56it/s]

Preprocessing:  45%|████▌     | 3846/8455 [03:46<05:47, 13.27it/s]

Preprocessing:  46%|████▌     | 3848/8455 [03:46<05:42, 13.45it/s]

Preprocessing:  46%|████▌     | 3850/8455 [03:46<05:42, 13.44it/s]

Preprocessing:  46%|████▌     | 3852/8455 [03:47<05:46, 13.28it/s]

Preprocessing:  46%|████▌     | 3854/8455 [03:47<05:34, 13.73it/s]

Preprocessing:  46%|████▌     | 3856/8455 [03:47<05:33, 13.81it/s]

Preprocessing:  46%|████▌     | 3858/8455 [03:47<05:21, 14.28it/s]

Preprocessing:  46%|████▌     | 3860/8455 [03:47<05:26, 14.09it/s]

Preprocessing:  46%|████▌     | 3862/8455 [03:47<05:19, 14.35it/s]

Preprocessing:  46%|████▌     | 3864/8455 [03:47<05:09, 14.85it/s]

Preprocessing:  46%|████▌     | 3866/8455 [03:47<05:11, 14.71it/s]

Preprocessing:  46%|████▌     | 3868/8455 [03:48<05:24, 14.15it/s]

Preprocessing:  46%|████▌     | 3870/8455 [03:48<05:30, 13.89it/s]

Preprocessing:  46%|████▌     | 3872/8455 [03:48<05:13, 14.62it/s]

Preprocessing:  46%|████▌     | 3874/8455 [03:48<05:19, 14.33it/s]

Preprocessing:  46%|████▌     | 3876/8455 [03:48<05:30, 13.84it/s]

Preprocessing:  46%|████▌     | 3878/8455 [03:48<05:30, 13.87it/s]

Preprocessing:  46%|████▌     | 3880/8455 [03:49<05:31, 13.79it/s]

Preprocessing:  46%|████▌     | 3882/8455 [03:49<05:26, 14.00it/s]

Preprocessing:  46%|████▌     | 3884/8455 [03:49<05:24, 14.10it/s]

Preprocessing:  46%|████▌     | 3886/8455 [03:49<05:17, 14.39it/s]

Preprocessing:  46%|████▌     | 3888/8455 [03:49<05:32, 13.74it/s]

Preprocessing:  46%|████▌     | 3890/8455 [03:49<05:36, 13.58it/s]

Preprocessing:  46%|████▌     | 3892/8455 [03:49<05:41, 13.35it/s]

Preprocessing:  46%|████▌     | 3894/8455 [03:50<05:37, 13.52it/s]

Preprocessing:  46%|████▌     | 3896/8455 [03:50<05:49, 13.03it/s]

Preprocessing:  46%|████▌     | 3898/8455 [03:50<05:49, 13.03it/s]

Preprocessing:  46%|████▌     | 3900/8455 [03:50<05:51, 12.96it/s]

Preprocessing:  46%|████▌     | 3902/8455 [03:50<05:48, 13.07it/s]

Preprocessing:  46%|████▌     | 3904/8455 [03:50<05:42, 13.27it/s]

Preprocessing:  46%|████▌     | 3906/8455 [03:50<05:54, 12.82it/s]

Preprocessing:  46%|████▌     | 3908/8455 [03:51<05:51, 12.92it/s]

Preprocessing:  46%|████▌     | 3910/8455 [03:51<05:59, 12.63it/s]

Preprocessing:  46%|████▋     | 3912/8455 [03:51<05:51, 12.93it/s]

Preprocessing:  46%|████▋     | 3914/8455 [03:51<05:45, 13.15it/s]

Preprocessing:  46%|████▋     | 3916/8455 [03:51<05:47, 13.06it/s]

Preprocessing:  46%|████▋     | 3918/8455 [03:51<05:45, 13.13it/s]

Preprocessing:  46%|████▋     | 3920/8455 [03:52<05:52, 12.88it/s]

Preprocessing:  46%|████▋     | 3922/8455 [03:52<05:49, 12.99it/s]

Preprocessing:  46%|████▋     | 3924/8455 [03:52<05:33, 13.57it/s]

Preprocessing:  46%|████▋     | 3926/8455 [03:52<05:47, 13.04it/s]

Preprocessing:  46%|████▋     | 3928/8455 [03:52<05:45, 13.10it/s]

Preprocessing:  46%|████▋     | 3930/8455 [03:52<05:42, 13.23it/s]

Preprocessing:  47%|████▋     | 3932/8455 [03:52<05:38, 13.38it/s]

Preprocessing:  47%|████▋     | 3934/8455 [03:53<05:40, 13.28it/s]

Preprocessing:  47%|████▋     | 3936/8455 [03:53<05:28, 13.77it/s]

Preprocessing:  47%|████▋     | 3938/8455 [03:53<05:32, 13.57it/s]

Preprocessing:  47%|████▋     | 3940/8455 [03:53<05:40, 13.25it/s]

Preprocessing:  47%|████▋     | 3942/8455 [03:53<05:42, 13.17it/s]

Preprocessing:  47%|████▋     | 3944/8455 [03:53<05:41, 13.19it/s]

Preprocessing:  47%|████▋     | 3946/8455 [03:54<05:49, 12.92it/s]

Preprocessing:  47%|████▋     | 3948/8455 [03:54<05:42, 13.15it/s]

Preprocessing:  47%|████▋     | 3950/8455 [03:54<05:38, 13.31it/s]

Preprocessing:  47%|████▋     | 3952/8455 [03:54<05:28, 13.70it/s]

Preprocessing:  47%|████▋     | 3954/8455 [03:54<05:27, 13.74it/s]

Preprocessing:  47%|████▋     | 3956/8455 [03:54<05:32, 13.54it/s]

Preprocessing:  47%|████▋     | 3958/8455 [03:54<05:26, 13.78it/s]

Preprocessing:  47%|████▋     | 3960/8455 [03:55<05:34, 13.43it/s]

Preprocessing:  47%|████▋     | 3962/8455 [03:55<05:44, 13.05it/s]

Preprocessing:  47%|████▋     | 3964/8455 [03:55<05:38, 13.28it/s]

Preprocessing:  47%|████▋     | 3966/8455 [03:55<05:47, 12.91it/s]

Preprocessing:  47%|████▋     | 3968/8455 [03:55<05:55, 12.61it/s]

Preprocessing:  47%|████▋     | 3970/8455 [03:55<05:37, 13.28it/s]

Preprocessing:  47%|████▋     | 3972/8455 [03:55<05:22, 13.91it/s]

Preprocessing:  47%|████▋     | 3974/8455 [03:56<05:23, 13.84it/s]

Preprocessing:  47%|████▋     | 3976/8455 [03:56<05:22, 13.88it/s]

Preprocessing:  47%|████▋     | 3978/8455 [03:56<05:14, 14.23it/s]

Preprocessing:  47%|████▋     | 3980/8455 [03:56<05:11, 14.38it/s]

Preprocessing:  47%|████▋     | 3982/8455 [03:56<05:18, 14.06it/s]

Preprocessing:  47%|████▋     | 3984/8455 [03:56<05:11, 14.37it/s]

Preprocessing:  47%|████▋     | 3986/8455 [03:56<05:25, 13.74it/s]

Preprocessing:  47%|████▋     | 3988/8455 [03:57<05:29, 13.55it/s]

Preprocessing:  47%|████▋     | 3990/8455 [03:57<05:28, 13.59it/s]

Preprocessing:  47%|████▋     | 3992/8455 [03:57<05:28, 13.57it/s]

Preprocessing:  47%|████▋     | 3994/8455 [03:57<05:37, 13.22it/s]

Preprocessing:  47%|████▋     | 3996/8455 [03:57<05:44, 12.96it/s]

Preprocessing:  47%|████▋     | 3998/8455 [03:57<05:40, 13.10it/s]

Preprocessing:  47%|████▋     | 4000/8455 [03:58<05:45, 12.91it/s]

Preprocessing:  47%|████▋     | 4002/8455 [03:58<05:53, 12.61it/s]

Preprocessing:  47%|████▋     | 4004/8455 [03:58<05:44, 12.92it/s]

Preprocessing:  47%|████▋     | 4006/8455 [03:58<05:53, 12.58it/s]

Preprocessing:  47%|████▋     | 4008/8455 [03:58<05:45, 12.86it/s]

Preprocessing:  47%|████▋     | 4010/8455 [03:58<05:28, 13.53it/s]

Preprocessing:  47%|████▋     | 4012/8455 [03:58<05:37, 13.18it/s]

Preprocessing:  47%|████▋     | 4014/8455 [03:59<05:38, 13.13it/s]

Preprocessing:  47%|████▋     | 4016/8455 [03:59<05:41, 12.99it/s]

Preprocessing:  48%|████▊     | 4018/8455 [03:59<05:51, 12.62it/s]

Preprocessing:  48%|████▊     | 4020/8455 [03:59<05:52, 12.58it/s]

Preprocessing:  48%|████▊     | 4022/8455 [03:59<05:54, 12.51it/s]

Preprocessing:  48%|████▊     | 4024/8455 [03:59<05:57, 12.40it/s]

Preprocessing:  48%|████▊     | 4026/8455 [04:00<05:45, 12.82it/s]

Preprocessing:  48%|████▊     | 4028/8455 [04:00<05:27, 13.50it/s]

Preprocessing:  48%|████▊     | 4030/8455 [04:00<05:23, 13.69it/s]

Preprocessing:  48%|████▊     | 4032/8455 [04:00<05:27, 13.50it/s]

Preprocessing:  48%|████▊     | 4034/8455 [04:00<05:33, 13.27it/s]

Preprocessing:  48%|████▊     | 4036/8455 [04:00<05:35, 13.17it/s]

Preprocessing:  48%|████▊     | 4038/8455 [04:00<05:39, 12.99it/s]

Preprocessing:  48%|████▊     | 4040/8455 [04:01<05:28, 13.44it/s]

Preprocessing:  48%|████▊     | 4042/8455 [04:01<05:18, 13.86it/s]

Preprocessing:  48%|████▊     | 4044/8455 [04:01<05:27, 13.45it/s]

Preprocessing:  48%|████▊     | 4046/8455 [04:01<05:45, 12.75it/s]

Preprocessing:  48%|████▊     | 4048/8455 [04:01<05:41, 12.90it/s]

Preprocessing:  48%|████▊     | 4050/8455 [04:01<05:44, 12.77it/s]

Preprocessing:  48%|████▊     | 4052/8455 [04:02<05:54, 12.42it/s]

Preprocessing:  48%|████▊     | 4054/8455 [04:02<06:07, 11.99it/s]

Preprocessing:  48%|████▊     | 4056/8455 [04:02<05:44, 12.76it/s]

Preprocessing:  48%|████▊     | 4058/8455 [04:02<05:38, 13.01it/s]

Preprocessing:  48%|████▊     | 4060/8455 [04:02<05:28, 13.37it/s]

Preprocessing:  48%|████▊     | 4062/8455 [04:02<05:19, 13.74it/s]

Preprocessing:  48%|████▊     | 4064/8455 [04:02<05:07, 14.30it/s]

Preprocessing:  48%|████▊     | 4066/8455 [04:03<04:58, 14.71it/s]

Preprocessing:  48%|████▊     | 4068/8455 [04:03<05:07, 14.25it/s]

Preprocessing:  48%|████▊     | 4070/8455 [04:03<05:34, 13.11it/s]

Preprocessing:  48%|████▊     | 4072/8455 [04:03<06:03, 12.05it/s]

Preprocessing:  48%|████▊     | 4074/8455 [04:03<05:51, 12.46it/s]

Preprocessing:  48%|████▊     | 4076/8455 [04:03<05:31, 13.22it/s]

Preprocessing:  48%|████▊     | 4078/8455 [04:03<05:27, 13.35it/s]

Preprocessing:  48%|████▊     | 4080/8455 [04:04<05:23, 13.51it/s]

Preprocessing:  48%|████▊     | 4082/8455 [04:04<05:13, 13.96it/s]

Preprocessing:  48%|████▊     | 4084/8455 [04:04<04:57, 14.67it/s]

Preprocessing:  48%|████▊     | 4086/8455 [04:04<04:47, 15.19it/s]

Preprocessing:  48%|████▊     | 4088/8455 [04:04<04:50, 15.04it/s]

Preprocessing:  48%|████▊     | 4090/8455 [04:04<04:53, 14.89it/s]

Preprocessing:  48%|████▊     | 4092/8455 [04:04<04:52, 14.92it/s]

Preprocessing:  48%|████▊     | 4094/8455 [04:05<05:09, 14.11it/s]

Preprocessing:  48%|████▊     | 4096/8455 [04:05<05:03, 14.36it/s]

Preprocessing:  48%|████▊     | 4098/8455 [04:05<04:57, 14.66it/s]

Preprocessing:  48%|████▊     | 4100/8455 [04:05<04:54, 14.80it/s]

Preprocessing:  49%|████▊     | 4102/8455 [04:05<04:52, 14.90it/s]

Preprocessing:  49%|████▊     | 4104/8455 [04:05<04:57, 14.63it/s]

Preprocessing:  49%|████▊     | 4106/8455 [04:05<05:01, 14.44it/s]

Preprocessing:  49%|████▊     | 4108/8455 [04:06<05:05, 14.22it/s]

Preprocessing:  49%|████▊     | 4110/8455 [04:06<05:13, 13.84it/s]

Preprocessing:  49%|████▊     | 4112/8455 [04:06<05:24, 13.40it/s]

Preprocessing:  49%|████▊     | 4114/8455 [04:06<05:29, 13.16it/s]

Preprocessing:  49%|████▊     | 4116/8455 [04:06<05:35, 12.92it/s]

Preprocessing:  49%|████▊     | 4118/8455 [04:06<05:43, 12.63it/s]

Preprocessing:  49%|████▊     | 4120/8455 [04:06<05:21, 13.47it/s]

Preprocessing:  49%|████▉     | 4122/8455 [04:07<05:17, 13.64it/s]

Preprocessing:  49%|████▉     | 4124/8455 [04:07<05:28, 13.17it/s]

Preprocessing:  49%|████▉     | 4126/8455 [04:07<05:24, 13.33it/s]

Preprocessing:  49%|████▉     | 4128/8455 [04:07<05:27, 13.22it/s]

Preprocessing:  49%|████▉     | 4130/8455 [04:07<05:13, 13.81it/s]

Preprocessing:  49%|████▉     | 4132/8455 [04:07<05:09, 13.95it/s]

Preprocessing:  49%|████▉     | 4134/8455 [04:07<05:20, 13.48it/s]

Preprocessing:  49%|████▉     | 4136/8455 [04:08<05:27, 13.17it/s]

Preprocessing:  49%|████▉     | 4138/8455 [04:08<05:41, 12.62it/s]

Preprocessing:  49%|████▉     | 4140/8455 [04:08<05:25, 13.27it/s]

Preprocessing:  49%|████▉     | 4142/8455 [04:08<05:35, 12.87it/s]

Preprocessing:  49%|████▉     | 4144/8455 [04:08<05:29, 13.08it/s]

Preprocessing:  49%|████▉     | 4146/8455 [04:08<05:24, 13.28it/s]

Preprocessing:  49%|████▉     | 4148/8455 [04:09<05:21, 13.40it/s]

Preprocessing:  49%|████▉     | 4150/8455 [04:09<05:05, 14.09it/s]

Preprocessing:  49%|████▉     | 4152/8455 [04:09<05:08, 13.97it/s]

Preprocessing:  49%|████▉     | 4154/8455 [04:09<05:05, 14.08it/s]

Preprocessing:  49%|████▉     | 4156/8455 [04:09<05:25, 13.20it/s]

Preprocessing:  49%|████▉     | 4158/8455 [04:09<05:22, 13.34it/s]

Preprocessing:  49%|████▉     | 4160/8455 [04:09<05:29, 13.03it/s]

Preprocessing:  49%|████▉     | 4162/8455 [04:10<05:32, 12.92it/s]

Preprocessing:  49%|████▉     | 4164/8455 [04:10<05:35, 12.79it/s]

Preprocessing:  49%|████▉     | 4166/8455 [04:10<05:32, 12.88it/s]

Preprocessing:  49%|████▉     | 4168/8455 [04:10<05:35, 12.77it/s]

Preprocessing:  49%|████▉     | 4170/8455 [04:10<05:17, 13.48it/s]

Preprocessing:  49%|████▉     | 4172/8455 [04:10<05:27, 13.08it/s]

Preprocessing:  49%|████▉     | 4174/8455 [04:10<05:22, 13.26it/s]

Preprocessing:  49%|████▉     | 4176/8455 [04:11<05:24, 13.20it/s]

Preprocessing:  49%|████▉     | 4178/8455 [04:11<05:22, 13.28it/s]

Preprocessing:  49%|████▉     | 4180/8455 [04:11<05:30, 12.93it/s]

Preprocessing:  49%|████▉     | 4182/8455 [04:11<05:37, 12.67it/s]

Preprocessing:  49%|████▉     | 4184/8455 [04:11<05:17, 13.46it/s]

Preprocessing:  50%|████▉     | 4186/8455 [04:11<05:18, 13.42it/s]

Preprocessing:  50%|████▉     | 4188/8455 [04:12<05:24, 13.13it/s]

Preprocessing:  50%|████▉     | 4190/8455 [04:12<05:27, 13.04it/s]

Preprocessing:  50%|████▉     | 4192/8455 [04:12<05:17, 13.41it/s]

Preprocessing:  50%|████▉     | 4194/8455 [04:12<05:27, 13.00it/s]

Preprocessing:  50%|████▉     | 4196/8455 [04:12<05:32, 12.79it/s]

Preprocessing:  50%|████▉     | 4198/8455 [04:12<05:26, 13.05it/s]

Preprocessing:  50%|████▉     | 4200/8455 [04:12<05:31, 12.83it/s]

Preprocessing:  50%|████▉     | 4202/8455 [04:13<05:26, 13.04it/s]

Preprocessing:  50%|████▉     | 4204/8455 [04:13<05:27, 12.96it/s]

Preprocessing:  50%|████▉     | 4206/8455 [04:13<05:22, 13.17it/s]

Preprocessing:  50%|████▉     | 4208/8455 [04:13<05:15, 13.45it/s]

Preprocessing:  50%|████▉     | 4210/8455 [04:13<05:16, 13.40it/s]

Preprocessing:  50%|████▉     | 4212/8455 [04:13<05:17, 13.37it/s]

Preprocessing:  50%|████▉     | 4214/8455 [04:14<05:25, 13.03it/s]

Preprocessing:  50%|████▉     | 4216/8455 [04:14<05:30, 12.84it/s]

Preprocessing:  50%|████▉     | 4218/8455 [04:14<05:16, 13.40it/s]

Preprocessing:  50%|████▉     | 4220/8455 [04:14<04:58, 14.17it/s]

Preprocessing:  50%|████▉     | 4222/8455 [04:14<05:06, 13.82it/s]

Preprocessing:  50%|████▉     | 4224/8455 [04:14<04:53, 14.41it/s]

Preprocessing:  50%|████▉     | 4226/8455 [04:14<05:00, 14.08it/s]

Preprocessing:  50%|█████     | 4228/8455 [04:15<04:54, 14.35it/s]

Preprocessing:  50%|█████     | 4230/8455 [04:15<04:47, 14.72it/s]

Preprocessing:  50%|█████     | 4232/8455 [04:15<05:09, 13.63it/s]

Preprocessing:  50%|█████     | 4234/8455 [04:15<05:15, 13.39it/s]

Preprocessing:  50%|█████     | 4236/8455 [04:15<05:14, 13.43it/s]

Preprocessing:  50%|█████     | 4238/8455 [04:15<05:04, 13.87it/s]

Preprocessing:  50%|█████     | 4240/8455 [04:15<05:02, 13.92it/s]

Preprocessing:  50%|█████     | 4242/8455 [04:16<04:55, 14.26it/s]

Preprocessing:  50%|█████     | 4244/8455 [04:16<04:58, 14.09it/s]

Preprocessing:  50%|█████     | 4246/8455 [04:16<05:10, 13.57it/s]

Preprocessing:  50%|█████     | 4248/8455 [04:16<05:05, 13.79it/s]

Preprocessing:  50%|█████     | 4250/8455 [04:16<05:06, 13.73it/s]

Preprocessing:  50%|█████     | 4252/8455 [04:16<05:07, 13.65it/s]

Preprocessing:  50%|█████     | 4254/8455 [04:16<04:56, 14.18it/s]

Preprocessing:  50%|█████     | 4256/8455 [04:17<04:54, 14.24it/s]

Preprocessing:  50%|█████     | 4258/8455 [04:17<05:11, 13.46it/s]

Preprocessing:  50%|█████     | 4260/8455 [04:17<05:20, 13.08it/s]

Preprocessing:  50%|█████     | 4262/8455 [04:17<05:18, 13.16it/s]

Preprocessing:  50%|█████     | 4264/8455 [04:17<05:04, 13.78it/s]

Preprocessing:  50%|█████     | 4266/8455 [04:17<04:49, 14.45it/s]

Preprocessing:  50%|█████     | 4268/8455 [04:17<04:44, 14.71it/s]

Preprocessing:  51%|█████     | 4270/8455 [04:18<04:53, 14.27it/s]

Preprocessing:  51%|█████     | 4272/8455 [04:18<05:03, 13.80it/s]

Preprocessing:  51%|█████     | 4274/8455 [04:18<05:11, 13.41it/s]

Preprocessing:  51%|█████     | 4276/8455 [04:18<04:57, 14.06it/s]

Preprocessing:  51%|█████     | 4278/8455 [04:18<04:59, 13.95it/s]

Preprocessing:  51%|█████     | 4280/8455 [04:18<04:53, 14.24it/s]

Preprocessing:  51%|█████     | 4282/8455 [04:18<04:51, 14.33it/s]

Preprocessing:  51%|█████     | 4284/8455 [04:19<05:08, 13.53it/s]

Preprocessing:  51%|█████     | 4286/8455 [04:19<05:08, 13.52it/s]

Preprocessing:  51%|█████     | 4288/8455 [04:19<04:56, 14.04it/s]

Preprocessing:  51%|█████     | 4290/8455 [04:19<04:46, 14.54it/s]

Preprocessing:  51%|█████     | 4292/8455 [04:19<04:42, 14.73it/s]

Preprocessing:  51%|█████     | 4294/8455 [04:19<04:35, 15.09it/s]

Preprocessing:  51%|█████     | 4296/8455 [04:19<04:43, 14.65it/s]

Preprocessing:  51%|█████     | 4298/8455 [04:20<04:39, 14.89it/s]

Preprocessing:  51%|█████     | 4300/8455 [04:20<04:35, 15.09it/s]

Preprocessing:  51%|█████     | 4302/8455 [04:20<04:39, 14.87it/s]

Preprocessing:  51%|█████     | 4304/8455 [04:20<04:39, 14.84it/s]

Preprocessing:  51%|█████     | 4306/8455 [04:20<04:37, 14.96it/s]

Preprocessing:  51%|█████     | 4308/8455 [04:20<04:39, 14.85it/s]

Preprocessing:  51%|█████     | 4310/8455 [04:20<04:47, 14.42it/s]

Preprocessing:  51%|█████     | 4312/8455 [04:20<04:52, 14.18it/s]

Preprocessing:  51%|█████     | 4314/8455 [04:21<05:06, 13.51it/s]

Preprocessing:  51%|█████     | 4316/8455 [04:21<05:16, 13.09it/s]

Preprocessing:  51%|█████     | 4318/8455 [04:21<05:09, 13.37it/s]

Preprocessing:  51%|█████     | 4320/8455 [04:21<05:15, 13.10it/s]

Preprocessing:  51%|█████     | 4322/8455 [04:21<05:12, 13.22it/s]

Preprocessing:  51%|█████     | 4324/8455 [04:21<05:20, 12.87it/s]

Preprocessing:  51%|█████     | 4326/8455 [04:22<05:15, 13.11it/s]

Preprocessing:  51%|█████     | 4328/8455 [04:22<05:12, 13.19it/s]

Preprocessing:  51%|█████     | 4330/8455 [04:22<05:11, 13.24it/s]

Preprocessing:  51%|█████     | 4332/8455 [04:22<05:21, 12.84it/s]

Preprocessing:  51%|█████▏    | 4334/8455 [04:22<05:17, 13.00it/s]

Preprocessing:  51%|█████▏    | 4336/8455 [04:22<05:16, 13.00it/s]

Preprocessing:  51%|█████▏    | 4338/8455 [04:23<05:20, 12.84it/s]

Preprocessing:  51%|█████▏    | 4340/8455 [04:23<05:24, 12.68it/s]

Preprocessing:  51%|█████▏    | 4342/8455 [04:23<05:05, 13.46it/s]

Preprocessing:  51%|█████▏    | 4344/8455 [04:23<05:04, 13.48it/s]

Preprocessing:  51%|█████▏    | 4346/8455 [04:23<05:00, 13.68it/s]

Preprocessing:  51%|█████▏    | 4348/8455 [04:23<05:13, 13.09it/s]

Preprocessing:  51%|█████▏    | 4350/8455 [04:23<05:28, 12.52it/s]

Preprocessing:  51%|█████▏    | 4352/8455 [04:24<05:41, 12.00it/s]

Preprocessing:  51%|█████▏    | 4354/8455 [04:24<05:26, 12.56it/s]

Preprocessing:  52%|█████▏    | 4356/8455 [04:24<05:05, 13.41it/s]

Preprocessing:  52%|█████▏    | 4358/8455 [04:24<05:10, 13.21it/s]

Preprocessing:  52%|█████▏    | 4360/8455 [04:24<05:16, 12.92it/s]

Preprocessing:  52%|█████▏    | 4362/8455 [04:24<05:12, 13.10it/s]

Preprocessing:  52%|█████▏    | 4364/8455 [04:24<05:04, 13.45it/s]

Preprocessing:  52%|█████▏    | 4366/8455 [04:25<05:10, 13.15it/s]

Preprocessing:  52%|█████▏    | 4368/8455 [04:25<05:05, 13.36it/s]

Preprocessing:  52%|█████▏    | 4370/8455 [04:25<05:12, 13.09it/s]

Preprocessing:  52%|█████▏    | 4372/8455 [04:25<04:57, 13.72it/s]

Preprocessing:  52%|█████▏    | 4374/8455 [04:25<05:10, 13.15it/s]

Preprocessing:  52%|█████▏    | 4376/8455 [04:25<05:07, 13.25it/s]

Preprocessing:  52%|█████▏    | 4378/8455 [04:26<04:56, 13.75it/s]

Preprocessing:  52%|█████▏    | 4380/8455 [04:26<04:48, 14.14it/s]

Preprocessing:  52%|█████▏    | 4382/8455 [04:26<05:00, 13.53it/s]

Preprocessing:  52%|█████▏    | 4384/8455 [04:26<04:52, 13.92it/s]

Preprocessing:  52%|█████▏    | 4386/8455 [04:26<05:03, 13.40it/s]

Preprocessing:  52%|█████▏    | 4388/8455 [04:26<05:02, 13.45it/s]

Preprocessing:  52%|█████▏    | 4390/8455 [04:26<04:54, 13.80it/s]

Preprocessing:  52%|█████▏    | 4392/8455 [04:27<04:43, 14.32it/s]

Preprocessing:  52%|█████▏    | 4394/8455 [04:27<04:42, 14.35it/s]

Preprocessing:  52%|█████▏    | 4396/8455 [04:27<04:42, 14.36it/s]

Preprocessing:  52%|█████▏    | 4398/8455 [04:27<04:42, 14.37it/s]

Preprocessing:  52%|█████▏    | 4400/8455 [04:27<04:46, 14.16it/s]

Preprocessing:  52%|█████▏    | 4402/8455 [04:27<04:49, 14.01it/s]

Preprocessing:  52%|█████▏    | 4404/8455 [04:27<04:55, 13.72it/s]

Preprocessing:  52%|█████▏    | 4406/8455 [04:28<04:55, 13.71it/s]

Preprocessing:  52%|█████▏    | 4408/8455 [04:28<04:42, 14.33it/s]

Preprocessing:  52%|█████▏    | 4410/8455 [04:28<04:46, 14.10it/s]

Preprocessing:  52%|█████▏    | 4412/8455 [04:28<04:40, 14.43it/s]

Preprocessing:  52%|█████▏    | 4414/8455 [04:28<04:57, 13.58it/s]

Preprocessing:  52%|█████▏    | 4416/8455 [04:28<04:52, 13.81it/s]

Preprocessing:  52%|█████▏    | 4418/8455 [04:28<04:52, 13.78it/s]

Preprocessing:  52%|█████▏    | 4420/8455 [04:29<04:57, 13.54it/s]

Preprocessing:  52%|█████▏    | 4422/8455 [04:29<05:05, 13.21it/s]

Preprocessing:  52%|█████▏    | 4424/8455 [04:29<05:10, 12.99it/s]

Preprocessing:  52%|█████▏    | 4426/8455 [04:29<05:00, 13.39it/s]

Preprocessing:  52%|█████▏    | 4428/8455 [04:29<05:08, 13.06it/s]

Preprocessing:  52%|█████▏    | 4430/8455 [04:29<04:50, 13.88it/s]

Preprocessing:  52%|█████▏    | 4432/8455 [04:29<04:55, 13.63it/s]

Preprocessing:  52%|█████▏    | 4434/8455 [04:30<04:45, 14.10it/s]

Preprocessing:  52%|█████▏    | 4436/8455 [04:30<05:06, 13.10it/s]

Preprocessing:  52%|█████▏    | 4438/8455 [04:30<05:02, 13.29it/s]

Preprocessing:  53%|█████▎    | 4440/8455 [04:30<05:01, 13.32it/s]

Preprocessing:  53%|█████▎    | 4442/8455 [04:30<05:11, 12.88it/s]

Preprocessing:  53%|█████▎    | 4444/8455 [04:30<05:57, 11.22it/s]

Preprocessing:  53%|█████▎    | 4446/8455 [04:31<06:13, 10.74it/s]

Preprocessing:  53%|█████▎    | 4448/8455 [04:31<05:54, 11.32it/s]

Preprocessing:  53%|█████▎    | 4450/8455 [04:31<05:16, 12.65it/s]

Preprocessing:  53%|█████▎    | 4452/8455 [04:31<04:48, 13.88it/s]

Preprocessing:  53%|█████▎    | 4454/8455 [04:31<04:26, 15.02it/s]

Preprocessing:  53%|█████▎    | 4456/8455 [04:31<04:11, 15.92it/s]

Preprocessing:  53%|█████▎    | 4458/8455 [04:31<04:08, 16.06it/s]

Preprocessing:  53%|█████▎    | 4460/8455 [04:31<04:00, 16.58it/s]

Preprocessing:  53%|█████▎    | 4462/8455 [04:32<03:54, 17.06it/s]

Preprocessing:  53%|█████▎    | 4464/8455 [04:32<03:46, 17.59it/s]

Preprocessing:  53%|█████▎    | 4466/8455 [04:32<03:47, 17.51it/s]

Preprocessing:  53%|█████▎    | 4468/8455 [04:32<03:53, 17.09it/s]

Preprocessing:  53%|█████▎    | 4470/8455 [04:32<03:44, 17.72it/s]

Preprocessing:  53%|█████▎    | 4472/8455 [04:32<03:42, 17.88it/s]

Preprocessing:  53%|█████▎    | 4474/8455 [04:32<03:42, 17.87it/s]

Preprocessing:  53%|█████▎    | 4476/8455 [04:32<03:36, 18.35it/s]

Preprocessing:  53%|█████▎    | 4478/8455 [04:32<03:35, 18.43it/s]

Preprocessing:  53%|█████▎    | 4480/8455 [04:33<03:38, 18.23it/s]

Preprocessing:  53%|█████▎    | 4482/8455 [04:33<03:47, 17.46it/s]

Preprocessing:  53%|█████▎    | 4484/8455 [04:33<03:44, 17.66it/s]

Preprocessing:  53%|█████▎    | 4486/8455 [04:33<03:49, 17.30it/s]

Preprocessing:  53%|█████▎    | 4488/8455 [04:33<03:46, 17.49it/s]

Preprocessing:  53%|█████▎    | 4490/8455 [04:33<03:42, 17.82it/s]

Preprocessing:  53%|█████▎    | 4492/8455 [04:33<03:43, 17.73it/s]

Preprocessing:  53%|█████▎    | 4494/8455 [04:33<03:47, 17.45it/s]

Preprocessing:  53%|█████▎    | 4496/8455 [04:34<03:49, 17.28it/s]

Preprocessing:  53%|█████▎    | 4498/8455 [04:34<03:47, 17.37it/s]

Preprocessing:  53%|█████▎    | 4500/8455 [04:34<03:43, 17.68it/s]

Preprocessing:  53%|█████▎    | 4502/8455 [04:34<04:24, 14.95it/s]

Preprocessing:  53%|█████▎    | 4504/8455 [04:34<04:57, 13.26it/s]

Preprocessing:  53%|█████▎    | 4506/8455 [04:34<04:48, 13.68it/s]

Preprocessing:  53%|█████▎    | 4508/8455 [04:34<04:29, 14.64it/s]

Preprocessing:  53%|█████▎    | 4510/8455 [04:34<04:11, 15.66it/s]

Preprocessing:  53%|█████▎    | 4512/8455 [04:35<04:05, 16.04it/s]

Preprocessing:  53%|█████▎    | 4514/8455 [04:35<04:00, 16.35it/s]

Preprocessing:  53%|█████▎    | 4516/8455 [04:35<03:50, 17.09it/s]

Preprocessing:  53%|█████▎    | 4518/8455 [04:35<03:49, 17.18it/s]

Preprocessing:  53%|█████▎    | 4520/8455 [04:35<03:42, 17.65it/s]

Preprocessing:  53%|█████▎    | 4522/8455 [04:35<03:45, 17.47it/s]

Preprocessing:  54%|█████▎    | 4524/8455 [04:35<04:31, 14.48it/s]

Preprocessing:  54%|█████▎    | 4526/8455 [04:35<04:12, 15.53it/s]

Preprocessing:  54%|█████▎    | 4528/8455 [04:36<04:02, 16.20it/s]

Preprocessing:  54%|█████▎    | 4530/8455 [04:36<03:53, 16.80it/s]

Preprocessing:  54%|█████▎    | 4533/8455 [04:36<03:39, 17.84it/s]

Preprocessing:  54%|█████▎    | 4535/8455 [04:36<03:38, 17.92it/s]

Preprocessing:  54%|█████▎    | 4537/8455 [04:36<03:33, 18.32it/s]

Preprocessing:  54%|█████▎    | 4539/8455 [04:36<03:37, 18.04it/s]

Preprocessing:  54%|█████▎    | 4542/8455 [04:36<03:33, 18.30it/s]

Preprocessing:  54%|█████▍    | 4545/8455 [04:36<03:31, 18.52it/s]

Preprocessing:  54%|█████▍    | 4547/8455 [04:37<03:35, 18.17it/s]

Preprocessing:  54%|█████▍    | 4549/8455 [04:37<03:32, 18.38it/s]

Preprocessing:  54%|█████▍    | 4551/8455 [04:37<03:33, 18.32it/s]

Preprocessing:  54%|█████▍    | 4553/8455 [04:37<03:30, 18.58it/s]

Preprocessing:  54%|█████▍    | 4555/8455 [04:37<03:28, 18.66it/s]

Preprocessing:  54%|█████▍    | 4557/8455 [04:37<03:41, 17.57it/s]

Preprocessing:  54%|█████▍    | 4559/8455 [04:37<04:16, 15.21it/s]

Preprocessing:  54%|█████▍    | 4561/8455 [04:37<04:37, 14.02it/s]

Preprocessing:  54%|█████▍    | 4563/8455 [04:38<04:34, 14.19it/s]

Preprocessing:  54%|█████▍    | 4565/8455 [04:38<04:34, 14.18it/s]

Preprocessing:  54%|█████▍    | 4567/8455 [04:38<04:32, 14.27it/s]

Preprocessing:  54%|█████▍    | 4569/8455 [04:38<04:30, 14.39it/s]

Preprocessing:  54%|█████▍    | 4571/8455 [04:38<04:33, 14.21it/s]

Preprocessing:  54%|█████▍    | 4573/8455 [04:38<04:49, 13.40it/s]

Preprocessing:  54%|█████▍    | 4575/8455 [04:38<04:47, 13.49it/s]

Preprocessing:  54%|█████▍    | 4577/8455 [04:39<04:46, 13.52it/s]

Preprocessing:  54%|█████▍    | 4579/8455 [04:39<04:43, 13.67it/s]

Preprocessing:  54%|█████▍    | 4581/8455 [04:39<04:34, 14.11it/s]

Preprocessing:  54%|█████▍    | 4583/8455 [04:39<04:46, 13.50it/s]

Preprocessing:  54%|█████▍    | 4585/8455 [04:39<04:43, 13.65it/s]

Preprocessing:  54%|█████▍    | 4587/8455 [04:39<04:47, 13.47it/s]

Preprocessing:  54%|█████▍    | 4589/8455 [04:39<04:37, 13.94it/s]

Preprocessing:  54%|█████▍    | 4591/8455 [04:40<04:36, 13.96it/s]

Preprocessing:  54%|█████▍    | 4593/8455 [04:40<04:47, 13.41it/s]

Preprocessing:  54%|█████▍    | 4595/8455 [04:40<04:37, 13.92it/s]

Preprocessing:  54%|█████▍    | 4597/8455 [04:40<04:42, 13.66it/s]

Preprocessing:  54%|█████▍    | 4599/8455 [04:40<04:43, 13.59it/s]

Preprocessing:  54%|█████▍    | 4601/8455 [04:40<04:56, 12.99it/s]

Preprocessing:  54%|█████▍    | 4603/8455 [04:41<05:20, 12.03it/s]

Preprocessing:  54%|█████▍    | 4605/8455 [04:41<04:58, 12.88it/s]

Preprocessing:  54%|█████▍    | 4607/8455 [04:41<05:01, 12.77it/s]

Preprocessing:  55%|█████▍    | 4609/8455 [04:41<05:10, 12.38it/s]

Preprocessing:  55%|█████▍    | 4611/8455 [04:41<05:05, 12.57it/s]

Preprocessing:  55%|█████▍    | 4613/8455 [04:41<05:11, 12.33it/s]

Preprocessing:  55%|█████▍    | 4615/8455 [04:42<05:19, 12.02it/s]

Preprocessing:  55%|█████▍    | 4617/8455 [04:42<05:03, 12.66it/s]

Preprocessing:  55%|█████▍    | 4619/8455 [04:42<04:58, 12.86it/s]

Preprocessing:  55%|█████▍    | 4621/8455 [04:42<04:43, 13.50it/s]

Preprocessing:  55%|█████▍    | 4623/8455 [04:42<04:50, 13.21it/s]

Preprocessing:  55%|█████▍    | 4625/8455 [04:42<04:43, 13.52it/s]

Preprocessing:  55%|█████▍    | 4627/8455 [04:42<04:43, 13.48it/s]

Preprocessing:  55%|█████▍    | 4629/8455 [04:43<04:52, 13.07it/s]

Preprocessing:  55%|█████▍    | 4631/8455 [04:43<04:45, 13.39it/s]

Preprocessing:  55%|█████▍    | 4633/8455 [04:43<04:36, 13.82it/s]

Preprocessing:  55%|█████▍    | 4635/8455 [04:43<04:29, 14.18it/s]

Preprocessing:  55%|█████▍    | 4637/8455 [04:43<04:29, 14.18it/s]

Preprocessing:  55%|█████▍    | 4639/8455 [04:43<04:31, 14.07it/s]

Preprocessing:  55%|█████▍    | 4641/8455 [04:43<04:21, 14.59it/s]

Preprocessing:  55%|█████▍    | 4643/8455 [04:44<04:30, 14.07it/s]

Preprocessing:  55%|█████▍    | 4645/8455 [04:44<04:38, 13.70it/s]

Preprocessing:  55%|█████▍    | 4647/8455 [04:44<04:47, 13.24it/s]

Preprocessing:  55%|█████▍    | 4649/8455 [04:44<05:07, 12.36it/s]

Preprocessing:  55%|█████▌    | 4651/8455 [04:44<04:56, 12.83it/s]

Preprocessing:  55%|█████▌    | 4653/8455 [04:44<05:03, 12.53it/s]

Preprocessing:  55%|█████▌    | 4655/8455 [04:45<05:05, 12.43it/s]

Preprocessing:  55%|█████▌    | 4657/8455 [04:45<04:56, 12.83it/s]

Preprocessing:  55%|█████▌    | 4659/8455 [04:45<04:53, 12.92it/s]

Preprocessing:  55%|█████▌    | 4661/8455 [04:45<04:46, 13.22it/s]

Preprocessing:  55%|█████▌    | 4663/8455 [04:45<04:48, 13.14it/s]

Preprocessing:  55%|█████▌    | 4665/8455 [04:45<04:37, 13.68it/s]

Preprocessing:  55%|█████▌    | 4667/8455 [04:45<04:35, 13.73it/s]

Preprocessing:  55%|█████▌    | 4669/8455 [04:46<04:38, 13.59it/s]

Preprocessing:  55%|█████▌    | 4671/8455 [04:46<04:39, 13.55it/s]

Preprocessing:  55%|█████▌    | 4673/8455 [04:46<04:39, 13.53it/s]

Preprocessing:  55%|█████▌    | 4675/8455 [04:46<04:40, 13.45it/s]

Preprocessing:  55%|█████▌    | 4677/8455 [04:46<04:39, 13.49it/s]

Preprocessing:  55%|█████▌    | 4679/8455 [04:46<04:34, 13.78it/s]

Preprocessing:  55%|█████▌    | 4681/8455 [04:46<04:35, 13.71it/s]

Preprocessing:  55%|█████▌    | 4683/8455 [04:47<04:28, 14.04it/s]

Preprocessing:  55%|█████▌    | 4685/8455 [04:47<04:40, 13.45it/s]

Preprocessing:  55%|█████▌    | 4687/8455 [04:47<04:30, 13.92it/s]

Preprocessing:  55%|█████▌    | 4689/8455 [04:47<04:27, 14.05it/s]

Preprocessing:  55%|█████▌    | 4691/8455 [04:47<04:37, 13.55it/s]

Preprocessing:  56%|█████▌    | 4693/8455 [04:47<04:48, 13.04it/s]

Preprocessing:  56%|█████▌    | 4695/8455 [04:47<04:52, 12.87it/s]

Preprocessing:  56%|█████▌    | 4697/8455 [04:48<04:48, 13.04it/s]

Preprocessing:  56%|█████▌    | 4699/8455 [04:48<04:42, 13.30it/s]

Preprocessing:  56%|█████▌    | 4701/8455 [04:48<04:36, 13.58it/s]

Preprocessing:  56%|█████▌    | 4703/8455 [04:48<04:50, 12.92it/s]

Preprocessing:  56%|█████▌    | 4705/8455 [04:48<04:45, 13.13it/s]

Preprocessing:  56%|█████▌    | 4707/8455 [04:48<04:36, 13.58it/s]

Preprocessing:  56%|█████▌    | 4709/8455 [04:49<04:37, 13.50it/s]

Preprocessing:  56%|█████▌    | 4711/8455 [04:49<04:30, 13.84it/s]

Preprocessing:  56%|█████▌    | 4713/8455 [04:49<04:25, 14.09it/s]

Preprocessing:  56%|█████▌    | 4715/8455 [04:49<04:24, 14.15it/s]

Preprocessing:  56%|█████▌    | 4717/8455 [04:49<04:19, 14.40it/s]

Preprocessing:  56%|█████▌    | 4719/8455 [04:49<04:25, 14.05it/s]

Preprocessing:  56%|█████▌    | 4721/8455 [04:49<04:31, 13.74it/s]

Preprocessing:  56%|█████▌    | 4723/8455 [04:50<04:24, 14.09it/s]

Preprocessing:  56%|█████▌    | 4725/8455 [04:50<04:29, 13.83it/s]

Preprocessing:  56%|█████▌    | 4727/8455 [04:50<04:47, 12.98it/s]

Preprocessing:  56%|█████▌    | 4729/8455 [04:50<05:05, 12.22it/s]

Preprocessing:  56%|█████▌    | 4731/8455 [04:50<05:18, 11.68it/s]

Preprocessing:  56%|█████▌    | 4733/8455 [04:50<05:28, 11.32it/s]

Preprocessing:  56%|█████▌    | 4735/8455 [04:51<05:24, 11.46it/s]

Preprocessing:  56%|█████▌    | 4737/8455 [04:51<05:16, 11.75it/s]

Preprocessing:  56%|█████▌    | 4739/8455 [04:51<05:10, 11.98it/s]

Preprocessing:  56%|█████▌    | 4741/8455 [04:51<05:19, 11.64it/s]

Preprocessing:  56%|█████▌    | 4743/8455 [04:51<05:33, 11.14it/s]

Preprocessing:  56%|█████▌    | 4745/8455 [04:51<05:39, 10.92it/s]

Preprocessing:  56%|█████▌    | 4747/8455 [04:52<05:32, 11.16it/s]

Preprocessing:  56%|█████▌    | 4749/8455 [04:52<05:27, 11.32it/s]

Preprocessing:  56%|█████▌    | 4751/8455 [04:52<05:37, 10.98it/s]

Preprocessing:  56%|█████▌    | 4753/8455 [04:52<05:45, 10.70it/s]

Preprocessing:  56%|█████▌    | 4755/8455 [04:52<05:32, 11.12it/s]

Preprocessing:  56%|█████▋    | 4757/8455 [04:53<05:33, 11.10it/s]

Preprocessing:  56%|█████▋    | 4759/8455 [04:53<05:21, 11.49it/s]

Preprocessing:  56%|█████▋    | 4761/8455 [04:53<05:24, 11.38it/s]

Preprocessing:  56%|█████▋    | 4763/8455 [04:53<05:28, 11.25it/s]

Preprocessing:  56%|█████▋    | 4765/8455 [04:53<05:18, 11.58it/s]

Preprocessing:  56%|█████▋    | 4767/8455 [04:53<05:33, 11.05it/s]

Preprocessing:  56%|█████▋    | 4769/8455 [04:54<05:45, 10.68it/s]

Preprocessing:  56%|█████▋    | 4771/8455 [04:54<05:49, 10.53it/s]

Preprocessing:  56%|█████▋    | 4773/8455 [04:54<05:22, 11.41it/s]

Preprocessing:  56%|█████▋    | 4775/8455 [04:54<05:04, 12.09it/s]

Preprocessing:  56%|█████▋    | 4777/8455 [04:54<05:04, 12.06it/s]

Preprocessing:  57%|█████▋    | 4779/8455 [04:54<04:53, 12.51it/s]

Preprocessing:  57%|█████▋    | 4781/8455 [04:55<04:59, 12.27it/s]

Preprocessing:  57%|█████▋    | 4783/8455 [04:55<04:56, 12.37it/s]

Preprocessing:  57%|█████▋    | 4785/8455 [04:55<04:43, 12.96it/s]

Preprocessing:  57%|█████▋    | 4787/8455 [04:55<04:49, 12.65it/s]

Preprocessing:  57%|█████▋    | 4789/8455 [04:55<04:37, 13.21it/s]

Preprocessing:  57%|█████▋    | 4791/8455 [04:55<04:38, 13.16it/s]

Preprocessing:  57%|█████▋    | 4793/8455 [04:55<04:37, 13.18it/s]

Preprocessing:  57%|█████▋    | 4795/8455 [04:56<04:47, 12.75it/s]

Preprocessing:  57%|█████▋    | 4797/8455 [04:56<04:43, 12.92it/s]

Preprocessing:  57%|█████▋    | 4799/8455 [04:56<04:41, 12.99it/s]

Preprocessing:  57%|█████▋    | 4801/8455 [04:56<04:45, 12.80it/s]

Preprocessing:  57%|█████▋    | 4803/8455 [04:56<04:35, 13.28it/s]

Preprocessing:  57%|█████▋    | 4805/8455 [04:56<04:40, 13.03it/s]

Preprocessing:  57%|█████▋    | 4807/8455 [04:57<04:37, 13.14it/s]

Preprocessing:  57%|█████▋    | 4809/8455 [04:57<04:37, 13.12it/s]

Preprocessing:  57%|█████▋    | 4811/8455 [04:57<04:45, 12.77it/s]

Preprocessing:  57%|█████▋    | 4813/8455 [04:57<04:34, 13.29it/s]

Preprocessing:  57%|█████▋    | 4815/8455 [04:57<04:35, 13.19it/s]

Preprocessing:  57%|█████▋    | 4817/8455 [04:57<04:47, 12.66it/s]

Preprocessing:  57%|█████▋    | 4819/8455 [04:58<04:49, 12.56it/s]

Preprocessing:  57%|█████▋    | 4821/8455 [04:58<04:54, 12.35it/s]

Preprocessing:  57%|█████▋    | 4823/8455 [04:58<04:40, 12.96it/s]

Preprocessing:  57%|█████▋    | 4825/8455 [04:58<04:36, 13.14it/s]

Preprocessing:  57%|█████▋    | 4827/8455 [04:58<04:32, 13.30it/s]

Preprocessing:  57%|█████▋    | 4829/8455 [04:58<04:37, 13.06it/s]

Preprocessing:  57%|█████▋    | 4831/8455 [04:58<04:36, 13.12it/s]

Preprocessing:  57%|█████▋    | 4833/8455 [04:59<04:34, 13.19it/s]

Preprocessing:  57%|█████▋    | 4835/8455 [04:59<04:23, 13.75it/s]

Preprocessing:  57%|█████▋    | 4837/8455 [04:59<04:35, 13.13it/s]

Preprocessing:  57%|█████▋    | 4839/8455 [04:59<04:56, 12.20it/s]

Preprocessing:  57%|█████▋    | 4841/8455 [04:59<05:02, 11.93it/s]

Preprocessing:  57%|█████▋    | 4843/8455 [04:59<04:57, 12.15it/s]

Preprocessing:  57%|█████▋    | 4845/8455 [05:00<04:39, 12.90it/s]

Preprocessing:  57%|█████▋    | 4847/8455 [05:00<04:33, 13.21it/s]

Preprocessing:  57%|█████▋    | 4849/8455 [05:00<04:35, 13.08it/s]

Preprocessing:  57%|█████▋    | 4851/8455 [05:00<04:25, 13.59it/s]

Preprocessing:  57%|█████▋    | 4853/8455 [05:00<04:15, 14.07it/s]

Preprocessing:  57%|█████▋    | 4855/8455 [05:00<04:29, 13.36it/s]

Preprocessing:  57%|█████▋    | 4857/8455 [05:00<04:35, 13.05it/s]

Preprocessing:  57%|█████▋    | 4859/8455 [05:01<04:52, 12.29it/s]

Preprocessing:  57%|█████▋    | 4861/8455 [05:01<04:41, 12.77it/s]

Preprocessing:  58%|█████▊    | 4863/8455 [05:01<04:37, 12.95it/s]

Preprocessing:  58%|█████▊    | 4865/8455 [05:01<04:33, 13.12it/s]

Preprocessing:  58%|█████▊    | 4867/8455 [05:01<04:29, 13.32it/s]

Preprocessing:  58%|█████▊    | 4869/8455 [05:01<04:30, 13.24it/s]

Preprocessing:  58%|█████▊    | 4871/8455 [05:01<04:28, 13.37it/s]

Preprocessing:  58%|█████▊    | 4873/8455 [05:02<04:33, 13.10it/s]

Preprocessing:  58%|█████▊    | 4875/8455 [05:02<04:48, 12.41it/s]

Preprocessing:  58%|█████▊    | 4877/8455 [05:02<04:36, 12.96it/s]

Preprocessing:  58%|█████▊    | 4879/8455 [05:02<04:41, 12.72it/s]

Preprocessing:  58%|█████▊    | 4881/8455 [05:02<04:45, 12.51it/s]

Preprocessing:  58%|█████▊    | 4883/8455 [05:02<04:40, 12.74it/s]

Preprocessing:  58%|█████▊    | 4885/8455 [05:03<04:38, 12.83it/s]

Preprocessing:  58%|█████▊    | 4887/8455 [05:03<04:30, 13.20it/s]

Preprocessing:  58%|█████▊    | 4889/8455 [05:03<04:27, 13.31it/s]

Preprocessing:  58%|█████▊    | 4891/8455 [05:03<04:27, 13.34it/s]

Preprocessing:  58%|█████▊    | 4893/8455 [05:03<04:26, 13.39it/s]

Preprocessing:  58%|█████▊    | 4895/8455 [05:03<04:20, 13.64it/s]

Preprocessing:  58%|█████▊    | 4897/8455 [05:03<04:22, 13.54it/s]

Preprocessing:  58%|█████▊    | 4899/8455 [05:04<04:23, 13.49it/s]

Preprocessing:  58%|█████▊    | 4901/8455 [05:04<04:31, 13.09it/s]

Preprocessing:  58%|█████▊    | 4903/8455 [05:04<04:37, 12.79it/s]

Preprocessing:  58%|█████▊    | 4905/8455 [05:04<04:32, 13.02it/s]

Preprocessing:  58%|█████▊    | 4907/8455 [05:04<04:28, 13.19it/s]

Preprocessing:  58%|█████▊    | 4909/8455 [05:04<04:36, 12.80it/s]

Preprocessing:  58%|█████▊    | 4911/8455 [05:05<04:33, 12.97it/s]

Preprocessing:  58%|█████▊    | 4913/8455 [05:05<04:23, 13.45it/s]

Preprocessing:  58%|█████▊    | 4915/8455 [05:05<04:17, 13.72it/s]

Preprocessing:  58%|█████▊    | 4917/8455 [05:05<04:21, 13.52it/s]

Preprocessing:  58%|█████▊    | 4919/8455 [05:05<04:13, 13.97it/s]

Preprocessing:  58%|█████▊    | 4921/8455 [05:05<04:29, 13.12it/s]

Preprocessing:  58%|█████▊    | 4923/8455 [05:05<04:26, 13.25it/s]

Preprocessing:  58%|█████▊    | 4925/8455 [05:06<04:15, 13.81it/s]

Preprocessing:  58%|█████▊    | 4927/8455 [05:06<04:23, 13.39it/s]

Preprocessing:  58%|█████▊    | 4929/8455 [05:06<04:51, 12.11it/s]

Preprocessing:  58%|█████▊    | 4931/8455 [05:06<04:41, 12.50it/s]

Preprocessing:  58%|█████▊    | 4933/8455 [05:06<04:27, 13.17it/s]

Preprocessing:  58%|█████▊    | 4935/8455 [05:06<04:15, 13.79it/s]

Preprocessing:  58%|█████▊    | 4937/8455 [05:07<04:23, 13.38it/s]

Preprocessing:  58%|█████▊    | 4939/8455 [05:07<04:17, 13.66it/s]

Preprocessing:  58%|█████▊    | 4941/8455 [05:07<04:30, 12.99it/s]

Preprocessing:  58%|█████▊    | 4943/8455 [05:07<04:16, 13.70it/s]

Preprocessing:  58%|█████▊    | 4945/8455 [05:07<04:06, 14.25it/s]

Preprocessing:  59%|█████▊    | 4947/8455 [05:07<04:19, 13.54it/s]

Preprocessing:  59%|█████▊    | 4949/8455 [05:07<04:14, 13.78it/s]

Preprocessing:  59%|█████▊    | 4951/8455 [05:08<04:11, 13.96it/s]

Preprocessing:  59%|█████▊    | 4953/8455 [05:08<04:03, 14.37it/s]

Preprocessing:  59%|█████▊    | 4955/8455 [05:08<03:58, 14.66it/s]

Preprocessing:  59%|█████▊    | 4957/8455 [05:08<03:55, 14.87it/s]

Preprocessing:  59%|█████▊    | 4959/8455 [05:08<03:57, 14.70it/s]

Preprocessing:  59%|█████▊    | 4961/8455 [05:08<04:13, 13.78it/s]

Preprocessing:  59%|█████▊    | 4963/8455 [05:08<04:26, 13.13it/s]

Preprocessing:  59%|█████▊    | 4965/8455 [05:09<04:25, 13.12it/s]

Preprocessing:  59%|█████▊    | 4967/8455 [05:09<04:25, 13.14it/s]

Preprocessing:  59%|█████▉    | 4969/8455 [05:09<04:22, 13.27it/s]

Preprocessing:  59%|█████▉    | 4971/8455 [05:09<04:15, 13.62it/s]

Preprocessing:  59%|█████▉    | 4973/8455 [05:09<04:17, 13.51it/s]

Preprocessing:  59%|█████▉    | 4975/8455 [05:09<04:16, 13.55it/s]

Preprocessing:  59%|█████▉    | 4977/8455 [05:09<04:19, 13.38it/s]

Preprocessing:  59%|█████▉    | 4979/8455 [05:10<04:12, 13.75it/s]

Preprocessing:  59%|█████▉    | 4981/8455 [05:10<04:28, 12.95it/s]

Preprocessing:  59%|█████▉    | 4983/8455 [05:10<04:47, 12.06it/s]

Preprocessing:  59%|█████▉    | 4985/8455 [05:10<04:44, 12.19it/s]

Preprocessing:  59%|█████▉    | 4987/8455 [05:10<04:48, 12.01it/s]

Preprocessing:  59%|█████▉    | 4989/8455 [05:10<04:59, 11.57it/s]

Preprocessing:  59%|█████▉    | 4991/8455 [05:11<04:48, 11.99it/s]

Preprocessing:  59%|█████▉    | 4993/8455 [05:11<04:56, 11.66it/s]

Preprocessing:  59%|█████▉    | 4995/8455 [05:11<04:53, 11.79it/s]

Preprocessing:  59%|█████▉    | 4997/8455 [05:11<04:59, 11.56it/s]

Preprocessing:  59%|█████▉    | 4999/8455 [05:11<05:01, 11.45it/s]

Preprocessing:  59%|█████▉    | 5001/8455 [05:11<04:48, 11.95it/s]

Preprocessing:  59%|█████▉    | 5003/8455 [05:12<04:34, 12.57it/s]

Preprocessing:  59%|█████▉    | 5005/8455 [05:12<04:30, 12.74it/s]

Preprocessing:  59%|█████▉    | 5007/8455 [05:12<04:26, 12.92it/s]

Preprocessing:  59%|█████▉    | 5009/8455 [05:12<04:54, 11.71it/s]

Preprocessing:  59%|█████▉    | 5011/8455 [05:12<04:38, 12.38it/s]

Preprocessing:  59%|█████▉    | 5013/8455 [05:12<04:31, 12.69it/s]

Preprocessing:  59%|█████▉    | 5015/8455 [05:13<04:30, 12.72it/s]

Preprocessing:  59%|█████▉    | 5017/8455 [05:13<04:21, 13.15it/s]

Preprocessing:  59%|█████▉    | 5019/8455 [05:13<04:17, 13.33it/s]

Preprocessing:  59%|█████▉    | 5021/8455 [05:13<04:15, 13.42it/s]

Preprocessing:  59%|█████▉    | 5023/8455 [05:13<04:20, 13.18it/s]

Preprocessing:  59%|█████▉    | 5025/8455 [05:13<04:23, 13.00it/s]

Preprocessing:  59%|█████▉    | 5027/8455 [05:13<04:28, 12.76it/s]

Preprocessing:  59%|█████▉    | 5029/8455 [05:14<04:33, 12.51it/s]

Preprocessing:  60%|█████▉    | 5031/8455 [05:14<04:29, 12.69it/s]

Preprocessing:  60%|█████▉    | 5033/8455 [05:14<04:21, 13.08it/s]

Preprocessing:  60%|█████▉    | 5035/8455 [05:14<04:17, 13.29it/s]

Preprocessing:  60%|█████▉    | 5037/8455 [05:14<04:36, 12.37it/s]

Preprocessing:  60%|█████▉    | 5039/8455 [05:14<04:50, 11.78it/s]

Preprocessing:  60%|█████▉    | 5041/8455 [05:15<04:48, 11.85it/s]

Preprocessing:  60%|█████▉    | 5043/8455 [05:15<04:36, 12.32it/s]

Preprocessing:  60%|█████▉    | 5045/8455 [05:15<04:38, 12.22it/s]

Preprocessing:  60%|█████▉    | 5047/8455 [05:15<04:37, 12.27it/s]

Preprocessing:  60%|█████▉    | 5049/8455 [05:15<04:38, 12.23it/s]

Preprocessing:  60%|█████▉    | 5051/8455 [05:15<04:30, 12.57it/s]

Preprocessing:  60%|█████▉    | 5053/8455 [05:16<04:22, 12.96it/s]

Preprocessing:  60%|█████▉    | 5055/8455 [05:16<04:18, 13.14it/s]

Preprocessing:  60%|█████▉    | 5057/8455 [05:16<04:14, 13.34it/s]

Preprocessing:  60%|█████▉    | 5059/8455 [05:16<04:19, 13.08it/s]

Preprocessing:  60%|█████▉    | 5061/8455 [05:16<04:17, 13.16it/s]

Preprocessing:  60%|█████▉    | 5063/8455 [05:16<04:25, 12.78it/s]

Preprocessing:  60%|█████▉    | 5065/8455 [05:17<04:37, 12.22it/s]

Preprocessing:  60%|█████▉    | 5067/8455 [05:17<04:36, 12.25it/s]

Preprocessing:  60%|█████▉    | 5069/8455 [05:17<04:26, 12.72it/s]

Preprocessing:  60%|█████▉    | 5071/8455 [05:17<04:17, 13.16it/s]

Preprocessing:  60%|██████    | 5073/8455 [05:17<04:17, 13.13it/s]

Preprocessing:  60%|██████    | 5075/8455 [05:17<04:15, 13.22it/s]

Preprocessing:  60%|██████    | 5077/8455 [05:17<04:16, 13.19it/s]

Preprocessing:  60%|██████    | 5079/8455 [05:18<04:21, 12.91it/s]

Preprocessing:  60%|██████    | 5081/8455 [05:18<04:24, 12.73it/s]

Preprocessing:  60%|██████    | 5083/8455 [05:18<04:23, 12.79it/s]

Preprocessing:  60%|██████    | 5085/8455 [05:18<04:25, 12.67it/s]

Preprocessing:  60%|██████    | 5087/8455 [05:18<04:22, 12.81it/s]

Preprocessing:  60%|██████    | 5089/8455 [05:18<04:17, 13.07it/s]

Preprocessing:  60%|██████    | 5091/8455 [05:18<04:18, 13.03it/s]

Preprocessing:  60%|██████    | 5093/8455 [05:19<04:18, 13.00it/s]

Preprocessing:  60%|██████    | 5095/8455 [05:19<04:16, 13.08it/s]

Preprocessing:  60%|██████    | 5097/8455 [05:19<04:21, 12.85it/s]

Preprocessing:  60%|██████    | 5099/8455 [05:19<04:19, 12.92it/s]

Preprocessing:  60%|██████    | 5101/8455 [05:19<04:23, 12.73it/s]

Preprocessing:  60%|██████    | 5103/8455 [05:19<04:27, 12.53it/s]

Preprocessing:  60%|██████    | 5105/8455 [05:20<04:19, 12.91it/s]

Preprocessing:  60%|██████    | 5107/8455 [05:20<04:16, 13.06it/s]

Preprocessing:  60%|██████    | 5109/8455 [05:20<04:16, 13.07it/s]

Preprocessing:  60%|██████    | 5111/8455 [05:20<04:08, 13.45it/s]

Preprocessing:  60%|██████    | 5113/8455 [05:20<04:05, 13.60it/s]

Preprocessing:  60%|██████    | 5115/8455 [05:20<04:14, 13.12it/s]

Preprocessing:  61%|██████    | 5117/8455 [05:21<04:22, 12.73it/s]

Preprocessing:  61%|██████    | 5119/8455 [05:21<04:28, 12.41it/s]

Preprocessing:  61%|██████    | 5121/8455 [05:21<04:24, 12.60it/s]

Preprocessing:  61%|██████    | 5123/8455 [05:21<04:22, 12.71it/s]

Preprocessing:  61%|██████    | 5125/8455 [05:21<04:18, 12.89it/s]

Preprocessing:  61%|██████    | 5127/8455 [05:21<04:23, 12.62it/s]

Preprocessing:  61%|██████    | 5129/8455 [05:21<04:14, 13.09it/s]

Preprocessing:  61%|██████    | 5131/8455 [05:22<04:06, 13.48it/s]

Preprocessing:  61%|██████    | 5133/8455 [05:22<04:01, 13.77it/s]

Preprocessing:  61%|██████    | 5135/8455 [05:22<04:12, 13.17it/s]

Preprocessing:  61%|██████    | 5137/8455 [05:22<04:14, 13.06it/s]

Preprocessing:  61%|██████    | 5139/8455 [05:22<04:15, 12.97it/s]

Preprocessing:  61%|██████    | 5141/8455 [05:22<04:14, 13.01it/s]

Preprocessing:  61%|██████    | 5143/8455 [05:22<04:07, 13.38it/s]

Preprocessing:  61%|██████    | 5145/8455 [05:23<04:11, 13.14it/s]

Preprocessing:  61%|██████    | 5147/8455 [05:23<04:16, 12.89it/s]

Preprocessing:  61%|██████    | 5149/8455 [05:23<04:12, 13.07it/s]

Preprocessing:  61%|██████    | 5151/8455 [05:23<04:08, 13.27it/s]

Preprocessing:  61%|██████    | 5153/8455 [05:23<04:13, 13.01it/s]

Preprocessing:  61%|██████    | 5155/8455 [05:23<04:12, 13.06it/s]

Preprocessing:  61%|██████    | 5157/8455 [05:24<04:18, 12.75it/s]

Preprocessing:  61%|██████    | 5159/8455 [05:24<04:07, 13.29it/s]

Preprocessing:  61%|██████    | 5161/8455 [05:24<03:58, 13.82it/s]

Preprocessing:  61%|██████    | 5163/8455 [05:24<03:57, 13.85it/s]

Preprocessing:  61%|██████    | 5165/8455 [05:24<03:55, 13.99it/s]

Preprocessing:  61%|██████    | 5167/8455 [05:24<03:56, 13.88it/s]

Preprocessing:  61%|██████    | 5169/8455 [05:24<03:52, 14.15it/s]

Preprocessing:  61%|██████    | 5171/8455 [05:25<03:58, 13.78it/s]

Preprocessing:  61%|██████    | 5173/8455 [05:25<04:02, 13.51it/s]

Preprocessing:  61%|██████    | 5175/8455 [05:25<03:55, 13.96it/s]

Preprocessing:  61%|██████    | 5177/8455 [05:25<04:04, 13.38it/s]

Preprocessing:  61%|██████▏   | 5179/8455 [05:25<04:02, 13.53it/s]

Preprocessing:  61%|██████▏   | 5181/8455 [05:25<04:04, 13.39it/s]

Preprocessing:  61%|██████▏   | 5183/8455 [05:25<04:07, 13.24it/s]

Preprocessing:  61%|██████▏   | 5185/8455 [05:26<04:15, 12.81it/s]

Preprocessing:  61%|██████▏   | 5187/8455 [05:26<04:09, 13.09it/s]

Preprocessing:  61%|██████▏   | 5189/8455 [05:26<04:06, 13.25it/s]

Preprocessing:  61%|██████▏   | 5191/8455 [05:26<04:10, 13.03it/s]

Preprocessing:  61%|██████▏   | 5193/8455 [05:26<04:04, 13.33it/s]

Preprocessing:  61%|██████▏   | 5195/8455 [05:26<04:07, 13.15it/s]

Preprocessing:  61%|██████▏   | 5197/8455 [05:27<04:09, 13.07it/s]

Preprocessing:  61%|██████▏   | 5199/8455 [05:27<04:13, 12.84it/s]

Preprocessing:  62%|██████▏   | 5201/8455 [05:27<04:18, 12.57it/s]

Preprocessing:  62%|██████▏   | 5203/8455 [05:27<04:22, 12.40it/s]

Preprocessing:  62%|██████▏   | 5205/8455 [05:27<04:20, 12.45it/s]

Preprocessing:  62%|██████▏   | 5207/8455 [05:27<04:07, 13.12it/s]

Preprocessing:  62%|██████▏   | 5209/8455 [05:28<04:17, 12.61it/s]

Preprocessing:  62%|██████▏   | 5211/8455 [05:28<04:30, 11.97it/s]

Preprocessing:  62%|██████▏   | 5213/8455 [05:28<04:23, 12.29it/s]

Preprocessing:  62%|██████▏   | 5215/8455 [05:28<04:10, 12.92it/s]

Preprocessing:  62%|██████▏   | 5217/8455 [05:28<04:06, 13.15it/s]

Preprocessing:  62%|██████▏   | 5219/8455 [05:28<03:51, 13.97it/s]

Preprocessing:  62%|██████▏   | 5221/8455 [05:28<03:31, 15.31it/s]

Preprocessing:  62%|██████▏   | 5224/8455 [05:28<03:05, 17.45it/s]

Preprocessing:  62%|██████▏   | 5227/8455 [05:29<02:50, 18.95it/s]

Preprocessing:  62%|██████▏   | 5230/8455 [05:29<02:36, 20.65it/s]

Preprocessing:  62%|██████▏   | 5233/8455 [05:29<02:27, 21.83it/s]

Preprocessing:  62%|██████▏   | 5236/8455 [05:29<02:21, 22.80it/s]

Preprocessing:  62%|██████▏   | 5239/8455 [05:29<02:17, 23.43it/s]

Preprocessing:  62%|██████▏   | 5242/8455 [05:29<02:12, 24.17it/s]

Preprocessing:  62%|██████▏   | 5245/8455 [05:29<02:13, 23.98it/s]

Preprocessing:  62%|██████▏   | 5248/8455 [05:29<02:11, 24.40it/s]

Preprocessing:  62%|██████▏   | 5251/8455 [05:30<02:06, 25.25it/s]

Preprocessing:  62%|██████▏   | 5254/8455 [05:30<02:07, 25.18it/s]

Preprocessing:  62%|██████▏   | 5257/8455 [05:30<02:09, 24.62it/s]

Preprocessing:  62%|██████▏   | 5260/8455 [05:30<02:09, 24.64it/s]

Preprocessing:  62%|██████▏   | 5263/8455 [05:30<02:10, 24.48it/s]

Preprocessing:  62%|██████▏   | 5266/8455 [05:30<02:08, 24.78it/s]

Preprocessing:  62%|██████▏   | 5269/8455 [05:30<02:08, 24.87it/s]

Preprocessing:  62%|██████▏   | 5272/8455 [05:30<02:15, 23.42it/s]

Preprocessing:  62%|██████▏   | 5275/8455 [05:31<02:24, 22.04it/s]

Preprocessing:  62%|██████▏   | 5278/8455 [05:31<02:26, 21.69it/s]

Preprocessing:  62%|██████▏   | 5281/8455 [05:31<02:23, 22.05it/s]

Preprocessing:  62%|██████▏   | 5284/8455 [05:31<02:22, 22.22it/s]

Preprocessing:  63%|██████▎   | 5287/8455 [05:31<02:19, 22.66it/s]

Preprocessing:  63%|██████▎   | 5290/8455 [05:31<02:15, 23.29it/s]

Preprocessing:  63%|██████▎   | 5293/8455 [05:31<02:15, 23.34it/s]

Preprocessing:  63%|██████▎   | 5296/8455 [05:32<02:14, 23.41it/s]

Preprocessing:  63%|██████▎   | 5299/8455 [05:32<02:13, 23.70it/s]

Preprocessing:  63%|██████▎   | 5302/8455 [05:32<02:13, 23.69it/s]

Preprocessing:  63%|██████▎   | 5305/8455 [05:32<02:11, 23.88it/s]

Preprocessing:  63%|██████▎   | 5308/8455 [05:32<02:10, 24.16it/s]

Preprocessing:  63%|██████▎   | 5311/8455 [05:32<02:10, 24.00it/s]

Preprocessing:  63%|██████▎   | 5314/8455 [05:32<02:09, 24.32it/s]

Preprocessing:  63%|██████▎   | 5317/8455 [05:32<02:14, 23.34it/s]

Preprocessing:  63%|██████▎   | 5320/8455 [05:33<02:12, 23.61it/s]

Preprocessing:  63%|██████▎   | 5323/8455 [05:33<02:12, 23.63it/s]

Preprocessing:  63%|██████▎   | 5326/8455 [05:33<02:15, 23.13it/s]

Preprocessing:  63%|██████▎   | 5329/8455 [05:33<02:16, 22.98it/s]

Preprocessing:  63%|██████▎   | 5332/8455 [05:33<02:14, 23.24it/s]

Preprocessing:  63%|██████▎   | 5335/8455 [05:33<02:10, 23.87it/s]

Preprocessing:  63%|██████▎   | 5338/8455 [05:33<02:12, 23.47it/s]

Preprocessing:  63%|██████▎   | 5341/8455 [05:33<02:11, 23.59it/s]

Preprocessing:  63%|██████▎   | 5344/8455 [05:34<02:12, 23.54it/s]

Preprocessing:  63%|██████▎   | 5347/8455 [05:34<02:11, 23.68it/s]

Preprocessing:  63%|██████▎   | 5350/8455 [05:34<02:09, 24.06it/s]

Preprocessing:  63%|██████▎   | 5353/8455 [05:34<02:16, 22.79it/s]

Preprocessing:  63%|██████▎   | 5356/8455 [05:34<02:14, 23.10it/s]

Preprocessing:  63%|██████▎   | 5359/8455 [05:34<02:12, 23.40it/s]

Preprocessing:  63%|██████▎   | 5362/8455 [05:34<02:11, 23.46it/s]

Preprocessing:  63%|██████▎   | 5365/8455 [05:34<02:11, 23.50it/s]

Preprocessing:  63%|██████▎   | 5368/8455 [05:35<02:09, 23.78it/s]

Preprocessing:  64%|██████▎   | 5371/8455 [05:35<02:12, 23.25it/s]

Preprocessing:  64%|██████▎   | 5374/8455 [05:35<02:12, 23.29it/s]

Preprocessing:  64%|██████▎   | 5377/8455 [05:35<02:11, 23.43it/s]

Preprocessing:  64%|██████▎   | 5380/8455 [05:35<02:10, 23.54it/s]

Preprocessing:  64%|██████▎   | 5383/8455 [05:35<02:10, 23.56it/s]

Preprocessing:  64%|██████▎   | 5386/8455 [05:35<02:22, 21.51it/s]

Preprocessing:  64%|██████▎   | 5389/8455 [05:36<02:25, 21.06it/s]

Preprocessing:  64%|██████▍   | 5392/8455 [05:36<02:22, 21.52it/s]

Preprocessing:  64%|██████▍   | 5395/8455 [05:36<02:19, 21.89it/s]

Preprocessing:  64%|██████▍   | 5398/8455 [05:36<02:17, 22.22it/s]

Preprocessing:  64%|██████▍   | 5401/8455 [05:36<02:15, 22.58it/s]

Preprocessing:  64%|██████▍   | 5404/8455 [05:36<02:13, 22.86it/s]

Preprocessing:  64%|██████▍   | 5407/8455 [05:36<02:11, 23.13it/s]

Preprocessing:  64%|██████▍   | 5410/8455 [05:36<02:11, 23.16it/s]

Preprocessing:  64%|██████▍   | 5413/8455 [05:37<02:11, 23.20it/s]

Preprocessing:  64%|██████▍   | 5416/8455 [05:37<02:10, 23.26it/s]

Preprocessing:  64%|██████▍   | 5419/8455 [05:37<02:09, 23.44it/s]

Preprocessing:  64%|██████▍   | 5422/8455 [05:37<02:09, 23.44it/s]

Preprocessing:  64%|██████▍   | 5425/8455 [05:37<02:09, 23.48it/s]

Preprocessing:  64%|██████▍   | 5428/8455 [05:37<02:09, 23.46it/s]

Preprocessing:  64%|██████▍   | 5431/8455 [05:37<02:10, 23.23it/s]

Preprocessing:  64%|██████▍   | 5434/8455 [05:37<02:11, 23.02it/s]

Preprocessing:  64%|██████▍   | 5437/8455 [05:38<02:10, 23.17it/s]

Preprocessing:  64%|██████▍   | 5440/8455 [05:38<02:14, 22.44it/s]

Preprocessing:  64%|██████▍   | 5443/8455 [05:38<02:11, 22.97it/s]

Preprocessing:  64%|██████▍   | 5446/8455 [05:38<02:14, 22.32it/s]

Preprocessing:  64%|██████▍   | 5449/8455 [05:38<02:12, 22.71it/s]

Preprocessing:  64%|██████▍   | 5452/8455 [05:38<02:10, 22.95it/s]

Preprocessing:  65%|██████▍   | 5455/8455 [05:38<02:07, 23.45it/s]

Preprocessing:  65%|██████▍   | 5458/8455 [05:38<02:07, 23.52it/s]

Preprocessing:  65%|██████▍   | 5461/8455 [05:39<02:06, 23.58it/s]

Preprocessing:  65%|██████▍   | 5464/8455 [05:39<02:07, 23.52it/s]

Preprocessing:  65%|██████▍   | 5467/8455 [05:39<02:06, 23.66it/s]

Preprocessing:  65%|██████▍   | 5470/8455 [05:39<02:06, 23.68it/s]

Preprocessing:  65%|██████▍   | 5473/8455 [05:39<02:07, 23.47it/s]

Preprocessing:  65%|██████▍   | 5476/8455 [05:39<02:06, 23.54it/s]

Preprocessing:  65%|██████▍   | 5479/8455 [05:39<02:12, 22.47it/s]

Preprocessing:  65%|██████▍   | 5482/8455 [05:40<02:18, 21.51it/s]

Preprocessing:  65%|██████▍   | 5485/8455 [05:40<02:26, 20.33it/s]

Preprocessing:  65%|██████▍   | 5488/8455 [05:40<02:33, 19.29it/s]

Preprocessing:  65%|██████▍   | 5490/8455 [05:40<02:37, 18.78it/s]

Preprocessing:  65%|██████▍   | 5492/8455 [05:40<02:38, 18.72it/s]

Preprocessing:  65%|██████▍   | 5494/8455 [05:40<02:41, 18.38it/s]

Preprocessing:  65%|██████▌   | 5496/8455 [05:40<02:55, 16.87it/s]

Preprocessing:  65%|██████▌   | 5498/8455 [05:40<02:51, 17.29it/s]

Preprocessing:  65%|██████▌   | 5500/8455 [05:41<02:48, 17.53it/s]

Preprocessing:  65%|██████▌   | 5502/8455 [05:41<02:43, 18.01it/s]

Preprocessing:  65%|██████▌   | 5504/8455 [05:41<02:40, 18.36it/s]

Preprocessing:  65%|██████▌   | 5506/8455 [05:41<02:39, 18.44it/s]

Preprocessing:  65%|██████▌   | 5508/8455 [05:41<02:36, 18.85it/s]

Preprocessing:  65%|██████▌   | 5510/8455 [05:41<02:45, 17.80it/s]

Preprocessing:  65%|██████▌   | 5513/8455 [05:41<02:38, 18.51it/s]

Preprocessing:  65%|██████▌   | 5515/8455 [05:41<02:43, 17.98it/s]

Preprocessing:  65%|██████▌   | 5517/8455 [05:42<02:41, 18.21it/s]

Preprocessing:  65%|██████▌   | 5519/8455 [05:42<02:40, 18.30it/s]

Preprocessing:  65%|██████▌   | 5521/8455 [05:42<02:39, 18.43it/s]

Preprocessing:  65%|██████▌   | 5523/8455 [05:42<02:42, 17.99it/s]

Preprocessing:  65%|██████▌   | 5525/8455 [05:42<02:38, 18.43it/s]

Preprocessing:  65%|██████▌   | 5527/8455 [05:42<02:37, 18.65it/s]

Preprocessing:  65%|██████▌   | 5529/8455 [05:42<02:36, 18.69it/s]

Preprocessing:  65%|██████▌   | 5531/8455 [05:42<02:35, 18.86it/s]

Preprocessing:  65%|██████▌   | 5533/8455 [05:42<02:36, 18.63it/s]

Preprocessing:  65%|██████▌   | 5535/8455 [05:42<02:35, 18.76it/s]

Preprocessing:  65%|██████▌   | 5537/8455 [05:43<02:37, 18.49it/s]

Preprocessing:  66%|██████▌   | 5539/8455 [05:43<02:38, 18.39it/s]

Preprocessing:  66%|██████▌   | 5541/8455 [05:43<02:35, 18.68it/s]

Preprocessing:  66%|██████▌   | 5543/8455 [05:43<02:35, 18.76it/s]

Preprocessing:  66%|██████▌   | 5545/8455 [05:43<02:38, 18.36it/s]

Preprocessing:  66%|██████▌   | 5547/8455 [05:43<02:34, 18.77it/s]

Preprocessing:  66%|██████▌   | 5550/8455 [05:43<02:32, 19.02it/s]

Preprocessing:  66%|██████▌   | 5553/8455 [05:43<02:27, 19.63it/s]

Preprocessing:  66%|██████▌   | 5555/8455 [05:44<02:37, 18.44it/s]

Preprocessing:  66%|██████▌   | 5557/8455 [05:44<02:35, 18.67it/s]

Preprocessing:  66%|██████▌   | 5560/8455 [05:44<02:32, 18.93it/s]

Preprocessing:  66%|██████▌   | 5562/8455 [05:44<02:36, 18.53it/s]

Preprocessing:  66%|██████▌   | 5565/8455 [05:44<02:31, 19.06it/s]

Preprocessing:  66%|██████▌   | 5567/8455 [05:44<02:30, 19.13it/s]

Preprocessing:  66%|██████▌   | 5570/8455 [05:44<02:19, 20.66it/s]

Preprocessing:  66%|██████▌   | 5573/8455 [05:44<02:13, 21.60it/s]

Preprocessing:  66%|██████▌   | 5576/8455 [05:45<02:09, 22.18it/s]

Preprocessing:  66%|██████▌   | 5579/8455 [05:45<02:06, 22.75it/s]

Preprocessing:  66%|██████▌   | 5582/8455 [05:45<02:07, 22.47it/s]

Preprocessing:  66%|██████▌   | 5585/8455 [05:45<02:06, 22.76it/s]

Preprocessing:  66%|██████▌   | 5588/8455 [05:45<02:04, 23.10it/s]

Preprocessing:  66%|██████▌   | 5591/8455 [05:45<02:02, 23.35it/s]

Preprocessing:  66%|██████▌   | 5594/8455 [05:45<02:02, 23.42it/s]

Preprocessing:  66%|██████▌   | 5597/8455 [05:45<02:01, 23.48it/s]

Preprocessing:  66%|██████▌   | 5600/8455 [05:46<02:01, 23.49it/s]

Preprocessing:  66%|██████▋   | 5603/8455 [05:46<02:02, 23.23it/s]

Preprocessing:  66%|██████▋   | 5606/8455 [05:46<02:03, 23.15it/s]

Preprocessing:  66%|██████▋   | 5609/8455 [05:46<02:02, 23.31it/s]

Preprocessing:  66%|██████▋   | 5612/8455 [05:46<02:01, 23.44it/s]

Preprocessing:  66%|██████▋   | 5615/8455 [05:46<02:17, 20.59it/s]

Preprocessing:  66%|██████▋   | 5618/8455 [05:46<02:19, 20.31it/s]

Preprocessing:  66%|██████▋   | 5621/8455 [05:47<02:13, 21.26it/s]

Preprocessing:  67%|██████▋   | 5624/8455 [05:47<02:09, 21.86it/s]

Preprocessing:  67%|██████▋   | 5627/8455 [05:47<02:07, 22.11it/s]

Preprocessing:  67%|██████▋   | 5630/8455 [05:47<02:08, 21.92it/s]

Preprocessing:  67%|██████▋   | 5633/8455 [05:47<02:07, 22.16it/s]

Preprocessing:  67%|██████▋   | 5636/8455 [05:47<02:04, 22.56it/s]

Preprocessing:  67%|██████▋   | 5639/8455 [05:47<02:02, 22.95it/s]

Preprocessing:  67%|██████▋   | 5642/8455 [05:47<02:00, 23.27it/s]

Preprocessing:  67%|██████▋   | 5645/8455 [05:48<01:59, 23.50it/s]

Preprocessing:  67%|██████▋   | 5648/8455 [05:48<02:00, 23.24it/s]

Preprocessing:  67%|██████▋   | 5651/8455 [05:48<02:00, 23.35it/s]

Preprocessing:  67%|██████▋   | 5654/8455 [05:48<02:00, 23.29it/s]

Preprocessing:  67%|██████▋   | 5657/8455 [05:48<01:58, 23.53it/s]

Preprocessing:  67%|██████▋   | 5660/8455 [05:48<01:57, 23.75it/s]

Preprocessing:  67%|██████▋   | 5663/8455 [05:48<01:57, 23.71it/s]

Preprocessing:  67%|██████▋   | 5666/8455 [05:48<01:57, 23.71it/s]

Preprocessing:  67%|██████▋   | 5669/8455 [05:49<01:57, 23.80it/s]

Preprocessing:  67%|██████▋   | 5672/8455 [05:49<01:58, 23.49it/s]

Preprocessing:  67%|██████▋   | 5675/8455 [05:49<01:57, 23.63it/s]

Preprocessing:  67%|██████▋   | 5678/8455 [05:49<01:57, 23.62it/s]

Preprocessing:  67%|██████▋   | 5681/8455 [05:49<02:00, 23.11it/s]

Preprocessing:  67%|██████▋   | 5684/8455 [05:49<01:59, 23.19it/s]

Preprocessing:  67%|██████▋   | 5687/8455 [05:49<01:58, 23.43it/s]

Preprocessing:  67%|██████▋   | 5690/8455 [05:50<01:57, 23.56it/s]

Preprocessing:  67%|██████▋   | 5693/8455 [05:50<01:56, 23.80it/s]

Preprocessing:  67%|██████▋   | 5696/8455 [05:50<01:57, 23.49it/s]

Preprocessing:  67%|██████▋   | 5699/8455 [05:50<01:56, 23.62it/s]

Preprocessing:  67%|██████▋   | 5702/8455 [05:50<01:57, 23.38it/s]

Preprocessing:  67%|██████▋   | 5705/8455 [05:50<01:56, 23.66it/s]

Preprocessing:  68%|██████▊   | 5708/8455 [05:50<01:55, 23.86it/s]

Preprocessing:  68%|██████▊   | 5711/8455 [05:50<01:56, 23.63it/s]

Preprocessing:  68%|██████▊   | 5714/8455 [05:51<01:56, 23.56it/s]

Preprocessing:  68%|██████▊   | 5717/8455 [05:51<01:55, 23.71it/s]

Preprocessing:  68%|██████▊   | 5720/8455 [05:51<01:57, 23.35it/s]

Preprocessing:  68%|██████▊   | 5723/8455 [05:51<01:55, 23.61it/s]

Preprocessing:  68%|██████▊   | 5726/8455 [05:51<01:56, 23.45it/s]

Preprocessing:  68%|██████▊   | 5729/8455 [05:51<01:55, 23.61it/s]

Preprocessing:  68%|██████▊   | 5732/8455 [05:51<01:54, 23.75it/s]

Preprocessing:  68%|██████▊   | 5735/8455 [05:51<01:54, 23.69it/s]

Preprocessing:  68%|██████▊   | 5738/8455 [05:52<01:54, 23.77it/s]

Preprocessing:  68%|██████▊   | 5741/8455 [05:52<01:53, 23.85it/s]

Preprocessing:  68%|██████▊   | 5744/8455 [05:52<01:54, 23.59it/s]

Preprocessing:  68%|██████▊   | 5747/8455 [05:52<01:53, 23.92it/s]

Preprocessing:  68%|██████▊   | 5750/8455 [05:52<01:53, 23.93it/s]

Preprocessing:  68%|██████▊   | 5753/8455 [05:52<01:54, 23.62it/s]

Preprocessing:  68%|██████▊   | 5756/8455 [05:52<01:54, 23.62it/s]

Preprocessing:  68%|██████▊   | 5759/8455 [05:52<01:53, 23.66it/s]

Preprocessing:  68%|██████▊   | 5762/8455 [05:53<01:53, 23.74it/s]

Preprocessing:  68%|██████▊   | 5765/8455 [05:53<01:52, 23.81it/s]

Preprocessing:  68%|██████▊   | 5768/8455 [05:53<01:55, 23.24it/s]

Preprocessing:  68%|██████▊   | 5771/8455 [05:53<01:54, 23.38it/s]

Preprocessing:  68%|██████▊   | 5774/8455 [05:53<01:53, 23.53it/s]

Preprocessing:  68%|██████▊   | 5777/8455 [05:53<01:52, 23.84it/s]

Preprocessing:  68%|██████▊   | 5780/8455 [05:53<01:52, 23.76it/s]

Preprocessing:  68%|██████▊   | 5783/8455 [05:53<01:52, 23.83it/s]

Preprocessing:  68%|██████▊   | 5786/8455 [05:54<01:52, 23.73it/s]

Preprocessing:  68%|██████▊   | 5789/8455 [05:54<01:53, 23.53it/s]

Preprocessing:  69%|██████▊   | 5792/8455 [05:54<01:53, 23.42it/s]

Preprocessing:  69%|██████▊   | 5795/8455 [05:54<01:53, 23.50it/s]

Preprocessing:  69%|██████▊   | 5798/8455 [05:54<01:52, 23.53it/s]

Preprocessing:  69%|██████▊   | 5801/8455 [05:54<01:52, 23.66it/s]

Preprocessing:  69%|██████▊   | 5804/8455 [05:54<01:51, 23.80it/s]

Preprocessing:  69%|██████▊   | 5807/8455 [05:54<01:51, 23.84it/s]

Preprocessing:  69%|██████▊   | 5810/8455 [05:55<01:50, 23.93it/s]

Preprocessing:  69%|██████▉   | 5813/8455 [05:55<01:51, 23.78it/s]

Preprocessing:  69%|██████▉   | 5816/8455 [05:55<01:51, 23.68it/s]

Preprocessing:  69%|██████▉   | 5819/8455 [05:55<01:51, 23.72it/s]

Preprocessing:  69%|██████▉   | 5822/8455 [05:55<01:51, 23.65it/s]

Preprocessing:  69%|██████▉   | 5825/8455 [05:55<01:51, 23.68it/s]

Preprocessing:  69%|██████▉   | 5828/8455 [05:55<01:50, 23.80it/s]

Preprocessing:  69%|██████▉   | 5831/8455 [05:55<01:50, 23.70it/s]

Preprocessing:  69%|██████▉   | 5834/8455 [05:56<01:50, 23.66it/s]

Preprocessing:  69%|██████▉   | 5837/8455 [05:56<01:51, 23.55it/s]

Preprocessing:  69%|██████▉   | 5840/8455 [05:56<01:51, 23.45it/s]

Preprocessing:  69%|██████▉   | 5843/8455 [05:56<01:50, 23.56it/s]

Preprocessing:  69%|██████▉   | 5846/8455 [05:56<01:51, 23.43it/s]

Preprocessing:  69%|██████▉   | 5849/8455 [05:56<01:50, 23.59it/s]

Preprocessing:  69%|██████▉   | 5852/8455 [05:56<01:51, 23.37it/s]

Preprocessing:  69%|██████▉   | 5855/8455 [05:56<01:50, 23.43it/s]

Preprocessing:  69%|██████▉   | 5858/8455 [05:57<01:50, 23.56it/s]

Preprocessing:  69%|██████▉   | 5861/8455 [05:57<01:50, 23.44it/s]

Preprocessing:  69%|██████▉   | 5864/8455 [05:57<01:50, 23.51it/s]

Preprocessing:  69%|██████▉   | 5867/8455 [05:57<01:49, 23.63it/s]

Preprocessing:  69%|██████▉   | 5870/8455 [05:57<01:48, 23.78it/s]

Preprocessing:  69%|██████▉   | 5873/8455 [05:57<01:48, 23.73it/s]

Preprocessing:  69%|██████▉   | 5876/8455 [05:57<01:48, 23.85it/s]

Preprocessing:  70%|██████▉   | 5879/8455 [05:58<01:48, 23.83it/s]

Preprocessing:  70%|██████▉   | 5882/8455 [05:58<01:47, 23.89it/s]

Preprocessing:  70%|██████▉   | 5885/8455 [05:58<01:48, 23.71it/s]

Preprocessing:  70%|██████▉   | 5888/8455 [05:58<01:48, 23.67it/s]

Preprocessing:  70%|██████▉   | 5891/8455 [05:58<01:46, 24.01it/s]

Preprocessing:  70%|██████▉   | 5894/8455 [05:58<01:45, 24.17it/s]

Preprocessing:  70%|██████▉   | 5897/8455 [05:58<01:45, 24.22it/s]

Preprocessing:  70%|██████▉   | 5900/8455 [05:58<01:46, 24.05it/s]

Preprocessing:  70%|██████▉   | 5903/8455 [05:59<01:45, 24.12it/s]

Preprocessing:  70%|██████▉   | 5906/8455 [05:59<01:46, 23.83it/s]

Preprocessing:  70%|██████▉   | 5909/8455 [05:59<01:49, 23.35it/s]

Preprocessing:  70%|██████▉   | 5912/8455 [05:59<01:47, 23.68it/s]

Preprocessing:  70%|██████▉   | 5915/8455 [05:59<01:45, 24.05it/s]

Preprocessing:  70%|██████▉   | 5918/8455 [05:59<01:44, 24.33it/s]

Preprocessing:  70%|███████   | 5921/8455 [05:59<01:43, 24.53it/s]

Preprocessing:  70%|███████   | 5924/8455 [05:59<01:45, 24.09it/s]

Preprocessing:  70%|███████   | 5927/8455 [06:00<01:45, 24.06it/s]

Preprocessing:  70%|███████   | 5930/8455 [06:00<01:45, 24.02it/s]

Preprocessing:  70%|███████   | 5933/8455 [06:00<01:46, 23.74it/s]

Preprocessing:  70%|███████   | 5936/8455 [06:00<01:45, 23.92it/s]

Preprocessing:  70%|███████   | 5939/8455 [06:00<01:44, 24.11it/s]

Preprocessing:  70%|███████   | 5942/8455 [06:00<01:45, 23.85it/s]

Preprocessing:  70%|███████   | 5945/8455 [06:00<01:52, 22.27it/s]

Preprocessing:  70%|███████   | 5948/8455 [06:00<01:52, 22.31it/s]

Preprocessing:  70%|███████   | 5951/8455 [06:01<01:50, 22.63it/s]

Preprocessing:  70%|███████   | 5954/8455 [06:01<01:50, 22.70it/s]

Preprocessing:  70%|███████   | 5957/8455 [06:01<01:48, 22.99it/s]

Preprocessing:  70%|███████   | 5960/8455 [06:01<01:50, 22.68it/s]

Preprocessing:  71%|███████   | 5963/8455 [06:01<01:52, 22.17it/s]

Preprocessing:  71%|███████   | 5966/8455 [06:01<01:53, 21.98it/s]

Preprocessing:  71%|███████   | 5969/8455 [06:01<01:54, 21.62it/s]

Preprocessing:  71%|███████   | 5972/8455 [06:02<01:53, 21.90it/s]

Preprocessing:  71%|███████   | 5975/8455 [06:02<01:52, 22.08it/s]

Preprocessing:  71%|███████   | 5978/8455 [06:02<01:53, 21.90it/s]

Preprocessing:  71%|███████   | 5981/8455 [06:02<01:50, 22.47it/s]

Preprocessing:  71%|███████   | 5984/8455 [06:02<01:52, 21.99it/s]

Preprocessing:  71%|███████   | 5987/8455 [06:02<01:50, 22.39it/s]

Preprocessing:  71%|███████   | 5990/8455 [06:02<01:49, 22.52it/s]

Preprocessing:  71%|███████   | 5993/8455 [06:02<01:48, 22.74it/s]

Preprocessing:  71%|███████   | 5996/8455 [06:03<01:47, 22.83it/s]

Preprocessing:  71%|███████   | 5999/8455 [06:03<01:47, 22.80it/s]

Preprocessing:  71%|███████   | 6002/8455 [06:03<01:46, 23.00it/s]

Preprocessing:  71%|███████   | 6005/8455 [06:03<01:45, 23.15it/s]

Preprocessing:  71%|███████   | 6008/8455 [06:03<01:45, 23.09it/s]

Preprocessing:  71%|███████   | 6011/8455 [06:03<01:47, 22.71it/s]

Preprocessing:  71%|███████   | 6014/8455 [06:03<01:46, 22.89it/s]

Preprocessing:  71%|███████   | 6017/8455 [06:03<01:45, 23.20it/s]

Preprocessing:  71%|███████   | 6020/8455 [06:04<01:46, 22.85it/s]

Preprocessing:  71%|███████   | 6023/8455 [06:04<01:46, 22.79it/s]

Preprocessing:  71%|███████▏  | 6026/8455 [06:04<01:47, 22.57it/s]

Preprocessing:  71%|███████▏  | 6029/8455 [06:04<01:47, 22.63it/s]

Preprocessing:  71%|███████▏  | 6032/8455 [06:04<01:45, 22.99it/s]

Preprocessing:  71%|███████▏  | 6035/8455 [06:04<01:46, 22.72it/s]

Preprocessing:  71%|███████▏  | 6038/8455 [06:04<01:46, 22.70it/s]

Preprocessing:  71%|███████▏  | 6041/8455 [06:05<01:47, 22.47it/s]

Preprocessing:  71%|███████▏  | 6044/8455 [06:05<01:46, 22.56it/s]

Preprocessing:  72%|███████▏  | 6047/8455 [06:05<01:47, 22.47it/s]

Preprocessing:  72%|███████▏  | 6050/8455 [06:05<01:46, 22.66it/s]

Preprocessing:  72%|███████▏  | 6053/8455 [06:05<01:44, 23.03it/s]

Preprocessing:  72%|███████▏  | 6056/8455 [06:05<01:43, 23.17it/s]

Preprocessing:  72%|███████▏  | 6059/8455 [06:05<01:42, 23.29it/s]

Preprocessing:  72%|███████▏  | 6062/8455 [06:05<01:44, 22.95it/s]

Preprocessing:  72%|███████▏  | 6065/8455 [06:06<01:45, 22.67it/s]

Preprocessing:  72%|███████▏  | 6068/8455 [06:06<01:44, 22.79it/s]

Preprocessing:  72%|███████▏  | 6071/8455 [06:06<01:44, 22.78it/s]

Preprocessing:  72%|███████▏  | 6074/8455 [06:06<01:43, 23.07it/s]

Preprocessing:  72%|███████▏  | 6077/8455 [06:06<01:43, 22.89it/s]

Preprocessing:  72%|███████▏  | 6080/8455 [06:06<01:43, 22.93it/s]

Preprocessing:  72%|███████▏  | 6083/8455 [06:06<01:43, 22.88it/s]

Preprocessing:  72%|███████▏  | 6086/8455 [06:07<01:45, 22.52it/s]

Preprocessing:  72%|███████▏  | 6089/8455 [06:07<01:44, 22.58it/s]

Preprocessing:  72%|███████▏  | 6092/8455 [06:07<01:45, 22.32it/s]

Preprocessing:  72%|███████▏  | 6095/8455 [06:07<01:45, 22.27it/s]

Preprocessing:  72%|███████▏  | 6098/8455 [06:07<01:45, 22.33it/s]

Preprocessing:  72%|███████▏  | 6101/8455 [06:07<01:44, 22.54it/s]

Preprocessing:  72%|███████▏  | 6104/8455 [06:07<01:43, 22.64it/s]

Preprocessing:  72%|███████▏  | 6107/8455 [06:07<01:44, 22.51it/s]

Preprocessing:  72%|███████▏  | 6110/8455 [06:08<01:52, 20.78it/s]

Preprocessing:  72%|███████▏  | 6113/8455 [06:08<02:02, 19.05it/s]

Preprocessing:  72%|███████▏  | 6116/8455 [06:08<01:56, 20.05it/s]

Preprocessing:  72%|███████▏  | 6119/8455 [06:08<01:51, 20.90it/s]

Preprocessing:  72%|███████▏  | 6122/8455 [06:08<01:47, 21.60it/s]

Preprocessing:  72%|███████▏  | 6125/8455 [06:08<01:46, 21.95it/s]

Preprocessing:  72%|███████▏  | 6128/8455 [06:08<01:45, 22.15it/s]

Preprocessing:  73%|███████▎  | 6131/8455 [06:09<01:43, 22.53it/s]

Preprocessing:  73%|███████▎  | 6134/8455 [06:09<01:41, 22.82it/s]

Preprocessing:  73%|███████▎  | 6137/8455 [06:09<01:41, 22.79it/s]

Preprocessing:  73%|███████▎  | 6140/8455 [06:09<01:41, 22.78it/s]

Preprocessing:  73%|███████▎  | 6143/8455 [06:09<01:40, 23.04it/s]

Preprocessing:  73%|███████▎  | 6146/8455 [06:09<01:40, 23.06it/s]

Preprocessing:  73%|███████▎  | 6149/8455 [06:09<01:39, 23.17it/s]

Preprocessing:  73%|███████▎  | 6152/8455 [06:09<01:40, 23.02it/s]

Preprocessing:  73%|███████▎  | 6155/8455 [06:10<01:40, 22.94it/s]

Preprocessing:  73%|███████▎  | 6158/8455 [06:10<01:40, 22.86it/s]

Preprocessing:  73%|███████▎  | 6161/8455 [06:10<01:40, 22.94it/s]

Preprocessing:  73%|███████▎  | 6164/8455 [06:10<01:40, 22.79it/s]

Preprocessing:  73%|███████▎  | 6167/8455 [06:10<01:40, 22.79it/s]

Preprocessing:  73%|███████▎  | 6170/8455 [06:10<01:39, 22.96it/s]

Preprocessing:  73%|███████▎  | 6173/8455 [06:10<01:37, 23.45it/s]

Preprocessing:  73%|███████▎  | 6176/8455 [06:11<01:39, 22.83it/s]

Preprocessing:  73%|███████▎  | 6179/8455 [06:11<01:39, 22.82it/s]

Preprocessing:  73%|███████▎  | 6182/8455 [06:11<01:40, 22.69it/s]

Preprocessing:  73%|███████▎  | 6185/8455 [06:11<01:39, 22.78it/s]

Preprocessing:  73%|███████▎  | 6188/8455 [06:11<01:40, 22.65it/s]

Preprocessing:  73%|███████▎  | 6191/8455 [06:11<01:39, 22.73it/s]

Preprocessing:  73%|███████▎  | 6194/8455 [06:11<01:38, 23.07it/s]

Preprocessing:  73%|███████▎  | 6197/8455 [06:11<01:38, 22.95it/s]

Preprocessing:  73%|███████▎  | 6200/8455 [06:12<01:38, 22.96it/s]

Preprocessing:  73%|███████▎  | 6203/8455 [06:12<01:38, 22.87it/s]

Preprocessing:  73%|███████▎  | 6206/8455 [06:12<01:39, 22.57it/s]

Preprocessing:  73%|███████▎  | 6209/8455 [06:12<01:37, 23.07it/s]

Preprocessing:  73%|███████▎  | 6212/8455 [06:12<01:35, 23.41it/s]

Preprocessing:  74%|███████▎  | 6215/8455 [06:12<01:36, 23.28it/s]

Preprocessing:  74%|███████▎  | 6218/8455 [06:12<01:36, 23.13it/s]

Preprocessing:  74%|███████▎  | 6221/8455 [06:12<01:35, 23.28it/s]

Preprocessing:  74%|███████▎  | 6224/8455 [06:13<01:34, 23.56it/s]

Preprocessing:  74%|███████▎  | 6227/8455 [06:13<01:36, 23.11it/s]

Preprocessing:  74%|███████▎  | 6230/8455 [06:13<01:37, 22.86it/s]

Preprocessing:  74%|███████▎  | 6233/8455 [06:13<01:36, 23.14it/s]

Preprocessing:  74%|███████▍  | 6236/8455 [06:13<01:35, 23.36it/s]

Preprocessing:  74%|███████▍  | 6239/8455 [06:13<01:34, 23.35it/s]

Preprocessing:  74%|███████▍  | 6242/8455 [06:13<01:36, 22.87it/s]

Preprocessing:  74%|███████▍  | 6245/8455 [06:14<01:36, 23.01it/s]

Preprocessing:  74%|███████▍  | 6248/8455 [06:14<01:34, 23.36it/s]

Preprocessing:  74%|███████▍  | 6251/8455 [06:14<01:34, 23.24it/s]

Preprocessing:  74%|███████▍  | 6254/8455 [06:14<01:35, 23.03it/s]

Preprocessing:  74%|███████▍  | 6257/8455 [06:14<01:34, 23.22it/s]

Preprocessing:  74%|███████▍  | 6260/8455 [06:14<01:34, 23.33it/s]

Preprocessing:  74%|███████▍  | 6263/8455 [06:14<01:33, 23.50it/s]

Preprocessing:  74%|███████▍  | 6266/8455 [06:14<01:32, 23.64it/s]

Preprocessing:  74%|███████▍  | 6269/8455 [06:15<01:32, 23.61it/s]

Preprocessing:  74%|███████▍  | 6272/8455 [06:15<01:33, 23.35it/s]

Preprocessing:  74%|███████▍  | 6275/8455 [06:15<01:34, 23.00it/s]

Preprocessing:  74%|███████▍  | 6278/8455 [06:15<01:32, 23.53it/s]

Preprocessing:  74%|███████▍  | 6281/8455 [06:15<01:33, 23.15it/s]

Preprocessing:  74%|███████▍  | 6284/8455 [06:15<01:33, 23.32it/s]

Preprocessing:  74%|███████▍  | 6287/8455 [06:15<01:32, 23.46it/s]

Preprocessing:  74%|███████▍  | 6290/8455 [06:15<01:32, 23.35it/s]

Preprocessing:  74%|███████▍  | 6293/8455 [06:16<01:33, 23.25it/s]

Preprocessing:  74%|███████▍  | 6296/8455 [06:16<01:32, 23.40it/s]

Preprocessing:  75%|███████▍  | 6299/8455 [06:16<01:32, 23.30it/s]

Preprocessing:  75%|███████▍  | 6302/8455 [06:16<01:31, 23.49it/s]

Preprocessing:  75%|███████▍  | 6305/8455 [06:16<01:31, 23.61it/s]

Preprocessing:  75%|███████▍  | 6308/8455 [06:16<01:33, 23.08it/s]

Preprocessing:  75%|███████▍  | 6311/8455 [06:16<01:32, 23.22it/s]

Preprocessing:  75%|███████▍  | 6314/8455 [06:16<01:31, 23.44it/s]

Preprocessing:  75%|███████▍  | 6317/8455 [06:17<01:31, 23.49it/s]

Preprocessing:  75%|███████▍  | 6320/8455 [06:17<01:30, 23.56it/s]

Preprocessing:  75%|███████▍  | 6323/8455 [06:17<01:31, 23.41it/s]

Preprocessing:  75%|███████▍  | 6326/8455 [06:17<01:31, 23.32it/s]

Preprocessing:  75%|███████▍  | 6329/8455 [06:17<01:31, 23.24it/s]

Preprocessing:  75%|███████▍  | 6332/8455 [06:17<01:30, 23.54it/s]

Preprocessing:  75%|███████▍  | 6335/8455 [06:17<01:30, 23.30it/s]

Preprocessing:  75%|███████▍  | 6338/8455 [06:18<01:31, 23.21it/s]

Preprocessing:  75%|███████▍  | 6341/8455 [06:18<01:30, 23.33it/s]

Preprocessing:  75%|███████▌  | 6344/8455 [06:18<01:30, 23.41it/s]

Preprocessing:  75%|███████▌  | 6347/8455 [06:18<01:30, 23.20it/s]

Preprocessing:  75%|███████▌  | 6350/8455 [06:18<01:30, 23.16it/s]

Preprocessing:  75%|███████▌  | 6353/8455 [06:18<01:29, 23.37it/s]

Preprocessing:  75%|███████▌  | 6356/8455 [06:18<01:30, 23.24it/s]

Preprocessing:  75%|███████▌  | 6359/8455 [06:18<01:29, 23.49it/s]

Preprocessing:  75%|███████▌  | 6362/8455 [06:19<01:30, 23.14it/s]

Preprocessing:  75%|███████▌  | 6365/8455 [06:19<01:29, 23.38it/s]

Preprocessing:  75%|███████▌  | 6368/8455 [06:19<01:30, 23.18it/s]

Preprocessing:  75%|███████▌  | 6371/8455 [06:19<01:30, 23.09it/s]

Preprocessing:  75%|███████▌  | 6374/8455 [06:19<01:30, 23.02it/s]

Preprocessing:  75%|███████▌  | 6377/8455 [06:19<01:29, 23.12it/s]

Preprocessing:  75%|███████▌  | 6380/8455 [06:19<01:29, 23.17it/s]

Preprocessing:  75%|███████▌  | 6383/8455 [06:19<01:30, 22.77it/s]

Preprocessing:  76%|███████▌  | 6386/8455 [06:20<01:30, 22.93it/s]

Preprocessing:  76%|███████▌  | 6389/8455 [06:20<01:28, 23.27it/s]

Preprocessing:  76%|███████▌  | 6392/8455 [06:20<01:28, 23.32it/s]

Preprocessing:  76%|███████▌  | 6395/8455 [06:20<01:27, 23.49it/s]

Preprocessing:  76%|███████▌  | 6398/8455 [06:20<01:29, 23.07it/s]

Preprocessing:  76%|███████▌  | 6401/8455 [06:20<01:28, 23.09it/s]

Preprocessing:  76%|███████▌  | 6404/8455 [06:20<01:30, 22.72it/s]

Preprocessing:  76%|███████▌  | 6407/8455 [06:20<01:29, 22.81it/s]

Preprocessing:  76%|███████▌  | 6410/8455 [06:21<01:29, 22.76it/s]

Preprocessing:  76%|███████▌  | 6413/8455 [06:21<01:29, 22.88it/s]

Preprocessing:  76%|███████▌  | 6416/8455 [06:21<01:28, 23.05it/s]

Preprocessing:  76%|███████▌  | 6419/8455 [06:21<01:27, 23.27it/s]

Preprocessing:  76%|███████▌  | 6422/8455 [06:21<01:28, 22.85it/s]

Preprocessing:  76%|███████▌  | 6425/8455 [06:21<01:28, 22.95it/s]

Preprocessing:  76%|███████▌  | 6428/8455 [06:21<01:28, 22.99it/s]

Preprocessing:  76%|███████▌  | 6431/8455 [06:22<01:28, 22.86it/s]

Preprocessing:  76%|███████▌  | 6434/8455 [06:22<01:27, 22.97it/s]

Preprocessing:  76%|███████▌  | 6437/8455 [06:22<01:26, 23.27it/s]

Preprocessing:  76%|███████▌  | 6440/8455 [06:22<01:28, 22.69it/s]

Preprocessing:  76%|███████▌  | 6443/8455 [06:22<01:28, 22.65it/s]

Preprocessing:  76%|███████▌  | 6446/8455 [06:22<01:28, 22.64it/s]

Preprocessing:  76%|███████▋  | 6449/8455 [06:22<01:28, 22.74it/s]

Preprocessing:  76%|███████▋  | 6452/8455 [06:22<01:27, 22.77it/s]

Preprocessing:  76%|███████▋  | 6455/8455 [06:23<01:27, 22.91it/s]

Preprocessing:  76%|███████▋  | 6458/8455 [06:23<01:28, 22.62it/s]

Preprocessing:  76%|███████▋  | 6461/8455 [06:23<01:27, 22.70it/s]

Preprocessing:  76%|███████▋  | 6464/8455 [06:23<01:26, 23.08it/s]

Preprocessing:  76%|███████▋  | 6467/8455 [06:23<01:25, 23.34it/s]

Preprocessing:  77%|███████▋  | 6470/8455 [06:23<01:24, 23.48it/s]

Preprocessing:  77%|███████▋  | 6473/8455 [06:23<01:27, 22.68it/s]

Preprocessing:  77%|███████▋  | 6476/8455 [06:24<01:25, 23.13it/s]

Preprocessing:  77%|███████▋  | 6479/8455 [06:24<01:25, 23.14it/s]

Preprocessing:  77%|███████▋  | 6482/8455 [06:24<01:26, 22.92it/s]

Preprocessing:  77%|███████▋  | 6485/8455 [06:24<01:29, 22.02it/s]

Preprocessing:  77%|███████▋  | 6488/8455 [06:24<01:27, 22.43it/s]

Preprocessing:  77%|███████▋  | 6491/8455 [06:24<01:26, 22.69it/s]

Preprocessing:  77%|███████▋  | 6494/8455 [06:24<01:27, 22.51it/s]

Preprocessing:  77%|███████▋  | 6497/8455 [06:24<01:34, 20.75it/s]

Preprocessing:  77%|███████▋  | 6500/8455 [06:25<01:30, 21.49it/s]

Preprocessing:  77%|███████▋  | 6503/8455 [06:25<01:30, 21.51it/s]

Preprocessing:  77%|███████▋  | 6506/8455 [06:25<01:29, 21.86it/s]

Preprocessing:  77%|███████▋  | 6509/8455 [06:25<01:27, 22.15it/s]

Preprocessing:  77%|███████▋  | 6512/8455 [06:25<01:27, 22.27it/s]

Preprocessing:  77%|███████▋  | 6515/8455 [06:25<01:30, 21.39it/s]

Preprocessing:  77%|███████▋  | 6518/8455 [06:25<01:31, 21.09it/s]

Preprocessing:  77%|███████▋  | 6521/8455 [06:26<01:37, 19.81it/s]

Preprocessing:  77%|███████▋  | 6524/8455 [06:26<01:44, 18.42it/s]

Preprocessing:  77%|███████▋  | 6526/8455 [06:26<01:47, 17.87it/s]

Preprocessing:  77%|███████▋  | 6528/8455 [06:26<01:51, 17.31it/s]

Preprocessing:  77%|███████▋  | 6530/8455 [06:26<01:55, 16.71it/s]

Preprocessing:  77%|███████▋  | 6532/8455 [06:26<01:54, 16.82it/s]

Preprocessing:  77%|███████▋  | 6534/8455 [06:26<01:52, 17.05it/s]

Preprocessing:  77%|███████▋  | 6536/8455 [06:27<01:51, 17.19it/s]

Preprocessing:  77%|███████▋  | 6538/8455 [06:27<01:51, 17.20it/s]

Preprocessing:  77%|███████▋  | 6540/8455 [06:27<01:53, 16.85it/s]

Preprocessing:  77%|███████▋  | 6542/8455 [06:27<01:53, 16.84it/s]

Preprocessing:  77%|███████▋  | 6544/8455 [06:27<01:52, 16.94it/s]

Preprocessing:  77%|███████▋  | 6546/8455 [06:27<01:54, 16.66it/s]

Preprocessing:  77%|███████▋  | 6548/8455 [06:27<01:53, 16.74it/s]

Preprocessing:  77%|███████▋  | 6550/8455 [06:27<01:50, 17.25it/s]

Preprocessing:  77%|███████▋  | 6552/8455 [06:27<01:50, 17.29it/s]

Preprocessing:  78%|███████▊  | 6554/8455 [06:28<01:49, 17.33it/s]

Preprocessing:  78%|███████▊  | 6556/8455 [06:28<01:49, 17.35it/s]

Preprocessing:  78%|███████▊  | 6558/8455 [06:28<01:50, 17.23it/s]

Preprocessing:  78%|███████▊  | 6561/8455 [06:28<01:40, 18.81it/s]

Preprocessing:  78%|███████▊  | 6564/8455 [06:28<01:33, 20.14it/s]

Preprocessing:  78%|███████▊  | 6567/8455 [06:28<01:31, 20.56it/s]

Preprocessing:  78%|███████▊  | 6570/8455 [06:28<01:28, 21.21it/s]

Preprocessing:  78%|███████▊  | 6573/8455 [06:29<01:28, 21.16it/s]

Preprocessing:  78%|███████▊  | 6576/8455 [06:29<01:25, 21.89it/s]

Preprocessing:  78%|███████▊  | 6579/8455 [06:29<01:23, 22.57it/s]

Preprocessing:  78%|███████▊  | 6582/8455 [06:29<01:23, 22.45it/s]

Preprocessing:  78%|███████▊  | 6585/8455 [06:29<01:22, 22.58it/s]

Preprocessing:  78%|███████▊  | 6588/8455 [06:29<01:24, 22.18it/s]

Preprocessing:  78%|███████▊  | 6591/8455 [06:29<01:35, 19.45it/s]

Preprocessing:  78%|███████▊  | 6594/8455 [06:29<01:31, 20.34it/s]

Preprocessing:  78%|███████▊  | 6597/8455 [06:30<01:28, 20.99it/s]

Preprocessing:  78%|███████▊  | 6600/8455 [06:30<01:26, 21.48it/s]

Preprocessing:  78%|███████▊  | 6603/8455 [06:30<01:23, 22.10it/s]

Preprocessing:  78%|███████▊  | 6606/8455 [06:30<01:21, 22.62it/s]

Preprocessing:  78%|███████▊  | 6609/8455 [06:30<01:20, 22.93it/s]

Preprocessing:  78%|███████▊  | 6612/8455 [06:30<01:20, 22.91it/s]

Preprocessing:  78%|███████▊  | 6615/8455 [06:30<01:19, 23.22it/s]

Preprocessing:  78%|███████▊  | 6618/8455 [06:31<01:19, 23.06it/s]

Preprocessing:  78%|███████▊  | 6621/8455 [06:31<01:19, 23.07it/s]

Preprocessing:  78%|███████▊  | 6624/8455 [06:31<01:19, 22.94it/s]

Preprocessing:  78%|███████▊  | 6627/8455 [06:31<01:18, 23.18it/s]

Preprocessing:  78%|███████▊  | 6630/8455 [06:31<01:18, 23.27it/s]

Preprocessing:  78%|███████▊  | 6633/8455 [06:31<01:18, 23.11it/s]

Preprocessing:  78%|███████▊  | 6636/8455 [06:31<01:19, 22.94it/s]

Preprocessing:  79%|███████▊  | 6639/8455 [06:31<01:18, 23.13it/s]

Preprocessing:  79%|███████▊  | 6642/8455 [06:32<01:19, 22.84it/s]

Preprocessing:  79%|███████▊  | 6645/8455 [06:32<01:19, 22.76it/s]

Preprocessing:  79%|███████▊  | 6648/8455 [06:32<01:19, 22.87it/s]

Preprocessing:  79%|███████▊  | 6651/8455 [06:32<01:18, 22.92it/s]

Preprocessing:  79%|███████▊  | 6654/8455 [06:32<01:18, 23.09it/s]

Preprocessing:  79%|███████▊  | 6657/8455 [06:32<01:17, 23.08it/s]

Preprocessing:  79%|███████▉  | 6660/8455 [06:32<01:18, 22.96it/s]

Preprocessing:  79%|███████▉  | 6663/8455 [06:32<01:18, 22.73it/s]

Preprocessing:  79%|███████▉  | 6666/8455 [06:33<01:17, 23.04it/s]

Preprocessing:  79%|███████▉  | 6669/8455 [06:33<01:18, 22.90it/s]

Preprocessing:  79%|███████▉  | 6672/8455 [06:33<01:16, 23.18it/s]

Preprocessing:  79%|███████▉  | 6675/8455 [06:33<01:16, 23.30it/s]

Preprocessing:  79%|███████▉  | 6678/8455 [06:33<01:20, 21.95it/s]

Preprocessing:  79%|███████▉  | 6681/8455 [06:33<01:22, 21.48it/s]

Preprocessing:  79%|███████▉  | 6684/8455 [06:33<01:23, 21.13it/s]

Preprocessing:  79%|███████▉  | 6687/8455 [06:34<01:21, 21.71it/s]

Preprocessing:  79%|███████▉  | 6690/8455 [06:34<01:20, 21.87it/s]

Preprocessing:  79%|███████▉  | 6693/8455 [06:34<01:19, 22.05it/s]

Preprocessing:  79%|███████▉  | 6696/8455 [06:34<01:18, 22.39it/s]

Preprocessing:  79%|███████▉  | 6699/8455 [06:34<01:17, 22.75it/s]

Preprocessing:  79%|███████▉  | 6702/8455 [06:34<01:17, 22.68it/s]

Preprocessing:  79%|███████▉  | 6705/8455 [06:34<01:15, 23.07it/s]

Preprocessing:  79%|███████▉  | 6708/8455 [06:34<01:15, 23.00it/s]

Preprocessing:  79%|███████▉  | 6711/8455 [06:35<01:14, 23.31it/s]

Preprocessing:  79%|███████▉  | 6714/8455 [06:35<01:14, 23.22it/s]

Preprocessing:  79%|███████▉  | 6717/8455 [06:35<01:14, 23.39it/s]

Preprocessing:  79%|███████▉  | 6720/8455 [06:35<01:15, 23.01it/s]

Preprocessing:  80%|███████▉  | 6723/8455 [06:35<01:14, 23.19it/s]

Preprocessing:  80%|███████▉  | 6726/8455 [06:35<01:15, 23.03it/s]

Preprocessing:  80%|███████▉  | 6729/8455 [06:35<01:15, 22.93it/s]

Preprocessing:  80%|███████▉  | 6732/8455 [06:36<01:15, 22.83it/s]

Preprocessing:  80%|███████▉  | 6735/8455 [06:36<01:15, 22.91it/s]

Preprocessing:  80%|███████▉  | 6738/8455 [06:36<01:15, 22.71it/s]

Preprocessing:  80%|███████▉  | 6741/8455 [06:36<01:16, 22.48it/s]

Preprocessing:  80%|███████▉  | 6744/8455 [06:36<01:21, 21.10it/s]

Preprocessing:  80%|███████▉  | 6747/8455 [06:36<01:22, 20.70it/s]

Preprocessing:  80%|███████▉  | 6750/8455 [06:36<01:19, 21.46it/s]

Preprocessing:  80%|███████▉  | 6753/8455 [06:37<01:17, 21.91it/s]

Preprocessing:  80%|███████▉  | 6756/8455 [06:37<01:16, 22.25it/s]

Preprocessing:  80%|███████▉  | 6759/8455 [06:37<01:14, 22.64it/s]

Preprocessing:  80%|███████▉  | 6762/8455 [06:37<01:14, 22.60it/s]

Preprocessing:  80%|████████  | 6765/8455 [06:37<01:17, 21.70it/s]

Preprocessing:  80%|████████  | 6768/8455 [06:37<01:18, 21.37it/s]

Preprocessing:  80%|████████  | 6771/8455 [06:37<01:19, 21.26it/s]

Preprocessing:  80%|████████  | 6774/8455 [06:38<01:33, 18.02it/s]

Preprocessing:  80%|████████  | 6776/8455 [06:38<01:38, 16.98it/s]

Preprocessing:  80%|████████  | 6778/8455 [06:38<01:41, 16.57it/s]

Preprocessing:  80%|████████  | 6780/8455 [06:38<01:40, 16.66it/s]

Preprocessing:  80%|████████  | 6782/8455 [06:38<01:41, 16.53it/s]

Preprocessing:  80%|████████  | 6784/8455 [06:38<01:39, 16.74it/s]

Preprocessing:  80%|████████  | 6787/8455 [06:38<01:27, 18.95it/s]

Preprocessing:  80%|████████  | 6790/8455 [06:38<01:19, 21.01it/s]

Preprocessing:  80%|████████  | 6793/8455 [06:39<01:13, 22.65it/s]

Preprocessing:  80%|████████  | 6796/8455 [06:39<01:10, 23.68it/s]

Preprocessing:  80%|████████  | 6799/8455 [06:39<01:05, 25.21it/s]

Preprocessing:  80%|████████  | 6802/8455 [06:39<01:03, 25.96it/s]

Preprocessing:  80%|████████  | 6805/8455 [06:39<01:03, 25.87it/s]

Preprocessing:  81%|████████  | 6808/8455 [06:39<01:08, 23.91it/s]

Preprocessing:  81%|████████  | 6811/8455 [06:39<01:07, 24.23it/s]

Preprocessing:  81%|████████  | 6814/8455 [06:39<01:04, 25.33it/s]

Preprocessing:  81%|████████  | 6817/8455 [06:39<01:04, 25.55it/s]

Preprocessing:  81%|████████  | 6820/8455 [06:40<01:02, 25.97it/s]

Preprocessing:  81%|████████  | 6823/8455 [06:40<01:02, 26.20it/s]

Preprocessing:  81%|████████  | 6826/8455 [06:40<01:00, 27.12it/s]

Preprocessing:  81%|████████  | 6829/8455 [06:40<01:00, 27.03it/s]

Preprocessing:  81%|████████  | 6832/8455 [06:40<00:59, 27.23it/s]

Preprocessing:  81%|████████  | 6835/8455 [06:40<00:59, 27.11it/s]

Preprocessing:  81%|████████  | 6838/8455 [06:40<00:59, 27.32it/s]

Preprocessing:  81%|████████  | 6841/8455 [06:40<00:58, 27.41it/s]

Preprocessing:  81%|████████  | 6844/8455 [06:40<00:58, 27.61it/s]

Preprocessing:  81%|████████  | 6847/8455 [06:41<00:59, 27.17it/s]

Preprocessing:  81%|████████  | 6850/8455 [06:41<01:13, 21.77it/s]

Preprocessing:  81%|████████  | 6853/8455 [06:41<01:25, 18.69it/s]

Preprocessing:  81%|████████  | 6856/8455 [06:41<01:19, 20.18it/s]

Preprocessing:  81%|████████  | 6859/8455 [06:41<01:12, 21.92it/s]

Preprocessing:  81%|████████  | 6862/8455 [06:41<01:07, 23.59it/s]

Preprocessing:  81%|████████  | 6865/8455 [06:41<01:06, 23.83it/s]

Preprocessing:  81%|████████  | 6868/8455 [06:42<01:04, 24.67it/s]

Preprocessing:  81%|████████▏ | 6871/8455 [06:42<01:02, 25.36it/s]

Preprocessing:  81%|████████▏ | 6874/8455 [06:42<01:01, 25.78it/s]

Preprocessing:  81%|████████▏ | 6877/8455 [06:42<01:00, 25.89it/s]

Preprocessing:  81%|████████▏ | 6880/8455 [06:42<01:02, 25.07it/s]

Preprocessing:  81%|████████▏ | 6883/8455 [06:42<01:01, 25.37it/s]

Preprocessing:  81%|████████▏ | 6886/8455 [06:42<01:02, 25.06it/s]

Preprocessing:  81%|████████▏ | 6889/8455 [06:42<01:01, 25.65it/s]

Preprocessing:  82%|████████▏ | 6892/8455 [06:42<01:00, 26.03it/s]

Preprocessing:  82%|████████▏ | 6895/8455 [06:43<00:57, 26.96it/s]

Preprocessing:  82%|████████▏ | 6898/8455 [06:43<00:57, 26.94it/s]

Preprocessing:  82%|████████▏ | 6901/8455 [06:43<00:57, 27.14it/s]

Preprocessing:  82%|████████▏ | 6904/8455 [06:43<00:58, 26.69it/s]

Preprocessing:  82%|████████▏ | 6907/8455 [06:43<01:01, 25.12it/s]

Preprocessing:  82%|████████▏ | 6910/8455 [06:43<01:12, 21.34it/s]

Preprocessing:  82%|████████▏ | 6913/8455 [06:43<01:13, 21.12it/s]

Preprocessing:  82%|████████▏ | 6916/8455 [06:44<01:11, 21.68it/s]

Preprocessing:  82%|████████▏ | 6919/8455 [06:44<01:09, 22.18it/s]

Preprocessing:  82%|████████▏ | 6922/8455 [06:44<01:07, 22.59it/s]

Preprocessing:  82%|████████▏ | 6925/8455 [06:44<01:08, 22.49it/s]

Preprocessing:  82%|████████▏ | 6928/8455 [06:44<01:08, 22.31it/s]

Preprocessing:  82%|████████▏ | 6931/8455 [06:44<01:07, 22.44it/s]

Preprocessing:  82%|████████▏ | 6934/8455 [06:44<01:07, 22.66it/s]

Preprocessing:  82%|████████▏ | 6937/8455 [06:44<01:07, 22.54it/s]

Preprocessing:  82%|████████▏ | 6940/8455 [06:45<01:07, 22.51it/s]

Preprocessing:  82%|████████▏ | 6943/8455 [06:45<01:07, 22.29it/s]

Preprocessing:  82%|████████▏ | 6946/8455 [06:45<01:07, 22.51it/s]

Preprocessing:  82%|████████▏ | 6949/8455 [06:45<01:07, 22.35it/s]

Preprocessing:  82%|████████▏ | 6952/8455 [06:45<01:07, 22.35it/s]

Preprocessing:  82%|████████▏ | 6955/8455 [06:45<01:06, 22.67it/s]

Preprocessing:  82%|████████▏ | 6958/8455 [06:45<01:07, 22.28it/s]

Preprocessing:  82%|████████▏ | 6961/8455 [06:46<01:06, 22.35it/s]

Preprocessing:  82%|████████▏ | 6964/8455 [06:46<01:06, 22.37it/s]

Preprocessing:  82%|████████▏ | 6967/8455 [06:46<01:05, 22.59it/s]

Preprocessing:  82%|████████▏ | 6970/8455 [06:46<01:05, 22.51it/s]

Preprocessing:  82%|████████▏ | 6973/8455 [06:46<01:13, 20.13it/s]

Preprocessing:  83%|████████▎ | 6976/8455 [06:46<01:20, 18.26it/s]

Preprocessing:  83%|████████▎ | 6979/8455 [06:46<01:18, 18.83it/s]

Preprocessing:  83%|████████▎ | 6982/8455 [06:47<01:17, 19.12it/s]

Preprocessing:  83%|████████▎ | 6985/8455 [06:47<01:13, 19.88it/s]

Preprocessing:  83%|████████▎ | 6988/8455 [06:47<01:10, 20.96it/s]

Preprocessing:  83%|████████▎ | 6991/8455 [06:47<01:07, 21.78it/s]

Preprocessing:  83%|████████▎ | 6994/8455 [06:47<01:05, 22.27it/s]

Preprocessing:  83%|████████▎ | 6997/8455 [06:47<01:05, 22.17it/s]

Preprocessing:  83%|████████▎ | 7000/8455 [06:47<01:05, 22.32it/s]

Preprocessing:  83%|████████▎ | 7003/8455 [06:48<01:05, 22.34it/s]

Preprocessing:  83%|████████▎ | 7006/8455 [06:48<01:03, 22.71it/s]

Preprocessing:  83%|████████▎ | 7009/8455 [06:48<01:02, 23.01it/s]

Preprocessing:  83%|████████▎ | 7012/8455 [06:48<01:01, 23.56it/s]

Preprocessing:  83%|████████▎ | 7015/8455 [06:48<01:02, 23.18it/s]

Preprocessing:  83%|████████▎ | 7018/8455 [06:48<01:01, 23.39it/s]

Preprocessing:  83%|████████▎ | 7021/8455 [06:48<01:04, 22.22it/s]

Preprocessing:  83%|████████▎ | 7024/8455 [06:49<01:15, 18.85it/s]

Preprocessing:  83%|████████▎ | 7027/8455 [06:49<01:11, 19.84it/s]

Preprocessing:  83%|████████▎ | 7030/8455 [06:49<01:08, 20.84it/s]

Preprocessing:  83%|████████▎ | 7033/8455 [06:49<01:06, 21.28it/s]

Preprocessing:  83%|████████▎ | 7036/8455 [06:49<01:05, 21.66it/s]

Preprocessing:  83%|████████▎ | 7039/8455 [06:49<01:04, 21.89it/s]

Preprocessing:  83%|████████▎ | 7042/8455 [06:49<01:04, 22.05it/s]

Preprocessing:  83%|████████▎ | 7045/8455 [06:49<01:03, 22.34it/s]

Preprocessing:  83%|████████▎ | 7048/8455 [06:50<01:02, 22.64it/s]

Preprocessing:  83%|████████▎ | 7051/8455 [06:50<01:01, 22.69it/s]

Preprocessing:  83%|████████▎ | 7054/8455 [06:50<01:00, 23.14it/s]

Preprocessing:  83%|████████▎ | 7057/8455 [06:50<01:01, 22.80it/s]

Preprocessing:  84%|████████▎ | 7060/8455 [06:50<01:00, 23.00it/s]

Preprocessing:  84%|████████▎ | 7063/8455 [06:50<01:00, 22.89it/s]

Preprocessing:  84%|████████▎ | 7066/8455 [06:50<01:02, 22.30it/s]

Preprocessing:  84%|████████▎ | 7069/8455 [06:50<01:01, 22.47it/s]

Preprocessing:  84%|████████▎ | 7072/8455 [06:51<01:01, 22.35it/s]

Preprocessing:  84%|████████▎ | 7075/8455 [06:51<01:02, 22.25it/s]

Preprocessing:  84%|████████▎ | 7078/8455 [06:51<01:00, 22.66it/s]

Preprocessing:  84%|████████▎ | 7081/8455 [06:51<00:59, 23.01it/s]

Preprocessing:  84%|████████▍ | 7084/8455 [06:51<00:59, 23.14it/s]

Preprocessing:  84%|████████▍ | 7087/8455 [06:51<01:00, 22.76it/s]

Preprocessing:  84%|████████▍ | 7090/8455 [06:51<00:59, 22.88it/s]

Preprocessing:  84%|████████▍ | 7093/8455 [06:52<00:59, 22.98it/s]

Preprocessing:  84%|████████▍ | 7096/8455 [06:52<00:58, 23.10it/s]

Preprocessing:  84%|████████▍ | 7099/8455 [06:52<00:58, 23.01it/s]

Preprocessing:  84%|████████▍ | 7102/8455 [06:52<01:00, 22.41it/s]

Preprocessing:  84%|████████▍ | 7105/8455 [06:52<01:01, 22.06it/s]

Preprocessing:  84%|████████▍ | 7108/8455 [06:52<01:00, 22.26it/s]

Preprocessing:  84%|████████▍ | 7111/8455 [06:52<00:59, 22.41it/s]

Preprocessing:  84%|████████▍ | 7114/8455 [06:52<00:59, 22.50it/s]

Preprocessing:  84%|████████▍ | 7117/8455 [06:53<00:59, 22.64it/s]

Preprocessing:  84%|████████▍ | 7120/8455 [06:53<00:58, 22.76it/s]

Preprocessing:  84%|████████▍ | 7123/8455 [06:53<00:58, 22.90it/s]

Preprocessing:  84%|████████▍ | 7126/8455 [06:53<00:58, 22.59it/s]

Preprocessing:  84%|████████▍ | 7129/8455 [06:53<01:01, 21.57it/s]

Preprocessing:  84%|████████▍ | 7132/8455 [06:53<01:01, 21.60it/s]

Preprocessing:  84%|████████▍ | 7135/8455 [06:53<01:01, 21.59it/s]

Preprocessing:  84%|████████▍ | 7138/8455 [06:54<01:00, 21.71it/s]

Preprocessing:  84%|████████▍ | 7141/8455 [06:54<01:01, 21.48it/s]

Preprocessing:  84%|████████▍ | 7144/8455 [06:54<01:00, 21.59it/s]

Preprocessing:  85%|████████▍ | 7147/8455 [06:54<00:59, 22.09it/s]

Preprocessing:  85%|████████▍ | 7150/8455 [06:54<00:58, 22.30it/s]

Preprocessing:  85%|████████▍ | 7153/8455 [06:54<00:57, 22.51it/s]

Preprocessing:  85%|████████▍ | 7156/8455 [06:54<00:56, 22.92it/s]

Preprocessing:  85%|████████▍ | 7159/8455 [06:54<00:56, 22.89it/s]

Preprocessing:  85%|████████▍ | 7162/8455 [06:55<00:56, 22.83it/s]

Preprocessing:  85%|████████▍ | 7165/8455 [06:55<00:56, 22.77it/s]

Preprocessing:  85%|████████▍ | 7168/8455 [06:55<00:55, 23.08it/s]

Preprocessing:  85%|████████▍ | 7171/8455 [06:55<00:55, 23.02it/s]

Preprocessing:  85%|████████▍ | 7174/8455 [06:55<00:55, 23.18it/s]

Preprocessing:  85%|████████▍ | 7177/8455 [06:55<00:55, 23.07it/s]

Preprocessing:  85%|████████▍ | 7180/8455 [06:55<00:55, 23.06it/s]

Preprocessing:  85%|████████▍ | 7183/8455 [06:56<00:54, 23.19it/s]

Preprocessing:  85%|████████▍ | 7186/8455 [06:56<00:55, 22.76it/s]

Preprocessing:  85%|████████▌ | 7189/8455 [06:56<00:55, 22.87it/s]

Preprocessing:  85%|████████▌ | 7192/8455 [06:56<00:54, 23.08it/s]

Preprocessing:  85%|████████▌ | 7195/8455 [06:56<00:54, 23.27it/s]

Preprocessing:  85%|████████▌ | 7198/8455 [06:56<00:54, 23.14it/s]

Preprocessing:  85%|████████▌ | 7201/8455 [06:56<00:53, 23.27it/s]

Preprocessing:  85%|████████▌ | 7204/8455 [06:56<00:54, 23.04it/s]

Preprocessing:  85%|████████▌ | 7207/8455 [06:57<00:57, 21.87it/s]

Preprocessing:  85%|████████▌ | 7210/8455 [06:57<01:02, 19.93it/s]

Preprocessing:  85%|████████▌ | 7213/8455 [06:57<01:00, 20.37it/s]

Preprocessing:  85%|████████▌ | 7216/8455 [06:57<00:59, 20.89it/s]

Preprocessing:  85%|████████▌ | 7219/8455 [06:57<00:57, 21.47it/s]

Preprocessing:  85%|████████▌ | 7222/8455 [06:57<00:56, 21.82it/s]

Preprocessing:  85%|████████▌ | 7225/8455 [06:57<00:58, 21.03it/s]

Preprocessing:  85%|████████▌ | 7228/8455 [06:58<00:56, 21.72it/s]

Preprocessing:  86%|████████▌ | 7231/8455 [06:58<00:55, 21.98it/s]

Preprocessing:  86%|████████▌ | 7234/8455 [06:58<00:53, 22.66it/s]

Preprocessing:  86%|████████▌ | 7237/8455 [06:58<00:53, 22.71it/s]

Preprocessing:  86%|████████▌ | 7240/8455 [06:58<00:54, 22.34it/s]

Preprocessing:  86%|████████▌ | 7243/8455 [06:58<00:56, 21.38it/s]

Preprocessing:  86%|████████▌ | 7246/8455 [06:58<00:59, 20.25it/s]

Preprocessing:  86%|████████▌ | 7249/8455 [06:59<00:57, 21.05it/s]

Preprocessing:  86%|████████▌ | 7252/8455 [06:59<00:56, 21.46it/s]

Preprocessing:  86%|████████▌ | 7255/8455 [06:59<00:54, 21.92it/s]

Preprocessing:  86%|████████▌ | 7258/8455 [06:59<00:52, 22.70it/s]

Preprocessing:  86%|████████▌ | 7261/8455 [06:59<00:52, 22.80it/s]

Preprocessing:  86%|████████▌ | 7264/8455 [06:59<00:52, 22.68it/s]

Preprocessing:  86%|████████▌ | 7267/8455 [06:59<00:52, 22.43it/s]

Preprocessing:  86%|████████▌ | 7270/8455 [06:59<00:52, 22.71it/s]

Preprocessing:  86%|████████▌ | 7273/8455 [07:00<00:51, 22.86it/s]

Preprocessing:  86%|████████▌ | 7276/8455 [07:00<00:51, 22.74it/s]

Preprocessing:  86%|████████▌ | 7279/8455 [07:00<00:51, 22.78it/s]

Preprocessing:  86%|████████▌ | 7282/8455 [07:00<00:50, 23.15it/s]

Preprocessing:  86%|████████▌ | 7285/8455 [07:00<00:50, 23.35it/s]

Preprocessing:  86%|████████▌ | 7288/8455 [07:00<00:50, 23.00it/s]

Preprocessing:  86%|████████▌ | 7291/8455 [07:00<00:50, 23.04it/s]

Preprocessing:  86%|████████▋ | 7294/8455 [07:01<00:53, 21.82it/s]

Preprocessing:  86%|████████▋ | 7297/8455 [07:01<00:56, 20.56it/s]

Preprocessing:  86%|████████▋ | 7300/8455 [07:01<00:54, 21.21it/s]

Preprocessing:  86%|████████▋ | 7303/8455 [07:01<00:52, 21.91it/s]

Preprocessing:  86%|████████▋ | 7306/8455 [07:01<00:51, 22.44it/s]

Preprocessing:  86%|████████▋ | 7309/8455 [07:01<00:50, 22.62it/s]

Preprocessing:  86%|████████▋ | 7312/8455 [07:01<00:49, 22.94it/s]

Preprocessing:  87%|████████▋ | 7315/8455 [07:01<00:50, 22.79it/s]

Preprocessing:  87%|████████▋ | 7318/8455 [07:02<00:49, 22.75it/s]

Preprocessing:  87%|████████▋ | 7321/8455 [07:02<00:50, 22.43it/s]

Preprocessing:  87%|████████▋ | 7324/8455 [07:02<00:50, 22.56it/s]

Preprocessing:  87%|████████▋ | 7327/8455 [07:02<00:49, 23.00it/s]

Preprocessing:  87%|████████▋ | 7330/8455 [07:02<00:51, 22.01it/s]

Preprocessing:  87%|████████▋ | 7333/8455 [07:02<00:54, 20.67it/s]

Preprocessing:  87%|████████▋ | 7336/8455 [07:02<00:53, 20.78it/s]

Preprocessing:  87%|████████▋ | 7339/8455 [07:03<00:53, 21.01it/s]

Preprocessing:  87%|████████▋ | 7342/8455 [07:03<00:54, 20.57it/s]

Preprocessing:  87%|████████▋ | 7345/8455 [07:03<00:51, 21.41it/s]

Preprocessing:  87%|████████▋ | 7348/8455 [07:03<00:54, 20.25it/s]

Preprocessing:  87%|████████▋ | 7351/8455 [07:03<00:57, 19.30it/s]

Preprocessing:  87%|████████▋ | 7354/8455 [07:03<00:56, 19.64it/s]

Preprocessing:  87%|████████▋ | 7356/8455 [07:04<01:05, 16.80it/s]

Preprocessing:  87%|████████▋ | 7358/8455 [07:04<01:15, 14.58it/s]

Preprocessing:  87%|████████▋ | 7360/8455 [07:04<01:19, 13.69it/s]

Preprocessing:  87%|████████▋ | 7362/8455 [07:04<01:20, 13.52it/s]

Preprocessing:  87%|████████▋ | 7364/8455 [07:04<01:22, 13.25it/s]

Preprocessing:  87%|████████▋ | 7366/8455 [07:04<01:24, 12.85it/s]

Preprocessing:  87%|████████▋ | 7368/8455 [07:05<01:23, 12.99it/s]

Preprocessing:  87%|████████▋ | 7370/8455 [07:05<01:21, 13.36it/s]

Preprocessing:  87%|████████▋ | 7372/8455 [07:05<01:20, 13.44it/s]

Preprocessing:  87%|████████▋ | 7374/8455 [07:05<01:20, 13.50it/s]

Preprocessing:  87%|████████▋ | 7376/8455 [07:05<01:19, 13.60it/s]

Preprocessing:  87%|████████▋ | 7378/8455 [07:05<01:19, 13.62it/s]

Preprocessing:  87%|████████▋ | 7380/8455 [07:05<01:17, 13.83it/s]

Preprocessing:  87%|████████▋ | 7382/8455 [07:06<01:20, 13.40it/s]

Preprocessing:  87%|████████▋ | 7384/8455 [07:06<01:23, 12.77it/s]

Preprocessing:  87%|████████▋ | 7386/8455 [07:06<01:25, 12.53it/s]

Preprocessing:  87%|████████▋ | 7388/8455 [07:06<01:24, 12.68it/s]

Preprocessing:  87%|████████▋ | 7390/8455 [07:06<01:23, 12.80it/s]

Preprocessing:  87%|████████▋ | 7392/8455 [07:06<01:22, 12.88it/s]

Preprocessing:  87%|████████▋ | 7394/8455 [07:07<01:22, 12.94it/s]

Preprocessing:  87%|████████▋ | 7396/8455 [07:07<01:29, 11.78it/s]

Preprocessing:  87%|████████▋ | 7398/8455 [07:07<01:35, 11.09it/s]

Preprocessing:  88%|████████▊ | 7400/8455 [07:07<01:31, 11.55it/s]

Preprocessing:  88%|████████▊ | 7402/8455 [07:07<01:25, 12.35it/s]

Preprocessing:  88%|████████▊ | 7404/8455 [07:07<01:20, 13.01it/s]

Preprocessing:  88%|████████▊ | 7406/8455 [07:08<01:17, 13.47it/s]

Preprocessing:  88%|████████▊ | 7408/8455 [07:08<01:15, 13.88it/s]

Preprocessing:  88%|████████▊ | 7410/8455 [07:08<01:15, 13.86it/s]

Preprocessing:  88%|████████▊ | 7412/8455 [07:08<01:16, 13.56it/s]

Preprocessing:  88%|████████▊ | 7414/8455 [07:08<01:16, 13.64it/s]

Preprocessing:  88%|████████▊ | 7416/8455 [07:08<01:14, 13.88it/s]

Preprocessing:  88%|████████▊ | 7418/8455 [07:08<01:15, 13.79it/s]

Preprocessing:  88%|████████▊ | 7420/8455 [07:09<01:15, 13.79it/s]

Preprocessing:  88%|████████▊ | 7422/8455 [07:09<01:13, 13.96it/s]

Preprocessing:  88%|████████▊ | 7424/8455 [07:09<01:14, 13.88it/s]

Preprocessing:  88%|████████▊ | 7426/8455 [07:09<01:15, 13.63it/s]

Preprocessing:  88%|████████▊ | 7428/8455 [07:09<01:14, 13.80it/s]

Preprocessing:  88%|████████▊ | 7430/8455 [07:09<01:13, 13.86it/s]

Preprocessing:  88%|████████▊ | 7432/8455 [07:09<01:14, 13.80it/s]

Preprocessing:  88%|████████▊ | 7434/8455 [07:10<01:23, 12.30it/s]

Preprocessing:  88%|████████▊ | 7436/8455 [07:10<01:23, 12.22it/s]

Preprocessing:  88%|████████▊ | 7438/8455 [07:10<01:24, 12.04it/s]

Preprocessing:  88%|████████▊ | 7440/8455 [07:10<01:27, 11.55it/s]

Preprocessing:  88%|████████▊ | 7442/8455 [07:10<01:25, 11.82it/s]

Preprocessing:  88%|████████▊ | 7444/8455 [07:10<01:22, 12.21it/s]

Preprocessing:  88%|████████▊ | 7446/8455 [07:11<01:22, 12.26it/s]

Preprocessing:  88%|████████▊ | 7448/8455 [07:11<01:21, 12.32it/s]

Preprocessing:  88%|████████▊ | 7450/8455 [07:11<01:17, 12.98it/s]

Preprocessing:  88%|████████▊ | 7452/8455 [07:11<01:19, 12.60it/s]

Preprocessing:  88%|████████▊ | 7454/8455 [07:11<01:17, 12.86it/s]

Preprocessing:  88%|████████▊ | 7456/8455 [07:11<01:17, 12.94it/s]

Preprocessing:  88%|████████▊ | 7458/8455 [07:11<01:15, 13.24it/s]

Preprocessing:  88%|████████▊ | 7460/8455 [07:12<01:14, 13.30it/s]

Preprocessing:  88%|████████▊ | 7462/8455 [07:12<01:18, 12.69it/s]

Preprocessing:  88%|████████▊ | 7464/8455 [07:12<01:16, 12.89it/s]

Preprocessing:  88%|████████▊ | 7466/8455 [07:12<01:13, 13.40it/s]

Preprocessing:  88%|████████▊ | 7468/8455 [07:12<01:12, 13.68it/s]

Preprocessing:  88%|████████▊ | 7470/8455 [07:12<01:13, 13.49it/s]

Preprocessing:  88%|████████▊ | 7472/8455 [07:13<01:13, 13.46it/s]

Preprocessing:  88%|████████▊ | 7474/8455 [07:13<01:12, 13.55it/s]

Preprocessing:  88%|████████▊ | 7476/8455 [07:13<01:11, 13.78it/s]

Preprocessing:  88%|████████▊ | 7478/8455 [07:13<01:12, 13.43it/s]

Preprocessing:  88%|████████▊ | 7480/8455 [07:13<01:14, 13.15it/s]

Preprocessing:  88%|████████▊ | 7482/8455 [07:13<01:14, 13.13it/s]

Preprocessing:  89%|████████▊ | 7484/8455 [07:13<01:15, 12.92it/s]

Preprocessing:  89%|████████▊ | 7486/8455 [07:14<01:14, 12.98it/s]

Preprocessing:  89%|████████▊ | 7488/8455 [07:14<01:13, 13.16it/s]

Preprocessing:  89%|████████▊ | 7490/8455 [07:14<01:12, 13.35it/s]

Preprocessing:  89%|████████▊ | 7492/8455 [07:14<01:10, 13.64it/s]

Preprocessing:  89%|████████▊ | 7494/8455 [07:14<01:09, 13.85it/s]

Preprocessing:  89%|████████▊ | 7496/8455 [07:14<01:08, 14.00it/s]

Preprocessing:  89%|████████▊ | 7498/8455 [07:14<01:11, 13.30it/s]

Preprocessing:  89%|████████▊ | 7500/8455 [07:15<01:10, 13.64it/s]

Preprocessing:  89%|████████▊ | 7502/8455 [07:15<01:09, 13.65it/s]

Preprocessing:  89%|████████▉ | 7504/8455 [07:15<01:11, 13.27it/s]

Preprocessing:  89%|████████▉ | 7506/8455 [07:15<01:12, 13.15it/s]

Preprocessing:  89%|████████▉ | 7508/8455 [07:15<01:10, 13.39it/s]

Preprocessing:  89%|████████▉ | 7510/8455 [07:15<01:11, 13.30it/s]

Preprocessing:  89%|████████▉ | 7512/8455 [07:16<01:10, 13.37it/s]

Preprocessing:  89%|████████▉ | 7514/8455 [07:16<01:10, 13.36it/s]

Preprocessing:  89%|████████▉ | 7516/8455 [07:16<01:12, 12.95it/s]

Preprocessing:  89%|████████▉ | 7518/8455 [07:16<01:13, 12.81it/s]

Preprocessing:  89%|████████▉ | 7520/8455 [07:16<01:14, 12.62it/s]

Preprocessing:  89%|████████▉ | 7522/8455 [07:16<01:15, 12.42it/s]

Preprocessing:  89%|████████▉ | 7524/8455 [07:17<01:16, 12.22it/s]

Preprocessing:  89%|████████▉ | 7526/8455 [07:17<01:14, 12.53it/s]

Preprocessing:  89%|████████▉ | 7528/8455 [07:17<01:14, 12.38it/s]

Preprocessing:  89%|████████▉ | 7530/8455 [07:17<01:17, 11.96it/s]

Preprocessing:  89%|████████▉ | 7532/8455 [07:17<01:16, 12.12it/s]

Preprocessing:  89%|████████▉ | 7534/8455 [07:17<01:12, 12.72it/s]

Preprocessing:  89%|████████▉ | 7536/8455 [07:17<01:11, 12.88it/s]

Preprocessing:  89%|████████▉ | 7538/8455 [07:18<01:08, 13.38it/s]

Preprocessing:  89%|████████▉ | 7540/8455 [07:18<01:09, 13.10it/s]

Preprocessing:  89%|████████▉ | 7542/8455 [07:18<01:10, 12.92it/s]

Preprocessing:  89%|████████▉ | 7544/8455 [07:18<01:10, 12.97it/s]

Preprocessing:  89%|████████▉ | 7546/8455 [07:18<01:10, 12.98it/s]

Preprocessing:  89%|████████▉ | 7548/8455 [07:18<01:07, 13.39it/s]

Preprocessing:  89%|████████▉ | 7550/8455 [07:19<01:09, 13.04it/s]

Preprocessing:  89%|████████▉ | 7552/8455 [07:19<01:10, 12.87it/s]

Preprocessing:  89%|████████▉ | 7554/8455 [07:19<01:06, 13.46it/s]

Preprocessing:  89%|████████▉ | 7556/8455 [07:19<01:07, 13.23it/s]

Preprocessing:  89%|████████▉ | 7558/8455 [07:19<01:09, 12.90it/s]

Preprocessing:  89%|████████▉ | 7560/8455 [07:19<01:08, 13.04it/s]

Preprocessing:  89%|████████▉ | 7562/8455 [07:19<01:09, 12.81it/s]

Preprocessing:  89%|████████▉ | 7564/8455 [07:20<01:10, 12.63it/s]

Preprocessing:  89%|████████▉ | 7566/8455 [07:20<01:21, 10.89it/s]

Preprocessing:  90%|████████▉ | 7568/8455 [07:20<01:22, 10.74it/s]

Preprocessing:  90%|████████▉ | 7570/8455 [07:20<01:19, 11.11it/s]

Preprocessing:  90%|████████▉ | 7572/8455 [07:20<01:17, 11.43it/s]

Preprocessing:  90%|████████▉ | 7574/8455 [07:21<01:15, 11.74it/s]

Preprocessing:  90%|████████▉ | 7576/8455 [07:21<01:13, 12.02it/s]

Preprocessing:  90%|████████▉ | 7578/8455 [07:21<01:10, 12.49it/s]

Preprocessing:  90%|████████▉ | 7580/8455 [07:21<01:09, 12.52it/s]

Preprocessing:  90%|████████▉ | 7582/8455 [07:21<01:07, 12.86it/s]

Preprocessing:  90%|████████▉ | 7584/8455 [07:21<01:07, 12.98it/s]

Preprocessing:  90%|████████▉ | 7586/8455 [07:21<01:06, 13.06it/s]

Preprocessing:  90%|████████▉ | 7588/8455 [07:22<01:06, 13.13it/s]

Preprocessing:  90%|████████▉ | 7590/8455 [07:22<01:13, 11.83it/s]

Preprocessing:  90%|████████▉ | 7592/8455 [07:22<01:11, 12.15it/s]

Preprocessing:  90%|████████▉ | 7594/8455 [07:22<01:11, 12.07it/s]

Preprocessing:  90%|████████▉ | 7596/8455 [07:22<01:11, 11.93it/s]

Preprocessing:  90%|████████▉ | 7598/8455 [07:22<01:10, 12.20it/s]

Preprocessing:  90%|████████▉ | 7600/8455 [07:23<01:08, 12.40it/s]

Preprocessing:  90%|████████▉ | 7602/8455 [07:23<01:12, 11.78it/s]

Preprocessing:  90%|████████▉ | 7604/8455 [07:23<01:12, 11.70it/s]

Preprocessing:  90%|████████▉ | 7606/8455 [07:23<01:11, 11.89it/s]

Preprocessing:  90%|████████▉ | 7608/8455 [07:23<01:10, 11.98it/s]

Preprocessing:  90%|█████████ | 7610/8455 [07:23<01:14, 11.35it/s]

Preprocessing:  90%|█████████ | 7612/8455 [07:24<01:13, 11.43it/s]

Preprocessing:  90%|█████████ | 7614/8455 [07:24<01:11, 11.73it/s]

Preprocessing:  90%|█████████ | 7616/8455 [07:24<01:17, 10.83it/s]

Preprocessing:  90%|█████████ | 7618/8455 [07:24<01:19, 10.52it/s]

Preprocessing:  90%|█████████ | 7620/8455 [07:24<01:18, 10.60it/s]

Preprocessing:  90%|█████████ | 7622/8455 [07:25<01:13, 11.29it/s]

Preprocessing:  90%|█████████ | 7624/8455 [07:25<01:11, 11.64it/s]

Preprocessing:  90%|█████████ | 7626/8455 [07:25<01:12, 11.51it/s]

Preprocessing:  90%|█████████ | 7628/8455 [07:25<01:11, 11.51it/s]

Preprocessing:  90%|█████████ | 7630/8455 [07:25<01:10, 11.72it/s]

Preprocessing:  90%|█████████ | 7632/8455 [07:25<01:07, 12.15it/s]

Preprocessing:  90%|█████████ | 7634/8455 [07:26<01:07, 12.12it/s]

Preprocessing:  90%|█████████ | 7636/8455 [07:26<01:06, 12.40it/s]

Preprocessing:  90%|█████████ | 7638/8455 [07:26<01:04, 12.72it/s]

Preprocessing:  90%|█████████ | 7640/8455 [07:26<01:04, 12.54it/s]

Preprocessing:  90%|█████████ | 7642/8455 [07:26<01:02, 13.04it/s]

Preprocessing:  90%|█████████ | 7644/8455 [07:26<01:02, 12.89it/s]

Preprocessing:  90%|█████████ | 7646/8455 [07:26<01:02, 12.93it/s]

Preprocessing:  90%|█████████ | 7648/8455 [07:27<01:00, 13.40it/s]

Preprocessing:  90%|█████████ | 7650/8455 [07:27<01:02, 12.94it/s]

Preprocessing:  91%|█████████ | 7652/8455 [07:27<01:01, 12.96it/s]

Preprocessing:  91%|█████████ | 7654/8455 [07:27<01:02, 12.72it/s]

Preprocessing:  91%|█████████ | 7656/8455 [07:27<01:05, 12.19it/s]

Preprocessing:  91%|█████████ | 7658/8455 [07:27<01:02, 12.82it/s]

Preprocessing:  91%|█████████ | 7660/8455 [07:28<01:03, 12.60it/s]

Preprocessing:  91%|█████████ | 7662/8455 [07:28<01:02, 12.75it/s]

Preprocessing:  91%|█████████ | 7664/8455 [07:28<01:00, 13.12it/s]

Preprocessing:  91%|█████████ | 7666/8455 [07:28<01:01, 12.76it/s]

Preprocessing:  91%|█████████ | 7668/8455 [07:28<00:59, 13.30it/s]

Preprocessing:  91%|█████████ | 7670/8455 [07:28<00:59, 13.17it/s]

Preprocessing:  91%|█████████ | 7672/8455 [07:28<00:58, 13.28it/s]

Preprocessing:  91%|█████████ | 7674/8455 [07:29<00:57, 13.55it/s]

Preprocessing:  91%|█████████ | 7676/8455 [07:29<00:58, 13.41it/s]

Preprocessing:  91%|█████████ | 7678/8455 [07:29<00:57, 13.41it/s]

Preprocessing:  91%|█████████ | 7680/8455 [07:29<00:57, 13.57it/s]

Preprocessing:  91%|█████████ | 7682/8455 [07:29<00:57, 13.56it/s]

Preprocessing:  91%|█████████ | 7684/8455 [07:29<00:59, 13.01it/s]

Preprocessing:  91%|█████████ | 7686/8455 [07:30<01:01, 12.41it/s]

Preprocessing:  91%|█████████ | 7688/8455 [07:30<01:02, 12.33it/s]

Preprocessing:  91%|█████████ | 7690/8455 [07:30<00:58, 13.01it/s]

Preprocessing:  91%|█████████ | 7692/8455 [07:30<00:54, 14.05it/s]

Preprocessing:  91%|█████████ | 7695/8455 [07:30<00:45, 16.80it/s]

Preprocessing:  91%|█████████ | 7698/8455 [07:30<00:40, 18.84it/s]

Preprocessing:  91%|█████████ | 7701/8455 [07:30<00:38, 19.55it/s]

Preprocessing:  91%|█████████ | 7703/8455 [07:30<00:39, 19.10it/s]

Preprocessing:  91%|█████████ | 7706/8455 [07:31<00:36, 20.32it/s]

Preprocessing:  91%|█████████ | 7709/8455 [07:31<00:35, 21.04it/s]

Preprocessing:  91%|█████████ | 7712/8455 [07:31<00:35, 20.83it/s]

Preprocessing:  91%|█████████ | 7715/8455 [07:31<00:33, 22.39it/s]

Preprocessing:  91%|█████████▏| 7718/8455 [07:31<00:31, 23.38it/s]

Preprocessing:  91%|█████████▏| 7721/8455 [07:31<00:30, 24.24it/s]

Preprocessing:  91%|█████████▏| 7724/8455 [07:31<00:32, 22.66it/s]

Preprocessing:  91%|█████████▏| 7727/8455 [07:32<00:35, 20.76it/s]

Preprocessing:  91%|█████████▏| 7730/8455 [07:32<00:33, 21.62it/s]

Preprocessing:  91%|█████████▏| 7733/8455 [07:32<00:32, 22.56it/s]

Preprocessing:  91%|█████████▏| 7736/8455 [07:32<00:30, 23.23it/s]

Preprocessing:  92%|█████████▏| 7739/8455 [07:32<00:30, 23.72it/s]

Preprocessing:  92%|█████████▏| 7742/8455 [07:32<00:29, 24.05it/s]

Preprocessing:  92%|█████████▏| 7745/8455 [07:32<00:28, 24.56it/s]

Preprocessing:  92%|█████████▏| 7748/8455 [07:32<00:28, 24.92it/s]

Preprocessing:  92%|█████████▏| 7751/8455 [07:33<00:28, 24.55it/s]

Preprocessing:  92%|█████████▏| 7754/8455 [07:33<00:29, 24.01it/s]

Preprocessing:  92%|█████████▏| 7757/8455 [07:33<00:29, 23.63it/s]

Preprocessing:  92%|█████████▏| 7760/8455 [07:33<00:29, 23.62it/s]

Preprocessing:  92%|█████████▏| 7763/8455 [07:33<00:28, 24.01it/s]

Preprocessing:  92%|█████████▏| 7766/8455 [07:33<00:27, 24.63it/s]

Preprocessing:  92%|█████████▏| 7769/8455 [07:33<00:28, 23.97it/s]

Preprocessing:  92%|█████████▏| 7772/8455 [07:33<00:28, 23.79it/s]

Preprocessing:  92%|█████████▏| 7775/8455 [07:34<00:29, 23.18it/s]

Preprocessing:  92%|█████████▏| 7778/8455 [07:34<00:28, 23.80it/s]

Preprocessing:  92%|█████████▏| 7781/8455 [07:34<00:27, 24.19it/s]

Preprocessing:  92%|█████████▏| 7784/8455 [07:34<00:27, 24.70it/s]

Preprocessing:  92%|█████████▏| 7787/8455 [07:34<00:26, 25.15it/s]

Preprocessing:  92%|█████████▏| 7790/8455 [07:34<00:26, 24.86it/s]

Preprocessing:  92%|█████████▏| 7793/8455 [07:34<00:26, 24.54it/s]

Preprocessing:  92%|█████████▏| 7796/8455 [07:34<00:26, 24.49it/s]

Preprocessing:  92%|█████████▏| 7799/8455 [07:35<00:28, 23.23it/s]

Preprocessing:  92%|█████████▏| 7802/8455 [07:35<00:27, 23.49it/s]

Preprocessing:  92%|█████████▏| 7805/8455 [07:35<00:27, 23.78it/s]

Preprocessing:  92%|█████████▏| 7808/8455 [07:35<00:27, 23.15it/s]

Preprocessing:  92%|█████████▏| 7811/8455 [07:35<00:27, 23.45it/s]

Preprocessing:  92%|█████████▏| 7814/8455 [07:35<00:26, 24.27it/s]

Preprocessing:  92%|█████████▏| 7817/8455 [07:35<00:26, 24.16it/s]

Preprocessing:  92%|█████████▏| 7820/8455 [07:35<00:25, 24.62it/s]

Preprocessing:  93%|█████████▎| 7823/8455 [07:36<00:25, 25.17it/s]

Preprocessing:  93%|█████████▎| 7826/8455 [07:36<00:24, 25.24it/s]

Preprocessing:  93%|█████████▎| 7829/8455 [07:36<00:25, 24.71it/s]

Preprocessing:  93%|█████████▎| 7832/8455 [07:36<00:26, 23.94it/s]

Preprocessing:  93%|█████████▎| 7835/8455 [07:36<00:25, 24.19it/s]

Preprocessing:  93%|█████████▎| 7838/8455 [07:36<00:25, 24.60it/s]

Preprocessing:  93%|█████████▎| 7841/8455 [07:36<00:24, 24.80it/s]

Preprocessing:  93%|█████████▎| 7844/8455 [07:36<00:24, 25.42it/s]

Preprocessing:  93%|█████████▎| 7847/8455 [07:36<00:24, 25.24it/s]

Preprocessing:  93%|█████████▎| 7850/8455 [07:37<00:23, 25.29it/s]

Preprocessing:  93%|█████████▎| 7853/8455 [07:37<00:23, 25.17it/s]

Preprocessing:  93%|█████████▎| 7856/8455 [07:37<00:23, 25.32it/s]

Preprocessing:  93%|█████████▎| 7859/8455 [07:37<00:23, 25.42it/s]

Preprocessing:  93%|█████████▎| 7862/8455 [07:37<00:23, 25.47it/s]

Preprocessing:  93%|█████████▎| 7865/8455 [07:37<00:23, 25.20it/s]

Preprocessing:  93%|█████████▎| 7868/8455 [07:37<00:23, 25.06it/s]

Preprocessing:  93%|█████████▎| 7871/8455 [07:37<00:23, 25.27it/s]

Preprocessing:  93%|█████████▎| 7874/8455 [07:38<00:22, 25.36it/s]

Preprocessing:  93%|█████████▎| 7877/8455 [07:38<00:22, 25.50it/s]

Preprocessing:  93%|█████████▎| 7880/8455 [07:38<00:22, 25.39it/s]

Preprocessing:  93%|█████████▎| 7883/8455 [07:38<00:22, 25.61it/s]

Preprocessing:  93%|█████████▎| 7886/8455 [07:38<00:22, 25.82it/s]

Preprocessing:  93%|█████████▎| 7889/8455 [07:38<00:22, 25.45it/s]

Preprocessing:  93%|█████████▎| 7892/8455 [07:38<00:22, 25.43it/s]

Preprocessing:  93%|█████████▎| 7895/8455 [07:38<00:22, 25.41it/s]

Preprocessing:  93%|█████████▎| 7898/8455 [07:38<00:21, 25.32it/s]

Preprocessing:  93%|█████████▎| 7901/8455 [07:39<00:22, 24.27it/s]

Preprocessing:  93%|█████████▎| 7904/8455 [07:39<00:23, 23.76it/s]

Preprocessing:  94%|█████████▎| 7907/8455 [07:39<00:22, 24.41it/s]

Preprocessing:  94%|█████████▎| 7910/8455 [07:39<00:22, 24.29it/s]

Preprocessing:  94%|█████████▎| 7913/8455 [07:39<00:22, 24.50it/s]

Preprocessing:  94%|█████████▎| 7916/8455 [07:39<00:21, 24.74it/s]

Preprocessing:  94%|█████████▎| 7919/8455 [07:39<00:21, 24.72it/s]

Preprocessing:  94%|█████████▎| 7922/8455 [07:39<00:21, 25.11it/s]

Preprocessing:  94%|█████████▎| 7925/8455 [07:40<00:21, 24.76it/s]

Preprocessing:  94%|█████████▍| 7928/8455 [07:40<00:21, 24.51it/s]

Preprocessing:  94%|█████████▍| 7931/8455 [07:40<00:21, 24.59it/s]

Preprocessing:  94%|█████████▍| 7934/8455 [07:40<00:21, 24.50it/s]

Preprocessing:  94%|█████████▍| 7937/8455 [07:40<00:21, 23.80it/s]

Preprocessing:  94%|█████████▍| 7940/8455 [07:40<00:22, 23.40it/s]

Preprocessing:  94%|█████████▍| 7943/8455 [07:40<00:22, 23.13it/s]

Preprocessing:  94%|█████████▍| 7946/8455 [07:40<00:21, 23.33it/s]

Preprocessing:  94%|█████████▍| 7949/8455 [07:41<00:21, 23.92it/s]

Preprocessing:  94%|█████████▍| 7952/8455 [07:41<00:20, 24.13it/s]

Preprocessing:  94%|█████████▍| 7955/8455 [07:41<00:20, 24.78it/s]

Preprocessing:  94%|█████████▍| 7958/8455 [07:41<00:20, 24.62it/s]

Preprocessing:  94%|█████████▍| 7961/8455 [07:41<00:19, 24.79it/s]

Preprocessing:  94%|█████████▍| 7964/8455 [07:41<00:19, 24.96it/s]

Preprocessing:  94%|█████████▍| 7967/8455 [07:41<00:19, 24.66it/s]

Preprocessing:  94%|█████████▍| 7970/8455 [07:41<00:20, 24.04it/s]

Preprocessing:  94%|█████████▍| 7973/8455 [07:42<00:20, 23.63it/s]

Preprocessing:  94%|█████████▍| 7976/8455 [07:42<00:20, 23.92it/s]

Preprocessing:  94%|█████████▍| 7979/8455 [07:42<00:19, 24.36it/s]

Preprocessing:  94%|█████████▍| 7982/8455 [07:42<00:19, 24.20it/s]

Preprocessing:  94%|█████████▍| 7985/8455 [07:42<00:19, 23.62it/s]

Preprocessing:  94%|█████████▍| 7988/8455 [07:42<00:19, 23.61it/s]

Preprocessing:  95%|█████████▍| 7991/8455 [07:42<00:19, 24.14it/s]

Preprocessing:  95%|█████████▍| 7994/8455 [07:42<00:19, 24.08it/s]

Preprocessing:  95%|█████████▍| 7997/8455 [07:43<00:18, 24.23it/s]

Preprocessing:  95%|█████████▍| 8000/8455 [07:43<00:18, 24.07it/s]

Preprocessing:  95%|█████████▍| 8003/8455 [07:43<00:19, 23.61it/s]

Preprocessing:  95%|█████████▍| 8006/8455 [07:43<00:19, 23.59it/s]

Preprocessing:  95%|█████████▍| 8009/8455 [07:43<00:18, 23.83it/s]

Preprocessing:  95%|█████████▍| 8012/8455 [07:43<00:18, 24.00it/s]

Preprocessing:  95%|█████████▍| 8015/8455 [07:43<00:18, 24.15it/s]

Preprocessing:  95%|█████████▍| 8018/8455 [07:43<00:18, 24.01it/s]

Preprocessing:  95%|█████████▍| 8021/8455 [07:44<00:22, 19.46it/s]

Preprocessing:  95%|█████████▍| 8024/8455 [07:44<00:23, 18.59it/s]

Preprocessing:  95%|█████████▍| 8026/8455 [07:44<00:23, 18.42it/s]

Preprocessing:  95%|█████████▍| 8029/8455 [07:44<00:22, 18.92it/s]

Preprocessing:  95%|█████████▍| 8032/8455 [07:44<00:21, 19.61it/s]

Preprocessing:  95%|█████████▌| 8035/8455 [07:44<00:20, 20.66it/s]

Preprocessing:  95%|█████████▌| 8038/8455 [07:45<00:20, 20.61it/s]

Preprocessing:  95%|█████████▌| 8041/8455 [07:45<00:19, 21.33it/s]

Preprocessing:  95%|█████████▌| 8044/8455 [07:45<00:18, 21.74it/s]

Preprocessing:  95%|█████████▌| 8047/8455 [07:45<00:18, 22.49it/s]

Preprocessing:  95%|█████████▌| 8050/8455 [07:45<00:17, 22.77it/s]

Preprocessing:  95%|█████████▌| 8053/8455 [07:45<00:17, 23.28it/s]

Preprocessing:  95%|█████████▌| 8056/8455 [07:45<00:17, 23.13it/s]

Preprocessing:  95%|█████████▌| 8059/8455 [07:45<00:16, 23.68it/s]

Preprocessing:  95%|█████████▌| 8062/8455 [07:46<00:16, 23.44it/s]

Preprocessing:  95%|█████████▌| 8065/8455 [07:46<00:16, 23.75it/s]

Preprocessing:  95%|█████████▌| 8068/8455 [07:46<00:16, 23.76it/s]

Preprocessing:  95%|█████████▌| 8071/8455 [07:46<00:15, 24.12it/s]

Preprocessing:  95%|█████████▌| 8074/8455 [07:46<00:16, 23.12it/s]

Preprocessing:  96%|█████████▌| 8077/8455 [07:46<00:16, 22.79it/s]

Preprocessing:  96%|█████████▌| 8080/8455 [07:46<00:16, 23.44it/s]

Preprocessing:  96%|█████████▌| 8083/8455 [07:46<00:15, 23.96it/s]

Preprocessing:  96%|█████████▌| 8086/8455 [07:47<00:15, 23.27it/s]

Preprocessing:  96%|█████████▌| 8089/8455 [07:47<00:16, 22.34it/s]

Preprocessing:  96%|█████████▌| 8092/8455 [07:47<00:17, 20.85it/s]

Preprocessing:  96%|█████████▌| 8095/8455 [07:47<00:17, 20.72it/s]

Preprocessing:  96%|█████████▌| 8098/8455 [07:47<00:17, 20.66it/s]

Preprocessing:  96%|█████████▌| 8101/8455 [07:47<00:16, 21.08it/s]

Preprocessing:  96%|█████████▌| 8104/8455 [07:47<00:16, 21.28it/s]

Preprocessing:  96%|█████████▌| 8107/8455 [07:48<00:16, 21.31it/s]

Preprocessing:  96%|█████████▌| 8110/8455 [07:48<00:16, 21.54it/s]

Preprocessing:  96%|█████████▌| 8113/8455 [07:48<00:15, 22.26it/s]

Preprocessing:  96%|█████████▌| 8116/8455 [07:48<00:15, 21.68it/s]

Preprocessing:  96%|█████████▌| 8119/8455 [07:48<00:15, 21.76it/s]

Preprocessing:  96%|█████████▌| 8122/8455 [07:48<00:16, 20.08it/s]

Preprocessing:  96%|█████████▌| 8125/8455 [07:48<00:16, 20.57it/s]

Preprocessing:  96%|█████████▌| 8128/8455 [07:49<00:15, 20.94it/s]

Preprocessing:  96%|█████████▌| 8131/8455 [07:49<00:15, 20.99it/s]

Preprocessing:  96%|█████████▌| 8134/8455 [07:49<00:15, 20.55it/s]

Preprocessing:  96%|█████████▌| 8137/8455 [07:49<00:15, 20.67it/s]

Preprocessing:  96%|█████████▋| 8140/8455 [07:49<00:15, 20.91it/s]

Preprocessing:  96%|█████████▋| 8143/8455 [07:49<00:15, 20.54it/s]

Preprocessing:  96%|█████████▋| 8146/8455 [07:49<00:15, 19.97it/s]

Preprocessing:  96%|█████████▋| 8149/8455 [07:50<00:14, 20.46it/s]

Preprocessing:  96%|█████████▋| 8152/8455 [07:50<00:14, 20.45it/s]

Preprocessing:  96%|█████████▋| 8155/8455 [07:50<00:14, 21.08it/s]

Preprocessing:  96%|█████████▋| 8158/8455 [07:50<00:13, 21.74it/s]

Preprocessing:  97%|█████████▋| 8161/8455 [07:50<00:13, 21.99it/s]

Preprocessing:  97%|█████████▋| 8164/8455 [07:50<00:13, 21.92it/s]

Preprocessing:  97%|█████████▋| 8167/8455 [07:50<00:12, 22.22it/s]

Preprocessing:  97%|█████████▋| 8170/8455 [07:51<00:12, 22.53it/s]

Preprocessing:  97%|█████████▋| 8173/8455 [07:51<00:12, 22.45it/s]

Preprocessing:  97%|█████████▋| 8176/8455 [07:51<00:12, 22.13it/s]

Preprocessing:  97%|█████████▋| 8179/8455 [07:51<00:12, 22.35it/s]

Preprocessing:  97%|█████████▋| 8182/8455 [07:51<00:12, 22.53it/s]

Preprocessing:  97%|█████████▋| 8185/8455 [07:51<00:11, 22.53it/s]

Preprocessing:  97%|█████████▋| 8188/8455 [07:51<00:11, 22.68it/s]

Preprocessing:  97%|█████████▋| 8191/8455 [07:52<00:11, 22.17it/s]

Preprocessing:  97%|█████████▋| 8194/8455 [07:52<00:11, 22.03it/s]

Preprocessing:  97%|█████████▋| 8197/8455 [07:52<00:11, 21.83it/s]

Preprocessing:  97%|█████████▋| 8200/8455 [07:52<00:11, 21.62it/s]

Preprocessing:  97%|█████████▋| 8203/8455 [07:52<00:11, 21.71it/s]

Preprocessing:  97%|█████████▋| 8206/8455 [07:52<00:11, 21.61it/s]

Preprocessing:  97%|█████████▋| 8209/8455 [07:52<00:11, 21.71it/s]

Preprocessing:  97%|█████████▋| 8212/8455 [07:52<00:11, 21.48it/s]

Preprocessing:  97%|█████████▋| 8215/8455 [07:53<00:11, 21.34it/s]

Preprocessing:  97%|█████████▋| 8218/8455 [07:53<00:11, 20.76it/s]

Preprocessing:  97%|█████████▋| 8221/8455 [07:53<00:11, 20.68it/s]

Preprocessing:  97%|█████████▋| 8224/8455 [07:53<00:11, 20.65it/s]

Preprocessing:  97%|█████████▋| 8227/8455 [07:53<00:10, 20.92it/s]

Preprocessing:  97%|█████████▋| 8230/8455 [07:53<00:10, 21.42it/s]

Preprocessing:  97%|█████████▋| 8233/8455 [07:53<00:10, 21.54it/s]

Preprocessing:  97%|█████████▋| 8236/8455 [07:54<00:10, 21.25it/s]

Preprocessing:  97%|█████████▋| 8239/8455 [07:54<00:10, 20.97it/s]

Preprocessing:  97%|█████████▋| 8242/8455 [07:54<00:10, 21.11it/s]

Preprocessing:  98%|█████████▊| 8245/8455 [07:54<00:09, 21.49it/s]

Preprocessing:  98%|█████████▊| 8248/8455 [07:54<00:09, 21.37it/s]

Preprocessing:  98%|█████████▊| 8251/8455 [07:54<00:09, 21.22it/s]

Preprocessing:  98%|█████████▊| 8254/8455 [07:54<00:09, 21.53it/s]

Preprocessing:  98%|█████████▊| 8257/8455 [07:55<00:09, 21.58it/s]

Preprocessing:  98%|█████████▊| 8260/8455 [07:55<00:09, 21.42it/s]

Preprocessing:  98%|█████████▊| 8263/8455 [07:55<00:08, 21.84it/s]

Preprocessing:  98%|█████████▊| 8266/8455 [07:55<00:08, 22.00it/s]

Preprocessing:  98%|█████████▊| 8269/8455 [07:55<00:08, 21.49it/s]

Preprocessing:  98%|█████████▊| 8272/8455 [07:55<00:08, 21.82it/s]

Preprocessing:  98%|█████████▊| 8275/8455 [07:55<00:08, 21.51it/s]

Preprocessing:  98%|█████████▊| 8278/8455 [07:56<00:08, 22.00it/s]

Preprocessing:  98%|█████████▊| 8281/8455 [07:56<00:07, 21.80it/s]

Preprocessing:  98%|█████████▊| 8284/8455 [07:56<00:07, 21.46it/s]

Preprocessing:  98%|█████████▊| 8287/8455 [07:56<00:07, 21.72it/s]

Preprocessing:  98%|█████████▊| 8290/8455 [07:56<00:07, 22.13it/s]

Preprocessing:  98%|█████████▊| 8293/8455 [07:56<00:07, 22.17it/s]

Preprocessing:  98%|█████████▊| 8296/8455 [07:56<00:07, 21.92it/s]

Preprocessing:  98%|█████████▊| 8299/8455 [07:57<00:06, 22.32it/s]

Preprocessing:  98%|█████████▊| 8302/8455 [07:57<00:06, 22.09it/s]

Preprocessing:  98%|█████████▊| 8305/8455 [07:57<00:06, 22.15it/s]

Preprocessing:  98%|█████████▊| 8308/8455 [07:57<00:06, 21.66it/s]

Preprocessing:  98%|█████████▊| 8311/8455 [07:57<00:06, 21.43it/s]

Preprocessing:  98%|█████████▊| 8314/8455 [07:57<00:06, 21.28it/s]

Preprocessing:  98%|█████████▊| 8317/8455 [07:57<00:06, 21.44it/s]

Preprocessing:  98%|█████████▊| 8320/8455 [07:57<00:06, 21.85it/s]

Preprocessing:  98%|█████████▊| 8323/8455 [07:58<00:06, 21.68it/s]

Preprocessing:  98%|█████████▊| 8326/8455 [07:58<00:05, 21.78it/s]

Preprocessing:  99%|█████████▊| 8329/8455 [07:58<00:05, 21.96it/s]

Preprocessing:  99%|█████████▊| 8332/8455 [07:58<00:05, 21.83it/s]

Preprocessing:  99%|█████████▊| 8335/8455 [07:58<00:05, 21.24it/s]

Preprocessing:  99%|█████████▊| 8338/8455 [07:58<00:05, 20.93it/s]

Preprocessing:  99%|█████████▊| 8341/8455 [07:58<00:05, 21.41it/s]

Preprocessing:  99%|█████████▊| 8344/8455 [07:59<00:05, 21.54it/s]

Preprocessing:  99%|█████████▊| 8347/8455 [07:59<00:04, 21.69it/s]

Preprocessing:  99%|█████████▉| 8350/8455 [07:59<00:04, 21.68it/s]

Preprocessing:  99%|█████████▉| 8353/8455 [07:59<00:04, 21.81it/s]

Preprocessing:  99%|█████████▉| 8356/8455 [07:59<00:04, 22.07it/s]

Preprocessing:  99%|█████████▉| 8359/8455 [07:59<00:04, 22.09it/s]

Preprocessing:  99%|█████████▉| 8362/8455 [07:59<00:04, 20.05it/s]

Preprocessing:  99%|█████████▉| 8365/8455 [08:00<00:05, 17.55it/s]

Preprocessing:  99%|█████████▉| 8367/8455 [08:00<00:05, 16.08it/s]

Preprocessing:  99%|█████████▉| 8370/8455 [08:00<00:04, 17.41it/s]

Preprocessing:  99%|█████████▉| 8373/8455 [08:00<00:04, 18.46it/s]

Preprocessing:  99%|█████████▉| 8376/8455 [08:00<00:04, 19.48it/s]

Preprocessing:  99%|█████████▉| 8379/8455 [08:00<00:03, 20.13it/s]

Preprocessing:  99%|█████████▉| 8382/8455 [08:01<00:03, 20.61it/s]

Preprocessing:  99%|█████████▉| 8385/8455 [08:01<00:03, 20.90it/s]

Preprocessing:  99%|█████████▉| 8388/8455 [08:01<00:03, 20.49it/s]

Preprocessing:  99%|█████████▉| 8391/8455 [08:01<00:03, 20.45it/s]

Preprocessing:  99%|█████████▉| 8394/8455 [08:01<00:02, 20.51it/s]

Preprocessing:  99%|█████████▉| 8397/8455 [08:01<00:02, 20.63it/s]

Preprocessing:  99%|█████████▉| 8400/8455 [08:01<00:02, 20.46it/s]

Preprocessing:  99%|█████████▉| 8403/8455 [08:02<00:02, 20.43it/s]

Preprocessing:  99%|█████████▉| 8406/8455 [08:02<00:02, 20.56it/s]

Preprocessing:  99%|█████████▉| 8409/8455 [08:02<00:02, 20.26it/s]

Preprocessing:  99%|█████████▉| 8412/8455 [08:02<00:02, 20.53it/s]

Preprocessing: 100%|█████████▉| 8415/8455 [08:02<00:01, 20.96it/s]

Preprocessing: 100%|█████████▉| 8418/8455 [08:02<00:01, 21.23it/s]

Preprocessing: 100%|█████████▉| 8421/8455 [08:02<00:01, 21.85it/s]

Preprocessing: 100%|█████████▉| 8424/8455 [08:03<00:01, 21.72it/s]

Preprocessing: 100%|█████████▉| 8427/8455 [08:03<00:01, 17.78it/s]

Preprocessing: 100%|█████████▉| 8429/8455 [08:03<00:01, 18.09it/s]

Preprocessing: 100%|█████████▉| 8432/8455 [08:03<00:01, 19.08it/s]

Preprocessing: 100%|█████████▉| 8435/8455 [08:03<00:01, 19.88it/s]

Preprocessing: 100%|█████████▉| 8438/8455 [08:03<00:00, 20.77it/s]

Preprocessing: 100%|█████████▉| 8441/8455 [08:03<00:00, 21.31it/s]

Preprocessing: 100%|█████████▉| 8444/8455 [08:04<00:00, 21.79it/s]

Preprocessing: 100%|█████████▉| 8447/8455 [08:04<00:00, 21.74it/s]

Preprocessing: 100%|█████████▉| 8450/8455 [08:04<00:00, 21.29it/s]

Preprocessing: 100%|█████████▉| 8453/8455 [08:04<00:00, 21.52it/s]

Preprocessing: 100%|██████████| 8455/8455 [08:04<00:00, 17.45it/s]

## Visualisasi Preprocessing Bertahap

Melihat efek dari setiap tahapan preprocessing secara bertahap.

In [ ]:
# Visualisasi Preprocessing Bertahap secara otomatis untuk semua tahapan
visualize_pipeline_steps(images, labels, PIPELINE)

In [5]:
# Konversi hasil preprocessing ke grayscale khusus untuk ekstraksi fitur GLCM & LBP
print("Mengonversi gambar preprocessed ke grayscale...")
images_preprocessed = np.array([
    cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) for img in tqdm(images_preprocessed_color, desc="Converting to grayscale")
])

Mengonversi gambar preprocessed ke grayscale...

Converting to grayscale:   0%|          | 0/8455 [00:00<?, ?it/s]

Converting to grayscale:   7%|▋         | 616/8455 [00:00<00:01, 6055.72it/s]

Converting to grayscale:  19%|█▉        | 1604/8455 [00:00<00:00, 8237.70it/s]

Converting to grayscale:  35%|███▍      | 2925/8455 [00:00<00:00, 10462.73it/s]

Converting to grayscale:  50%|█████     | 4262/8455 [00:00<00:00, 11530.43it/s]

Converting to grayscale:  66%|██████▌   | 5595/8455 [00:00<00:00, 12169.22it/s]

Converting to grayscale:  81%|████████  | 6813/8455 [00:00<00:00, 11850.82it/s]

Converting to grayscale:  95%|█████████▌| 8063/8455 [00:00<00:00, 12034.72it/s]

Converting to grayscale: 100%|██████████| 8455/8455 [00:00<00:00, 11384.72it/s]

## Feature Extraction - Color & Texture

Kita mengekstrak:
- **HSV Color Stats & Histograms**
- **NRBR Color Stats & Histograms**
- **LBP Texture Histograms**
- **GLCM Texture Features**

In [6]:
# Ekstrasi Fitur Warna HSV
print("Mengekstrak fitur HSV...")
h_hists, s_hists, v_hists, \
h_means, h_stds, h_skews, h_kurts, \
s_means, s_stds, s_skews, s_kurts, \
v_means, v_stds, v_skews, v_kurts = extract_hsv_features(images_preprocessed_color)

# Ekstraksi Fitur Warna NRBR (Normalized Red-Blue Ratio)
print("Mengekstrak fitur NRBR...")
nrbr_hists, nrbr_means, nrbr_stds, nrbr_skews, nrbr_kurts = extract_nrbr_features(images_preprocessed_color)

# Ekstraksi Fitur Tekstur LBP (Local Binary Pattern)
print("Mengekstrak fitur LBP...")
lbp_hists = extract_lbp_features(images_preprocessed, bins=8)

Mengekstrak fitur HSV...

Mengekstrak fitur NRBR...

Mengekstrak fitur LBP...

In [7]:
# Ekstraksi Fitur Tekstur GLCM
def glcm(image, angle):
    if angle == 0:
        angles = [0]
    elif angle == 45:
        angles = [np.pi / 4]
    elif angle == 90:
        angles = [np.pi / 2]
    elif angle == 135:
        angles = [3 * np.pi / 4]
    else:
        raise ValueError("Sudut tidak valid. Gunakan 0, 45, 90, atau 135.")
    return graycomatrix(image, [1], angles, 256, symmetric=True, normed=True)

def correlation(matriks):
    return graycoprops(matriks, 'correlation')[0, 0]
def dissimilarity(matriks):
    return graycoprops(matriks, 'dissimilarity')[0, 0]
def homogenity(matriks):
    return graycoprops(matriks, 'homogeneity')[0, 0]
def contrast(matriks):
    return graycoprops(matriks, 'contrast')[0, 0]
def ASM(matriks):
    return graycoprops(matriks, 'ASM')[0, 0]
def energy(matriks):
    return graycoprops(matriks, 'energy')[0, 0]
def entropyGlcm(matriks):
    return entropy(matriks.ravel())

Kontras0, Kontras45, Kontras90, Kontras135 = [], [], [], []
dissimilarity0, dissimilarity45, dissimilarity90, dissimilarity135 = [], [], [], []
homogenity0, homogenity45, homogenity90, homogenity135 = [], [], [], []
entropy0, entropy45, entropy90, entropy135 = [], [], [], []
ASM0, ASM45, ASM90, ASM135 = [], [], [], []
energy0, energy45, energy90, energy135 = [], [], [], []
correlation0, correlation45, correlation90, correlation135 = [], [], [], []

for i in tqdm(range(len(images_preprocessed)), desc="Extracting GLCM features"):
    g0 = glcm(images_preprocessed[i], 0)
    g45 = glcm(images_preprocessed[i], 45)
    g90 = glcm(images_preprocessed[i], 90)
    g135 = glcm(images_preprocessed[i], 135)
    
    Kontras0.append(contrast(g0))
    Kontras45.append(contrast(g45))
    Kontras90.append(contrast(g90))
    Kontras135.append(contrast(g135))
    
    dissimilarity0.append(dissimilarity(g0))
    dissimilarity45.append(dissimilarity(g45))
    dissimilarity90.append(dissimilarity(g90))
    dissimilarity135.append(dissimilarity(g135))
    
    homogenity0.append(homogenity(g0))
    homogenity45.append(homogenity(g45))
    homogenity90.append(homogenity(g90))
    homogenity135.append(homogenity(g135))
    
    entropy0.append(entropyGlcm(g0))
    entropy45.append(entropyGlcm(g45))
    entropy90.append(entropyGlcm(g90))
    entropy135.append(entropyGlcm(g135))
    
    ASM0.append(ASM(g0))
    ASM45.append(ASM(g45))
    ASM90.append(ASM(g90))
    ASM135.append(ASM(g135))
    
    energy0.append(energy(g0))
    energy45.append(energy(g45))
    energy90.append(energy(g90))
    energy135.append(energy(g135))
    
    correlation0.append(correlation(g0))
    correlation45.append(correlation(g45))
    correlation90.append(correlation(g90))
    correlation135.append(correlation(g135))

Extracting GLCM features:   0%|          | 0/8455 [00:00<?, ?it/s]

Extracting GLCM features:   0%|          | 4/8455 [00:00<03:36, 39.07it/s]

Extracting GLCM features:   0%|          | 13/8455 [00:00<02:06, 66.64it/s]

Extracting GLCM features:   0%|          | 23/8455 [00:00<01:48, 77.47it/s]

Extracting GLCM features:   0%|          | 31/8455 [00:00<01:56, 72.12it/s]

Extracting GLCM features:   0%|          | 40/8455 [00:00<01:50, 76.21it/s]

Extracting GLCM features:   1%|          | 48/8455 [00:00<01:50, 75.75it/s]

Extracting GLCM features:   1%|          | 56/8455 [00:00<01:51, 75.08it/s]

Extracting GLCM features:   1%|          | 64/8455 [00:00<01:51, 75.49it/s]

Extracting GLCM features:   1%|          | 72/8455 [00:00<01:49, 76.30it/s]

Extracting GLCM features:   1%|          | 81/8455 [00:01<01:47, 77.75it/s]

Extracting GLCM features:   1%|          | 89/8455 [00:01<01:46, 78.31it/s]

Extracting GLCM features:   1%|          | 97/8455 [00:01<01:46, 78.46it/s]

Extracting GLCM features:   1%|▏         | 106/8455 [00:01<01:43, 80.43it/s]

Extracting GLCM features:   1%|▏         | 115/8455 [00:01<01:43, 80.81it/s]

Extracting GLCM features:   1%|▏         | 124/8455 [00:01<01:45, 79.23it/s]

Extracting GLCM features:   2%|▏         | 132/8455 [00:01<01:44, 79.30it/s]

Extracting GLCM features:   2%|▏         | 141/8455 [00:01<01:44, 79.88it/s]

Extracting GLCM features:   2%|▏         | 150/8455 [00:01<01:41, 81.81it/s]

Extracting GLCM features:   2%|▏         | 159/8455 [00:02<01:39, 83.07it/s]

Extracting GLCM features:   2%|▏         | 168/8455 [00:02<01:39, 83.06it/s]

Extracting GLCM features:   2%|▏         | 177/8455 [00:02<01:38, 84.07it/s]

Extracting GLCM features:   2%|▏         | 186/8455 [00:02<01:37, 84.63it/s]

Extracting GLCM features:   2%|▏         | 195/8455 [00:02<01:38, 83.81it/s]

Extracting GLCM features:   2%|▏         | 204/8455 [00:02<01:37, 84.37it/s]

Extracting GLCM features:   3%|▎         | 213/8455 [00:02<01:38, 83.89it/s]

Extracting GLCM features:   3%|▎         | 222/8455 [00:02<01:38, 83.66it/s]

Extracting GLCM features:   3%|▎         | 231/8455 [00:02<01:41, 81.16it/s]

Extracting GLCM features:   3%|▎         | 240/8455 [00:03<01:47, 76.45it/s]

Extracting GLCM features:   3%|▎         | 248/8455 [00:03<01:56, 70.66it/s]

Extracting GLCM features:   3%|▎         | 256/8455 [00:03<01:58, 69.31it/s]

Extracting GLCM features:   3%|▎         | 264/8455 [00:03<01:56, 70.40it/s]

Extracting GLCM features:   3%|▎         | 272/8455 [00:03<01:59, 68.56it/s]

Extracting GLCM features:   3%|▎         | 279/8455 [00:03<02:05, 65.16it/s]

Extracting GLCM features:   3%|▎         | 286/8455 [00:03<02:10, 62.57it/s]

Extracting GLCM features:   3%|▎         | 293/8455 [00:03<02:17, 59.47it/s]

Extracting GLCM features:   4%|▎         | 300/8455 [00:04<02:14, 60.42it/s]

Extracting GLCM features:   4%|▎         | 307/8455 [00:04<02:12, 61.34it/s]

Extracting GLCM features:   4%|▎         | 314/8455 [00:04<02:12, 61.33it/s]

Extracting GLCM features:   4%|▍         | 322/8455 [00:04<02:02, 66.16it/s]

Extracting GLCM features:   4%|▍         | 331/8455 [00:04<01:55, 70.39it/s]

Extracting GLCM features:   4%|▍         | 339/8455 [00:04<01:52, 72.15it/s]

Extracting GLCM features:   4%|▍         | 347/8455 [00:04<01:50, 73.56it/s]

Extracting GLCM features:   4%|▍         | 355/8455 [00:04<01:47, 75.16it/s]

Extracting GLCM features:   4%|▍         | 363/8455 [00:04<01:46, 76.20it/s]

Extracting GLCM features:   4%|▍         | 371/8455 [00:04<01:46, 75.92it/s]

Extracting GLCM features:   4%|▍         | 379/8455 [00:05<01:47, 74.93it/s]

Extracting GLCM features:   5%|▍         | 387/8455 [00:05<01:49, 73.76it/s]

Extracting GLCM features:   5%|▍         | 395/8455 [00:05<01:51, 72.14it/s]

Extracting GLCM features:   5%|▍         | 403/8455 [00:05<01:50, 72.89it/s]

Extracting GLCM features:   5%|▍         | 412/8455 [00:05<01:46, 75.65it/s]

Extracting GLCM features:   5%|▍         | 420/8455 [00:05<01:45, 76.23it/s]

Extracting GLCM features:   5%|▌         | 428/8455 [00:05<01:44, 77.12it/s]

Extracting GLCM features:   5%|▌         | 437/8455 [00:05<01:42, 78.60it/s]

Extracting GLCM features:   5%|▌         | 445/8455 [00:05<01:43, 77.75it/s]

Extracting GLCM features:   5%|▌         | 453/8455 [00:06<01:42, 78.02it/s]

Extracting GLCM features:   5%|▌         | 461/8455 [00:06<01:42, 78.02it/s]

Extracting GLCM features:   6%|▌         | 469/8455 [00:06<01:45, 75.69it/s]

Extracting GLCM features:   6%|▌         | 478/8455 [00:06<01:42, 78.07it/s]

Extracting GLCM features:   6%|▌         | 487/8455 [00:06<01:40, 79.14it/s]

Extracting GLCM features:   6%|▌         | 496/8455 [00:06<01:39, 80.11it/s]

Extracting GLCM features:   6%|▌         | 505/8455 [00:06<01:42, 77.20it/s]

Extracting GLCM features:   6%|▌         | 513/8455 [00:06<01:42, 77.85it/s]

Extracting GLCM features:   6%|▌         | 521/8455 [00:06<01:43, 76.31it/s]

Extracting GLCM features:   6%|▋         | 530/8455 [00:07<01:41, 77.86it/s]

Extracting GLCM features:   6%|▋         | 539/8455 [00:07<01:39, 79.40it/s]

Extracting GLCM features:   6%|▋         | 547/8455 [00:07<01:42, 77.17it/s]

Extracting GLCM features:   7%|▋         | 556/8455 [00:07<01:40, 78.38it/s]

Extracting GLCM features:   7%|▋         | 564/8455 [00:07<01:40, 78.52it/s]

Extracting GLCM features:   7%|▋         | 572/8455 [00:07<01:41, 77.40it/s]

Extracting GLCM features:   7%|▋         | 581/8455 [00:07<01:39, 79.17it/s]

Extracting GLCM features:   7%|▋         | 590/8455 [00:07<01:37, 80.34it/s]

Extracting GLCM features:   7%|▋         | 599/8455 [00:07<01:40, 78.06it/s]

Extracting GLCM features:   7%|▋         | 608/8455 [00:08<01:38, 80.00it/s]

Extracting GLCM features:   7%|▋         | 617/8455 [00:08<01:37, 80.60it/s]

Extracting GLCM features:   7%|▋         | 626/8455 [00:08<01:37, 80.62it/s]

Extracting GLCM features:   8%|▊         | 635/8455 [00:08<01:36, 80.84it/s]

Extracting GLCM features:   8%|▊         | 644/8455 [00:08<01:37, 80.26it/s]

Extracting GLCM features:   8%|▊         | 653/8455 [00:08<01:35, 81.61it/s]

Extracting GLCM features:   8%|▊         | 662/8455 [00:08<01:36, 80.72it/s]

Extracting GLCM features:   8%|▊         | 671/8455 [00:08<01:34, 82.09it/s]

Extracting GLCM features:   8%|▊         | 680/8455 [00:08<01:36, 80.45it/s]

Extracting GLCM features:   8%|▊         | 689/8455 [00:09<01:35, 81.61it/s]

Extracting GLCM features:   8%|▊         | 698/8455 [00:09<01:35, 81.37it/s]

Extracting GLCM features:   8%|▊         | 707/8455 [00:09<01:36, 80.58it/s]

Extracting GLCM features:   8%|▊         | 716/8455 [00:09<01:34, 81.59it/s]

Extracting GLCM features:   9%|▊         | 725/8455 [00:09<01:34, 82.08it/s]

Extracting GLCM features:   9%|▊         | 734/8455 [00:09<01:34, 81.38it/s]

Extracting GLCM features:   9%|▉         | 743/8455 [00:09<01:35, 81.00it/s]

Extracting GLCM features:   9%|▉         | 752/8455 [00:09<01:34, 81.78it/s]

Extracting GLCM features:   9%|▉         | 761/8455 [00:09<01:33, 82.23it/s]

Extracting GLCM features:   9%|▉         | 770/8455 [00:10<01:37, 78.55it/s]

Extracting GLCM features:   9%|▉         | 778/8455 [00:10<01:38, 77.76it/s]

Extracting GLCM features:   9%|▉         | 786/8455 [00:10<01:38, 77.97it/s]

Extracting GLCM features:   9%|▉         | 794/8455 [00:10<01:40, 76.36it/s]

Extracting GLCM features:   9%|▉         | 802/8455 [00:10<01:47, 71.48it/s]

Extracting GLCM features:  10%|▉         | 810/8455 [00:10<01:48, 70.32it/s]

Extracting GLCM features:  10%|▉         | 818/8455 [00:10<01:47, 71.08it/s]

Extracting GLCM features:  10%|▉         | 827/8455 [00:10<01:43, 74.00it/s]

Extracting GLCM features:  10%|▉         | 835/8455 [00:10<01:41, 75.30it/s]

Extracting GLCM features:  10%|▉         | 843/8455 [00:11<01:40, 76.02it/s]

Extracting GLCM features:  10%|█         | 851/8455 [00:11<01:48, 69.89it/s]

Extracting GLCM features:  10%|█         | 859/8455 [00:11<01:49, 69.48it/s]

Extracting GLCM features:  10%|█         | 867/8455 [00:11<01:44, 72.28it/s]

Extracting GLCM features:  10%|█         | 875/8455 [00:11<01:43, 73.03it/s]

Extracting GLCM features:  10%|█         | 884/8455 [00:11<01:40, 75.41it/s]

Extracting GLCM features:  11%|█         | 893/8455 [00:11<01:38, 76.52it/s]

Extracting GLCM features:  11%|█         | 902/8455 [00:11<01:36, 78.08it/s]

Extracting GLCM features:  11%|█         | 910/8455 [00:11<01:41, 74.57it/s]

Extracting GLCM features:  11%|█         | 918/8455 [00:12<01:46, 71.00it/s]

Extracting GLCM features:  11%|█         | 926/8455 [00:12<01:49, 68.77it/s]

Extracting GLCM features:  11%|█         | 933/8455 [00:12<01:53, 66.47it/s]

Extracting GLCM features:  11%|█         | 940/8455 [00:12<02:01, 61.81it/s]

Extracting GLCM features:  11%|█         | 947/8455 [00:12<02:05, 59.86it/s]

Extracting GLCM features:  11%|█▏        | 954/8455 [00:12<02:01, 61.56it/s]

Extracting GLCM features:  11%|█▏        | 962/8455 [00:12<01:53, 65.91it/s]

Extracting GLCM features:  11%|█▏        | 970/8455 [00:12<01:47, 69.57it/s]

Extracting GLCM features:  12%|█▏        | 979/8455 [00:12<01:41, 73.93it/s]

Extracting GLCM features:  12%|█▏        | 988/8455 [00:13<01:38, 76.00it/s]

Extracting GLCM features:  12%|█▏        | 997/8455 [00:13<01:36, 77.48it/s]

Extracting GLCM features:  12%|█▏        | 1006/8455 [00:13<01:34, 79.17it/s]

Extracting GLCM features:  12%|█▏        | 1015/8455 [00:13<01:33, 79.43it/s]

Extracting GLCM features:  12%|█▏        | 1023/8455 [00:13<01:36, 76.76it/s]

Extracting GLCM features:  12%|█▏        | 1032/8455 [00:13<01:34, 78.65it/s]

Extracting GLCM features:  12%|█▏        | 1041/8455 [00:13<01:32, 80.28it/s]

Extracting GLCM features:  12%|█▏        | 1050/8455 [00:13<01:36, 76.51it/s]

Extracting GLCM features:  13%|█▎        | 1059/8455 [00:13<01:34, 77.94it/s]

Extracting GLCM features:  13%|█▎        | 1067/8455 [00:14<01:34, 78.48it/s]

Extracting GLCM features:  13%|█▎        | 1075/8455 [00:14<01:34, 78.23it/s]

Extracting GLCM features:  13%|█▎        | 1084/8455 [00:14<01:33, 79.06it/s]

Extracting GLCM features:  13%|█▎        | 1093/8455 [00:14<01:30, 81.47it/s]

Extracting GLCM features:  13%|█▎        | 1102/8455 [00:14<01:32, 79.76it/s]

Extracting GLCM features:  13%|█▎        | 1111/8455 [00:14<01:29, 81.64it/s]

Extracting GLCM features:  13%|█▎        | 1120/8455 [00:14<01:29, 81.90it/s]

Extracting GLCM features:  13%|█▎        | 1129/8455 [00:14<01:29, 81.75it/s]

Extracting GLCM features:  13%|█▎        | 1138/8455 [00:14<01:29, 81.59it/s]

Extracting GLCM features:  14%|█▎        | 1147/8455 [00:15<01:33, 78.46it/s]

Extracting GLCM features:  14%|█▎        | 1156/8455 [00:15<01:31, 79.86it/s]

Extracting GLCM features:  14%|█▍        | 1165/8455 [00:15<01:30, 80.26it/s]

Extracting GLCM features:  14%|█▍        | 1174/8455 [00:15<01:29, 81.15it/s]

Extracting GLCM features:  14%|█▍        | 1183/8455 [00:15<01:31, 79.74it/s]

Extracting GLCM features:  14%|█▍        | 1191/8455 [00:15<01:31, 79.40it/s]

Extracting GLCM features:  14%|█▍        | 1199/8455 [00:15<01:31, 79.55it/s]

Extracting GLCM features:  14%|█▍        | 1208/8455 [00:15<01:28, 81.84it/s]

Extracting GLCM features:  14%|█▍        | 1217/8455 [00:15<01:28, 81.97it/s]

Extracting GLCM features:  15%|█▍        | 1226/8455 [00:16<01:27, 82.44it/s]

Extracting GLCM features:  15%|█▍        | 1235/8455 [00:16<01:28, 81.89it/s]

Extracting GLCM features:  15%|█▍        | 1244/8455 [00:16<01:29, 80.86it/s]

Extracting GLCM features:  15%|█▍        | 1253/8455 [00:16<01:28, 81.67it/s]

Extracting GLCM features:  15%|█▍        | 1262/8455 [00:16<01:28, 81.38it/s]

Extracting GLCM features:  15%|█▌        | 1272/8455 [00:16<01:25, 84.19it/s]

Extracting GLCM features:  15%|█▌        | 1281/8455 [00:16<01:24, 84.88it/s]

Extracting GLCM features:  15%|█▌        | 1290/8455 [00:16<01:23, 85.33it/s]

Extracting GLCM features:  15%|█▌        | 1299/8455 [00:16<01:23, 85.99it/s]

Extracting GLCM features:  15%|█▌        | 1308/8455 [00:17<01:22, 86.90it/s]

Extracting GLCM features:  16%|█▌        | 1317/8455 [00:17<01:21, 87.25it/s]

Extracting GLCM features:  16%|█▌        | 1326/8455 [00:17<01:21, 87.80it/s]

Extracting GLCM features:  16%|█▌        | 1335/8455 [00:17<01:21, 86.84it/s]

Extracting GLCM features:  16%|█▌        | 1344/8455 [00:17<01:21, 87.69it/s]

Extracting GLCM features:  16%|█▌        | 1353/8455 [00:17<01:22, 86.29it/s]

Extracting GLCM features:  16%|█▌        | 1362/8455 [00:17<01:22, 85.50it/s]

Extracting GLCM features:  16%|█▌        | 1371/8455 [00:17<01:22, 85.53it/s]

Extracting GLCM features:  16%|█▋        | 1380/8455 [00:17<01:28, 80.27it/s]

Extracting GLCM features:  16%|█▋        | 1389/8455 [00:17<01:28, 80.15it/s]

Extracting GLCM features:  17%|█▋        | 1398/8455 [00:18<01:26, 81.63it/s]

Extracting GLCM features:  17%|█▋        | 1407/8455 [00:18<01:28, 80.05it/s]

Extracting GLCM features:  17%|█▋        | 1416/8455 [00:18<01:25, 81.99it/s]

Extracting GLCM features:  17%|█▋        | 1425/8455 [00:18<01:26, 81.31it/s]

Extracting GLCM features:  17%|█▋        | 1434/8455 [00:18<01:25, 82.10it/s]

Extracting GLCM features:  17%|█▋        | 1444/8455 [00:18<01:23, 83.97it/s]

Extracting GLCM features:  17%|█▋        | 1453/8455 [00:18<01:21, 85.62it/s]

Extracting GLCM features:  17%|█▋        | 1462/8455 [00:18<01:23, 83.34it/s]

Extracting GLCM features:  17%|█▋        | 1471/8455 [00:18<01:23, 83.78it/s]

Extracting GLCM features:  18%|█▊        | 1480/8455 [00:19<01:25, 81.11it/s]

Extracting GLCM features:  18%|█▊        | 1489/8455 [00:19<01:24, 82.34it/s]

Extracting GLCM features:  18%|█▊        | 1498/8455 [00:19<01:22, 84.04it/s]

Extracting GLCM features:  18%|█▊        | 1507/8455 [00:19<01:22, 84.73it/s]

Extracting GLCM features:  18%|█▊        | 1516/8455 [00:19<01:23, 83.54it/s]

Extracting GLCM features:  18%|█▊        | 1525/8455 [00:19<01:21, 85.05it/s]

Extracting GLCM features:  18%|█▊        | 1534/8455 [00:19<01:21, 85.05it/s]

Extracting GLCM features:  18%|█▊        | 1543/8455 [00:19<01:21, 84.92it/s]

Extracting GLCM features:  18%|█▊        | 1552/8455 [00:19<01:23, 82.82it/s]

Extracting GLCM features:  18%|█▊        | 1562/8455 [00:20<01:20, 85.45it/s]

Extracting GLCM features:  19%|█▊        | 1571/8455 [00:20<01:25, 80.85it/s]

Extracting GLCM features:  19%|█▊        | 1580/8455 [00:20<01:23, 82.73it/s]

Extracting GLCM features:  19%|█▉        | 1589/8455 [00:20<01:23, 82.08it/s]

Extracting GLCM features:  19%|█▉        | 1598/8455 [00:20<01:23, 81.88it/s]

Extracting GLCM features:  19%|█▉        | 1607/8455 [00:20<01:22, 82.99it/s]

Extracting GLCM features:  19%|█▉        | 1616/8455 [00:20<01:20, 84.93it/s]

Extracting GLCM features:  19%|█▉        | 1625/8455 [00:20<01:21, 83.93it/s]

Extracting GLCM features:  19%|█▉        | 1634/8455 [00:20<01:35, 71.27it/s]

Extracting GLCM features:  19%|█▉        | 1642/8455 [00:21<01:40, 67.89it/s]

Extracting GLCM features:  20%|█▉        | 1651/8455 [00:21<01:34, 72.26it/s]

Extracting GLCM features:  20%|█▉        | 1660/8455 [00:21<01:29, 76.32it/s]

Extracting GLCM features:  20%|█▉        | 1669/8455 [00:21<01:26, 78.20it/s]

Extracting GLCM features:  20%|█▉        | 1677/8455 [00:21<01:26, 78.37it/s]

Extracting GLCM features:  20%|█▉        | 1686/8455 [00:21<01:24, 80.26it/s]

Extracting GLCM features:  20%|██        | 1695/8455 [00:21<01:23, 81.28it/s]

Extracting GLCM features:  20%|██        | 1704/8455 [00:21<01:21, 82.73it/s]

Extracting GLCM features:  20%|██        | 1713/8455 [00:21<01:20, 83.90it/s]

Extracting GLCM features:  20%|██        | 1722/8455 [00:22<01:22, 81.42it/s]

Extracting GLCM features:  20%|██        | 1731/8455 [00:22<01:28, 75.79it/s]

Extracting GLCM features:  21%|██        | 1739/8455 [00:22<01:28, 76.03it/s]

Extracting GLCM features:  21%|██        | 1747/8455 [00:22<01:31, 73.56it/s]

Extracting GLCM features:  21%|██        | 1755/8455 [00:22<01:36, 69.75it/s]

Extracting GLCM features:  21%|██        | 1763/8455 [00:22<01:39, 67.11it/s]

Extracting GLCM features:  21%|██        | 1771/8455 [00:22<01:36, 69.09it/s]

Extracting GLCM features:  21%|██        | 1779/8455 [00:22<01:35, 70.09it/s]

Extracting GLCM features:  21%|██        | 1788/8455 [00:23<01:30, 74.04it/s]

Extracting GLCM features:  21%|██        | 1796/8455 [00:23<01:28, 75.03it/s]

Extracting GLCM features:  21%|██▏       | 1804/8455 [00:23<01:29, 74.41it/s]

Extracting GLCM features:  21%|██▏       | 1813/8455 [00:23<01:24, 78.34it/s]

Extracting GLCM features:  22%|██▏       | 1822/8455 [00:23<01:22, 80.39it/s]

Extracting GLCM features:  22%|██▏       | 1831/8455 [00:23<01:20, 81.94it/s]

Extracting GLCM features:  22%|██▏       | 1840/8455 [00:23<01:21, 80.85it/s]

Extracting GLCM features:  22%|██▏       | 1849/8455 [00:23<01:20, 82.18it/s]

Extracting GLCM features:  22%|██▏       | 1858/8455 [00:23<01:18, 83.67it/s]

Extracting GLCM features:  22%|██▏       | 1867/8455 [00:23<01:18, 83.87it/s]

Extracting GLCM features:  22%|██▏       | 1876/8455 [00:24<01:17, 84.44it/s]

Extracting GLCM features:  22%|██▏       | 1885/8455 [00:24<01:17, 85.12it/s]

Extracting GLCM features:  22%|██▏       | 1894/8455 [00:24<01:18, 83.81it/s]

Extracting GLCM features:  23%|██▎       | 1903/8455 [00:24<01:17, 84.77it/s]

Extracting GLCM features:  23%|██▎       | 1912/8455 [00:24<01:16, 85.21it/s]

Extracting GLCM features:  23%|██▎       | 1921/8455 [00:24<01:16, 85.08it/s]

Extracting GLCM features:  23%|██▎       | 1930/8455 [00:24<01:17, 84.21it/s]

Extracting GLCM features:  23%|██▎       | 1939/8455 [00:24<01:17, 83.61it/s]

Extracting GLCM features:  23%|██▎       | 1948/8455 [00:24<01:18, 82.41it/s]

Extracting GLCM features:  23%|██▎       | 1957/8455 [00:25<01:17, 83.44it/s]

Extracting GLCM features:  23%|██▎       | 1966/8455 [00:25<01:16, 84.63it/s]

Extracting GLCM features:  23%|██▎       | 1975/8455 [00:25<01:16, 84.56it/s]

Extracting GLCM features:  23%|██▎       | 1984/8455 [00:25<01:17, 83.99it/s]

Extracting GLCM features:  24%|██▎       | 1993/8455 [00:25<01:19, 81.00it/s]

Extracting GLCM features:  24%|██▎       | 2002/8455 [00:25<01:20, 79.89it/s]

Extracting GLCM features:  24%|██▍       | 2011/8455 [00:25<01:20, 79.72it/s]

Extracting GLCM features:  24%|██▍       | 2019/8455 [00:25<01:22, 77.87it/s]

Extracting GLCM features:  24%|██▍       | 2028/8455 [00:25<01:20, 80.29it/s]

Extracting GLCM features:  24%|██▍       | 2038/8455 [00:26<01:17, 83.20it/s]

Extracting GLCM features:  24%|██▍       | 2047/8455 [00:26<01:17, 83.19it/s]

Extracting GLCM features:  24%|██▍       | 2056/8455 [00:26<01:16, 83.37it/s]

Extracting GLCM features:  24%|██▍       | 2065/8455 [00:26<01:15, 84.18it/s]

Extracting GLCM features:  25%|██▍       | 2074/8455 [00:26<01:15, 84.49it/s]

Extracting GLCM features:  25%|██▍       | 2083/8455 [00:26<01:14, 85.37it/s]

Extracting GLCM features:  25%|██▍       | 2092/8455 [00:26<01:16, 83.24it/s]

Extracting GLCM features:  25%|██▍       | 2101/8455 [00:26<01:17, 82.42it/s]

Extracting GLCM features:  25%|██▍       | 2110/8455 [00:26<01:24, 75.06it/s]

Extracting GLCM features:  25%|██▌       | 2118/8455 [00:27<01:32, 68.31it/s]

Extracting GLCM features:  25%|██▌       | 2126/8455 [00:27<01:32, 68.19it/s]

Extracting GLCM features:  25%|██▌       | 2133/8455 [00:27<01:33, 67.60it/s]

Extracting GLCM features:  25%|██▌       | 2142/8455 [00:27<01:26, 73.16it/s]

Extracting GLCM features:  25%|██▌       | 2151/8455 [00:27<01:22, 76.85it/s]

Extracting GLCM features:  26%|██▌       | 2160/8455 [00:27<01:19, 79.43it/s]

Extracting GLCM features:  26%|██▌       | 2170/8455 [00:27<01:16, 82.11it/s]

Extracting GLCM features:  26%|██▌       | 2179/8455 [00:27<01:16, 81.63it/s]

Extracting GLCM features:  26%|██▌       | 2188/8455 [00:27<01:18, 79.58it/s]

Extracting GLCM features:  26%|██▌       | 2197/8455 [00:28<01:18, 80.18it/s]

Extracting GLCM features:  26%|██▌       | 2206/8455 [00:28<01:17, 80.69it/s]

Extracting GLCM features:  26%|██▌       | 2215/8455 [00:28<01:15, 82.41it/s]

Extracting GLCM features:  26%|██▋       | 2224/8455 [00:28<01:14, 83.14it/s]

Extracting GLCM features:  26%|██▋       | 2233/8455 [00:28<01:13, 84.18it/s]

Extracting GLCM features:  27%|██▋       | 2242/8455 [00:28<01:16, 81.30it/s]

Extracting GLCM features:  27%|██▋       | 2251/8455 [00:28<01:17, 79.96it/s]

Extracting GLCM features:  27%|██▋       | 2260/8455 [00:28<01:18, 79.19it/s]

Extracting GLCM features:  27%|██▋       | 2270/8455 [00:28<01:14, 82.54it/s]

Extracting GLCM features:  27%|██▋       | 2279/8455 [00:29<01:15, 81.56it/s]

Extracting GLCM features:  27%|██▋       | 2288/8455 [00:29<01:17, 79.85it/s]

Extracting GLCM features:  27%|██▋       | 2297/8455 [00:29<01:19, 77.76it/s]

Extracting GLCM features:  27%|██▋       | 2305/8455 [00:29<01:20, 76.84it/s]

Extracting GLCM features:  27%|██▋       | 2314/8455 [00:29<01:18, 78.10it/s]

Extracting GLCM features:  27%|██▋       | 2323/8455 [00:29<01:17, 78.65it/s]

Extracting GLCM features:  28%|██▊       | 2331/8455 [00:29<01:18, 78.27it/s]

Extracting GLCM features:  28%|██▊       | 2340/8455 [00:29<01:17, 79.07it/s]

Extracting GLCM features:  28%|██▊       | 2349/8455 [00:29<01:15, 80.34it/s]

Extracting GLCM features:  28%|██▊       | 2358/8455 [00:30<01:14, 81.85it/s]

Extracting GLCM features:  28%|██▊       | 2367/8455 [00:30<01:18, 77.38it/s]

Extracting GLCM features:  28%|██▊       | 2376/8455 [00:30<01:18, 77.84it/s]

Extracting GLCM features:  28%|██▊       | 2385/8455 [00:30<01:16, 78.97it/s]

Extracting GLCM features:  28%|██▊       | 2393/8455 [00:30<01:20, 75.72it/s]

Extracting GLCM features:  28%|██▊       | 2401/8455 [00:30<01:19, 76.03it/s]

Extracting GLCM features:  28%|██▊       | 2409/8455 [00:30<01:19, 76.20it/s]

Extracting GLCM features:  29%|██▊       | 2418/8455 [00:30<01:16, 79.14it/s]

Extracting GLCM features:  29%|██▊       | 2427/8455 [00:30<01:13, 81.82it/s]

Extracting GLCM features:  29%|██▉       | 2436/8455 [00:31<01:15, 79.41it/s]

Extracting GLCM features:  29%|██▉       | 2445/8455 [00:31<01:15, 79.63it/s]

Extracting GLCM features:  29%|██▉       | 2453/8455 [00:31<01:16, 78.47it/s]

Extracting GLCM features:  29%|██▉       | 2461/8455 [00:31<01:18, 76.24it/s]

Extracting GLCM features:  29%|██▉       | 2469/8455 [00:31<01:22, 72.51it/s]

Extracting GLCM features:  29%|██▉       | 2477/8455 [00:31<01:25, 70.11it/s]

Extracting GLCM features:  29%|██▉       | 2485/8455 [00:31<01:26, 69.36it/s]

Extracting GLCM features:  29%|██▉       | 2493/8455 [00:31<01:26, 68.67it/s]

Extracting GLCM features:  30%|██▉       | 2501/8455 [00:32<01:24, 70.26it/s]

Extracting GLCM features:  30%|██▉       | 2510/8455 [00:32<01:22, 72.06it/s]

Extracting GLCM features:  30%|██▉       | 2518/8455 [00:32<01:23, 71.08it/s]

Extracting GLCM features:  30%|██▉       | 2526/8455 [00:32<01:21, 72.44it/s]

Extracting GLCM features:  30%|██▉       | 2534/8455 [00:32<01:26, 68.54it/s]

Extracting GLCM features:  30%|███       | 2542/8455 [00:32<01:25, 69.38it/s]

Extracting GLCM features:  30%|███       | 2551/8455 [00:32<01:21, 72.84it/s]

Extracting GLCM features:  30%|███       | 2560/8455 [00:32<01:18, 75.34it/s]

Extracting GLCM features:  30%|███       | 2569/8455 [00:32<01:16, 77.13it/s]

Extracting GLCM features:  30%|███       | 2577/8455 [00:33<01:15, 77.90it/s]

Extracting GLCM features:  31%|███       | 2585/8455 [00:33<01:20, 72.54it/s]

Extracting GLCM features:  31%|███       | 2593/8455 [00:33<01:19, 73.88it/s]

Extracting GLCM features:  31%|███       | 2601/8455 [00:33<01:20, 72.71it/s]

Extracting GLCM features:  31%|███       | 2609/8455 [00:33<01:21, 71.86it/s]

Extracting GLCM features:  31%|███       | 2618/8455 [00:33<01:17, 75.14it/s]

Extracting GLCM features:  31%|███       | 2626/8455 [00:33<01:28, 65.72it/s]

Extracting GLCM features:  31%|███       | 2634/8455 [00:33<01:26, 67.60it/s]

Extracting GLCM features:  31%|███       | 2642/8455 [00:33<01:23, 69.76it/s]

Extracting GLCM features:  31%|███▏      | 2651/8455 [00:34<01:17, 74.87it/s]

Extracting GLCM features:  31%|███▏      | 2660/8455 [00:34<01:16, 75.81it/s]

Extracting GLCM features:  32%|███▏      | 2669/8455 [00:34<01:13, 79.09it/s]

Extracting GLCM features:  32%|███▏      | 2678/8455 [00:34<01:12, 79.39it/s]

Extracting GLCM features:  32%|███▏      | 2687/8455 [00:34<01:10, 82.11it/s]

Extracting GLCM features:  32%|███▏      | 2696/8455 [00:34<01:11, 81.06it/s]

Extracting GLCM features:  32%|███▏      | 2705/8455 [00:34<01:10, 81.20it/s]

Extracting GLCM features:  32%|███▏      | 2714/8455 [00:34<01:08, 83.29it/s]

Extracting GLCM features:  32%|███▏      | 2723/8455 [00:34<01:07, 85.17it/s]

Extracting GLCM features:  32%|███▏      | 2732/8455 [00:35<01:08, 84.07it/s]

Extracting GLCM features:  32%|███▏      | 2741/8455 [00:35<01:07, 85.11it/s]

Extracting GLCM features:  33%|███▎      | 2751/8455 [00:35<01:05, 87.60it/s]

Extracting GLCM features:  33%|███▎      | 2760/8455 [00:35<01:04, 87.90it/s]

Extracting GLCM features:  33%|███▎      | 2769/8455 [00:35<01:04, 88.37it/s]

Extracting GLCM features:  33%|███▎      | 2778/8455 [00:35<01:03, 88.79it/s]

Extracting GLCM features:  33%|███▎      | 2788/8455 [00:35<01:02, 90.00it/s]

Extracting GLCM features:  33%|███▎      | 2798/8455 [00:35<01:06, 85.52it/s]

Extracting GLCM features:  33%|███▎      | 2807/8455 [00:35<01:11, 79.29it/s]

Extracting GLCM features:  33%|███▎      | 2816/8455 [00:36<01:09, 81.54it/s]

Extracting GLCM features:  33%|███▎      | 2825/8455 [00:36<01:09, 81.44it/s]

Extracting GLCM features:  34%|███▎      | 2835/8455 [00:36<01:06, 85.01it/s]

Extracting GLCM features:  34%|███▎      | 2845/8455 [00:36<01:04, 86.54it/s]

Extracting GLCM features:  34%|███▍      | 2855/8455 [00:36<01:04, 87.45it/s]

Extracting GLCM features:  34%|███▍      | 2865/8455 [00:36<01:02, 88.74it/s]

Extracting GLCM features:  34%|███▍      | 2874/8455 [00:36<01:04, 86.59it/s]

Extracting GLCM features:  34%|███▍      | 2884/8455 [00:36<01:02, 89.27it/s]

Extracting GLCM features:  34%|███▍      | 2893/8455 [00:36<01:04, 86.46it/s]

Extracting GLCM features:  34%|███▍      | 2903/8455 [00:37<01:03, 87.96it/s]

Extracting GLCM features:  34%|███▍      | 2913/8455 [00:37<01:02, 89.25it/s]

Extracting GLCM features:  35%|███▍      | 2922/8455 [00:37<01:03, 87.45it/s]

Extracting GLCM features:  35%|███▍      | 2931/8455 [00:37<01:03, 87.44it/s]

Extracting GLCM features:  35%|███▍      | 2940/8455 [00:37<01:03, 87.25it/s]

Extracting GLCM features:  35%|███▍      | 2949/8455 [00:37<01:02, 87.93it/s]

Extracting GLCM features:  35%|███▍      | 2958/8455 [00:37<01:03, 85.98it/s]

Extracting GLCM features:  35%|███▌      | 2967/8455 [00:37<01:04, 85.46it/s]

Extracting GLCM features:  35%|███▌      | 2976/8455 [00:37<01:04, 84.63it/s]

Extracting GLCM features:  35%|███▌      | 2986/8455 [00:37<01:03, 86.25it/s]

Extracting GLCM features:  35%|███▌      | 2996/8455 [00:38<01:01, 88.32it/s]

Extracting GLCM features:  36%|███▌      | 3005/8455 [00:38<01:03, 85.31it/s]

Extracting GLCM features:  36%|███▌      | 3014/8455 [00:38<01:04, 84.68it/s]

Extracting GLCM features:  36%|███▌      | 3023/8455 [00:38<01:04, 84.35it/s]

Extracting GLCM features:  36%|███▌      | 3033/8455 [00:38<01:02, 86.94it/s]

Extracting GLCM features:  36%|███▌      | 3042/8455 [00:38<01:03, 85.51it/s]

Extracting GLCM features:  36%|███▌      | 3052/8455 [00:38<01:01, 87.89it/s]

Extracting GLCM features:  36%|███▌      | 3062/8455 [00:38<01:00, 88.44it/s]

Extracting GLCM features:  36%|███▋      | 3071/8455 [00:38<01:00, 88.68it/s]

Extracting GLCM features:  36%|███▋      | 3081/8455 [00:39<00:59, 90.32it/s]

Extracting GLCM features:  37%|███▋      | 3091/8455 [00:39<00:59, 90.16it/s]

Extracting GLCM features:  37%|███▋      | 3101/8455 [00:39<00:59, 90.57it/s]

Extracting GLCM features:  37%|███▋      | 3111/8455 [00:39<00:59, 90.11it/s]

Extracting GLCM features:  37%|███▋      | 3121/8455 [00:39<00:59, 90.29it/s]

Extracting GLCM features:  37%|███▋      | 3131/8455 [00:39<00:58, 90.98it/s]

Extracting GLCM features:  37%|███▋      | 3141/8455 [00:39<00:58, 90.88it/s]

Extracting GLCM features:  37%|███▋      | 3151/8455 [00:39<01:00, 87.10it/s]

Extracting GLCM features:  37%|███▋      | 3161/8455 [00:39<00:59, 89.57it/s]

Extracting GLCM features:  37%|███▋      | 3170/8455 [00:40<00:59, 89.55it/s]

Extracting GLCM features:  38%|███▊      | 3179/8455 [00:40<01:02, 85.03it/s]

Extracting GLCM features:  38%|███▊      | 3188/8455 [00:40<01:03, 82.97it/s]

Extracting GLCM features:  38%|███▊      | 3197/8455 [00:40<01:02, 84.05it/s]

Extracting GLCM features:  38%|███▊      | 3206/8455 [00:40<01:01, 85.33it/s]

Extracting GLCM features:  38%|███▊      | 3216/8455 [00:40<01:00, 86.09it/s]

Extracting GLCM features:  38%|███▊      | 3225/8455 [00:40<01:00, 86.72it/s]

Extracting GLCM features:  38%|███▊      | 3235/8455 [00:40<00:58, 89.01it/s]

Extracting GLCM features:  38%|███▊      | 3245/8455 [00:40<00:57, 89.97it/s]

Extracting GLCM features:  38%|███▊      | 3255/8455 [00:41<00:59, 87.39it/s]

Extracting GLCM features:  39%|███▊      | 3265/8455 [00:41<00:58, 89.15it/s]

Extracting GLCM features:  39%|███▊      | 3275/8455 [00:41<00:57, 90.42it/s]

Extracting GLCM features:  39%|███▉      | 3285/8455 [00:41<00:57, 89.90it/s]

Extracting GLCM features:  39%|███▉      | 3295/8455 [00:41<01:03, 81.79it/s]

Extracting GLCM features:  39%|███▉      | 3304/8455 [00:41<01:04, 80.48it/s]

Extracting GLCM features:  39%|███▉      | 3314/8455 [00:41<01:01, 83.89it/s]

Extracting GLCM features:  39%|███▉      | 3324/8455 [00:41<00:59, 86.69it/s]

Extracting GLCM features:  39%|███▉      | 3333/8455 [00:41<00:58, 86.87it/s]

Extracting GLCM features:  40%|███▉      | 3342/8455 [00:42<01:06, 76.86it/s]

Extracting GLCM features:  40%|███▉      | 3350/8455 [00:42<01:12, 70.90it/s]

Extracting GLCM features:  40%|███▉      | 3359/8455 [00:42<01:07, 75.23it/s]

Extracting GLCM features:  40%|███▉      | 3369/8455 [00:42<01:03, 79.52it/s]

Extracting GLCM features:  40%|███▉      | 3378/8455 [00:42<01:02, 80.84it/s]

Extracting GLCM features:  40%|████      | 3387/8455 [00:42<01:02, 81.57it/s]

Extracting GLCM features:  40%|████      | 3396/8455 [00:42<01:01, 82.92it/s]

Extracting GLCM features:  40%|████      | 3406/8455 [00:42<00:58, 86.15it/s]

Extracting GLCM features:  40%|████      | 3416/8455 [00:42<00:57, 87.35it/s]

Extracting GLCM features:  41%|████      | 3426/8455 [00:43<00:56, 88.62it/s]

Extracting GLCM features:  41%|████      | 3436/8455 [00:43<00:55, 90.67it/s]

Extracting GLCM features:  41%|████      | 3446/8455 [00:43<00:56, 87.94it/s]

Extracting GLCM features:  41%|████      | 3455/8455 [00:43<00:58, 85.81it/s]

Extracting GLCM features:  41%|████      | 3464/8455 [00:43<00:58, 85.97it/s]

Extracting GLCM features:  41%|████      | 3473/8455 [00:43<00:57, 85.91it/s]

Extracting GLCM features:  41%|████      | 3482/8455 [00:43<00:57, 86.94it/s]

Extracting GLCM features:  41%|████▏     | 3492/8455 [00:43<00:55, 88.89it/s]

Extracting GLCM features:  41%|████▏     | 3502/8455 [00:43<00:55, 89.72it/s]

Extracting GLCM features:  42%|████▏     | 3512/8455 [00:44<00:54, 91.23it/s]

Extracting GLCM features:  42%|████▏     | 3522/8455 [00:44<00:55, 88.69it/s]

Extracting GLCM features:  42%|████▏     | 3531/8455 [00:44<00:55, 89.01it/s]

Extracting GLCM features:  42%|████▏     | 3540/8455 [00:44<00:56, 86.80it/s]

Extracting GLCM features:  42%|████▏     | 3549/8455 [00:44<01:00, 80.84it/s]

Extracting GLCM features:  42%|████▏     | 3558/8455 [00:44<01:01, 79.99it/s]

Extracting GLCM features:  42%|████▏     | 3567/8455 [00:44<00:59, 81.72it/s]

Extracting GLCM features:  42%|████▏     | 3576/8455 [00:44<00:58, 82.77it/s]

Extracting GLCM features:  42%|████▏     | 3586/8455 [00:44<00:56, 85.99it/s]

Extracting GLCM features:  43%|████▎     | 3595/8455 [00:45<00:58, 83.24it/s]

Extracting GLCM features:  43%|████▎     | 3605/8455 [00:45<00:56, 85.63it/s]

Extracting GLCM features:  43%|████▎     | 3614/8455 [00:45<00:56, 86.32it/s]

Extracting GLCM features:  43%|████▎     | 3624/8455 [00:45<00:55, 86.90it/s]

Extracting GLCM features:  43%|████▎     | 3633/8455 [00:45<00:54, 87.68it/s]

Extracting GLCM features:  43%|████▎     | 3643/8455 [00:45<00:54, 88.70it/s]

Extracting GLCM features:  43%|████▎     | 3653/8455 [00:45<00:53, 89.01it/s]

Extracting GLCM features:  43%|████▎     | 3663/8455 [00:45<00:53, 88.97it/s]

Extracting GLCM features:  43%|████▎     | 3672/8455 [00:45<00:53, 88.97it/s]

Extracting GLCM features:  44%|████▎     | 3682/8455 [00:46<00:52, 90.27it/s]

Extracting GLCM features:  44%|████▎     | 3692/8455 [00:46<00:53, 89.00it/s]

Extracting GLCM features:  44%|████▍     | 3702/8455 [00:46<00:52, 90.13it/s]

Extracting GLCM features:  44%|████▍     | 3712/8455 [00:46<00:54, 87.21it/s]

Extracting GLCM features:  44%|████▍     | 3721/8455 [00:46<00:59, 79.38it/s]

Extracting GLCM features:  44%|████▍     | 3730/8455 [00:46<00:59, 80.05it/s]

Extracting GLCM features:  44%|████▍     | 3739/8455 [00:46<00:57, 82.11it/s]

Extracting GLCM features:  44%|████▍     | 3749/8455 [00:46<00:55, 84.41it/s]

Extracting GLCM features:  44%|████▍     | 3758/8455 [00:46<00:54, 85.55it/s]

Extracting GLCM features:  45%|████▍     | 3767/8455 [00:47<00:54, 85.57it/s]

Extracting GLCM features:  45%|████▍     | 3776/8455 [00:47<00:54, 86.16it/s]

Extracting GLCM features:  45%|████▍     | 3786/8455 [00:47<00:53, 87.33it/s]

Extracting GLCM features:  45%|████▍     | 3795/8455 [00:47<00:53, 87.15it/s]

Extracting GLCM features:  45%|████▍     | 3804/8455 [00:47<00:53, 87.03it/s]

Extracting GLCM features:  45%|████▌     | 3814/8455 [00:47<00:52, 87.83it/s]

Extracting GLCM features:  45%|████▌     | 3823/8455 [00:47<00:54, 84.60it/s]

Extracting GLCM features:  45%|████▌     | 3832/8455 [00:47<00:55, 83.25it/s]

Extracting GLCM features:  45%|████▌     | 3841/8455 [00:47<00:56, 82.37it/s]

Extracting GLCM features:  46%|████▌     | 3850/8455 [00:48<00:54, 83.75it/s]

Extracting GLCM features:  46%|████▌     | 3859/8455 [00:48<00:54, 84.14it/s]

Extracting GLCM features:  46%|████▌     | 3868/8455 [00:48<00:54, 83.62it/s]

Extracting GLCM features:  46%|████▌     | 3877/8455 [00:48<00:54, 84.62it/s]

Extracting GLCM features:  46%|████▌     | 3886/8455 [00:48<00:53, 85.79it/s]

Extracting GLCM features:  46%|████▌     | 3895/8455 [00:48<00:53, 84.55it/s]

Extracting GLCM features:  46%|████▌     | 3904/8455 [00:48<00:53, 85.38it/s]

Extracting GLCM features:  46%|████▋     | 3913/8455 [00:48<00:52, 85.73it/s]

Extracting GLCM features:  46%|████▋     | 3922/8455 [00:48<00:56, 79.57it/s]

Extracting GLCM features:  46%|████▋     | 3931/8455 [00:49<00:57, 78.54it/s]

Extracting GLCM features:  47%|████▋     | 3939/8455 [00:49<00:57, 77.88it/s]

Extracting GLCM features:  47%|████▋     | 3947/8455 [00:49<00:58, 76.72it/s]

Extracting GLCM features:  47%|████▋     | 3956/8455 [00:49<00:57, 78.31it/s]

Extracting GLCM features:  47%|████▋     | 3965/8455 [00:49<00:55, 80.76it/s]

Extracting GLCM features:  47%|████▋     | 3975/8455 [00:49<00:53, 83.67it/s]

Extracting GLCM features:  47%|████▋     | 3984/8455 [00:49<00:52, 84.87it/s]

Extracting GLCM features:  47%|████▋     | 3993/8455 [00:49<00:53, 82.71it/s]

Extracting GLCM features:  47%|████▋     | 4002/8455 [00:49<00:52, 84.21it/s]

Extracting GLCM features:  47%|████▋     | 4011/8455 [00:49<00:52, 85.31it/s]

Extracting GLCM features:  48%|████▊     | 4020/8455 [00:50<00:51, 85.84it/s]

Extracting GLCM features:  48%|████▊     | 4029/8455 [00:50<00:52, 85.01it/s]

Extracting GLCM features:  48%|████▊     | 4039/8455 [00:50<00:50, 86.60it/s]

Extracting GLCM features:  48%|████▊     | 4048/8455 [00:50<00:51, 86.32it/s]

Extracting GLCM features:  48%|████▊     | 4057/8455 [00:50<00:50, 86.60it/s]

Extracting GLCM features:  48%|████▊     | 4067/8455 [00:50<00:50, 86.99it/s]

Extracting GLCM features:  48%|████▊     | 4076/8455 [00:50<00:51, 85.70it/s]

Extracting GLCM features:  48%|████▊     | 4085/8455 [00:50<00:50, 85.83it/s]

Extracting GLCM features:  48%|████▊     | 4094/8455 [00:50<00:50, 86.18it/s]

Extracting GLCM features:  49%|████▊     | 4103/8455 [00:51<00:50, 86.58it/s]

Extracting GLCM features:  49%|████▊     | 4112/8455 [00:51<00:50, 86.45it/s]

Extracting GLCM features:  49%|████▉     | 4122/8455 [00:51<00:49, 87.07it/s]

Extracting GLCM features:  49%|████▉     | 4131/8455 [00:51<00:51, 83.96it/s]

Extracting GLCM features:  49%|████▉     | 4140/8455 [00:51<00:51, 83.95it/s]

Extracting GLCM features:  49%|████▉     | 4149/8455 [00:51<00:50, 84.64it/s]

Extracting GLCM features:  49%|████▉     | 4158/8455 [00:51<00:50, 85.84it/s]

Extracting GLCM features:  49%|████▉     | 4167/8455 [00:51<00:49, 86.46it/s]

Extracting GLCM features:  49%|████▉     | 4176/8455 [00:51<00:49, 87.21it/s]

Extracting GLCM features:  49%|████▉     | 4185/8455 [00:51<00:49, 86.84it/s]

Extracting GLCM features:  50%|████▉     | 4194/8455 [00:52<00:49, 86.05it/s]

Extracting GLCM features:  50%|████▉     | 4203/8455 [00:52<00:48, 87.13it/s]

Extracting GLCM features:  50%|████▉     | 4212/8455 [00:52<00:48, 86.86it/s]

Extracting GLCM features:  50%|████▉     | 4221/8455 [00:52<00:48, 86.78it/s]

Extracting GLCM features:  50%|█████     | 4230/8455 [00:52<00:50, 84.27it/s]

Extracting GLCM features:  50%|█████     | 4239/8455 [00:52<00:50, 83.22it/s]

Extracting GLCM features:  50%|█████     | 4248/8455 [00:52<00:50, 84.09it/s]

Extracting GLCM features:  50%|█████     | 4257/8455 [00:52<00:49, 84.29it/s]

Extracting GLCM features:  50%|█████     | 4267/8455 [00:52<00:48, 85.53it/s]

Extracting GLCM features:  51%|█████     | 4276/8455 [00:53<00:48, 86.07it/s]

Extracting GLCM features:  51%|█████     | 4285/8455 [00:53<00:50, 83.19it/s]

Extracting GLCM features:  51%|█████     | 4294/8455 [00:53<00:51, 80.96it/s]

Extracting GLCM features:  51%|█████     | 4303/8455 [00:53<00:52, 78.90it/s]

Extracting GLCM features:  51%|█████     | 4312/8455 [00:53<00:50, 81.75it/s]

Extracting GLCM features:  51%|█████     | 4321/8455 [00:53<00:49, 83.81it/s]

Extracting GLCM features:  51%|█████     | 4330/8455 [00:53<00:48, 84.51it/s]

Extracting GLCM features:  51%|█████▏    | 4339/8455 [00:53<00:51, 79.29it/s]

Extracting GLCM features:  51%|█████▏    | 4348/8455 [00:53<00:50, 81.59it/s]

Extracting GLCM features:  52%|█████▏    | 4357/8455 [00:54<00:51, 79.96it/s]

Extracting GLCM features:  52%|█████▏    | 4366/8455 [00:54<00:50, 80.87it/s]

Extracting GLCM features:  52%|█████▏    | 4376/8455 [00:54<00:48, 83.25it/s]

Extracting GLCM features:  52%|█████▏    | 4385/8455 [00:54<00:48, 83.67it/s]

Extracting GLCM features:  52%|█████▏    | 4394/8455 [00:54<00:47, 85.21it/s]

Extracting GLCM features:  52%|█████▏    | 4403/8455 [00:54<00:47, 85.12it/s]

Extracting GLCM features:  52%|█████▏    | 4412/8455 [00:54<00:53, 76.24it/s]

Extracting GLCM features:  52%|█████▏    | 4420/8455 [00:54<00:58, 68.82it/s]

Extracting GLCM features:  52%|█████▏    | 4428/8455 [00:55<00:57, 69.80it/s]

Extracting GLCM features:  52%|█████▏    | 4436/8455 [00:55<00:59, 67.09it/s]

Extracting GLCM features:  53%|█████▎    | 4444/8455 [00:55<00:58, 68.31it/s]

Extracting GLCM features:  53%|█████▎    | 4451/8455 [00:55<00:59, 67.20it/s]

Extracting GLCM features:  53%|█████▎    | 4460/8455 [00:55<00:56, 70.17it/s]

Extracting GLCM features:  53%|█████▎    | 4468/8455 [00:55<00:56, 70.79it/s]

Extracting GLCM features:  53%|█████▎    | 4476/8455 [00:55<00:55, 71.38it/s]

Extracting GLCM features:  53%|█████▎    | 4484/8455 [00:55<00:57, 69.38it/s]

Extracting GLCM features:  53%|█████▎    | 4492/8455 [00:55<00:54, 72.15it/s]

Extracting GLCM features:  53%|█████▎    | 4501/8455 [00:56<00:51, 76.22it/s]

Extracting GLCM features:  53%|█████▎    | 4511/8455 [00:56<00:48, 81.56it/s]

Extracting GLCM features:  53%|█████▎    | 4520/8455 [00:56<00:48, 80.72it/s]

Extracting GLCM features:  54%|█████▎    | 4529/8455 [00:56<00:48, 81.77it/s]

Extracting GLCM features:  54%|█████▎    | 4539/8455 [00:56<00:45, 86.09it/s]

Extracting GLCM features:  54%|█████▍    | 4550/8455 [00:56<00:42, 92.18it/s]

Extracting GLCM features:  54%|█████▍    | 4562/8455 [00:56<00:40, 96.65it/s]

Extracting GLCM features:  54%|█████▍    | 4573/8455 [00:56<00:38, 99.80it/s]

Extracting GLCM features:  54%|█████▍    | 4584/8455 [00:56<00:39, 98.74it/s]

Extracting GLCM features:  54%|█████▍    | 4594/8455 [00:56<00:39, 96.88it/s]

Extracting GLCM features:  54%|█████▍    | 4605/8455 [00:57<00:38, 98.98it/s]

Extracting GLCM features:  55%|█████▍    | 4615/8455 [00:57<00:39, 98.11it/s]

Extracting GLCM features:  55%|█████▍    | 4625/8455 [00:57<00:39, 96.98it/s]

Extracting GLCM features:  55%|█████▍    | 4636/8455 [00:57<00:38, 98.61it/s]

Extracting GLCM features:  55%|█████▍    | 4647/8455 [00:57<00:38, 100.04it/s]

Extracting GLCM features:  55%|█████▌    | 4658/8455 [00:57<00:36, 102.87it/s]

Extracting GLCM features:  55%|█████▌    | 4669/8455 [00:57<00:38, 98.33it/s]

Extracting GLCM features:  55%|█████▌    | 4679/8455 [00:57<00:38, 98.17it/s]

Extracting GLCM features:  55%|█████▌    | 4691/8455 [00:57<00:36, 102.07it/s]

Extracting GLCM features:  56%|█████▌    | 4702/8455 [00:58<00:36, 103.69it/s]

Extracting GLCM features:  56%|█████▌    | 4713/8455 [00:58<00:36, 102.40it/s]

Extracting GLCM features:  56%|█████▌    | 4725/8455 [00:58<00:35, 104.17it/s]

Extracting GLCM features:  56%|█████▌    | 4736/8455 [00:58<00:36, 103.25it/s]

Extracting GLCM features:  56%|█████▌    | 4748/8455 [00:58<00:35, 104.75it/s]

Extracting GLCM features:  56%|█████▋    | 4760/8455 [00:58<00:34, 107.00it/s]

Extracting GLCM features:  56%|█████▋    | 4771/8455 [00:58<00:34, 105.96it/s]

Extracting GLCM features:  57%|█████▋    | 4782/8455 [00:58<00:35, 104.88it/s]

Extracting GLCM features:  57%|█████▋    | 4793/8455 [00:58<00:34, 105.85it/s]

Extracting GLCM features:  57%|█████▋    | 4804/8455 [00:59<00:46, 79.14it/s]

Extracting GLCM features:  57%|█████▋    | 4813/8455 [00:59<00:51, 70.72it/s]

Extracting GLCM features:  57%|█████▋    | 4823/8455 [00:59<00:47, 76.83it/s]

Extracting GLCM features:  57%|█████▋    | 4834/8455 [00:59<00:43, 83.59it/s]

Extracting GLCM features:  57%|█████▋    | 4845/8455 [00:59<00:40, 89.53it/s]

Extracting GLCM features:  57%|█████▋    | 4855/8455 [00:59<00:39, 91.48it/s]

Extracting GLCM features:  58%|█████▊    | 4866/8455 [00:59<00:38, 94.18it/s]

Extracting GLCM features:  58%|█████▊    | 4877/8455 [00:59<00:36, 97.57it/s]

Extracting GLCM features:  58%|█████▊    | 4889/8455 [01:00<00:34, 102.10it/s]

Extracting GLCM features:  58%|█████▊    | 4900/8455 [01:00<00:35, 101.37it/s]

Extracting GLCM features:  58%|█████▊    | 4911/8455 [01:00<00:36, 96.02it/s]

Extracting GLCM features:  58%|█████▊    | 4922/8455 [01:00<00:35, 98.75it/s]

Extracting GLCM features:  58%|█████▊    | 4933/8455 [01:00<00:34, 100.73it/s]

Extracting GLCM features:  58%|█████▊    | 4944/8455 [01:00<00:34, 103.12it/s]

Extracting GLCM features:  59%|█████▊    | 4955/8455 [01:00<00:34, 102.84it/s]

Extracting GLCM features:  59%|█████▊    | 4966/8455 [01:00<00:34, 102.24it/s]

Extracting GLCM features:  59%|█████▉    | 4977/8455 [01:00<00:33, 103.41it/s]

Extracting GLCM features:  59%|█████▉    | 4989/8455 [01:01<00:32, 106.51it/s]

Extracting GLCM features:  59%|█████▉    | 5000/8455 [01:01<00:32, 106.23it/s]

Extracting GLCM features:  59%|█████▉    | 5011/8455 [01:01<00:33, 102.30it/s]

Extracting GLCM features:  59%|█████▉    | 5022/8455 [01:01<00:33, 102.89it/s]

Extracting GLCM features:  60%|█████▉    | 5033/8455 [01:01<00:34, 99.88it/s]

Extracting GLCM features:  60%|█████▉    | 5044/8455 [01:01<00:34, 100.14it/s]

Extracting GLCM features:  60%|█████▉    | 5055/8455 [01:01<00:33, 101.09it/s]

Extracting GLCM features:  60%|█████▉    | 5066/8455 [01:01<00:34, 98.97it/s]

Extracting GLCM features:  60%|██████    | 5076/8455 [01:01<00:34, 97.98it/s]

Extracting GLCM features:  60%|██████    | 5086/8455 [01:02<00:34, 97.62it/s]

Extracting GLCM features:  60%|██████    | 5096/8455 [01:02<00:37, 88.67it/s]

Extracting GLCM features:  60%|██████    | 5106/8455 [01:02<00:40, 81.77it/s]

Extracting GLCM features:  60%|██████    | 5115/8455 [01:02<00:41, 79.56it/s]

Extracting GLCM features:  61%|██████    | 5124/8455 [01:02<00:41, 80.65it/s]

Extracting GLCM features:  61%|██████    | 5135/8455 [01:02<00:38, 86.33it/s]

Extracting GLCM features:  61%|██████    | 5144/8455 [01:02<00:42, 78.25it/s]

Extracting GLCM features:  61%|██████    | 5153/8455 [01:02<00:46, 71.18it/s]

Extracting GLCM features:  61%|██████    | 5161/8455 [01:03<00:45, 72.86it/s]

Extracting GLCM features:  61%|██████    | 5169/8455 [01:03<00:44, 74.23it/s]

Extracting GLCM features:  61%|██████    | 5178/8455 [01:03<00:43, 75.87it/s]

Extracting GLCM features:  61%|██████▏   | 5187/8455 [01:03<00:42, 77.15it/s]

Extracting GLCM features:  61%|██████▏   | 5196/8455 [01:03<00:41, 78.43it/s]

Extracting GLCM features:  62%|██████▏   | 5204/8455 [01:03<00:41, 78.26it/s]

Extracting GLCM features:  62%|██████▏   | 5213/8455 [01:03<00:40, 79.83it/s]

Extracting GLCM features:  62%|██████▏   | 5222/8455 [01:03<00:41, 77.76it/s]

Extracting GLCM features:  62%|██████▏   | 5230/8455 [01:03<00:41, 77.26it/s]

Extracting GLCM features:  62%|██████▏   | 5238/8455 [01:04<00:41, 77.41it/s]

Extracting GLCM features:  62%|██████▏   | 5246/8455 [01:04<00:41, 76.91it/s]

Extracting GLCM features:  62%|██████▏   | 5254/8455 [01:04<00:42, 75.47it/s]

Extracting GLCM features:  62%|██████▏   | 5262/8455 [01:04<00:43, 74.01it/s]

Extracting GLCM features:  62%|██████▏   | 5270/8455 [01:04<00:42, 74.68it/s]

Extracting GLCM features:  62%|██████▏   | 5278/8455 [01:04<00:41, 75.96it/s]

Extracting GLCM features:  63%|██████▎   | 5287/8455 [01:04<00:40, 77.49it/s]

Extracting GLCM features:  63%|██████▎   | 5296/8455 [01:04<00:40, 78.42it/s]

Extracting GLCM features:  63%|██████▎   | 5304/8455 [01:04<00:40, 78.10it/s]

Extracting GLCM features:  63%|██████▎   | 5313/8455 [01:04<00:39, 79.93it/s]

Extracting GLCM features:  63%|██████▎   | 5321/8455 [01:05<00:39, 78.42it/s]

Extracting GLCM features:  63%|██████▎   | 5329/8455 [01:05<00:39, 78.16it/s]

Extracting GLCM features:  63%|██████▎   | 5337/8455 [01:05<00:39, 78.08it/s]

Extracting GLCM features:  63%|██████▎   | 5345/8455 [01:05<00:39, 78.11it/s]

Extracting GLCM features:  63%|██████▎   | 5354/8455 [01:05<00:39, 78.59it/s]

Extracting GLCM features:  63%|██████▎   | 5363/8455 [01:05<00:39, 79.21it/s]

Extracting GLCM features:  64%|██████▎   | 5372/8455 [01:05<00:38, 79.67it/s]

Extracting GLCM features:  64%|██████▎   | 5380/8455 [01:05<00:39, 77.85it/s]

Extracting GLCM features:  64%|██████▎   | 5388/8455 [01:05<00:41, 73.89it/s]

Extracting GLCM features:  64%|██████▍   | 5396/8455 [01:06<00:44, 68.41it/s]

Extracting GLCM features:  64%|██████▍   | 5403/8455 [01:06<00:47, 63.77it/s]

Extracting GLCM features:  64%|██████▍   | 5410/8455 [01:06<00:50, 60.36it/s]

Extracting GLCM features:  64%|██████▍   | 5417/8455 [01:06<00:51, 59.36it/s]

Extracting GLCM features:  64%|██████▍   | 5424/8455 [01:06<00:50, 60.59it/s]

Extracting GLCM features:  64%|██████▍   | 5431/8455 [01:06<00:48, 62.24it/s]

Extracting GLCM features:  64%|██████▍   | 5440/8455 [01:06<00:44, 67.88it/s]

Extracting GLCM features:  64%|██████▍   | 5448/8455 [01:06<00:42, 71.18it/s]

Extracting GLCM features:  65%|██████▍   | 5456/8455 [01:07<00:42, 70.56it/s]

Extracting GLCM features:  65%|██████▍   | 5464/8455 [01:07<00:42, 71.01it/s]

Extracting GLCM features:  65%|██████▍   | 5472/8455 [01:07<00:40, 73.30it/s]

Extracting GLCM features:  65%|██████▍   | 5480/8455 [01:07<00:39, 75.18it/s]

Extracting GLCM features:  65%|██████▍   | 5488/8455 [01:07<00:38, 76.40it/s]

Extracting GLCM features:  65%|██████▌   | 5496/8455 [01:07<00:38, 77.13it/s]

Extracting GLCM features:  65%|██████▌   | 5504/8455 [01:07<00:38, 77.63it/s]

Extracting GLCM features:  65%|██████▌   | 5513/8455 [01:07<00:37, 78.38it/s]

Extracting GLCM features:  65%|██████▌   | 5521/8455 [01:07<00:38, 75.41it/s]

Extracting GLCM features:  65%|██████▌   | 5529/8455 [01:07<00:39, 74.09it/s]

Extracting GLCM features:  65%|██████▌   | 5537/8455 [01:08<00:42, 68.45it/s]

Extracting GLCM features:  66%|██████▌   | 5544/8455 [01:08<00:43, 66.36it/s]

Extracting GLCM features:  66%|██████▌   | 5551/8455 [01:08<00:44, 65.67it/s]

Extracting GLCM features:  66%|██████▌   | 5558/8455 [01:08<00:49, 57.96it/s]

Extracting GLCM features:  66%|██████▌   | 5564/8455 [01:08<00:50, 56.80it/s]

Extracting GLCM features:  66%|██████▌   | 5572/8455 [01:08<00:46, 61.55it/s]

Extracting GLCM features:  66%|██████▌   | 5579/8455 [01:08<00:45, 62.76it/s]

Extracting GLCM features:  66%|██████▌   | 5586/8455 [01:08<00:44, 64.11it/s]

Extracting GLCM features:  66%|██████▌   | 5593/8455 [01:09<00:43, 65.73it/s]

Extracting GLCM features:  66%|██████▌   | 5600/8455 [01:09<00:46, 61.45it/s]

Extracting GLCM features:  66%|██████▋   | 5607/8455 [01:09<00:48, 59.19it/s]

Extracting GLCM features:  66%|██████▋   | 5614/8455 [01:09<00:48, 58.15it/s]

Extracting GLCM features:  66%|██████▋   | 5620/8455 [01:09<00:48, 57.93it/s]

Extracting GLCM features:  67%|██████▋   | 5626/8455 [01:09<00:48, 58.38it/s]

Extracting GLCM features:  67%|██████▋   | 5632/8455 [01:09<00:48, 58.75it/s]

Extracting GLCM features:  67%|██████▋   | 5639/8455 [01:09<00:47, 58.89it/s]

Extracting GLCM features:  67%|██████▋   | 5646/8455 [01:09<00:45, 61.91it/s]

Extracting GLCM features:  67%|██████▋   | 5653/8455 [01:10<00:46, 60.40it/s]

Extracting GLCM features:  67%|██████▋   | 5660/8455 [01:10<00:46, 60.01it/s]

Extracting GLCM features:  67%|██████▋   | 5667/8455 [01:10<00:46, 60.39it/s]

Extracting GLCM features:  67%|██████▋   | 5675/8455 [01:10<00:43, 64.32it/s]

Extracting GLCM features:  67%|██████▋   | 5683/8455 [01:10<00:41, 66.21it/s]

Extracting GLCM features:  67%|██████▋   | 5690/8455 [01:10<00:42, 64.76it/s]

Extracting GLCM features:  67%|██████▋   | 5699/8455 [01:10<00:40, 68.71it/s]

Extracting GLCM features:  67%|██████▋   | 5706/8455 [01:10<00:41, 66.51it/s]

Extracting GLCM features:  68%|██████▊   | 5713/8455 [01:10<00:42, 63.96it/s]

Extracting GLCM features:  68%|██████▊   | 5720/8455 [01:11<00:43, 63.43it/s]

Extracting GLCM features:  68%|██████▊   | 5727/8455 [01:11<00:43, 63.19it/s]

Extracting GLCM features:  68%|██████▊   | 5734/8455 [01:11<00:42, 63.41it/s]

Extracting GLCM features:  68%|██████▊   | 5741/8455 [01:11<00:42, 63.26it/s]

Extracting GLCM features:  68%|██████▊   | 5748/8455 [01:11<00:43, 62.54it/s]

Extracting GLCM features:  68%|██████▊   | 5755/8455 [01:11<00:43, 62.00it/s]

Extracting GLCM features:  68%|██████▊   | 5762/8455 [01:11<00:43, 62.37it/s]

Extracting GLCM features:  68%|██████▊   | 5769/8455 [01:11<00:43, 62.02it/s]

Extracting GLCM features:  68%|██████▊   | 5776/8455 [01:12<00:44, 60.52it/s]

Extracting GLCM features:  68%|██████▊   | 5783/8455 [01:12<00:44, 60.14it/s]

Extracting GLCM features:  68%|██████▊   | 5791/8455 [01:12<00:41, 64.20it/s]

Extracting GLCM features:  69%|██████▊   | 5799/8455 [01:12<00:38, 68.12it/s]

Extracting GLCM features:  69%|██████▊   | 5807/8455 [01:12<00:37, 70.35it/s]

Extracting GLCM features:  69%|██████▉   | 5815/8455 [01:12<00:37, 70.26it/s]

Extracting GLCM features:  69%|██████▉   | 5823/8455 [01:12<00:36, 71.31it/s]

Extracting GLCM features:  69%|██████▉   | 5831/8455 [01:12<00:36, 71.00it/s]

Extracting GLCM features:  69%|██████▉   | 5839/8455 [01:12<00:36, 71.50it/s]

Extracting GLCM features:  69%|██████▉   | 5847/8455 [01:12<00:35, 73.71it/s]

Extracting GLCM features:  69%|██████▉   | 5855/8455 [01:13<00:35, 73.72it/s]

Extracting GLCM features:  69%|██████▉   | 5863/8455 [01:13<00:34, 74.55it/s]

Extracting GLCM features:  69%|██████▉   | 5871/8455 [01:13<00:39, 65.88it/s]

Extracting GLCM features:  70%|██████▉   | 5878/8455 [01:13<00:42, 61.20it/s]

Extracting GLCM features:  70%|██████▉   | 5885/8455 [01:13<00:42, 59.83it/s]

Extracting GLCM features:  70%|██████▉   | 5892/8455 [01:13<00:44, 58.17it/s]

Extracting GLCM features:  70%|██████▉   | 5898/8455 [01:13<00:44, 57.85it/s]

Extracting GLCM features:  70%|██████▉   | 5904/8455 [01:13<00:46, 54.57it/s]

Extracting GLCM features:  70%|██████▉   | 5910/8455 [01:14<00:47, 53.09it/s]

Extracting GLCM features:  70%|██████▉   | 5916/8455 [01:14<00:46, 54.29it/s]

Extracting GLCM features:  70%|███████   | 5922/8455 [01:14<00:46, 54.56it/s]

Extracting GLCM features:  70%|███████   | 5928/8455 [01:14<00:45, 56.04it/s]

Extracting GLCM features:  70%|███████   | 5935/8455 [01:14<00:43, 58.22it/s]

Extracting GLCM features:  70%|███████   | 5944/8455 [01:14<00:38, 65.23it/s]

Extracting GLCM features:  70%|███████   | 5952/8455 [01:14<00:36, 68.77it/s]

Extracting GLCM features:  70%|███████   | 5959/8455 [01:14<00:37, 65.71it/s]

Extracting GLCM features:  71%|███████   | 5966/8455 [01:14<00:37, 66.72it/s]

Extracting GLCM features:  71%|███████   | 5974/8455 [01:15<00:36, 68.11it/s]

Extracting GLCM features:  71%|███████   | 5983/8455 [01:15<00:34, 71.53it/s]

Extracting GLCM features:  71%|███████   | 5991/8455 [01:15<00:33, 72.58it/s]

Extracting GLCM features:  71%|███████   | 5999/8455 [01:15<00:33, 73.90it/s]

Extracting GLCM features:  71%|███████   | 6007/8455 [01:15<00:32, 75.38it/s]

Extracting GLCM features:  71%|███████   | 6016/8455 [01:15<00:31, 76.35it/s]

Extracting GLCM features:  71%|███████   | 6024/8455 [01:15<00:32, 75.20it/s]

Extracting GLCM features:  71%|███████▏  | 6032/8455 [01:15<00:32, 75.31it/s]

Extracting GLCM features:  71%|███████▏  | 6041/8455 [01:15<00:31, 77.27it/s]

Extracting GLCM features:  72%|███████▏  | 6049/8455 [01:16<00:31, 77.16it/s]

Extracting GLCM features:  72%|███████▏  | 6057/8455 [01:16<00:34, 68.83it/s]

Extracting GLCM features:  72%|███████▏  | 6065/8455 [01:16<00:34, 69.82it/s]

Extracting GLCM features:  72%|███████▏  | 6075/8455 [01:16<00:31, 76.41it/s]

Extracting GLCM features:  72%|███████▏  | 6083/8455 [01:16<00:34, 69.50it/s]

Extracting GLCM features:  72%|███████▏  | 6091/8455 [01:16<00:35, 66.84it/s]

Extracting GLCM features:  72%|███████▏  | 6098/8455 [01:16<00:35, 66.37it/s]

Extracting GLCM features:  72%|███████▏  | 6105/8455 [01:16<00:35, 67.08it/s]

Extracting GLCM features:  72%|███████▏  | 6113/8455 [01:16<00:33, 69.49it/s]

Extracting GLCM features:  72%|███████▏  | 6121/8455 [01:17<00:32, 71.36it/s]

Extracting GLCM features:  72%|███████▏  | 6129/8455 [01:17<00:32, 71.75it/s]

Extracting GLCM features:  73%|███████▎  | 6137/8455 [01:17<00:31, 72.64it/s]

Extracting GLCM features:  73%|███████▎  | 6145/8455 [01:17<00:31, 74.25it/s]

Extracting GLCM features:  73%|███████▎  | 6153/8455 [01:17<00:31, 74.06it/s]

Extracting GLCM features:  73%|███████▎  | 6162/8455 [01:17<00:29, 76.47it/s]

Extracting GLCM features:  73%|███████▎  | 6170/8455 [01:17<00:31, 71.69it/s]

Extracting GLCM features:  73%|███████▎  | 6178/8455 [01:17<00:33, 68.12it/s]

Extracting GLCM features:  73%|███████▎  | 6186/8455 [01:17<00:32, 70.51it/s]

Extracting GLCM features:  73%|███████▎  | 6194/8455 [01:18<00:31, 72.51it/s]

Extracting GLCM features:  73%|███████▎  | 6202/8455 [01:18<00:31, 72.29it/s]

Extracting GLCM features:  73%|███████▎  | 6210/8455 [01:18<00:31, 70.57it/s]

Extracting GLCM features:  74%|███████▎  | 6218/8455 [01:18<00:32, 69.00it/s]

Extracting GLCM features:  74%|███████▎  | 6225/8455 [01:18<00:32, 69.23it/s]

Extracting GLCM features:  74%|███████▎  | 6232/8455 [01:18<00:32, 68.79it/s]

Extracting GLCM features:  74%|███████▍  | 6239/8455 [01:18<00:32, 68.08it/s]

Extracting GLCM features:  74%|███████▍  | 6246/8455 [01:18<00:33, 66.79it/s]

Extracting GLCM features:  74%|███████▍  | 6254/8455 [01:18<00:32, 68.39it/s]

Extracting GLCM features:  74%|███████▍  | 6261/8455 [01:19<00:32, 66.63it/s]

Extracting GLCM features:  74%|███████▍  | 6268/8455 [01:19<00:34, 63.29it/s]

Extracting GLCM features:  74%|███████▍  | 6275/8455 [01:19<00:33, 64.86it/s]

Extracting GLCM features:  74%|███████▍  | 6282/8455 [01:19<00:33, 65.68it/s]

Extracting GLCM features:  74%|███████▍  | 6289/8455 [01:19<00:34, 62.34it/s]

Extracting GLCM features:  74%|███████▍  | 6296/8455 [01:19<00:36, 58.47it/s]

Extracting GLCM features:  75%|███████▍  | 6302/8455 [01:19<00:47, 45.70it/s]

Extracting GLCM features:  75%|███████▍  | 6308/8455 [01:20<01:02, 34.40it/s]

Extracting GLCM features:  75%|███████▍  | 6313/8455 [01:20<01:10, 30.44it/s]

Extracting GLCM features:  75%|███████▍  | 6317/8455 [01:20<01:14, 28.60it/s]

Extracting GLCM features:  75%|███████▍  | 6321/8455 [01:20<01:12, 29.37it/s]

Extracting GLCM features:  75%|███████▍  | 6325/8455 [01:20<01:08, 31.20it/s]

Extracting GLCM features:  75%|███████▍  | 6329/8455 [01:20<01:05, 32.30it/s]

Extracting GLCM features:  75%|███████▍  | 6333/8455 [01:21<01:05, 32.51it/s]

Extracting GLCM features:  75%|███████▍  | 6337/8455 [01:21<01:06, 31.64it/s]

Extracting GLCM features:  75%|███████▍  | 6341/8455 [01:21<01:08, 30.85it/s]

Extracting GLCM features:  75%|███████▌  | 6345/8455 [01:21<01:06, 31.69it/s]

Extracting GLCM features:  75%|███████▌  | 6349/8455 [01:21<01:05, 32.39it/s]

Extracting GLCM features:  75%|███████▌  | 6353/8455 [01:21<01:04, 32.79it/s]

Extracting GLCM features:  75%|███████▌  | 6357/8455 [01:21<01:02, 33.66it/s]

Extracting GLCM features:  75%|███████▌  | 6361/8455 [01:21<01:00, 34.62it/s]

Extracting GLCM features:  75%|███████▌  | 6366/8455 [01:21<00:56, 36.76it/s]

Extracting GLCM features:  75%|███████▌  | 6371/8455 [01:22<00:53, 38.91it/s]

Extracting GLCM features:  75%|███████▌  | 6375/8455 [01:22<00:54, 38.52it/s]

Extracting GLCM features:  75%|███████▌  | 6379/8455 [01:22<00:54, 37.81it/s]

Extracting GLCM features:  75%|███████▌  | 6383/8455 [01:22<00:58, 35.48it/s]

Extracting GLCM features:  76%|███████▌  | 6387/8455 [01:22<00:57, 35.81it/s]

Extracting GLCM features:  76%|███████▌  | 6391/8455 [01:22<00:55, 36.92it/s]

Extracting GLCM features:  76%|███████▌  | 6395/8455 [01:22<01:01, 33.76it/s]

Extracting GLCM features:  76%|███████▌  | 6399/8455 [01:22<01:02, 33.01it/s]

Extracting GLCM features:  76%|███████▌  | 6403/8455 [01:23<01:03, 32.15it/s]

Extracting GLCM features:  76%|███████▌  | 6407/8455 [01:23<01:11, 28.74it/s]

Extracting GLCM features:  76%|███████▌  | 6410/8455 [01:23<01:18, 26.21it/s]

Extracting GLCM features:  76%|███████▌  | 6413/8455 [01:23<01:17, 26.36it/s]

Extracting GLCM features:  76%|███████▌  | 6416/8455 [01:23<01:18, 25.94it/s]

Extracting GLCM features:  76%|███████▌  | 6420/8455 [01:23<01:13, 27.70it/s]

Extracting GLCM features:  76%|███████▌  | 6424/8455 [01:23<01:07, 30.04it/s]

Extracting GLCM features:  76%|███████▌  | 6428/8455 [01:23<01:03, 32.13it/s]

Extracting GLCM features:  76%|███████▌  | 6433/8455 [01:24<00:56, 35.48it/s]

Extracting GLCM features:  76%|███████▌  | 6437/8455 [01:24<00:59, 34.03it/s]

Extracting GLCM features:  76%|███████▌  | 6441/8455 [01:24<00:58, 34.33it/s]

Extracting GLCM features:  76%|███████▋  | 6447/8455 [01:24<00:51, 38.81it/s]

Extracting GLCM features:  76%|███████▋  | 6452/8455 [01:24<00:49, 40.10it/s]

Extracting GLCM features:  76%|███████▋  | 6457/8455 [01:24<00:49, 40.28it/s]

Extracting GLCM features:  76%|███████▋  | 6462/8455 [01:24<00:50, 39.12it/s]

Extracting GLCM features:  76%|███████▋  | 6467/8455 [01:24<00:47, 41.61it/s]

Extracting GLCM features:  77%|███████▋  | 6472/8455 [01:25<00:45, 43.57it/s]

Extracting GLCM features:  77%|███████▋  | 6477/8455 [01:25<00:44, 44.81it/s]

Extracting GLCM features:  77%|███████▋  | 6483/8455 [01:25<00:43, 45.82it/s]

Extracting GLCM features:  77%|███████▋  | 6488/8455 [01:25<00:42, 46.48it/s]

Extracting GLCM features:  77%|███████▋  | 6493/8455 [01:25<00:41, 47.08it/s]

Extracting GLCM features:  77%|███████▋  | 6498/8455 [01:25<00:40, 47.85it/s]

Extracting GLCM features:  77%|███████▋  | 6503/8455 [01:25<00:42, 46.18it/s]

Extracting GLCM features:  77%|███████▋  | 6508/8455 [01:25<00:44, 43.95it/s]

Extracting GLCM features:  77%|███████▋  | 6513/8455 [01:25<00:44, 43.63it/s]

Extracting GLCM features:  77%|███████▋  | 6518/8455 [01:26<00:43, 44.89it/s]

Extracting GLCM features:  77%|███████▋  | 6523/8455 [01:26<00:42, 45.69it/s]

Extracting GLCM features:  77%|███████▋  | 6528/8455 [01:26<00:42, 45.46it/s]

Extracting GLCM features:  77%|███████▋  | 6533/8455 [01:26<00:43, 44.45it/s]

Extracting GLCM features:  77%|███████▋  | 6538/8455 [01:26<00:45, 41.90it/s]

Extracting GLCM features:  77%|███████▋  | 6543/8455 [01:26<00:46, 41.56it/s]

Extracting GLCM features:  77%|███████▋  | 6548/8455 [01:26<00:46, 41.09it/s]

Extracting GLCM features:  78%|███████▊  | 6553/8455 [01:26<00:46, 40.82it/s]

Extracting GLCM features:  78%|███████▊  | 6558/8455 [01:26<00:45, 41.91it/s]

Extracting GLCM features:  78%|███████▊  | 6563/8455 [01:27<00:45, 41.36it/s]

Extracting GLCM features:  78%|███████▊  | 6568/8455 [01:27<00:46, 41.01it/s]

Extracting GLCM features:  78%|███████▊  | 6573/8455 [01:27<00:45, 41.80it/s]

Extracting GLCM features:  78%|███████▊  | 6578/8455 [01:27<00:45, 41.44it/s]

Extracting GLCM features:  78%|███████▊  | 6583/8455 [01:27<00:45, 40.93it/s]

Extracting GLCM features:  78%|███████▊  | 6588/8455 [01:27<00:48, 38.57it/s]

Extracting GLCM features:  78%|███████▊  | 6592/8455 [01:27<00:50, 36.72it/s]

Extracting GLCM features:  78%|███████▊  | 6596/8455 [01:27<00:52, 35.75it/s]

Extracting GLCM features:  78%|███████▊  | 6600/8455 [01:28<00:52, 35.35it/s]

Extracting GLCM features:  78%|███████▊  | 6604/8455 [01:28<00:55, 33.19it/s]

Extracting GLCM features:  78%|███████▊  | 6608/8455 [01:28<01:01, 30.11it/s]

Extracting GLCM features:  78%|███████▊  | 6612/8455 [01:28<01:02, 29.49it/s]

Extracting GLCM features:  78%|███████▊  | 6616/8455 [01:28<00:58, 31.64it/s]

Extracting GLCM features:  78%|███████▊  | 6620/8455 [01:28<00:55, 33.09it/s]

Extracting GLCM features:  78%|███████▊  | 6624/8455 [01:28<00:53, 34.16it/s]

Extracting GLCM features:  78%|███████▊  | 6628/8455 [01:28<00:51, 35.70it/s]

Extracting GLCM features:  78%|███████▊  | 6632/8455 [01:29<00:53, 34.12it/s]

Extracting GLCM features:  78%|███████▊  | 6636/8455 [01:29<00:52, 34.70it/s]

Extracting GLCM features:  79%|███████▊  | 6640/8455 [01:29<00:50, 35.67it/s]

Extracting GLCM features:  79%|███████▊  | 6644/8455 [01:29<00:51, 35.01it/s]

Extracting GLCM features:  79%|███████▊  | 6648/8455 [01:29<00:51, 34.78it/s]

Extracting GLCM features:  79%|███████▊  | 6653/8455 [01:29<00:49, 36.42it/s]

Extracting GLCM features:  79%|███████▊  | 6658/8455 [01:29<00:46, 38.83it/s]

Extracting GLCM features:  79%|███████▉  | 6663/8455 [01:29<00:43, 40.81it/s]

Extracting GLCM features:  79%|███████▉  | 6668/8455 [01:29<00:41, 43.10it/s]

Extracting GLCM features:  79%|███████▉  | 6673/8455 [01:30<00:41, 43.11it/s]

Extracting GLCM features:  79%|███████▉  | 6678/8455 [01:30<00:43, 40.49it/s]

Extracting GLCM features:  79%|███████▉  | 6683/8455 [01:30<00:43, 40.47it/s]

Extracting GLCM features:  79%|███████▉  | 6688/8455 [01:30<00:44, 39.63it/s]

Extracting GLCM features:  79%|███████▉  | 6692/8455 [01:30<00:44, 39.28it/s]

Extracting GLCM features:  79%|███████▉  | 6697/8455 [01:30<00:42, 41.67it/s]

Extracting GLCM features:  79%|███████▉  | 6702/8455 [01:30<00:40, 43.36it/s]

Extracting GLCM features:  79%|███████▉  | 6707/8455 [01:30<00:39, 43.89it/s]

Extracting GLCM features:  79%|███████▉  | 6712/8455 [01:31<00:41, 42.50it/s]

Extracting GLCM features:  79%|███████▉  | 6717/8455 [01:31<00:41, 41.78it/s]

Extracting GLCM features:  80%|███████▉  | 6722/8455 [01:31<00:40, 42.59it/s]

Extracting GLCM features:  80%|███████▉  | 6727/8455 [01:31<00:41, 41.86it/s]

Extracting GLCM features:  80%|███████▉  | 6732/8455 [01:31<00:43, 39.88it/s]

Extracting GLCM features:  80%|███████▉  | 6737/8455 [01:31<00:42, 40.14it/s]

Extracting GLCM features:  80%|███████▉  | 6742/8455 [01:31<00:40, 42.64it/s]

Extracting GLCM features:  80%|███████▉  | 6747/8455 [01:31<00:38, 44.12it/s]

Extracting GLCM features:  80%|███████▉  | 6752/8455 [01:31<00:37, 45.00it/s]

Extracting GLCM features:  80%|███████▉  | 6757/8455 [01:32<00:37, 45.15it/s]

Extracting GLCM features:  80%|███████▉  | 6762/8455 [01:32<00:37, 45.61it/s]

Extracting GLCM features:  80%|████████  | 6767/8455 [01:32<00:36, 46.46it/s]

Extracting GLCM features:  80%|████████  | 6772/8455 [01:32<00:35, 46.91it/s]

Extracting GLCM features:  80%|████████  | 6777/8455 [01:32<00:38, 44.01it/s]

Extracting GLCM features:  80%|████████  | 6782/8455 [01:32<00:38, 43.22it/s]

Extracting GLCM features:  80%|████████  | 6787/8455 [01:32<00:39, 41.88it/s]

Extracting GLCM features:  80%|████████  | 6792/8455 [01:32<00:39, 41.72it/s]

Extracting GLCM features:  80%|████████  | 6797/8455 [01:33<00:40, 41.06it/s]

Extracting GLCM features:  80%|████████  | 6802/8455 [01:33<00:40, 41.05it/s]

Extracting GLCM features:  81%|████████  | 6807/8455 [01:33<00:41, 39.82it/s]

Extracting GLCM features:  81%|████████  | 6811/8455 [01:33<00:41, 39.48it/s]

Extracting GLCM features:  81%|████████  | 6815/8455 [01:33<00:41, 39.15it/s]

Extracting GLCM features:  81%|████████  | 6820/8455 [01:33<00:40, 40.41it/s]

Extracting GLCM features:  81%|████████  | 6825/8455 [01:33<00:39, 41.38it/s]

Extracting GLCM features:  81%|████████  | 6830/8455 [01:33<00:40, 40.38it/s]

Extracting GLCM features:  81%|████████  | 6835/8455 [01:33<00:39, 41.28it/s]

Extracting GLCM features:  81%|████████  | 6840/8455 [01:34<00:39, 40.67it/s]

Extracting GLCM features:  81%|████████  | 6845/8455 [01:34<00:40, 40.14it/s]

Extracting GLCM features:  81%|████████  | 6850/8455 [01:34<00:40, 40.10it/s]

Extracting GLCM features:  81%|████████  | 6855/8455 [01:34<00:39, 40.59it/s]

Extracting GLCM features:  81%|████████  | 6860/8455 [01:34<00:41, 38.80it/s]

Extracting GLCM features:  81%|████████  | 6864/8455 [01:34<00:41, 38.49it/s]

Extracting GLCM features:  81%|████████  | 6869/8455 [01:34<00:39, 40.04it/s]

Extracting GLCM features:  81%|████████▏ | 6874/8455 [01:34<00:40, 39.36it/s]

Extracting GLCM features:  81%|████████▏ | 6878/8455 [01:35<00:41, 38.00it/s]

Extracting GLCM features:  81%|████████▏ | 6882/8455 [01:35<00:41, 37.86it/s]

Extracting GLCM features:  81%|████████▏ | 6886/8455 [01:35<00:41, 37.57it/s]

Extracting GLCM features:  82%|████████▏ | 6891/8455 [01:35<00:39, 39.31it/s]

Extracting GLCM features:  82%|████████▏ | 6895/8455 [01:35<00:39, 39.39it/s]

Extracting GLCM features:  82%|████████▏ | 6900/8455 [01:35<00:37, 41.01it/s]

Extracting GLCM features:  82%|████████▏ | 6905/8455 [01:35<00:38, 40.72it/s]

Extracting GLCM features:  82%|████████▏ | 6910/8455 [01:35<00:37, 41.22it/s]

Extracting GLCM features:  82%|████████▏ | 6915/8455 [01:35<00:37, 41.31it/s]

Extracting GLCM features:  82%|████████▏ | 6920/8455 [01:36<00:38, 40.02it/s]

Extracting GLCM features:  82%|████████▏ | 6925/8455 [01:36<00:39, 38.91it/s]

Extracting GLCM features:  82%|████████▏ | 6930/8455 [01:36<00:38, 39.91it/s]

Extracting GLCM features:  82%|████████▏ | 6935/8455 [01:36<00:40, 37.90it/s]

Extracting GLCM features:  82%|████████▏ | 6939/8455 [01:36<00:39, 37.90it/s]

Extracting GLCM features:  82%|████████▏ | 6943/8455 [01:36<00:39, 38.18it/s]

Extracting GLCM features:  82%|████████▏ | 6947/8455 [01:36<00:39, 38.38it/s]

Extracting GLCM features:  82%|████████▏ | 6951/8455 [01:36<00:39, 37.71it/s]

Extracting GLCM features:  82%|████████▏ | 6955/8455 [01:37<00:39, 37.84it/s]

Extracting GLCM features:  82%|████████▏ | 6959/8455 [01:37<00:39, 37.92it/s]

Extracting GLCM features:  82%|████████▏ | 6964/8455 [01:37<00:37, 40.13it/s]

Extracting GLCM features:  82%|████████▏ | 6969/8455 [01:37<00:35, 42.18it/s]

Extracting GLCM features:  82%|████████▏ | 6974/8455 [01:37<00:33, 43.84it/s]

Extracting GLCM features:  83%|████████▎ | 6979/8455 [01:37<00:32, 44.91it/s]

Extracting GLCM features:  83%|████████▎ | 6984/8455 [01:37<00:31, 46.22it/s]

Extracting GLCM features:  83%|████████▎ | 6989/8455 [01:37<00:32, 45.21it/s]

Extracting GLCM features:  83%|████████▎ | 6994/8455 [01:37<00:32, 45.65it/s]

Extracting GLCM features:  83%|████████▎ | 6999/8455 [01:38<00:31, 45.88it/s]

Extracting GLCM features:  83%|████████▎ | 7004/8455 [01:38<00:30, 47.02it/s]

Extracting GLCM features:  83%|████████▎ | 7009/8455 [01:38<00:30, 46.83it/s]

Extracting GLCM features:  83%|████████▎ | 7014/8455 [01:38<00:30, 47.63it/s]

Extracting GLCM features:  83%|████████▎ | 7019/8455 [01:38<00:30, 47.08it/s]

Extracting GLCM features:  83%|████████▎ | 7024/8455 [01:38<00:30, 46.56it/s]

Extracting GLCM features:  83%|████████▎ | 7029/8455 [01:38<00:30, 46.25it/s]

Extracting GLCM features:  83%|████████▎ | 7035/8455 [01:38<00:29, 48.28it/s]

Extracting GLCM features:  83%|████████▎ | 7040/8455 [01:38<00:29, 47.43it/s]

Extracting GLCM features:  83%|████████▎ | 7045/8455 [01:38<00:29, 47.06it/s]

Extracting GLCM features:  83%|████████▎ | 7050/8455 [01:39<00:30, 45.86it/s]

Extracting GLCM features:  83%|████████▎ | 7055/8455 [01:39<00:30, 46.65it/s]

Extracting GLCM features:  84%|████████▎ | 7060/8455 [01:39<00:29, 47.42it/s]

Extracting GLCM features:  84%|████████▎ | 7066/8455 [01:39<00:28, 49.44it/s]

Extracting GLCM features:  84%|████████▎ | 7071/8455 [01:39<00:29, 47.01it/s]

Extracting GLCM features:  84%|████████▎ | 7076/8455 [01:39<00:30, 45.91it/s]

Extracting GLCM features:  84%|████████▎ | 7081/8455 [01:39<00:29, 46.23it/s]

Extracting GLCM features:  84%|████████▍ | 7086/8455 [01:39<00:29, 46.69it/s]

Extracting GLCM features:  84%|████████▍ | 7091/8455 [01:39<00:29, 46.24it/s]

Extracting GLCM features:  84%|████████▍ | 7096/8455 [01:40<00:29, 46.67it/s]

Extracting GLCM features:  84%|████████▍ | 7101/8455 [01:40<00:28, 46.78it/s]

Extracting GLCM features:  84%|████████▍ | 7106/8455 [01:40<00:29, 46.02it/s]

Extracting GLCM features:  84%|████████▍ | 7111/8455 [01:40<00:30, 43.78it/s]

Extracting GLCM features:  84%|████████▍ | 7116/8455 [01:40<00:31, 42.33it/s]

Extracting GLCM features:  84%|████████▍ | 7121/8455 [01:40<00:30, 44.35it/s]

Extracting GLCM features:  84%|████████▍ | 7126/8455 [01:40<00:29, 44.48it/s]

Extracting GLCM features:  84%|████████▍ | 7131/8455 [01:40<00:29, 44.63it/s]

Extracting GLCM features:  84%|████████▍ | 7136/8455 [01:40<00:29, 44.33it/s]

Extracting GLCM features:  84%|████████▍ | 7141/8455 [01:41<00:29, 44.04it/s]

Extracting GLCM features:  85%|████████▍ | 7146/8455 [01:41<00:29, 45.02it/s]

Extracting GLCM features:  85%|████████▍ | 7151/8455 [01:41<00:28, 45.67it/s]

Extracting GLCM features:  85%|████████▍ | 7156/8455 [01:41<00:28, 45.40it/s]

Extracting GLCM features:  85%|████████▍ | 7161/8455 [01:41<00:28, 45.76it/s]

Extracting GLCM features:  85%|████████▍ | 7166/8455 [01:41<00:27, 46.76it/s]

Extracting GLCM features:  85%|████████▍ | 7171/8455 [01:41<00:27, 46.17it/s]

Extracting GLCM features:  85%|████████▍ | 7176/8455 [01:41<00:27, 46.32it/s]

Extracting GLCM features:  85%|████████▍ | 7181/8455 [01:41<00:27, 46.02it/s]

Extracting GLCM features:  85%|████████▍ | 7186/8455 [01:42<00:27, 46.85it/s]

Extracting GLCM features:  85%|████████▌ | 7191/8455 [01:42<00:26, 47.17it/s]

Extracting GLCM features:  85%|████████▌ | 7196/8455 [01:42<00:26, 47.37it/s]

Extracting GLCM features:  85%|████████▌ | 7201/8455 [01:42<00:26, 47.55it/s]

Extracting GLCM features:  85%|████████▌ | 7206/8455 [01:42<00:26, 46.70it/s]

Extracting GLCM features:  85%|████████▌ | 7211/8455 [01:42<00:27, 44.72it/s]

Extracting GLCM features:  85%|████████▌ | 7216/8455 [01:42<00:28, 43.70it/s]

Extracting GLCM features:  85%|████████▌ | 7221/8455 [01:42<00:27, 44.27it/s]

Extracting GLCM features:  85%|████████▌ | 7227/8455 [01:42<00:26, 46.81it/s]

Extracting GLCM features:  86%|████████▌ | 7233/8455 [01:43<00:24, 49.06it/s]

Extracting GLCM features:  86%|████████▌ | 7239/8455 [01:43<00:24, 49.83it/s]

Extracting GLCM features:  86%|████████▌ | 7245/8455 [01:43<00:24, 50.18it/s]

Extracting GLCM features:  86%|████████▌ | 7251/8455 [01:43<00:23, 50.96it/s]

Extracting GLCM features:  86%|████████▌ | 7257/8455 [01:43<00:23, 50.88it/s]

Extracting GLCM features:  86%|████████▌ | 7263/8455 [01:43<00:24, 49.08it/s]

Extracting GLCM features:  86%|████████▌ | 7268/8455 [01:43<00:25, 47.07it/s]

Extracting GLCM features:  86%|████████▌ | 7273/8455 [01:43<00:25, 45.59it/s]

Extracting GLCM features:  86%|████████▌ | 7278/8455 [01:44<00:25, 45.46it/s]

Extracting GLCM features:  86%|████████▌ | 7283/8455 [01:44<00:25, 45.46it/s]

Extracting GLCM features:  86%|████████▌ | 7288/8455 [01:44<00:25, 45.72it/s]

Extracting GLCM features:  86%|████████▋ | 7294/8455 [01:44<00:24, 47.56it/s]

Extracting GLCM features:  86%|████████▋ | 7300/8455 [01:44<00:23, 49.33it/s]

Extracting GLCM features:  86%|████████▋ | 7305/8455 [01:44<00:23, 48.96it/s]

Extracting GLCM features:  86%|████████▋ | 7311/8455 [01:44<00:22, 50.27it/s]

Extracting GLCM features:  87%|████████▋ | 7317/8455 [01:44<00:22, 51.65it/s]

Extracting GLCM features:  87%|████████▋ | 7323/8455 [01:44<00:21, 51.70it/s]

Extracting GLCM features:  87%|████████▋ | 7329/8455 [01:45<00:21, 52.09it/s]

Extracting GLCM features:  87%|████████▋ | 7335/8455 [01:45<00:21, 51.65it/s]

Extracting GLCM features:  87%|████████▋ | 7341/8455 [01:45<00:22, 49.19it/s]

Extracting GLCM features:  87%|████████▋ | 7346/8455 [01:45<00:22, 48.70it/s]

Extracting GLCM features:  87%|████████▋ | 7352/8455 [01:45<00:22, 49.59it/s]

Extracting GLCM features:  87%|████████▋ | 7357/8455 [01:45<00:22, 49.58it/s]

Extracting GLCM features:  87%|████████▋ | 7363/8455 [01:45<00:21, 49.97it/s]

Extracting GLCM features:  87%|████████▋ | 7369/8455 [01:45<00:21, 50.65it/s]

Extracting GLCM features:  87%|████████▋ | 7375/8455 [01:45<00:21, 50.02it/s]

Extracting GLCM features:  87%|████████▋ | 7381/8455 [01:46<00:20, 51.16it/s]

Extracting GLCM features:  87%|████████▋ | 7387/8455 [01:46<00:20, 51.40it/s]

Extracting GLCM features:  87%|████████▋ | 7393/8455 [01:46<00:20, 51.76it/s]

Extracting GLCM features:  88%|████████▊ | 7399/8455 [01:46<00:20, 52.46it/s]

Extracting GLCM features:  88%|████████▊ | 7405/8455 [01:46<00:20, 50.92it/s]

Extracting GLCM features:  88%|████████▊ | 7411/8455 [01:46<00:21, 49.05it/s]

Extracting GLCM features:  88%|████████▊ | 7416/8455 [01:46<00:21, 47.96it/s]

Extracting GLCM features:  88%|████████▊ | 7421/8455 [01:46<00:22, 46.13it/s]

Extracting GLCM features:  88%|████████▊ | 7426/8455 [01:47<00:23, 43.24it/s]

Extracting GLCM features:  88%|████████▊ | 7431/8455 [01:47<00:25, 39.41it/s]

Extracting GLCM features:  88%|████████▊ | 7436/8455 [01:47<00:28, 35.68it/s]

Extracting GLCM features:  88%|████████▊ | 7440/8455 [01:47<00:28, 35.31it/s]

Extracting GLCM features:  88%|████████▊ | 7444/8455 [01:47<00:27, 36.25it/s]

Extracting GLCM features:  88%|████████▊ | 7448/8455 [01:47<00:27, 37.11it/s]

Extracting GLCM features:  88%|████████▊ | 7453/8455 [01:47<00:25, 38.97it/s]

Extracting GLCM features:  88%|████████▊ | 7458/8455 [01:47<00:24, 39.98it/s]

Extracting GLCM features:  88%|████████▊ | 7464/8455 [01:48<00:22, 43.29it/s]

Extracting GLCM features:  88%|████████▊ | 7469/8455 [01:48<00:23, 42.56it/s]

Extracting GLCM features:  88%|████████▊ | 7475/8455 [01:48<00:21, 45.45it/s]

Extracting GLCM features:  88%|████████▊ | 7480/8455 [01:48<00:21, 45.88it/s]

Extracting GLCM features:  89%|████████▊ | 7485/8455 [01:48<00:21, 44.55it/s]

Extracting GLCM features:  89%|████████▊ | 7490/8455 [01:48<00:21, 45.44it/s]

Extracting GLCM features:  89%|████████▊ | 7495/8455 [01:48<00:21, 45.38it/s]

Extracting GLCM features:  89%|████████▊ | 7500/8455 [01:48<00:21, 45.25it/s]

Extracting GLCM features:  89%|████████▉ | 7506/8455 [01:48<00:20, 47.42it/s]

Extracting GLCM features:  89%|████████▉ | 7511/8455 [01:49<00:20, 46.87it/s]

Extracting GLCM features:  89%|████████▉ | 7516/8455 [01:49<00:21, 44.03it/s]

Extracting GLCM features:  89%|████████▉ | 7521/8455 [01:49<00:21, 44.14it/s]

Extracting GLCM features:  89%|████████▉ | 7527/8455 [01:49<00:19, 46.50it/s]

Extracting GLCM features:  89%|████████▉ | 7533/8455 [01:49<00:19, 48.33it/s]

Extracting GLCM features:  89%|████████▉ | 7539/8455 [01:49<00:18, 49.32it/s]

Extracting GLCM features:  89%|████████▉ | 7545/8455 [01:49<00:18, 50.49it/s]

Extracting GLCM features:  89%|████████▉ | 7551/8455 [01:49<00:20, 44.18it/s]

Extracting GLCM features:  89%|████████▉ | 7556/8455 [01:50<00:23, 38.27it/s]

Extracting GLCM features:  89%|████████▉ | 7561/8455 [01:50<00:22, 39.22it/s]

Extracting GLCM features:  89%|████████▉ | 7566/8455 [01:50<00:22, 40.10it/s]

Extracting GLCM features:  90%|████████▉ | 7572/8455 [01:50<00:20, 43.09it/s]

Extracting GLCM features:  90%|████████▉ | 7578/8455 [01:50<00:19, 45.79it/s]

Extracting GLCM features:  90%|████████▉ | 7584/8455 [01:50<00:18, 47.71it/s]

Extracting GLCM features:  90%|████████▉ | 7589/8455 [01:50<00:18, 47.42it/s]

Extracting GLCM features:  90%|████████▉ | 7594/8455 [01:50<00:18, 46.01it/s]

Extracting GLCM features:  90%|████████▉ | 7600/8455 [01:51<00:18, 47.19it/s]

Extracting GLCM features:  90%|████████▉ | 7605/8455 [01:51<00:18, 45.68it/s]

Extracting GLCM features:  90%|█████████ | 7610/8455 [01:51<00:19, 43.88it/s]

Extracting GLCM features:  90%|█████████ | 7615/8455 [01:51<00:19, 43.63it/s]

Extracting GLCM features:  90%|█████████ | 7620/8455 [01:51<00:18, 44.18it/s]

Extracting GLCM features:  90%|█████████ | 7625/8455 [01:51<00:18, 44.02it/s]

Extracting GLCM features:  90%|█████████ | 7630/8455 [01:51<00:18, 43.91it/s]

Extracting GLCM features:  90%|█████████ | 7635/8455 [01:51<00:18, 44.01it/s]

Extracting GLCM features:  90%|█████████ | 7640/8455 [01:51<00:17, 45.32it/s]

Extracting GLCM features:  90%|█████████ | 7645/8455 [01:52<00:18, 44.30it/s]

Extracting GLCM features:  90%|█████████ | 7650/8455 [01:52<00:17, 45.71it/s]

Extracting GLCM features:  91%|█████████ | 7656/8455 [01:52<00:16, 47.40it/s]

Extracting GLCM features:  91%|█████████ | 7662/8455 [01:52<00:16, 48.93it/s]

Extracting GLCM features:  91%|█████████ | 7668/8455 [01:52<00:15, 49.51it/s]

Extracting GLCM features:  91%|█████████ | 7673/8455 [01:52<00:15, 49.47it/s]

Extracting GLCM features:  91%|█████████ | 7679/8455 [01:52<00:15, 50.73it/s]

Extracting GLCM features:  91%|█████████ | 7685/8455 [01:52<00:15, 49.46it/s]

Extracting GLCM features:  91%|█████████ | 7690/8455 [01:52<00:15, 48.93it/s]

Extracting GLCM features:  91%|█████████ | 7696/8455 [01:53<00:15, 50.05it/s]

Extracting GLCM features:  91%|█████████ | 7702/8455 [01:53<00:14, 50.69it/s]

Extracting GLCM features:  91%|█████████ | 7708/8455 [01:53<00:14, 50.79it/s]

Extracting GLCM features:  91%|█████████ | 7714/8455 [01:53<00:15, 47.34it/s]

Extracting GLCM features:  91%|█████████▏| 7719/8455 [01:53<00:16, 43.91it/s]

Extracting GLCM features:  91%|█████████▏| 7724/8455 [01:53<00:17, 40.61it/s]

Extracting GLCM features:  91%|█████████▏| 7729/8455 [01:53<00:18, 39.50it/s]

Extracting GLCM features:  91%|█████████▏| 7734/8455 [01:53<00:17, 41.30it/s]

Extracting GLCM features:  92%|█████████▏| 7740/8455 [01:54<00:16, 43.83it/s]

Extracting GLCM features:  92%|█████████▏| 7745/8455 [01:54<00:15, 44.98it/s]

Extracting GLCM features:  92%|█████████▏| 7750/8455 [01:54<00:15, 45.57it/s]

Extracting GLCM features:  92%|█████████▏| 7755/8455 [01:54<00:15, 46.52it/s]

Extracting GLCM features:  92%|█████████▏| 7760/8455 [01:54<00:14, 46.63it/s]

Extracting GLCM features:  92%|█████████▏| 7765/8455 [01:54<00:15, 45.46it/s]

Extracting GLCM features:  92%|█████████▏| 7770/8455 [01:54<00:15, 43.72it/s]

Extracting GLCM features:  92%|█████████▏| 7775/8455 [01:54<00:15, 43.54it/s]

Extracting GLCM features:  92%|█████████▏| 7781/8455 [01:54<00:14, 45.90it/s]

Extracting GLCM features:  92%|█████████▏| 7786/8455 [01:55<00:14, 45.45it/s]

Extracting GLCM features:  92%|█████████▏| 7791/8455 [01:55<00:15, 42.46it/s]

Extracting GLCM features:  92%|█████████▏| 7796/8455 [01:55<00:15, 41.35it/s]

Extracting GLCM features:  92%|█████████▏| 7801/8455 [01:55<00:17, 38.17it/s]

Extracting GLCM features:  92%|█████████▏| 7805/8455 [01:55<00:17, 36.87it/s]

Extracting GLCM features:  92%|█████████▏| 7809/8455 [01:55<00:17, 36.99it/s]

Extracting GLCM features:  92%|█████████▏| 7814/8455 [01:55<00:16, 38.83it/s]

Extracting GLCM features:  92%|█████████▏| 7818/8455 [01:55<00:16, 38.68it/s]

Extracting GLCM features:  93%|█████████▎| 7823/8455 [01:56<00:16, 39.21it/s]

Extracting GLCM features:  93%|█████████▎| 7827/8455 [01:56<00:16, 36.99it/s]

Extracting GLCM features:  93%|█████████▎| 7831/8455 [01:56<00:17, 36.33it/s]

Extracting GLCM features:  93%|█████████▎| 7835/8455 [01:56<00:17, 35.65it/s]

Extracting GLCM features:  93%|█████████▎| 7839/8455 [01:56<00:16, 36.58it/s]

Extracting GLCM features:  93%|█████████▎| 7844/8455 [01:56<00:15, 38.33it/s]

Extracting GLCM features:  93%|█████████▎| 7849/8455 [01:56<00:14, 40.50it/s]

Extracting GLCM features:  93%|█████████▎| 7854/8455 [01:56<00:14, 42.17it/s]

Extracting GLCM features:  93%|█████████▎| 7859/8455 [01:56<00:13, 43.67it/s]

Extracting GLCM features:  93%|█████████▎| 7864/8455 [01:57<00:13, 43.38it/s]

Extracting GLCM features:  93%|█████████▎| 7869/8455 [01:57<00:13, 45.03it/s]

Extracting GLCM features:  93%|█████████▎| 7874/8455 [01:57<00:12, 46.13it/s]

Extracting GLCM features:  93%|█████████▎| 7879/8455 [01:57<00:12, 47.10it/s]

Extracting GLCM features:  93%|█████████▎| 7884/8455 [01:57<00:11, 47.77it/s]

Extracting GLCM features:  93%|█████████▎| 7889/8455 [01:57<00:11, 47.68it/s]

Extracting GLCM features:  93%|█████████▎| 7894/8455 [01:57<00:11, 47.84it/s]

Extracting GLCM features:  93%|█████████▎| 7900/8455 [01:57<00:11, 48.62it/s]

Extracting GLCM features:  94%|█████████▎| 7906/8455 [01:57<00:11, 49.16it/s]

Extracting GLCM features:  94%|█████████▎| 7911/8455 [01:58<00:11, 48.28it/s]

Extracting GLCM features:  94%|█████████▎| 7916/8455 [01:58<00:11, 46.75it/s]

Extracting GLCM features:  94%|█████████▎| 7921/8455 [01:58<00:11, 44.83it/s]

Extracting GLCM features:  94%|█████████▎| 7926/8455 [01:58<00:12, 43.59it/s]

Extracting GLCM features:  94%|█████████▍| 7931/8455 [01:58<00:11, 44.55it/s]

Extracting GLCM features:  94%|█████████▍| 7936/8455 [01:58<00:11, 45.20it/s]

Extracting GLCM features:  94%|█████████▍| 7941/8455 [01:58<00:11, 43.88it/s]

Extracting GLCM features:  94%|█████████▍| 7946/8455 [01:58<00:11, 42.71it/s]

Extracting GLCM features:  94%|█████████▍| 7951/8455 [01:59<00:12, 39.03it/s]

Extracting GLCM features:  94%|█████████▍| 7955/8455 [01:59<00:12, 38.48it/s]

Extracting GLCM features:  94%|█████████▍| 7960/8455 [01:59<00:12, 39.93it/s]

Extracting GLCM features:  94%|█████████▍| 7965/8455 [01:59<00:11, 41.33it/s]

Extracting GLCM features:  94%|█████████▍| 7970/8455 [01:59<00:11, 41.99it/s]

Extracting GLCM features:  94%|█████████▍| 7975/8455 [01:59<00:11, 42.95it/s]

Extracting GLCM features:  94%|█████████▍| 7980/8455 [01:59<00:10, 44.13it/s]

Extracting GLCM features:  94%|█████████▍| 7985/8455 [01:59<00:10, 44.78it/s]

Extracting GLCM features:  95%|█████████▍| 7990/8455 [01:59<00:10, 44.91it/s]

Extracting GLCM features:  95%|█████████▍| 7995/8455 [02:00<00:10, 44.63it/s]

Extracting GLCM features:  95%|█████████▍| 8000/8455 [02:00<00:10, 44.87it/s]

Extracting GLCM features:  95%|█████████▍| 8005/8455 [02:00<00:10, 44.72it/s]

Extracting GLCM features:  95%|█████████▍| 8010/8455 [02:00<00:09, 45.25it/s]

Extracting GLCM features:  95%|█████████▍| 8015/8455 [02:00<00:09, 45.91it/s]

Extracting GLCM features:  95%|█████████▍| 8020/8455 [02:00<00:09, 45.69it/s]

Extracting GLCM features:  95%|█████████▍| 8025/8455 [02:00<00:09, 45.28it/s]

Extracting GLCM features:  95%|█████████▍| 8030/8455 [02:00<00:09, 44.11it/s]

Extracting GLCM features:  95%|█████████▌| 8035/8455 [02:00<00:10, 41.62it/s]

Extracting GLCM features:  95%|█████████▌| 8040/8455 [02:01<00:10, 40.43it/s]

Extracting GLCM features:  95%|█████████▌| 8045/8455 [02:01<00:09, 41.10it/s]

Extracting GLCM features:  95%|█████████▌| 8050/8455 [02:01<00:09, 42.13it/s]

Extracting GLCM features:  95%|█████████▌| 8055/8455 [02:01<00:09, 41.52it/s]

Extracting GLCM features:  95%|█████████▌| 8060/8455 [02:01<00:09, 41.19it/s]

Extracting GLCM features:  95%|█████████▌| 8065/8455 [02:01<00:09, 40.18it/s]

Extracting GLCM features:  95%|█████████▌| 8070/8455 [02:01<00:09, 40.23it/s]

Extracting GLCM features:  96%|█████████▌| 8075/8455 [02:01<00:09, 40.59it/s]

Extracting GLCM features:  96%|█████████▌| 8080/8455 [02:02<00:09, 40.40it/s]

Extracting GLCM features:  96%|█████████▌| 8085/8455 [02:02<00:09, 40.20it/s]

Extracting GLCM features:  96%|█████████▌| 8090/8455 [02:02<00:09, 37.53it/s]

Extracting GLCM features:  96%|█████████▌| 8094/8455 [02:02<00:09, 37.84it/s]

Extracting GLCM features:  96%|█████████▌| 8098/8455 [02:02<00:10, 34.55it/s]

Extracting GLCM features:  96%|█████████▌| 8102/8455 [02:02<00:10, 34.68it/s]

Extracting GLCM features:  96%|█████████▌| 8107/8455 [02:02<00:09, 36.83it/s]

Extracting GLCM features:  96%|█████████▌| 8112/8455 [02:02<00:08, 38.97it/s]

Extracting GLCM features:  96%|█████████▌| 8117/8455 [02:03<00:08, 40.88it/s]

Extracting GLCM features:  96%|█████████▌| 8122/8455 [02:03<00:08, 41.61it/s]

Extracting GLCM features:  96%|█████████▌| 8127/8455 [02:03<00:07, 42.37it/s]

Extracting GLCM features:  96%|█████████▌| 8132/8455 [02:03<00:07, 43.68it/s]

Extracting GLCM features:  96%|█████████▌| 8137/8455 [02:03<00:07, 44.20it/s]

Extracting GLCM features:  96%|█████████▋| 8142/8455 [02:03<00:07, 44.56it/s]

Extracting GLCM features:  96%|█████████▋| 8147/8455 [02:03<00:06, 45.29it/s]

Extracting GLCM features:  96%|█████████▋| 8152/8455 [02:03<00:06, 45.92it/s]

Extracting GLCM features:  96%|█████████▋| 8157/8455 [02:03<00:06, 45.76it/s]

Extracting GLCM features:  97%|█████████▋| 8162/8455 [02:04<00:06, 46.62it/s]

Extracting GLCM features:  97%|█████████▋| 8167/8455 [02:04<00:06, 44.11it/s]

Extracting GLCM features:  97%|█████████▋| 8172/8455 [02:04<00:06, 44.81it/s]

Extracting GLCM features:  97%|█████████▋| 8177/8455 [02:04<00:06, 44.57it/s]

Extracting GLCM features:  97%|█████████▋| 8182/8455 [02:04<00:06, 45.30it/s]

Extracting GLCM features:  97%|█████████▋| 8187/8455 [02:04<00:05, 45.74it/s]

Extracting GLCM features:  97%|█████████▋| 8192/8455 [02:04<00:05, 45.00it/s]

Extracting GLCM features:  97%|█████████▋| 8197/8455 [02:04<00:05, 43.32it/s]

Extracting GLCM features:  97%|█████████▋| 8202/8455 [02:04<00:06, 40.40it/s]

Extracting GLCM features:  97%|█████████▋| 8207/8455 [02:05<00:06, 38.10it/s]

Extracting GLCM features:  97%|█████████▋| 8212/8455 [02:05<00:05, 40.52it/s]

Extracting GLCM features:  97%|█████████▋| 8217/8455 [02:05<00:05, 41.20it/s]

Extracting GLCM features:  97%|█████████▋| 8222/8455 [02:05<00:05, 42.45it/s]

Extracting GLCM features:  97%|█████████▋| 8227/8455 [02:05<00:05, 42.79it/s]

Extracting GLCM features:  97%|█████████▋| 8232/8455 [02:05<00:05, 42.35it/s]

Extracting GLCM features:  97%|█████████▋| 8237/8455 [02:05<00:05, 41.93it/s]

Extracting GLCM features:  97%|█████████▋| 8242/8455 [02:05<00:05, 41.29it/s]

Extracting GLCM features:  98%|█████████▊| 8247/8455 [02:06<00:05, 40.55it/s]

Extracting GLCM features:  98%|█████████▊| 8252/8455 [02:06<00:04, 40.85it/s]

Extracting GLCM features:  98%|█████████▊| 8257/8455 [02:06<00:04, 42.25it/s]

Extracting GLCM features:  98%|█████████▊| 8262/8455 [02:06<00:04, 43.91it/s]

Extracting GLCM features:  98%|█████████▊| 8267/8455 [02:06<00:04, 40.11it/s]

Extracting GLCM features:  98%|█████████▊| 8272/8455 [02:06<00:04, 36.66it/s]

Extracting GLCM features:  98%|█████████▊| 8276/8455 [02:06<00:05, 35.15it/s]

Extracting GLCM features:  98%|█████████▊| 8280/8455 [02:06<00:05, 33.04it/s]

Extracting GLCM features:  98%|█████████▊| 8284/8455 [02:07<00:05, 33.10it/s]

Extracting GLCM features:  98%|█████████▊| 8288/8455 [02:07<00:05, 32.50it/s]

Extracting GLCM features:  98%|█████████▊| 8292/8455 [02:07<00:04, 32.78it/s]

Extracting GLCM features:  98%|█████████▊| 8296/8455 [02:07<00:04, 34.38it/s]

Extracting GLCM features:  98%|█████████▊| 8301/8455 [02:07<00:04, 36.58it/s]

Extracting GLCM features:  98%|█████████▊| 8306/8455 [02:07<00:03, 38.10it/s]

Extracting GLCM features:  98%|█████████▊| 8311/8455 [02:07<00:03, 39.23it/s]

Extracting GLCM features:  98%|█████████▊| 8315/8455 [02:07<00:03, 37.19it/s]

Extracting GLCM features:  98%|█████████▊| 8319/8455 [02:08<00:03, 35.44it/s]

Extracting GLCM features:  98%|█████████▊| 8323/8455 [02:08<00:04, 31.81it/s]

Extracting GLCM features:  98%|█████████▊| 8327/8455 [02:08<00:04, 30.18it/s]

Extracting GLCM features:  99%|█████████▊| 8331/8455 [02:08<00:03, 31.14it/s]

Extracting GLCM features:  99%|█████████▊| 8335/8455 [02:08<00:03, 32.88it/s]

Extracting GLCM features:  99%|█████████▊| 8339/8455 [02:08<00:03, 33.37it/s]

Extracting GLCM features:  99%|█████████▊| 8343/8455 [02:08<00:03, 33.75it/s]

Extracting GLCM features:  99%|█████████▊| 8347/8455 [02:08<00:03, 31.12it/s]

Extracting GLCM features:  99%|█████████▉| 8351/8455 [02:09<00:03, 32.94it/s]

Extracting GLCM features:  99%|█████████▉| 8355/8455 [02:09<00:02, 34.35it/s]

Extracting GLCM features:  99%|█████████▉| 8360/8455 [02:09<00:02, 36.56it/s]

Extracting GLCM features:  99%|█████████▉| 8364/8455 [02:09<00:02, 37.07it/s]

Extracting GLCM features:  99%|█████████▉| 8368/8455 [02:09<00:02, 37.44it/s]

Extracting GLCM features:  99%|█████████▉| 8372/8455 [02:09<00:02, 37.31it/s]

Extracting GLCM features:  99%|█████████▉| 8376/8455 [02:09<00:02, 35.48it/s]

Extracting GLCM features:  99%|█████████▉| 8380/8455 [02:09<00:02, 35.26it/s]

Extracting GLCM features:  99%|█████████▉| 8384/8455 [02:09<00:02, 35.10it/s]

Extracting GLCM features:  99%|█████████▉| 8388/8455 [02:10<00:01, 35.99it/s]

Extracting GLCM features:  99%|█████████▉| 8392/8455 [02:10<00:01, 36.56it/s]

Extracting GLCM features:  99%|█████████▉| 8396/8455 [02:10<00:01, 35.25it/s]

Extracting GLCM features:  99%|█████████▉| 8400/8455 [02:10<00:01, 32.81it/s]

Extracting GLCM features:  99%|█████████▉| 8404/8455 [02:10<00:01, 33.28it/s]

Extracting GLCM features:  99%|█████████▉| 8408/8455 [02:10<00:01, 34.35it/s]

Extracting GLCM features: 100%|█████████▉| 8413/8455 [02:10<00:01, 36.29it/s]

Extracting GLCM features: 100%|█████████▉| 8418/8455 [02:10<00:00, 37.95it/s]

Extracting GLCM features: 100%|█████████▉| 8423/8455 [02:11<00:00, 39.62it/s]

Extracting GLCM features: 100%|█████████▉| 8427/8455 [02:11<00:00, 37.03it/s]

Extracting GLCM features: 100%|█████████▉| 8431/8455 [02:11<00:00, 33.99it/s]

Extracting GLCM features: 100%|█████████▉| 8435/8455 [02:11<00:00, 32.34it/s]

Extracting GLCM features: 100%|█████████▉| 8440/8455 [02:11<00:00, 34.54it/s]

Extracting GLCM features: 100%|█████████▉| 8445/8455 [02:11<00:00, 37.99it/s]

Extracting GLCM features: 100%|█████████▉| 8450/8455 [02:11<00:00, 39.65it/s]

Extracting GLCM features: 100%|██████████| 8455/8455 [02:11<00:00, 40.35it/s]

Extracting GLCM features: 100%|██████████| 8455/8455 [02:11<00:00, 64.10it/s]

In [8]:
# Gabungkan semua fitur ke dalam satu DataFrame
dataTable = {
    'Filename': filenames,
    'Label': labels,
    # GLCM
    'Contrast0': Kontras0, 'Contrast45': Kontras45, 'Contrast90': Kontras90, 'Contrast135': Kontras135,
    'Homogeneity0': homogenity0, 'Homogeneity45': homogenity45, 'Homogeneity90': homogenity90, 'Homogeneity135': homogenity135,
    'Dissimilarity0': dissimilarity0, 'Dissimilarity45': dissimilarity45, 'Dissimilarity90': dissimilarity90, 'Dissimilarity135': dissimilarity135,
    'Entropy0': entropy0, 'Entropy45': entropy45, 'Entropy90': entropy90, 'Entropy135': entropy135,
    'ASM0': ASM0, 'ASM45': ASM45, 'ASM90': ASM90, 'ASM135': ASM135,
    'Energy0': energy0, 'Energy45': energy45, 'Energy90': energy90, 'Energy135': energy135,
    'Correlation0': correlation0, 'Correlation45': correlation45, 'Correlation90': correlation90, 'Correlation135': correlation135,
    # HSV Stats
    'HSV_H_Mean': h_means, 'HSV_H_Std': h_stds, 'HSV_H_Skew': h_skews, 'HSV_H_Kurt': h_kurts,
    'HSV_S_Mean': s_means, 'HSV_S_Std': s_stds, 'HSV_S_Skew': s_skews, 'HSV_S_Kurt': s_kurts,
    'HSV_V_Mean': v_means, 'HSV_V_Std': v_stds, 'HSV_V_Skew': v_skews, 'HSV_V_Kurt': v_kurts,
    # NRBR Stats
    'NRBR_Mean': nrbr_means, 'NRBR_Std': nrbr_stds, 'NRBR_Skew': nrbr_skews, 'NRBR_Kurt': nrbr_kurts,
}

# Tambahkan HSV Histograms
for b in range(16):
    dataTable[f'HSV_H_Hist_Bin_{b}'] = h_hists[:, b]
for b in range(8):
    dataTable[f'HSV_S_Hist_Bin_{b}'] = s_hists[:, b]
for b in range(8):
    dataTable[f'HSV_V_Hist_Bin_{b}'] = v_hists[:, b]

# Tambahkan NRBR Histograms
for b in range(16):
    dataTable[f'NRBR_Hist_Bin_{b}'] = nrbr_hists[:, b]

# Tambahkan LBP Histograms
for b in range(8):
    dataTable[f'LBP_Hist_Bin_{b}'] = lbp_hists[:, b]

df = pd.DataFrame(dataTable)
csv_path = f'hasil_ekstraksi_{EXPERIMENT_NAME}.csv'
df.to_csv(csv_path, index=False)
print(f'Fitur gabungan berhasil disimpan ke {csv_path}')
df.head()

Fitur gabungan berhasil disimpan ke hasil_ekstraksi_experiment7.csv

,Filename,Label,Contrast0,Contrast45,Contrast90,Contrast135,Homogeneity0,Homogeneity45,Homogeneity90,Homogeneity135,...,NRBR_Hist_Bin_14,NRBR_Hist_Bin_15,LBP_Hist_Bin_0,LBP_Hist_Bin_1,LBP_Hist_Bin_2,LBP_Hist_Bin_3,LBP_Hist_Bin_4,LBP_Hist_Bin_5,LBP_Hist_Bin_6,LBP_Hist_Bin_7
0,2_altocumulus_001371.jpg,altocumulus,40.775245,68.317693,53.069409,109.373610,0.444436,0.356638,0.414099,0.350389,...,0.0,0.0,0.005022,0.002074,0.000188,0.003516,0.002617,0.000249,0.003530,0.014054
1,2_altocumulus_000676.jpg,altocumulus,57.111765,131.910281,86.972273,147.136332,0.188943,0.126553,0.151879,0.121817,...,0.0,0.0,0.009438,0.003016,0.000186,0.003321,0.003275,0.000196,0.003170,0.008648
2,2_altocumulus_001452.jpg,altocumulus,44.792142,99.253749,58.116774,102.821561,0.227448,0.152434,0.205733,0.168055,...,0.0,0.0,0.008182,0.003631,0.000098,0.003468,0.003144,0.000110,0.003613,0.009005
3,2_altocumulus_000336.jpg,altocumulus,70.553171,148.056471,104.989844,190.781561,0.359902,0.279251,0.307238,0.252632,...,0.0,0.0,0.007486,0.002597,0.000213,0.003524,0.002735,0.000217,0.002612,0.011866
4,2_altocumulus_000201.jpg,altocumulus,34.986949,107.669988,93.377374,143.817178,0.290522,0.198616,0.221322,0.181443,...,0.0,0.0,0.010111,0.001965,0.000147,0.002636,0.002906,0.000167,0.003104,0.010213

## Train-Test Split & Normalization

In [9]:
# Pisahkan fitur dan label
X = df.drop(columns=['Filename', 'Label']).values
y = df['Label'].values

# Split 80/20 secara acak dan terstratifikasi
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Z-score Normalization (dengan epsilon 1e-8 untuk menghindari pembagian dengan nol)
mean_train = X_train.mean(axis=0)
std_train = X_train.std(axis=0)
X_train_norm = (X_train - mean_train) / (std_train + 1e-8)
X_test_norm = (X_test - mean_train) / (std_train + 1e-8)
print(f"Train shape: {X_train_norm.shape}")
print(f"Test shape: {X_test_norm.shape}")

Train shape: (6764, 100)
Test shape: (1691, 100)

## Classifiers Training & Evaluation

In [10]:
def evaluate_model(clf, X_tr, y_tr, X_ts, y_ts, name):
    clf.fit(X_tr, y_tr)
    y_pred_tr = clf.predict(X_tr)
    y_pred_ts = clf.predict(X_ts)
    
    print(f"\n====== {name} - Training Set ======")
    print(classification_report(y_tr, y_pred_tr, zero_division=0))
    print(f"Accuracy: {accuracy_score(y_tr, y_pred_tr):.4f}")
    
    print(f"\n====== {name} - Testing Set ======")
    print(classification_report(y_ts, y_pred_ts, zero_division=0))
    print(confusion_matrix(y_ts, y_pred_ts))
    print(f"Accuracy: {accuracy_score(y_ts, y_pred_ts):.4f}")
    return y_pred_ts

# Definisikan model dengan class_weight='balanced' untuk penanganan optimal jika ada minor imbalans
rf = RandomForestClassifier(n_estimators=150, random_state=42, class_weight='balanced')
svm = SVC(kernel='rbf', C=2.0, random_state=42, class_weight='balanced')
knn = KNeighborsClassifier(n_neighbors=5, weights='distance')

y_pred_rf_test = evaluate_model(rf, X_train_norm, y_train, X_test_norm, y_test, "Random Forest")
y_pred_svm_test = evaluate_model(svm, X_train_norm, y_train, X_test_norm, y_test, "SVM")
y_pred_knn_test = evaluate_model(knn, X_train_norm, y_train, X_test_norm, y_test, "KNN")

====== Random Forest - Training Set ======
               precision    recall  f1-score   support

  altocumulus       1.00      1.00      1.00      1000
       cirrus       1.00      1.00      1.00      1000
     clearsky       1.00      1.00      1.00      1000
 cumulonimbus       1.00      1.00      1.00      1000
      cumulus       1.00      1.00      1.00      1000
        mixed       1.00      1.00      1.00       764
stratocumulus       1.00      1.00      1.00      1000

     accuracy                           1.00      6764
    macro avg       1.00      1.00      1.00      6764
 weighted avg       1.00      1.00      1.00      6764

Accuracy: 1.0000

====== Random Forest - Testing Set ======
               precision    recall  f1-score   support

  altocumulus       0.80      0.87      0.84       250
       cirrus       0.75      0.69      0.72       250
     clearsky       0.93      0.97      0.95       250
 cumulonimbus       0.70      0.74      0.72       250
      cumulus       0.88      0.90      0.89       250
        mixed       0.67      0.63      0.65       191
stratocumulus       0.67      0.62      0.64       250

     accuracy                           0.78      1691
    macro avg       0.77      0.77      0.77      1691
 weighted avg       0.78      0.78      0.78      1691

[[218   7   0   6  10   8   1]
 [ 14 172   2   9   6  16  31]
 [  0   1 242   0   0   0   7]
 [  9   2   2 186   1  14  36]
 [  4   6   0   0 224  16   0]
 [ 22  15   0  17  14 121   2]
 [  4  26  15  46   0   5 154]]
Accuracy: 0.7788

====== SVM - Training Set ======
               precision    recall  f1-score   support

  altocumulus       0.89      0.87      0.88      1000
       cirrus       0.81      0.85      0.83      1000
     clearsky       0.96      0.98      0.97      1000
 cumulonimbus       0.87      0.83      0.85      1000
      cumulus       0.92      0.92      0.92      1000
        mixed       0.80      0.80      0.80       764
stratocumulus       0.81      0.81      0.81      1000

     accuracy                           0.87      6764
    macro avg       0.87      0.87      0.87      6764
 weighted avg       0.87      0.87      0.87      6764

Accuracy: 0.8674

====== SVM - Testing Set ======
               precision    recall  f1-score   support

  altocumulus       0.86      0.88      0.87       250
       cirrus       0.78      0.76      0.77       250
     clearsky       0.94      0.97      0.95       250
 cumulonimbus       0.70      0.80      0.75       250
      cumulus       0.89      0.88      0.88       250
        mixed       0.72      0.66      0.69       191
stratocumulus       0.70      0.63      0.66       250

     accuracy                           0.80      1691
    macro avg       0.80      0.80      0.80      1691
 weighted avg       0.80      0.80      0.80      1691

[[221   7   0   2   8  10   2]
 [  9 191   1   8   6  12  23]
 [  0   1 242   3   0   0   4]
 [  7   0   0 200   0   8  35]
 [  5   7   0   3 219  16   0]
 [ 11  15   0  22  13 127   3]
 [  3  23  15  48   0   4 157]]
Accuracy: 0.8025

====== KNN - Training Set ======
               precision    recall  f1-score   support

  altocumulus       1.00      1.00      1.00      1000
       cirrus       1.00      1.00      1.00      1000
     clearsky       1.00      1.00      1.00      1000
 cumulonimbus       1.00      1.00      1.00      1000
      cumulus       1.00      1.00      1.00      1000
        mixed       1.00      1.00      1.00       764
stratocumulus       1.00      1.00      1.00      1000

     accuracy                           1.00      6764
    macro avg       1.00      1.00      1.00      6764
 weighted avg       1.00      1.00      1.00      6764

Accuracy: 1.0000

====== KNN - Testing Set ======
               precision    recall  f1-score   support

  altocumulus       0.80      0.79      0.79       250
       cirrus       0.72      0.66      0.69       250
     clearsky       0.89      0.94      0.91       250
 cumulonimbus       0.65      0.73      0.69       250
      cumulus       0.84      0.88      0.86       250
        mixed       0.64      0.63      0.64       191
stratocumulus       0.67      0.58      0.62       250

     accuracy                           0.75      1691
    macro avg       0.74      0.74      0.74      1691
 weighted avg       0.75      0.75      0.75      1691

[[197   8   0   6  11  24   4]
 [ 11 165   8  18  10  17  21]
 [  0   8 236   3   1   0   2]
 [ 11   3   2 182   1  14  37]
 [  8   9   1   2 220  10   0]
 [ 14  14   0  19  16 121   7]
 [  6  23  19  51   4   2 145]]
Accuracy: 0.7487

## Save Experiment Metrics & Auto-update README

In [11]:
from pathlib import Path
METRICS_PATH = Path('../results/metrics.csv')
METRICS_PATH.parent.mkdir(parents=True, exist_ok=True)

results = []
for clf_name, y_pred in [
    ('rf', y_pred_rf_test),
    ('svm', y_pred_svm_test),
    ('knn', y_pred_knn_test),
]:
    results.append({
        'experiment_name': EXPERIMENT_NAME,
        'classifier': clf_name,
        'accuracy': accuracy_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred, average='weighted', zero_division=0),
        'recall': recall_score(y_test, y_pred, average='weighted', zero_division=0),
        'f1': f1_score(y_test, y_pred, average='weighted', zero_division=0),
    })

new_rows = pd.DataFrame(results)

if METRICS_PATH.exists() and METRICS_PATH.stat().st_size > 0:
    all_metrics = pd.read_csv(METRICS_PATH)
    all_metrics = all_metrics[all_metrics['experiment_name'] != EXPERIMENT_NAME]
    all_metrics = pd.concat([all_metrics, new_rows], ignore_index=True)
else:
    all_metrics = new_rows

all_metrics.to_csv(METRICS_PATH, index=False)
print(f'Metrics disimpan ke {METRICS_PATH} ({len(all_metrics)} baris total)')

# Jalankan script generate_metrics_table.py untuk memperbarui tabel hasil di README.md secara otomatis
import subprocess
try:
    subprocess.run(["python", "../src/generate_metrics_table.py"], check=True)
    print("README.md berhasil diperbarui dengan tabel hasil terbaru!")
except Exception as e:
    print(f"Peringatan: Gagal meng-update README.md: {e}")

all_metrics

Metrics disimpan ke ..\results\metrics.csv (24 baris total)

README.md berhasil diperbarui dengan tabel hasil terbaru!

   experiment_name classifier  accuracy  precision    recall        f1
0      experiment1         rf  0.821316   0.821657  0.821316  0.821135
1      experiment1        svm  0.787632   0.802315  0.787632  0.792130
2      experiment1        knn  0.782895   0.776283  0.782895  0.776533
3      experiment2         rf  0.829737   0.829593  0.829737  0.829322
4      experiment2        svm  0.793158   0.802144  0.793158  0.796048
5      experiment2        knn  0.780263   0.773187  0.780263  0.774127
6      experiment3         rf  0.655789   0.654693  0.655789  0.653106
7      experiment3        svm  0.609211   0.621162  0.609211  0.603450
8      experiment3        knn  0.621053   0.615394  0.621053  0.613233
9      experiment4         rf  0.832105   0.831199  0.832105  0.831413
10     experiment4        svm  0.791842   0.800839  0.791842  0.794697
11     experiment4        knn  0.776579   0.769591  0.776579  0.770272
12        baseline         rf  0.513897   0.514438  0.513897  0.513258
13        baseline        svm  0.498522   0.528703  0.498522  0.504854
14        baseline        knn  0.479598   0.479948  0.479598  0.477134
15     experiment5         rf  0.819042   0.818971  0.819042  0.818742
16     experiment5        svm  0.825547   0.826023  0.825547  0.825399
17     experiment5        knn  0.777646   0.779104  0.777646  0.776845
18     experiment6         rf  0.781786   0.780220  0.781786  0.779467
19     experiment6        svm  0.787700   0.786901  0.787700  0.786791
20     experiment6        knn  0.734477   0.731847  0.734477  0.731474
21     experiment7         rf  0.778829   0.775568  0.778829  0.776423
22     experiment7        svm  0.802484   0.801696  0.802484  0.801103
23     experiment7        knn  0.748669   0.746509  0.748669  0.746353

## Analisis Eksperimen 13 (Sequential: Experiment 7)

Silakan berikan ulasan analisis Anda di sini.